### PR TITLE
Update odl stable to v2.0.3

### PR DESCRIPTION
**Pull request by crycode-de**
Huge adapter rewrite with new features and some breaking changes.

* [Changelog](https://github.com/crycode-de/ioBroker.odl#changelog)
* [Forum testing thread](https://forum.iobroker.net/topic/53379/test-adapter-odl-umweltradioaktivit%C3%A4t-v2-0-x-latest)

### CODE REVIEW

**Comment by Apollon77** [comment]
SHould users be informed before update? We have the new Message feature where on upgrade a message box is shown and user can decide if he wants to continue or not ... ?!

**Comment by crycode-de** [comment]
@Apollon77 Just released v2.0.4 with the message added. Everything else is exactly like v2.0.3.

**Comment by Apollon77** [comment]
@crycode-de One tip: To mke sure all users see it you also need to add a globalDependency to Admin >= 5.1.28 (but no new version needed, just io-package on github should be enough before I merge :-)

**Comment by crycode-de** [comment]
@Apollon77 Done. Thank you for the tip 👍

**Pull request merged**
