### PR TITLE
Add net-tools to stable

### PR DESCRIPTION
**Pull request by Jey-Cee**

### CODE REVIEW

**Comment by Jey-Cee** [comment]
RE-CHECK

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.net-tools](https://github.com/jey-cee/ioBroker.net-tools)
[Downloads](https://www.npmjs.com/package/iobroker.net-tools) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.net-tools/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/jey-cee/ioBroker.net-tools/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/jey-cee/ioBroker.net-tools/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 Jey Cee <jey-cee@live.com>" at the end of [README.md](https://github.com/jey-cee/ioBroker.net-tools/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Jey Cee <jey-cee@live.com>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by Jey-Cee** [comment]
RE-CHECK

**Comment by Jey-Cee** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.net-tools](https://github.com/jey-cee/ioBroker.net-tools)
[Downloads](https://www.npmjs.com/package/iobroker.net-tools) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.net-tools/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@Jey-Cee no blocker, I merge but please update for next update :-)

**Comment by Jey-Cee** [comment]
Thx

**Pull request merged**
