### PR TITLE
add Warema WMS Webcontrol Pro

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.wmswebcontrol](https://github.com/TA2k/ioBroker.wmswebcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.wmswebcontrol) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.wmswebcontrol/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.wmswebcontrol)!. Please execute in adapter directory: `npm owner add bluefox iobroker.wmswebcontrol`
- [ ] :eyes: [W400] Cannot find "wmswebcontrol" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.wmswebcontrol](https://github.com/TA2k/ioBroker.wmswebcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.wmswebcontrol) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.wmswebcontrol/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.wmswebcontrol)!. Please execute in adapter directory: `npm owner add bluefox iobroker.wmswebcontrol`
- [ ] :eyes: [W400] Cannot find "wmswebcontrol" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

Review Feedback:

* Please update testing lib, else all your tests will fail
* Please set connecion state to false in unload :-)
* Translations missing for admin in words.js? https://github.com/TA2k/ioBroker.wmswebcontrol/blob/master/admin/words.js (please also check that for ford/nissan!)

Only last needs to be checked and pot fixed, rest optional

**Comment by TA2k** [comment]
Issues fixed

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.wmswebcontrol](https://github.com/TA2k/ioBroker.wmswebcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.wmswebcontrol) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.wmswebcontrol/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "wmswebcontrol" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Thank you, then please poke again after changes are oin npm :-)

**Comment by TA2k** [comment]
done

**Comment by ldittmar81** [comment]
@Apollon77 - here ist all done or is there another question? Should be changed to Adapter review needed...

**Pull request merged**
