### PR TITLE
Add mempool-space to latest

### PR DESCRIPTION
**Pull request by Hans-Wurst-21**
Please add my adapter ioBroker.mempool-space to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
reminder 24.11.2024

**Comment by simatec** [comment]
jsonConfig looks good ;)

**Comment by mcm1957** [comment]
@Hans-Wurst-21 

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] some labels seem obsolete
  
  labels 'option1' and 'option2' could be delegted from i18n files. (non blocking remark)  

- [ ] consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- [ ] linter setup

  Please use standard iobroker linter setup. This is located at @iobroker/eslint-config. See migration guide at https://github.com/ioBroker/ioBroker.eslint-config/blob/main/MIGRATION.md
  
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
As the noted remarks are minimal and non blocking, I would ask to review / check / fix them with the next release. I will release tot adapter anyway.

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Comment by Hans-Wurst-21** [comment]
@mcm1957 
I have accepted your comments and changed it to v.0.0.4.
Please look over the code again if you like.

**Pull request merged**
