### PR TITLE
Bumped Miele CloudService to Version 2.0.3 in stable and added dysonAirPurifier to latest

### PR DESCRIPTION
**Pull request by Grizzelbee**
* Bumped Miele CloudService to Version 2.0.3 in stable, Miele CloudService contains some minor bugfixes

* Added new Adapter dysonAirPurifier to latest, complete new development.

### CODE REVIEW

**Comment by Apollon77** [comment]
Mixing a Stable and an other first adaper for stable is not that great idea ... - new adapters get review and such ... so it gets delayed

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.

### [ioBroker.dysonairpurifier](https://github.com/Grizzelbee/ioBroker.dysonairpurifier)
[Downloads](https://www.npmjs.com/package/iobroker.dysonairpurifier) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.dysonairpurifier/)

- [ ] :heavy_exclamation_mark: [E112] extIcon must be the same as an icon but with github path
- [ ] :eyes: [W400] Cannot find "dysonairpurifier" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Grizzelbee** [comment]
@Apollon77 
> Mixing a Stable and an other first adaper for stable is not that great idea ... - new adapters get review and such ... so it gets delayed
Thats the point I'm totally aware of. 
The point I wasn't aware of is, that merging such pull requests (same project but different files on different days) is a feature of git.

But delaying the update of Miele-Adapter wouldn't do any harm. ;)

May you please check the adapter-checker mentions manually? In my opinion these are false positives.

**Comment by Grizzelbee** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.

### [ioBroker.dysonairpurifier](https://github.com/Grizzelbee/ioBroker.dysonairpurifier)
[Downloads](https://www.npmjs.com/package/iobroker.dysonairpurifier) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.dysonairpurifier/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.dysonairpurifier) are broken. Please fix.
- [ ] :eyes: [W400] Cannot find "dysonairpurifier" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Grizzelbee** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.dysonairpurifier](https://github.com/Grizzelbee/ioBroker.dysonairpurifier)
[Downloads](https://www.npmjs.com/package/iobroker.dysonairpurifier) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.dysonairpurifier/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "dysonairpurifier" in latest repository

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Grizzelbee** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.

### [ioBroker.dysonairpurifier](https://github.com/Grizzelbee/ioBroker.dysonairpurifier)
[Downloads](https://www.npmjs.com/package/iobroker.dysonairpurifier) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.dysonairpurifier/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "dysonairpurifier" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Grizzelbee** [comment]
Everything is fixed. May I ask for an update?

**Comment by Apollon77** [comment]
Hi, sorry for the delay. Here my review comments:
* really materializeTab=true? (io-package)
* with adapter-core 2.4.0 as dep you need to require at least js.controller 2.0.0
* if you want think about using the new automatic encrypt/decrypt feature of controller 3.x
* you should do the setState in the callback of set/extendObject
* please make sure to clear all running timiuts and intervals in "unload" (e.g. https://github.com/Grizzelbee/ioBroker.dysonairpurifier/blob/master/main.js#L588) - i know that you do thet in the "In close" handlers ... can we rely on them 100% ;-)

Thank you for checking and adjusting

**Comment by Apollon77** [comment]
PS: is the index 4 in the table at beginning the role of objects? If yes please make sure to ONLY use defined roles! Do not invest new ones :-)

**Comment by Grizzelbee** [comment]
Requested changes on dyson-adapter haven been applied to v0.7.0 which is online now

**Comment by Grizzelbee** [comment]
RE-CHECK

**Comment by Grizzelbee** [comment]
The dyson Adapter implements Adapter request 186 ( [https://github.com/ioBroker/AdapterRequests/issues/186](https://github.com/ioBroker/AdapterRequests/issues/186) )

**Comment by Apollon77** [comment]
@Grizzelbee Hey, and sorry for the late review. I have some comments:
* please check the used roles ... "state.power" is not defined, as example
* also "states" is formally only defined for number state types (but it basically fworks also for strings by chance...)
* Note: await ....then is an anto pattern ... use one or the other (https://github.com/Grizzelbee/ioBroker.dysonairpurifier/blob/master/main.js#L330 as examle, but also others)
* please encrypt the password!! see best practices in Readme her ein repo for infos and example
* when I see the code correct you always call extendObject also if nothing changed, correct? basicylly an adapter should onwly do that when changes are to be expected (os maybe on first run) and after that only setState ... else it generates lot of unneeded object changes).
Please have a look at the review comments and adjust

**Comment by Grizzelbee** [comment]
@Apollon77 : Next iteration. ;) 
Tried to fix all your comments and pretty shure I hit all.

**Comment by Apollon77** [comment]
Hm ... you should do all the object creates async and await them in your asnyc method e.g. https://github.com/Grizzelbee/ioBroker.dysonairpurifier/blob/master/main.js#L205 ... else they run all in parallel

**Comment by Apollon77** [comment]
PS: you still need to have Password key also in "native". And best also add "protectedNative" with Password as key (same es encrsptedNative) to prevent access to that key from object readers

**Comment by Grizzelbee** [comment]
Okay. Let's see whether I hit it with the next attempt... v0.7.3

**Comment by Grizzelbee** [comment]
Adapter is working again.

**Pull request merged**
