### PR TITLE
pix (6 adapters updated)

### PR DESCRIPTION
**Pull request by Pix---**
tankerkoenig, feiertage, homepilot, tvspielfilm, solarwetter, epson_stylus_px830

### CODE REVIEW

**Comment by Apollon77** [comment]
I fixed all conflicts ... please check ... and there are nly 3 updated adapters in the PR?!

**Comment by GermanBluefox** [comment]
:(
image

**Comment by GermanBluefox** [comment]
image

**Comment by GermanBluefox** [comment]
image

**Comment by Apollon77** [comment]
@Pix--- wie machen wir hier weiter?

**Comment by Pix---** [comment]
Bluefox added as owner in mentioned adapters. Obsolete node_modules deleted.

**Comment by Apollon77** [comment]
why closed?

**Comment by Pix---** [comment]
sorry, thought it was my account

**Comment by Apollon77** [comment]
How we proceed here?

**Comment by GermanBluefox** [comment]
Merge

**Pull request merged**
