### PR TITLE
Add smartcontrol to Latest

### PR DESCRIPTION
**Pull request by Mic-M**
Github: https://github.com/Mic-M/ioBroker.smartcontrol
Forum: [Threads tagged with smartcontrol](https://forum.iobroker.net/tags/smartcontrol) | [Current thread](https://forum.iobroker.net/topic/36750/test-adapter-smartcontrol-0-3-x-github-ab-12-09-20?page=1) | [Splash Page](https://forum.iobroker.net/topic/36728/smart-control-adapter-splash-page)

Please review and add to Latest. A couple of comments, since I recently initiated discussions related to i18n and documentation, which were also related to this adapter, so this adapter is kind of a "hot iron" 😄 , but now it should meet all conventions and also providing a great usability for our users ;-)
  * Compact Mode successfully checked
  * https://adapter-check.iobroker.in/ looks good.
  * All 10 required translations are implemented via gulp (admin/i18n -> words.js).
  * Adapter documentation is available in English and German, both on [Github](https://github.com/Mic-M/ioBroker.smartcontrol#instructions) and also embedded within the adapter configuration. If user's language setting is not English (en), the code checks `admin/doc-md/` folder for existence of local language. If not there, English is the fallback, plus a note note (italic, blue text "Your current ioBroker language is ...") to encourage users helping in translating into their languages. Currently I have English and German as documentation.
image

Thank you!

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.smartcontrol](https://github.com/Mic-M/ioBroker.smartcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.smartcontrol) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.smartcontrol/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "smartcontrol" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
welcome

**Comment by Mic-M** [comment]
Awesome :sunglasses:
Thanks!

**Pull request merged**
