### PR TITLE
Bump iwg-vpn to 2.0.5 at stable

### PR DESCRIPTION
**Pull request by iwg-vpn**

### CODE REVIEW

**Comment by mcm1957** [comment]
Your adapter https://github.com/iwg-vpn/ioBroker.iwg-vpn does not use standard iobroker testing.

Please see requirements https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository which is also required for stable repository.

```
Adapter needs to have at least Adapter basic testing (installing, running) using GitHub actions. More information in forum from apollon77 (Just take from other adapters the samples)
```

You may copy the ```test-and-release.yml``` workflow from the example adapter or newly created adapter. If you need help, please let uas know.

If you need any help setting up standard testing and / or if you prefer a that we / I create a PR to fix this please let us know.

**Please add a comment when you have reviewed and fixed the suggestion or at least commented the suggestions and you think the adapter is ready for a re-review**

NOTE: No new release is required as long as standard test pass. It's ok to disable lint for the first time as linter might require quality changes which are not required at high priority. It's sufficient to enable lint with standard setupo for the next release. But standard node tests for nod 16/18/20 are mandatory

**Comment by iwg-vpn** [comment]
test-and-release.yml was added

**Comment by mcm1957** [comment]
2.0.5 created 17.10.2023

**Comment by mcm1957** [comment]
2.0.5 created 17.10.2023
12 user (4%)
OK

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@iwg-vpn 

Please honor version numbering for the next release:
```
objects API introduced
```
for sure is not only a bug fix but introduces a new feature. So this release should have been a minor release (at least)

increase patch version for releases including fixes only, but do not provide new features and are not breaking
increase minor version for releases including new feature (may contain bugfixes)
increase major version for releases including breaking changes ('something incompatible')

Thanks in advance

(This remark does not blcok 2.0.5 to be released at stable for now)

**Pull request merged**
