### PR TITLE
Add selveRF to latest

### PR DESCRIPTION
**Pull request by Rintrium**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.froeling](https://github.com/TA2k/ioBroker.froeling)
[Downloads](https://www.npmjs.com/package/iobroker.froeling) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.froeling/)

:thumbsup: No errors found

### [ioBroker.lg-thinq](https://github.com/TA2k/ioBroker.lg-thinq)
[Downloads](https://www.npmjs.com/package/iobroker.lg-thinq) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-thinq/)

:thumbsup: No errors found

### [ioBroker.openhab](https://github.com/iobroker-community-adapters/ioBroker.openhab)
[Downloads](https://www.npmjs.com/package/iobroker.openhab) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.openhab/)

- [ ] :heavy_exclamation_mark: [E104] No common.titleLang found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.openhab) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2017-2022 bluefox <dogafox@gmail.com>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2017-2022 bluefox <dogafox@gmail.com>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.rainbird](https://github.com/StrathCole/ioBroker.rainbird)
[Downloads](https://www.npmjs.com/package/iobroker.rainbird) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.rainbird/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/StrathCole/ioBroker.rainbird/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/StrathCole/ioBroker.rainbird/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 Marius Burkard <m.burkard@pixcept.de>" at the end of [README.md](https://github.com/StrathCole/ioBroker.rainbird/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Marius Burkard <m.burkard@pixcept.de>" at the start of LICENSE

### [ioBroker.selverf](https://github.com/Rintrium/ioBroker.selverf)
[Downloads](https://www.npmjs.com/package/iobroker.selverf) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.selverf/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 Rintrium <main@rintrium.de>" at the end of [README.md](https://github.com/Rintrium/ioBroker.selverf/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Rintrium <main@rintrium.de>" at the start of LICENSE
- [ ] :eyes: [W400] Cannot find "selverf" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Rintrium** [comment]
Added 2022 to License and Readme.md

**Comment by ldittmar81** [comment]
@Apollon77 all error fixed. Adapter-Review needed

**Comment by ldittmar81** [comment]
Close https://github.com/ioBroker/AdapterRequests/issues/308 after review

**Comment by Apollon77** [comment]
Hi, here some review comments:
* Please also add the channel object in https://github.com/Rintrium/ioBroker.selverf/blob/master/io-package.json#L291
* you do not need https://github.com/Rintrium/ioBroker.selverf/blob/master/main.js#L42-L53 ... already in io-package
* Please make sure when settings timeouts that yoiu clear a pot already set one (if this is relevant e.g. for this.connectionTimeout)

Rest is looking good. Please check and adjust

**Comment by Rintrium** [comment]
I added the channel object and removed the unnecessary code in main.js. I also rechecked the used timeouts and did not find any obvious missing clearTimeouts (clearTimeout is only missing, when the function that is executed was called by the timeout).

If my changes look ok, I will publish a new version and would like to add that version to the stable repository if that's ok. There weren't any functional changes and I got positive feedback for version 0.5.3 (and I'm also using it since release).

**Comment by Apollon77** [comment]
All good. please release and I'm havve to merge here. Thank you for the checka dn adjustments! Just poke here when npm publish is done

**Comment by Rintrium** [comment]
I made the necessary changes and pushed version 0.6.1 to npm and github. The release script threw an error for version 0.6.0 so I had to repeat and bump the version number to 0.6.1. All checks are passing.

**Pull request merged**
