### PR TITLE
add un2000-modbus adapter

### PR DESCRIPTION
**Pull request by daolis**

### CODE REVIEW

**Comment by mcm1957** [comment]
@daolis 
Did you close this request intentionally or was it an error?

**Comment by daolis** [comment]
> @daolis Did you close this request intentionally or was it an error?

Thought there is something wrong, because of the `ioBroker.bosesoundtouch` and `ioBroker.sonnen-charger` checks here.
But it looks like the `addToLatest` call did some re-sorting and intention changes too.
And i dont get the [E201] issue in `ioBroker.sun2000-modbus` checks. I dont have `Bluefox` somewhere mentionned in my repo...

And already deleted the forked repo, to use the Web version to add it, but there i get the Bluefox issue too. :disappointed:

**Comment by daolis** [comment]
Ahh, i checked other adapters on npm, and bluefox is everywhere...
Why its necessary to add bluefox to every npm repo as owner?!

**Comment by mcm1957** [comment]
You did not use www.iobroker.dev to create the PR but used an old fork whiuch is not in sync.

I suggest to use www.iobroker.dev - adapter - release to request an PR
If this does not work, feel free to use addToLatest which is somehow older. I will sort out additonal modules - no problem.

E201 miuts be fixed as described in the error message. You MUST send en npm invite to him. see https://github.com/ioBroker/ioBroker.repositories#add-an-owner-to-a-packet. This is required to avoid stale adapters.

**Comment by daolis** [comment]
Yes, i didn't use www.iobrioker.dev at the beginning.
But i used the following...
 From DOC: https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository
 To https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository
And i foolowed these steps: Fork, npn, add, PR...
(End this repos were not out of sync, because i created the fork today...)

If this is an outdated procedure, the maybe the doc, readme should be updated.

About the stale repos: Ok, got it, will send an invite.
Thanks

**Comment by mcm1957** [comment]
> @mcm1957 Correct, i didn't use [www.iobrioker.dev](http://www.iobrioker.dev) at the beginning. But i used the following... From DOC: https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository To https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository And i followed these steps: Fork, npn, add, PR... (And this repos was not out of sync (from the fork point of view), because i created the fork today...)
> 
> If this is an outdated procedure, then maybe the doc, readme should be updated.
> 
> About the stale repos: Ok, got it, will send an invite. Thanks

doc is not outdated - only an older more manual way. The web interface is described 5 lines below:
https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository-web-frontend

Anyway -
**Please open a new PR as this PR cannot be reopend any more.**

**Comment by daolis** [comment]
@mcm1957 ok, thanks.
Will use the web version now, but have to wait until bluefox accepted the npm invitaion.

**Pull request closed without merging**
