### PR TITLE
Added Energiefluss Adapter

### PR DESCRIPTION
**Pull request by SKB-CGN**
Hi,
please add the "Energiefluss"-Adapter to ioBroker.

Thanks!

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.energiefluss](https://github.com/SKB-CGN/ioBroker.energiefluss)
[Downloads](https://www.npmjs.com/package/iobroker.energiefluss) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.energiefluss/)

- [ ] :heavy_exclamation_mark: [E160] "admin" is not allowed in common.dependencies
- [ ] :heavy_exclamation_mark: [E154] common.dependencies must contain [{"js-controller": ">=2.0.0"}] or later - recommended: [{"js-controller": ">=3.3.22"}]
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E518] "@alcalzone/release-script" is used, but ".releaseconfig.json" not found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W172] "common.localLink" in [io-package.json](https://github.com/SKB-CGN/ioBroker.energiefluss/blob/master/io-package.json) is deprecated. Please define object "common.localLinks": { "_default": "..." }
- [ ] :eyes: [W400] Cannot find "energiefluss" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by SKB-CGN** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.energiefluss](https://github.com/SKB-CGN/ioBroker.energiefluss)
[Downloads](https://www.npmjs.com/package/iobroker.energiefluss) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.energiefluss/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E518] "@alcalzone/release-script" is used, but ".releaseconfig.json" not found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "energiefluss" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by SKB-CGN** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.energiefluss](https://github.com/SKB-CGN/ioBroker.energiefluss)
[Downloads](https://www.npmjs.com/package/iobroker.energiefluss) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.energiefluss/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "energiefluss" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.energiefluss](https://github.com/SKB-CGN/ioBroker.energiefluss)
[Downloads](https://www.npmjs.com/package/iobroker.energiefluss) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.energiefluss/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "energiefluss" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.energiefluss](https://github.com/SKB-CGN/ioBroker.energiefluss)
[Downloads](https://www.npmjs.com/package/iobroker.energiefluss) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.energiefluss/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "energiefluss" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
Please remove node 14 from test-and-release.yml, add node 18 and (optionally) add node 20 to testing matrix.
Node 14 is no longer supported and tests will fail since 22.5.2023.

Thanks
McM1957

**Comment by SKB-CGN** [comment]
Added nNode 18 as default and testing for 16, 18 and 20.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
As this adapter is no longer maintained according to README.md (https://github.com/SKB-CGN/ioBroker.energiefluss#note) this PR will be closed.

Please feel free to open a new PR whenever yoju continue to maintain this adapter or a followup adapter seems to be ready for lates.

And please excuse the very long processing delay. We are working to fix this problem, new PRs should at leest get an review within one week.

Hope you continue to use and support ioBroker
and THANK YOU VERY MUCH for spending your time for ioBroker !

**Comment by mcm1957** [comment]
As this adapter is no longer maintained there seems to be no reason to add it to any repository.
Or did I understand you note at README stating that the adapter is mo longer maintained in a wrong way ?

https://github.com/SKB-CGN/ioBroker.energiefluss#note

Of course I could reactivate the PR but this makes only sense for an adapter which is maintained in the future too.
Please indicate your future plans

**Comment by SKB-CGN** [comment]
The adapter is completed as it is because it reached the maximum configuration phase it could handle.

Therefore it is not 'given up'. It's finished like it is.

The 'erweitert' version is the next generation of this adapter in a complete different configuration and layout.

Both adapters are fully working!

**Comment by SKB-CGN** [comment]
Hi,
i have removed german language from README and created new files inside docs.

The Adapter displays values, which can also come from javascript and/or alias states, which are mostly created by the users and they do not care about the ACK flag.
Therefore, the adapters reacts on non-ack flags as well.

Please check the adapter and add it.

Thank you!

**Comment by mcm1957** [comment]
As you state by youself, correct ahndling of onStateChange ist stillmissing:

**Comment by SKB-CGN** [comment]
Thanks for replying.

What's the opinion of @Apollon77 here?

As some other developers told me, they either do **not** react on the ack true flag in 'javascript.*.' or '0_userdata.*.' or 'alias.*.'

What's now the correct or most common way?

**Comment by SKB-CGN** [comment]
@Apollon77 

Sure, that's the fact I fully understand.

But this adapter is not 'dependent' on the values of other adapters or so, as it displays their values or works/calculates with them.

Most of the time, those values are user calculated via their own scripts.

I mean, it's not a problem, to only read and react on ack-true ones, but there need to be a 'coding law' for that, as I implemented that also in another adapter, which was directly fighted against because it was only reacting on ack-true and the users forgot to set their own ack-true.

@arteck was describing that as well.

Perhaps, there needs to be a defined rule.

**Comment by Apollon77** [comment]
For adapters this is all defined ... The "problem" comes when users write own scripts for own stuff ... They do not know (nor understand) this and so they do whatever they want and they do not care if ack is true or false because they "just" want to store a value :-) 

So for you as adapter that uses user defined states you have three options:
A) just react on anything irrelevant of ack flag for such user generated states
B) tell the users how they need to set their states in ortder for the adapetr to use the values and then you can say "I only react on ack=true" ... and yes this will be a "customer support pain"
C) make it configurable (which is the developer pain - and users still need to understand it) ... :-)

Sorry bit exactly in this area it is very hard to have a "rule" for the users to follow that you can rely on

**Comment by mcm1957** [comment]
I've discussed ack handling with Apollon77 again. As Apollon77 already stated the following rules apply

- OWN states MUST correctly handle ack flag; so own states used as input to the adapter must check ack=false.
- FOREIGN states should check ack flag. But this is not always possible while comfiorting users, especially 0_userdata_0 states will likely be written with all possible values :-(. So its OK for adapter to check ack flag for foreign states depending on its needs.

As a summary - as you seem to use only foreign states as input (and no own 'command / control / input' states) ack handling is ok as it is.

**Comment by SKB-CGN** [comment]
Sure, understand.

What about the following:

I will only allow 0_userdata, alias and JavaScript to be ack-false and react on them as well as for foreign states from other adapters which produce ack-true.

I think that will make sense to act on ack-true for all adapters in the proper way and to act on 'user-environment' states, which could be ack-false.

What do you think about that?

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If another testing topic already exists, ist OK to continue using this topic too.

**Comment by mcm1957** [comment]
> Sure, understand.
> 
> What about the following:
> 
> I will only allow 0_userdata, alias and JavaScript to be ack-false and react on them as well as for foreign states from other adapters which produce ack-true.
> 
> I think that will make sense to act on ack-true for all adapters in the proper way and to act on 'user-environment' states, which could be ack-false.
> 
> What do you think about that?

That would be a very good and constructive solution as 'normal users' should only write to states at this location.
Most likely no (good) adapter should write output values without ack. So there is no real reason to encounter problems there.

I've released the adapter anyway to latest. Please register an issue and handle it whenever you have time to do.

THANKS for your work and constructive cooperation

**Comment by Apollon77** [comment]
@SKB-CGN this is a great idea. maybe also add node-red and mqtt as other "allowed strange ack flags" :-)

**Pull request merged**
