### PR TITLE
Add ecoflow to latest

### PR DESCRIPTION
**Pull request by Newan**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.ecoflow](https://github.com/Newan/ioBroker.ecoflow)
[Downloads](https://www.npmjs.com/package/iobroker.ecoflow) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.ecoflow/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "ecoflow" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

thank you for your submission and here are some review comments:
* It seems that some states are incorrectly defined, see your testing results: https://github.com/Newan/ioBroker.ecoflow/actions/runs/3013617524/jobs/4842974462#step:2:520 ... you should set "def" values matching the defined datatype :-)
* makes it sense to encrypt the secretkey? Can be handled automatically ... just defined as nativeEncrypted (see best practices)
* please also create channels (info/status) for your static objects
* i think you have a bnad typo in your deps ... https://github.com/Newan/ioBroker.ecoflow/blob/main/package.json#L20 ... this should be "axios" or? ;-)
* The release script will not work as it is right now because when using v3 syou need another plugin dep and a config file. see the v3 changelog off release script
* you should set a timeout for the external communication which is always lower then your interval (or not use an interval at all - see best practices, but also then a timeout is a good idea)

Thank you for checking and adjusting,

Ingo

**Comment by Newan** [comment]
fixed

**Comment by Newan** [comment]
> Re-Review done. Please release the new version :-) Then I can merge.

New Version released

**Pull request merged**
