### PR TITLE
Add amtronwallbox to latest

### PR DESCRIPTION
**Pull request by rg-engineering**
Please add my adapter ioBroker.amtronwallbox to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
Related 
https://github.com/ioBroker/ioBroker.repositories/pulls?q=is%3Apr+amtronwallbox+is%3Aclosed

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- [ ] Readme.md should contain a link to the manufacturer and/or device

  The README.md of any adapter related to device or m ultiple devices of a manufacturer should contain a link the manufacturers website and/or to a description of the device. This is to anable new users to easily check wether they associate the adapter with the correct device(s). (See https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository paragraph 4.)

- [ ] adapter requires node 16

  Due to usage of adaptercore 3.x.x this adapter requires node 16 or newer. Please merge PR https://github.com/rg-engineering/ioBroker.amtronwallbox/pull/74 to add engines requirement to package.json.  

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please do not use general roles (like state, or value) only if no dedicated role is available.

- [ ] axios requires timeouts

  Please verify that you set a timeout at all axios calls. At least here (https://github.com/rg-engineering/ioBroker.amtronwallbox/blob/693e36944ae8173a360d57dd84ade94fed42aad3/main.js#L184) it seems to be missing. Axios defaults to "no timeout" which could case hanging adapters.

- [ ] adapter uses sentry

  As this adapter uses sentry evaluate whether you want to enble creating a sentry release  during deploy by uncommengting the relevant section: https://github.com/rg-engineering/ioBroker.amtronwallbox/blob/693e36944ae8173a360d57dd84ade94fed42aad3/.github/workflows/test-and-release.yml#L70 (only info, no blocking point)

  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by rg-engineering** [comment]
@mcm1957 with version 0.2.8 I've changed:
* link to amtron wallboxes added in readme
* check of node > 16 in package.json
* state roles overworked as good as I'm able to do (some states of adapter does not really match to iob spec)
* timeouts for axios configured

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
ok

**Pull request merged**
