### PR TITLE
Add ioBroker.residents to latest repo

### PR DESCRIPTION
**Pull request by jpawlowski**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.residents](https://github.com/jpawlowski/ioBroker.residents)
[Downloads](https://www.npmjs.com/package/iobroker.residents) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.residents/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by jpawlowski** [comment]
Anything expected of you that I should do?

**Comment by Apollon77** [comment]
I'm about to treview soon

**Comment by Apollon77** [comment]
Hi,

here my review results.

* Please do not invent own roles (e.g. https://github.com/jpawlowski/ioBroker.residents/blob/main/io-package.json#L319). Ue the defined list or open an issue in ioBoker repo for new role addition discussion

Please adjust this ajd we are ready for repository. :-)

Another note:
One additional top for "potentially long running timers (e.g. disableAbsentResidentsDailyTimer) ... The maximum "timeout" you can set is 2147483647ms ... this is max 24days ... Any hight value will trigger the timout immediately(!!) aka 0 ... you maybe shoukd consider this ... some absences can be longer then 24days

**Comment by jpawlowski** [comment]
> * Please do not invent own roles (e.g. https://github.com/jpawlowski/ioBroker.residents/blob/main/io-package.json#L319). Ue the defined list or open an issue in ioBoker repo for new role addition discussion
> 
> Please adjust this ajd we are ready for repository. :-)

@Apollon77 done by referenced commits and published in [v0.0.3-beta.12](https://github.com/jpawlowski/ioBroker.residents/releases/tag/v0.0.3-beta.12), please proceed 😀

> Another note: One additional top for "potentially long running timers (e.g. disableAbsentResidentsDailyTimer) ... The maximum "timeout" you can set is 2147483647ms ... this is max 24days ... Any hight value will trigger the timout immediately(!!) aka 0 ... you maybe shoukd consider this ... some absences can be longer then 24days

The timers are designed to never have more than 24 hours(!), not days. They use a value by the hour of the day, e.g. a time from 00:00:00 till 23:59:59.
The idea is to always set the absence status from short absence to long absence as soon as possible, to also have corresponding savings measures as quickly as possible. If none of the residents have stayed overnight, the day just starting will thus start in extended absence mode and will not operate in "nearby mode" again until someone either comes home or an event for going home is sent/triggered.

**Comment by jpawlowski** [comment]
Anything else?

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.residents](https://github.com/jpawlowski/ioBroker.residents)
[Downloads](https://www.npmjs.com/package/iobroker.residents) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.residents/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "residents" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jpawlowski** [comment]
> 👍 No errors found

😊

> * [ ]  👀 [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI

React is being used as complex configuration options and flexibility is required.

> * [ ]  👀 [W400] Cannot find "residents" in latest repository

Hey, Captain Obvious, you don't say 😅

**Comment by jpawlowski** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.residents](https://github.com/jpawlowski/ioBroker.residents)
[Downloads](https://www.npmjs.com/package/iobroker.residents) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.residents/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "residents" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jpawlowski** [comment]
I am a little lost here.

What should I do to move this issue forward?

**Comment by mcm1957** [comment]
@jpawlowski 
As far as I can see there's nothing to do for you at the moment.  @Apollon77  marked this PR with "Adapter Review needed" last week. I'm sure he is aware of this and will üperform the review as soon as he has time for it. Your adapter is not the only one waiting for a review. So please stand by.

Please note that a deeper review is only performed when adding an adapter initially. Later updates to stabel are normally release within a few days, upodates to latest are release automatically twice a day for adapters already contained in repository.

Thanks for your work and the time you spend for ioBroker.

**Comment by Apollon77** [comment]
Yes I need to find time .... will hopefully have soon

**Comment by jpawlowski** [comment]
Alright, understood!

This

> Please adjust this ajd we are ready for repository. :-)

sounded like all the checks had already been completed.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.residents](https://github.com/jpawlowski/ioBroker.residents)
[Downloads](https://www.npmjs.com/package/iobroker.residents) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.residents/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "residents" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.residents](https://github.com/jpawlowski/ioBroker.residents)
[Downloads](https://www.npmjs.com/package/iobroker.residents) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.residents/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "residents" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
Re-Review
- no unsupported roles deteted 
- timer limits have been explained by dev

**OK - lets go**

**Pull request merged**
