### PR TITLE
Added awtrix-light to stable, updated stable version of pvforecast, youtube

### PR DESCRIPTION
**Pull request by klein0r**

### CODE REVIEW

**Comment by mcm1957** [comment]
Just for future PRs:

Please submit seperated PRs for each update if possible.

Especially new at stable is processed a little bit different and an issue / question for one adapter would block all.

**Comment by klein0r** [comment]
> Please submit seperated PRs for each update if possible.

Do you know if the dev portal creates a new pranch and pr automatically for each version bump?

**Comment by mcm1957** [comment]
youtube:
4.3.0 created 28.08.2023
22 user (5%)
OK

**Comment by mcm1957** [comment]
> > Please submit seperated PRs for each update if possible.
> 
> Do you know if the dev portal creates a new pranch and pr automatically for each version bump?

As far as I know YES.
In addition future "reminder issues" will provide a direct link to the dev portal and your adapter

**Comment by mcm1957** [comment]
Newer issues contain such a link already, i.e. your youtube rimnder ('click to use developer portal')

image

**Pull request merged**
