### PR TITLE
Neuer Adapter ems-esp

### PR DESCRIPTION
**Pull request by tp1de**
Nach einem halben Jahr im produktiven Einsatz möchte ich den Adapter ins Repository aufnehmen lassen.
https://forum.iobroker.net/topic/45862

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by tp1de** [comment]
> RE-CHECK!

What shall I re-check?

**Comment by Apollon77** [comment]
No, normally a bot should do something :-))

BTW: Can you please redo/update the PR and sort in yur adapter entry alphabetically?

**Comment by Apollon77** [comment]
And please also use https://adapter-check.iobroker.in/ to check your adapter ... there are some issues that needs to be fixed!

**Comment by tp1de** [comment]
@Apollon77  I hope everything is ok now ...

**Comment by tp1de** [comment]
RE-CHECK

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
@tp1de I get this from adapter checker ..
Bildschirmfoto 2021-12-29 um 13 05 27
.

**Comment by tp1de** [comment]
@Apollon77  I am confused. Adapter checker does not show any errors to me anymore. Do I use the checker correctly?

image

**Comment by tp1de** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
Whats your main branch? Master or main? The default is "main" ... but you did check for "master"???

**Comment by tp1de** [comment]
> Whats your main branch? Master or main? The default is "main" ... but you did check for "master"???

Shit .... you are right !

image


I am not sure what to do with E506. I just maintained English and German text. Isn't this enough?

**Comment by Apollon77** [comment]
>  Isn't this enough?

We try to have basic translations for all supported languages ... you can use the referenced web tool to get the auto translations.

**Comment by tp1de** [comment]
> We try to have basic translations for all supported languages

**Is this a must for first release or can I update later?**

Just a question: When doing updates on words.js and/or io-package.json do I need to create a new npm (with new version number) ?

**Comment by Apollon77** [comment]
for texts in io-package it is a must, for words a "should" :-)) but would be acceptable

> When doing updates on words.js and/or io-package.json do I need to create a new npm (with new version number) ?

words.js yes, io-package should work without, but better also with an update that it is consistent

**Comment by tp1de** [comment]
@Apollon77 
I translated now everything, no adapter check errors except: [W400] Cannot find "ems-esp" in latest repository
I hope everything is fine now.

**Comment by tp1de** [comment]
RE-CHECK!

**Comment by tp1de** [comment]
@Apollon77  what can I do to proceed?

**Comment by Apollon77** [comment]
Please wait until I can do the adapter review ... I'm currently working from bottom to top ...

**Comment by Apollon77** [comment]
Hi,

ok, then here we go with the review:
* Please remove all the "_*" entries (and some more) from your package.json. It seems that you committed a package.json that was installed via npm ... you need to clean up all irrelevant entries
* really https://github.com/tp1de/ioBroker.ems-esp/blob/main/main.js#L106? Why you not simply await adapter.getForeignObjectAsync in L98 ? Please not start with such bad hacks if you already use async/await
* is https://github.com/tp1de/ioBroker.ems-esp/blob/main/main.js#L124 really intended? Multiple instances of the same adapter would write into the same directory? Maybe it is better to use an instance specific dir (also utils method available); and BTW: Whats stored in the files? Remember that they are not in the backup by default!And also when an instance is moved to another host they are not transferred!
* Sleep in adapters is very bad behaviours if not done right. You need to make sure that eighter you rememnber of unload was called in between and do not proceed after sleep - or you need to store all these timeouts and make sure that unload kills them all when it is called
* Some "sleeps" in between feel strange because no idea why the are there, e.g. https://github.com/tp1de/ioBroker.ems-esp/blob/84994082a98c6690ffc3176efb47ce882419f857/main.js#L167 ... aahh now I see .. you "need" them because of that strange mix of async/await and callback style e.g. in https://github.com/tp1de/ioBroker.ems-esp/blob/main/main.js#L767 ... honestly ... do one way and do it right ... not such weird mixups that noone can understand and will produce issues
* All your objects mis the common.role attrible (e.g. https://github.com/tp1de/ioBroker.ems-esp/blob/84994082a98c6690ffc3176efb47ce882419f857/main.js#L177-L185). Please add proper roles -> https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md
* It is uncommon to use the "from" to check if statechange came from adapter (https://github.com/tp1de/ioBroker.ems-esp/blob/84994082a98c6690ffc3176efb47ce882419f857/main.js#L248) ... normally "state.ack=true" changes are not processed and only "state.ack=false" is handled in on statechange
* ok ... now i see ... https://github.com/tp1de/ioBroker.ems-esp/blob/main/main.js#L621-L628 ... all setStates from adaspter that are "data provided by adater and not meaned to be commands needs to have ack=true set!!
* unload also needs to destroy and cleanup allused servers and resources (e.g. https://github.com/tp1de/ioBroker.ems-esp/blob/main/main.js#L484) ... and the callback should not be called before these are really "turned off" ... else this will give big chaos in compact mode. Did you ever tested your adapter in compact mode? I guess not ...

I stopped after these topics fr the first run, please check and adjust the issues

Ingo

**Comment by tp1de** [comment]
Hallo Ingo, bitte lass mich mal auf Deutsch antworten.

Respekt für Dein Feedback, mir war nicht bewusst, dass Du so im Detail Dir das Coding anschaust. Ich muss allerdings gestehen, dass meine erste Reaktion war: Lass es sein ist zu kompliziert !

Ich bin Rentner und kein IT-Entwickler. Es ist 40 Jahre her wo ich als Student programmiert habe. Die asynchrone Welt von JS überfordert mich noch etwas. Auch für die Adapterentwicklung habe ich nur viele (z.T. alte) Teil-Informationen im Netz gefunden. Gibt es dazu Links?
Aber zu Deinen Anmerkungen:

1. Die package.json stammt aus dem Adapter-Creator vor etwa 9 Monaten. Ich habe mir nun andere package.json angesehen und viele Unterschiede entdeckt. **Ich bin mir nicht sicher, ob es reicht die _* Einträge zu löschen.**
Kannst Du mir helfen?
2. Ich habe festgestellt, dass (vor einigen Monaten) die await adapter.getForeignObjectAsync nicht funktioniert - deshalb das "sleep". Ich teste nochmal. Das betrifft auch Deine anderen Anmerkungen. So wie ich das sehe, funktioniert ein await auch nicht bei DB-Operationen (mySQL / InfluxDB). Ohne sleep bekomme ich "Sequence out of order" Fehlermeldungen. 
3. Der Adapter ist nur für eine Instanz gedacht - werde ich aber überarbeiten.
4. Die States Attribute sind vergeben. Nur der übergeordnete Ordnungsbegriff (z.B. boiler hat keinen Wert:
image
5. Die state check Anmerkungen verstehe ich. Das Coding stammt aus den Anfängen der Adapterentwicklung. Werde ich überarbeiten.
6. Das ordnungsgemäße beenden der Server-Prozesse hatte ich for einigen Wochen getestet. Ich werde aber noch einmal den Compact-Mode einschalten und testen.

**Comment by Apollon77** [comment]
Hi, gesundes neues erstmal.

Ja wir machen diese "tiefen Reviews" damit wir den Entwicklern bestmöglich helfen können und auch die User die es nutzen  eine positive Erfahrung haben.

1. Kann so nicht sein. diese _-Einträge und so entstehen wenn man  ein "npm i paketname" macht weil sich dort npm selbst Daten merkt ... also müsstest du mindestens das gemacht haben :-) Aber ja aufräumen und gut ist
2. Das darf an sich nicht sein und wäre ein Bug im js-controller ... also wenn es so ist dann bitte melden als Issue - aber da diese Funktion sehr oft verwendet wird klänge es eher nach irgendwas anderem.
3. Dann ist das ok, dann setzte "common.singleton: true" in io-package und iobroker sorgt dafür das es pro Host nur eine Instanz geben darf. Dann ist das alles ok
4. Ok, wenn das die Channel objekte sind ist ja alles ok ... bin ehrlich das ich irgendwann auch nicht mehr tiefer geschaut habe. ber auch "Boiler" sollte an sich als objekt vom typ channel, device oder folder angelegt werden

Und vielen Dank für Dein Feedback. Ja die Developer Doku ist aktuell da aber sehr verstreut - aber eine neue Seite ist als Developer Initiative in Arbeit. Unter https://iobroker.dev ist bereits einiges verlinkt was vllt hilft. mehr kommt bald. Developer support generell gibts im Forum und auch Discord und Telegram.

Meld dich einfach hier kurz wenn ich nochmal reviewen soll

**Comment by tp1de** [comment]
> Hi, gesundes neues erstmal.

Ja das wünsche ich Dir auch Ingo.

> Ja wir machen diese "tiefen Reviews" damit wir den Entwicklern bestmöglich helfen können und auch die User die es nutzen eine positive Erfahrung haben.

Finde ich super - ist aber sehr viel Arbeit. Tiefer Respekt, jetzt verstehe ich auch, warum das etwas dauert.

> Unter https://iobroker.dev ist bereits einiges verlinkt

Link funktioniert leider nicht. Ich bekomme Fehlermeldungen:
```
Die Website ist nicht erreichbar Die Webseite unter https://iobroker.dev/ ist eventuell vorübergehend nicht verfügbar oder wurde dauerhaft an eine neue Webadresse verschoben.
ERR_HTTP2_PROTOCOL_ERROR
```

Ich bin im Moment dabei, den Adapter etwas anders zu strukturieren. Ich würde gerne einzelnen Programmcode in separate JS-Files "auslagern" analog dem "include" aus den alten Programmierzeiten vor 40 Jahren. Ich verstehe aber noch nicht ganz wie ich das mache und was das für die globalen Variablen bedeutet. Ich bin am testen und melde mich, wenn ich fertig bin.

Grüße Thomas

**Comment by Apollon77** [comment]
Versuch mal https://www.iobroker.dev

**Comment by Apollon77** [comment]
Und Bei Fragen komm uns Discord oder Telegram

**Comment by tp1de** [comment]
> Versuch mal https://www.iobroker.dev

Geht - Danke !

**Comment by ldittmar81** [comment]
Close https://github.com/ioBroker/AdapterRequests/issues/302 when done.

**Comment by tp1de** [comment]
@Apollon77 So nun habe ich den Code neu strukturiert, ausführlich im Compact-Mode getestet und die gewünschten Anpassungen gemacht. Sollte so reichen .... oder?
( Die sleep-Funktion und fehlenden clearTimers hatten wir ja ausführlich bei Discord diskutiert)

**Comment by tp1de** [comment]
@Apollon77 So nun habe ich den Code neu strukturiert, ausführlich im Compact-Mode getestet und die gewünschten Anpassungen gemacht. Sollte so reichen .... oder?
( Die sleep-Funktion und fehlenden clearTimers hatten wir ja ausführlich bei Discord diskutiert)

**Comment by tp1de** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
Why closed?

**Comment by tp1de** [comment]
Wondering that nothing happened anymore and I still have changes / updates to do for user feedback.
(I do not understand good enough what to do in this case with versions & npm modules while still waiting for approval)

I will do the changes needed and then make a new pull request....

**Comment by Apollon77** [comment]
Ok ... "nothing happened anymore" was mainly because of lack of time on the weekend for re-reviews... comes next. Just poke when I should check again

**Comment by tp1de** [comment]
Ingo kein Problem, ist nur für mich sehr intransparent wie ich in diesem Fall mit Änderungen umgehen soll ... Deswegen erst einmal close.
Bist Du denn der Einzige der die Repositories reviewed? Ist ja ggfs. eine Menge Arbeit.

Ich habe aktuell ein "Problem": Irgendwie ist mein Adapter bei all den Änderungen in die Tab-Leiste gerutscht und ich bekomme ihn nicht mehr raus.
image

**Comment by Apollon77** [comment]
An sich
* tab in io-üpackage löschen
* "iob upload adaptername"
* admin neu starten; worst case local storage und cookies löschen vom browser

**Comment by tp1de** [comment]
Ja danke für's Feedback. Ich habe gemerkt, dass ich den Adapter löschen und neu installieren muss, damit der Eintrag entfernt wird. D.h. upload alleine reicht nicht aus.

**Pull request closed without merging**
