### PR TITLE
Add iobroker.easee

### PR DESCRIPTION
**Pull request by Newan**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

:thumbsup: No errors found

### [ioBroker.easee](https://github.com/Newan/ioBroker.easee)
[Downloads](https://www.npmjs.com/package/iobroker.easee) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.easee/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.easee)!. Please execute in adapter directory: `npm owner add bluefox iobroker.easee`
- [ ] :heavy_exclamation_mark: [E506] Word "username" is not translated to russian in [admin/words.js](https://github.com/Newan/ioBroker.easee/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "password" is not translated to russian in [admin/words.js](https://github.com/Newan/ioBroker.easee/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "polltime" is not translated to russian in [admin/words.js](https://github.com/Newan/ioBroker.easee/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/Newan/ioBroker.easee", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/Newan/ioBroker.easee", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "easee" in latest repository

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

:thumbsup: No errors found

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Morluktom <strassertom@gmx.de>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@Newan Please have a look at the automatic checker comments and give a ping once fixed

**Comment by Newan** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

:thumbsup: No errors found

### [ioBroker.easee](https://github.com/Newan/ioBroker.easee)
[Downloads](https://www.npmjs.com/package/iobroker.easee) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.easee/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "easee" in latest repository

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

:thumbsup: No errors found

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Morluktom <strassertom@gmx.de>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hello,

here some review comments:
* please encrypt the password! See development best practices in readme in this repo
* you should await that https://github.com/Newan/ioBroker.easee/blob/master/main.js#L79
* you should also await the setState e.g. https://github.com/Newan/ioBroker.easee/blob/master/main.js#L396
* it is maybe not the best idea to do setObjectNotExistsAsync calls any time you want to write values. YOu should do that once

Please check and adjust. Thank you

**Comment by Newan** [comment]
> Hello,
> 
> here some review comments:
> 
> * please encrypt the password! See development best practices in readme in this repo
> * you should await that https://github.com/Newan/ioBroker.easee/blob/master/main.js#L79
> * you should also await the setState e.g. https://github.com/Newan/ioBroker.easee/blob/master/main.js#L396

fixed

> * it is maybe not the best idea to do setObjectNotExistsAsync calls any time you want to write values. YOu should do that once
> 
Prior to the runtime, it cannot be determined how many chargers there are. It is even possible, that some might be added or removed. I just could make it more static i. e. read on startup and set the objects. You would loose the ability to dynamically add chargers and if you add a charger the adapter would require to be restarted. Do you have any alternative solution?

**Comment by Apollon77** [comment]
If it is really about devices just use an internal object to remember for which device you added the states in the current "run". so if a new device is added it will be exected once

**Comment by Newan** [comment]
> If it is really about devices just use an internal object to remember for which device you added the states in the current "run". so if

I have rebuilt this

**Comment by Apollon77** [comment]
Hi,

thank you, I will moerge now, but one advice: https://github.com/Newan/ioBroker.easee/commit/fde501161045d08363bf99dc98ba8e4586b4c418#diff-58417e0f781b6656949d37258c8b9052ed266e2eb7a5163cad7b0863e6b2916aR430-R440 ... maybe also use await and the Async methods here :-)

**Pull request merged**
