### PR TITLE
Update logparser to 2.1.3

### PR DESCRIPTION
**Pull request by ciddi89**
Please update my adapter ioBroker.logparser to version 2.1.3.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
2.1.3 was released at 19.05.2023
Normally a new release should be one or two weeks at latest before adding oit to stable.
If this release is a urgent hot fix please indiacte.

Otherwise I will delay merging a litle bit ..

**Comment by ciddi89** [comment]
wtf? since when? last release was on 2023-04-07 and dependecies was updated on the first of this month so there is no problem. Why isn't Ingo this job doing anymore?

**Comment by mcm1957** [comment]
Its NOT about time difference between lats und current release. It's simple the fact that the new release (2.1.3) has been created 
19.05.2023, 22:21:49, app 1/2h ago. This release is n ot even listed at latest now. So why should it be decaltred stable without any beta testing? Is there any hot fix included? If yes, please indicate.

image

Again:
Every release should be some time (1 two 2 weeks) at latest and / or a significant percentage users should be using the latest / beta version. This is not the case for 2.1.3.

Maybe you wanted to relese 2.1.2 which was at stable same time ?

Ingo is very limited in time so I try to support with routine jobs. But I will inform him explicitly. Please feel free to comtact him directly too.

@Apollon77 Please check whether my decison is inappropiate.

**Comment by Apollon77** [comment]
Ingo would ask the same question :-) And since always ... normally a new version shoud be in beta for some time to make sure there are no issues. See also Readme.

And I'm happy if other Community members also find time to support with such things to speed up such Repo merges.

**Comment by mcm1957** [comment]
Wouldn't be necessary to close the PR. I would have merged it in 1 or 2 weeks  if no serious issues have been reported.

**Pull request closed without merging**
