### PR TITLE
Update panasonic-comfort-cloud to 3.0.2

### PR DESCRIPTION
**Pull request by marc2016**

### CODE REVIEW

**Comment by marc2016** [comment]
RE-CHECK!

**Comment by marc2016** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@marc2016 
Please update / enable standard github testing.
Currently integration testi ng is disabled:
```
      - name: Run local tests
        run: npm test
#      - name: Run unit tests
#        run: npm run test:unit
#      - name: Run integration tests # (linux/osx)
#        if: startsWith(runner.OS, 'windows') == false
#        run: DEBUG=testing:* npm run test:integration
#      - name: Run integration tests # (windows)
#        if: startsWith(runner.OS, 'windows')
#        run: set DEBUG=testing:* & npm run test:integration
```

I would suggest to replace test_and_release workflow with up to date version (i.e. from template adapter). package tests and integrations tests are mandatory. Of course you can add additional tests if you like.

And please remove node 16 tests (they will fail anyway) and consider addint node 22 to testing matrix (node 22 is suggested but not yet mandatory)

**Comment by marc2016** [comment]
Thank you very much for the hint :-) I changed to the new workflow.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by marc2016** [comment]
@mcm1957  the Adapter does not work anymore in previous versions, because Panasonic switch the login process to OAuth. Until the release to stable no one can use the adapter from stable repo.

**Comment by mcm1957** [comment]
OK thanks for Info.
Will release immidiatly of course.

**Comment by marc2016** [comment]
> OK thanks for Info. Will release immidiatly of course.

Thank you 👍🏻

**Pull request merged**
