### PR TITLE
added ecovacs-deebot adapter

### PR DESCRIPTION
**Pull request by mrbungle64**

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi,

here some review comments:
* Needs fix: Please encrypt the password! You can check e.g. my meross Adapter for the relevant code for index_m.html and main.js for encryption and decryption
* Needs fix: you can use https://translator.iobroker.in/ to auto translate all relevant texts into all needed languages by providing english text
* Needs fix: you need to store all Timeouts and make sure to clear them in "On unload", e.g. https://github.com/mrbungle64/ioBroker.ecovacs-deebot/blob/master/main.js#L65 ... else it will break completely in compact mode ... same for https://github.com/mrbungle64/ioBroker.ecovacs-deebot/blob/master/main.js#L217 ... the interval needs to be a class variable that it can be cleared in unload!
* Note: You structured your states in several levels. please also create the needed channel/device objects for these levels. e.g. "history" and "consumable" and such. In your case I would use "channel" objects there.

Also please review https://github.com/ioBroker/ioBroker.repositories#development-and-coding-best-practices

**Comment by mrbungle64** [comment]
Hi @Apollon77,

thanks for the review :)

I already fixed the issues:

> * Needs fix: Please encrypt the password! You can check e.g. my meross Adapter for the relevant code for index_m.html and main.js for encryption and decryption

[compare view](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/compare/8e7743269ac59cc9c4347a66d04eda4e2d898518..c1fa0d8f7263284a1e349213e22a8120952d34b4)

> * Needs fix: you can use https://translator.iobroker.in/ to auto translate all relevant texts into all needed languages by providing english text

[compare view](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/compare/c1fa0d8f7263284a1e349213e22a8120952d34b4..d2783d790d6bf6a8ef5b54a4accfc334bd185ac7)

> * Needs fix: you need to store all Timeouts and make sure to clear them in "On unload", e.g. https://github.com/mrbungle64/ioBroker.ecovacs-deebot/blob/master/main.js#L65 ... else it will break completely in compact mode ... same for https://github.com/mrbungle64/ioBroker.ecovacs-deebot/blob/master/main.js#L217 ... the interval needs to be a class variable that it can be cleared in unload!

[compare view](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/compare/d2783d790d6bf6a8ef5b54a4accfc334bd185ac7..771e9127a829c84844926e19c22b3896b02811b4)

> * Note: You structured your states in several levels. please also create the needed channel/device objects for these levels. e.g. "history" and "consumable" and such. In your case I would use "channel" objects there.

[compare view](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/compare/771e9127a829c84844926e19c22b3896b02811b4..ea153f98b7763cfe081ae4f895d9e45703f8c30e)

... but since I switched to encrypted password there is a bug in the adapter configuration that the values displayed below the password field are stored correctly and are highlightened in the select box but not preselected. I'm trying to fix since yesterday but no success.

If you have any idea how I could fix it or if it's a known issue I would be happy about a hint :)

**Comment by Apollon77** [comment]
did you fixed it? I'm not the frontend guy, so might not that helpfull. Try to ask in developer area in forum, i think there are devs to help. Post here then I can also point some devs to it.

BTW: For your timeout/interval change: Better also check if a timeout is already running before setting a new one because as I understand your code (especially onStateChange) it could happen that the timout is set again before it expired ... so better be clean there. Same for Interval

**Comment by mrbungle64** [comment]
> did you fixed it? I'm not the frontend guy, so might not that helpfull. Try to ask in developer area in forum, i think there are devs to help. Post here then I can also point some devs to it.

I fixed it a few minutes ago.
If I use socket.emit() only for the password field the problem is solved :)
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/commit/a360a7ac65300132323349d8f5db217de0865edb

> BTW: For your timeout/interval change: Better also check if a timeout is already running before setting a new one because as I understand your code (especially onStateChange) it could happen that the timout is set again before it expired ... so better be clean there. Same for Interval

Thanks for the hint :) I also fixed this issue:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/commit/50641f8a9ff50d84838c33e453aab59a81fa4f0a

**Comment by Apollon77** [comment]
So version is ready for the repo?

**Comment by mrbungle64** [comment]
> So version is ready for the repo?

yes :)

**Pull request merged**
