### PR TITLE
Add Twinkly Adapter into latest

### PR DESCRIPTION
**Pull request by patrickbs96**
I've created an Adapter to control the Twinkly Lights. 
Repo: https://github.com/patrickbs96/ioBroker.twinkly
Forum: https://forum.iobroker.net/topic/39632/new-adapter-twinkly

### CODE REVIEW

**Comment by Apollon77** [comment]
Re-CHECK!

**Comment by patrickbs96** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

:thumbsup: No errors found

### [ioBroker.twinkly](https://github.com/patrickbs96/ioBroker.twinkly)
[Downloads](https://www.npmjs.com/package/iobroker.twinkly) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.twinkly/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "twinkly" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hello, sorry for the late review. I have some comments:
* please adjust js-controller dep in io-package to >=2.0.0 because you use adapter.core 2.4.0 as dep
* why https://github.com/patrickbs96/ioBroker.twinkly/blob/master/io-package.json#L197-L211 is in? You do not use an admin tab
* please change https://github.com/patrickbs96/ioBroker.twinkly/blob/master/main.js#L849 to work sequencial ... right now you have one while loop and so fire all your tasks directly. On smaller systems this can mean a huge load. Please process next entry after the callback was called (or switch to async/await here) - please also run adapter with js.controller 3.2 and delete all objects to verify that all objects were created before states are set
* why you have a hard wait of 5s before first poll? maybe because the async objects creation above? ;-)
* you only test nodejs 12+ ... is this required? If yes please add as engine requirement to package.json

Thank you for looking int these comments and adjust accordingly

**Comment by patrickbs96** [comment]
@Apollon77 thanks for the review.

- Updated
- Removed it. Must have been added automatically when I created the adapter from the template.
- Changed. I'm used to everything always being sequential at work, therefore I didn't see that... 
- Removed the wait, don't think there was a reason for that.
- Added 10 again, I had it removed as I thought it wasn't needed anymore.

**Comment by patrickbs96** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/xenon-s/ioBroker.device-reminder/blob/master/iob_npm.done)" found in repo! Please add it to .gitignore
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 xenon-s <ente_s@hotmail.de>" at the end of [README.md](https://github.com/xenon-s/ioBroker.device-reminder/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 xenon-s <ente_s@hotmail.de>" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E818] file iob_npm.done found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E914] file iob_npm.done found in repository, but not found in .gitignore

### [ioBroker.twinkly](https://github.com/patrickbs96/ioBroker.twinkly)
[Downloads](https://www.npmjs.com/package/iobroker.twinkly) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.twinkly/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/patrickbs96/ioBroker.twinkly/blob/master/io-package.json). Must be removed.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 patrickbs96 <patrickbsimon96@gmail.com>" at the end of [README.md](https://github.com/patrickbs96/ioBroker.twinkly/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 patrickbs96 <patrickbsimon96@gmail.com>" at the start of LICENSE
- [ ] :eyes: [W400] Cannot find "twinkly" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by patrickbs96** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/xenon-s/ioBroker.device-reminder/blob/master/iob_npm.done)" found in repo! Please add it to .gitignore
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 xenon-s <ente_s@hotmail.de>" at the end of [README.md](https://github.com/xenon-s/ioBroker.device-reminder/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 xenon-s <ente_s@hotmail.de>" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E818] file iob_npm.done found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E914] file iob_npm.done found in repository, but not found in .gitignore

### [ioBroker.twinkly](https://github.com/patrickbs96/ioBroker.twinkly)
[Downloads](https://www.npmjs.com/package/iobroker.twinkly) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.twinkly/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/patrickbs96/ioBroker.twinkly/blob/master/io-package.json). Must be removed.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 patrickbs96 <patrickbsimon96@gmail.com>" at the end of [README.md](https://github.com/patrickbs96/ioBroker.twinkly/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 patrickbs96 <patrickbsimon96@gmail.com>" at the start of LICENSE
- [ ] :eyes: [W400] Cannot find "twinkly" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by patrickbs96** [comment]
The errors from Re-Check have been corrected but it seems it's still referencing the version with those errors

**Comment by Apollon77** [comment]
... also the PR hiere shows a merge conflict that should be resolved ...

And: https://github.com/patrickbs96/ioBroker.twinkly/blob/master/main.js#L927-L932
Ithink you can just repace that by a "if (resultError) throw new Error(...); return true" ... and done

And https://github.com/patrickbs96/ioBroker.twinkly/blob/329e4a05e83a82dc4544b5c39ef97665fbf59a21/main.js#L538-L539 ... awaith ... .then() is an anto pattern which should also not be needed :-)

normally to catch errors from async you simply make a try/catch around it

**Comment by patrickbs96** [comment]
Thanks for the info :-) I've updated the code.

**Pull request merged**
