### PR TITLE
add adapter followthesun to latest repository

### PR DESCRIPTION
**Pull request by HGlab01**
Started to learn how adapter works and I would like to implement
https://github.com/ioBroker/AdapterRequests/issues/226
as a first "training".

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi,

some changes are needed :-)
* remove onState/ObjectChange when you do not need it ... the same with the "default * subscribe
* do not use setObject but setObjectNotExists
* if you have statically defined objects you can put then in io-package in instanceObjects and controller will take care to create them.
* please name the config items with their real namees and not "option1" :-) https://github.com/HGlab01/ioBroker.followthesun/blob/master/main.js#L126 and If you need aspecial datatype (e.g. number in your case) then do proper checking and converting (parseInt e.g.). Never trust user input!!
* you should move that whole block into the other block above because else it could be that your calc methid is called before data are initialiuzed (edge case but possible)
* make sure to end your "schedule" in unload - https://github.com/HGlab01/ioBroker.followthesun/blob/master/main.js#L161

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.followthesun](https://github.com/HGlab01/ioBroker.followthesun)
[Downloads](https://www.npmjs.com/package/iobroker.followthesun) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.followthesun/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/HGlab01/ioBroker.followthesun/blob/master/io-package.json). Must be removed.
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.followthesun)!. Please execute in adapter directory: `npm owner add bluefox iobroker.followthesun`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/HGlab01/ioBroker.followthesun/blob/master/iob_npm.done)" found in repo! Please add it to .gitignore
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/HGlab01/ioBroker.followthesun", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/HGlab01/ioBroker.followthesun" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "followthesun" in latest repository
- [ ] :eyes: [W801] .npmignore not found
- [ ] :eyes: [W901] .gitignore not found

### [ioBroker.senec](https://github.com/nobl/ioBroker.senec)
[Downloads](https://www.npmjs.com/package/iobroker.senec) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.senec/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/nobl/ioBroker.senec", press the first "Edit" button you will find on the page and add the description.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Please also check the other comments from the automated checker

**Comment by Apollon77** [comment]
Please also have a look into https://github.com/ioBroker/ioBroker.repositories#development-and-coding-best-practices

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.followthesun](https://github.com/HGlab01/ioBroker.followthesun)
[Downloads](https://www.npmjs.com/package/iobroker.followthesun) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.followthesun/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.0.3
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/HGlab01/ioBroker.followthesun", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E818] file iob_npm.done found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "followthesun" in latest repository

### [ioBroker.senec](https://github.com/nobl/ioBroker.senec)
[Downloads](https://www.npmjs.com/package/iobroker.senec) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.senec/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/nobl/ioBroker.senec", press the first "Edit" button you will find on the page and add the description.


*Add comment "RE-CHECK!" to start check anew*

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.followthesun](https://github.com/HGlab01/ioBroker.followthesun)
[Downloads](https://www.npmjs.com/package/iobroker.followthesun) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.followthesun/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.0.3
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/HGlab01/ioBroker.followthesun", press the first "Edit" button you will find on the page and add the description.
- [ ] :eyes: [W400] Cannot find "followthesun" in latest repository

### [ioBroker.senec](https://github.com/nobl/ioBroker.senec)
[Downloads](https://www.npmjs.com/package/iobroker.senec) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.senec/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/nobl/ioBroker.senec", press the first "Edit" button you will find on the page and add the description.


*Add comment "RE-CHECK!" to start check anew*

**Comment by HGlab01** [comment]
Good morning team!

I guess I need your help to solve the lasst view issues:
 ❗ [E145] No news found for actual version 0.0.3
--> I added a line '0.0.3' in section changelog. What else I have to do? 
 ❗ [E300] Not found on travis. Please setup travis
--> Travis CI is configured and works in my point of view (https://travis-ci.com/github/HGlab01/ioBroker.followthesun)
 ❗ [E801] No repository about text found. Please go to "https://github.com/HGlab01/ioBroker.followthesun", press the first "Edit" button you will find on the page and add the description.
--> I doublechecked if a description in README.md exists. What to do here?

Thanks for your support!

**Comment by Apollon77** [comment]
Hi,

news also need to go into io-package.json to be shown in admin. In fact : Use Readme.md for long changelog, and new for a short version.

Travis is ok , seems to be a false positive

The github infos topic is broken since they changes their layout :-) So also ok

**Comment by Apollon77** [comment]
But also - and here I'm honest - we need to think if it make sense to have an adapter that just does this ;-) The infos are available in javascript adapter kind of out of the box ... hm ... but yes not as states ...

(But if it is an easy learningprojct for you then goal is also reached or !? ;-) )

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.followthesun](https://github.com/HGlab01/ioBroker.followthesun)
[Downloads](https://www.npmjs.com/package/iobroker.followthesun) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.followthesun/)

- [ ] :heavy_exclamation_mark: [E100] Cannot parse [io-package.json](https://github.com/HGlab01/ioBroker.followthesun/blob/master/io-package.json): SyntaxError: Unexpected token } in JSON at position 182
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/HGlab01/ioBroker.followthesun", press the first "Edit" button you will find on the page and add the description.

### [ioBroker.senec](https://github.com/nobl/ioBroker.senec)
[Downloads](https://www.npmjs.com/package/iobroker.senec) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.senec/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/nobl/ioBroker.senec", press the first "Edit" button you will find on the page and add the description.


*Add comment "RE-CHECK!" to start check anew*

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.followthesun](https://github.com/HGlab01/ioBroker.followthesun)
[Downloads](https://www.npmjs.com/package/iobroker.followthesun) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.followthesun/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/HGlab01/ioBroker.followthesun", press the first "Edit" button you will find on the page and add the description.
- [ ] :eyes: [W400] Cannot find "followthesun" in latest repository

### [ioBroker.senec](https://github.com/nobl/ioBroker.senec)
[Downloads](https://www.npmjs.com/package/iobroker.senec) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.senec/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/nobl/ioBroker.senec", press the first "Edit" button you will find on the page and add the description.


*Add comment "RE-CHECK!" to start check anew*

**Comment by HGlab01** [comment]
Hi @Apollon77!
I agree, this adapter is no rocket science and it's your decision.
My two thoughts why I chose this topic
- It was requested in the forum
- I have the impression that a lot of iobroker users do not use JS but Blockly. For this user group it could help to get the sun postion via an adapter.

Up to you ;-) 
Either way, thanks for the support!

**Comment by HGlab01** [comment]
I believe everything is done from my side.
E300 and E801 are false positive.
What's the next step?
It's only about the decision if you will add the adapter to the repository? Do you need anything else from my side?
When/how will the decision be done?

**Comment by HGlab01** [comment]
Morning @Apollon77 ,
is there any progress on my pull-request?

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.followthesun](https://github.com/HGlab01/ioBroker.followthesun)
[Downloads](https://www.npmjs.com/package/iobroker.followthesun) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.followthesun/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/HGlab01/ioBroker.followthesun/blob/master/io-package.json). Must be removed.
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/HGlab01/ioBroker.followthesun/blob/master/iob_npm.done)" found in repo! Please add it to .gitignore
- [ ] :eyes: [W400] Cannot find "followthesun" in latest repository

### [ioBroker.senec](https://github.com/nobl/ioBroker.senec)
[Downloads](https://www.npmjs.com/package/iobroker.senec) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.senec/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.followthesun](https://github.com/HGlab01/ioBroker.followthesun)
[Downloads](https://www.npmjs.com/package/iobroker.followthesun) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.followthesun/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "followthesun" in latest repository

### [ioBroker.senec](https://github.com/nobl/ioBroker.senec)
[Downloads](https://www.npmjs.com/package/iobroker.senec) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.senec/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by HGlab01** [comment]
Dear iobroker team,
in my point of view your behavior is a bit strange.
Please feel free to reject the request to add this new adapter to the repository, if you think it does not fit.
Ignoring the request feels not very community like.

**Pull request merged**
