### PR TITLE
bump xbox

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.xbox](https://github.com/foxriver76/ioBroker.xbox)
[Downloads](https://www.npmjs.com/package/iobroker.xbox) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.xbox/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/foxriver76/ioBroker.xbox/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E504] found setInterval in "main.js, but no clearInterval detected
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.xbox](https://github.com/foxriver76/ioBroker.xbox)
[Downloads](https://www.npmjs.com/package/iobroker.xbox) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.xbox/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
