### PR TITLE
Update e3oncan to 0.9.5

### PR DESCRIPTION
**Pull request by MyHomeMyData**
Please update my adapter ioBroker.e3oncan to version 0.9.5.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
@MyHomeMyData 
Please activate nodeJs 22 tests - unless you know there is a problem.

A new release is NOT required, but tests should pass with GH head

**Comment by mcm1957** [comment]
reminder 8.10.2024

**Comment by MyHomeMyData** [comment]
Adapter is running with node 22, but tests fail with node 22. Problem seems to be linked to socketcan.
I'm in clarification about that, issue is still open.

Martin, we had a discussion about that topic via telegram.

I added a note in readme: "Not fully tested with node 22." So from my point of view we should proceed.

**Comment by mcm1957** [comment]
Sorry - I missed this.
Too much issues every day ...

**Pull request merged**
