### PR TITLE
Added vis-icontwo to latest

### PR DESCRIPTION
**Pull request by jkvarel**
Added vis-icontwo to latest

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-icontwo](https://github.com/inventwo/ioBroker.vis-icontwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-icontwo) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-icontwo/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "vis-icontwo" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jkvarel** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-icontwo](https://github.com/inventwo/ioBroker.vis-icontwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-icontwo) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-icontwo/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "vis-icontwo" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jkvarel** [comment]
Hi :) ,
when can we expect the pull request to be merged? Or is something wrong with our adapter?

**Comment by Apollon77** [comment]
Nothing wrong only time for review needed

**Comment by jkvarel** [comment]
Ok great. But I don't have to do anything?

**Comment by Apollon77** [comment]
@jkvarel Reveiw comments:
* please remove the main.js ... there is nothing in it so nothing needed ... please see https://github.com/ioBroker/ioBroker.icons-icons8/blob/master/io-package.json as kind of a template
* you can also remove from io.package "connectionType" and "dataSource" because irrelevant here

**Comment by skvarel** [comment]
> 
>     * please remove the main.js ... there is nothing in it so nothing needed ... please see https://github.com/ioBroker/ioBroker.icons-icons8/blob/master/io-package.json as kind of a template
> 
>     * you can also remove from io.package "connectionType" and "dataSource" because irrelevant here

Done! I have adjusted the code.

**Comment by Apollon77** [comment]
Sorry for the delay.

but the mode needs to be "none" then, or ?!
https://github.com/inventwo/ioBroker.vis-icontwo/blob/master/io-package.json#L175

**Comment by skvarel** [comment]
No promlem! 

I've changed the entry now. Version 0.1.9 Published a few seconds ago.

**Comment by Apollon77** [comment]
Welcome in the repo

**Pull request merged**
