### PR TITLE
add bestway

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bestway](https://github.com/TA2k/ioBroker.bestway)
[Downloads](https://www.npmjs.com/package/iobroker.bestway) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.bestway/)

- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :eyes: [W400] Cannot find "bestway" in latest repository
- [ ] :eyes: [W801] .npmignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bestway](https://github.com/TA2k/ioBroker.bestway)
[Downloads](https://www.npmjs.com/package/iobroker.bestway) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.bestway/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "bestway" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
