### PR TITLE
add Adapter mytime to latest

### PR DESCRIPTION
**Pull request by oweitman**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mytime](https://github.com/oweitman/ioBroker.mytime)
[Downloads](https://www.npmjs.com/package/iobroker.mytime) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.mytime/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "mytime" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

here some review comments:
* when using adapter-core 2.4.0 dep you need to require at least js-controller 2.0.0 (https://github.com/oweitman/ioBroker.mytime/blob/master/io-package.json#L94)
* please translate the io-package.json content ... you can use the iobroker translation tool
* please add all admin options that can be set also with their default values in io-package native object
* if objectChanges are not needed please do not subscribe to it

Thank you to check and adjust

**Comment by oweitman** [comment]
RE-CHECK!
Punkte sollten behoben sein.

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mytime](https://github.com/oweitman/ioBroker.mytime)
[Downloads](https://www.npmjs.com/package/iobroker.mytime) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.mytime/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "mytime" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
