### PR TITLE
Update oekofen-json to 1.0.4

### PR DESCRIPTION
**Pull request by chaozmc**
Please update my adapter ioBroker.oekofen-json to version 1.0.4.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
1.0.4 created 22.09.2023

**Comment by mcm1957** [comment]
@chaozmc 
As you removed node 16 from tests, you must ensure that this adapter is used with node 18 or newer only.
Please merge PR https://github.com/chaozmc/ioBroker.oekofen-json/pull/23 to add a matching engines clause.

**Comment by chaozmc** [comment]
@mcm1957
i've added your PR as suggested, but as this is a new patchlevel now i guess this PR needs to be closed, and i'll add a new one with 1.0.5 in a few days after 1.0.5 is available in latest für a few days?

**Comment by mcm1957** [comment]
> @mcm1957 i've added your PR as suggested, but as this is a new patchlevel now i guess this PR needs to be closed, and i'll add a new one with 1.0.5 in a few days after 1.0.5 is available in latest für a few days?

This would be the cleanest solution.

**Comment by chaozmc** [comment]
Allright

**Pull request closed without merging**
