### PR TITLE
bump history to 2.2.6

### PR DESCRIPTION
**Pull request by foxriver76**
needed for controller v5

### CODE REVIEW

**Comment by mcm1957** [comment]
adapter checker error can be ignored for stable merge

**Comment by mcm1957** [comment]
2.2.6 created 23.08.2023
157 user (0,5%)

@foxriver76 
When do you plan to release js-controller to stable?
I would suggest that histore should be available at latest at for a few (2 or 3 days) before going to stable, but if this is too long in your oppion I cn release it immidiatly too. You know best what has changed :-)

According to readme changes required for js-controll5 have been done end 2022 but never made into a relase. But I wonder why this did not pop up during latest tests of js-controller.

So please respond if you think history should go to stable immidiatly, otherwise I will do it at weekend

**Comment by foxriver76** [comment]
Problem is, the previous version had adapter-core `^2.6.0` and in cases where it was not automatically installed to `2.6.8`, it has problems with controller v5, so super edgy.

**Comment by foxriver76** [comment]
And weekend is fine.

**Comment by mcm1957** [comment]
728 User
OK

**Pull request merged**
