### PR TITLE
Shelly Version 3.3.3

### PR DESCRIPTION
**Pull request by schmupu**
Stable Version 3.3.3
* (Stübi) - Use only version with Shelly firmware greater equal v1.7.0 . Shelly firmware less v1.7.0 will not be supported by this Shelly adapter version anymore
* (Stübi) - Add state vibration and tilt to Shelly DW
* (Stübi) - Add polltime to index_m.html  
* (Stübi) - Fix RGBW2 with FW 1.7 - Issue #161
* (Stübi) - Add state Button Type for Shelly  1, 1PM, 2, 2.5 - Issue #157
* (Stübi) - Add state Button Reverse for Shelly 1, 1PM, 2, 2.5
* (Stübi) - Add firmware update button
* (Stübi) - Fix auto firmware update
* (Stübi) - Add state external humidity to Shelly 1 / 1PM - Issue #160
* (Stübi) - Add helper library and cleanup source code
* (Stübi) - Add Shelly I3

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.shelly](https://github.com/schmupu/ioBroker.shelly)
[Downloads](https://www.npmjs.com/package/iobroker.shelly) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.shelly/)

- [ ] :heavy_exclamation_mark: [E506] Word "Shelly devices that shall not be displayed" is not translated to german in [admin/words.js](https://github.com/schmupu/ioBroker.shelly/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "Shelly devices that shall not be displayed" is not translated to russian in [admin/words.js](https://github.com/schmupu/ioBroker.shelly/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/schmupu/ioBroker.shelly", press the first "Edit" button you will find on the page and add the description.
- [ ] :eyes: [W505] setTimeout found in "shelly.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@schmupu please check the texts that are translated incomplete please ... but I will merge still.
More important is to chekc the Timeouts that they are cancelled correctly on unload!

**Comment by schmupu** [comment]
Thanks! I forgot to delete the old text. That is the reason off missing translation

**Pull request merged**
