### PR TITLE
add adapter pid to latest

### PR DESCRIPTION
**Pull request by mcm1957**
Please add adapter pid to latest repository.

Link to adapter repo: https://github.com/iobroker-community-adapters/ioBroker.pid

Forum Thread: https://forum.iobroker.net/topic/64250/test-neuer-adapter-pid-pid-regler-v0-0-x

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nsclient](https://github.com/iobroker-community-adapters/ioBroker.nsclient)
[Downloads](https://www.npmjs.com/package/iobroker.nsclient) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.nsclient/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.nsclient)!. Please execute in adapter directory: `npm owner add bluefox iobroker.nsclient`
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2023 mcm1957 <mcm57@gmx.at>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.nsclient/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 mcm1957 <mcm57@gmx.at>" at the start of LICENSE
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.nsclient/blob/master/io-package.json)

### [ioBroker.acme](https://github.com/iobroker-community-adapters/ioBroker.acme)
[Downloads](https://www.npmjs.com/package/iobroker.acme) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.acme/)

- [ ] :heavy_exclamation_mark: [E606] Current adapter version 0.1.0 not found in [README.md](https://github.com/iobroker-community-adapters/ioBroker.acme/blob/master/README.md)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.acme/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/iobroker-community-adapters/ioBroker.acme/blob/master/package.json) (0.1.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.acme) (0.0.2)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.frontier_silicon](https://github.com/iobroker-community-adapters/ioBroker.frontier_silicon)
[Downloads](https://www.npmjs.com/package/iobroker.frontier_silicon) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.frontier_silicon/)

:thumbsup: No errors found

### [ioBroker.logparser](https://github.com/iobroker-community-adapters/ioBroker.logparser)
[Downloads](https://www.npmjs.com/package/iobroker.logparser) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.logparser/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.logparser/blob/master/io-package.json)


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
The adapter checker checked several adapter BUT NOT the pid adapter !?!?

**Comment by mcm1957** [comment]
MANUAL check (using iobroker,.dev):

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nsclient](https://github.com/iobroker-community-adapters/ioBroker.nsclient)
[Downloads](https://www.npmjs.com/package/iobroker.nsclient) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.nsclient/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.nsclient)!. Please execute in adapter directory: `npm owner add bluefox iobroker.nsclient`
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2023 mcm1957 <mcm57@gmx.at>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.nsclient/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 mcm1957 <mcm57@gmx.at>" at the start of LICENSE
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.nsclient/blob/master/io-package.json)

### [ioBroker.acme](https://github.com/iobroker-community-adapters/ioBroker.acme)
[Downloads](https://www.npmjs.com/package/iobroker.acme) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.acme/)

- [ ] :heavy_exclamation_mark: [E606] Current adapter version 0.1.0 not found in [README.md](https://github.com/iobroker-community-adapters/ioBroker.acme/blob/master/README.md)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.acme/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/iobroker-community-adapters/ioBroker.acme/blob/master/package.json) (0.1.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.acme) (0.0.2)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.frontier_silicon](https://github.com/iobroker-community-adapters/ioBroker.frontier_silicon)
[Downloads](https://www.npmjs.com/package/iobroker.frontier_silicon) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.frontier_silicon/)

:thumbsup: No errors found

### [ioBroker.logparser](https://github.com/iobroker-community-adapters/ioBroker.logparser)
[Downloads](https://www.npmjs.com/package/iobroker.logparser) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.logparser/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.logparser/blob/master/io-package.json)


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nsclient](https://github.com/iobroker-community-adapters/ioBroker.nsclient)
[Downloads](https://www.npmjs.com/package/iobroker.nsclient) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.nsclient/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.nsclient)!. Please execute in adapter directory: `npm owner add bluefox iobroker.nsclient`
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2023 mcm1957 <mcm57@gmx.at>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.nsclient/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 mcm1957 <mcm57@gmx.at>" at the start of LICENSE
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.nsclient/blob/master/io-package.json)

### [ioBroker.acme](https://github.com/iobroker-community-adapters/ioBroker.acme)
[Downloads](https://www.npmjs.com/package/iobroker.acme) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.acme/)

- [ ] :heavy_exclamation_mark: [E606] Current adapter version 0.1.0 not found in [README.md](https://github.com/iobroker-community-adapters/ioBroker.acme/blob/master/README.md)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.acme/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/iobroker-community-adapters/ioBroker.acme/blob/master/package.json) (0.1.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.acme) (0.0.2)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.frontier_silicon](https://github.com/iobroker-community-adapters/ioBroker.frontier_silicon)
[Downloads](https://www.npmjs.com/package/iobroker.frontier_silicon) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.frontier_silicon/)

:thumbsup: No errors found

### [ioBroker.logparser](https://github.com/iobroker-community-adapters/ioBroker.logparser)
[Downloads](https://www.npmjs.com/package/iobroker.logparser) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.logparser/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.logparser/blob/master/io-package.json)


*Add comment "RE-CHECK!" to start check anew*

**Pull request closed without merging**
