### PR TITLE
SIA Adapter for alarm systems

### PR DESCRIPTION
**Pull request by schmupu**
SIA Adapter for alarm systems like Lupusec, ABUS, ...

### CODE REVIEW

**Comment by schmupu** [comment]
the state roles should all okay

**Comment by GermanBluefox** [comment]
https://github.com/schmupu/ioBroker.sia/issues/1

**Comment by Apollon77** [comment]
Additional please also:
- io.package in common.license the license needs to be defined

**Comment by schmupu** [comment]
Changed the roles for the states like described in [](https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md)

**Pull request merged**
