### PR TITLE
vodafone speedtest to latest

### PR DESCRIPTION
**Pull request by peterbaumert**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.coronavirus-statistics](https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics)
[Downloads](https://www.npmjs.com/package/iobroker.coronavirus-statistics) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.coronavirus-statistics/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.coronavirus-statistics) are broken. Please fix.

### [ioBroker.vodafone-speedtest](https://github.com/peterbaumert/ioBroker.vodafone-speedtest)
[Downloads](https://www.npmjs.com/package/iobroker.vodafone-speedtest) 
[NPM](https://nodei.co/npm/iobroker.vodafone-speedtest/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "vodafone-speedtest" in latest repository

### [ioBroker.windows-control](https://github.com/Mic-M/ioBroker.windows-control)
[Downloads](https://www.npmjs.com/package/iobroker.windows-control) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.windows-control/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by peterbaumert** [comment]
I dont know what to fix here actually? I think this is an error of travis maybe?

**Comment by Apollon77** [comment]
Nothing to do for you ... everything ok

**Comment by GermanBluefox** [comment]
https://github.com/peterbaumert/ioBroker.vodafone-speedtest/issues/2

**Comment by peterbaumert** [comment]
> [peterbaumert/ioBroker.vodafone-speedtest#2](https://github.com/peterbaumert/ioBroker.vodafone-speedtest/issues/2)

fixed and new release done

**Pull request merged**
