### PR TITLE
Add operating-hours to latest

### PR DESCRIPTION
**Pull request by BenAhrdt**
Please add my adapter ioBroker.operating-hours to latest.

*This pull request was created by https://www.iobroker.dev 79ffd9b.*

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by BenAhrdt** [comment]
i updated to a new version (bugfix)

**Comment by BenAhrdt** [comment]
i updated to 0.0.13
(Dependencies updated)

**Comment by BenAhrdt** [comment]
is there anything to do?

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.operating-hours](https://github.com/BenAhrdt/ioBroker.operating-hours)
[Downloads](https://www.npmjs.com/package/iobroker.operating-hours) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.operating-hours/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/BenAhrdt/ioBroker.operating-hours/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "operating-hours" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by BenAhrdt** [comment]
So everything is ok?

**Comment by Apollon77** [comment]
For the automatic checker yes

**Comment by Apollon77** [comment]
all good, nothing to do for you

**Comment by Apollon77** [comment]
Hi,

All good, welcome in the repo

**Pull request merged**
