### PR TITLE
added notification-manager to latest

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.notification-manager](https://github.com/foxriver76/ioBroker.notification-manager)
[Downloads](https://www.npmjs.com/package/iobroker.notification-manager) 
[NPM](https://nodei.co/npm/iobroker.notification-manager/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.notification-manager)!. Please execute in adapter directory: `npm owner add bluefox iobroker.notification-manager`
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/foxriver76/ioBroker.notification-manager", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/foxriver76/ioBroker.notification-manager/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "notification-manager" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.notification-manager](https://github.com/foxriver76/ioBroker.notification-manager)
[Downloads](https://www.npmjs.com/package/iobroker.notification-manager) 
[NPM](https://nodei.co/npm/iobroker.notification-manager/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.notification-manager)!. Please execute in adapter directory: `npm owner add bluefox iobroker.notification-manager`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/foxriver76/ioBroker.notification-manager/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "notification-manager" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
I think BF needs to accept the invite first.

**Comment by mcm1957** [comment]
> I think BF needs to accept the invite first.

Yes, thats OK
I just wunder why [E802] no topics is reported while I clearly can see some ?

**Comment by foxriver76** [comment]
It is no longer displayed in the update ;-)

**Comment by mcm1957** [comment]
> It is no longer displayed in the update ;-)

OK - caching problem.
AT MY BROWSER I ASSUME :-).

Let me know if you prefer / need an urgent release. Otherwise the lates requests are planned to be processed in app. 2 weeks.

**Comment by foxriver76** [comment]
No hurries. Thanks for your effort.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.notification-manager](https://github.com/foxriver76/ioBroker.notification-manager)
[Downloads](https://www.npmjs.com/package/iobroker.notification-manager) 
[NPM](https://nodei.co/npm/iobroker.notification-manager/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/foxriver76/ioBroker.notification-manager/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "notification-manager" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
