### PR TITLE
Add egigeozone2 1.0.6 to stable

### PR DESCRIPTION
**Pull request by obakuhl**
Please update my adapter ioBroker.egigeozone2 to version 1.0.6.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by obakuhl** [comment]
The year is indeed specified within the license file:

Copyright (c) 2017 BasGo
Copyright (c) 2024 obakuhl, iobroker-community

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Please see PR https://github.com/obakuhl/ioBroker.egigeozone2/pull/45
Latest copyright year must be first within file.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Your Adapter has been added to stable repository. If you like you can extend the news message here:

https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/history/history.md

If you add some more information / description, please consider to add this information to README.md too.

If you have any questions related to the news file, please contact @Apollon77 for further information.

Please note, that the PR announcing the new adapter at stable might not be merged.
https://github.com/ioBroker/ioBroker.docs/pull/

**Pull request merged**
