### PR TITLE
Added vis-inventwo adapter to latest

### PR DESCRIPTION
**Pull request by jkvarel**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Please fix:
image

**Comment by GermanBluefox** [comment]
Test message

**Comment by GermanBluefox** [comment]
## Automated adapter checker
### ioBroker.vis-inventwo
 * [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.vis-inventwo"
 * [E300] Not found on travis. Please setup travis
 * [E802] No topics found in the repository. Please go to "https://github.com/inventwo/ioBroker.vis-inventwo" and press "Manage topics"
 * [E604] No "## License" found in README.md

**Comment by GermanBluefox** [comment]
## Automated adapter checker
### ioBroker.vis-inventwo
 * [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.vis-inventwo"
 * [E300] Not found on travis. Please setup travis
 * [E802] No topics found in the repository. Please go to "https://github.com/inventwo/ioBroker.vis-inventwo" and press "Manage topics"
 * [E604] No "## License" found in README.md

**Comment by GermanBluefox** [comment]
## Automated adapter checker
### [ioBroker.vis-inventwo](https://github.com/inventwo/ioBroker.vis-inventwo)
 * [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: `npm owner add bluefox iobroker.vis-inventwo`
 * [E300] Not found on [travis](https://travis-ci.org/). Please setup travis
 * [E802] No topics found in the repository. Please go to "https://github.com/inventwo/ioBroker.vis-inventwo" and press `Manage topics`
 * [E604] No `## License` found in [README.md](https://github.com/inventwo/ioBroker.vis-inventwo/blob/master/README.md)

**Comment by Apollon77** [comment]
Additional review comments:
* Please translate news and other texts. you can use https://translator.iobroker.in/ for it
* I checked the adapter code. Why the adapter is defined as "deamon"? This code is doing nothing. SHould be changed to "once" I think

**Comment by GermanBluefox** [comment]
> Additional review comments:
> 
> * Please translate news and other texts. you can use https://translator.iobroker.in/ for it
> * I checked the adapter code. Why the adapter is defined as "deamon"? This code is doing nothing. SHould be changed to "once" I think

And unused handler must be deleted: https://github.com/inventwo/ioBroker.vis-inventwo/blob/master/main.js#L25

**Comment by jkvarel** [comment]
Everything is fixed :)

**Comment by Apollon77** [comment]
RE_CHECK!

**Comment by GermanBluefox** [comment]
> RE_CHECK!

`RE-CHECK!` (only one word :) )

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-inventwo](https://github.com/inventwo/ioBroker.vis-inventwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-inventwo) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-inventwo/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "vis-inventwo" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-inventwo](https://github.com/inventwo/ioBroker.vis-inventwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-inventwo) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-inventwo/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "vis-inventwo" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jkvarel** [comment]
RE-CHECK

**Comment by jkvarel** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-inventwo](https://github.com/inventwo/ioBroker.vis-inventwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-inventwo) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-inventwo/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "vis-inventwo" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
