### PR TITLE
add tinymqttbroker 0.0.5 to stable

### PR DESCRIPTION
**Pull request by HGlab01**

### CODE REVIEW

**Comment by mcm1957** [comment]
Did you create a tester Thread at forum?
If not, please create one wo check for some feedback.

If already done, please provide link. 
ANY discussion/test topic is ok, it need not be at tester forum althgough this is the prefered location.

see https://github.com/ioBroker/ioBr

**Comment by HGlab01** [comment]
I did a lot of stress tests and in my installation it is the underlaying adapter for a lot of other functionality.
In addition it is installes 24times by other users.

image

**Comment by mcm1957** [comment]
I don't have any doubt that the adapter is very well tested.

But please open a test thread so that users
-) are informed about the new adapter
-) can give feedback

Searching for tinymqttbroker did not list any topic at forum.

**Comment by HGlab01** [comment]
you could trust the PO of the adapter, as I have a bit of experience with iob adapters.
Or you could trust 25 installs and no sentry entry so far.
Nevertheless I created a forum entry right now
https://forum.iobroker.net/topic/68254/test-adapter-tinymqttbroker-v0-0-x-github

**Comment by mcm1957** [comment]
0.5.0 created 11.09.2023
9 user ...
OK

**Pull request merged**
