### PR TITLE
add nuki-extended to stable

### PR DESCRIPTION
**Pull request by Zefau**
add nuki-extended to stable and furthermore add nuki2 to stable with v1.0.5 for deprecation notice (will be removed in one month)

### CODE REVIEW

**Comment by Apollon77** [comment]
Please correct image link

**Comment by Apollon77** [comment]
Can it be that nuki2 is not in latest repo?

**Comment by Zefau** [comment]
No it has been removed from latest repo and replaced with nuki-extended. 

The addition to the stable repo is only to push the version number (and add the deprecation notice) for those who haven't upgraded with the latest repo so far.

**Comment by Apollon77** [comment]
Then why you add nuki2 to stable repo when it was never there?? AN adapter needs to be in latest and stable at the same time

**Comment by Zefau** [comment]
Nuki2 v1.0.4 was added to stable on Sep 4, 2019 (c60d7dbdc20797fd3ba1cd93f09561f441616df5). GermanBluefox unfortunately removed nuki2 when nuki-extended was introduced to latest (3a1aba5804491f8edb5f6c03a1db2f1ceb7b2a3a).

My objective is to add the deprecation notice (which has been added to Nuki2 v1.0.5).

**Comment by Apollon77** [comment]
Then please readd nuki2 to latest too ...

**Comment by Zefau** [comment]
I updated the pr to only add nuki-extended to stable.

**Comment by Zefau** [comment]
@Apollon77 is that ok? :-)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.nuki-extended/issues/55

**Comment by Apollon77** [comment]
yes

**Pull request merged**
