### PR TITLE
include oilfox

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by Apollon77** [comment]
Cool, but some smaller things:
- check the warning in adapter testing please and fix accordingly: https://travis-ci.org/iobroker-community-adapters/ioBroker.oilfox/jobs/476544443#L1297
- gulpfile.js is missing. Please get from template
- somehow the adapter testing is still not workig ... reason is that you now have removed the only "it" method in testing. Please add one "it" with only a 1second timeout. This shuld fix it ;-)

**Comment by jogibear9988** [comment]
I don't understand the third warning: WARNING: Admin3 support is missing! Please add it
I have a index_m.html

**Comment by Apollon77** [comment]
comes from missing gulpfile.js :-)

**Comment by jogibear9988** [comment]
possibility to retrigger?

**Comment by Apollon77** [comment]
welcome to repo :-)

**Comment by Apollon77** [comment]
Repo should be updated in 10 mins

**Pull request merged**
