### PR TITLE
Updated luftdaten, octoprint, youtube, lametric, trashschedule

### PR DESCRIPTION
**Pull request by klein0r**

### CODE REVIEW

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lametric](https://github.com/klein0r/ioBroker.lametric)
[Downloads](https://www.npmjs.com/package/iobroker.lametric) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lametric/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/klein0r/ioBroker.lametric) are broken. Please fix.

### [ioBroker.luftdaten](https://github.com/klein0r/ioBroker.luftdaten)
[Downloads](https://www.npmjs.com/package/iobroker.luftdaten) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luftdaten/)

:thumbsup: No errors found

### [ioBroker.octoprint](https://github.com/klein0r/ioBroker.octoprint)
[Downloads](https://www.npmjs.com/package/iobroker.octoprint) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.octoprint/)

:thumbsup: No errors found

### [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule)
[Downloads](https://www.npmjs.com/package/iobroker.trashschedule) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.trashschedule/)

:thumbsup: No errors found

### [ioBroker.youtube](https://github.com/klein0r/ioBroker.youtube)
[Downloads](https://www.npmjs.com/package/iobroker.youtube) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.youtube/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/klein0r/ioBroker.youtube) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lametric](https://github.com/klein0r/ioBroker.lametric)
[Downloads](https://www.npmjs.com/package/iobroker.lametric) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lametric/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/klein0r/ioBroker.lametric) are broken. Please fix.

### [ioBroker.luftdaten](https://github.com/klein0r/ioBroker.luftdaten)
[Downloads](https://www.npmjs.com/package/iobroker.luftdaten) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luftdaten/)

- [ ] :heavy_exclamation_mark: [E504] "main.js found in [package.json](https://github.com/klein0r/ioBroker.luftdaten/blob/master/package.json), but not found as file

### [ioBroker.octoprint](https://github.com/klein0r/ioBroker.octoprint)
[Downloads](https://www.npmjs.com/package/iobroker.octoprint) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.octoprint/)

:thumbsup: No errors found

### [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule)
[Downloads](https://www.npmjs.com/package/iobroker.trashschedule) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.trashschedule/)

:thumbsup: No errors found

### [ioBroker.youtube](https://github.com/klein0r/ioBroker.youtube)
[Downloads](https://www.npmjs.com/package/iobroker.youtube) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.youtube/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/klein0r/ioBroker.youtube) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lametric](https://github.com/klein0r/ioBroker.lametric)
[Downloads](https://www.npmjs.com/package/iobroker.lametric) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lametric/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/klein0r/ioBroker.lametric) are broken. Please fix.

### [ioBroker.luftdaten](https://github.com/klein0r/ioBroker.luftdaten)
[Downloads](https://www.npmjs.com/package/iobroker.luftdaten) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luftdaten/)

:thumbsup: No errors found

### [ioBroker.octoprint](https://github.com/klein0r/ioBroker.octoprint)
[Downloads](https://www.npmjs.com/package/iobroker.octoprint) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.octoprint/)

:thumbsup: No errors found

### [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule)
[Downloads](https://www.npmjs.com/package/iobroker.trashschedule) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.trashschedule/)

:thumbsup: No errors found

### [ioBroker.youtube](https://github.com/klein0r/ioBroker.youtube)
[Downloads](https://www.npmjs.com/package/iobroker.youtube) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.youtube/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/klein0r/ioBroker.youtube) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lametric](https://github.com/klein0r/ioBroker.lametric)
[Downloads](https://www.npmjs.com/package/iobroker.lametric) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lametric/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/klein0r/ioBroker.lametric) are broken. Please fix.

### [ioBroker.youtube](https://github.com/klein0r/ioBroker.youtube)
[Downloads](https://www.npmjs.com/package/iobroker.youtube) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.youtube/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/klein0r/ioBroker.youtube) are broken. Please fix.

### [ioBroker.luftdaten](https://github.com/klein0r/ioBroker.luftdaten)
[Downloads](https://www.npmjs.com/package/iobroker.luftdaten) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luftdaten/)

:thumbsup: No errors found

### [ioBroker.octoprint](https://github.com/klein0r/ioBroker.octoprint)
[Downloads](https://www.npmjs.com/package/iobroker.octoprint) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.octoprint/)

:thumbsup: No errors found

### [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule)
[Downloads](https://www.npmjs.com/package/iobroker.trashschedule) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.trashschedule/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by klein0r** [comment]
@Apollon77 Irgendwie zeigt der Checker hier noch immer an, dass die Tests broken sind, obwohl das im zweiten Commit vom Pull Request behoben wurde. Woran kann das liegen?

**Comment by Apollon77** [comment]
all good, shows false positives sometimes

**Pull request merged**
