### PR TITLE
update

### PR DESCRIPTION
**Pull request by arteck**
hs100
fullybrowser

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.fullybrowser](https://github.com/arteck/ioBroker.fullybrowser)
[Downloads](https://www.npmjs.com/package/iobroker.fullybrowser) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fullybrowser/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.fullybrowser)!. Please execute in adapter directory: `npm owner add bluefox iobroker.fullybrowser`
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2014-2020 Arthur Rupp <arteck@outlook.com>" at the start of LICENSE
- [ ] :eyes: [W901] .gitignore not found

### [ioBroker.hs100](https://github.com/arteck/ioBroker.hs100)
[Downloads](https://www.npmjs.com/package/iobroker.hs100) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hs100/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.hs100)!. Please execute in adapter directory: `npm owner add bluefox iobroker.hs100`
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/arteck/ioBroker.hs100) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/arteck/ioBroker.hs100" and press `Manage topics`
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2014-2020 Arthur Rupp <arteck@outlook.com>" at the start of LICENSE
- [ ] :eyes: [W901] .gitignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
@arteck  ?

**Comment by Apollon77** [comment]
@arteck

**Comment by arteck** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.fullybrowser](https://github.com/arteck/ioBroker.fullybrowser)
[Downloads](https://www.npmjs.com/package/iobroker.fullybrowser) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fullybrowser/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/arteck/ioBroker.fullybrowser) are broken. Please fix.

### [ioBroker.hs100](https://github.com/arteck/ioBroker.hs100)
[Downloads](https://www.npmjs.com/package/iobroker.hs100) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hs100/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
both adapter were updated separately in the meanttime

**Pull request closed without merging**
