### PR TITLE
Update stable versions and add volvo adapter to stable

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
Better to separate stable and new latest ... now all need to wait for review

**Comment by Apollon77** [comment]
RE_CHECK!

**Comment by TA2k** [comment]
separated

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.gruenbeck](https://github.com/TA2k/ioBroker.gruenbeck)
[Downloads](https://www.npmjs.com/package/iobroker.gruenbeck) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.gruenbeck/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/TA2k/ioBroker.gruenbeck/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/TA2k/ioBroker.gruenbeck/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 tomboxi <tombox2020@gmail.com>" at the end of [README.md](https://github.com/TA2k/ioBroker.gruenbeck/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2020 tomboxi <tombox2020@gmail.com>" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore

### [ioBroker.mercedesme](https://github.com/TA2k/ioBroker.mercedesme)
[Downloads](https://www.npmjs.com/package/iobroker.mercedesme) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mercedesme/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/TA2k/ioBroker.mercedesme/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/TA2k/ioBroker.mercedesme/blob/master/io-package.json)

### [ioBroker.nina](https://github.com/TA2k/ioBroker.nina)
[Downloads](https://www.npmjs.com/package/iobroker.nina) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.nina/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/TA2k/ioBroker.nina/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/TA2k/ioBroker.nina/blob/master/io-package.json)

### [ioBroker.velux](https://github.com/TA2k/ioBroker.velux)
[Downloads](https://www.npmjs.com/package/iobroker.velux) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.velux/)

:thumbsup: No errors found

### [ioBroker.volvo](https://github.com/TA2k/ioBroker.volvo)
[Downloads](https://www.npmjs.com/package/iobroker.volvo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.volvo/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/TA2k/ioBroker.volvo/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/TA2k/ioBroker.volvo/blob/master/io-package.json)

### [ioBroker.vw-connect](https://github.com/TA2k/ioBroker.vw-connect)
[Downloads](https://www.npmjs.com/package/iobroker.vw-connect) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vw-connect/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/TA2k/ioBroker.vw-connect/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/TA2k/ioBroker.vw-connect/blob/master/io-package.json)

### [ioBroker.mystrom](https://github.com/TA2k/ioBroker.mystrom)
[Downloads](https://www.npmjs.com/package/iobroker.mystrom) 
[NPM](https://nodei.co/npm/iobroker.mystrom/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/TA2k/ioBroker.mystrom", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/TA2k/ioBroker.mystrom", press the settings button beside the about title and add some topics.
- [ ] :heavy_exclamation_mark: [E603] NO "## Changelog" found in [README.md](https://github.com/TA2k/ioBroker.mystrom/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E604] No `## License` found in [README.md](https://github.com/TA2k/ioBroker.mystrom/blob/master/README.md)
- [ ] :eyes: [W400] Cannot find "mystrom" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@TA2k I accept ... please add the montioned new files to io-package  for next version :-) Thank you!

**Pull request merged**
