### PR TITLE
added ocpp to latest

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.froeling](https://github.com/TA2k/ioBroker.froeling)
[Downloads](https://www.npmjs.com/package/iobroker.froeling) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.froeling/)

:thumbsup: No errors found

### [ioBroker.lg-thinq](https://github.com/TA2k/ioBroker.lg-thinq)
[Downloads](https://www.npmjs.com/package/iobroker.lg-thinq) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-thinq/)

:thumbsup: No errors found

### [ioBroker.ocpp](https://github.com/foxriver76/ioBroker.ocpp)
[Downloads](https://www.npmjs.com/package/iobroker.ocpp) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.ocpp/)

- [ ] :heavy_exclamation_mark: [object Object]

### [ioBroker.openhab](https://github.com/iobroker-community-adapters/ioBroker.openhab)
[Downloads](https://www.npmjs.com/package/iobroker.openhab) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.openhab/)

- [ ] :heavy_exclamation_mark: [E104] No common.titleLang found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.openhab) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2017-2022 bluefox <dogafox@gmail.com>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2017-2022 bluefox <dogafox@gmail.com>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.rainbird](https://github.com/StrathCole/ioBroker.rainbird)
[Downloads](https://www.npmjs.com/package/iobroker.rainbird) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.rainbird/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/StrathCole/ioBroker.rainbird/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/StrathCole/ioBroker.rainbird/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 Marius Burkard <m.burkard@pixcept.de>" at the end of [README.md](https://github.com/StrathCole/ioBroker.rainbird/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Marius Burkard <m.burkard@pixcept.de>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by ldittmar81** [comment]
@foxriver76 Please correct the automatically found errors.

**Comment by foxriver76** [comment]
> * [object Object]

@ldittmar81 Okay

**Comment by ldittmar81** [comment]
Please close https://github.com/ioBroker/AdapterRequests/issues/582 after review

**Comment by Apollon77** [comment]
Hi, 

some review comments:
* please put admin dep (https://github.com/foxriver76/ioBroker.ocpp/blob/main/io-package.json#L144) in globalDepenencies
* you might want to add a bit error handling on https://github.com/foxriver76/ioBroker.ocpp/blob/main/src/main.ts#L64 ? :-)

Rest is ok

**Comment by foxriver76** [comment]
Admin fixed,

Error handling not sure if theres something catchable and if I can only restart, it's a custom impl https://github.com/elifTech/cpd-ocpp/blob/969d124a8c6f87d67f854246be1356fe11afe927/src/centralSystem.js#L20

**Pull request merged**
