### PR TITLE
Add waste-collection-erding to latest

### PR DESCRIPTION
**Pull request by Sickboy78**
Please add my adapter ioBroker.waste-collection-erding to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
@klein0r 
@Sickboy78 

Does the existing adapter **trashschedule** (https://github.com/klein0r/ioBroker.trashschedule) already support "erding"?
If  not, wouldn't it be an option to integrate this supplier into trashschedule? I assume that klein0r will accept a PR for this.
Do we need another waste adapter dedicated to a region?

@Apollon77 
Some general oppinion?

**Comment by Sickboy78** [comment]
Imho Erding is currently not supported since LK Erding does not provide an ICAL calender (only ICS and CSV for download) and the API portal.awido.de is not integrated into trashschedule.
But it would totally make sence to integrate it, if this is possible. Need to take a closer look though ...

**Comment by mcm1957** [comment]
I would suggest that you take a look if you have time and eventually discuss a solution with klein0r. Let's wait for the result. 
Thanks for you cooperation.

**Comment by simatec** [comment]
If the adapter can be integrated independently and not in Trashschedule, I would ask you to migrate the adapter to jsonConfig.

**Comment by Sickboy78** [comment]
@klein0r @mcm1957 

While digging into the Awido API for integration with trashschedule, I found that it is used by nearly 50 districts and cities, i.e. it would add hundreds of cities to be available in trashschedule.
So heres the PR:
https://github.com/klein0r/ioBroker.trashschedule/pull/285

**Comment by Sickboy78** [comment]
Functionality was integrated with trashschedule, therfore canceling this PR.

**Pull request closed without merging**
