### PR TITLE
Update fritzdect to 2.5.2

### PR DESCRIPTION
**Pull request by foxthefox**

### CODE REVIEW

**Comment by mcm1957** [comment]
2.5.2 created 12.10.2023

**Comment by mcm1957** [comment]
@foxthefox 
There seems to be some issue with 2.5.2
https://github.com/foxthefox/ioBroker.fritzdect/issues/459
https://github.com/foxthefox/ioBroker.fritzdect/issues/460
https://forum.iobroker.net/topic/44473/fritzbox-dect-adapter/19

Please try to analyze / fix the problem. Does not make sense to push 2.5.2 to stable as long as that problem is not anylzed or solved.

**Please add a commetn as soon as the above problem is solved or you want to push 2.5.2 to stable anyway**

**Comment by mcm1957** [comment]
@foxthefox
Problems mentioned above look like fixed with 2.5.3.

Please let me know wther a stable upodate to 2.5.2 would be really useful now. I suggest to wait for 2.5.3 to be old enough for stable and to close here.

**Comment by foxthefox** [comment]
yes, 2.5.3 would be the next version for stable.

**Comment by mcm1957** [comment]
Then lets close here.

Please open a new PR as soon as 2.5.3 is old eneogh and you think ist Ok too.

THANKS for sepnding your time for this adapter and ioBroker.

**Pull request closed without merging**
