### PR TITLE
Bosch Smart Home Bridge Adapter stable 0.1.7

### PR DESCRIPTION
**Pull request by holomekc**
(holomekc) Improved error handling
(holomekc) Added open doors and windows feature
(holomekc) functions and rooms are only added for new channels
(holomekc) increase timeout for requests which expect to contain more data

### CODE REVIEW

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bshb](https://github.com/holomekc/ioBroker.bshb)
[Downloads](https://www.npmjs.com/package/iobroker.bshb) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.bshb/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "build/main.js", but no clearTimeout detected
- [ ] :eyes: [W801] .npmignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
Can you stop these timers in unload?
https://github.com/holomekc/ioBroker.bshb/blob/master/src/main.ts#L229
https://github.com/holomekc/ioBroker.bshb/blob/master/src/main.ts#L237

**Comment by holomekc** [comment]
Thanks for the feedback. Is this ok?
https://github.com/holomekc/ioBroker.bshb/pull/22

**Comment by GermanBluefox** [comment]
https://github.com/holomekc/ioBroker.bshb/pull/24

**Comment by holomekc** [comment]
Thx. I merged the changes.

**Comment by GermanBluefox** [comment]
On npm is still 0.1.7...

**Comment by holomekc** [comment]
Hi. Yes I know. As mentioned before I was waiting with publishing in case something else needs to be changed. So I assume it is fine now.

I published 0.1.8 in npm right now.

**Pull request merged**
