### PR TITLE
added benchmark stable

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.benchmark](https://github.com/foxriver76/ioBroker.benchmark)
[Downloads](https://www.npmjs.com/package/iobroker.benchmark) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.benchmark/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:foxriver76/ioBroker.benchmark.git. Expected: git+https://github.com/foxriver76/ioBroker.benchmark.git
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/foxriver76/ioBroker.benchmark/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.benchmark)!. Please execute in adapter directory: `npm owner add bluefox iobroker.benchmark`
- [ ] :heavy_exclamation_mark: [E402] Types of adapter in latest repository and in [io-package.json](https://github.com/foxriver76/ioBroker.benchmark/blob/master/io-package.json) are different "utility" !== "hardware"
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "build/main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.benchmark](https://github.com/foxriver76/ioBroker.benchmark)
[Downloads](https://www.npmjs.com/package/iobroker.benchmark) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.benchmark/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:foxriver76/ioBroker.benchmark.git. Expected: git+https://github.com/foxriver76/ioBroker.benchmark.git
- [ ] :heavy_exclamation_mark: [E152] common.dataSource type has an invalid type none
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.benchmark)!. Please execute in adapter directory: `npm owner add bluefox iobroker.benchmark`
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "build/main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
Compact mode not supported on purpose, thus timeouts also not important. BF is added, dataSource `none` is allowed

**Pull request merged**
