### PR TITLE
Add alias-manager

### PR DESCRIPTION
**Pull request by sbormann**
Added alias-manager

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/sbormann/ioBroker.alias-manager/blob/master/iob_npm.done)" found in repo! Please add it to .gitignore
- [ ] :eyes: [W400] Cannot find "alias-manager" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by sbormann** [comment]
RE-CHECK

**Comment by Apollon77** [comment]
Re-CHECK!

**Comment by sbormann** [comment]
Hi,
fehlt noch irgendwas von meiner Seite?
Ich habe RE-CHECK geschrieben, es ist aber nichts passiert...
VG!

**Comment by Apollon77** [comment]
Alles ok, wir müssen review machen

**Comment by Apollon77** [comment]
Hello,

sorry for the late review response. When I understand correctly this adapter is 100% executed in admin page, so you can remove main.js. with onlyWWW flag in io.packsge (https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json#L220) and mode= none (https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json#L223) also no process is uneededly started

Also some infos and maybe a screenshot could help in readme to get better understanding on functionality of the adapter

**Comment by Apollon77** [comment]
I basically can merge already ... or do you want to adjust the above?

**Comment by sbormann** [comment]
Hi Ingo, please merge! Tanks

**Pull request merged**
