### PR TITLE
zigbee 1.0.4

### PR DESCRIPTION
**Pull request by kirovilya**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.zigbee](https://github.com/ioBroker/ioBroker.zigbee)
[Downloads](https://www.npmjs.com/package/iobroker.zigbee) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.zigbee/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.zigbee)!. Please execute in adapter directory: `npm owner add bluefox iobroker.zigbee`


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.zigbee](https://github.com/ioBroker/ioBroker.zigbee)
[Downloads](https://www.npmjs.com/package/iobroker.zigbee) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.zigbee/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.zigbee)!. Please execute in adapter directory: `npm owner add bluefox iobroker.zigbee`


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@kirovilya Bluefix not shown for npm ...

**Comment by kirovilya** [comment]
image
hmm...
also, I am run `npm owner add bluefox iobroker.zigbee` on local machine

**Comment by GermanBluefox** [comment]
> iobroker.zigbee

image

**Comment by Apollon77** [comment]
Strange ... How we proceed? @GermanBluefox can you check if you have admin rights please? maybe it tis just a display thing - we already had that befroe

**Comment by Apollon77** [comment]
I would accept the PR now

**Pull request merged**
