### PR TITLE
Add egigeozone2 to latest

### PR DESCRIPTION
**Pull request by obakuhl**
Please add my adapter ioBroker.egigeozone2 to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

**Comment by mcm1957** [comment]
reminder 7.5.2024

**Comment by obakuhl** [comment]
RE-CHECK!

**Comment by obakuhl** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by obakuhl** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] errors reported by adapter checker must be fixed

  - Please update testing to current version. 
    This is required to use the standard github based tests. Your test-and-release is outdated / modified. This need s to be changed but will be listet as a seperate issue later.

  - "subscribe":"messagebox" is depracated and will stop working with up-coming js-controller 6. "messagebox" is also deprecated in meantime (although it will still work with js-controller 6) For a new adpater please replace both  with
     ```
        "supportedMessages": {
            "custom": true
        }
    ```
    See https://github.com/ioBroker/ioBroker.js-controller/blob/8be449d5c8664fd271d87f36dc8d70da8dc119dd/schemas/io-package.json#L742 for details.

- [ ] please verify that all dependencies are listed at package.json and up to date
  
  Assuming that you will require the standard node url package, you should requiring it using node: syntax. 
   ```const url = require('node:url');```
  Same relates to http and https requires.

- [ ]  outdated file index.html

  This adapter uses jsonConfig now. So the old configuration file admin(index.html is not used any more and should be removed.

- [ ] sensitive information, especially passwords should be stored encrypted
  
  You configuration seems to contain passwords (or other sensitive information) which is not stored encrypted. As long as those information is not stored inside a table you can encrypt and secure this infomation simply by adding the following configuration to io-package.json. The iob runtime will encrypt / decrypt the data as required; no addition programming effort is required. Note that users will need to reenter this info one time after adding encryption, so drop a note at release notes.
  ```
  "encryptedNative": [
    "password",
    "data2"
  ],
  "protectedNative": [
    "password",
    "data2"
  ],
  ```
  At least the password is sensitive and must be protected.

###

- [ ] invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```, i.e. by using the following snippet:
  ```
  function name2id(pName) {
      return (pName || '').replace(adapter.FORBIDDEN_CHARS, '_');
  }
  ```

  User date received via message must be filtered.

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whnever a dedicated role exists.

  As far as I noticed state roles are not set at all.

- [ ] useless subscribes

  Why do you subscribe to system.group.* and system.user.* ? I did not detect any onObject change handlers to react on changes reported by subscription.

- [ ] Check certificate handling / lets encrypt(?)

  Not sure whether le config at https://github.com/obakuhl/ioBroker.egigeozone2/blob/2a717360beb139065a34f5ef8047131ce89a878a/main.js#L52 refers to letsEncrypt. But lets encrypt has been removed from aadoter / js-controller and is now handles by acme adapter - as fars as I know. I do NOT know exact details but I suggest you discuss at telegramm dev channel or poll @Apollon77 to verify whterh adaptions are required for js-controller 5 and upcoming js-controller 6.

- [ ] check and adapt testing
  
  Standard iobroker testing is required but seems to be missing. Please add and setup ./github/workflows/test-and-release.yml

  Please use test-and.release workflow as provided by current templates using @iobroker/testing and standard test scripts at /test.  If needed I can provide a PR for it.  

  Of course you can add any additional tests - but standard tests are required.

- [ ] adapt testing to supported node releases

  As node 16 is end of life and will no longer be supported ioBroker github based tests removing node 16.x tests from matrix if still present.
  Tests for node 18 are mandatory as this is the recommended node version. 
  Tests for node 20 are mandatory unless you already know incompatibilities which cannot be fixed immidiatly. In this case please create a issue stating the problem and fix as soon as possible.
  
  So the recommended testmatrix is [18.x, 20.x] depending on engines requirments setting at package.json 

  Tests must be performed at all supported platforms (linux, windows, mac) unless special hardware or software restrictions prohibit this.
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
I've created PR https://github.com/obakuhl/ioBroker.egigeozone2/pull/21 to update testing to current standards. Please check / merge.

**Comment by mcm1957** [comment]
Did you check / fix the other comments?

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

reminder 28.5.2024

**Comment by obakuhl** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
The following issues are still open:
- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whnever a dedicated role exists.

  As far as I noticed state roles are not set at all.

  **Issue still open.** 
  Please evaluate / fix this. Every state must have a matching role assigned. Simply select the best matching role from the documenation listed abaove and ass "role":"..." to common part if state creation. You even have an example in your code at line 284 (https://github.com/obakuhl/ioBroker.egigeozone2/blob/7774291a846c18113f145fdc74aec613e758cc75/main.js#L284)

- [ ] useless subscribes

  Why do you subscribe to system.group.* and system.user.* ? I did not detect any onObject change handlers to react on changes reported by subscription.

  **Issue still open** 
  Please fix or explain the reason for those subscribes.
  Subscribing is used to activate a callback whenever an object hcnages. As you so not have any callback code within your adapter, those subsribes are uselass (in my ippinion). Is suggest to remove lines 51 - 53 (https://github.com/obakuhl/ioBroker.egigeozone2/blob/7774291a846c18113f145fdc74aec613e758cc75/main.js#L52)

- [ ] Check certificate handling / lets encrypt(?)

  Not sure whether le config at https://github.com/obakuhl/ioBroker.egigeozone2/blob/2a717360beb139065a34f5ef8047131ce89a878a/main.js#L52 refers to letsEncrypt. But lets encrypt has been removed from aadoter / js-controller and is now handles by acme adapter - as fars as I know. I do NOT know exact details but I suggest you discuss at telegramm dev channel or poll @Apollon77 to verify whterh adaptions are required for js-controller 5 and upcoming js-controller 6.

  **Issue still open** 
  As you die not yet check I'll try to get a feedback from core team if this code sequence is still valid for upcomin js-controller 6 and current admin.


The first two of them should be easy to fix.

Please add roles to every state. If you have further questions please ask.

Subscribes seem to be useless. As you do not know what they are used for, simply delete it. If something does no longer work afterwards, you know at least your code better :-).

SSL / Letx Encrypt is an area where several changes occured during the last months. Letx Encrypt and certificate handling has been removed from admin and will be dropped from js-controller with release 6. I contacted core team if this will affect you code and if there is already some change required. I'll give feedback as soon as I have new info.

Did you test you code using an https server? Does this work? Does this work using lets-encrypt certificates?

**Comment by obakuhl** [comment]
Thanks for the feedback. The first two issues were easy to fix as you said (I havent merged it to master yet) 😁

Regarding the third issue I need to check the details of that change. But since js-controller 6 is only in the alpha phase, is it a compromise to make this adapter available to everyone now and I work on the update in parallel?

**Comment by mcm1957** [comment]
I'm quite sure that ssl will not work with current stable admin / js-controller 5 too as lets-encrypt has been already removed from admin. Did you test https communication?

In general I would suggest to fix webserver before listing the adapter at latest. User can install it from npm anyway already - so the benefit of listing at latest would be minimal. js-controller is at alpha currently, but it will be available at latest in the near future (if no problems detected). 

Anyway - I will ask @Apollon77 how to proceed. My personal preference would be to not release a new adapzter to latest if it is already outdated at least in the near future.

As @Foxriver76 did some changes to webserver within a few hours the effort should not be big. But I would recommand to conatct him directly if you need help / explanation.

**Comment by foxriver76** [comment]
Using certificates directly is also deprecated before controller v6. In the end it is not much for you todo, likely makes things less complex. 

See example here https://github.com/ioBroker/webserver?tab=readme-ov-file#how-to

You use web server module instead of importing `node:http` or `node:https`. In your case you are doing a bit of "Das Rad neu erfinden" - unnecessary work and unnecessary sources of error. Certificate management is then done by the user itself via ACME adapter if someone needs Let's encrypt certificates.

**Comment by obakuhl** [comment]
RE-CHECK!

**Comment by obakuhl** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Rechecking:

-[x] reevaluate state roles

Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

Please avoid using general roles (state, value) whnever a dedicated role exists.

As far as I noticed state roles are not set at all.

Issue still open.
Please evaluate / fix this. Every state must have a matching role assigned. Simply select the best matching role from the documenation listed abaove and ass "role":"..." to common part if state creation. You even have an example in your code at line 284 (https://github.com/obakuhl/ioBroker.egigeozone2/blob/7774291a846c18113f145fdc74aec613e758cc75/main.js#L284)


-[x] useless subscribes

Why do you subscribe to system.group.* and system.user.* ? I did not detect any onObject change handlers to react on changes reported by subscription.

Issue still open
Please fix or explain the reason for those subscribes.
Subscribing is used to activate a callback whenever an object hcnages. As you so not have any callback code within your adapter, those subsribes are uselass (in my ippinion). Is suggest to remove lines 51 - 53 (https://github.com/obakuhl/ioBroker.egigeozone2/blob/7774291a846c18113f145fdc74aec613e758cc75/main.js#L52)


-[x] Check certificate handling / lets encrypt(?)

Not sure whether le config at https://github.com/obakuhl/ioBroker.egigeozone2/blob/2a717360beb139065a34f5ef8047131ce89a878a/main.js#L52 refers to letsEncrypt. But lets encrypt has been removed from aadoter / js-controller and is now handles by acme adapter - as fars as I know. I do NOT know exact details but I suggest you discuss at telegramm dev channel or poll @Apollon77 to verify whterh adaptions are required for js-controller 5 and upcoming js-controller 6.

Issue still open
As you die not yet check I'll try to get a feedback from core team if this code sequence is still valid for upcomin js-controller 6 and current admin.

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If another testing topic already exists, it' OK to continue using this topic too.

**Comment by obakuhl** [comment]
I have created a thread: https://forum.iobroker.net/topic/75530/test-adapter-egigeozone2

**Pull request merged**
