### PR TITLE
Add schwoerer-ventcube adapter

### PR DESCRIPTION
**Pull request by Excodibur**
Adapter zur Lüftungssteuerung der zentralen Lüftungsanlage "Ventcube" (Schwörerhaus KG)

### CODE REVIEW

**Comment by Excodibur** [comment]
https://forum.iobroker.net/topic/36535/neuer-adapter-schwoerer-ventcube

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.schwoerer-ventcube](https://github.com/Excodibur/ioBroker.schwoerer-ventcube)
[Downloads](https://www.npmjs.com/package/iobroker.schwoerer-ventcube) 
[NPM](https://nodei.co/npm/iobroker.schwoerer-ventcube/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 1.0.1
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E124] Main file not found under URL: https://raw.githubusercontent.com/Excodibur/ioBroker.schwoerer-ventcube/master/build/main.js
- [ ] :heavy_exclamation_mark: [E506] Word "server" is not translated to russian in [admin/words.js](https://github.com/Excodibur/ioBroker.schwoerer-ventcube/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "port" is not translated to russian in [admin/words.js](https://github.com/Excodibur/ioBroker.schwoerer-ventcube/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "interval" is not translated to russian in [admin/words.js](https://github.com/Excodibur/ioBroker.schwoerer-ventcube/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E504] "build/main.js found in [package.json](https://github.com/Excodibur/ioBroker.schwoerer-ventcube/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/Excodibur/ioBroker.schwoerer-ventcube", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "schwoerer-ventcube" in latest repository
- [ ] :eyes: [W801] .npmignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Excodibur** [comment]
RE-CHECK

**Comment by Excodibur** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.schwoerer-ventcube](https://github.com/Excodibur/ioBroker.schwoerer-ventcube)
[Downloads](https://www.npmjs.com/package/iobroker.schwoerer-ventcube) 
[NPM](https://nodei.co/npm/iobroker.schwoerer-ventcube/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "schwoerer-ventcube" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Excodibur** [comment]
Hinweis: Da der Adapter für die Ansteuerung der Ventcube-Lüftungsanlage der Firma Schwörerhaus KG entwickelt wurde und es sich hierbei um eine firmeneigene Lüftungslösung handelt, ist sowohl die Zielgruppe, als auch die Zahl der potentiellen Tester stark auf Kunden dieser spezifischen Hausbau-Firma beschränkt.

**Comment by DutchmanNL** [comment]
@Excodibur 

- At each call setObject is executed, please use setObjecNotExist
https://github.com/Excodibur/ioBroker.schwoerer-ventcube/blob/master/src/main.ts#L83-L90

- is it really needed to subscribe all states ?
https://github.com/Excodibur/ioBroker.schwoerer-ventcube/blob/master/src/main.ts#L106

**Comment by Excodibur** [comment]
@DutchmanNL 

1. Ok, I changed it now to **setObjectNotExistsAsync** in main.ts. I checked [adapter.js](https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L3194), but don't fully get the purpose of "NotExists". Is it there to prevent duplicate creation of a state-object with the same name?
2.  No, you are right - it is not needed. I limited it now to `parameters.*` .

I included those changes now in v1.1.1 and updated the release.

**Comment by Excodibur** [comment]
How do we proceed from here to get the adapter into your repo? Are further reviews required, or do I need to provide something in addition?

Since finding testers active in the ioBroker community is a bit difficult for this housevendor-specific climate-control solution, I can only provide working integration tests (see Github actions) againt a mockservice as proof at the moment.

**Comment by DutchmanNL** [comment]
Hi @Excodibur beschallt you did all you can and I previewed your adapter and looks fine for me.
End approval and merge is up to @Apollon77 he will take care of it as soon time allows it

So stupid a day only has 24hours .... :/

**Comment by Excodibur** [comment]
@DutchmanNL Thanks for the feedback! I understand of course and can relate quite a bit. ;-)

**Comment by Apollon77** [comment]
> Ok, I changed it now to setObjectNotExistsAsync in main.ts. I checked adapter.js, but don't fully get the purpose of "NotExists". Is it there to prevent duplicate creation of a state-object with the same name?

setObject overrides the object and in older js-controller versions custom attributes were not completely remembered and restored, this should be fixed in controller 2.x+, but also hard overwrite of objects is not that needed

**Comment by Apollon77** [comment]
Hey, I have

* with     "@iobroker/adapter-core": "^2.4.0", your js.cntroller dep needs to be >=2.0.0
* it is a "best practice" to ctreate ainfo channel with a connection state and set this with the connection status so that admin can show the status better
* please make sure timeoits (and intervals) like https://github.com/Excodibur/ioBroker.schwoerer-ventcube/blob/32f6aac46ae0a3720711e91a4512087fdf7da478/src/lib/connector.ts#L52 are cleared when "unload" is called. This is not the case currently
* Is it possible to also set state roles better then just "value"? (https://github.com/Excodibur/ioBroker.schwoerer-ventcube/blob/32f6aac46ae0a3720711e91a4512087fdf7da478/src/main.ts#L63)

Thank you for checking and fixing. Please drop a line here when done

**Comment by Excodibur** [comment]
@Apollon77 Thank you for those remarks.

I changed adapter implementation accordingly: https://github.com/Excodibur/ioBroker.schwoerer-ventcube/releases/tag/v1.3.0

Please take a look at it.

**Comment by Apollon77** [comment]
I did not saw the connection.info state for Admin and roles optimized, but in fact up to you :-) Welcome in Repo.

**Comment by Excodibur** [comment]
@Apollon77 Thanks again for adding the adapter.
The other points should be there as well, at least I hope I understood them correctly. :-)

connection.info (set in Connector itself)
https://github.com/Excodibur/ioBroker.schwoerer-ventcube/blob/2a4533fe8e05a365506402918e2b21f372698854/io-package.json#L116-L138

Improved state roles logic
https://github.com/Excodibur/ioBroker.schwoerer-ventcube/blob/2a4533fe8e05a365506402918e2b21f372698854/src/main.ts#L74-L100

**Pull request merged**
