### PR TITLE
Update tonew stable version

### PR DESCRIPTION
**Pull request by BenAhrdt**
Updating operating-hours to 0.0.15

=> Automatic reset implemented

### CODE REVIEW

**Comment by Apollon77** [comment]
From where do you know that this version is "stable"? Normally we require stable to have at least some installations or time passed by, so that you can be sure to not have a broken version.

In special cases on very important bugfixes we allow faster stable update ... But this seems not the ase here, or?

**Comment by BenAhrdt** [comment]
OK, i have checked it.
also it is possible to set it to latest.

**Comment by BenAhrdt** [comment]
OK, so tomorrow the user can install beta. wright?

**Comment by BenAhrdt** [comment]
i closed this pR because i will check it with testers in Beta and maby do some changes

**Pull request closed without merging**
