### PR TITLE
fb-checkpresence

### PR DESCRIPTION
**Pull request by afuerhoff**
https://forum.iobroker.net/topic/28288/test-adapter-fb-checkpresence-v0-2-x

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi,

here some review comments:
* Needs Fix: please remove .vscode from GitHub
* Needs Fix: please remove iopackage common.installedFrom
* Note: why you do anhard dependecy to history? also sql and influxdb offer the interfaces via messages you want to use :-)
* Note: Why do you use a scheduler library for a simple "every x minutes interval" logic? should be easy to do with setInterval ;-)
* Note: If you do not implement onstate/objectChange please do not implement it

**Comment by afuerhoff** [comment]
Hi, thank you for your review comments.

**Fixes:**
I will correct this and publish it in a new version -> v0.2.2.

**Dependency to history:**
The adapter can handle history, sql and influxdb. The history adapter dependency was a test solution some weeks ago and I have forgotten to remove it. I give a hint in the documentation to choose the right history adapter as a pre condition. -> v0.2.2

**Scheduler library:**
I am a beginner with javascript and google helps me to find this solution. But it's a good hint and I will change this to "setInterval". -> v0.2.2

**onstate/objectChange:**
I used it for debugging and I will remove it. -> v0.2.2

Should I add a new pull request after correction?

**Comment by afuerhoff** [comment]
Hi @Apollon77, I have published a new version v0.2.2 on github and npm. Can you please check it.

**Comment by Apollon77** [comment]
looks good, welcome in the repo

**Pull request merged**
