### PR TITLE
Added Mercury

### PR DESCRIPTION
**Pull request by instalator**

### CODE REVIEW

**Comment by instalator** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mercury](https://github.com/instalator/ioBroker.mercury)
[Downloads](https://www.npmjs.com/package/iobroker.mercury) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mercury/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mercury](https://github.com/instalator/ioBroker.mercury)
[Downloads](https://www.npmjs.com/package/iobroker.mercury) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mercury/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
