### PR TITLE
Add Adapter Value-Tracker over time

### PR DESCRIPTION
**Pull request by Omega236**
Add Adapter valuetrackerovertime

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.valuetrackerovertime](https://github.com/Omega236/ioBroker.valuetrackerovertime)
[Downloads](https://www.npmjs.com/package/iobroker.valuetrackerovertime) 
[NPM](https://nodei.co/npm/iobroker.valuetrackerovertime/)

- [ ] :heavy_exclamation_mark: [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html 
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/Omega236/ioBroker.valuetrackerovertime", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/Omega236/ioBroker.valuetrackerovertime", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "valuetrackerovertime" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Omega236** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.valuetrackerovertime](https://github.com/Omega236/ioBroker.valuetrackerovertime)
[Downloads](https://www.npmjs.com/package/iobroker.valuetrackerovertime) 
[NPM](https://nodei.co/npm/iobroker.valuetrackerovertime/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "valuetrackerovertime" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Omega236** [comment]
mixed with virtualpowermeter so close it

**Pull request closed without merging**
