### PR TITLE
update valloxmv to 0.1.2

### PR DESCRIPTION
**Pull request by hacki11**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bsblan](https://github.com/hacki11/ioBroker.bsblan)
[Downloads](https://www.npmjs.com/package/iobroker.bsblan) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.bsblan/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/hacki11/ioBroker.bsblan", press the first "Edit" button you will find on the page and add the description.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@hacki11 I merge this now but please fix the checker finding please!

**Comment by hacki11** [comment]
I always have this message but it seems to be a checker issue

**Pull request merged**
