### PR TITLE
unifi-protect to latest

### PR DESCRIPTION
**Pull request by peterbaumert**

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi,

here a short review comments:
* Needs fix: [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.unifi-protect"
* Needs-fix: [E802] No topics found in the repository. Please go to "https://github.com/peterbaumert/ioBroker.unifi-protect" and press "Manage topics"
* Needs-fix: [E300] Not found on travis. Please setup travis
* Needs-fix: please encrypt the password from configuration
* Needs-fix: store and clear Timeouts/Intrvals on unload !! (e.g. https://github.com/peterbaumert/ioBroker.unifi-protect/blob/master/main.js#L50)
... and some more ... Please check the points from the development best practices https://github.com/ioBroker/ioBroker.repositories#development-and-coding-best-practices

**Comment by peterbaumert** [comment]
Point one i did and it shows blufox on npm settings.
Point 3 i thought the github actions are enough?
Rest i will fix tomorrow

**Comment by Apollon77** [comment]
GitHub Actions are not enough at the moment because they do not allow us to get an easy overview, especially when we want to see how our adapters behave with new nodejs versions. For this I currently have forked all adapters and so I can use my Travis to get an exact view on the status

**Comment by peterbaumert** [comment]
Hi @Apollon77 I fixed everything. Can you check again?

**Comment by GermanBluefox** [comment]
image

**Comment by peterbaumert** [comment]
> image
> 
> Please call: `npm owner add bluefox iobroker.unifi-protect`

Hi @GermanBluefox  as i stated already, i did this and it shows on npm.

image

But i also did it again:
npm owner add bluefox iobroker.unifi-protect
+ bluefox (iobroker.unifi-protect)

**Comment by peterbaumert** [comment]
so i completly removed bluefox one more time and did it again. Now it seems to be fine. could you check again @GermanBluefox  or @Apollon77

**Comment by Apollon77** [comment]
Thank you for enabling travis ... but please also execute the integration theses there ... currently only package tests are executed.
Rest looks fine!

**Comment by peterbaumert** [comment]
Hi @Apollon77 , thanks for the review. I think i did enable now what you meant :D

KR Peter

**Comment by Apollon77** [comment]
yes, great, thank you!

**Pull request merged**
