### PR TITLE
Add my-opcua to latest

### PR DESCRIPTION
**Pull request by gokturk413**
Please add my adapter ioBroker.my-opcua to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
@gokturk413 

Thanks for writing an adapter for ioBroker.

Before I will do a detailled review, please check th requirements for adding an adapter to latest repository.
https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository
https://github.com/ioBroker/ioBroker.repositories#development-and-coding-best-practices

Especially
- fix issues reported by adapter checker
- fix standard github testing (testing MUST be present and pass tests for node (16) / 18 / 20
- readme must cobtain a suffiient desctiption of the functionality the adapetr provides incuding a link to the manufakturer of device or service. "install .net framework 4.6 , Node.js v18.14.0" is too few information about installation and usage
- non relevant directoies (i.e. log) should be removed from github repository
- all dummy and example code must be removed, logs must be meaningful
- Code must have a working functionality. I cannot see i.e. setState do something useful.

**Comment by mcm1957** [comment]
@gokturk413 
**There's an existing adapter ioBroker.opcua.**

Please check wether this adapter will satisfy your needs. If you want to add some features, please contact @GermanBluefox (i.e. using a issue at this repo) and / or submit an PR.

I will close this PR as there are several issues to be fixed and the the need for a new adapter is notz clear.
If you really see a benefit creating a new adapter, please discuss with @GermanBluefox, create a new PR and clearly state why we should add a new adapter.

@Apollon77 FYI

**Comment by gokturk413** [comment]
one reason is that opcua is paid, but the product i created is free. The
second reason is that opcua is not working well, so I decided to write a
new adapter.

**Comment by mcm1957** [comment]
Ok,I'll check the commercial aspect and come back. I did not notice this.

Not working well should normally result in one or more issues or PR. In respect to commercial license this will be considered different.

I'll reipen PR for now. Please let us / me know at which timeframe you plan to solve the first code issues reported (see above). Please note that a detailled review will follow after vasic errors are fixed.

**Comment by gokturk413** [comment]
Hi. Can you help me about github. The jobs are failed javascript heap out
of memory. I am actually new on github can not find what is error.

**Comment by mcm1957** [comment]
As a PR is not the right place to discuss basic development issues, I woul suggest to join iobroker development starters group to get help for development and basics.

https://t.me/+gsX-e8k4mLtmZjZk

Please mention your goals (devlop adapter xxy) after subscribing as without any iobroker related communication you might be kicked out very fast (spam bot measurement).

I've provided a PR to update test-and-release script ot current level and versions. Normall you should  not need to modify anything inside the workflow.

Memory problems at eslint are unusual. Maybe they are cuased by outdated node 14 (fixed by PR mentioned) or some serious code problem confusing eslint. Please ask at Forum if still persist with node 16/18/20.

**Comment by mcm1957** [comment]
**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by gokturk413** [comment]
I have trouble with the github workflow to npm

**Comment by mcm1957** [comment]
I will close here as there is still some work to be done before a first release is available.

**Please open a new PR after standard github action pass the test and the adapter is working at your installation**. I also suggest that you open a Topic at forum.iobroker.net within tester area to request additional test by some users (although this is not required for a latest PR.

I repeat my very first review results (Some points might be solver - I did no new review lately)

- fix issues reported by adapter checker
- fix standard github testing (testing MUST be present and pass tests for node (16) / 18 / 20
- readme must cobtain a suffiient desctiption of the functionality the adapetr provides incuding a link to the manufakturer of device or service. "install .net framework 4.6 , Node.js v18.14.0" is too few information about installation and usage. Add an example how to use the adapter to readme.
- non relevant directories (i.e. log) should be removed from github repository
- all dummy and example code must be removed, logs must be meaningful
- Code must have a working functionality. I cannot see i.e. setState do something useful.

For support please join our telegram channel - see link above.

McM1957

**Pull request closed without merging**
