### PR TITLE
add zehnder-cloud

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by TA2k** [comment]
!RE-CHECK

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by ldittmar81** [comment]
@Apollon77 - E201 is false positiv. Review can be done.

Please close https://github.com/ioBroker/AdapterRequests/issues/144 after review.

**Comment by Apollon77** [comment]
hey @TA2k 

please make sure to kill all timeoits in unload  - tleast this.reLoginTimeout is missing ...or?!

**Comment by TA2k** [comment]
Jap. Is fixed now

**Pull request merged**
