### PR TITLE
Added adapter alpha-ess to Latest

### PR DESCRIPTION
**Pull request by Gaspode69**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alpha-ess](https://github.com/Gaspode69/ioBroker.alpha-ess)
[Downloads](https://www.npmjs.com/package/iobroker.alpha-ess) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.alpha-ess/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.alpha-ess)!. Please execute in adapter directory: `npm owner add bluefox iobroker.alpha-ess`
- [ ] :eyes: [W400] Cannot find "alpha-ess" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Gaspode69** [comment]
Hi, I sent an invitation to bluefox in NPM as maintainer because "npm owner add bluefox iobroker.alpha-ess" raised an HTTP-401. In the forum I found a hint to use npmjs.com instead. Was that wrong?

**Comment by Apollon77** [comment]
Sometimes npm cli is strange ... do it via their web interface

**Comment by Gaspode69** [comment]
Yes, that's what I did, or at least tried to do. The only way I found is to invite him as a "Maintainer".

**Comment by Gaspode69** [comment]
One more question: Is the Warning "[W400] Cannot find "alpha-ess" in latest repository" something I must care about?
I guess this warning will vanish automatically after the commit is merged, right?

**Comment by Apollon77** [comment]
>  I guess this warning will vanish automatically after the commit is merged, right?

exactly

**Comment by Gaspode69** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alpha-ess](https://github.com/Gaspode69/ioBroker.alpha-ess)
[Downloads](https://www.npmjs.com/package/iobroker.alpha-ess) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.alpha-ess/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "alpha-ess" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@Gaspode69 Hi, here some review comments:

* You use axios but do not have this as a dependency. Please move from devDeps to dependencies!
* maybe not log the password :-) https://github.com/Gaspode69/ioBroker.alpha-ess/blob/main/main.js#L366
* if you use arrow functions you avoid constructly like https://github.com/Gaspode69/ioBroker.alpha-ess/blob/main/main.js#L388-L389 (just use `setTimeout(() => this.whatever(), 3000)`
* and if you "await" the lmethods like fetchRealtimeData() you maybe do not need such constructs at all because all requests would be done sequencially
* ideally add "timeout" parameter to axios calls else network timeouts hang forever maybe

Thank you for looking into this and adjusting it

**Comment by Gaspode69** [comment]
@Apollon77 
Hi thank you very much for the review and the useful hints.
I created a PR and would like you to do the review if this is OK for you. Therefore, I added you as Contributor.

**Comment by Apollon77** [comment]
Sure, request review and I check this afternoon.

**Comment by Gaspode69** [comment]
Is it possible that you have to accept the collaborator invitation first, before I can request the review? Sorry for asking questins like this, I am quite new to the world of GitHub.

**Comment by Gaspode69** [comment]
All suggested changes implemented and reviewed by @Apollon77 
Version 0.1.0 available in npm

**Comment by Apollon77** [comment]
welcome

**Comment by Gaspode69** [comment]
Thank you!

**Pull request merged**
