### PR TITLE
Update panasonic-comfort-cloud to 2.2.0

### PR DESCRIPTION
**Pull request by marc2016**
Hallo,

I updated the adapter panasonic-comfort-cloud to version 2.2.0

Thx :-)

### CODE REVIEW

**Comment by mcm1957** [comment]
Please update README.md to contain releasenotes for 2.2.0

**Comment by marc2016** [comment]
> @marc2016
> Please update README.md to contain releasenotes for 2.2.0
> (Does not require a new release, update at github is sufficient)

Done!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
2.2.0 created at 13.6.2023
OK

**Pull request merged**
