### PR TITLE
update backitup to 1.4.3

### PR DESCRIPTION
**Pull request by simatec**

### CODE REVIEW

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.backitup](https://github.com/simatec/ioBroker.backitup)
[Downloads](https://www.npmjs.com/package/iobroker.backitup) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.backitup/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by simatec** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.backitup](https://github.com/simatec/ioBroker.backitup)
[Downloads](https://www.npmjs.com/package/iobroker.backitup) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.backitup/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
we wait till testsed by latest ... @simatec please create PR later agin, ok?!

**Pull request closed without merging**
