### PR TITLE
Add HioB to latest

### PR DESCRIPTION
**Pull request by moba15**

### CODE REVIEW

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

mcm1957

**Comment by mcm1957** [comment]
reminder 4.3.2024

**Comment by Lucky-ESA** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by moba15** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] errors reported by adapter checker must be fixed

  Please check W170
  
- [ ] Readme.md is very short

  The README.md of this adapter is very minimalistic. Please add a short description about the functionality of the adapter. Some text "This adapter enables to control ... using the hiob app, ..." which could be used at the news web page and describing the functionality of the adapter with 3 to 5 sentences.

  The primary documentation is fine and many thangs for providing such an extensive text info.

- [ ] Please use STATE instead of DATA POINT

  The official naming for states of ioBroker is states, So please replace DataPoint at english documentation including README.md with "state" as long as they refer to an ioBroker state.

- [ ] adapter should require up to date js-controller

  Please change "js-controller": ">=3.3.22" at io-package.json to require js-controller 5 (preferred for new adapters) or at least to js-controller 4 if you need por want to support js-controller 4 still. Please note, that no automatic tests are performed againts js-controller 4.

- [ ] github dependabot support seems to be missing
  
  It looks like you did not yet setup dependabot support; at least .github/dependaboit.yml is missing.
  
  Please consider setting up dependabot support (and to ease life the workflow auto-merge.yml). Dependabot will ensure that your adapter uses the most recent versions of external packages and avoids problem due to outdted base libraries. Dependabit provides PRs at you repository to update the dependencies. Depending on you setting, especially on auto-merge.yml configuration no or only minor revisions will be outmatically merged into you main branch. All major revisions msiut (ans should) be reviewed by you. 

  Read this as a suggestion, using dependabot is not mandatory.
    
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
@moba15 
Any news? Do you need some help / explanation  related to remarks from 5.4.2024?

@Apollon77 
Just a kind reminder to take a look if possible.

reminder 19.4.2024

**Comment by moba15** [comment]
Thanks for your feedback. I have now completed my changes. I hope I didn't forget anything.

**Comment by Apollon77** [comment]
Ok, also a short review from my side ...

* https://github.com/moba15/ioBroker.hiob/blob/main/src/main.ts#L77-L115 why same object created twice? in fcat you could also out this static one into io-package optionally
* same for the other "static" objects - they could also moved to io-package optionally
* if you subscribe "*" anyway there is no ned for that other subscribe https://github.com/moba15/ioBroker.hiob/blob/main/src/main.ts#L143-L144
* How many states you subscribe there usually? https://github.com/moba15/ioBroker.hiob/blob/main/src/main.ts#L302 if more then 50/100 it could make sore sense to subscribe to all all changes and sort out in adapter, else controller could get high load and effects all adapters

**Comment by mcm1957** [comment]
@moba15 
Please note comments from Apollon77

reminder 27.4.1014

**Comment by moba15** [comment]
Thanks for your feedback. 
Short Update from my side: 

> Any news? Do you need some help / explanation related to remarks from 5.4.2024?

I should have fixed them all

> * https://github.com/moba15/ioBroker.hiob/blob/main/src/main.ts#L77-L115 why same object created twice? in fcat you could also out this static one into io-package optionally

Now it is only created once.

> * if you subscribe "*" anyway there is no ned for that other subscribe https://github.com/moba15/ioBroker.hiob/blob/main/src/main.ts#L143-L144

I now only subscribe to "*" 


> * How many states you subscribe there usually? https://github.com/moba15/ioBroker.hiob/blob/main/src/main.ts#L302 if more then 50/100 it could make sore sense to subscribe to all all changes and sort out in adapter, else controller could get high load and effects all adapters

I don't really know if I've understood that correctly. But in the following I describe shortly what  have done to "fix" this problem:
Every time the user requests to get notified about certain state changes, I look if I already subscribed to this state. 
If not, I look if  I have already subscribed to 50 or more states within the same instance. If so, I subscribe to the complete instance and unsubscribe the single states. I also added a check if it is a alias state. You mentioned that it could be problematic to subscribe to alias.0.*, so I did a check for this as well.  
See implementation: https://github.com/moba15/ioBroker.hiob/blob/77fb2eaead13cde143f6b12cd0c013a6931e45eb/src/listener/listener.ts#L68

**Comment by mcm1957** [comment]
@Apollon77  FYI

Please comment. **I leave the ltgm marking to you for this adapter** as it is ruther complex and you have the better knowledge if somethiung need to be changes or is ok as it is. Please either mark lgtm or merge yourself

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Re-Review

- [x] errors reported by adapter checker must be fixed

  Please check W170
  
- [x] Readme.md is very short

  The README.md of this adapter is very minimalistic. Please add a short description about the functionality of the adapter. Some text "This adapter enables to control ... using the hiob app, ..." which could be used at the news web page and describing the functionality of the adapter with 3 to 5 sentences.

  The primary documentation is fine and many thangs for providing such an extensive text info.

- [x] Please use STATE instead of DATA POINT

  The official naming for states of ioBroker is states, So please replace DataPoint at english documentation including README.md with "state" as long as they refer to an ioBroker state.

- [c] adapter should require up to date js-controller

  Please change "js-controller": ">=3.3.22" at io-package.json to require js-controller 5 (preferred for new adapters) or at least to js-controller 4 if you need por want to support js-controller 4 still. Please note, that no automatic tests are performed againts js-controller 4.

- [x] github dependabot support seems to be missing
  
  It looks like you did not yet setup dependabot support; at least .github/dependaboit.yml is missing.
  
  Please consider setting up dependabot support (and to ease life the workflow auto-merge.yml). Dependabot will ensure that your adapter uses the most recent versions of external packages and avoids problem due to outdted base libraries. Dependabit provides PRs at you repository to update the dependencies. Depending on you setting, especially on auto-merge.yml configuration no or only minor revisions will be outmatically merged into you main branch. All major revisions msiut (ans should) be reviewed by you. 

  Read this as a suggestion, using dependabot is not mandatory.

**Comment by mcm1957** [comment]
As @Apollon77 does not have any addition comments this adapter will be released to lates repository.

**Comment by mcm1957** [comment]
@moba15 
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Pull request merged**
