### PR TITLE
Update heos to 2.1.0

### PR DESCRIPTION
**Pull request by withstu**

### CODE REVIEW

**Comment by mcm1957** [comment]
Url error will be checked by me.
Most likely either a user change or a change from master to main without repo notification accured.

Please wait some days due to holiday absebce

**Comment by withstu** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
2.1.0 created 05.08.2023
59 user (app 5%)
OK

**Pull request merged**
