### PR TITLE
Add air-Q adapter (v1.0.2) to stable

### LINKED ISSUE #52: Update stable version in repo from 0.0.0 to 1.0.1
# Think about adding version 1.0.1 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**1.0.1** (30 days old)
**Installs**: stable=**0** (0%), latest=**undefined** (NaN%), total=**9**

Click to use [developer portal](https://www.iobroker.dev/adapter/air-q/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

Note: This is an automatically generated message and not personally authored by bluefox!
      Do not close this issue manually as a new issue will be created if condition for update still exists
      @mcm1957 for evidence

### PR DESCRIPTION
**Pull request by pr0crstntr**
closes https://github.com/CorantGmbH/ioBroker.air-q/issues/52

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Please check and merge https://github.com/CorantGmbH/ioBroker.air-q/pull/59
A new release is NOT required for now.

**Comment by mcm1957** [comment]
reminder 30.4.2024

**Comment by pr0crstntr** [comment]
done :+1:

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Your Adapter has been added to stable repository. If you like you can extend the news message here:

https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/history/history.md

If you add some more information / description, please consider to add this information to README.md too.

If you have any questions related to the news file, please contact @Apollon77 for further information.

Please note, that the PR announcing the new adapter at stable might not be merged.
https://github.com/ioBroker/ioBroker.docs/pull/512

**Pull request merged**
