### PR TITLE
Bosch Smart Home Bridge Adapter stable 0.1.9

### PR DESCRIPTION
**Pull request by holomekc**
- fixed bug in scenario handling which was introduced in 0.1.8
- minor improvements

https://github.com/holomekc/ioBroker.bshb/pull/26

### CODE REVIEW

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bshb](https://github.com/holomekc/ioBroker.bshb)
[Downloads](https://www.npmjs.com/package/iobroker.bshb) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.bshb/)

:thumbsup: No errors found
- [ ] :eyes: [W801] .npmignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by holomekc** [comment]
RE-CHECK

**Comment by holomekc** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bshb](https://github.com/holomekc/ioBroker.bshb)
[Downloads](https://www.npmjs.com/package/iobroker.bshb) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.bshb/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
