### PR TITLE
RepetierServer Adapter

### PR DESCRIPTION
**Pull request by Baumert7269**
Überarbeiteter Adapter in Version V0.0.8.

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
@Baumert7269 Can you please solve the merge conflucts - and please also sort the adapter entry alphabetically in the file?

**Comment by Apollon77** [comment]
Here are my review comments. Please check and adjust them:
* Please cleanup the package.json. This is one from an "installed folder". All the items with "_" needs to be removed and so
* please put the admin depenednec into common.globalDependencies unless you really need admin adapter in this version on the same host as the adapter (https://github.com/Baumert7269/ioBroker.repetierserver/blob/master/io-package.json#L67-L69)
* is that a common default api key or yours? if yours it should not be in io-package because wpuld be then default for all users https://github.com/Baumert7269/ioBroker.repetierserver/blob/master/io-package.json#L78
* should the api key be stored encrpyted? If yes please check readme here with the dev-best-practices for instructions
* your testing all fails. Please fix https://github.com/Baumert7269/ioBroker.repetierserver/actions
* you maybe want to adjust the Template name? https://github.com/Baumert7269/ioBroker.repetierserver/blob/master/main.js#L110
* please check the roles. value.indicator (as example) is no valid role. https://github.com/Baumert7269/ioBroker.repetierserver/blob/master/main.js#L1439 --> see here https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md

**Comment by Apollon77** [comment]
@Baumert7269 and please also rebase the PR. Do you need any help?

**Comment by ldittmar81** [comment]
@Baumert7269 can I help you with the points in the review comment from Apollon?

**Comment by Apollon77** [comment]
@Baumert7269  How we should continue? Can we help somehow? Should we do a PR with relevant changes? But that would still require you to verify and test and release it afterwards because the changes can only be done "blind".

**Comment by Apollon77** [comment]
@Baumert7269 Happy new year, how we should proceed?

**Comment by Apollon77** [comment]
@Baumert7269 Any news on how we should continue?

**Comment by mcm1957** [comment]
Please update testing to current status. You should add git workflow test-and-release using node 16 / 18 und (optional) 20.

And please REMOVE file sources-dist-stable from this PR. Adapters MUST be available at latest some time before they are accepted at stable repository. So changeing latest and stable within one PR is not appropiate.

I would suggest to close this PR an create a new request after updateing the adapter to current status (i.e workflow, standard github test, ...)

**Comment by mcm1957** [comment]
No reaction since 2022
PR has merge conflicts

Closing this PR for now.
Please open a new PR to add this adapter to latest if desired.

**Pull request closed without merging**
