### PR TITLE
add wiegand-tcpip v0.4.6

### PR DESCRIPTION
**Pull request by kBrausew**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.wiegand-tcpip](https://github.com/kBrausew/ioBroker.wiegand-tcpip)
[Downloads](https://www.npmjs.com/package/iobroker.wiegand-tcpip) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.wiegand-tcpip/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "wiegand-tcpip" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hello,

here some review comments:
* Please also add nodjes 16.x to the github action tests
* why datasource assumption? https://github.com/kBrausew/ioBroker.wiegand-tcpip/blob/master/io-package.json#L133
* Hint: why an unsubscript on startip? There should be nothing subscribed? https://github.com/kBrausew/ioBroker.wiegand-tcpip/blob/master/main.js#L118
* Hint: https://github.com/kBrausew/ioBroker.wiegand-tcpip/blob/master/main.js#L120-L124 ... static objects can be defined in io-package in instanceObjects, so no code is needed
* to check if a state change is a command please use the ack flag ...  ack=false means commena d and only thins should trigger commands in stateChange ... so https://github.com/kBrausew/ioBroker.wiegand-tcpip/blob/master/main.js#L652-L654 should be replaced by a `if (!state.ack) ...`
* Do you really subscribe every single state? if not then https://github.com/kBrausew/ioBroker.wiegand-tcpip/blob/master/main.js#L670 will have no real effect because unsubscribe only checks for patterns subscribed before
* BTW (re the screenshot in setup page): divices -> devices :-)

Thank you for checking and asjusting

**Comment by kBrausew** [comment]
All points met and released with version v0.4.6

**Comment by kBrausew** [comment]
Any showstopper? 
Next version is waiting

**Comment by Apollon77** [comment]
just do next version ... I have on my plan for next days. Sorry for the delay

**Comment by Apollon77** [comment]
Hi,

sorry for the long waiting time.

For onStateCHnge that whole "check for the instance that triggered a change" is normally not needed - the state.ack check should provent all issues ... but now your code would not react correctly if you set a ack=false state to control something yourself ... No "issue", but should never happen ...

But it also do not hurt (just makes it more complex for you :-) )

Welcome in the repository

**Pull request merged**
