### PR TITLE
add mediola-gateway to latest

### PR DESCRIPTION
**Pull request by oelison**
now adding it only to the sources-dist.json
solves:
https://github.com/ioBroker/AdapterRequests/issues/47

### CODE REVIEW

**Comment by mcm1957** [comment]
link to repository: https://github.com/oelison/ioBroker.mediola-gateway

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mediola-gateway](https://github.com/oelison/ioBroker.mediola-gateway)
[Downloads](https://www.npmjs.com/package/iobroker.mediola-gateway) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.mediola-gateway/)

- [ ] :heavy_exclamation_mark: [E142] logo is too big. It must be less or equal than 512x512
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/oelison/ioBroker.mediola-gateway", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/oelison/ioBroker.mediola-gateway", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/oelison/ioBroker.mediola-gateway/blob/master/io-package.json)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/oelison/ioBroker.mediola-gateway/blob/master/package.json) (0.1.1) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.mediola-gateway) (0.1.0)
- [ ] :eyes: [W400] Cannot find "mediola-gateway" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- errors reported by adapter checker must be fixed

  All errors must be fixed
  All warnings should be evaluated. Especially W202 indicates some problem with automatic release which must be fixed.
 
- test-and-release should have deploy activated

  currently the test-and-release workflow has npm deploy disabled. If there is no t any very special requirment, automatic deploy should be anabled. See control file for details: https://github.com/oelison/ioBroker.mediola-gateway/blob/d3f8aa22d8a039bacd2a3727f7949c3af87a9cbc/.github/workflows/test-and-release.yml#L55

- Readme.md is very short

  The README.md of this adapter is very minimalistic. It consists of onle one line of information. Please add a short description about the functionality of the adpter,  add links the the manufacturer site (if applicable) and add a description of the configuration of the adapter. If you provide an external documentation - which should be located at doc/xx directory - please add links to at least the english documentation. See rewuirement at point 4 of https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository

- invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```, i.e. by using the following snippet:
```
function name2id(pName) {
    return (pName || '').replace(adapter.FORBIDDEN_CHARS, '_');
}
```
  This adapter constructs ids based on the return value from the device:
```
                                        this.log.debug(JSON.stringify(element));
                                        this.setObjectNotExists("id" + element.adr, {
                                            type: "state",
                                            common: {
                                                name: "sysvar" + element.adr,
                                                type: "string",
                                                role: "text",
                                                read: true,
                                                write: false,
                                            },
                                            native: {},
                                        });
                                        this.setState("id" + element.adr, { val: element.state, ack: true });
```
element.adr should / must be ceched for invalid chars.

- statechanges must follow ack flag rules

  The adapter should only react on writes to (own) states with ackFlag set to false. Writes with ack=true to own writeable states should/must be ignored. When subsribed foreign states reacting on changes with ack=true is ok.

  see: https://forum.iobroker.net/topic/46771/wozu-ist-der-ack-flag-da?_=1684434944515 and
  
- axios questions
 
  Are you sure, that axios calls do not need any explicit timeouts?
  Is it really ok to sile ntyl ignore any axios errors raised as exceptions? (The are logged a debiug only)?

- adapt testing to supported node releases

  Tests for node 16 is mandatory unless you require node 18 and higher. (already OK)
  Tests for node 18 is mandatory as many users already use node 18 and node 16 will be eol and deprected Q3/2023. (already OK)
  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x],

- github dependabot support
  automerge token sees to be missing
  see https://github.com/oelison/ioBroker.mediola-gateway/actions/runs/4944507855/jobs/8840056428?pr=21
  (This is not a requirement but either autmerge should be setup correctyl or you should disable automerge and merge manually (which is not recommended due to effort)
  
Thanks for reading and evaluating this suggestions.
McM1957

**Comment by oelison** [comment]
Yes, the readme was a bit short.
Adapter checks are now passing.
Test and release has deploy activated now.
Invalid characters are not possible. The returned value is 1-255 in hex (01-FF).
ack set to false for setting own objects. (no evaluation done, so no functional change)
Testing expanded to Node 20.x.
I hate auto merge, but like the mails for updates. I left it as it is. The release need to be done anyway.
Axios: I will think about this, but actually I can't see a better way.

**Comment by mcm1957** [comment]
> Invalid characters are not possible. The returned value is 1-255 in hex (01-FF). 

I would suggest to check it anyway. As the data is sent by an external system., there is no gurantee that there is no other data received.

>Axios: I will think about this, but actually I can't see a better way.

Well I woul log any error as error (and notz as debug) unless those errors are received at regular operation. In this case I wqould suggest to handle them and to report exctly any abnomality. Currently the user simply will see nothing if functionality fails if I'm correct.

**Comment by oelison** [comment]
Thank you for your review.
I added the check and also error messages for axios errors.
It also offers me to make a new read, until the sys vars are detected.
The ack I set for all read only objects to true again.
warn: mediola-gateway.0 (10032) Read-only state "mediola-gateway.0.receivedIrData" has been written without ack-flag
warn: mediola-gateway.0 (11096) Read-only state "mediola-gateway.0.id01" has been written without ack-flag

**Comment by mcm1957** [comment]
>warn: mediola-gateway.0 (11096) Read-only state "mediola-gateway.0.id01" has been written without ack-flag

I think theres some misunderstanding.

WRITING to own states should be normally done with ACK=TRUE just as you did it.

My notes refer to the fact that your **onStateChange** code does not check the ack flag of the modified state, Modifications of states signalled via onStateChange with ACK==TRIUE should be ignored for own states (aka "Button or triggerstates")

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mediola-gateway](https://github.com/oelison/ioBroker.mediola-gateway)
[Downloads](https://www.npmjs.com/package/iobroker.mediola-gateway) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.mediola-gateway/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "mediola-gateway" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by oelison** [comment]
Done.

**Comment by oelison** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mediola-gateway](https://github.com/oelison/ioBroker.mediola-gateway)
[Downloads](https://www.npmjs.com/package/iobroker.mediola-gateway) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.mediola-gateway/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "mediola-gateway" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
@oelison 
Any reason to cancel this request?
Or a sideeffect if forced push.?

Please oben new request if adding still requested and add a link to the closed PR

**Comment by oelison** [comment]
I deleted the repo state on my side. So accidental this closes this PR. I will make a new one.
Thank you for your hint.

**Pull request closed without merging**
