### PR TITLE
add iobroker.kostal-piko-ba to latest

### PR DESCRIPTION
**Pull request by hombach**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.kostal-piko-ba](https://github.com/hombach/ioBroker.kostal-piko-ba)
[Downloads](https://www.npmjs.com/package/iobroker.kostal-piko-ba) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.kostal-piko-ba/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/hombach/ioBroker.kostal-piko-ba) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/hombach/ioBroker.kostal-piko-ba", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/hombach/ioBroker.kostal-piko-ba" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "kostal-piko-ba" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by hombach** [comment]
[E301]: all Travis tests for ARM64 are currently not working at all -> will re-check here as soon as Travis CI engine is working again
[E801]: About text ist existing -> false positive test! 
[E802]: Topics are existing -> false positive test!

**Comment by hombach** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.kostal-piko-ba](https://github.com/hombach/ioBroker.kostal-piko-ba)
[Downloads](https://www.npmjs.com/package/iobroker.kostal-piko-ba) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.kostal-piko-ba/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/hombach/ioBroker.kostal-piko-ba", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/hombach/ioBroker.kostal-piko-ba" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "kostal-piko-ba" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by hombach** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.kostal-piko-ba](https://github.com/hombach/ioBroker.kostal-piko-ba)
[Downloads](https://www.npmjs.com/package/iobroker.kostal-piko-ba) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.kostal-piko-ba/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/hombach/ioBroker.kostal-piko-ba", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/hombach/ioBroker.kostal-piko-ba" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "kostal-piko-ba" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by hombach** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.kostal-piko-ba](https://github.com/hombach/ioBroker.kostal-piko-ba)
[Downloads](https://www.npmjs.com/package/iobroker.kostal-piko-ba) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.kostal-piko-ba/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "kostal-piko-ba" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
