### PR TITLE
Add vaillant and volvo adapter

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
image

**Comment by GermanBluefox** [comment]
image

**Comment by TA2k** [comment]
npmignore in volvo fixed
vaillant uses the need google action tests. recommended bei create adapter
https://github.com/TA2k/ioBroker.vaillant/actions

**Comment by Apollon77** [comment]
please also add travis (create-adapter got changed again) ... topic is that on travis we get very easy get an overview on all adapters ... github actions are currently not allowing this. Thank you!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
### ioBroker.vaillant
 * [E300] Not found on travis. Please setup travis
### ioBroker.volvo
No errors found

**Comment by TA2k** [comment]
https://travis-ci.org/TA2k/ioBroker.vaillant/

**Comment by Apollon77** [comment]
More review comments:

vaillant:
* please remove io-package common.installedFrom!
* updating values runs at least 120s ... you should find a way to stop such a progress (e.g. having a "stopped" variable which is checked before each communication try or such ... else compact mode will be problematic
* Are intervals really a good choice here? Is a timout for the next data call at the end of an working one not better?
* Password needs to be encrypted!

volvo:
* Password needs to be encrypted!
* many requests run in parallel ... really wanted?
* these setState should be in the createObject callback  ... https://github.com/TA2k/ioBroker.volvo/blob/master/main.js#L282

**Comment by TA2k** [comment]
Sometimes request are not working I think it is ok to try it again in the interval instead of stopping requesting. 
What is the correct way to encrypt passwords?
https://github.com/ioBroker/create-adapter/issues/407#issuecomment-593583775

For Volvo there are only 3 request in parallel why not? The app is doing it the same way.

**Comment by Apollon77** [comment]
Not working means? Bringing errors? Then you could implement retries ... but ok ... was mainly feedback. Also for number of parallel requests

encrypt/decrypt see e.g. my Meross adapter

**Comment by TA2k** [comment]
Mh it looks the encryption will change in the future and causes problem but ok.  Will add this

**Comment by Apollon77** [comment]
Yes it might change but erbeute make sure not to break things. But yes, later adjustment effort might be needed.

**Comment by TA2k** [comment]
fixed in both repos

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vaillant](https://github.com/TA2k/ioBroker.vaillant)
[Downloads](https://www.npmjs.com/package/iobroker.vaillant) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vaillant/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/TA2k/ioBroker.vaillant/blob/master/io-package.json). Must be removed.
- [ ] :eyes: [W400] Cannot find "vaillant" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js, but no clearTimeout detected

### [ioBroker.volvo](https://github.com/TA2k/ioBroker.volvo)
[Downloads](https://www.npmjs.com/package/iobroker.volvo) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.volvo/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "volvo" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
volvo is ok, vaillant needs a last fix @TA2k Thank you!

**Comment by TA2k** [comment]
fixed

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vaillant](https://github.com/TA2k/ioBroker.vaillant)
[Downloads](https://www.npmjs.com/package/iobroker.vaillant) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vaillant/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "vaillant" in latest repository

### [ioBroker.volvo](https://github.com/TA2k/ioBroker.volvo)
[Downloads](https://www.npmjs.com/package/iobroker.volvo) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.volvo/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "volvo" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
