### PR TITLE
Add Adapter energiefluss-erweitert to latest.

### PR DESCRIPTION
**Pull request by SKB-CGN**
Hi,
this is an extended version of the "energiefluss"-adapter. Please add it to the beta repo.

Thanks!

### CODE REVIEW

**Comment by mcm1957** [comment]
Please fix PR.
icon is missing -erweiter at url.

**Comment by mcm1957** [comment]
reminder 22.2.2023

**Comment by SKB-CGN** [comment]
Correct. I have edited the file again.
Sorry for this small mistake.

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

You will find the results of the review and evntually issues / suggestings as a communt to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

mcm1957

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.
And SORRY for the very long processing time

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] package.json should contain keywords

  package.json currently contains:
  ```
    "keywords": [
      "key"
    ],
  ```
  Please consider using some more descriptive keywords. (But I do not consider this blocking)
  
  
Thanks for reading and evaluating this suggestions.
McM1957

**Comment by mcm1957** [comment]
Additional remark:

0.2.2 did not yet make its way to npm. Is this on purpose?

I would suggest to enable outomatic deploy at test-and-relöease workflow:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/blob/55ef2ac150e76344140d6befd85ad7e090f00b1e/.github/workflows/test-and-release.yml#L54

But again - this is not blocking, just a suggestion

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Pull request merged**
