### PR TITLE
Update fritzdect to 2.5.11

### PR DESCRIPTION
**Pull request by foxthefox**
Update to 2.5.11 as of automatic whish

### CODE REVIEW

**Comment by mcm1957** [comment]
@foxthefox 
[E204] Version "2.5.10" listed at common.news at [io-package.json](https://github.com/foxthefox/ioBroker.fritzdect/blob/master/io-package.json) does not exist at [NPM](https://www.npmjs.com/package/iobroker.fritzdect). Please remove from news section.

Please remove from news section as releases not existing at npm confuse users if they select them at "install dedicated version" dialog. A change at io-package.json at GitHub is sufficient - NO new release is required as repo builder picks GitHub head version anyway.

**Comment by foxthefox** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Sorry - one more change request:

Please remove discouraged installation guide from README:md. (New Release is NOT required)
https://github.com/foxthefox/ioBroker.fritzdect/issues/575

**Comment by mcm1957** [comment]
README has been fixed - THANKS

**Comment by mcm1957** [comment]
RE-CHECK!

**Pull request merged**
