### PR TITLE
Update solarmanpv to 0.5.0

### PR DESCRIPTION
**Pull request by raschy**
Please update my adapter ioBroker.solarmanpv to version 0.5.0.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
0.5.0 released 16.6 1 day old

New releases should be available at latest for some time unless this is an ugent hotfix.

Please notify us if urgent release us required. Otherwise i ll kepp the request open and merge in some days.

**Comment by raschy** [comment]
0.4.1 and 0.4.2 had minor problems that were fixed in 0.4.3. In addition, there was a small function extension. Wouldn't it make sense to bring 0.5.0 into stable quite soon?

**Comment by mcm1957** [comment]
Reading this I would suggest to wait app 1week and check if latest users experiance any problems. I gave seen some minor extension breaking code at surprising ways. Dont want to tell that this is the case her. Bit normal way is to let users test the software at latest a little bit.

I woild merge in app 1 week. If this is too long please ping Apollon77. I m nearly offline the next days

**Comment by Apollon77** [comment]
@raschy Ok i would say: I you got infos from the affected users with the problems that its ok for them now ... then makes sense to also do earlier.

**Comment by raschy** [comment]
I saw today at noon that the version 0.5.0 is offered in the latest. So users who have a bug can fall back on this and we wait this week before it can go into stable. Thanks for the effort.

**Comment by mcm1957** [comment]
@raschy 
Just for info

LATEST Repo is updated every time you create a new release and piblish it to  npm the standard way without any additonal steps. This update is done twice a day at app 14:00 an during night. So latest next day users should get a new release using latest.

STABLE must be requested. A new Release at stble should have some usage at latest. If an urgent fix is nexessary a very fast release is possible of course. Please try to avoid such fixes to be combined with new functionality if possible. And please state the need for an urgent release explicutky if its the case to save time for questions.

And a BIG THANKS for maintaing this adapter

**Comment by raschy** [comment]
@mcm1957 LATEST Repo : Yes, I was aware of that as well. Unfortunately, until this morning the version was not yet in the latest - or I did not find it.

**Comment by mcm1957** [comment]
According to iobroker.dev 0.5.0 is at latest an used by 23 installations

If you still do not get it check your repo setting urls and do a manual refresh. Urls should use .live nodes as far as i know.

Please ask at telegram or forum if you need more help. I m using mobile only this werk so i m limited with investigations. Sorry

**Comment by mcm1957** [comment]
Solarman 0.5.0 16.06.2023
88 User (6,7%)
no issues
OK

**Pull request merged**
