### PR TITLE
Update sources-dist-stable.json

### PR DESCRIPTION
**Pull request by unltdnetworx**
new confirmed stable versions for energymanager, pi-hole, snips and stiebel-isg

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.energymanager](https://github.com/unltdnetworx/ioBroker.energymanager)
[Downloads](https://www.npmjs.com/package/iobroker.energymanager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.energymanager/)

- [ ] :heavy_exclamation_mark: [E130] Too many news found in [io-package.json](https://github.com/unltdnetworx/ioBroker.energymanager/blob/master/io-package.json). Mast be less than 21. Please remove old news.
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.energymanager", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.energymanager" and press `Manage topics`
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.pi-hole](https://github.com/unltdnetworx/ioBroker.pi-hole)
[Downloads](https://www.npmjs.com/package/iobroker.pi-hole) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.pi-hole/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/unltdnetworx/ioBroker.pi-hole/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.pi-hole", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.pi-hole" and press `Manage topics`
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.snips](https://github.com/unltdnetworx/ioBroker.snips)
[Downloads](https://www.npmjs.com/package/iobroker.snips) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.snips/)

- [ ] :heavy_exclamation_mark: [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html 
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.snips", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.snips" and press `Manage topics`

### [ioBroker.stiebel-isg](https://github.com/unltdnetworx/ioBroker.stiebel-isg)
[Downloads](https://www.npmjs.com/package/iobroker.stiebel-isg) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.stiebel-isg/)

- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/unltdnetworx/ioBroker.stiebel-isg/blob/master/iob_npm.done)" found in repo! Please add it to .gitignore
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.stiebel-isg", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.stiebel-isg" and press `Manage topics`


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@unltdnetworx Pleas ehave a look. Ignore the github errors for content ... this is false positive, but please try to make sure the rest is addressed in upcoming versions :-) Thank you!

**Comment by Apollon77** [comment]
And please make sure in any case to adress the setTimeout issue fast.
https://github.com/unltdnetworx/ioBroker.energymanager/blob/master/main.js#L34 is a very long timeout ... please make sure that if unload is called this timeout is cancelled!

**Comment by unltdnetworx** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.energymanager](https://github.com/unltdnetworx/ioBroker.energymanager)
[Downloads](https://www.npmjs.com/package/iobroker.energymanager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.energymanager/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.energymanager", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.energymanager" and press `Manage topics`

### [ioBroker.pi-hole](https://github.com/unltdnetworx/ioBroker.pi-hole)
[Downloads](https://www.npmjs.com/package/iobroker.pi-hole) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.pi-hole/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.pi-hole", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.pi-hole" and press `Manage topics`

### [ioBroker.snips](https://github.com/unltdnetworx/ioBroker.snips)
[Downloads](https://www.npmjs.com/package/iobroker.snips) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.snips/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/unltdnetworx/ioBroker.snips/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.snips", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.snips" and press `Manage topics`

### [ioBroker.stiebel-isg](https://github.com/unltdnetworx/ioBroker.stiebel-isg)
[Downloads](https://www.npmjs.com/package/iobroker.stiebel-isg) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.stiebel-isg/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.stiebel-isg", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.stiebel-isg" and press `Manage topics`


*Add comment "RE-CHECK!" to start check anew*

**Comment by unltdnetworx** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.energymanager](https://github.com/unltdnetworx/ioBroker.energymanager)
[Downloads](https://www.npmjs.com/package/iobroker.energymanager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.energymanager/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.energymanager", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.energymanager" and press `Manage topics`

### [ioBroker.pi-hole](https://github.com/unltdnetworx/ioBroker.pi-hole)
[Downloads](https://www.npmjs.com/package/iobroker.pi-hole) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.pi-hole/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.pi-hole", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.pi-hole" and press `Manage topics`

### [ioBroker.snips](https://github.com/unltdnetworx/ioBroker.snips)
[Downloads](https://www.npmjs.com/package/iobroker.snips) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.snips/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/unltdnetworx/ioBroker.snips) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E506] Word "Filter:" is not translated to russian in [admin/words.js](https://github.com/unltdnetworx/ioBroker.snips/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.snips", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.snips" and press `Manage topics`

### [ioBroker.stiebel-isg](https://github.com/unltdnetworx/ioBroker.stiebel-isg)
[Downloads](https://www.npmjs.com/package/iobroker.stiebel-isg) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.stiebel-isg/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.stiebel-isg", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.stiebel-isg" and press `Manage topics`


*Add comment "RE-CHECK!" to start check anew*

**Comment by unltdnetworx** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.energymanager](https://github.com/unltdnetworx/ioBroker.energymanager)
[Downloads](https://www.npmjs.com/package/iobroker.energymanager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.energymanager/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.energymanager", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.energymanager" and press `Manage topics`

### [ioBroker.pi-hole](https://github.com/unltdnetworx/ioBroker.pi-hole)
[Downloads](https://www.npmjs.com/package/iobroker.pi-hole) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.pi-hole/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.pi-hole", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.pi-hole" and press `Manage topics`

### [ioBroker.snips](https://github.com/unltdnetworx/ioBroker.snips)
[Downloads](https://www.npmjs.com/package/iobroker.snips) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.snips/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "main.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.snips", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.snips" and press `Manage topics`

### [ioBroker.stiebel-isg](https://github.com/unltdnetworx/ioBroker.stiebel-isg)
[Downloads](https://www.npmjs.com/package/iobroker.stiebel-isg) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.stiebel-isg/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "main.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.stiebel-isg", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.stiebel-isg" and press `Manage topics`


*Add comment "RE-CHECK!" to start check anew*

**Comment by unltdnetworx** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.energymanager](https://github.com/unltdnetworx/ioBroker.energymanager)
[Downloads](https://www.npmjs.com/package/iobroker.energymanager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.energymanager/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.energymanager", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.energymanager" and press `Manage topics`

### [ioBroker.pi-hole](https://github.com/unltdnetworx/ioBroker.pi-hole)
[Downloads](https://www.npmjs.com/package/iobroker.pi-hole) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.pi-hole/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.pi-hole", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.pi-hole" and press `Manage topics`

### [ioBroker.snips](https://github.com/unltdnetworx/ioBroker.snips)
[Downloads](https://www.npmjs.com/package/iobroker.snips) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.snips/)

- [ ] :heavy_exclamation_mark: [E504] "main.js found in [package.json](https://github.com/unltdnetworx/ioBroker.snips/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.snips", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.snips" and press `Manage topics`

### [ioBroker.stiebel-isg](https://github.com/unltdnetworx/ioBroker.stiebel-isg)
[Downloads](https://www.npmjs.com/package/iobroker.stiebel-isg) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.stiebel-isg/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/unltdnetworx/ioBroker.stiebel-isg) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/unltdnetworx/ioBroker.stiebel-isg", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/unltdnetworx/ioBroker.stiebel-isg" and press `Manage topics`


*Add comment "RE-CHECK!" to start check anew*

**Comment by unltdnetworx** [comment]
False errors occur randomly.
snips: there is a main.js file
stiebel-isg: all tests passed

last review:
Intervals were criticized, but there were none in the source code or were stopped on unload. just re-checked an other errors occured.

**Pull request merged**
