### PR TITLE
Add senec adapter to latest

### PR DESCRIPTION
**Pull request by nobl**
Please add senec adapter to latest. It is ready for feedback and testing.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.Senec](https://github.com/nobl/ioBroker.Senec)
[Downloads](https://www.npmjs.com/package/iobroker.Senec) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.Senec/)

- [ ] :heavy_exclamation_mark: [E005] Adapter name must be lowercase
- [ ] :heavy_exclamation_mark: [E006] Invalid characters found in adapter name "Senec". Only lowercase chars, "-" and "_" are allowed
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/nobl/ioBroker.senec. Expected: git+https://github.com/nobl/ioBroker.Senec.git
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.senec)!. Please execute in adapter directory: "npm owner add bluefox iobroker.Senec"
- [ ] :eyes: [W400] Cannot find "Senec" in latest repository

**Comment by nobl** [comment]
hope i got it fixed properly.
Bluefox should be owner but maybe that was also problematic due to the capital S. (sorry)

**Comment by Apollon77** [comment]
Hi,

some additional review comments:
* please remove docs/en from io-package or create the files :-)
* beside error for requests there can also be cases where err is not set nut still no body available. Normally check for response && response.statusCode
* adapter will stop working when e.g. a timeout happens or no valid json is returned because of https://github.com/nobl/ioBroker.senec/blob/master/main.js#L114 and a new timeout is only set if no exception in thrown ... you might want to optimize this

**Comment by nobl** [comment]
ok - lets see :-)
done (added), done (yeah - reasonable to do that), done (was more or less intentional but far from perfect - yes) and added more things due to user-feedback :)

**Comment by Apollon77** [comment]
super, thank you!

**Pull request merged**
