### PR TITLE
new adapter for openligadb soccer sport data

### PR DESCRIPTION
**Pull request by oweitman**
https://forum.iobroker.net/topic/29506/test-adapter-openligadb-v0-0-x

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi,

looks godd, but I have some review comments:
* Needs fix: You need to make sure to e able to clear any timeout and interval set by the adapter and do that on-unload. (https://github.com/oweitman/ioBroker.openligadb/blob/master/openligadb.js#L40 does not exists or I'm blind ;-) ... and it should clear all set timeouts) Else compact mode will break

Rest looks fine!

**Comment by oweitman** [comment]
new version v0.0.7 included now the removal of the timeout. this is now reported as debug message in log.

**Comment by Apollon77** [comment]
Timeouts and intervals are just some of the topics that needs to be done in unload. You need to clean up all resources - so also servers and serialports needs to be closed and such.

**Comment by oweitman** [comment]
thanks

**Pull request merged**
