### PR TITLE
Netatmo Energy adapter added

### PR DESCRIPTION
**Pull request by Homemade-Disaster**
Using Netatmo Energy API to get informations and send some API requests.
Supported requests are:
- homesdata
- homestatus
- setroomthermpoint
- setthermmode

### CODE REVIEW

**Comment by Homemade-Disaster** [comment]
https://forum.iobroker.net/topic/39851/test-adapter-netatmo-energy-v0-1-x-github-latest

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)

### [ioBroker.netatmo-energy](https://github.com/Homemade-Disaster/ioBroker.netatmo-energy)
[Downloads](https://www.npmjs.com/package/iobroker.netatmo-energy) 
[NPM](https://nodei.co/npm/iobroker.netatmo-energy/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "netatmo-energy" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Homemade-Disaster** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)

### [ioBroker.netatmo-energy](https://github.com/Homemade-Disaster/ioBroker.netatmo-energy)
[Downloads](https://www.npmjs.com/package/iobroker.netatmo-energy) 
[NPM](https://nodei.co/npm/iobroker.netatmo-energy/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "netatmo-energy" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Homemade-Disaster** [comment]
Hello, please can you tell me what I should do now. I didn't get an error on netatmo-energy. Do you need any document from my side. Thanks in advance.

**Comment by Homemade-Disaster** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)

### [ioBroker.netatmo-energy](https://github.com/Homemade-Disaster/ioBroker.netatmo-energy)
[Downloads](https://www.npmjs.com/package/iobroker.netatmo-energy) 
[NPM](https://nodei.co/npm/iobroker.netatmo-energy/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "netatmo-energy" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
Thank you for the pull request.
We must check the code and after that will merge.

Just now you have done everything what depends on you. :)

**Comment by Homemade-Disaster** [comment]
Version 0.1.19 already published. 
From my side it is possible to put it in stable to. 
I have deployed a widget in the adapter and a wiki (https://github.com/Homemade-Disaster/ioBroker.netatmo-energy/wiki) already exists. 

@GermanBluefox Hopefully everything is ok for you

**Comment by Apollon77** [comment]
We were a it busy with new js-controlle rversion ... adapter reviews come next :-)

**Comment by Apollon77** [comment]
Hi,

thank you for your patience!

I have some small last comments from review:
* I see some Timeouts in https://github.com/Homemade-Disaster/ioBroker.netatmo-energy/blob/master/lib/notification.js#L19 (e.g.) that are not properly cleared on unload ... (and not possible to be cleared). Please adjust that, else it can give issues with compact mode. And this is especially bad because it seems on first check that you do such a call in "unload" ... did you tested your adapter in compact mode?
* The inverval defined in https://github.com/Homemade-Disaster/ioBroker.netatmo-energy/blob/master/main.js#L218 is not cleared in unload!
* please also make sure that once unload was called really no code is executed anymore (e.g. also a still running request that came back with an answer should not be processed)

And some additional not that problematic notes:
* We have a more automatic encryption/decryption but you do not need to use it ... see best practices, but ok.
* best practice would be to add the "password key name" at least in "protectedNative" array in io-package to prevent side access by other object readers
* you can remove the .travis.yml file if you do not use travis
* personal note about using intervals when communicating with external APIs... thats dangerous ... intervals fire the next call regardless of the former one was successfully handled. in tiemout cases this can lead to piling up requests that once timeout is gone all run at the same timepoint. see also best practice infos in readme of repo
* await ... then (e.g. https://github.com/Homemade-Disaster/ioBroker.netatmo-energy/blob/master/main.js#L325-L326) is kind of an anti pattern ... normally you do one or the other :-) For errors you simply add a try/catch around the await statement

Thank you for checking and adjusting

**Comment by Apollon77** [comment]
@Homemade-Disaster Is there anything where we can support?

**Comment by Apollon77** [comment]
@Homemade-Disaster Any update?

**Comment by ldittmar81** [comment]
Hello @Homemade-Disaster... do you need some help to finish your adapter?

**Comment by Homemade-Disaster** [comment]
Hello,

yes, it would be great to get help.
kr

**Comment by Apollon77** [comment]
Ok @Homemade-Disaster what help you need? We can support here or you join Discord or telegram groups for developers or ask in Forum ...

**Comment by Homemade-Disaster** [comment]
Hello,

now I added an abort controller for fetch requests. I redesigned some of the coding and also made the js-controller 4.x check and rework.
Please check again if I forgot something necessary.

Best regards

**Comment by Apollon77** [comment]
All fine, do you want to update the stable version to 0.2.4 before I merge? @Homemade-Disaster

**Comment by Homemade-Disaster** [comment]
Hi, update to 0.2.4 done. Thank you for your feedback.

**Pull request merged**
