### PR TITLE
hs100 - "version": "1.1.5"

### PR DESCRIPTION
**Pull request by arteck**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hs100](https://github.com/arteck/ioBroker.hs100)
[Downloads](https://www.npmjs.com/package/iobroker.hs100) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hs100/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/arteck/ioBroker.hs100) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@arteck plese check travis ...

**Comment by arteck** [comment]
done

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hs100](https://github.com/arteck/ioBroker.hs100)
[Downloads](https://www.npmjs.com/package/iobroker.hs100) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hs100/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/arteck/ioBroker.hs100) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
