### PR TITLE
Updated countdown adapter to 1.0.5

### PR DESCRIPTION
**Pull request by jack-blackson**

### CODE REVIEW

**Comment by Apollon77** [comment]
Adapter checker results:
* [E801] .npmignore not found
* [E901] .gitignore not found

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.countdown](https://github.com/jack-blackson/ioBroker.countdown)
[Downloads](https://www.npmjs.com/package/iobroker.countdown) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.countdown/)

:thumbsup: No errors found
- [ ] :eyes: [W801] .npmignore not found
- [ ] :eyes: [W901] .gitignore not found

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.countdown](https://github.com/jack-blackson/ioBroker.countdown)
[Downloads](https://www.npmjs.com/package/iobroker.countdown) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.countdown/)

:thumbsup: No errors found
- [ ] :eyes: [W801] .npmignore not found
- [ ] :eyes: [W901] .gitignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by jack-blackson** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.countdown](https://github.com/jack-blackson/ioBroker.countdown)
[Downloads](https://www.npmjs.com/package/iobroker.countdown) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.countdown/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
