### PR TITLE
Update i2c to 1.2.0

### LINKED ISSUE #154: Update stable version in repo from 1.1.1 to 1.2.0
# Think about update stable version to 1.2.0
**Version**: stable=**1.1.1** (108 days old) => latest=**1.2.0** (15 days old)
**Installs**: stable=**275** (69.44%), latest=**46** (11.62%), total=**396**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L572)

### PR DESCRIPTION
**Pull request by UncleSamSwiss**
Closes https://github.com/UncleSamSwiss/ioBroker.i2c/issues/154

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.i2c](https://github.com/UncleSamSwiss/ioBroker.i2c)
[Downloads](https://www.npmjs.com/package/iobroker.i2c) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.i2c/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 UncleSamSwiss <samuel.weibel@gmail.com>" at the end of [README.md](https://github.com/UncleSamSwiss/ioBroker.i2c/blob/master/README.md)


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.i2c](https://github.com/UncleSamSwiss/ioBroker.i2c)
[Downloads](https://www.npmjs.com/package/iobroker.i2c) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.i2c/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 UncleSamSwiss <samuel.weibel@gmail.com>" at the end of [README.md](https://github.com/UncleSamSwiss/ioBroker.i2c/blob/master/README.md)


*Add comment "RE-CHECK!" to start check anew*

**Comment by UncleSamSwiss** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.i2c](https://github.com/UncleSamSwiss/ioBroker.i2c)
[Downloads](https://www.npmjs.com/package/iobroker.i2c) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.i2c/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
