### PR TITLE
Update hausbus_de to 1.4.6

### PR DESCRIPTION
**Pull request by hausbus**
Please update my adapter ioBroker.hausbus_de to version 1.4.6.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by hausbus** [comment]
@mcm1957 This version was pushed to stable directly because support for a new hardware module was added. This does not affect the current logic or functionality but allows to use the new hardware. This was just about making the adapter recognize the new hardware version. So potential side effects should be under control. If needed I can inform our customers that they will have to switch to latest or wait 1-2 weeks

**Comment by mcm1957** [comment]
Fixes for checker errors available at
https://github.com/hausbus/ioBroker.hausbus_de/pull/54
https://github.com/hausbus/ioBroker.hausbus_de/pull/55
https://github.com/hausbus/ioBroker.hausbus_de/pull/56

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
> @mcm1957 This version was pushed to stable directly because support for a new hardware module was added. This does not affect the current logic or functionality but allows to use the new hardware. This was just about making the adapter recognize the new hardware version. So potential side effects should be under control. If needed I can inform our customers that they will have to switch to latest or wait 1-2 weeks

OK, I'll release it as an exception as the number of users is small.
But normally a new version should by available at least 7 days at latest and have at least a few installations. 1.4.6 does not have any installation recorded today.

**Pull request merged**
