### PR TITLE
Added sanext

### PR DESCRIPTION
**Pull request by instalator**

### CODE REVIEW

**Comment by instalator** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sanext](https://github.com/instalator/ioBroker.sanext)
[Downloads](https://www.npmjs.com/package/iobroker.sanext) 
[NPM](https://nodei.co/npm/iobroker.sanext/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.sanext)!. Please execute in adapter directory: `npm owner add bluefox iobroker.sanext`
- [ ] :eyes: [W400] Cannot find "sanext" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sanext](https://github.com/instalator/ioBroker.sanext)
[Downloads](https://www.npmjs.com/package/iobroker.sanext) 
[NPM](https://nodei.co/npm/iobroker.sanext/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.sanext)!. Please execute in adapter directory: `npm owner add bluefox iobroker.sanext`
- [ ] :eyes: [W400] Cannot find "sanext" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by instalator** [comment]
> * exclamation [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.sanext)!. Please execute in adapter directory: `npm owner add bluefox iobroker.sanext`

false

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sanext](https://github.com/instalator/ioBroker.sanext)
[Downloads](https://www.npmjs.com/package/iobroker.sanext) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sanext/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.sanext)!. Please execute in adapter directory: `npm owner add bluefox iobroker.sanext`
- [ ] :eyes: [W400] Cannot find "sanext" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
