### PR TITLE
Add roborock to latest

### PR DESCRIPTION
**Pull request by copystring**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.


- sensitive information, especially passwords should be stored encrypted
  
  You configuration seems to contain passwords (or other sensitive information) which is not stored encrypted. As long as those information is not stored inside a table you can encrypt and secure this infomation simply by adding the following configuration to io-package.json. The iob runtime will encrypt / decrypt the data as required; no addition programming effort is required. Note that users will need to reenter this info one time after adding encryption, so drop a note at release notes.
  ```
  "encryptedNative": [
    "password",
    "data2"
  ],
  "protectedNative": [
    "password",
    "data2"
  ],
  ```

- consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- check and limit configurable timeouts / intervals
  
  Node setTimeout/setInterval routines have a maximum allowed value of 2,147,483,647 ms. Using delays larger than 2,147,483,647 ms (about 24.8 days) result in the timeout being executed immediately. So all (user configurable) values passed to setTimeout / setInterval should be checked and limited.
  
- check and limit intervals used to access cloud services
  
  Limit all intervals used to access cloud services to a reasonable value. If users configure an inapprobiate access rate this could lead to suspending the service by the provider for all ioBroker users.  

- cancel all timers at unload

  Your code seems to use setInterval to start polling. But there is no clearInterval at onUnload. Clearing all timers is essential to avoid memory leaks when running ion compact mode.
  
  
- This adapter seems to use sentry, but no sentry info is added to Readme.md
  
  This adapter seems to use sentry for error logging. Please add the suggested sentry information at the top of Readme.md
  
  ```**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0.```

  
- This adapter seems to implement sentry by itself and seems to be not using the sentry plugin. 

   Sentry should / must be an option for users so disabling sending any information to remote locations should be controllable by users. At least the user must be informed aboiut the fact that any data is transmitted. Please consider using the provides ioBroker sentry plugin which will handle opting out of sentry.

  
Thanks for reading and evaluating this suggestions.
McM1957

**Comment by copystring** [comment]
Hi. Thank you for your suggestions. I took care of (almost) all of them.

 - sensitive information, especially passwords should be stored encrypted -> fixed
 - consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout -> done
 - cancel all timers at unload -> done
 - This adapter seems to use sentry, but no sentry info is added to Readme.md -> done
 - This adapter seems to implement sentry by itself and seems to be not using the sentry plugin. -> done

**Comment by mcm1957** [comment]
Thank for your effort and for spending tim efor ioBroker adapters! 
Hope this makes the official review faster and with less comments.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lightify](https://github.com/soef/ioBroker.lightify)
[Downloads](https://www.npmjs.com/package/iobroker.lightify) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lightify/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL in [package.json](https://github.com/soef/ioBroker.lightify/blob/master/package.json): https://github.com/soef/iobroker.lightify. Expected: git@github.com:soef/ioBroker.lightify.git or https://github.com/soef/ioBroker.lightify.git
- [ ] :heavy_exclamation_mark: [E104] No "common.titleLang" found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E115] No license found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)

### [ioBroker.mihome-cloud](https://github.com/TA2k/ioBroker.mihome-cloud)
[Downloads](https://www.npmjs.com/package/iobroker.mihome-cloud) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mihome-cloud/)

- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
- [ ] :heavy_exclamation_mark: [E407] Meta URL (latest) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
- [ ] :heavy_exclamation_mark: [E426] Icon (stable) must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
- [ ] :heavy_exclamation_mark: [E428] Meta URL (stable) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
- [ ] :heavy_exclamation_mark: [E606] Current adapter version 0.1.0 not found in [README.md](https://github.com/TA2k/ioBroker.mihome-cloud/blob/master/README.md)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/TA2k/ioBroker.mihome-cloud/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W515] Why you decided to disable i18n support?

### [ioBroker.roborock](https://github.com/copystring/ioBroker.roborock)
[Downloads](https://www.npmjs.com/package/iobroker.roborock) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.roborock/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "roborock" in latest repository

### [ioBroker.semp](https://github.com/rg-engineering/ioBroker.semp)
[Downloads](https://www.npmjs.com/package/iobroker.semp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.semp/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.semp)!. Please execute in adapter directory: `npm owner add bluefox iobroker.semp`
- [ ] :heavy_exclamation_mark: [E506] Word "DeviceSwitchOffAtEndOfTimer" is not translated to german in [admin/words.js](https://github.com/rg-engineering/ioBroker.semp/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "DeviceSwitchOffAtEndOfTimer" is not translated to russian in [admin/words.js](https://github.com/rg-engineering/ioBroker.semp/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W202] Version of [package.json](https://github.com/rg-engineering/ioBroker.semp/blob/master/package.json) (1.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.semp) (1.0.0)

### [ioBroker.vis-2-widgets-gauges](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges)
[Downloads](https://www.npmjs.com/package/iobroker.vis-2-widgets-gauges) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-2-widgets-gauges/)

- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E162] onlyWWW should have common.mode "none" in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E124] Main file not found under URL: https://raw.githubusercontent.com/ioBroker/ioBroker.vis-2-widgets-gauges/main/main.js
- [ ] :heavy_exclamation_mark: [E504] "main.js" found in [package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.vis-2-widgets-material](https://github.com/ioBroker/ioBroker.vis-2-widgets-material)
[Downloads](https://www.npmjs.com/package/iobroker.vis-2-widgets-material) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-2-widgets-material/)

- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E162] onlyWWW should have common.mode "none" in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E142] logo is too big. It must be less or equal than 512x512
- [ ] :heavy_exclamation_mark: [E124] Main file not found under URL: https://raw.githubusercontent.com/ioBroker/ioBroker.vis-2-widgets-material/main/main.js
- [ ] :heavy_exclamation_mark: [E504] "main.js" found in [package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/ioBroker/ioBroker.vis-2-widgets-material", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/ioBroker/ioBroker.vis-2-widgets-material", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.roborock](https://github.com/copystring/ioBroker.roborock)
[Downloads](https://www.npmjs.com/package/iobroker.roborock) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.roborock/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "roborock" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
Please remove node 14 from test-and-release.yml and (optionally) add node 20 to testing matrix.
Node 14 is no longer supported and tests will fail since 22.5.2023.

Thanks
McM1957

**Comment by copystring** [comment]
Sure. How do make this change appear here?

**Comment by mcm1957** [comment]
> Sure. How do make this change appear here?

simply change it at your repository at main/master branch (edit and commit workflows/test-and-release.yml)
Head revision will be used for github actions

**Comment by copystring** [comment]
Done.

**Comment by mcm1957** [comment]
I've done a recheck of my comments from february. Thanks for applying 99% of my suggestions.

The following suggestion has not been applied yet:
- check and limit configurable timeouts / intervals

Node setTimeout/setInterval routines have a maximum allowed value of 2,147,483,647 ms. Using delays larger than 2,147,483,647 ms (about 24.8 days) result in the timeout being executed immediately. So all (user configurable) values passed to setTimeout / setInterval should be checked and limited.

Did I miss something when reading the code?
Currently the intervall values seem to have no limit - neither at jsonCponfig nor inside code. This could result in someone entering zero or even a negative value which in turn could easily overload the ioBroker installation or the target device. So I would suggest to add limits at jsonConfig (min attribute / eventually max attribute) and preferable at code too.

Otherwise everything looks fine for me - but it would be no surprise if apollon77 sees something additional :-)

**Comment by copystring** [comment]
Do you mean the ones the user can set in the options of the adapter?

**Comment by copystring** [comment]
Fixed via https://github.com/copystring/ioBroker.roborock/commit/0e4f5d385faaf5a3ac417a63434043e32c3c5dd8

**Comment by mcm1957** [comment]
Yes I refer to the interval limits the user can set via config page.
I'm not sure whether setting limits inside io-config.json works; I will have to check this myself. Nerver done there until now.
I would have suggested to ass the limits to the json config. You find examples for jsonConfig at mcm57/ioBroker.jsonConfig-demo "adapter". But I'm not sure wthere limiting example is implemented yet.

Please simply try whether you can inster 0 or a negative value into the instance config or use increment / decrement to reach too small values and try to store such a config. If it fails - evrything ok.

**Comment by copystring** [comment]
I can confirm this works just fine. It is not possible to enter a value below or above min/max.

**Pull request merged**
