### PR TITLE
Bump Tradfri to 2.7.1

### PR DESCRIPTION
**Pull request by AlCalzone**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tradfri](https://github.com/AlCalzone/ioBroker.tradfri)
[Downloads](https://www.npmjs.com/package/iobroker.tradfri) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.tradfri/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/AlCalzone/ioBroker.tradfri/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/AlCalzone/ioBroker.tradfri/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2017-2021 AlCalzone <d.griesel@gmx.net>" at the end of [README.md](https://github.com/AlCalzone/ioBroker.tradfri/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2017-2021 AlCalzone <d.griesel@gmx.net>" at the start of LICENSE
- [ ] :eyes: [W801] .npmignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by AlCalzone** [comment]
working on it - this is going to be v2.7.1

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tradfri](https://github.com/AlCalzone/ioBroker.tradfri)
[Downloads](https://www.npmjs.com/package/iobroker.tradfri) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.tradfri/)

:thumbsup: No errors found
- [ ] :eyes: [W801] .npmignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by AlCalzone** [comment]
2.7.1 is functionally identical to 2.7.0 (15 days old) - just fixed the issues in io-package.json.

**Pull request merged**
