### PR TITLE
Update Alpha-ESS to 0.5.0

### PR DESCRIPTION
**Pull request by Gaspode69**

### CODE REVIEW

**Comment by Gaspode69** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alpha-ess](https://github.com/Gaspode69/ioBroker.alpha-ess)
[Downloads](https://www.npmjs.com/package/iobroker.alpha-ess) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alpha-ess/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
@Apollon77 
Not quite sure why an autocheck and a Review needed is tagged here. Looks like some mistriggering of check script.

PR seems to be a normal update to stable besides the jump from 0.2.0 to 0.5.0. 

(Sorry, if I'm incorrect and bothering you)

**Comment by Apollon77** [comment]
Uups. Übersehen.

**Pull request merged**
