### PR TITLE
Add pid to latest

### PR DESCRIPTION
**Pull request by mcm1957**
Please add my adapter ioBroker.envertech-pv to latest.

Replacement for PR #2228 which was closed on error during test

NOTE: adding bluefox does not work dues to insufficient permissions. Please check. Adapter was created directly inside community area

```
npm owner add bluefox iobroker.pid"
This operation requires a one-time password.
Enter OTP: npm ERR! code EOWNERMUTATE
npm ERR! Failed to update package: "canceled"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Martin\AppData\Local\npm-cache\_logs\2023-05-07T12_41_53_596Z-debug-0.log

E:\GitHub\mcm1957\create-adapter>

E:\GitHub\mcm1957\create-adapter>

E:\GitHub\mcm1957\create-adapter>npm owner add bluefox iobroker.pid
This operation requires a one-time password.
Enter OTP: 151651
npm ERR! code EOWNERMUTATE
npm ERR! Failed to update package: "403 Forbidden - PUT https://registry.npmjs.org/iobroker.pid/-rev/2-07d5f40ee96290dae59956f9b37fec62 - You do not have permission to publish \"iobroker.pid\". Are you logged in as the correct user?"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Martin\AppData\Local\npm-cache\_logs\2023-05-07T12_42_09_723Z-debug-0.log

```

```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@8.15.0
2 info using node@v16.17.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:E:\GitHub\mcm1957\create-adapter\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\Martin\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\Martin\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 timing npm:load:configload Completed in 11ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm owner add bluefox iobroker.pid
23 verbose argv "owner" "add" "bluefox" "iobroker.pid"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:C:\Users\Martin\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\Martin\AppData\Local\npm-cache\_logs\2023-05-07T12_42_09_723Z-debug-0.log
29 timing npm:load:logFile Completed in 11ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 28ms
33 verbose owner add bluefox to iobroker.pid
34 silly logfile start cleaning logs, removing 2 files
35 silly logfile done cleaning log files
36 http fetch GET 200 https://registry.npmjs.org/-/user/org.couchdb.user:bluefox 413ms (cache updated)
37 http fetch GET 200 https://registry.npmjs.org/iobroker.pid 62ms (cache revalidated)
38 http fetch PUT 401 https://registry.npmjs.org/iobroker.pid/-rev/2-07d5f40ee96290dae59956f9b37fec62 850ms
39 http fetch PUT 403 https://registry.npmjs.org/iobroker.pid/-rev/2-07d5f40ee96290dae59956f9b37fec62 710ms
40 timing command:owner Completed in 30839ms
41 verbose stack Error: Failed to update package: "403 Forbidden - PUT https://registry.npmjs.org/iobroker.pid/-rev/2-07d5f40ee96290dae59956f9b37fec62 - You do not have permission to publish \"iobroker.pid\". Are you logged in as the correct user?"
41 verbose stack     at Owner.changeOwners (C:\Program Files\nodejs\node_modules\npm\lib\commands\owner.js:225:9)
41 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
41 verbose stack     at async Owner.exec (C:\Program Files\nodejs\node_modules\npm\lib\commands\owner.js:77:7)
41 verbose stack     at async module.exports (C:\Program Files\nodejs\node_modules\npm\lib\cli.js:78:5)
42 verbose cwd E:\GitHub\mcm1957\create-adapter
43 verbose Windows_NT 10.0.19045
44 verbose node v16.17.0
45 verbose npm  v8.15.0
46 error code EOWNERMUTATE
47 error Failed to update package: "403 Forbidden - PUT https://registry.npmjs.org/iobroker.pid/-rev/2-07d5f40ee96290dae59956f9b37fec62 - You do not have permission to publish \"iobroker.pid\". Are you logged in as the correct user?"
48 verbose exit 1
49 timing npm Completed in 30902ms
50 verbose code 1
51 error A complete log of this run can be found in:
51 error     C:\Users\Martin\AppData\Local\npm-cache\_logs\2023-05-07T12_42_09_723Z-debug-0.log
```

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.pid](https://github.com/iobroker-community-adapters/ioBroker.pid)
[Downloads](https://www.npmjs.com/package/iobroker.pid) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.pid/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.pid)!. Please execute in adapter directory: `npm owner add bluefox iobroker.pid`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.pid/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "pid" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@Apollon77 
Please fix access for Bluefox. I do not have sufficient rights

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@mcm1957 

This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, ist OK to continue using this topic too.

**Pull request merged**
