### PR TITLE
add Adapter Webuntis

### PR DESCRIPTION
**Pull request by Newan**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [package.json](https://github.com/main/package.json)
[Downloads](https://www.npmjs.com/package/package.json) 
[NPM](https://nodei.co/npm/package.json/)

- [ ] :heavy_exclamation_mark: 404: Invalid URL


*Add comment "RE-CHECK!" to start check anew*

**Comment by Newan** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [package.json](https://github.com/main/package.json)
[Downloads](https://www.npmjs.com/package/package.json) 
[NPM](https://nodei.co/npm/package.json/)

- [ ] :heavy_exclamation_mark: 404: Invalid URL

### [ioBroker.webuntis](https://github.com/Newan/ioBroker.webuntis)
[Downloads](https://www.npmjs.com/package/iobroker.webuntis) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.webuntis/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "webuntis" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by ldittmar81** [comment]
https://github.com/ioBroker/AdapterRequests/issues/673 can be closed after merge

**Comment by Apollon77** [comment]
@Newan you should please add tzhe adapter to the latest repo first ...

**Comment by Newan** [comment]
> @Newan you should please add tzhe adapter to the latest repo first ...

Sorry, i forgot it

**Comment by Apollon77** [comment]
Hi @Newan,

here some review comments:
* Should the client secret be better stored encrpted?
* when you add the info.connection stat eplease also add the respenctive channel https://github.com/Newan/ioBroker.webuntis/blob/main/io-package.json#L127
* AN adater that does something on a in fact schedule on full hour (and only then) ... do you not think it makes more sense to do that as a scheduled adapter? Buecause it will use resources (like RAM) all the time and in fact only do something every hour ...
* Optionally you could remember which objects were already created to not always re-create them

Thank you for checking and adjusting

**Comment by Newan** [comment]
> * Should the client secret be better stored encrpted?
In any case, I thought I did. I still have it entered in the io-package.json
> * when you add the info.connection stat eplease also add the respenctive channel https://github.com/Newan/ioBroker.webuntis/blob/main/io-package.json#L127
In any case, I thought I did. I still have it entered in the io-package.json
> * AN adater that does something on a in fact schedule on full hour (and only then) ... do you not think it makes more sense to do that as a scheduled adapter? Buecause it will use resources (like RAM) all the time and in fact only do something every hour ...
Basically yes, but later the interval should be set by each person and be shorter. For chat with teachers etc

**Comment by Apollon77** [comment]
Just a last small thingy: For the auto encryption please add a "common.globalDependency" to admin >= 4.0.9 to the io-package

**Comment by Newan** [comment]
> Just a last small thingy: For the auto encryption please add a "common.globalDependency" to admin >= 4.0.9 to the io-package

ok, please check it.. if it is ok i create a new version

**Pull request merged**
