### PR TITLE
Added pvforecast

### PR DESCRIPTION
**Pull request by klein0r**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.pvforecast](https://github.com/iobroker-community-adapters/ioBroker.pvforecast)
[Downloads](https://www.npmjs.com/package/iobroker.pvforecast) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.pvforecast/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "pvforecast" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@klein0r Can you plesse fix the PR and remove the package-lock changes?

**Comment by klein0r** [comment]
Oh, I'm sorry - still have no idea how that happened. Will open a new PR (since I don't know how to remove a file from a commit) 😄

**Pull request closed without merging**
