### PR TITLE
Add zendure-solarflow to latest

### PR DESCRIPTION
**Pull request by nograx**
Please add my adapter ioBroker.zendure-solarflow to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by nograx** [comment]
Fixed the issues on GitHub actions. I will bump the version number if first test from other users are successful.

**Comment by mcm1957** [comment]
@nograx 

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- [ ] sensitive information, especially passwords should be stored encrypted
  
  You configuration seems to contain passwords (or other sensitive information) which is not stored encrypted. As long as those information is not stored inside a table you can encrypt and secure this infomation simply by adding the following configuration to io-package.json. The iob runtime will encrypt / decrypt the data as required; no addition programming effort is required. Note that users will need to reenter this info one time after adding encryption, so drop a note at release notes.
  ```
  "encryptedNative": [
    "password",
    "data2"
  ],
  "protectedNative": [
    "password",
    "data2"
  ],
  ```

- [ ] logging state changes at level info 
  Please check wether logging state changes at level info is required. I would suggest level debug to be sufficient unless you are sure, that only such states are subscribe which are very seldom changed.

- [ ] invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```

  Your state Ids are composed of productKey and deviceKey. I did not see a verification that thise values do not contain illegal characters. Even if the current api ensures that all charactes are valid, this shoudl be checked at code as either the api could cahnge or due to some problem random data could be read.

- [ ] onStateChange handler ignores ack flag 

  The adapter must honor the ack flag when processing onStateChange events. Whenever the onStateChange handler is called for an own state (a state owned by the processing instance of the adapter) it must ignore this event if the ack flags is set. Only stateChanges with ack==false are allowed to be processed.

  When processing foreign states which are output of another adapter  processing must only occure if the ack flag is true.

- [ ] folder creation seems to be missing

  You use state ids like '    productKey + "." + deviceKey + "." + "lastUpdate", '

  So you must explicitly create folders (type: folder, device, channel) for productKey and deviceKey explicitly. Pleaase note that ioBroker standards require [device.[channel.[folder...]]].state sequence.

- [ ] reevaluate state roles and read/write flags

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whnever a dedicated role exists.

  Several states seem to have write flag set to true althoug the are not to be written by user for sure. Please set write to false except the state is to be written by user and handled at onStateChange.

  outputLimit must by of type level as it is an input value

- [ ] axios calls should have timeouts

  All axios calls should have a timeout specified as default for timeout according to axios docu is 0 = no timeout. ZThis could lead to stalled processing

- [ ] consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- [ ] time / itervalls must be cleard at unload

  All timers and intervalltimers mut be cleared during execution aof onUnload. This is required as otherwise timers could lead to carshes when using compact mode where multiple adapters shre one process environment.
  
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
@nograx 

Do you need any help? 
Need some topics more explanation?

**Comment by nograx** [comment]
Hi,
there where some points... not enough time, the adapter is running fine in my environment and it seems there is a small demand for this adapter... 

I've tried to fix all the issues mentioned above. 
Thanks,
Peter

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@nograx 
Thanks for review / changes,

Did you miss

- [ ] axios calls should have timeouts

  All axios calls should have a timeout specified as default for timeout according to axios docu is 0 = no timeout. ZThis could lead to stalled processing

or do **I** miss something. axios does not have a default timeout, so in case of a non or slow answering server this culd lead to hanging adapters. Especially combined with intall this is not safe. axios timeoput should be shorter than interval.

Please review or comment

**Comment by nograx** [comment]
Hi,

you're right. Forgot to add the timeout. Fixed it in release 1.0.4.

Cheers, 
Peter

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, ist OK to continue using this topic too.

**Pull request merged**
