### PR TITLE
UP vis-players

### PR DESCRIPTION
**Pull request by instalator**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-players](https://github.com/instalator/ioBroker.vis-players)
[Downloads](https://www.npmjs.com/package/iobroker.vis-players) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-players/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/instalator/ioBroker.vis-players) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by instalator** [comment]
https://github.com/instalator/ioBroker.vis-players/issues/10

**Comment by instalator** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-players](https://github.com/instalator/ioBroker.vis-players)
[Downloads](https://www.npmjs.com/package/iobroker.vis-players) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-players/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/instalator/ioBroker.vis-players) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by instalator** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-players](https://github.com/instalator/ioBroker.vis-players)
[Downloads](https://www.npmjs.com/package/iobroker.vis-players) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-players/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/instalator/ioBroker.vis-players) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by instalator** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-players](https://github.com/instalator/ioBroker.vis-players)
[Downloads](https://www.npmjs.com/package/iobroker.vis-players) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-players/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/instalator/ioBroker.vis-players) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by instalator** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-players](https://github.com/instalator/ioBroker.vis-players)
[Downloads](https://www.npmjs.com/package/iobroker.vis-players) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-players/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
