### PR TITLE
Added lighcontrol adapter

### PR DESCRIPTION
**Pull request by Schmakus**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lightcontrol](https://github.com/schmakus/ioBroker.lightcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.lightcontrol) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.lightcontrol/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.lightcontrol)!. Please execute in adapter directory: `npm owner add bluefox iobroker.lightcontrol`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/schmakus/ioBroker.lightcontrol/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "lightcontrol" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@Schmakus Please add Blueox to Npm if not done

and BTW: https://weblate.iobroker.net/projects/adapters/lightcontrol/#repository ... did you force pushed to the repo? Weblate do not like this

**Comment by Schmakus** [comment]
> @Schmakus Please add Blueox to Npm if not done
> 
> and BTW: https://weblate.iobroker.net/projects/adapters/lightcontrol/#repository ... did you force pushed to the repo? Weblate do not like this

no, I didn't. only push or PR

**Comment by Schmakus** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lightcontrol](https://github.com/schmakus/ioBroker.lightcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.lightcontrol) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.lightcontrol/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Ok, I have reset weblate for now. lets see if it happens again

**Comment by mcm1957** [comment]
> > @Schmakus Please add Blueox to Npm if not done
> > and BTW: https://weblate.iobroker.net/projects/adapters/lightcontrol/#repository ... did you force pushed to the repo? Weblate do not like this
> 
> no, I didn't. only push or PR

@Schmakus
Your repository seems to contain some translation keys which do not have an english translation (- whih seem to be missing in en/translatio.json. See https://github.com/ioBrokerTranslator/requests/issues/106#issuecomment-1368098578
Maybe this could confuse weblate too as english is configured as source language. So every key should have at least an english translation (@Apollon77  please correct me if I'm wrong)

**Comment by Schmakus** [comment]
> > > @Schmakus Please add Blueox to Npm if not done
> > > and BTW: https://weblate.iobroker.net/projects/adapters/lightcontrol/#repository ... did you force pushed to the repo? Weblate do not like this
> > 
> > 
> > no, I didn't. only push or PR
> 
> @Schmakus Your repository seems to contain some translation keys which do not have an english translation (- whih seem to be missing in en/translatio.json. See [ioBrokerTranslator/requests#106 (comment)](https://github.com/ioBrokerTranslator/requests/issues/106#issuecomment-1368098578) Maybe this could confuse weblate too as english is configured as source language. So every key should have at least an english translation (@Apollon77 please correct me if I'm wrong)

I did not find any missing translations. only one translation en -> de at the en json file.

**Comment by mcm1957** [comment]
The key "Add Light" and the key "All" contain translations at https://github.com/Schmakus/ioBroker.lightcontrol/tree/main/admin/i18n/de/translations.json 

But I could not find those keys at https://github.com/Schmakus/ioBroker.lightcontrol/tree/main/admin/i18n/en/translations.json

I assume that this could either confuse weblate or that some future translation PR will remove the keys from the german translation. So I suggest to check if those keys are missing in english - or are outdated in other languages

**Comment by Schmakus** [comment]
Ok, what is the best practice to delete unused translations? I thought that if I delete unused translations at en.json then it automatically delete in the other files.

**Comment by mcm1957** [comment]
> Ok, what is the best practice to delete unused translations? I thought that if I delete unused translations at en.json then it automatically delete in the other files.

Ok
Thats what I know too.

So if I understand your post those keys are obsolete and removed at purpose at english version.

I guess that at time of adding weblate support german and english files were not in sync. I guess at this time the english translation was already temoved but the german still existedin the files.

Maybe weblate will remove the gernan translations when the next rebuild of files is triggered due to a change in english file. But I do not know for sure if the misding keys will be detected as they are not present in current english import state already. So no change for the key is detected by weblate. 

@UncleSamSwiss is the specialist who could know how this works. Eventually contect him at telegram or wait if he answers here.

**Comment by UncleSamSwiss** [comment]
Sorry, no clue either.

**Comment by Schmakus** [comment]
Well,I could try to add the missing values to the en.json and push it?!

**Comment by Schmakus** [comment]
@mcm1957 please check it again. I have updated the translations.

**Comment by mcm1957** [comment]
> @mcm1957 please check it again. I have updated the translations.

seems to be ok - I could not detect any missing strings anaymore.

**Comment by mcm1957** [comment]
> Ok, what is the best practice to delete unused translations? I thought that if I delete unused translations at en.json then it automatically delete in the other files.

Hi,
I checked the weblate setup and I will add an additional plugin to adapter lightcontrol. With this additional addon removing a translation from the source (eb) translations.json will (or at least should) result in removal of the oitdated string from all languages.

If you like you can test it by removing the obsolete translations from you en file and cmmit/push ist to your repository. You should get an PR from weblate after some time (max 1 day).

If there are further issues which are only realted to weblate, please oben a issue at https://github.com/ioBrokerTranslator/requests

**Comment by Schmakus** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lightcontrol](https://github.com/schmakus/ioBroker.lightcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.lightcontrol) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.lightcontrol/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

here my review results.

* Are Links to issues really working in changelog in Admin?
* is custom_m really used ? https://github.com/Schmakus/ioBroker.lightcontrol/blob/main/admin/custom_m.html seems like not. Then remove it please and also remove it from io-package
* is materialize-css really a production dependency?
* please have alook in the testing ... a new installation will also start that way tzhe first time ... aka crash the first time https://github.com/Schmakus/ioBroker.lightcontrol/actions/runs/3884107331/jobs/6626231358#step:2:690 - the second parameter here is wrong https://github.com/Schmakus/ioBroker.lightcontrol/blob/main/main.js#L997

Thanks for checking and fixing ... Please poke here when ready for a re-check

Ingo

**Comment by Schmakus** [comment]
ready for a re-check

**Comment by Apollon77** [comment]
Hi,

please still remove custom_m.html (because not used), but I will merge it now :-)

Ingo

**Pull request merged**
