### PR TITLE
add ioBroker.apg-info to repo

### PR DESCRIPTION
**Pull request by HGlab01**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
Repochecker reports the following issues. Please note that E201 (npm access for bluefox) is mandatory.
 
[E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.apg-info"
[W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W400] Cannot find "apg-info" in latest repository
[W515] Why you decided to disable i18n support?

**Comment by HGlab01** [comment]
> Repochecker reports the following issues. Please note that E201 (npm access for bluefox) is mandatory.
> 
> [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.apg-info"

image

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- adapter seems to have no configurable settings but custom_m and jsonConfiog.json exist
  
  It looks like this adapter does not have any configurable settings. But in this case admin/custom:m.html and jsonConfig.json (which contains template data only) seem to be obsolete. Please consider removing all unneeded files.

- words.js seems to belong to other adapter
   
  Consider removing words.js if not needed or generate a matching words.js if used at all.

```
systemDictionary = {
    'fuelpricemonitor adapter settings': {
        'en': 'Adapter settings for fuelpricemonitor',
```

- scheduled adapters should (must) have random delays
  
  An unmodified schedule adapter that queries data from external systems will produce a lot of issues because usually the default schedule stays unchanged for all users and so all installations out there will then contact the server at the exact same time create a "potentially huge" request spike. The best practice for now is at least to add a random delay to spread the calls within that minute - or even move the "minutes" on first start and so persist that (e.g. see https://github.com/ioBroker/ioBroker.yr/blob/master/main.js#L84-L90) ... if the adapter gets successfull then we have a big issue and the webpage owner contacting us ... we should prevent that from the beginning.

  Your adapter seems to have  a fixed schedule at io-package.json 
```    "schedule": "14 1 0,14 * * *",```

- do not access cloud services at fixed timestamps
  
  Avoid accessing cloud services at fixed timestamps (i.e. at every full hour, at 5 minutes after midnight , ...) This could lead to high load peaks at the cloud service as all ioBorker installations will use the service at almost the same time. Use random timestamps where possible.  

- This adapter seems to use sentry, but no sentry info is added to Readme.md
  
  This adapter seems to use sentry for error logging. Please add the suggested sentry information at the top of Readme.md
  
  ```**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0.```
  
- This adapter seems to use a private sentry implementation without possibility to disable sentry

  This adapter seems to use some sentry implementaion for error logging. But it looks like the user has no possibility to disable this. Due to data protection good practice the user should at least have the possibility to opt-out. Please consider using the standard ioBroker sentry plugin which will provide this possibility.
  

Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by HGlab01** [comment]
Thanks @mcm1957 for the review and all the valuable input. Highly appreciated! 

- ad custom_m, jsonConfiog.json and word.js --> thanks will do
- schedule/cloud service --> fully agree; I had not really an idea how to solve for an adapter that starts via cron job  - but I will look in the solution you provided
- Sentry --> currently it is not activated, but in the readme it is mentioned
image
https://github.com/HGlab01/ioBroker.apg-info/blob/66b4d9bf6faf3e2aa32b4ed1f249100cb704adf6/README.md?plain=1#L18
- Sentry implementation --> I use the iobroker implementation (for this and other adapters) and I also tested it (in other adapters) if sentry is disabled then sentry stays silent
https://github.com/HGlab01/ioBroker.apg-info/blob/66b4d9bf6faf3e2aa32b4ed1f249100cb704adf6/main.js#L301-L314

Please feel free to reply/challenge my feedback ;-)

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
No,not that I m aware of.

Theres only a big lack of time from Apollon77 who must doba review and accept the adapter.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.apg-info](https://github.com/HGlab01/ioBroker.apg-info)
[Downloads](https://www.npmjs.com/package/iobroker.apg-info) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.apg-info/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "apg-info" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?

### [ioBroker.lightify](https://github.com/soef/ioBroker.lightify)
[Downloads](https://www.npmjs.com/package/iobroker.lightify) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lightify/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL in [package.json](https://github.com/soef/ioBroker.lightify/blob/master/package.json): https://github.com/soef/iobroker.lightify. Expected: git@github.com:soef/ioBroker.lightify.git or https://github.com/soef/ioBroker.lightify.git
- [ ] :heavy_exclamation_mark: [E104] No "common.titleLang" found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E115] No license found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)

### [ioBroker.mihome-cloud](https://github.com/TA2k/ioBroker.mihome-cloud)
[Downloads](https://www.npmjs.com/package/iobroker.mihome-cloud) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mihome-cloud/)

- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
- [ ] :heavy_exclamation_mark: [E407] Meta URL (latest) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
- [ ] :heavy_exclamation_mark: [E426] Icon (stable) must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
- [ ] :heavy_exclamation_mark: [E428] Meta URL (stable) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
- [ ] :heavy_exclamation_mark: [E606] Current adapter version 0.1.0 not found in [README.md](https://github.com/TA2k/ioBroker.mihome-cloud/blob/master/README.md)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/TA2k/ioBroker.mihome-cloud/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W515] Why you decided to disable i18n support?

### [ioBroker.semp](https://github.com/rg-engineering/ioBroker.semp)
[Downloads](https://www.npmjs.com/package/iobroker.semp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.semp/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.semp)!. Please execute in adapter directory: `npm owner add bluefox iobroker.semp`
- [ ] :heavy_exclamation_mark: [E506] Word "DeviceSwitchOffAtEndOfTimer" is not translated to german in [admin/words.js](https://github.com/rg-engineering/ioBroker.semp/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "DeviceSwitchOffAtEndOfTimer" is not translated to russian in [admin/words.js](https://github.com/rg-engineering/ioBroker.semp/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W202] Version of [package.json](https://github.com/rg-engineering/ioBroker.semp/blob/master/package.json) (1.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.semp) (1.0.0)

### [ioBroker.vis-2-widgets-gauges](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges)
[Downloads](https://www.npmjs.com/package/iobroker.vis-2-widgets-gauges) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-2-widgets-gauges/)

- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E162] onlyWWW should have common.mode "none" in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E124] Main file not found under URL: https://raw.githubusercontent.com/ioBroker/ioBroker.vis-2-widgets-gauges/main/main.js
- [ ] :heavy_exclamation_mark: [E504] "main.js" found in [package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.vis-2-widgets-material](https://github.com/ioBroker/ioBroker.vis-2-widgets-material)
[Downloads](https://www.npmjs.com/package/iobroker.vis-2-widgets-material) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-2-widgets-material/)

- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E162] onlyWWW should have common.mode "none" in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E142] logo is too big. It must be less or equal than 512x512
- [ ] :heavy_exclamation_mark: [E124] Main file not found under URL: https://raw.githubusercontent.com/ioBroker/ioBroker.vis-2-widgets-material/main/main.js
- [ ] :heavy_exclamation_mark: [E504] "main.js" found in [package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/ioBroker/ioBroker.vis-2-widgets-material", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/ioBroker/ioBroker.vis-2-widgets-material", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.apg-info](https://github.com/HGlab01/ioBroker.apg-info)
[Downloads](https://www.npmjs.com/package/iobroker.apg-info) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.apg-info/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "apg-info" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
Please remove node 14 from test-and-release.yml and (optionally) add node 20 to testing matrix.
Node 14 is no longer supported and tests will fail since 22.5.2023.

Thanks
McM1957

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by HGlab01** [comment]
> Please remove node 14 from test-and-release.yml and (optionally) add node 20 to testing matrix. Node 14 is no longer supported and tests will fail since 22.5.2023.
> 
> Thanks McM1957

done!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.apg-info](https://github.com/HGlab01/ioBroker.apg-info)
[Downloads](https://www.npmjs.com/package/iobroker.apg-info) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.apg-info/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "apg-info" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by HGlab01** [comment]
Thanx Ingo, I know you are super busy... Maybe there is midterm a solution to extend the review team...

**Comment by Apollon77** [comment]
@mcm1957 already support and in fact any developer can support in doing reviews of other developers

**Comment by mcm1957** [comment]
@HGlab01 

Any reason to cancel this PR?
Or done on error by deleting your fork ...

In the later case, please open a new PR an reference this PR.

**Comment by HGlab01** [comment]
ups! I did not take the open PR into account as I deleted the fork 
well do

**Comment by mcm1957** [comment]
Happened to me too some time ago.
So I asked explicitly.

**Pull request closed without merging**
