### PR TITLE
please add daswetter and vis-weather into repos

### PR DESCRIPTION
**Pull request by rg-engineering**
both are quite stable so we should move them to repositories.
Beside that I prepared sbfspot for repos but this is not stable enough for stable-repo...

### CODE REVIEW

**Comment by Apollon77** [comment]
Hey,
The Logo from sbfspot is not really matching to the adapter, or ?! Is it not possible to make something out of the sbfspot logo or such?!

**Comment by Apollon77** [comment]
can you please remove the project file?!

**Comment by GermanBluefox** [comment]
And please add a smaller logo.

**Comment by rg-engineering** [comment]
> And please add a smaller logo.
Is there a maximum size or what is the requirement?

**Pull request merged**
