### PR TITLE
set Nuki version 1.1.4 to stable

### PR DESCRIPTION
**Pull request by smaragdschlange**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nuki](https://github.com/smaragdschlange/ioBroker.nuki)
[Downloads](https://www.npmjs.com/package/iobroker.nuki) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.nuki/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js, but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@smaragdschlange also if it is displayed as "warning" please check and fix the timeouts and clear them in unload method

**Comment by smaragdschlange** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nuki](https://github.com/smaragdschlange/ioBroker.nuki)
[Downloads](https://www.npmjs.com/package/iobroker.nuki) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.nuki/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@smaragdschlange but because we talk about stable update here you should increase the version number accordingly ;-)

**Comment by smaragdschlange** [comment]
@Apollon77 ok, but changing the version number again also means that I'll have to let the community test it again. I will do so.

Thanks

**Comment by Apollon77** [comment]
I would accept it also after a check by you in this case :-)

**Pull request closed without merging**
