### PR TITLE
Add solarmanpv to latest

### PR DESCRIPTION
**Pull request by raschy**
Please add my adapter ioBroker.solarmanpv to latest.

*This pull request was created by https://www.iobroker.dev 79ffd9b.*

### CODE REVIEW

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.solarmanpv](https://github.com/raschy/ioBroker.solarmanpv)
[Downloads](https://www.npmjs.com/package/iobroker.solarmanpv) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.solarmanpv/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "solarmanpv" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

thank you for your submission and here are some review comments:
* Please do not mix languages in readme because it gets automatically translated! Please remove the german part
* whats that? https://github.com/raschy/ioBroker.solarmanpv/blob/main/admin/jsonConfig.json#L45-L46 I think this do nt belong there
* migth role value.power better for https://github.com/raschy/ioBroker.solarmanpv/blob/139675d5b871a4b9ea234ffe6afa5054f079e7d5/main.js#L198 ?

Thank you for checking and adjusting my comments,

Ingo

**Comment by raschy** [comment]
Hi Ingo,
I have fixed the addressed lines and removed the German text of the readme. I hope everything is satisfactory now.

Greetings Rainer

**Comment by Apollon77** [comment]
why you closed the PR?

**Comment by Apollon77** [comment]
Yes, welcome in the repo

**Comment by raschy** [comment]
Sorry, I just wanted to report back but not close! Wrong button.

**Comment by raschy** [comment]
Hi Ingo, thank you for the addition to the repo. Rainer

**Pull request merged**
