### PR TITLE
add bydhvs adapter to official repository

### PR DESCRIPTION
**Pull request by christianh17**
discussion see: https://forum.iobroker.net/topic/43931/neuer-adapter-byd-hvs/51

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@christianh17 The adapter is not in the latest repo (the other file) ... please add there too ... normally it goes into latest first ...

**Comment by christianh17** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by christianh17** [comment]
I just did some small bug fixes, did a new version and added this one to the latest-repository. The RE-CHECK-Posting was deleted automatically :-(. Sorry, I am new with this kind of stuff, can you please give me some advice what to do next? Thanks.

**Comment by Apollon77** [comment]
All good, I will do review later todaay

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

some review comments:
* Do you have a callback after socket close in https://github.com/christianh17/ioBroker.bydhvs/blob/master/main.js#L178 ? Then best use this to call unload callback
* please add roles for all objects https://github.com/christianh17/ioBroker.bydhvs/blob/master/main.js#L199
* this timout in https://github.com/christianh17/ioBroker.bydhvs/blob/19b8a7d75c852fbdc9279b3d5d64124d8e8a9f75/main.js#L611 is not enable in unload (rare case but could be)
* Please also subscribe to the error event of the IPClient, else adapter might crash in error cases
* What happens on disconnect? I do not see any reconnecton mechanism?
Thank you for checking and fixing the issues

**Comment by christianh17** [comment]
Hi!
Thanks for the review. I tried to resolve all points:

_Do you have a callback after socket close in https://github.com/christianh17/ioBroker.bydhvs/blob/master/main.js#L178 ? Then best use this to call unload callback_
My idea was different: I open the connection to read the data and immediately close it afterwards. So I close the socket at the unload event. Reason: The BYD battery allows only one connection at a time.

_please add roles for all objects https://github.com/christianh17/ioBroker.bydhvs/blob/master/main.js#L199_
fixed
_this timout in https://github.com/christianh17/ioBroker.bydhvs/blob/19b8a7d75c852fbdc9279b3d5d64124d8e8a9f75/main.js#L611 is not enable in unload (rare case but could be)_
fixed
_Please also subscribe to the error event of the IPClient, else adapter might crash in error cases_
fixed
_What happens on disconnect? I do not see any reconnecton mechanism?_
As mentiononed above. If the connections drops - the socket is closed and there will be the next try for the next pull.

For now,  i did a new prepatch-version, I am now at 1.2.2-0 . I did not change the PR, at first I would like to get an O0 for the adapter from you, afterwards I will change the PR.

Kind regards
Christian

**Comment by christianh17** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by christianh17** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
Latest shouldn’t have a version attribute.

**Comment by christianh17** [comment]
@foxriver76: Sorry, I do not understand what to do. All other adapters do have a version like:
{
          "admin": {
            "meta": "https://raw.githubusercontent.com/ioBroker/ioBroker.admin/master/io-package.json",
            "icon": "https://raw.githubusercontent.com/ioBroker/ioBroker.admin/master/admin/admin.png",
            "type": "general",
            "version": "4.2.1"
          },
Shall I really delete the line with the version-number in my PR?

**Comment by foxriver76** [comment]
For sources-dist-stable this is correct, because the version is hard defined by the developer. For sources-dist (Beta) the latest npm version is automatically taken.

**Pull request closed without merging**
