### PR TITLE
Airzone Adapter

### PR DESCRIPTION
**Pull request by SilentPhoenix11**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.airzone](https://github.com/SilentPhoenix11/ioBroker.airzone)
[Downloads](https://www.npmjs.com/package/iobroker.airzone) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.airzone/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/SilentPhoenix11/ioBroker.airzone) are broken. Please fix.
- [ ] :eyes: [W400] Cannot find "airzone" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by SilentPhoenix11** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.airzone](https://github.com/SilentPhoenix11/ioBroker.airzone)
[Downloads](https://www.npmjs.com/package/iobroker.airzone) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.airzone/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/SilentPhoenix11/ioBroker.airzone) are broken. Please fix.
- [ ] :eyes: [W400] Cannot find "airzone" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by SilentPhoenix11** [comment]
https://travis-ci.com/github/SilentPhoenix11/ioBroker.airzone => "build.passed"

**Comment by Apollon77** [comment]
All good ... false positive :-)

**Comment by Apollon77** [comment]
Hi,

some review comments:
* Please update the basic details in io-package with all languages (you can use the iobroker translate tool - see readme of this repo for link)
* you use supportCustoms in io-package but no custom FIle. Please remove that
* you use adminTab in io-package but no tab file is provided, please remove that
* you need to add all fileds that you allow in confog also to "native" in io-package with their default values.
* please encrypt password! (you can use the auto encrypt feature, just define the fields in encryptedNative array in io-package and protectedNative and all is handled for you
* Please add translations in words.js
* personal note on intervals: They are pot. problematic when doing external communication. if there are timeouts it can happen that requests pile up and then many happen at the same time. The interval fires every x seconds ... irrelevant of the run from before was finished ... better is to use a timeout and set next after one is finished
*  you should remember if unload was called and make sure that no code is executed after it (scenario: you do the web requests and before finished unload is called ... your code would be still executed after it but DB is already gone
* you do not set any role on the created objects https://github.com/SilentPhoenix11/ioBroker.airzone/blob/master/main.js#L98 Please add correct roles, see schema definition

Thank you for checking and adjusting this.

**Comment by SilentPhoenix11** [comment]
Hi,
thank you for the detailed feedback. I think I have implemented all of the points mentioned.

**Comment by SilentPhoenix11** [comment]
Hi,
have you had time to look at the corrections on my adapter?

**Comment by Apollon77** [comment]
Welcome in the repo and sorry for the longer delay

**Pull request merged**
