### PR TITLE
Update iogo stable to 0.5.10

### PR DESCRIPTION
**Pull request by nisiode**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.iogo](https://github.com/nisiode/ioBroker.iogo)
[Downloads](https://www.npmjs.com/package/iobroker.iogo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iogo/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.5.10
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/nisiode/ioBroker.iogo", press the first "Edit" button you will find on the page and add the description.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
the news are missing :-( the other error is false positive

**Comment by nisiode** [comment]
news are not missing, but linked to the wrong version :-(

**Comment by nisiode** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.iogo](https://github.com/nisiode/ioBroker.iogo)
[Downloads](https://www.npmjs.com/package/iobroker.iogo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iogo/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/nisiode/ioBroker.iogo", press the first "Edit" button you will find on the page and add the description.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Formally we would need a 0.5.11 .-.. but ok that time :-)

**Pull request merged**
