### PR TITLE
Update cloudflare to 1.2.1

### PR DESCRIPTION
**Pull request by Marco15453**
Please update my adapter ioBroker.cloudflare to version 1.2.1.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
This PR has been created when the specified release was not even available at LATEST repository.

This PR will be kept on hold until the release is at least 14 days old, has more than 5% users and no new issues are created. Feel free to request an earlier release to stable - but not before the release is at least 7 days old.

If this is an emergenc version please drop a note to release it immidiatly.

reminder 27.08.2024

**Comment by Marco15453** [comment]
RE-CHECK!

**Comment by Marco15453** [comment]
Updated to v1.2.1 to fix the Vulnerability Issue detected by Dependabot

**Comment by Marco15453** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
This PR has been created when the specified release (1.2.1) was not even available at LATEST repository.

Please create a new PR after the

**Comment by Marco15453** [comment]
RE-CHECK!

**Comment by Marco15453** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Pull request merged**
