### PR TITLE
Add Traccar

### PR DESCRIPTION
**Pull request by o0shojo0o**

### CODE REVIEW

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.traccar](https://github.com/o0shojo0o/ioBroker.traccar)
[Downloads](https://www.npmjs.com/package/iobroker.traccar) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.traccar/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.traccar)!. Please execute in adapter directory: `npm owner add bluefox iobroker.traccar`
- [ ] :eyes: [W400] Cannot find "traccar" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
> * ❗ [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.traccar)!. Please execute in adapter directory: `npm owner add bluefox`

False positive!
image

**Comment by Apollon77** [comment]
Hello,

here is my review Feedback:
* when using adapter-core 2.4.0 the controller dependency in https://github.com/o0shojo0o/ioBroker.traccar/blob/master/io-package.json#L96 needs to be >=2.0.0 ... BUT when you want to use the new encryptedNative feature to let iobroker do anything the controller dep needs to be >= 3.0.0 - and you need to add a "globalDependency" with admin >= 4.0.9
* please also assign a variable to this timeout https://github.com/o0shojo0o/ioBroker.traccar/blob/master/main.js#L180-L182 and clear it on unload
* you declared https://github.com/o0shojo0o/ioBroker.traccar/blob/master/main.js#L317 as async but all usages (also for reateObjectAndState) do not await it ... please change that
* best move https://github.com/o0shojo0o/ioBroker.traccar/blob/master/main.js#L80 to after the clearTimeouts ... if DB is already gone that the timeouts gets killed in any case

Thank you for checking my comments and adjusting accordingly. Please poke here agen when I can take another look

**Comment by o0shojo0o** [comment]
Thanks for once again a great adapter review, I have implemented or correlated all points.

**Pull request merged**
