### PR TITLE
Update sureflap to 2.2.0

### PR DESCRIPTION
**Pull request by Sickboy78**
Please update my adapter ioBroker.sureflap to version 2.2.0.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
@Sickboy78 
Please fix
[E204] Version "2.2.1" listed at common.news at [io-package.json](https://github.com/Sickboy78/ioBroker.sureflap/blob/master/io-package.json) does not exist at [NPM](https://www.npmjs.com/package/iobroker.sureflap). Please remove from news section.

A new Release is NOT required.

Backupgound for this check is that users will be offered to install this release at instalation dropdown. But this will fail unexpectedly for them as npm package cannot be found.

**Comment by Sickboy78** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
2.2.0 created 26.07.2024 -> OK

**Pull request merged**
