### PR TITLE
iwg-vpn new stable version

### PR DESCRIPTION
**Pull request by iwg-vpn**

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Version: stable=1.0.0 (141 days old) => latest=1.0.1 (15 days old)
Installs: stable=171 (81.43%), latest=7 (3.33%), total=210

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.iwg-vpn](https://github.com/iwg-vpn/ioBroker.iwg-vpn)
[Downloads](https://www.npmjs.com/package/iobroker.iwg-vpn) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iwg-vpn/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.iwg-vpn)!. Please execute in adapter directory: `npm owner add bluefox iobroker.iwg-vpn`
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/en/translations.json" or "admin/i18n/en.json" not found, but admin support is declared
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/de/translations.json" or "admin/i18n/de.json" not found, but admin support is declared
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/ru/translations.json" or "admin/i18n/ru.json" not found, but admin support is declared
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/pt/translations.json" or "admin/i18n/pt.json" not found, but admin support is declared
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/nl/translations.json" or "admin/i18n/nl.json" not found, but admin support is declared
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/fr/translations.json" or "admin/i18n/fr.json" not found, but admin support is declared
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/it/translations.json" or "admin/i18n/it.json" not found, but admin support is declared
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/es/translations.json" or "admin/i18n/es.json" not found, but admin support is declared
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/pl/translations.json" or "admin/i18n/pl.json" not found, but admin support is declared
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/uk/translations.json" or "admin/i18n/uk.json" not found, but admin support is declared
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/zh-cn/translations.json" or "admin/i18n/zh-cn.json" not found, but admin support is declared
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iwg-vpn/ioBroker.iwg-vpn/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W172] "common.localLink" in [io-package.json](https://github.com/iwg-vpn/ioBroker.iwg-vpn/blob/master/io-package.json) is deprecated. Please define object "common.localLinks": { "_default": "..." }
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
Please fix errors reportted by adapter checker, especially npm access for Bluefox seems to be missing but is a requirment for the adapter to be listed at ioBroker repositories:

```
C:>npm owner ls iobroker.iwg-vpn
iwg-vpn <iwg.vpn@gmail.com>

C:>```

**Comment by mcm1957** [comment]
closes https://github.com/iwg-vpn/ioBroker.iwg-vpn/issues/2

**Comment by mcm1957** [comment]
@iwg-vpn:
**Please fix npm access for Bluefox** (see adapter checker output error E201).
This is a requirment for the adapter to be listed at ioBroker repositories. Release will not be updated without this fix.

**Comment by mcm1957** [comment]
@iwg-vpn 
Do you need any help?

**Review by mcm1957 — CHANGES_REQUESTED** [review]
Please add bluefox as owner to npm package.

**Comment by mcm1957** [comment]
How should we continue?
Do you need any help?

**This PR might be closed if neither the problem will be solved nor any feedback is received.**

**Comment by iwg-vpn** [comment]
> npm owner add bluefox iobroker.iwg-vpn
> npm notice INFO: User bluefox invited to package iobroker.iwg-vpn successfully.
+ bluefox (iobroker.iwg-vpn)

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.iwg-vpn](https://github.com/iwg-vpn/ioBroker.iwg-vpn)
[Downloads](https://www.npmjs.com/package/iobroker.iwg-vpn) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iwg-vpn/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iwg-vpn/ioBroker.iwg-vpn/blob/master/io-package.json)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/iwg-vpn/ioBroker.iwg-vpn/blob/master/package.json) (1.0.2) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.iwg-vpn) (1.0.1)


*Add comment "RE-CHECK!" to start check anew*

**Review by mcm1957 — COMMENTED** [review]
everything ok

**Pull request merged**
