### PR TITLE
virtualpowermeter add

### PR DESCRIPTION
**Pull request by Omega236**
mein erster Adapter

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Not found on travis. Please setup travis

**Comment by GermanBluefox** [comment]
Stable? Does anyone tested this adapter?

**Comment by Omega236** [comment]
Hello,
yes stable,
https://forum.iobroker.net/topic/20247/adapter-virtualpowermeter/16
tested by Wildbill and ilovegym

**Comment by GermanBluefox** [comment]
Ok. But travis must be activated

**Comment by Omega236** [comment]
travis passed.
Aber jetzt habe ich Version 0.2.8 eingespielt. wie ändere ich nun am sinnvollsten die sources-dist-stable.json auf diese Version?

**Comment by Apollon77** [comment]
genau so :-))

**Comment by Omega236** [comment]
Update to Final Release 1.0.0 for Stable

**Comment by Apollon77** [comment]
Looks ok!
On npm the 1.0.0 is current ... do you still want to have 0.2.8 in stable?

**Comment by Apollon77** [comment]
Welcome :-)

**Pull request merged**
