### PR TITLE
Add reolink to latest

### PR DESCRIPTION
**Pull request by oelison**
Please add my adapter ioBroker.reolink to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by oelison** [comment]
Title is missleading, but simply add reolink to ioBroker adapters. I have just autogenerated from ioBroker Developer Portal.

**Comment by mcm1957** [comment]
Don't know whats misleading. PR adds reolink to sources-dist.jsosn which definied which adapters are available at latest.
So everything seem OK.

**Comment by oelison** [comment]
Ah yes, not stable, just latest...

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] Readme.md should contain a link to the manufacturer and/or device

  The README.md of any adapter related to device or m ultiple devices of a manufacturer should contain a link the manufacturers website and/or to a description of the device. This is to anable new users to easily check wether they associate the adapter with the correct device(s). (See https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository paragraph 4.)

- [ ] package.json should contain keywords

  Please add some matching keywords to package.json.
  'template' seems to be unchanged from creaton, realonk etc. would be useful.

- [ ] package.json should specifiy required nodejs version

  Please consioder adding en engines clause to package.json. Especially if you use adapter-core 3.x.x or newer nodegs 16 or newer must be reuested:
  ```
    "engines": {
    "node": ">= 16"
  },
  ```
  
- [ ] please verify that all dependencies are up to date

  Some dependencies are outdated. Please update to current releases if no special reason to keep an older version exists.
  adapter-core 2.6.0 and axios 0.26.2 are outdated for sure. Same for i.e. adapter-dev, ioborker/testing etc.

- [ ] sensitive information, especially passwords should be stored encrypted
  
  You configuration seems to contain passwords (or other sensitive information) which is not stored encrypted. As long as those information is not stored inside a table you can encrypt and secure this infomation simply by adding the following configuration to io-package.json. The iob runtime will encrypt / decrypt the data as required; no addition programming effort is required. Note that users will need to reenter this info one time after adding encryption, so drop a note at release notes.
  ```
  "encryptedNative": [
    "password",
    "data2"
  ],
  "protectedNative": [
    "password",
    "data2"
  ],
  ```

- [ ] review translations for ids

  Please review translations encoded into io-package.json. I do not think that any camera will provide a 'gesichtsstütze' :-)
  As an alternative solution you could implement name attribute translation within code using i18n and weblate.
 
- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whenever a dedicated role exists.

  Special remarks:
  - write:true must be set only, if state is to be written by external sources (user scripts, other adapters, ...) Those states must not have a role value.* but most likely level.*
  - all states with write:true must be handled at onStateChange
  - states *.support sound like an indocator, so check if write:true is needed there. Harddiscsizte does not make much sense to write too - or else?
  - please check state types, some type sound like a boolean indoicator (i.e. sensor.dog_cat.support). Sound like info if this feature is supported but not as a number of cats supported. If the state is logically a boolean, it should be declared and handled as such - and eventually processed / converted in code accordingly.
  - role:motion does not exist. Maybe sensor.motion is what you look for.
  
  Please reevaluate all roles used.
 
- [ ] check and limit configurable timeouts / intervals
  
  Node setTimeout/setInterval routines have a maximum allowed value of 2,147,483,647 ms. Using delays larger than 2,147,483,647 ms (about 24.8 days) result in the timeout being executed immediately. So all (user configurable) values passed to setTimeout / setInterval should be checked in code and limited. Checking/limiting in code is required as config data could be changed directly or by some other adapter too, so limiting at ui level might not be sufficient.
  
- [ ] adapt testing to supported node releases

  Tests for node 16 is mandatory unless you require node 18 and higher (at package.json).
  Tests for node 18 is mandatory as this is the recommended node version and node 16 will be eol and deprected Q3/2023.
  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x] or [18.x, 20.x] depending on engines requirments setting at package.json 

  As node 16 is end-of-life now, it's ok to remove node 16 from testing. In this case please require node 18 as minimum node version at pacakge.json.

- [ ] github dependabot support seems to be missing
  
  It looks like you did not yet setup dependabot support; at least .github/dependaboit.yml is missing.
  
  Please consider setting up dependabot support (and to ease life the workflow auto-merge.yml). Dependabot will ensure that your adapter uses the most recent versions of external packages and avoids problem due to outdted base libraries. Dependabit provides PRs at you repository to update the dependencies. Depending on you setting, especially on auto-merge.yml configuration no or only minor revisions will be outmatically merged into you main branch. All major revisions msiut (ans should) be reviewed by you. 
  
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by oelison** [comment]
Thank you for the good review. All is easily solvable. I will came back when it is done.

**Comment by mcm1957** [comment]
@oelison 
Still work-in-progress from your side or ready for re-review?

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by oelison** [comment]
Re-review could be done. With [PR 36](https://github.com/aendue/ioBroker.reolink/pull/36) all points from this ticket are solved.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Some more feedback:

- [ ] incorrect role
  https://github.com/aendue/ioBroker.reolink/blob/42863bb6bd74194319503b855f95198849577cf9/main.js#L92C38-L92C55
  Role value must have write:false. Most likely this state is a switch or a button (would require red:false then)

- [ ] roles seems to be improveable:
  switchLed seesm to be a switch
  ledBrightness seems to be a level
  several values states seem to be indicator (due to boolen value)

Improving roles could help vis adapters to use better disply widgest. 

**Please fix at least to one definitly incorrect role with the next release.** I will no longer delay addition to latest anyway.

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, ist OK to continue using this topic too.

**PLEASE consider fixing the notes I left here:**
https://github.com/ioBroker/ioBroker.repositories/pull/2866#issuecomment-1837124546

**Comment by oelison** [comment]
@mcm1957 The forum thread allready exist here: [neuer-adapter-reolink-kamera](https://forum.iobroker.net/topic/56116/neuer-adapter-reolink-kamera)

**Pull request merged**
