### PR TITLE
add pvoutputorg to latest

### PR DESCRIPTION
**Pull request by rg-engineering**
please add the new pvoutputorg to latest.

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.ebus](https://github.com/rg-engineering/ioBroker.ebus)
[Downloads](https://www.npmjs.com/package/iobroker.ebus) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.ebus/)

- [ ] :heavy_exclamation_mark: [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html 
- [ ] :heavy_exclamation_mark: [E504] found setInterval in "main.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore

### [ioBroker.sbfspot](https://github.com/rg-engineering/ioBroker.sbfspot)
[Downloads](https://www.npmjs.com/package/iobroker.sbfspot) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sbfspot/)

- [ ] :heavy_exclamation_mark: [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html 

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

:thumbsup: No errors found

### [ioBroker.backitup](https://github.com/simatec/ioBroker.backitup)
[Downloads](https://www.npmjs.com/package/iobroker.backitup) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.backitup/)

- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E814] file appveyor.yml found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore

### [ioBroker.hm-rpc](https://github.com/ioBroker/ioBroker.hm-rpc)
[Downloads](https://www.npmjs.com/package/iobroker.hm-rpc) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hm-rpc/)

:thumbsup: No errors found

### [ioBroker.vis-icontwo](https://github.com/inventwo/ioBroker.vis-icontwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-icontwo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-icontwo/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/inventwo/ioBroker.vis-icontwo) are broken. Please fix.

### [ioBroker.time-switch](https://github.com/walli545/ioBroker.time-switch)
[Downloads](https://www.npmjs.com/package/iobroker.time-switch) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.time-switch/)

- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E813] file src/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E817] file tsconfig.build.json found in repository, but not found in .npmignore

### [ioBroker.daswetter](https://github.com/rg-engineering/ioBroker.daswetter)
[Downloads](https://www.npmjs.com/package/iobroker.daswetter) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.daswetter/)

:thumbsup: No errors found

### [ioBroker.vis-weather](https://github.com/rg-engineering/ioBroker.vis-weather)
[Downloads](https://www.npmjs.com/package/iobroker.vis-weather) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-weather/)

:thumbsup: No errors found

### [ioBroker.alarm](https://github.com/misanorot/ioBroker.alarm)
[Downloads](https://www.npmjs.com/package/iobroker.alarm) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.alarm/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.proxmox](https://github.com/iobroker-community-adapters/ioBroker.proxmox)
[Downloads](https://www.npmjs.com/package/iobroker.proxmox) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.proxmox/)

:thumbsup: No errors found

### [ioBroker.viessmann](https://github.com/misanorot/ioBroker.viessmann)
[Downloads](https://www.npmjs.com/package/iobroker.viessmann) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.viessmann/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.pvoutputorg](https://github.com/rg-engineering/ioBroker.pvoutputorg)
[Downloads](https://www.npmjs.com/package/iobroker.pvoutputorg) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.pvoutputorg/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.pvoutputorg)!. Please execute in adapter directory: `npm owner add bluefox iobroker.pvoutputorg`
- [ ] :eyes: [W400] Cannot find "pvoutputorg" in latest repository

### [ioBroker.benchmark](https://github.com/foxriver76/ioBroker.benchmark)
[Downloads](https://www.npmjs.com/package/iobroker.benchmark) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.benchmark/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:foxriver76/ioBroker.benchmark.git. Expected: git+https://github.com/foxriver76/ioBroker.benchmark.git
- [ ] :heavy_exclamation_mark: [E152] common.dataSource type has an invalid type none
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "build/main.js", but no clearTimeout detected

### [ioBroker.ford](https://github.com/TA2k/ioBroker.ford)
[Downloads](https://www.npmjs.com/package/iobroker.ford) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ford/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 TA2k <tombox2020@gmail.com>" at the end of [README.md](https://github.com/TA2k/ioBroker.ford/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 TA2k <tombox2020@gmail.com>" at the start of LICENSE
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.homekit-controller](https://github.com/Apollon77/ioBroker.homekit-controller)
[Downloads](https://www.npmjs.com/package/iobroker.homekit-controller) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.homekit-controller/)

- [ ] :heavy_exclamation_mark: [E142] logo is too big. It mast be less or equal than 512x512
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.homekit-controller)!. Please execute in adapter directory: `npm owner add bluefox iobroker.homekit-controller`
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/Apollon77/ioBroker.homekit-controller", press the settings button beside the about title and add some topics.
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E813] file src/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E817] file tsconfig.build.json found in repository, but not found in .npmignore

### [ioBroker.opcua](https://github.com/ioBroker/ioBroker.opcua)
[Downloads](https://www.npmjs.com/package/iobroker.opcua) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.opcua/)

- [ ] :heavy_exclamation_mark: [E016] No SPDX license found in [package.json](https://github.com/ioBroker/ioBroker.opcua/blob/master/package.json). Please use one of listed here: https://spdx.org/licenses/
- [ ] :heavy_exclamation_mark: [E104] No common.titleLang found in [io-package.json](https://github.com/ioBroker/ioBroker.opcua/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin3 support
- [ ] :heavy_exclamation_mark: [E116] No SPDX license found. Please use one of listed here: https://spdx.org/licenses/
- [ ] :heavy_exclamation_mark: [E154] common.dependencies must contain{"js-controller": ">=2.0.0"} or {"js-controller": ">=3.0.0"}
- [ ] :heavy_exclamation_mark: [E124] Main file not found under URL: https://raw.githubusercontent.com/ioBroker/ioBroker.opcua/master/main.js
- [ ] :heavy_exclamation_mark: [E504] "main.js found in [package.json](https://github.com/ioBroker/ioBroker.opcua/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)

### [ioBroker.ph803w](https://github.com/Apollon77/ioBroker.ph803w)
[Downloads](https://www.npmjs.com/package/iobroker.ph803w) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ph803w/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.ph803w)!. Please execute in adapter directory: `npm owner add bluefox iobroker.ph803w`
- [ ] :heavy_exclamation_mark: [E504] found setInterval in "main.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore

### [ioBroker.iogopro](https://github.com/nisiode/ioBroker.iogopro)
[Downloads](https://www.npmjs.com/package/iobroker.iogopro) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iogopro/)

:thumbsup: No errors found

### [io-package.json](https://github.com/controller/io-package.json)
[Downloads](https://www.npmjs.com/package/io-package.json) 
[NPM](https://nodei.co/npm/io-package.json/)

- [ ] :heavy_exclamation_mark: 404: Invalid URL

### [ioBroker.scheduler](https://github.com/ioBroker/ioBroker.scheduler)
[Downloads](https://www.npmjs.com/package/iobroker.scheduler) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.scheduler/)

:thumbsup: No errors found

### [ioBroker.tesla-motors](https://github.com/iobroker-community-adapters/ioBroker.tesla-motors)
[Downloads](https://www.npmjs.com/package/iobroker.tesla-motors) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.tesla-motors/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 TA2k <tombox2020@gmail.com>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.tesla-motors/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 TA2k <tombox2020@gmail.com>" at the start of LICENSE

### [ioBroker.xterm](https://github.com/ioBroker/ioBroker.xterm)
[Downloads](https://www.npmjs.com/package/iobroker.xterm) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.xterm/)

- [ ] :heavy_exclamation_mark: [E152] common.dataSource type has an invalid type none
- [ ] :heavy_exclamation_mark: [E504] "main.js found in [package.json](https://github.com/ioBroker/ioBroker.xterm/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/ioBroker/ioBroker.xterm", press the settings button beside the about title and add some topics.

### [ioBroker.openknx](https://github.com/iobroker-community-adapters/ioBroker.openknx)
[Downloads](https://www.npmjs.com/package/iobroker.openknx) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.openknx/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/boellner/ioBroker.openknx. Expected: git+https://github.com/iobroker-community-adapters/ioBroker.openknx.git


*Add comment "RE-CHECK!" to start check anew*

**Comment by rg-engineering** [comment]
> [ioBroker.pvoutputorg](https://github.com/rg-engineering/ioBroker.pvoutputorg)
> 
> ❗ [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.pvoutputorg)!. Please execute in adapter directory: npm owner add bluefox iobroker.pvoutputorg
> 👀 [W400] Cannot find "pvoutputorg" in latest repository


Hi @GermanBluefox , @Apollon77 

is label "must be fixed" related to "Bluefox was not found in the collaborators"? if so then I must say that I executed "npm owner add bluefox iobroker.pvoutputorg" and bluefox was invited to my repo. I guess bluefox must accept that invitation on npmjs.com...

**Comment by rg-engineering** [comment]
@Apollon77 I thing I solved all mentioned issues above, so please recheck. thanks.

**Comment by Apollon77** [comment]
Hi @rg-engineering,

I checked again:
* I really do not like the cron approach to query data from an external webpage. Out of experience with several other adapters this will get problems as soon as the adapter uis used by a bigge rnumber of users! Because then ALL these users will do the requests at the exact same second producing big request spikes and then we have issues with the webpage/service provider. Thats why using timeouts instead of crons as said will automatically spread this load obver each second and minute and so equalize it. If you can/want not to change it please at least add a random delay or a "random second" for each adapter start, so that at least the calls get spread over the full minute ... but this is still faaaar from ideal!! Please really consider moving to setInterval if this works for the usecase
* There is not SIGNINT handler on adater class. You can remove https://github.com/rg-engineering/ioBroker.pvoutputorg/blob/main/main.js#L48
* why you do this? https://github.com/rg-engineering/ioBroker.pvoutputorg/blob/main/main.js#L206-L207.... should be irrelevant or? My comment for the use of the FORBIDDEN_CHARACTERS check was more for system.Name!!
* also state CHange handler is still in and doping nothing.

Please check again, thank you

**Comment by rg-engineering** [comment]
Hi @Apollon77 ,
I revised the whole thing again with version 1.7.0:

* I switched the whole thing back to interval. The exception is the EndOfDay upload: I continue to use cron there. I have to upload time-controlled once a day. However, the time is now determined dynamically for each installation: 1 hour after local sunset. That should spread the upload times far enough. In general, PVOutput.org has no problems with many simultaneous requests. They even recommend 5, 10 or 15 minutes per cron...
* SIGNINT handler is removed
* FORBIDDEN_CHARS are only used for the system name
* HandleStateChange is commented out but not removed because I need it later

I hope there is nothing preventing the adapter from being included in the latest...

**Comment by Apollon77** [comment]
Meeehhh ... stop ... your repo uses branch main .. the io-package and also this Repo PR reprerences "master". Please correct that in all places and then we are ready

**Comment by rg-engineering** [comment]
@Apollon77 oops, this I've overseen when I forked the repo. I would like to stay with "master" instead of "main". I've created and pushed master branch in my repo now. At this moment master and main have the same content... I will change the default branch of repo to master later
the repo PR is correct because I use master branch here already...

**Comment by rg-engineering** [comment]
@Apollon77 can you please verify again? many thanks.

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.meross](https://github.com/Apollon77/ioBroker.meross)
[Downloads](https://www.npmjs.com/package/iobroker.meross) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.meross/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Apollon77/ioBroker.meross/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)

### [ioBroker.pvoutputorg](https://github.com/rg-engineering/ioBroker.pvoutputorg)
[Downloads](https://www.npmjs.com/package/iobroker.pvoutputorg) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.pvoutputorg/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.pvoutputorg)!. Please execute in adapter directory: `npm owner add bluefox iobroker.pvoutputorg`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/rg-engineering/ioBroker.pvoutputorg/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W400] Cannot find "pvoutputorg" in latest repository
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.daswetter](https://github.com/rg-engineering/ioBroker.daswetter)
[Downloads](https://www.npmjs.com/package/iobroker.daswetter) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.daswetter/)

- [ ] :heavy_exclamation_mark: [E154] common.dependencies must contain {"js-controller": ">=2.0.0"} or later - recommended: {"js-controller": ">=3.3.22"}
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/rg-engineering/ioBroker.daswetter/blob/master/io-package.json)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/rg-engineering/ioBroker.daswetter/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/rg-engineering/ioBroker.heatingcontrol/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.sbfspot](https://github.com/rg-engineering/ioBroker.sbfspot)
[Downloads](https://www.npmjs.com/package/iobroker.sbfspot) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sbfspot/)

- [ ] :heavy_exclamation_mark: [E154] common.dependencies must contain {"js-controller": ">=2.0.0"} or later - recommended: {"js-controller": ">=3.3.22"}
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/rg-engineering/ioBroker.sbfspot/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.daikin-cloud](https://github.com/Apollon77/ioBroker.daikin-cloud)
[Downloads](https://www.npmjs.com/package/iobroker.daikin-cloud) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.daikin-cloud/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.daikin-cloud)!. Please execute in adapter directory: `npm owner add bluefox iobroker.daikin-cloud`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Apollon77/ioBroker.daikin-cloud/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)

### [ioBroker.nuki-extended](https://github.com/iobroker-community-adapters/ioBroker.nuki-extended)
[Downloads](https://www.npmjs.com/package/iobroker.nuki-extended) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.nuki-extended/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git+https://github.com/Zefau/ioBroker.nuki-extended.git. Expected: git@github.com:iobroker-community-adapters/ioBroker.nuki-extended.git or https://github.com/iobroker-community-adapters/ioBroker.nuki-extended.git
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.nuki-extended/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W172] "common.localLink" in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.nuki-extended/blob/master/io-package.json) is deprecated. Please define object "common.localLinks": { "_default": "..." }


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Welcome in the repo ... sorry that the review too that long.

**Pull request merged**
