### PR TITLE
Added onkyo2

### PR DESCRIPTION
**Pull request by instalator**

### CODE REVIEW

**Comment by SVallant** [comment]
What is the difference to iobroker.onkyo https://github.com/ioBroker/ioBroker.onkyo ??

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.onkyo2](https://github.com/instalator/ioBroker.onkyo2)
[Downloads](https://www.npmjs.com/package/iobroker.onkyo2) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.onkyo2/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "onkyo2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by instalator** [comment]
> What is the difference to iobroker.onkyo

In order that the driver was perverted to the inability to use it

**Comment by GermanBluefox** [comment]
Closed, after agreement from Instalator

**Pull request closed without merging**
