### PR TITLE
add epson_ecotank_et_2750

### PR DESCRIPTION
**Pull request by o0shojo0o**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)

### [ioBroker.epson_ecotank_et_2750](https://github.com/o0shojo0o/ioBroker.epson_ecotank_et_2750)
[Downloads](https://www.npmjs.com/package/iobroker.epson_ecotank_et_2750) 
[NPM](https://nodei.co/npm/iobroker.epson_ecotank_et_2750/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "epson_ecotank_et_2750" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
I assume that i can ignore the erros from the ioBroker.devices ;)

**Comment by o0shojo0o** [comment]
https://forum.iobroker.net/topic/40984/test-adapter-epson-ecotank-et-2750-v0-0-x

**Comment by Apollon77** [comment]
> I assume that i can ignore the erros from the ioBroker.devices? ;)

yes

**Comment by o0shojo0o** [comment]
Another one tested it and there were no problems. 
Is that enough?

**Pull request closed without merging**
