### PR TITLE
first stable version of heatingcontrol 0.3.17

### PR DESCRIPTION
**Pull request by rg-engineering**
please add first stable version of heatingcontrol 0.3.17

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

- [ ] :heavy_exclamation_mark: [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html 
- [ ] :eyes: [W505] setTimeout found in "main.js, but no clearTimeout detected

**Comment by rg-engineering** [comment]
fixed mit 0.3.18

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
