### PR TITLE
added ocpp stable

### PR DESCRIPTION
**Pull request by foxriver76**
v1 coming soon, but now with < 1 ;-)

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.ocpp](https://github.com/foxriver76/ioBroker.ocpp)
[Downloads](https://www.npmjs.com/package/iobroker.ocpp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ocpp/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:foxriver76/ioBroker.ocpp.git. Expected: git+https://github.com/foxriver76/ioBroker.ocpp.git
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.ocpp)!. Please execute in adapter directory: `npm owner add bluefox iobroker.ocpp`


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.ocpp](https://github.com/foxriver76/ioBroker.ocpp)
[Downloads](https://www.npmjs.com/package/iobroker.ocpp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ocpp/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:foxriver76/ioBroker.ocpp.git. Expected: git+https://github.com/foxriver76/ioBroker.ocpp.git
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.ocpp)!. Please execute in adapter directory: `npm owner add bluefox iobroker.ocpp`


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.ocpp](https://github.com/foxriver76/ioBroker.ocpp)
[Downloads](https://www.npmjs.com/package/iobroker.ocpp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ocpp/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:foxriver76/ioBroker.ocpp.git. Expected: git+https://github.com/foxriver76/ioBroker.ocpp.git
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.ocpp)!. Please execute in adapter directory: `npm owner add bluefox iobroker.ocpp`


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
