### PR TITLE
Bump huum-sauna to 0.4.5

### PR DESCRIPTION
**Pull request by Chris-656**
Think about update stable version to 0.4.5

### CODE REVIEW

**Comment by Chris-656** [comment]
RE-CHECK!

**Comment by Chris-656** [comment]
RE-CHECK!

**Comment by Chris-656** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@Chris-656 

Please add a changelog to README.md. Your current changelog is empty and consists of header only.

See i.e. https://github.com/iobroker-community-adapters/ioBroker.acme#changelog for an example. A chanelog including the release to be published is mandatory.

Note: NO new release is required, simply add the changelog and commit README.md

**Comment by mcm1957** [comment]
0.4.5 created 31.10.2023

**Comment by Chris-656** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
replaced by #2943

**Pull request closed without merging**
