### PR TITLE
Alexa-timer-vis Adapter

### PR DESCRIPTION
**Pull request by MiRo1310**

### CODE REVIEW

**Comment by ldittmar81** [comment]
RE-CHECK

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alexa-timer-vis](https://github.com/MiRo1310/ioBroker.alexa-timer-vis)
[Downloads](https://www.npmjs.com/package/iobroker.alexa-timer-vis) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.alexa-timer-vis/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "alexa-timer-vis" in latest repository

### [ioBroker.zoneminder](https://github.com/iobroker-community-adapters/ioBroker.zoneminder)
[Downloads](https://www.npmjs.com/package/iobroker.zoneminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.zoneminder/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/io-package.json). Must be removed.
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E154] common.dependencies must contain {"js-controller": ">=2.0.0"} or {"js-controller": ">=3.0.0"}
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.zoneminder) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 MeisterTR <meistertr.smarthome@gmail.com>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 MeisterTR <meistertr.smarthome@gmail.com>" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore


*Add comment "RE-CHECK!" to start check anew*

**Comment by ldittmar81** [comment]
Test Link https://forum.iobroker.net/topic/50765/test-adapter-adapter-alexa-timer-vis-v0-1-x-github-latest

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alexa-timer-vis](https://github.com/MiRo1310/ioBroker.alexa-timer-vis)
[Downloads](https://www.npmjs.com/package/iobroker.alexa-timer-vis) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.alexa-timer-vis/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "alexa-timer-vis" in latest repository

### [ioBroker.zoneminder](https://github.com/iobroker-community-adapters/ioBroker.zoneminder)
[Downloads](https://www.npmjs.com/package/iobroker.zoneminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.zoneminder/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/io-package.json). Must be removed.
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E154] common.dependencies must contain {"js-controller": ">=2.0.0"} or {"js-controller": ">=3.0.0"}
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.zoneminder) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 MeisterTR <meistertr.smarthome@gmail.com>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 MeisterTR <meistertr.smarthome@gmail.com>" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore

### [ioBroker.zwave2](https://github.com/AlCalzone/ioBroker.zwave2)
[Downloads](https://www.npmjs.com/package/iobroker.zwave2) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.zwave2/)

:thumbsup: No errors found

### [ioBroker.ems-esp](https://github.com/tp1de/ioBroker.ems-esp)
[Downloads](https://www.npmjs.com/package/iobroker.ems-esp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ems-esp/)

:thumbsup: No errors found

### [ioBroker.eusec](https://github.com/bropat/ioBroker.eusec)
[Downloads](https://www.npmjs.com/package/iobroker.eusec) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.eusec/)

:thumbsup: No errors found

### [ioBroker.shelly](https://github.com/iobroker-community-adapters/ioBroker.shelly)
[Downloads](https://www.npmjs.com/package/iobroker.shelly) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.shelly/)

:thumbsup: No errors found

### [ioBroker.ws](https://github.com/ioBroker/ioBroker.ws)
[Downloads](https://www.npmjs.com/package/iobroker.ws) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ws/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.ws/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.ws/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/ioBroker/ioBroker.ws", press the settings button beside the about title and add some topics.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@MiRo1310 Him, here is some review feedback:
* is the alexa2 dep in https://github.com/MiRo1310/ioBroker.alexa-timer-vis/blob/main/io-package.json#L244 really a "needs to be on this host?"  ... I think this is better as "globalDependency" (because needs to be somewhere in the system, or?
* please translate the desc field https://github.com/MiRo1310/ioBroker.alexa-timer-vis/blob/main/io-package.json#L200-L210
* It seems that there is something not correct ... see test results https://github.com/MiRo1310/ioBroker.alexa-timer-vis/runs/5147589607?check_suite_focus=true#step:2:636 - reason is that you use setObjectNotExistsAsync but do not await the result ... so you set first values before the object god created
* whats that? https://github.com/MiRo1310/ioBroker.alexa-timer-vis/blob/main/main.js#L956 ... unload needs to be finished morally within 500ms! (unkless you set in io-package that more time is required) - in fact there isno "buffer" needed to end timeouts
* Please dfo not mix languages in readme file ... if needed create docs pages in the respective languages and define them in io-package (see e.g. javascript adapter)

**Comment by MiRo1310** [comment]
I hope everything is correctly fixed.

Thanks

**Pull request merged**
