### PR TITLE
Loxone -> 3.0.1

### PR DESCRIPTION
**Pull request by raintonr**

### CODE REVIEW

**Comment by Apollon77** [comment]
Is there any beaking change (becasue major). Makes it sense to informusers somehow?

**Comment by raintonr** [comment]
Nope. No breaking changes. Just bug fixes and small improvements.

**Comment by mcm1957** [comment]
> Is there any beaking change (becasue major). Makes it sense to informusers somehow?

3.0.0 is at stable since 2021. So this is a update change.

Only noticeable favct is, that 3.0.1 is at latest since 30.3. only - what ruther short. Buts thats something raintonr should be able to decide. I do not know wether the change are more a hot fix or bigger changes due to fixes.

image

**Comment by Apollon77** [comment]
@raintonr But when there is no breaking change WHY then a major version update? This is not following semantic versioning rules ... Ok now this is too later but please try to folow semantic version in the future

**Comment by raintonr** [comment]
> ...when there is no breaking change WHY then a major version update?

I know how version numbers work @Apollon77 3.0.0 was the last release, hence the minor bump to 3.0.1.

https://www.npmjs.com/package/iobroker.loxone?activeTab=versions

**Comment by Apollon77** [comment]
Aahhhh then sorry ... I thought you did the jump. sorry ... misunderstanding. all good

**Pull request merged**
