### PR TITLE
Add mywallbox Adapter to latest

### PR DESCRIPTION
**Pull request by SKB-CGN**
Adapter for Cloud based Wallboxes like Pulsar or Pulsar Plus

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi, thank you for your adapter.

Is the adapter for Pulsar Wallboxes only? Then "Wallbox" as name is too generic in my eyes ... or do you pan to add more other such? Could you please rename it to pulsar-wallbox or such?

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by SKB-CGN** [comment]
> Hi, thank you for your adapter.
> 
> Is the adapter for Pulsar Wallboxes only? Then "Wallbox" as name is too generic in my eyes ... or do you pan to add more other such? Could you please rename it to pulsar-wallbox or such?

The Company is named "Wallbox" therefore i choosed this name.

**Comment by Apollon77** [comment]
wow ... puuhh ... a company name which matches a "in the meantime commodoty name of a device type" :-( I will discuss it in core team...
But I hope you also understand my point of view?

**Comment by SKB-CGN** [comment]
Hi,
do we have some news here?

**Comment by Apollon77** [comment]
Yes, we discussed yesterday. WOuld it be an issue torename tzo "my-wallbox" so we match the name of that cloud servcie you connect to?

Additionally please state in the readme exactly that it is for Wallboxes from company "wallbox" or such ... right now also the Readme could be easiely read "works for all wallboxes". The same for io-package title/tileLang and desc fields please.

This is a special case, but we want to avoid user confusion.

Additionally please adjust the links in the repo file to use raw.githubusercontent.com like the others ... github.com is not a CDN service ...

**Comment by SKB-CGN** [comment]
Hi,
would you please check the things again.

I have updated the name to My-Wallbox and changed (hopefully) all necessary dependencies and files.

Thank you!

**Comment by Apollon77** [comment]
I will do the adapter review in the next days ...

**Comment by SKB-CGN** [comment]
Great, but now i have the problem, that the adapter is not working anymore ... i do not know, whats going on.

**Comment by Apollon77** [comment]
Hm ... data on github looks fine ... what error you get?

**Comment by SKB-CGN** [comment]
The adapter is not doing anything. No commands running, no Interval is working. Nothing.

**Comment by Apollon77** [comment]
Code wise looks good ... also github actionsstart tghe adapter ... how you test locally?

**Comment by SKB-CGN** [comment]
i created the adapter with adapter creator and everytime i change the code, i do iobroker upload mywallbox

**Comment by Apollon77** [comment]
but you also reinstalled the adapter after that namechange completely?

**Comment by SKB-CGN** [comment]
Holy bible. I missed an error-handling. Will fix that shortly.

**Comment by SKB-CGN** [comment]
Now its working again. Thanks for waiting.

**Comment by SKB-CGN** [comment]
@Apollon77 Do we have some news here? :)

**Comment by Apollon77** [comment]
Yes, after vacation, wasn't able to do it before

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.my-wallbox](https://github.com/SKB-CGN/ioBroker.my-wallbox)
[Downloads](https://www.npmjs.com/package/iobroker.my-wallbox) 
[NPM](https://nodei.co/npm/iobroker.my-wallbox/)

- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/SKB-CGN/ioBroker.my-wallbox/blob/master/package.json) must be lowercase and be equal to "iobroker.my-wallbox". Now is "iobroker.mywallbox"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:SKB-CGN/ioBroker.my-wallbox.git. Expected: git@github.com:SKB-CGN/ioBroker.mywallbox.git or https://github.com/SKB-CGN/ioBroker.mywallbox.git
- [ ] :heavy_exclamation_mark: [E103] "common.name" in [io-package.json](https://github.com/SKB-CGN/ioBroker.my-wallbox/blob/master/io-package.json) must be equal to "my-wallbox'". Now is mywallbox
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/SKB-CGN/ioBroker.my-wallbox/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W400] Cannot find "my-wallbox" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [blob](https://github.com/ioBroker.wallbox/blob)
[Downloads](https://www.npmjs.com/package/blob) 
[NPM](https://nodei.co/npm/blob/)

:thumbsup: No errors found

### [ioBroker.mywallbox](https://github.com/SKB-CGN/ioBroker.mywallbox)
[Downloads](https://www.npmjs.com/package/iobroker.mywallbox) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.mywallbox/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:SKB-CGN/ioBroker.my-wallbox.git. Expected: git@github.com:SKB-CGN/ioBroker.mywallbox.git or https://github.com/SKB-CGN/ioBroker.mywallbox.git
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/SKB-CGN/ioBroker.mywallbox/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W400] Cannot find "mywallbox" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by SKB-CGN** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mywallbox](https://github.com/SKB-CGN/ioBroker.mywallbox)
[Downloads](https://www.npmjs.com/package/iobroker.mywallbox) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.mywallbox/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/SKB-CGN/ioBroker.mywallbox/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W400] Cannot find "mywallbox" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [blob](https://github.com/ioBroker.wallbox/blob)
[Downloads](https://www.npmjs.com/package/blob) 
[NPM](https://nodei.co/npm/blob/)

:thumbsup: No errors found

### [ioBroker.my-wallbox](https://github.com/SKB-CGN/ioBroker.my-wallbox)
[Downloads](https://www.npmjs.com/package/iobroker.my-wallbox) 
[NPM](https://nodei.co/npm/iobroker.my-wallbox/)

- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/SKB-CGN/ioBroker.my-wallbox/blob/master/package.json) must be lowercase and be equal to "iobroker.my-wallbox". Now is "iobroker.mywallbox"
- [ ] :heavy_exclamation_mark: [E103] "common.name" in [io-package.json](https://github.com/SKB-CGN/ioBroker.my-wallbox/blob/master/io-package.json) must be equal to "my-wallbox'". Now is mywallbox
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/SKB-CGN/ioBroker.my-wallbox/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W400] Cannot find "my-wallbox" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by SKB-CGN** [comment]
Can someone please tell me, how "[ioBroker.my-wallbox](https://github.com/SKB-CGN/ioBroker.my-wallbox)" can be removed here? I needed to change the name and the check always goes through my-wallbox either instead of only using mywallbox.

Thank you!

**Comment by Apollon77** [comment]
All good ... the checker only checks the initial repo file change ... so clean would be new PR ... but in this case "known", so all fine

**Comment by SKB-CGN** [comment]
Ok and all things are good now?

**Comment by Apollon77** [comment]
Hi,
here my review comments:
* please sort in the entry in this PR alphabetically 
* please fix that link https://github.com/SKB-CGN/ioBroker.mywallbox/blob/main/io-package.json#L131 (blob is too much)
* please also add an emoty "password" field in native https://github.com/SKB-CGN/ioBroker.mywallbox/blob/main/io-package.json#L151 as default value
* Please add a "common.globalDependencies with admin >= 4.0.9 to io-package because you use the automatic encryption
* you configured the automatic encryption but still have code in admin to encrypt passwords and to decrypt in main.js ... you you encrypt it twice right now ... Please remove https://github.com/SKB-CGN/ioBroker.mywallbox/blob/main/admin/index_m.html#L63 and the main.js code (would be breaking for all current users)
* Note: Using intervals for external server communication is not ideal (https://github.com/SKB-CGN/ioBroker.mywallbox/blob/d3e6a7543c1eb7ee85660d31b14672761cf4e28a/main.js#L444) ... can be done but could generate issues- seee infos in best practices
* you should set a timeout for the external communication which is always lower then your interval (or not use an interval at all - see above)
* Please check roles - e.g. https://github.com/SKB-CGN/ioBroker.mywallbox/blob/d3e6a7543c1eb7ee85660d31b14672761cf4e28a/main.js#L806 ... an indicator is defined as boolean red-only and not for numbers, see Role definitions in https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md

Thank you for checking and adjusting,

Ingo

**Comment by SKB-CGN** [comment]
Hi,
i am not sure, if i understood/understand the password topic correctly.

Its not needed in index_m.html to have the password function (anymore)? But how does the system know, to crypt the password?
And how is it done in the main.js file, to have the password decrypted again?

Thank you in advance!

**Comment by Apollon77** [comment]
WHen you provide "encryptedNative" in io-package with the fieldname all this is handled automatically. Admin will encrypt the field before daving it and the adapter class will decrypt it before starting the adapter code. So all is handled by "encryptedNative" settings. Additionally protectednative settings makes sure that only Admin and the adapter instances itself are allowed to read the value of the field.

You have set encryptedNative AND have manual functions to encrypt and decrypt ... so your password nis not encrypted twice :-)

**Comment by SKB-CGN** [comment]
Thanks, so the keyword for this is "only" encryptedNative - if you provide the fields in io-package.json, the backend automatically knows, to crypt or decrypt, if i understood your words correctly?!

**Comment by Apollon77** [comment]
exactly ... https://github.com/SKB-CGN/ioBroker.mywallbox/blob/d3e6a7543c1eb7ee85660d31b14672761cf4e28a/io-package.json#L148-L150 ... with this you already had done the job :-) (ok plus the admin dependency)

**Comment by SKB-CGN** [comment]
Much appreciated. This wasnt clear for me - ok, now i also got the point, while the password is encrypted/decrypted twice. Will change it!

**Comment by Apollon77** [comment]
@SKB-CGN Ready for re-review?

**Comment by SKB-CGN** [comment]
Not yet. It will take some more days cause of company traveling 😀

**Comment by Apollon77** [comment]
Ok, just write when ready, and happy travelling :-)

**Comment by Apollon77** [comment]
@SKB-CGN Just tell if you need any help!

**Comment by Apollon77** [comment]
Happy new year, any update?

**Comment by SKB-CGN** [comment]
Hi,
hopefully, i didnt miss something in the list.
Changed some things, removed the password decryption and changed to native.
Added a timer to the request function and sorted the adapter into the json alphabetically.

**Comment by mcm1957** [comment]
look like a re-review could be appropiate

**Comment by SKB-CGN** [comment]
Kind of review, please? Does it really need to take around 1year, to add an adapter to ioBroker?

**Comment by mcm1957** [comment]
Sorry, I can understand your problem. Theres a big backlog currently.

But your adapter was already reviewed once and you noted the fixing start of this year. So it's only 4,5 months - but I accept that this is very long too.

In any case THANKS for your work and your patiance.

Please keep in mind, that all work done here is non-commercial during spare time of volonteers. And currently much resources are locked to the upcoming integration of matter.

**Comment by Apollon77** [comment]
@SKB-CGN I'm very sorry, in some arreas we are a bit löimited in resources as free-time open source project and yes too many topics onnmy plate currently, so I need to see how to split my time between all of them. I'm very sorry and no, this should not be normal.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by SKB-CGN** [comment]
Added Node 18 as default and testing for 16, 18 and 20.

**Comment by SKB-CGN** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.
And sorry for the VERY long delay.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- [ ] errors reported by adapter checker must be fixed
  
  The translations should be completed.
  [W505] setTimeout found in "main.js", but no clearTimeout detected must be fixed
  
- [ ] Readme.md should contain a link to the manufacturer and/or device

  The README.md of any adapter related to device or m ultiple devices of a manufacturer should contain a link the manufacturers website and/or to a description of the device. This is to anable new users to easily check wether they associate the adapter with the correct device(s). (See https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository paragraph 4.)

- [ ] adapter requires node 16 due to adapter-core 3.x.x
  
  Please merge https://github.com/SKB-CGN/ioBroker.mywallbox/pull/69

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read. (see i.e. https://github.com/SKB-CGN/ioBroker.mywallbox/blob/04d181677262da0a963fb2486beec7e53ec0e361/main.js#L942)

  Roles are important for the type detector to work. So avoid general roles (like state or text) whenever a specific role exissts.
  
- [ ] consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- [ ] check and limit configurable timeouts / intervals
  
  Node setTimeout/setInterval routines have a maximum allowed value of 2,147,483,647 ms. Using delays larger than 2,147,483,647 ms (about 24.8 days) result in the timeout being executed immediately. So all (user configurable) values passed to setTimeout / setInterval should be checked and limited.
    
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by SKB-CGN** [comment]
Currently updating this one.
Will be ready soon.

**Comment by mcm1957** [comment]
[SKB-CGN](https://github.com/SKB-CGN)

**Comment by mcm1957** [comment]
> Currently updating this one. Will be ready soon.

Any news?
Do you need help?
reminder 31.12.2023

**Comment by mcm1957** [comment]
@SKB-CGN 

Happy New Year !

How shall we continue?
Do you need any help?

**Please let me/us know if you encounter any problem and which timefram you expect to fix the mentionend issues.**

mcm1957

reminder 15.01.2024

**Comment by SKB-CGN** [comment]
Hi,
i was on a long holiday. Tomorrow I will have a look at it again.

Thanks for your patience!

**Comment by mcm1957** [comment]
No problem at all.
Hope you enyed the holidays and please do not hurry.
I only ask as sometimes devs loose interest and I do not want to keep PRs open for 1 year or more :-) without any communication.

Juts respond if you have any questions, need help or think the adapter is ready for e recheck.

mcm1957

**Comment by mcm1957** [comment]
reminder 31.01.2024

**Comment by mcm1957** [comment]
reminder 15.2.2024

**Comment by SKB-CGN** [comment]
Hi,
i think the Adapter is ready to be added to the repo.

Please let me know!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Sorry to respond late. I must confess that I missed this PR (as it so old and the last one still ative in the backlog)
SORRY.

In addition some more Issues have been detected or are still open

- [ ] dependencies are incomplete
  
   You ear eusing axios, but axios is not include in adapter dependencies; use 'npm i axios' to add axios to the list of dependencies. Do not forget to commit package-loc.json too. This will require a ne release to as package.json is includes into npm packge.

https://github.com/SKB-CGN/ioBroker.mywallbox/blob/4014eef08357f294a66b2ba88840858ae2fecb91/main.js#L12C32-L13C1
https://github.com/SKB-CGN/ioBroker.mywallbox/blob/4014eef08357f294a66b2ba88840858ae2fecb91/package.json#L23


- [ ] consider automatic deploy (suggestion only - NON blocking!)

  I suggest to consider enabling automatic deploy to npm for new releases:
https://github.com/SKB-CGN/ioBroker.mywallbox/blob/4014eef08357f294a66b2ba88840858ae2fecb91/.github/workflows/test-and-release.yml#L58
  But note, that this is only asuggestion and is not blocking !


- [ ] reevaluate state roles - still seems to be open

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read. (see i.e. https://github.com/SKB-CGN/ioBroker.mywallbox/blob/04d181677262da0a963fb2486beec7e53ec0e361/main.js#L942)

  Roles are important for the type detector to work. So avoid general roles (like state or text) whenever a specific role exissts.

  Most states are created with role state while more specific roles exsists for sure, i.e.
  - lastSyncDT is most likely some date timestamp i.e. role 
  - role indicator requires a boolen state (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md#indicators-boolean-read-only)
    so powerSharingStatus euther needs type boolean or anopther role (i.e. value)
  -  software.currentVersion should be info.firmwarversion
  -  maxChgCurrent is for sure a currentvalue, so use i.e. value.current
  - ... please check all rolues and use specific roles whenever tehy exist.


- [ ] several files at ./lib are copied from iobroker.repositories

  Please delete the files not belonging to your adapter


- [ ] possibly unused variables
 
  Looks adapterItervals.controlCharger and changeChargerData are not used except when trying to canel them. Please remove them if I did not miss something


The following remarks by Apollon77 are still not solved too:

- [ ] please sort in the entry in this PR alphabetically


**Please let me/us know if you encounter any problem and which timefram you expect to fix the mentionend issues.**

**Comment by SKB-CGN** [comment]
Hi,
can we shortly pause this topic?
I will be on vacation the next weeks and after that, i will try, to fix all the things.
Please pause till middle of april.

Thank you!

**Comment by mcm1957** [comment]
OK
No problem
Have some nice vacation.

reminder 1.5.2024

**Comment by mcm1957** [comment]
@SKB-CGN 
Hope you are well.

Any news related to this PR? 
How should be proceed?

reminder 15.6.2024

**Comment by SKB-CGN** [comment]
Hey,
doing good, thanks a lot.
Hope you too.

I am at the end phase of releasing another update for the Energiefluss Adapter.

Therefore, this will be queued again.

Let's remind at the end of June.

**Comment by mcm1957** [comment]
reminder 1.7.2024

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
> Hey, doing good, thanks a lot. Hope you too.
> 
> I am at the end phase of releasing another update for the Energiefluss Adapter.
> 
> Therefore, this will be queued again.
> 
> Let's remind at the end of June.

Hi @SKB-CNG

Any news? 

As this PR is now open for a long time, please let me know if there is any realistic deadline (August or September) to finish this adapter. If this is not realistic, I would suggest to close this PR and open a new one whenever you have time to work on the adapter.

Please note that this is NO critism at your person. I want to explicitly say THANK YOU to work on an ioBroker adapter. But I want to keep PR queue simple and avoid PRs which are not processed on.

mcm1957

**Comment by SKB-CGN** [comment]
Hi,
I fully understand. I will refresh that one in the next days, when I am back from vacation.

**Comment by mcm1957** [comment]
Any news?
Please note that I will close this PR after 30.9.2024 unless there is some clear time frame specified for e new review.

**Comment by SKB-CGN** [comment]
Unterstand.

Will have a look during this week and try to complete it.

**Comment by mcm1957** [comment]
Feel free to take next week too. I'm on holidays next week and will not be able to do a review next week anyway.

**Comment by SKB-CGN** [comment]
RE-CHECK!

**Comment by SKB-CGN** [comment]
RE-CHECK!

**Comment by SKB-CGN** [comment]
RE-CHECK!

**Comment by SKB-CGN** [comment]
RE-CHECK!

**Comment by SKB-CGN** [comment]
Hi @mcm1957 - i have updated all things and i think, the adapter is fully operable.
What do you think?

**Comment by mcm1957** [comment]
Thanks for Info - I'll do a recheck

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by SKB-CGN** [comment]
RE-CHECK!

**Comment by SKB-CGN** [comment]
@mcm1957 As all errors have been fixed, can we proceed?

**Comment by SKB-CGN** [comment]
Not a problem ;)
Take your time!

**Comment by mcm1957** [comment]
@SKB-CGN 

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I'm sorry, that I did not check this adapter for such a long time - I simpyl do not have enough spare time.

Thanks for fixing issues already listed by Apollon77 and adapter checker. I do not remeber to have scanned this adapter in the past so I did a full recheck. Sorry to say that I would like to note some MINOR remarks. I think they should be fixable with small effort. Please take a look and do not spent time for eslint - this last point is only a hint for the future and not related to release for latest.

Thanks 
mcm1957 

-------
 
- [ ] folder ./lib contains unrelated files

  The folder ./lib contains several fiels copied from ioBroker.repositories. They do not make sense there. Please delete them (I think all but states.js are incorrect)

- [ ] creation of state tree seems to be incomplete

  You are creating some states with a dot in their name, i.e. 'lock.auto_lock'. This creates a tree consisting of an folder named lock and a state below named auto_lock. I could not detect the place where the (folder) Object 'lock' is created. Please note that all levels ob objects (device, channel, folders, states) must be explicitly created. Missing to create intermediate levels might be considered an error in furure versions of js-controller.

  As you seem to have fixed states only, it would be fully sufficient to liste the folders / channels (and even the states) at io-package. See existing creation of info and info.connection state.

- [ ] small note to state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whenever a dedicated role exists.

  State 'locked' must not have role 'indicator' if it is writeable. So either (suggestion) use role 'switch' or disable writeing the state - whatever matches the functionality. (https://github.com/SKB-CGN/ioBroker.mywallbox/blob/3c8d70edebf1902f658aa918aea6a8318badc882/lib/states.js#L413)

  Input states (i.e. maxChargingCurrent) must not have role value.* (as this is read only) but level.* - https://github.com/SKB-CGN/ioBroker.mywallbox/blob/3c8d70edebf1902f658aa918aea6a8318badc882/lib/states.js#L435


- [ ] A hint for migration of EsLint (not blocking remark)
  
  If you plan to migrate EsLint from 8.x.x to current release 9.x.x please migrate to use @iobroker/eslint-config. This is a new central configurarion of eslint-rules which should be used for all (new) adapters. But its not mandatory. A migration / installation guide is can be found here:

https://github.com/ioBroker/ioBroker.eslint-config/blob/main/MIGRATION.md

  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by SKB-CGN** [comment]
Hi,
may i ask you, to check this again, please?

**Comment by mcm1957** [comment]
I do not see a normal "seconds" state for timing too. You may use value.intervall - although its no true interval - or simüly use value as role.

In general it looks like all issues are satisifed. I'll rekease the adapter to stable now.

THANKS a lot for your work.

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Pull request merged**
