### PR TITLE
add ESPHome

### PR DESCRIPTION
**Pull request by DutchmanNL**

### CODE REVIEW

**Comment by Apollon77** [comment]
> https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.esphomemaster/admin/esphome.png no gettable ..404

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.esphome](https://github.com/iobroker-community-adapters/ioBroker.esphome)
[Downloads](https://www.npmjs.com/package/iobroker.esphome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.esphome/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.esphome)!. Please execute in adapter directory: `npm owner add bluefox iobroker.esphome`


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.esphome](https://github.com/iobroker-community-adapters/ioBroker.esphome)
[Downloads](https://www.npmjs.com/package/iobroker.esphome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.esphome/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.esphome)!. Please execute in adapter directory: `npm owner add bluefox iobroker.esphome`


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
> https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.esphomemaster/admin/esphome.png no gettable ..404

sorry stupid type, solved

**Comment by DutchmanNL** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.esphome](https://github.com/iobroker-community-adapters/ioBroker.esphome)
[Downloads](https://www.npmjs.com/package/iobroker.esphome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.esphome/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.esphome](https://github.com/iobroker-community-adapters/ioBroker.esphome)
[Downloads](https://www.npmjs.com/package/iobroker.esphome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.esphome/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
RE-CHECK!

logo fixed, all issue solved

**Comment by DutchmanNL** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.esphome](https://github.com/iobroker-community-adapters/ioBroker.esphome)
[Downloads](https://www.npmjs.com/package/iobroker.esphome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.esphome/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
@Apollon77 all solved 👯

**Comment by Apollon77** [comment]
Hey, review feedback:
* should you encrypt apiPass??
* makes that sense? https://github.com/iobroker-community-adapters/ioBroker.esphome/blob/main/admin/index_m.html#L272 ... and honestly with controller 3.2 as dep simply kill all that encrypt/decrypt and use encrypted/protectedNative

rest ok :-)

**Comment by DutchmanNL** [comment]
> Hey, review feedback:
> 
> * should you encrypt apiPass??
> * makes that sense? https://github.com/iobroker-community-adapters/ioBroker.esphome/blob/main/admin/index_m.html#L272 ... and honestly with controller 3.2 as dep simply kill all that encrypt/decrypt and use encrypted/protectedNative
> 
> rest ok :-)

as discussed by. telegram, encryption for API pass implemented other stay on old fashion as I need to store a array of password which cannot be handled with encryptedNative

https://github.com/DrozmotiX/ioBroker.esphome/commit/f94eee808d60f49155be782a9fe05ed052d6f857

**Comment by DutchmanNL** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.esphome](https://github.com/iobroker-community-adapters/ioBroker.esphome)
[Downloads](https://www.npmjs.com/package/iobroker.esphome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.esphome/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/DrozmotiX/ioBroker.esphome. Expected: git+https://github.com/iobroker-community-adapters/ioBroker.esphome.git


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.esphome](https://github.com/DrozmotiX/ioBroker.esphome)
[Downloads](https://www.npmjs.com/package/iobroker.esphome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.esphome/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
@Apollon77 password encryption for messaging fixed in 0.1.4

see https://github.com/DrozmotiX/ioBroker.esphome/commit/f1f55e794fb9c96d68e4fd8e9df0c480f7a7294d

**Pull request merged**
