### PR TITLE
Update zigbee to 1.9.5

### PR DESCRIPTION
**Pull request by arteck**

### CODE REVIEW

**Comment by mcm1957** [comment]
1.9.5 created 29.12.2023 
not yet published at latest

**Comment by mcm1957** [comment]
a) Title corrected - pelase use meaningful titles (Update xyz to m.n.u) for repository PRs.

b) As this release increases the node-js requirments from 16 to 18 a new minor version wozuld be required minimum. So normally this should be a 1.10.0 release. I'll check with Apollon.

**Comment by mcm1957** [comment]
1.9.5 created 29.12.2023
not yet published at latest

image

**Comment by Apollon77** [comment]
As clarified in Telegram. Go

**Pull request merged**
