### PR TITLE
Bump apg-info to 0.1.6

### PR DESCRIPTION
**Pull request by HGlab01**

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@HGlab01 

Every Adapter at STABLE reposittory MUST pass tests for Node 18 and 20 at all supported platforms (Linux, Windows, Mac).

Why did you remove Windows tests?
Please readd if there is no technical reason which prohibits the adapter to be used at windows.

**Comment by mcm1957** [comment]
reminder 5.4.2024

**Comment by HGlab01** [comment]
> Why did you remove Windows tests? Please readd if there is no technical reason which prohibits the adapter to be used at windows.

Because
1. no OS-based feature of nodejs is used
2. github windows instances are super slow in setup

But if it is a rule I will stick to it. Windows included again.

**Comment by Apollon77** [comment]
@HGlab01 Windows is important because when native libs or dependencies are used or such there always might be build issues that arise, so it is better to check it and know. Thank you for your understanding

**Pull request merged**
