### PR TITLE
add benchmark latest

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [io-package.json](https://github.com/main/io-package.json)
[Downloads](https://www.npmjs.com/package/io-package.json) 
[NPM](https://nodei.co/npm/io-package.json/)

- [ ] :heavy_exclamation_mark: 404


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.benchmark](https://github.com/foxriver76/ioBroker.benchmark)
[Downloads](https://www.npmjs.com/package/iobroker.benchmark) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.benchmark/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:foxriver76/ioBroker.benchmark.git. Expected: git+https://github.com/foxriver76/ioBroker.benchmark.git
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/foxriver76/ioBroker.benchmark/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/foxriver76/ioBroker.benchmark", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/foxriver76/ioBroker.benchmark", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "benchmark" in latest repository
- [ ] :eyes: [W505] setTimeout found in "build/main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by foxriver76** [comment]
Will E019 be fixed on Repo side? then I would merge this

**Pull request merged**
