### PR TITLE
please add sqlstatistics to latest

### PR DESCRIPTION
**Pull request by Scrounger**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sqlstatistics](https://github.com/Scrounger/ioBroker.sqlstatistics)
[Downloads](https://www.npmjs.com/package/iobroker.sqlstatistics) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sqlstatistics/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "main.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/Scrounger/ioBroker.sqlstatistics" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "sqlstatistics" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@Scrounger can you please check the Interval topic?

**Comment by Apollon77** [comment]
@Scrounger ?

**Comment by Scrounger** [comment]
Haven't worked on it much longer.
Currently I'm thinking about limiting the adapter to MySql, because every db provider provides the information very differently.
You are welcome to close the PR for now. I think it makes no sense to push into the latest

**Pull request closed without merging**
