### PR TITLE
add bydhvs adapter

### PR DESCRIPTION
**Pull request by christianh17**
New try - I did it like described in https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository but there are many changes in the PR.
Please give me advice what I shall do.

### CODE REVIEW

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bydhvs](https://github.com/ChristianH17/ioBroker.bydhvs)
[Downloads](https://www.npmjs.com/package/iobroker.bydhvs) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.bydhvs/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :eyes: [W400] Cannot find "bydhvs" in latest repository

### [ioBroker.epson_xp540](https://github.com/tikodu/ioBroker.epson_xp540)
[Downloads](https://www.npmjs.com/package/iobroker.epson_xp540) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.epson_xp540/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by christianh17** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bydhvs](https://github.com/ChristianH17/ioBroker.bydhvs)
[Downloads](https://www.npmjs.com/package/iobroker.bydhvs) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.bydhvs/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "bydhvs" in latest repository

### [ioBroker.epson_xp540](https://github.com/tikodu/ioBroker.epson_xp540)
[Downloads](https://www.npmjs.com/package/iobroker.epson_xp540) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.epson_xp540/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by christianh17** [comment]
RE-CHECK!

**Comment by christianh17** [comment]
Push... What shall I do so somebody cares about my PR?

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bydhvs](https://github.com/ChristianH17/ioBroker.bydhvs)
[Downloads](https://www.npmjs.com/package/iobroker.bydhvs) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.bydhvs/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "bydhvs" in latest repository

### [ioBroker.epson_xp540](https://github.com/tikodu/ioBroker.epson_xp540)
[Downloads](https://www.npmjs.com/package/iobroker.epson_xp540) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.epson_xp540/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
AFAIK you be fixed all issues kn your adapter. Thanks for that, however it seems like your PR is removing the easee adapter, is this intended?

**Comment by christianh17** [comment]
> 
> 
> AFAIK you have fixed all issues kn your adapter. Thanks for that, however it seems like your PR is removing the easee adapter, is this intended?

No, I did not want to touch any other adapters. But: To be honest: I do not know what happened. I strictly followed the readme.md from [https://github.com/ioBroker/ioBroker.repositories](url). Do you have a clue what I shall do?

**Comment by foxriver76** [comment]
Better edit the file manually.

**Comment by Apollon77** [comment]
Seems that easee is twice in repo ... I need to check that ... so all gott. I just need to find time for review... sorry

**Comment by foxriver76** [comment]
Review is already done @Apollon77, https://github.com/ioBroker/ioBroker.repositories/pull/1265#issuecomment-848244692

**Comment by christianh17** [comment]
<push>
Is there anything I can do? Shall I do a new PR and edit the files manually? But in my first try I was advised to use the srcipt.

**Comment by christianh17** [comment]
push - what shall I do???

**Comment by Apollon77** [comment]
Yes adapter is ok and I will add it to the repo. Mega sorry for that long delay.

**Pull request merged**
