### PR TITLE
added synology

### PR DESCRIPTION
**Pull request by instalator**

### CODE REVIEW

**Comment by Apollon77** [comment]
Thank you!
Please add ioBroker team as owners to npm: https://github.com/ioBroker/ioBroker.repositories#add-owner-to-packet

**Comment by Apollon77** [comment]
Thank you!
Please add ioBroker team as owners to npm: https://github.com/ioBroker/ioBroker.repositories#add-owner-to-packet.

Would it be possible to get the README in english too? Google translate would be enough :-)

**Comment by Apollon77** [comment]
And please use "infrastructure" as adapter type instead of "Multimedia".

**Comment by instalator** [comment]
> Please add ioBroker team as owners to npm: https://github.com/ioBroker/ioBroker.repositories#add-owner-to-packet.

14 http request PUT http://registry.npmjs.org/-/team/iobroker/developers/package
15 http 403 http://registry.npmjs.org/-/team/iobroker/developers/package

**Comment by Apollon77** [comment]
npm repo add iobroker team: does npm work for you in general because the response above looks like an error to me

**Comment by instalator** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'access',
1 verbose cli   'grant',
1 verbose cli   'read-write',
1 verbose cli   'iobroker:developers',
1 verbose cli   'iobroker.synology' ]
2 info using npm@2.15.11
3 info using node@v4.6.2
4 verbose config Skipping project config: C:\Users\instalator/.npmrc. (matches userconfig)
5 silly mapToRegistry name iobroker.synology
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry http://registry.npmjs.org/
8 silly mapToRegistry data Result {
8 silly mapToRegistry   raw: 'iobroker.synology',
8 silly mapToRegistry   scope: null,
8 silly mapToRegistry   name: 'iobroker.synology',
8 silly mapToRegistry   rawSpec: '',
8 silly mapToRegistry   spec: 'latest',
8 silly mapToRegistry   type: 'tag' }
9 silly mapToRegistry uri http://registry.npmjs.org/iobroker.synology
10 verbose request uri http://registry.npmjs.org/-/team/iobroker/developers/package
11 verbose request sending authorization for write operation
12 info attempt registry request try #1 at 11:55:22
13 verbose request using bearer token for auth
14 verbose request id 18b2919d4c71490f
15 http request PUT http://registry.npmjs.org/-/team/iobroker/developers/package
16 http 403 http://registry.npmjs.org/-/team/iobroker/developers/package
17 verbose headers { 'content-type': 'application/json',
17 verbose headers   'cache-control': 'max-age=300',
17 verbose headers   'content-length': '21',
17 verbose headers   'accept-ranges': 'bytes',
17 verbose headers   date: 'Thu, 04 Jan 2018 05:55:27 GMT',
17 verbose headers   via: '1.1 varnish',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-served-by': 'cache-hhn1550-HHN',
17 verbose headers   'x-cache': 'MISS',
17 verbose headers   'x-cache-hits': '0',
17 verbose headers   'x-timer': 'S1515045326.076283,VS0,VE1055',
17 verbose headers   vary: 'Accept-Encoding, Accept' }
18 verbose request invalidating C:\Users\instalator\AppData\Roaming\npm-cache\registry.npmjs.org\-\team\iobroker\developers\package on PUT
19 verbose stack Error: Forbidden : -/team/iobroker/developers/package
19 verbose stack     at makeError (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
19 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
19 verbose stack     at Request._callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
19 verbose stack     at Request.self.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
19 verbose stack     at emitTwo (events.js:87:13)
19 verbose stack     at Request.emit (events.js:172:7)
19 verbose stack     at Request.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1044:10)
19 verbose stack     at emitOne (events.js:77:13)
19 verbose stack     at Request.emit (events.js:169:7)
19 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:965:12)
20 verbose statusCode 403
21 verbose cwd C:\Users\instalator
22 error Windows_NT 6.1.7601
23 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "access" "grant" "read-write" "iobroker:developers" "iobroker.synology"
24 error node v4.6.2
25 error npm  v2.15.11
26 error code E403
27 error Forbidden : -/team/iobroker/developers/package
28 error If you need help, you may report this error at:
28 error     <https://github.com/npm/npm/issues>
29 verbose exit [ 1, true ]
```

**Comment by instalator** [comment]
C:\Users\instalator>npm owner add bluefox iobroker.synology
+ bluefox (iobroker.synology)

**Comment by instalator** [comment]
> Would it be possible to get the README in english too? Google translate would be enough :-)
added

**Pull request merged**
