### PR TITLE
added atlas-scientific-ezo-i2c Adapter

### PR DESCRIPTION
**Pull request by Buzze11**
Hi, 
unfortunately the UI in ioBroker-dev for adding to latests fails even though the adapter check is running fine.

The commandline addToLatest throws an error:

> iobroker.repositories@1.0.4 addToLatest
> node lib/scripts.js addToLatest --name atlas-scientific-ezo-i2c --type metering

ERROR: Unsupported protocol ssh:

So I`ve added my adapter manually to the source-dist-stable.json and source-dist.json
Hope that works out. 
 
Best regards
Thomas

### CODE REVIEW

**Comment by Buzze11** [comment]
Hi @mcm1957, sorry for wrong handling. I have removed the adapter now from sources-dist-stable.json and just left the entry in sources-dist.json.

Regards UI: I have had already forked the repository repo yesterday before I have tried the UI approach in iobroker-dev. My first attempt was the command line approach. Just after this did not work out I gave the UI a try as well. So in my case it cannot be related to the Issue "never forked something before". Whenever I will get free time I`ll have a deeper look in there. 

Hope its fine now? Thanks fro your quick reply. 
BR Thomas

**Comment by Buzze11** [comment]
Last question..Do I need to create a new pull request now? Or ist this handled in the same request?
BR Thomas

**Comment by mcm1957** [comment]
> Last question..Do I need to create a new pull request now? Or ist this handled in the same request? BR Thomas

Github merge the changes into the existign PR. (see changed files at top of PR).
So the basics are OK now - checks will start as soon as theres some time.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.atlas-scientific-ezo-i2c](https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c)
[Downloads](https://www.npmjs.com/package/iobroker.atlas-scientific-ezo-i2c) 
[NPM](https://nodei.co/npm/iobroker.atlas-scientific-ezo-i2c/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "atlas-scientific-ezo-i2c" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Buzze11** [comment]
> > Last question..Do I need to create a new pull request now? Or ist this handled in the same request? BR Thomas
> 
> Github merge the changes into the existign PR. (see changed files at top of PR). So the basics are OK now - checks will start as soon as theres some time.

Perfect, thanks a lot.. thumbs pushed!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- Readme.md contains developer info

  The README.md contains some remarks from adapter creator. Please tremove thos sections:
https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c#developer-manualhttps://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c#developer-manual

- i18n translations seem to be inconsistent

  i.e. german translations.json is almost empty while the neglish version contains text.
 
  ``` 
  {
    "atlas-scientific-ezo-i2c adapter settings": "Adaptereinstellungen für atlas-scientific-ezo-i2c"
  }
  ```
  npm run translate (--all) should fix it,

- adapt testing to supported node releases

  Tests for node 16 is mandatory unless you require node 18 and higher. (OK)
  Tests for node 18 is mandatory as many users already use node 18 and node 16 will be eol and deprected Q3/2023. (OK)
  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x],

- consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

  see https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/blob/e386f5403ee8192d1f643db2952ff9b2ce4063f7/src/lib/async.ts#L20  

- please evaluate stateId naming

  Your state Ids look like names, ie
  ```
    async CreateObjects(): Promise<void>{
        await this.adapter.extendObjectAsync(this.hexAddress + '.' + 'Device Status', {
            type: 'state',
            common: {
                name: this.hexAddress + ' ' + (this.config.name || 'DO'),
                type: 'string',
                role: 'value',
            },
            //native: any
        });
  ```
  https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/blob/e386f5403ee8192d1f643db2952ff9b2ce4063f7/src/devices/do.ts#L102

 This is per se no problem, but

  - state ids should not contain spaces. Several otehr adapters and some vis implementaions cannot handle spaces. So I would suggest to replace them i.e. by underscores.
  - dots inside stateIds reflect a folder structure. States should be structured device.channel.state. Its ok to use folders too. But if you use the hexaddress as a folder (or device / channel) please ensure that the corresponding  object is created explicitly.
  
  **Note:** I can have missed some points in your code related to the stae naming. In addition I would suggest to discuss this point with @apollon77 before doing major work to avoid invers statements at official review ! Apollon77 will have time to review after his holidays in app 1 or 2 weeks.,

- please consider using state roles

  I'm not sure wether type of states is rutehr fixed or dynamically defined by connected device. But if possible it would be good to use dedicated matching state roles. See https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md

Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by Buzze11** [comment]
Hi Martin, thanks a lot for your helpful feedback. I will have a look at all the mentioned things from you. 

Honestly I must say this was my first Typescript project at all, except some little play around with Angular. So your feedback is completely reasonable and helpful to me. I have been usually completely in the .net area with C# and my development experience has decreased quite a lot due to I changed my job role some years ago and so I have not developed much the past years. 

I will have a deeper look the next days into your suggestions, and maybe I am quicker with a new better release than the review will be. Shall I cancel the request so that there is no one putting the same effort in it like you unless I have reworked it?

BR Thomas

**Comment by mcm1957** [comment]
Feel free to keep the pr open. I assume you probably will not change 50% of code or more. In generalbthe code looks very good and i m suprised this is your first ts adaptet.

Ingo will not start revie before one or two weeks. And he will read this so he can decidexask aboutcdtatus anyway.

**Comment by Buzze11** [comment]
Hi Martin, I have already changed most of the stuff except setTimeout. I have just released Version 1.1.0 for now. So that it is already mostly related to your suggestions. The rest I`ll try to get time for and also await Ingo`s review to include maybe additional things as well. Hope its useful to someone. Just have done it for my personal project but thought maybe its something for others as well ;)

BR Thomas

**Comment by Buzze11** [comment]
Refactoring for using wrapper setTimeout / clearTimeout done as well.. 

BR Thomas

**Comment by mcm1957** [comment]
RE-REVIEW:
Most remarks have been considered. THANK'S very much.

Here's my newest feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- please evaluate stateId naming again

  Your state Ids look like names, ie
  ```
    async CreateObjects(): Promise<void>{
        await this.adapter.extendObjectAsync(this.hexAddress + '.' + 'Device Status', {
            type: 'state',
            common: {
                name: this.hexAddress + ' ' + (this.config.name || 'DO'),
                type: 'string',
                role: 'value',
            },
            //native: any
        });
  ```
  https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/blob/e386f5403ee8192d1f643db2952ff9b2ce4063f7/src/devices/do.ts#L102

 This is per se no problem, but

  - state ids should not contain spaces. Several other adapters and some vis implementaions cannot handle spaces. So I would suggest to replace them i.e. by underscores.
  - dots inside stateIds reflect a folder structure. States should be structured device.channel.state. Its ok to use folders too. But if you use the hexaddress as a folder (or device / channel) please ensure that the corresponding  object is created explicitly.
  
  **Note:** I can have missed some points in your code related to the stae naming. In addition I would suggest to discuss this point with @apollon77 before doing major work to avoid invers statements at official review ! Apollon77 will have time to review after his holidays in app 1 or 2 weeks.,

   **NEW**: I just detected that some states seem to use "(" within the id - not sure wether this is allowed.
  I would recommend to use only a-z,A-Z,0-9, -,_ für ids.
  Sorry for additional remark.
   see https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/blob/ef12cdd42c7df12d600731f053c2e4ab07f5d15c/src/devices/do.ts#L111

- please consider using state roles

  I'm not sure wether type of states is rutehr fixed or dynamically defined by connected device. But if possible it would be good to use dedicated matching state roles. See https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md

Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by Buzze11** [comment]
Hi McM1957, thanks a lot for your review.. please have a look at my answers inline.. Am 16.06.2023 um 22:17 schrieb Martin M. ***@***.***>:﻿
RE-REVIEW:
Most remarks have been considered. THANK'S very much.
Here's my newest feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.


please evaluate stateId naming again
Your state Ids look like names, ie
  async CreateObjects(): Promise<void>{
      await this.adapter.extendObjectAsync(this.hexAddress + '.' + 'Device Status', {
          type: 'state',
          common: {
              name: this.hexAddress + ' ' + (this.config.name || 'DO'),
              type: 'string',
              role: 'value',
          },
          //native: any
      });

https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/blob/e386f5403ee8192d1f643db2952ff9b2ce4063f7/src/devices/do.ts#L102


This is per se no problem, but

state ids should not contain spaces. Several other adapters and some vis implementaions cannot handle spaces. So I would suggest to replace them i.e. by underscores.
dots inside stateIds reflect a folder structure. States should be structured device.channel.state. Its ok to use folders too. But if you use the hexaddress as a folder (or device / channel) please ensure that the corresponding  object is created explicitly.

Note: I can have missed some points in your code related to the stae naming. In addition I would suggest to discuss this point with @Apollon77 before doing major work to avoid invers statements at official review ! Apollon77 will have time to review after his holidays in app 1 or 2 weeks.,
NEW: I just detected that some states seem to use "(" within the id - not sure wether this is allowed.
I would recommend to use only a-z,A-Z,0-9, -,_ für ids.
Sorry for additional remark.
see Okay, I was not aware about but I will remove the brackets as well. 😉https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/blob/ef12cdd42c7df12d600731f053c2e4ab07f5d15c/src/devices/do.ts#L111


please consider using state roles
I'm not sure wether type of states is rutehr fixed or dynamically defined by connected device. But if possible it would be good to use dedicated matching state roles. See https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md


I have had reviewed the state roles while doing the refactoring, but I could not find any „fitting“ role in there. Thanks for reading and evalutaing this suggestions.
McM1957

But the rest in general in fine now? Thanks for your efforts and the reviewBR Buzze11—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Buzze11** [comment]
Hi Hi McM1957, 

changes applied after your Re-Review. I have also added state roles where possible, state write/read everywhere and units where senseful. Checked in and updated release is triggered.

Thanks and best regards 
Buzze11

**Comment by Buzze11** [comment]
Hi guys, is there already any new feedback? Did the changes fulfill your requirements? 
BR Buzze11

**Comment by mcm1957** [comment]
Revie by @Apollon77 is still pending.
Currently no news from my side.
Sorry, missinf time is the problem currently.

**Comment by Buzze11** [comment]
Okay, thanks for your feedback.. then I'll just wait to hear from you.. 

BR Buzze11

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- [ ] errors reported by adapter checker must be fixed

  Especially error  ```[E201] Bluefox was not found in the collaborators on NPM!.``` must be fixed. If you just invited Bluefox its ignore to wait for his reaction. Please state that the invitation has been sent in this case.
  
- [ ] Readme.md is very short

  The README.md of this adapter is very minimalistic. Please add a short description about the functionality of the adpter,  add links the the manufacturer site (if applicable) and add a description of the configuration of the adapter. If you provide an external documentation - which should be located at doc/xx directory - please add links to at least the english documentation.

- [ ] Readme.md should be written in pure english

  As ioBroker is an international software supporting several languages the main Readme.md file should be written in english. Its ok to add additional Readme-<lang>.mds of course.
  
- [ ] Readme.md contains multiple languages
  
  Please remove the german version / all non english versions from Readme.md because Readme.md gets automatically translated and this will not work with multiple languages within Readme.md. You can add locatlized Readme pages in (docs/de and docs/en) like https://github.com/iobroker-community-adapters/ioBroker.pvforecast/tree/main/docs and add it to io-package (see https://github.com/iobroker-community-adapters/ioBroker.pvforecast/blob/main/io-package.json#L119-L122)
  
- [ ] sensitive information, especially passwords should be stored encrypted
  
  You configuration seems to contain passwords (or other sensitive information) which is not stored encrypted. As long as those information is not stored inside a table you can encrypt and secure this infomation simply by adding the following configuration to io-package.json. The iob runtime will encrypt / decrypt the data as required; no addition programming effort is required. Note that users will need to reenter this info one time after adding encryption, so drop a note at release notes.
  ```
  "encryptedNative": [
    "password",
    "data2"
  ],
  "protectedNative": [
    "password",
    "data2"
  ],
  ```

- [ ] sensitive information should not be logged into logfile

  To avoid publishing sensitive information when forwarding logs, those information should never be written into the logs but either omitted or at least partly masked so that the information cannot be misused. This relates at least to usernames, passwords, uniqui (user assigned) keys and tokens. In addition personal information like name, address, gegraphical coordinagtes should not be logged too.

- [ ] invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```, i.e. by using the following snippet:
```
function name2id(pName) {
    return (pName || '').replace(adapter.FORBIDDEN_CHARS, '_');
}
```

- [ ] unused onStateChange handler

  You configred an onStateChange handler but it looks like this handler does not do any important tasks. Please remove the handler if the adapter does not react on state changes.

- [ ] onStateChange handler ignores ack flag 

  The adapter must honor the ack flag when processing onStateChange events. Whenever the onStateChange handler is called for an own state (a state owned by the processing instance of the adapter) it must ignore this event if the ack flags is set. Only stateChanges with ack==false are allowed to be processed.

  When processing foreign states which are output of another adapter  processing must only occure if the ack flag is true.

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully.
  
- [ ] scheduled adapters should have random delays
  
  An unmodified schedule adapter that queries data from external systems will produce a lot of issues because usually the default schedule stays unchanged for all users and so all installations out there will then contact the server at the exact same time create a "potentially huge" request spike. The best practice for now is at least to add a random delay to spread the calls within that minute - or even move the "minutes" on first start and so persist that (e.g. see https://github.com/ioBroker/ioBroker.yr/blob/master/main.js#L84-L90) ... if the adapter gets successfull then we have a big issue and the webpage owner contacting us ... we seiould prevent that from the beginning.
  
- [ ] unused onState change handler
  
  Looks like your onStageHandler is never used. So please remove it.

- [ ] some labels seem to have no translation into all languages
  
  It seems that some labels are not translated into all supported languages, i.e. ...
  Please consider adding missing translations
  
- [ ] Is there any reason to not use i18n translation environment?
  
  I suggest to evaluate to use i18n translation environment and the iobroker/adapter-dev environment (https://github.com/ioBroker/adapter-dev#iobroker-adapter-dev). You could easyly add new strings to the english json and run ```npm run translate``` afterward. When using i18n environment activating iobrokers weblate translation system (see https://github.com/ioBrokerTranslator/doc) is trivial.  
  
- [ ] consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- [ ] check and limit configurable timeouts / intervals
  
  Node setTimeout/setInterval routines have a maximum allowed value of 2,147,483,647 ms. Using delays larger than 2,147,483,647 ms (about 24.8 days) result in the timeout being executed immediately. So all (user configurable) values passed to setTimeout / setInterval should be checked and limited.
  
- [ ] check and limit intervals used to access cloud services
  
  Limit all intervals used to access cloud services to a reasonable value. If users configure an inapprobiate access rate this could lead to suspending the service by the provider for all ioBroker users.  
  
- [ ] check and adapt testing
  
  Standard iobroker testing is required but seems to be missing. Please add and setup ./gizthub/workflows/test-and-release.yml
  
- [ ] adapt testing to supported node releases

  As node 14 is end of life and will no longer be supported by js-controller 5.x, consider removing node 14.x tests from matrix id still present.
  Tests for node 16 is mandatory unless you require node 18 and higher.
  Tests for node 18 is mandatory as many users already use node 18 and node 16 will be eol and deprected Q3/2023.
  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x],

- [ ] do not access cloud services at fixed timestamps
  
  Avoid accessing cloud services at fixed timestamps (i.e. at every full hour, at 5 minutes after midnight , ...) This could lead to high load peaks at the cloud service as all ioBorker installations will use the service at almost the same time. Use random timestamps where possible.  

- [ ] github dependabot support seems to be missing
  
  It looks like you did not yet setup dependabot support; at least .github/dependaboit.yml is missing.
  
  Please consider setting up dependabot support (and to ease life the workflow auto-merge.yml). Dependabot will ensure that your adapter uses the most recent versions of external packages and avoids problem due to outdted base libraries. Dependabit provides PRs at you repository to update the dependencies. Depending on you setting, especially on auto-merge.yml configuration no or only minor revisions will be outmatically merged into you main branch. All major revisions msiut (ans should) be reviewed by you. 
  
- [ ] This adapter seems to use sentry, but no sentry info is added to Readme.md
  
  This adapter seems to use sentry for error logging. Please add the suggested sentry information at the top of Readme.md
  
  ```**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0.```
  
- [ ] Sentry info at Readme.md could/should be improved
  
  Please extend to sentry information at Readme.md to include all information a user should get to decide wether to use sentry or to disable it. The sentry plugin provides a suggested text:
  
  ```**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0.```
  
  
Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
state ids seem to be ok now too.
So for me everythings ok - let see what Apollon77 detects.

**Pull request merged**
