### PR TITLE
add bwt

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bwt](https://github.com/TA2k/ioBroker.bwt)
[Downloads](https://www.npmjs.com/package/iobroker.bwt) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.bwt/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 TA2k <tombox2020@gmail.com>" at the end of [README.md](https://github.com/TA2k/ioBroker.bwt/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 TA2k <tombox2020@gmail.com>" at the start of LICENSE
- [ ] :eyes: [W400] Cannot find "bwt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bwt](https://github.com/TA2k/ioBroker.bwt)
[Downloads](https://www.npmjs.com/package/iobroker.bwt) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.bwt/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "bwt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by ldittmar81** [comment]
@Apollon77 No errors found. Review can be done.

**Comment by Apollon77** [comment]
Hi,

* https://github.com/TA2k/ioBroker.bwt/blob/master/main.js#L26 please remove if unneeded

**Comment by TA2k** [comment]
is removed

**Pull request merged**
