### PR TITLE
Add ioBroker.gsmsms

### PR DESCRIPTION
**Pull request by forelleblau**
Add new adapter.
- published on npm
- Forum: https://forum.iobroker.net/topic/60383/test-neuer-adapter-gsmsms

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.gsmsms](https://github.com/forelleblau/ioBroker.gsmsms)
[Downloads](https://www.npmjs.com/package/iobroker.gsmsms) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.gsmsms/)

:thumbsup: No errors found
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "gsmsms" in latest repository
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by forelleblau** [comment]
V0.0.4 with optimizations by @Apollon77 released

**Pull request merged**
