### PR TITLE
Added adapter for WARP chargers to sources-dist.json

### LINKED ISSUE #690: Tinkerforge WARP 2 Wallbox
**What kind of device or service you would like to see an adapter for?**
Ich habe 2 Tinkerforge WARP 2 Wallboxen und würde diese gern über einen Adapter integrieren können. Leider fehlen mir die Fähigkeiten so etwas selbst zu schreiben, vielleicht besteht ja bei mehreren Interesse dazu. Sonst müsste ich mich mit der Integration über MQTT beschäftigen. 

**Is an official API including documentation is available?**
Von Tinkerforge wird eine API hier bereitgestellt https://www.warp-charger.com/api.html?v=2

Vielen Dank schon einmal im Voraus an denjenigen der sich der Sache annehmen möchte :)

### PR DESCRIPTION
**Pull request by pottio**
Fixes https://github.com/ioBroker/AdapterRequests/issues/690

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by pottio** [comment]
Ich habe bereits einige positive Rückmeldungen erhalten, sowohl für WARP 1, als auch WARP 2 Charger. Was fehlt noch, damit der PR gemerged werden kann?

**Comment by Apollon77** [comment]
Der Adapter-Review durch mich fehlt noch.

**Comment by Apollon77** [comment]
Hi, here some Review feedback:
* (Must) Please do not use setObject for state objects! e.g. https://github.com/pottio/ioBroker.warp/blob/c6a19cd1aead22549e638144b6f60de91ddb380f/src/warp/warp-service.ts#L285 ... better option is setObjectNotExistAsync or extendObjects (yes extend also works when object do not exist before)
* Question/Hint: How many states that allow actions you usually have? also: how many single subscribes you do? Starting with 100 or such it is cheaper in sum to do a "*" subscribe and filter inconing data on receive :-)
* Info: The password encryption can be made more simple with the new options like "encryptedNative" and such , but works. But you should set protectedNative for "Passwordd" field to prevent access to the encrypted password from other adapters
* Info: The "news" entry for 0.0.2 in io-package seems completely broken.
* Info: In unload/terminate ... in fact no need to unsubscribe because this will happen automatically ... maybe tear doown your service first ... https://github.com/pottio/ioBroker.warp/blob/c6a19cd1aead22549e638144b6f60de91ddb380f/src/warp/warp-service.ts#L56
* Info: Do you think the idea with "create objects within first 60s after start" is really the best approch? you can also simply remember which devices you initialized already or such ... more flexible and especially old systems could have issues in load situations with 60s :-)

Please adjust the first point (and maybe more if you like) and publish a new version and poke again here. Thank you.

**Comment by pottio** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.warp](https://github.com/pottio/ioBroker.warp)
[Downloads](https://www.npmjs.com/package/iobroker.warp) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.warp/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "warp" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@pottio Ready for re-review?

**Comment by pottio** [comment]
Hi, thanks for your feedback.

- (Must) Please do not use setObject for state objects! e.g. https://github.com/pottio/ioBroker.warp/blob/c6a19cd1aead22549e638144b6f60de91ddb380f/src/warp/warp-service.ts#L285 ... better option is setObjectNotExistAsync or extendObjects (yes extend also works when object do not exist before)
**> Changed object creation/update to extendObjectAsync(...)**
- Question/Hint: How many states that allow actions you usually have? also: how many single subscribes you do? Starting with 100 or such it is cheaper in sum to do a "*" subscribe and filter inconing data on receive :-)
**> In total less than 20 states depending which WARP charger is used**
- Info: The password encryption can be made more simple with the new options like "encryptedNative" and such , but works. But you should set protectedNative for "Passwordd" field to prevent access to the encrypted password from other adapters
**> Used "encryptedNative" instead of unnecessary implementation within adapter/admin page. Also protected "user" and "password" via "protectedNative" feature**
- Info: The "news" entry for 0.0.2 in io-package seems completely broken.
**> Fixed**
- Info: In unload/terminate ... in fact no need to unsubscribe because this will happen automatically ... maybe tear doown your service first ... https://github.com/pottio/ioBroker.warp/blob/c6a19cd1aead22549e638144b6f60de91ddb380f/src/warp/warp-service.ts#L56
**> Removed unnecessary state unsubscribe implementations**
- Info: Do you think the idea with "create objects within first 60s after start" is really the best approch? you can also simply remember which devices you initialized already or such ... more flexible and especially old systems could have issues in load situations with 60s :-)
**> Created a new improvement issue for that topic (https://github.com/pottio/ioBroker.warp/issues/32)**

Please review again. Thanks!

**Comment by Apollon77** [comment]
Hi,

near to complete :-)
* with the ecnrypt change please add a common.globalDependencies with admin >= 4.0.9 to io-package.
Please add that and release update to npm and we are redy to merge! Thanky ou for your support!

Ingo

**Comment by pottio** [comment]
Hi, I added the _common.globalDependencies with admin >= 4.0.9 to io-package_ and deployed a new version :)

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.warp](https://github.com/pottio/ioBroker.warp)
[Downloads](https://www.npmjs.com/package/iobroker.warp) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.warp/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "warp" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Thank you, and welcome to the repo :-)

**Pull request merged**
