### PR TITLE
Updated vis-inventwo stable version to 1.3.3

### PR DESCRIPTION
**Pull request by jkvarel**
Updated vis-inventwo stable version to 1.3.3

### CODE REVIEW

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-inventwo](https://github.com/inventwo/ioBroker.vis-inventwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-inventwo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-inventwo/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/inventwo/ioBroker.vis-inventwo) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-inventwo](https://github.com/inventwo/ioBroker.vis-inventwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-inventwo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-inventwo/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/inventwo/ioBroker.vis-inventwo) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by jkvarel** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-inventwo](https://github.com/inventwo/ioBroker.vis-inventwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-inventwo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-inventwo/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/inventwo/ioBroker.vis-inventwo) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-inventwo](https://github.com/inventwo/ioBroker.vis-inventwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-inventwo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-inventwo/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/inventwo/ioBroker.vis-inventwo) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
