### PR TITLE
promote ioBroker.unifi to stable 0.6.6 version

### PR DESCRIPTION
**Pull request by jens-maus**
Please update ioBroker.unifi to 0.6.6

### CODE REVIEW

**Comment by mcm1957** [comment]
0.6.5 released 20.6 = today
Not even at latest

New releases must be available at latest for some time unless an urgent release is rwquired as hotfix. Please state if thi is rhe case.

**Comment by jens-maus** [comment]
0.6.5 is a minor release but the last stable was 0.5.x. Thus, time to get 0.6.x into stable and no need to wait if 0.6.5 is stable enough, since only minor changes happened in there. So please promote 0.6.5 to stable as requested.

**Comment by mcm1957** [comment]
PR changed

0.6.6 has just been released
And replaces 0.6.5 from earlier this day..

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
0.6.6 20.6.2023, 319 User (6%)
OK

**Pull request merged**
