### PR TITLE
Add rmb-bhkw to latest

### PR DESCRIPTION
**Pull request by satchafunkilus**
Please add my adapter ioBroker.rmb-bhkw to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

THIS IS A REPLACEMENT FOR #1779
PLEASE SEE DISCUSSION AT #1779

### CODE REVIEW

**Comment by satchafunkilus** [comment]
Referring to PR https://github.com/ioBroker/ioBroker.repositories/pull/1779

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lightify](https://github.com/soef/ioBroker.lightify)
[Downloads](https://www.npmjs.com/package/iobroker.lightify) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lightify/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL in [package.json](https://github.com/soef/ioBroker.lightify/blob/master/package.json): https://github.com/soef/iobroker.lightify. Expected: git@github.com:soef/ioBroker.lightify.git or https://github.com/soef/ioBroker.lightify.git
- [ ] :heavy_exclamation_mark: [E104] No "common.titleLang" found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E115] No license found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)

### [ioBroker.mihome-cloud](https://github.com/TA2k/ioBroker.mihome-cloud)
[Downloads](https://www.npmjs.com/package/iobroker.mihome-cloud) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mihome-cloud/)

- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
- [ ] :heavy_exclamation_mark: [E407] Meta URL (latest) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
- [ ] :heavy_exclamation_mark: [E426] Icon (stable) must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
- [ ] :heavy_exclamation_mark: [E428] Meta URL (stable) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
- [ ] :heavy_exclamation_mark: [E606] Current adapter version 0.1.0 not found in [README.md](https://github.com/TA2k/ioBroker.mihome-cloud/blob/master/README.md)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/TA2k/ioBroker.mihome-cloud/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W515] Why you decided to disable i18n support?

### [ioBroker.rmb-bhkw](https://github.com/satchafunkilus/ioBroker.rmb-bhkw)
[Downloads](https://www.npmjs.com/package/iobroker.rmb-bhkw) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.rmb-bhkw/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "rmb-bhkw" in latest repository

### [ioBroker.semp](https://github.com/rg-engineering/ioBroker.semp)
[Downloads](https://www.npmjs.com/package/iobroker.semp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.semp/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.semp)!. Please execute in adapter directory: `npm owner add bluefox iobroker.semp`
- [ ] :heavy_exclamation_mark: [E506] Word "DeviceSwitchOffAtEndOfTimer" is not translated to german in [admin/words.js](https://github.com/rg-engineering/ioBroker.semp/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "DeviceSwitchOffAtEndOfTimer" is not translated to russian in [admin/words.js](https://github.com/rg-engineering/ioBroker.semp/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W202] Version of [package.json](https://github.com/rg-engineering/ioBroker.semp/blob/master/package.json) (1.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.semp) (1.0.0)

### [ioBroker.vis-2-widgets-gauges](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges)
[Downloads](https://www.npmjs.com/package/iobroker.vis-2-widgets-gauges) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-2-widgets-gauges/)

- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E162] onlyWWW should have common.mode "none" in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E124] Main file not found under URL: https://raw.githubusercontent.com/ioBroker/ioBroker.vis-2-widgets-gauges/main/main.js
- [ ] :heavy_exclamation_mark: [E504] "main.js" found in [package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.vis-2-widgets-material](https://github.com/ioBroker/ioBroker.vis-2-widgets-material)
[Downloads](https://www.npmjs.com/package/iobroker.vis-2-widgets-material) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-2-widgets-material/)

- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E162] onlyWWW should have common.mode "none" in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E142] logo is too big. It must be less or equal than 512x512
- [ ] :heavy_exclamation_mark: [E124] Main file not found under URL: https://raw.githubusercontent.com/ioBroker/ioBroker.vis-2-widgets-material/main/main.js
- [ ] :heavy_exclamation_mark: [E504] "main.js" found in [package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/ioBroker/ioBroker.vis-2-widgets-material", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/ioBroker/ioBroker.vis-2-widgets-material", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
## Automated adapter checker

### [ioBroker.rmb-bhkw](https://github.com/satchafunkilus/ioBroker.rmb-bhkw)
[Downloads](https://www.npmjs.com/package/iobroker.rmb-bhkw) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.rmb-bhkw/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "rmb-bhkw" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
## Automated adapter checker

### [ioBroker.rmb-bhkw](https://github.com/satchafunkilus/ioBroker.rmb-bhkw)
[Downloads](https://www.npmjs.com/package/iobroker.rmb-bhkw) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.rmb-bhkw/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "rmb-bhkw" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.rmb-bhkw](https://github.com/satchafunkilus/ioBroker.rmb-bhkw)
[Downloads](https://www.npmjs.com/package/iobroker.rmb-bhkw) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.rmb-bhkw/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "rmb-bhkw" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
How shall we continue?
Please let us know if you plan zu fix the noted issues in the near future - or as an alterntive - like to discuss some / all of those points.

**Comment by mcm1957** [comment]
@satchafunkilus 

Any news?
Do you need help fixing the issues?

Please let us know if you still are woirking / maintain this adapter - a simple I'll continue as soon as I have time would be ok.

**If there is no reaction until 15.12.2023 this PR will be closed.**

@Apollon77 FYI

**Comment by satchafunkilus** [comment]
I'll take a look in the upcoming days

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, ist OK to continue using this topic too.

**Pull request merged**
