### PR TITLE
Add new Adapter for LG ESS HOME Inverter

### PR DESCRIPTION
**Pull request by Morluktom**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) 
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "lg-ess-home" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi, here some review comments:
* please translate the entries in io-package.json. YOu can use the iobroker translation tool (see readme here from repo in Best oractices)
* you implemented the "auto encryption logic" in admin, but you did not configured the fields in io.package. please add the encryptedNative and protectedNative sections - see also Best practices and feature descritpion in Readme of js-controller. Without this it will stay unencrypted in current controller versions
* In your adapter code the relevant logic to do not encrypt if controller supports it is not included. please check that mix and fix it
* you have defined the info.connection state in the instanceObjects ... please also create the relevant channel "info" there.
* https://github.com/Morluktom/ioBroker.lg-ess-home/blob/master/package.json#L23 really that outdated? Please update!!
* whats that? https://github.com/Morluktom/ioBroker.lg-ess-home/blob/master/main.js#L72-L110 I think you want to remove that or?!
* states in objects is only supported for number types (https://github.com/Morluktom/ioBroker.lg-ess-home/blob/master/lib/LgEss.js#L124)
* Note: e.g. https://github.com/Morluktom/ioBroker.lg-ess-home/blob/master/lib/LgEss.js#L601 ... tin timeout cases "response" is undefined ... so you should check that too before accessing response.statusCode

Thank you for checking and adjusting

**Comment by Morluktom** [comment]
Re work done.
Please Re-Check

**Comment by Apollon77** [comment]
Hey,

ok, I do not really understand why you removed the auto encryption (which should do all that stuff easier for devs), but ok also should work that way.

But I found one more issue (sorry):
* please do not add own fields into common on an object (https://github.com/Morluktom/ioBroker.lg-ess-home/blob/master/lib/LgEss.js#L301) ... you can use the native party for that


Rest looks good

**Comment by Morluktom** [comment]
Hi, 
I moved the ScalingFactor from common to nativ and i also have included the auto password encryption.
Thanks for your work.
Tom

**Comment by Morluktom** [comment]
@Apollon77 , is something still open?

**Comment by Apollon77** [comment]
SOrry, seemed I missed the notify, will check tomorrow

**Comment by Morluktom** [comment]
@Apollon77  everthing ok?

**Comment by Apollon77** [comment]
@Morluktom CLosed because it ttook too long? Then I'm really sorry

**Pull request closed without merging**
