### PR TITLE
Update bsblan to 0.3.3

### PR DESCRIPTION
**Pull request by hacki11**

### CODE REVIEW

**Comment by mcm1957** [comment]
•	[ ] ❗ [E019] Invalid repository URL in [package.json](https://github.com/hacki11/ioBroker.bsblan/blob/master/package.json): git://[git@github.com](mailto:git@github.com)/hacki11/ioBroker.bsblan.git. Expected: [git@github.com](mailto:git@github.com):hacki11/ioBroker.bsblan.git or https://github.com/hacki11/ioBroker.bsblan.git

must be fixed, Note: https:// version should work.

**Comment by hacki11** [comment]
RE-CHECK!

**Comment by hacki11** [comment]
npm publish v0.3.3 not yet done. (currently blocked, need to wait 24h) The adapter checker seems to use not the version i specified in the pull request. Don't know if this is as expected.

**Comment by mcm1957** [comment]
Checker reads data from latest repository. Normally a PR for stable should be created earliest 7 days after availability at latest repo. See comment above.

**Comment by mcm1957** [comment]
RE-CHECK!

**Pull request closed without merging**
