### PR TITLE
Update fronius-wattpilot to 4.6.3

### PR DESCRIPTION
**Pull request by tim2zg**
updated wattpilot from 4.6.2 to 4.6.3

### CODE REVIEW

**Comment by tim2zg** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
4.6.3. created 24.12.2023
32 user
OK

**Comment by mcm1957** [comment]
Tests for node 18 and 20 are missing. Node 18 is mandatory
Std tests need a check - I'll do today and note wether an update is recommended. As I need to run tests locally anyway I will provide a PR if suggested.

**Comment by mcm1957** [comment]
Tests with node 16/18/20 pass with updated workflow.
Please merge PR https://github.com/tim2zg/ioBroker.fronius-wattpilot/pull/49 whenever you find time to do so.

**Comment by tim2zg** [comment]
done

**Pull request merged**
