### PR TITLE
add adapter evcc to stable

### PR DESCRIPTION
**Pull request by Newan**

### CODE REVIEW

**Comment by mcm1957** [comment]
Please fix inconstencies at io-package.json:
https://github.com/Newan/ioBroker.evcc/issues/20

Icon at sources-dist-stable is also incorrect:
image

And last sources-dist.jsosn seems to need a fix to. (Please use a seperate PR for this and do not mix latest and stable updates in one PR).
image

**Comment by Newan** [comment]
> Please fix inconstencies at io-package.json: [Newan/ioBroker.evcc#20](https://github.com/Newan/ioBroker.evcc/issues/20)
> 
> Icon at sources-dist-stable is also incorrect: image
> 
> And last sources-dist.jsosn seems to need a fix to. (Please use a seperate PR for this and do not mix latest and stable updates in one PR). image

done, fixed

**Comment by Newan** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
released 14.06.2023
User 109
OK

**Pull request merged**
