### PR TITLE
Update bsblan adapter to 0.3.1

### PR DESCRIPTION
**Pull request by hacki11**

### CODE REVIEW

**Comment by hacki11** [comment]
RE-CHECK!

**Comment by hacki11** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@hacki11 
Your adapter https://github.com/hacki11/ioBroker.bsblan does not use standard iobroker testing using node 16/18/20

Please see requirements https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository which is also required for stable repository.

Adapter needs to have at least Adapter basic testing (installing, running) using GitHub actions. More information in forum from apollon77 (Just take from other adapters the samples)

Although your tests signal a green checkmark, they also signal that niode 14 tests have passed. This is impossible and indicates that you test do not include the required integration tests (= test that adapetr starts without error).

**I suggest that you completly replace the existing workflow test-and-release by an aup to date version.  You may copy the test-and-release.yml workflow from the example adapter or newly created adapter. If you need help, please let us know.**

Please feel free if you need any help setting up standard testing and / or if you prefer a that we / I create a PR to fix this.

Please add a comment when you have reviewed and fixed the suggestion or at least commented the suggestions and you think the adapter is ready for a re-review

**Comment by hacki11** [comment]
@mcm1957 I hope I have addressed your topics correctly.

**Comment by mcm1957** [comment]
0.3.1 created 08.10.2023
20 user (9%)
OK

**Pull request merged**
