### PR TITLE
Added mclighting

### PR DESCRIPTION
**Pull request by instalator**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mclighting](https://github.com/instalator/ioBroker.mclighting)
[Downloads](https://www.npmjs.com/package/iobroker.mclighting) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mclighting/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/instalator/ioBroker.mclighting) are broken. Please fix.
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by instalator** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mclighting](https://github.com/instalator/ioBroker.mclighting)
[Downloads](https://www.npmjs.com/package/iobroker.mclighting) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mclighting/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Pull request closed without merging**
