### PR TITLE
Webuntis

### PR DESCRIPTION
**Pull request by Newan**
update stable repo

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.webuntis](https://github.com/Newan/ioBroker.webuntis)
[Downloads](https://www.npmjs.com/package/iobroker.webuntis) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.webuntis/)

:thumbsup: No errors found

### [package.json](https://github.com/main/package.json)
[Downloads](https://www.npmjs.com/package/package.json) 
[NPM](https://nodei.co/npm/package.json/)

- [ ] :heavy_exclamation_mark: 404: Invalid URL


*Add comment "RE-CHECK!" to start check anew*

**Comment by Newan** [comment]
The adapter is already in the repository, it would only need to be updated

**Comment by Apollon77** [comment]
Hm ... if already in repo ... why this PR shows an addition? ... need to check

**Comment by Newan** [comment]
I think it's just the PR is wrong, because I made an update to the old one and not a new one fork

**Comment by Apollon77** [comment]
@Newan Can you please then recreae the PR?

**Pull request closed without merging**
