### PR TITLE
Add vis-2-shelly to latest

### PR DESCRIPTION
**Pull request by Kollos2k**

### CODE REVIEW

**Comment by Kollos2k** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

You will find the results of the review and evntually issues / suggestings as a communt to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

mcm1957

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects. As this adapter is related to vis-2 a review from Aüpollon77 or Foxriver might be required too.

- [ ] errors reported by adapter checker must be fixed

  Especially error  ```[E201] Bluefox was not found in the collaborators on NPM!.``` must be fixed. If you just invited Bluefox its ignore to wait for his reaction. Please state that the invitation has been sent in this case.
  
- [ ] directory readme

  Documentation should be stored insiede directory doc. So please rename directory readme to doc.

   
- [ ] please verify that all dependencies are up to date

  Some dependencies are outdated. Please update to current releases if no special reason to keep an older version exists. There are several open dependabot PRs indicating outdated dependencies. Please merge unless theres a technical reason to delay an upgrade:

image

  
- [ ] check 'singleton' flag

  Is it possible to run multiple instances of this adapter? Id not you should set attribute 'singleton=true'


- [ ] some UI files seem to be templates
 
  - i18n files are templates, please sync with words.js (use npm run translate ...) or remove them
  - custom config is likely misconfigured. Please check. 


- [ ] remove license entyr from io-package.json

   license entry is deprected and has been replyed by licenseInformation. Only one of those entries must be present.

- [ ] invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```, i.e. by using the following snippet:
```
function name2id(pName) {
    return (pName || '').replace(adapter.FORBIDDEN_CHARS, '_');
}
```

- [ ] avoid usage of setObject

  setObject(Async) creates a new object whenever it is called. You should avoid using setObject unless you really want to create new objects. Creating a new object deletes any userConfig, i.e. configures history logging which is most likely not desired. Most likely either setObjectNotExists oder (even better in most cases) extendObject should be used. Extend Object ensures that attributes like role, read/write flag etc. are set as specified and hence extendObjet shul dbe preferred when called onece during startup of the adapter.


- [ ] checkfor missing  await

  at some locations await seems to be missing. I.e. here https://github.com/Kollos2k/ioBroker.vis-2-shelly/blob/e195af3a67a7b115268f3a1ba67122f05eed656d/main.js#L232 you use setObject to create a state without await and assign a value 3 lines below. This state might not be created when trying to set it. Please check all your async operations.

- [ ] unused routine ?

  Routine createAndSetState seems to be unused. Please remove if this is correct.
  https://github.com/Kollos2k/ioBroker.vis-2-shelly/blob/e195af3a67a7b115268f3a1ba67122f05eed656d/main.js#L316

- [ ] onStateChange handler ignores ack flag 

  The adapter must honor the ack flag when processing onStateChange events. Whenever the onStateChange handler is called for an own state (a state owned by the processing instance of the adapter) it must ignore this event if the ack flags is set. Only stateChanges with ack==false are allowed to be processed.

  When processing foreign states which are output of another adapter  processing must only occure if the ack flag is true.

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whnever a dedicated role exists.

  Roles like role: "shelly.deviceList" are prohibited.

  Ensure that write:true is ONLY set if this state is to be written by other adapters or userscripts.


- [ ] some labels seem to have no translation into all languages
  
  It seems that some labels are not translated into all supported languages, i.e. ...
  Please consider adding missing translations
  
- [ ] check and adapt testing
  
  Standard iobroker testing is required but seems to be missing. Please add and setup ./gizthub/workflows/test-and-release.yml. Please add standard workflow. Please enable linter - should be possible with new code.
  
- [ ] adapt testing to supported node releases

  As node 14 is end of life and will no longer be supported by js-controller 5.x, consider removing node 14.x tests from matrix id still present.
  Tests for node 16 is mandatory unless you require node 18 and higher (at package.json).
  Tests for node 18 is mandatory as this is the recommended node version and node 16 will be eol and deprected Q3/2023.
  Add node 20 tests unless you already know incompatibilities. In this case, try to fix it as soon as possible and definitly add a issue describing the problem.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x] or [18.x, 20.x] depending on engines requirments setting at package.json 


- [ ] Testing must be performed at all supported platforms (linux, windows, mac-os).

  Unless there are any technical reasons to support only a subset of platforms, adapters must work at all platforms supported by ioBroker.

Thanks for reading and evaluating this suggestions.
Please keep in mind that this a quick first review so that you get a feedback as soon as possible. There might be additional remarks later.

McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**


@Apollon77:

- [ ] please indicate whether the NAME of this adapter is acceptable or it should include "widget" or so

**Comment by mcm1957** [comment]
@Kollos2k 
Did you close this PR intentionally ?
May I ask why?

**Comment by Kollos2k** [comment]
I try to figure out how all this works..... I have reopen it.

**Comment by foxriver76** [comment]
Frontend code looks good to me, nothing critical @mcm1957

**Comment by mcm1957** [comment]
> I try to figure out how all this works..... I have reopen it.

No problem - I'll recheck as soon as I have time.

**Comment by mcm1957** [comment]
Severel issues still open. (NO problem).

Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!

Please note that I will not be really reachable the rest of this week.

reminder 25.3.2024

**Comment by mcm1957** [comment]
@Lokkos2k

How shall we continue?
Do you need any help?
Did you notice the last comment and the provided PR?

Please check andfix or at least comment the issues listed earlier (https://github.com/ioBroker/ioBroker.repositories/pull/3384#issuecomment-1979597075)

reminder 8.4.2024

**Comment by Kollos2k** [comment]
I have no idea what I have to do. Everything seems good for me and there are no errors I have to fix?...

**Comment by foxriver76** [comment]
I think @mcm1957 refers to this todo list, where some entries are still open https://github.com/ioBroker/ioBroker.repositories/pull/3384#issuecomment-1979597075

**Comment by mcm1957** [comment]
> I have no idea what I have to do. Everything seems good for me and there are no errors I have to fix?...

Did you check / process the list of issues I posted earlier (https://github.com/ioBroker/ioBroker.repositories/pull/3384#issuecomment-1979597075) and think those points are solved?
Then If yes I will do a recheck. Please indicate.

I did not see a comment stating that the adapter is ready for review yet so I posted this reminder.

**Comment by Kollos2k** [comment]
Ok. I have to check it at evening.

**Comment by mcm1957** [comment]
> Ok. I have to check it at evening.

Thanks. And please feel free to ask if you have any questions and need support.

**Comment by Kollos2k** [comment]
I hope I have fixed the most issues.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@Kollos2k 

Thanks for all the fixes already performed. Please see my notes from the last review below.
- Testing must be fixed.
- Updates of dependencies read as a note / suggestion only.
- ack Handling at onStateChange must be fixed / discussed. Might be that I do not understand the purpose of your onStateChange handler. Please respond if something should be clearified.

In general 90% are done - good work and THANK you.

---------------------

- [ ] please verify that all dependencies are up to date (NON-blocking !)

Some dependencies are outdated. Please update to current releases if no special reason to keep an older version exists. There are several open dependabot PRs indicating outdated dependencies. Please merge PRs unless theres a technical reason to delay an upgrade

- [ ] onStateChange handler ignores ack flag

The adapter must honor the ack flag when processing onStateChange events. Whenever the onStateChange handler is called for an own state (a state owned by the processing instance of the adapter) it must ignore this event if the ack flags is set. Only stateChanges with ack==false are allowed to be processed.

When processing foreign states which are output of another adapter processing must only occure if the ack flag is true.

You subscribe to OWN states. But you do not check for ACK flag to be false when getting notified about a state change occuring at own states.

I think it will be necessary to distuingish whether onStateChange occures for own or for foreign states as this will likely require different actions. In any case ack handling should be different.

- [ ] adapt testing to supported node releases

Tests for node 18 are mandatory as this is the recommended node version and node 16 will be eol and deprected Q3/2023.
Tests for node 20 are mandatory unless you already know incompatibilities which cannot be fixed immidiatly. In this case, try to fix it as soon as possible and definitly add a issue describing the problem. 

So the recommended testmatrix is [18.x, 20.x] depending on engines requirments setting at package.json

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

reminder 12.4.2024

**Comment by mcm1957** [comment]
> 🔸I don't know how to fix the tests. I use the GitHub automation tests like showed in the video from Haus-Automatisierung.com....

Script is ok, but node 20 had been commented out. I readded it to test matrix. See PR:
https://github.com/Kollos2k/ioBroker.vis-2-shelly/pull/18

> 🔸 I'll fix the depencies.

Thanks

> 🔸I thought I have fixed the onStateChange issue. In the main.js the onStateChange will fired but only an function is called if the ack is true..... Or I have misunderstood the issue?

I will reposnd to this a little bit later

**Comment by mcm1957** [comment]
@Kollos2k 

> > 🔸I don't know how to fix the tests. I use the GitHub automation tests like showed in the video from Haus-Automatisierung.com....
 
>I readded it to test matrix and provided a PR. Hope this explains everything for this point. [Kollos2k/ioBroker.vis-2-shelly#18](https://github.com/Kollos2k/ioBroker.vis-2-shelly/pull/18)

I c reated the mentioned PR. Merging this PR should correct test-and-release.yml. 
Please check and merge the PR.

> > 🔸I thought I have fixed the onStateChange issue. In the main.js the onStateChange will fired but only an function is called if the ack is true..... Or I have misunderstood the issue?

> I will reposnd to this a little bit later

Sorry for the very late answer. Was busy the last days.
onStateChange is called whenever a subscribed state is changed. 

You subscribe to i.e. "shelly.*" which are foreign states. Whenever an onStateChange from those foreign states is received, your adapter should (most likely) only react on changes with ack=true. This rule is typical and there might be reasons to also process events with ack=false.

You also subscribe to OWN states (= states created by this adapter) as far as I read the code. Any write to a state of your adapter must be ignored if ack=true. Users (vis, java-script) must write changes with ack=false.

So you must most likely filter ack value depending an "class" of state.

Maybe it wouldbe goog to explain what state changes you expect done and what reaction you will perfrom on them,

Please comment / discuss if any more questions,

reminder 17.4.2024

**Comment by mcm1957** [comment]
@Kollos2k 
Do you need any help or have any questions to discuss?

reminder 27.4.2024

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
New PR to update tests to nodejs 18/20
https://github.com/Kollos2k/ioBroker.vis-2-shelly/pull/22

**Comment by mcm1957** [comment]
@Kollos2k 

How should we continue?
New PR to update tests to nodejs 18/20 has been proivided but not yet merged.
https://github.com/Kollos2k/ioBroker.vis-2-shelly/pull/22

Do you still work on this adapter oder did you stop working on it?
I do not want to recheck if you lost interest. But according to last comments most likely missing dependendy updates and especially missing testing with node 20 are blocking.

So please check and merge the PR and update testing and adapter-core to current versions (otherwise the tests will most likely fail). If you need an PR to update dependencies, please let me know.

reminder 28.5.2024

**Comment by mcm1957** [comment]
@Kollos2k 

How should we continue?
New PR to update tests to nodejs 18/20 has been proivided but not yet merged.
https://github.com/Kollos2k/ioBroker.vis-2-shelly/pull/22

**Do you still work on this adapter oder did you stop working on it?**

I do not want to recheck if you lost interest. But according to last comments most likely missing dependendy updates and especially missing testing with node 20 are blocking.

So please check and merge the PR and update testing and adapter-core to current versions (otherwise the tests will most likely fail). If you need an PR to update dependencies, please let me know.


**If there is no reaction at all until 30.6.2024 this PR will be closed**

reminder 15.6.2024

**Comment by mcm1957** [comment]
@Kollos2k

How should we continue?
New PR to update tests to nodejs 18/20 has been proivided but not yet merged.
https://github.com/Kollos2k/ioBroker.vis-2-shelly/pull/22

Do you still work on this adapter oder did you stop working on it?

I do not want to recheck if you lost interest. But according to last comments most likely missing dependendy updates and especially missing testing with node 20 are blocking.

So please check and merge the PR and update testing and adapter-core to current versions (otherwise the tests will most likely fail). If you need an PR to update dependencies, please let me know.

If there is no reaction at all until 30.6.2024 this PR will be closed

reminder 01.07.2024

**Comment by mcm1957** [comment]
As there was no reaction until now I will close this PR.

Please feel vre to create a new PR at any time.

**Pull request closed without merging**
