### PR TITLE
Add hue-extended to latest repository

### PR DESCRIPTION
**Pull request by Zefau**
hue-extended adapter to retrieve all information from Hue Bridge.
- Synchronize Config
- Synchronize Groups
- Synchronize Lights
- Synchronize Resources
- Synchronize Rules
- Synchronize Scenes
- Synchronize Schedules
- Synchronize Sensors 
- Trigger changes on states `on/off`, `bri` (`level`), `hue`, `sat`, `xy`, `ct`, `alert`, `effect` and `transitiontime`
- Additional triggers based on color spaces for `rgb`, `hsv`, `xyz`, `cmyk` and `hex`
- Run scene or apply `scene` on light or group

### CODE REVIEW

**Comment by Zefau** [comment]
@Apollon77 sorry for pinging you. Could you please merge?

**Comment by Apollon77** [comment]
Will check tomorrow after finalizing some other stuff.

**Comment by Apollon77** [comment]
Ok one question: is this a completely new adapter or "just" an enahnced version of the hue adapter? If second: Why not as PR there? Because breaking?

**Comment by Zefau** [comment]
It is a new adapter completely written from the scratch. It retrieves all elements from the Hue Bridge, including all scenes, rules, etc.

image

**Comment by Apollon77** [comment]
finalizing js.controller 2.0 took longer ... will review tomorrow hopefully. sorry

**Comment by Apollon77** [comment]
Welcome in the repo :-) ... when you have added Bluefox to npm ;-)

[E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.hue-extended"

see https://www.npmjs.com/package/iobroker.hue-extended

**Comment by Zefau** [comment]
Done.

**Pull request merged**
