### PR TITLE
Add gree-hvac to latest

### PR DESCRIPTION
**Pull request by mcm1957**

### CODE REVIEW

**Comment by mcm1957** [comment]
@XHunter74 
This PR replaces https://github.com/ioBroker/ioBroker.repositories/pull/3511 as far as it relates to addition of new adapter gree-hvac

Please watch this PR to get informed about further steps.

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

reminder 22.4.2024

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] errors reported by adapter checker must be fixed

  Especially error  ```[E201] Bluefox was not found in the collaborators on NPM!.``` must be fixed. If you just invited Bluefox its ignore to wait for his reaction. Please state that the invitation has been sent in this case.  If invite at commandline does not work please do
  - log into npmjs.com
  - select your adapter
  - select settings
  - goto "invite maintainer", insert "bluefox" and press invite
  
- [ ] package.json should contain keywords [non blocking]

   I would suggest to add at least gree to keywords.

- [ ] package.json should require up to date js-controller and admin version

  New adapters should request js-controller 5 and admin 6 as minimum if there are no strong reason to support (and test) older releases. So please add / adapt at io-package.json:

  ```
        "dependencies": [
            {
                "js-controller": ">=5.0.19"
            }
        ],
        "globalDependencies": [
            {
                "admin": ">=6.13.16"
            }
        ]
  ```
- [ ] please verify that all dependencies are up to date

  Some dependencies are outdated. Please update to current releases if no special reason to keep an older version exists.

  Minimum required cenzral components:
  - "@iobroker/adapter-core": "^3.1.4" 
  - "@iobroker/testing": "^4.1.3"

- [ ] Use table to configure devices
  
  Your adapter seems to support multiple devices. Using a textfield to enter a semicolon seperated list of ip addresses is at least unusal. Please consider changing the config to use a table to store  utiple devices (tables are supported by jsconConfig.

  In addition the connection code looks like you are sending broadcasts to a network. In this case a string with very few network ids would be ok too. But wouldn't it be better to name the paramter network instead of device in this case? And to default it to the local network if not specified?

- [ ] enhance error logging

  You use sentry to register many (or most) erro situations. Besides the fact that this might create a big load if the adapter is successfull all errors must be logged to logfile too. Users do not see sentry events. The fact that a problem occured must be visible at user logfiles to. So please log all error events as this.log.xxx too. Use logging as error / warning or debug as approbiate to the location of the error.

- [ ] avoid this.terminate

  Please avoid to use this.terminate as this.terminate bypasses onUnload code. Use this.stop instead. As this.stop currently does not support logging a text (will be enhances with js-controller 6) use this.log.err to log the approbiate text before terminating.

- [ ] invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```, i.e. by using the following snippet:

  ```
  function name2id(pName) {
      return (pName || '').replace(adapter.FORBIDDEN_CHARS, '_');
  }
  ```
  
  You derive the stateId from your device Id which in turn is delivered from an external system. So please filter out FORBIDDEN_CHARS and in addtion dots. As an optimum an id should consist only of a-zA-Z0-9 and _, but thats not enforced. Dots must only be used to seperate between folder/device objects and states and spaces should be avoided at all as several other adpaters / vis have trobles processing ids containing spaces.

- [ ] states must not have children

  see https://github.com/XHunter74/ioBroker.gree-hvac/blob/4d84c1070471723abfca0bc42447e068ac67bfdb/main.js#L108
  
  you create a base object of type statewith id 'deviceId'. Besides the fact that this id must be filtered to contain only valid characters this object of type state MJST not have children. But you create detailled stats named ${deviceId}.${property.name}, This must be changed,

  I suggest to create an object oftype 'device' with id devideId. This can und should be the parent for all ${deviceId}.${property.name}. In addition create astate named i.e. ${deviceId}.deviceInfo and store the stringified information of the device there. If you need the infomation only internally at the adapter you could store it at native area of the device object too.

  In addition roles etc. must be fixed (see below)
 
- [ ] consider subscribing to all states of your adapter.

  Consider to use one subscribe ('*') instead of subscribiung to each device seperatly. Every subscribe requires the js-controlelr to process one more lexical expression for every setState in the system. Reducing the number of subscribes could reduce the load at js-controller while this adapter will process all writes anyway. 

- [ ] onStateChange handler

   I suggest to check state to be valid as it might be null if the state is deleted. This would cause a crash now.

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whnever a dedicated role exists.

  Some incorrect roles:
  - indicator must be type boolean and readonly
  - variable is no valid role

- [ ]  specify units where possible

  Please specify usinits where possible. As you already have a list of known states, this should be possible at least for most states using a unit.

- [ ] Consider shorting names

  Names should name state. You use ruther long names providing a description, This info will be truncytes at most admin views. I would suggest to move the decriptive part into the description attribute as this data is written condensed and is using less space. 

  This is only a suggestion and not blocking.

- [ ] evaluate usage of common.state

  https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md#attributes-for-specific-object-types

  You probably would like to use common.state to add textual representation for some numeric enum values (like on/off/auto). This text would be shown at admin object view and could be comfortable for users.

  This is only a suggestion and not blocking.

- [ ] check german translations
  
  "Polierintervall in Millisekunden"
  
- [ ] consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- [ ] Review sendRequest routine

  see https://github.com/XHunter74/ioBroker.gree-hvac/blob/4d84c1070471723abfca0bc42447e068ac67bfdb/lib/connection.js#L56

  I think tehre are at least 2 problem areas:

  - If you leave the message routine by one of the return statements the promise is not solved. Someone waiting at the promise will do forever.

  - I do not see any timeout handling. If the decioe does not respond for any reason no socket.on('message') will occure. This will again let the promise unresolved.

- [ ] Consider replacing setInterval by setTimeout

  In generell you might consider replacing setInterval by setTimeout. This would ensure that the next cycle is started only after completing the previous cycle, i.e.

  ```  
  async readData (..) {
    processIt();
    this.setTimeout( readDate, interval);
  }
  ```
  When using setInterval you must ensure that teh request will not queue up as this could consume more an more meory and crash the complet iioBroker system finally.

- [ ] add callback at onMessage

  Please consider to readd callback at onMessage even if you do not want to send some feedback. If no feedback is called the sender is required to wait until a timeout occures. This timeout is cancelled if the callback is called. So the callback is optional - but to minimize waiting time for sending oart its good practise to use the callback.

- [ ] indicating unreachable devices

  I did not see an indication whether a device is reachable. The adapter should signal the user if a device is reachable / communicating or not. I suggest to add such a state and to log an warnign if a device becomes unreachable.

- [ ] readd info.connection state

  Adapetrs communicating with a device normally utilize the standard property info.connection. Setting this property controls the appeatrance of the instance at admin (green or yellow). So please consider setting this property to true if all devices are reachable / working and to false if one device fails.

- [ ] check and adapt testing
  
  Standard iobroker testing is required but seems to be missing. Please add standard setup ./gizthub/workflows/test-and-release.yml available at https://github.com/ioBroker/ioBroker.example/tree/master/JavaScript. This refers to workflow test-and.release and to testscripts at test directory.

  Of course ist ok and even desired if you add additional tests. Please use a seperate worflow for this to make routine checks during repository releases more effizient and easy.
  
- [ ] adapt testing to supported node releases

  Tests for node 18 are mandatory as this is the recommended node version. 
  Tests for node 20 are mandatory unless you already know incompatibilities which cannot be fixed immidiatly. In this case please create a issue stating the problem and fix as soon as possible.
  
  So the recommended testmatrix is [18.x, 20.x] depending on engines requirments setting at package.json 

  Tests must be performed at all supported platforms (linux, windows, mac) unless special hardware or software restrictions prohibit this.

- [ ] github dependabot support seems to be missing
  
  It looks like you did not yet setup dependabot support; at least .github/dependaboit.yml is missing.
  
  Please consider setting up dependabot support (and to ease life the workflow auto-merge.yml). Dependabot will ensure that your adapter uses the most recent versions of external packages and avoids problem due to outdted base libraries. Dependabit provides PRs at you repository to update the dependencies. Depending on you setting, especially on auto-merge.yml configuration no or only minor revisions will be outmatically merged into you main branch. All major revisions msiut (ans should) be reviewed by you. 
  
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by XHunter74** [comment]
"Use table to configure devices

Your adapter seems to support multiple devices. Using a textfield to enter a semicolon seperated list of ip addresses is at least unusal. Please consider changing the config to use a table to store utiple devices (tables are supported by jsconConfig."

@mcm1957 could you please provide some documentation about jsconConfig?

**Comment by mcm1957** [comment]
jsonConfig Schema
https://github.com/ioBroker/ioBroker.admin/blob/master/packages/jsonConfig/SCHEMA.md

Please note that #include is brand new and should currently be avoided as the admin version needed is not yet released to stable.

https://github.com/mcm4iob/ioBroker.jsonconfig-demo

A demo adapter showing many eleme ts ob jsonConfig but far not all.

**Comment by XHunter74** [comment]
@mcm1957 , seems I processed all your comments. Please re-check the adapter.

**Comment by XHunter74** [comment]
@mcm1957 ,Received this error:  [E025] Do not include "iobroker.js-controller" as dependency!
So I have a question: should I include it or not?

**Comment by XHunter74** [comment]
@mcm1957 could you please review the adapter?

**Comment by mcm1957** [comment]
REVIEW per 22.5.  (work in progress)

- [ ] errors reported by adapter checker must be fixed

  Especially error  ```[E201] Bluefox was not found in the collaborators on NPM!.``` must be fixed. If you just invited Bluefox its ignore to wait for his reaction. Please state that the invitation has been sent in this case.  If invite at commandline does not work please do
  - log into npmjs.com
  - select your adapter
  - select settings
  - goto "invite maintainer", insert "bluefox" and press invite
  
- [ ] package.json should contain keywords [non blocking]

   I would suggest to add at least gree to keywords.

- [ ] package.json should require up to date js-controller and admin version

  New adapters should request js-controller 5 and admin 6 as minimum if there are no strong reason to support (and test) older releases. So please add / adapt at io-package.json:

  ```
        "dependencies": [
            {
                "js-controller": ">=5.0.19"
            }
        ],
        "globalDependencies": [
            {
                "admin": ">=6.13.16"
            }
        ]
  ```
- [ ] please verify that all dependencies are up to date

  Some dependencies are outdated. Please update to current releases if no special reason to keep an older version exists.

  Minimum required cenzral components:
  - "@iobroker/adapter-core": "^3.1.4" 
  - "@iobroker/testing": "^4.1.3"

- [ ] Use table to configure devices
  
  Your adapter seems to support multiple devices. Using a textfield to enter a semicolon seperated list of ip addresses is at least unusal. Please consider changing the config to use a table to store  utiple devices (tables are supported by jsconConfig.

  In addition the connection code looks like you are sending broadcasts to a network. In this case a string with very few network ids would be ok too. But wouldn't it be better to name the paramter network instead of device in this case? And to default it to the local network if not specified?

- [ ] enhance error logging

  You use sentry to register many (or most) erro situations. Besides the fact that this might create a big load if the adapter is successfull all errors must be logged to logfile too. Users do not see sentry events. The fact that a problem occured must be visible at user logfiles to. So please log all error events as this.log.xxx too. Use logging as error / warning or debug as approbiate to the location of the error.

- [ ] avoid this.terminate

  Please avoid to use this.terminate as this.terminate bypasses onUnload code. Use this.stop instead. As this.stop currently does not support logging a text (will be enhances with js-controller 6) use this.log.err to log the approbiate text before terminating.

- [ ] invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```, i.e. by using the following snippet:

  ```
  function name2id(pName) {
      return (pName || '').replace(adapter.FORBIDDEN_CHARS, '_');
  }
  ```
  
  You derive the stateId from your device Id which in turn is delivered from an external system. So please filter out FORBIDDEN_CHARS and in addtion dots. As an optimum an id should consist only of a-zA-Z0-9 and _, but thats not enforced. Dots must only be used to seperate between folder/device objects and states and spaces should be avoided at all as several other adpaters / vis have trobles processing ids containing spaces.

- [ ] states must not have children

  see https://github.com/XHunter74/ioBroker.gree-hvac/blob/4d84c1070471723abfca0bc42447e068ac67bfdb/main.js#L108
  
  you create a base object of type statewith id 'deviceId'. Besides the fact that this id must be filtered to contain only valid characters this object of type state MJST not have children. But you create detailled stats named ${deviceId}.${property.name}, This must be changed,

  I suggest to create an object oftype 'device' with id devideId. This can und should be the parent for all ${deviceId}.${property.name}. In addition create astate named i.e. ${deviceId}.deviceInfo and store the stringified information of the device there. If you need the infomation only internally at the adapter you could store it at native area of the device object too.

  In addition roles etc. must be fixed (see below)
 
- [ ] consider subscribing to all states of your adapter.

  Consider to use one subscribe ('*') instead of subscribiung to each device seperatly. Every subscribe requires the js-controlelr to process one more lexical expression for every setState in the system. Reducing the number of subscribes could reduce the load at js-controller while this adapter will process all writes anyway. 

- [ ] onStateChange handler

   I suggest to check state to be valid as it might be null if the state is deleted. This would cause a crash now.

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whnever a dedicated role exists.

  Some incorrect roles:
  - indicator must be type boolean and readonly
  - variable is no valid role

- [ ]  specify units where possible

  Please specify usinits where possible. As you already have a list of known states, this should be possible at least for most states using a unit.

- [ ] Consider shorting names

  Names should name state. You use ruther long names providing a description, This info will be truncytes at most admin views. I would suggest to move the decriptive part into the description attribute as this data is written condensed and is using less space. 

  This is only a suggestion and not blocking.

- [ ] evaluate usage of common.state

  https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md#attributes-for-specific-object-types

  You probably would like to use common.state to add textual representation for some numeric enum values (like on/off/auto). This text would be shown at admin object view and could be comfortable for users.

  This is only a suggestion and not blocking.

- [ ] check german translations
  
  "Polierintervall in Millisekunden"
  
- [ ] consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- [ ] Review sendRequest routine

  see https://github.com/XHunter74/ioBroker.gree-hvac/blob/4d84c1070471723abfca0bc42447e068ac67bfdb/lib/connection.js#L56

  I think tehre are at least 2 problem areas:

  - If you leave the message routine by one of the return statements the promise is not solved. Someone waiting at the promise will do forever.

  - I do not see any timeout handling. If the decioe does not respond for any reason no socket.on('message') will occure. This will again let the promise unresolved.

- [ ] Consider replacing setInterval by setTimeout

  In generell you might consider replacing setInterval by setTimeout. This would ensure that the next cycle is started only after completing the previous cycle, i.e.

  ```  
  async readData (..) {
    processIt();
    this.setTimeout( readDate, interval);
  }
  ```
  When using setInterval you must ensure that teh request will not queue up as this could consume more an more meory and crash the complet iioBroker system finally.

- [ ] indicating unreachable devices

  I did not see an indication whether a device is reachable. The adapter should signal the user if a device is reachable / communicating or not. I suggest to add such a state and to log an warnign if a device becomes unreachable.

- [ ] readd info.connection state

  Adapetrs communicating with a device normally utilize the standard property info.connection. Setting this property controls the appeatrance of the instance at admin (green or yellow). So please consider setting this property to true if all devices are reachable / working and to false if one device fails.

- [ ] check and adapt testing
  
  Standard iobroker testing is required but seems to be missing. Please add standard setup ./gizthub/workflows/test-and-release.yml available at https://github.com/ioBroker/ioBroker.example/tree/master/JavaScript. This refers to workflow test-and.release and to testscripts at test directory.

  Of course ist ok and even desired if you add additional tests. Please use a seperate worflow for this to make routine checks during repository releases more effizient and easy.
  
- [ ] adapt testing to supported node releases

  Tests for node 18 are mandatory as this is the recommended node version. 
  Tests for node 20 are mandatory unless you already know incompatibilities which cannot be fixed immidiatly. In this case please create a issue stating the problem and fix as soon as possible.
  
  So the recommended testmatrix is [18.x, 20.x] depending on engines requirments setting at package.json 

  Tests must be performed at all supported platforms (linux, windows, mac) unless special hardware or software restrictions prohibit this.

- [ ] github dependabot support seems to be missing
  
  It looks like you did not yet setup dependabot support; at least .github/dependaboit.yml is missing.
  
  Please consider setting up dependabot support (and to ease life the workflow auto-merge.yml). Dependabot will ensure that your adapter uses the most recent versions of external packages and avoids problem due to outdted base libraries. Dependabit provides PRs at you repository to update the dependencies. Depending on you setting, especially on auto-merge.yml configuration no or only minor revisions will be outmatically merged into you main branch. All major revisions msiut (ans should) be reviewed by you.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@XHunter74 
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too

**Pull request merged**
