### PR TITLE
Add myuplink to latest

### PR DESCRIPTION
**Pull request by sebilm**
Tested by user (and me): https://github.com/sebilm/ioBroker.myuplink/issues/1

### CODE REVIEW

**Comment by sebilm** [comment]
RE-CHECK!

**Comment by sebilm** [comment]
RE-CHECK!

**Comment by sebilm** [comment]
Is anything else needed from me here?

**Comment by mcm1957** [comment]
> Is anything else needed from me here?

No - not at the moment
PR is waiting for review currently.

**Comment by sebilm** [comment]
Ok, thanks

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by sebilm** [comment]
Das macht mich jetzt schon etwas sprachlos. Das liegt der Pullrequest jetzt so lange rum, dass sich das Jahr inzwischen geändert hat und deshalb steht er jetzt auf musst fix. Man, man, man. Sorry, aber das musste ich jetzt mal los werden.

**Comment by sebilm** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] sensitive information should not be logged into logfile

  To avoid publishing sensitive information when forwarding logs, those information should never be written into the logs but either omitted or at least partly masked so that the information cannot be misused. This relates at least to usernames, passwords, uniqui (user assigned) keys and tokens. In addition personal information like name, address, gegraphical coordinagtes should not be logged too.

  see https://github.com/sebilm/ioBroker.myuplink/blob/268730d58b78743413b56af6d639d1b8160df4c3/src/authRepository.ts#L206

- [ ] invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```, i.e. by using the following snippet:
```
function name2id(pName) {
    return (pName || '').replace(adapter.FORBIDDEN_CHARS, '_');
}
```
  You are creating objects at routine https://github.com/sebilm/ioBroker.myuplink/blob/268730d58b78743413b56af6d639d1b8160df4c3/src/main.ts#L295

  Filtering all illegal charactes seems to be missing.
  Special handling of dots seems to be missing. If id of n object contains a dot ALL upper elements must be created explizitly as device, channel or folder objects.

  Please take special care at ids built from data entered by users or retruned by external sources. Do not assume anything. Filtering as jsonConfig is NOT sufficient as data could be entered at system objects too. Filter / correct all ids within code whenever creating oir accessing objects to avoid errors / crashes during runtime.

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whenever a dedicated role exists.

  
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
> Das macht mich jetzt schon etwas sprachlos. Das liegt der Pullrequest jetzt so lange rum, dass sich das Jahr inzwischen geändert hat und deshalb steht er jetzt auf musst fix. Man, man, man. Sorry, aber das musste ich jetzt mal los werden.

Nö - das Flag war zu dem Zeitpunkt schon entfernt - da z.Z. irrelevant.
Trotzdem DANKE fürs anpassen.

image

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] sensitive information should not be logged into logfile

  To avoid publishing sensitive information when forwarding logs, those information should never be written into the logs but either omitted or at least partly masked so that the information cannot be misused. This relates at least to usernames, passwords, uniqui (user assigned) keys and tokens. In addition personal information like name, address, gegraphical coordinagtes should not be logged too.

  see https://github.com/sebilm/ioBroker.myuplink/blob/268730d58b78743413b56af6d639d1b8160df4c3/src/authRepository.ts#L206

- [ ] invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```, i.e. by using the following snippet:
```
function name2id(pName) {
    return (pName || '').replace(adapter.FORBIDDEN_CHARS, '_');
}
```
  You are creating objects at routine https://github.com/sebilm/ioBroker.myuplink/blob/268730d58b78743413b56af6d639d1b8160df4c3/src/main.ts#L295

  Filtering all illegal charactes seems to be missing.
  Special handling of dots seems to be missing. If id of n object contains a dot ALL upper elements must be created explizitly as device, channel or folder objects.

  Please take special care at ids built from data entered by users or retruned by external sources. Do not assume anything. Filtering as jsonConfig is NOT sufficient as data could be entered at system objects too. Filter / correct all ids within code whenever creating oir accessing objects to avoid errors / crashes during runtime.

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whenever a dedicated role exists.

  
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
reminder 08.01.2024

**Comment by sebilm** [comment]
Thank you for reviewing my code. I have made the desired changes.

**Comment by mcm1957** [comment]
reminder 15.1.2024

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, ist OK to continue using this topic too.

**Pull request merged**
