### PR TITLE
Add envertech-pv to latest

### PR DESCRIPTION
**Pull request by mcm1957**
Please add my adapter ioBroker.envertech-pv to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
Link to repository: https://github.com/iobroker-community-adapters/ioBroker.envertech-pv

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
@Apollon @GermanBluefox 
Any idea why automated adapter checker reports "no changes adapters found"?
Some as with https://github.com/ioBroker/ioBroker.repositories/pull/2187

Could this be caused by https://github.com/ioBroker/ioBroker.repositories/pull/2165 where some checks are waiting approval to start?

**Pull request closed without merging**
