### PR TITLE
Update sources-dist-stable.json

### PR DESCRIPTION
**Pull request by sbormann**
iQontrol 0.2.20 - stable

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.iqontrol](https://github.com/sbormann/ioBroker.iqontrol)
[Downloads](https://www.npmjs.com/package/iobroker.iqontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iqontrol/)

- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/sbormann/ioBroker.iqontrol/blob/master/iob_npm.done)" found in repo! Please add it to .gitignore
- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/sbormann/ioBroker.iqontrol/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations


*Add comment "RE-CHECK!" to start check anew*

**Comment by sbormann** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.iqontrol](https://github.com/sbormann/ioBroker.iqontrol)
[Downloads](https://www.npmjs.com/package/iobroker.iqontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iqontrol/)

- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/sbormann/ioBroker.iqontrol/blob/master/iob_npm.done)" found in repo! Please add it to .gitignore
- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/sbormann/ioBroker.iqontrol/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
Please fix https://github.com/sbormann/ioBroker.iqontrol/issues/124

**Comment by Apollon77** [comment]
@sbormann how to continue? want update the version for stable?

**Comment by sbormann** [comment]
At the moment i try to fix all known issues (only a few left). Then a new request for stable version will follow in a few days. Therefore im closing this. Many thanks and greeings!

**Pull request closed without merging**
