### PR TITLE
Update solarmanpv to 0.4.1

### PR DESCRIPTION
**Pull request by raschy**
Please update my adapter ioBroker.solarmanpv to version 0.4.1.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.solarmanpv](https://github.com/raschy/ioBroker.solarmanpv)
[Downloads](https://www.npmjs.com/package/iobroker.solarmanpv) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.solarmanpv/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
0.4.1 released 27.05.23

**Comment by mcm1957** [comment]
no serious issues,
2 weeks at latest 
lets go ...

**Pull request merged**
