### PR TITLE
signal-cmb

### PR DESCRIPTION
**Pull request by derAlff**
https://forum.iobroker.net/topic/51645/test-adapter-signal-cmb-signal-messenger

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.signal-cmb](https://github.com/necotec/ioBroker.signal-cmb)
[Downloads](https://www.npmjs.com/package/iobroker.signal-cmb) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.signal-cmb/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "signal-cmb" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by necotec** [comment]
Oops. Added beta and stable in one PR 🙈

Is it a "must have" to do this in separate PRs, or is it ok?

**Comment by Apollon77** [comment]
Hi,

some review comments:
* Please recreate this PR Without changing the package-lock!! Thank you
* Please translate desc in io-package https://github.com/necotec/ioBroker.signal-cmb/blob/master/io-package.json#L104-L115
* I think https://github.com/necotec/ioBroker.signal-cmb/blob/master/io-package.json#L135 is more cloud or? :-)
* The native part in io-package needs to contain the default values of the fields the user can configure in admin. https://github.com/necotec/ioBroker.signal-cmb/blob/master/io-package.json#L146-L149

After these changes we should be fine

**Comment by necotec** [comment]
Created new PR

**Comment by necotec** [comment]
Created new PR

**Comment by Apollon77** [comment]
new PR missing?

**Comment by necotec** [comment]
New PR: https://github.com/ioBroker/ioBroker.repositories/pull/1673

**Pull request closed without merging**
