### PR TITLE
Add new adapter evcc

### PR DESCRIPTION
**Pull request by Newan**

### CODE REVIEW

**Comment by Newan** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.evcc](https://github.com/Newan/ioBroker.evcc)
[Downloads](https://www.npmjs.com/package/iobroker.evcc) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.evcc/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "evcc" in latest repository

### [ioBroker.easee](https://github.com/Newan/ioBroker.easee)
[Downloads](https://www.npmjs.com/package/iobroker.easee) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.easee/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 Jens Nachtigal <info@newan.de>" at the end of [README.md](https://github.com/Newan/ioBroker.easee/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Jens Nachtigal <info@newan.de>" at the start of LICENSE
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Newan/ioBroker.easee/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by Newan** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.easee](https://github.com/Newan/ioBroker.easee)
[Downloads](https://www.npmjs.com/package/iobroker.easee) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.easee/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 Jens Nachtigal <info@newan.de>" at the end of [README.md](https://github.com/Newan/ioBroker.easee/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Jens Nachtigal <info@newan.de>" at the start of LICENSE
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Newan/ioBroker.easee/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.evcc](https://github.com/Newan/ioBroker.evcc)
[Downloads](https://www.npmjs.com/package/iobroker.evcc) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.evcc/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "evcc" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request closed without merging**
