### PR TITLE
added adapter for wiffi-wz

### PR DESCRIPTION
**Pull request by t4qjXH8N**
I added my first adapter for the wiffi-wz, i hope everything is fine.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Please fix roles before merge..

**Comment by Apollon77** [comment]
I would go with hardware because it is mainly custom wiffy hardware

**Comment by t4qjXH8N** [comment]
I agree.

**Comment by Apollon77** [comment]
Please check the following:
- really add testing in travis/appveyor (maybe you missed the package.json entry for the test scipt? testing results (yes should be checked too) show "no test specified" :-) https://travis-ci.org/t4qjXH8N/ioBroker.wiffi-wz/jobs/416110237
- full translations would be awesome ... you can use http://iobroker.net:3000/ for that :-)
- add common.license to io-package.json too
- maybe you want to make sure the full set of forbidden characters is sanitized? Or can this not happen? (Regex: /[\]\[*,;'"`<>\\\s?]/g)

And one code comment: I think it is helpful for debugging to also catch the error event from the server and/or socket if available and log it ...

**Comment by t4qjXH8N** [comment]
Thank you, I am going to check this.

**Comment by t4qjXH8N** [comment]
What do you mean by sanitizing forbidden characters? Do you mean the buffer should be checked for these characters? If so, sanitizing should not be necessary,

**Comment by Apollon77** [comment]
it is about the object ids ... you have one place where you replace characters by udnerscores ... maybe you want to enhance that replacing to cover all "forbidden characters for object IDs"

**Comment by t4qjXH8N** [comment]
Could you please have a look at it? I hope I got everything right.

**Comment by Apollon77** [comment]
looks great! Welcome in the repo :)

Next step would be a forum tread to get other people using it and testing it ... and when it is stable please commit the PR to be moved to stable repo too.

**Pull request merged**
