### PR TITLE
Add vbus-gw to latest

### PR DESCRIPTION
**Pull request by pdbjjens**
Please add my adapter ioBroker.vbus-gw to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

You will find the results of the review and evntually issues / suggestings as a communt to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

mcm1957

**Comment by mcm1957** [comment]
reminder 7.2.2024

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.
And SORRY for the very long processing time.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] sensitive information should not be logged into logfile

  To avoid publishing sensitive information when forwarding logs, those information should never be written into the logs but either omitted or at least partly masked so that the information cannot be misused. This relates at least to usernames, passwords, uniqui (user assigned) keys and tokens. In addition personal information like name, address, gegraphical coordinagtes should not be logged too.

https://github.com/pdbjjens/ioBroker.vbus-gw/blob/f1e5e67f1468a22731a00d20f24cd88b8f6a1eb4/main.js#L63

I suggest to remove thos logging line. Logging the password makes storing the password protected useless.

https://github.com/pdbjjens/ioBroker.vbus-gw/blob/f1e5e67f1468a22731a00d20f24cd88b8f6a1eb4/main.js#L171

Here the password should be masked or removed too.
  
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
reminder 27.02.2024

**Comment by pdbjjens** [comment]
@mcm1957 
Thank you for the review and your valuable suggestions. 
I have removed all password logging since it was mainly a remnant of the development/debugging phase. 
I have released a patch v0.0.7 for your re-review.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Pull request merged**
