### PR TITLE
Update reolink to 1.1.2

### PR DESCRIPTION
**Pull request by mcm1957**
https://github.com/aendue/ioBroker.reolink/issues/107

### CODE REVIEW

**Comment by mcm1957** [comment]
@andue
Testing at node.js 22 is missing. Please add.
https://github.com/aendue/ioBroker.reolink/pull/117

**Comment by andue** [comment]
> @andue Testing at node.js 22 is missing. Please add. [aendue/ioBroker.reolink#117](https://github.com/aendue/ioBroker.reolink/pull/117)
> 
> reminder 29.10.2024

@mcm1957 think you marked a wrong andy ;)

**Comment by mcm1957** [comment]
thanks

@aendue

**Comment by mcm1957** [comment]
replaced by #4208

**Pull request closed without merging**
