### PR TITLE
Upgrade LinkTap to 0.3.0

### PR DESCRIPTION
**Pull request by Smart-Gang**
Support for new device types and ioBroker dependency (admin) update

### CODE REVIEW

**Comment by mcm1957** [comment]
2.0.3 created 9.9.2023

**Comment by mcm1957** [comment]
**just a feedback for next releases:**

```Added support for new devices``` sounds like new functionality. Thus increasing the minor version would have been correct.

The rules for versioning are:
- increase major if Breaking changes are introduced. This may include new features and bugfixes. 
- increase minor if  a new feature was added without breaking things. This may include bugfixes.
- increase patch if only a bug was fixed without adding new functionality.

**Comment by mcm1957** [comment]
@Smart-Gang 

Your adapter https://github.com/Smart-Gang/ioBroker.linktap does not use standard iobroker testing.

Please see requirements https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository

```
Adapter needs to have at least Adapter basic testing (installing, running) using GitHub actions. More information in Forum from apollon77 (Just take from other adapters the samples)
```

You may copy the ```test-and-release.yml``` workflow from the example adaptzer or newly created adapter. If you need help, please let uas know.

**Comment by mcm1957** [comment]
I've created a PR to aid in updateing / adding standard tests.
Please merge and check that tests pass.

**After merging and checking, please drop a comment to let us continue release management.**

**NOTE: If there is no reaction within 14 days I will close this PR.**

**Comment by mcm1957** [comment]
Thanks for your work.
Github test feedback still shows a failure. This is not caused by the standard github tests - they are ok - but by appvayour integration:

image

If you do not use appveyor I suggest to remove it from your test configuration. I was told that this canbe achived by
- open settings poage of github repository
- go to webhooks
- remove appveyor webhook

Of course its ok to fix the appveyor setup and to use it if you prefer. I'm sorry but I cannot aid with this testing environment. The goal should be to get a green checkmark as all tests pass.

mcm1957

P.S: appveyor issue is NOT blocking as I can check which tests fail manually - but it should be fixed in future to give you a quick feedback for durtehr work at the adapter. THANK YOU once again for your effort.

**Comment by mcm1957** [comment]
0.3.0 created 18.10.2023
manual adapter check OK

wait for minimum time at latest

**Comment by Smart-Gang** [comment]
> Thanks for your work. Github test feedback still shows a failure. This is not caused by the standard github tests - they are ok - but by appvayour integration:
> 
> image
> 
> If you do not use appveyor I suggest to remove it from your test configuration. I was told that this canbe achived by
> 
> * open settings poage of github repository
> * go to webhooks
> * remove appveyor webhook
> 
> Of course its ok to fix the appveyor setup and to use it if you prefer. I'm sorry but I cannot aid with this testing environment. The goal should be to get a green checkmark as all tests pass.
> 
> mcm1957
> 
> P.S: appveyor issue is NOT blocking as I can check which tests fail manually - but it should be fixed in future to give you a quick feedback for durtehr work at the adapter. THANK YOU once again for your effort.

Thanks for the info, I stopped using the appveyor and have now removed the webhook as well. 

Now all tests should be green.

Thanks for the support.

**Comment by mcm1957** [comment]
0.3.0 created 18.10.2023

**Pull request merged**
