### PR TITLE
Update sources-dist-stable.json

### PR DESCRIPTION
**Pull request by nisiode**
Add iogo in version v0.1.0

### CODE REVIEW

**Comment by Apollon77** [comment]
Please add current data as published here

**Comment by nisiode** [comment]
Changed "published" to current timestamp...
Where is this data being used for?

**Comment by Apollon77** [comment]
Statistic stuff and maybe later to show „new“ tags in admin or such

**Comment by GermanBluefox** [comment]
> Statistic stuff and maybe later to show „new“ tags in admin or such

Yet used. 
image

**Pull request merged**
