### PR TITLE
Updated laRenamed and added adapterstest adapters renamed

### PR DESCRIPTION
**Pull request by frankjoke**
Added bmw and broadlink2-Adapters and changed names where adapters have been renamed to ioBroker

### CODE REVIEW

**Comment by Apollon77** [comment]
Please also add to the second file when you add in stable. And please check that sort order is correct ... broadlink2 should come after broadlink, or ?! ;-))

**Comment by frankjoke** [comment]
I updated both files and put adapters in right order!

**Comment by Apollon77** [comment]
But now we have a conflict. COuld you please pull and merge and push again?! Thank you!

**Comment by frankjoke** [comment]
Ok, I made the changes without the BMW-adapter in the latest because the ble-adapter was added and the change conflicts with it. If you did the merge I will add it in a next pull request.

**Pull request merged**
