### PR TITLE
uv-protect added

### PR DESCRIPTION
**Pull request by simatec**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.uv-protect](https://github.com/simatec/ioBroker.uv-protect)
[Downloads](https://www.npmjs.com/package/iobroker.uv-protect) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.uv-protect/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/simatec/ioBroker.uv-protect/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/simatec/ioBroker.uv-protect/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.uv-protect)!. Please execute in adapter directory: `npm owner add bluefox iobroker.uv-protect`
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/simatec/ioBroker.uv-protect", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/simatec/ioBroker.uv-protect", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "uv-protect" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by simatec** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.uv-protect](https://github.com/simatec/ioBroker.uv-protect)
[Downloads](https://www.npmjs.com/package/iobroker.uv-protect) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.uv-protect/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "uv-protect" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by simatec** [comment]
Fixed ...

**Comment by simatec** [comment]
@Apollon77 push ;-)

**Comment by Apollon77** [comment]
My review comments:
* should the apiKey be stored encrypted?
* a method should be async to await it :-) https://github.com/simatec/ioBroker.uv-protect/blob/master/main.js#L45
* if all your stiff is awaited correctly including setState then this should not be needed ! https://github.com/simatec/ioBroker.uv-protect/blob/master/main.js#L210 ... try without :-)

Rest is fine ... please check these both

**Comment by simatec** [comment]
@Apollon77 
Thanks for your feedback.

I fixed all the bugs in version 0.2.2

**Comment by simatec** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.uv-protect](https://github.com/simatec/ioBroker.uv-protect)
[Downloads](https://www.npmjs.com/package/iobroker.uv-protect) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.uv-protect/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "uv-protect" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by simatec** [comment]
@Apollon77 ping ;-)

**Comment by Apollon77** [comment]
Now you set one variable async https://github.com/simatec/ioBroker.uv-protect/blob/eebe8305e5606cdee5b67ba1e295455a95048b9b/main.js#L46-L48 ...why not also await and async method here and bring it in flow? Now you hae a chance that the first run alsoways is "de" (because language default) and second run is then with correct language

Want to fix it before?

**Comment by Apollon77** [comment]
Ok I merge, but I think you want to fix that

**Comment by simatec** [comment]
@Apollon77 Thanks for your feedback. I tried to fix everything in version 0.3.2

**Comment by Apollon77** [comment]
* https://github.com/simatec/ioBroker.uv-protect/blob/eebe8305e5606cdee5b67ba1e295455a95048b9b/main.js#L54 await/callback mixture

**Pull request merged**
