### PR TITLE
added e3dc-rscp

### PR DESCRIPTION
**Pull request by git-kick**
New adapter, see [Tester Forum](https://forum.iobroker.net/topic/49217/test-adapter-e3dc-rscp-v0-0-x-github)

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.e3dc-rscp](https://github.com/git-kick/ioBroker.e3dc-rscp)
[Downloads](https://www.npmjs.com/package/iobroker.e3dc-rscp) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.e3dc-rscp/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "e3dc-rscp" in latest repository

### [ioBroker.froeling](https://github.com/TA2k/ioBroker.froeling)
[Downloads](https://www.npmjs.com/package/iobroker.froeling) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.froeling/)

:thumbsup: No errors found

### [ioBroker.lg-thinq](https://github.com/TA2k/ioBroker.lg-thinq)
[Downloads](https://www.npmjs.com/package/iobroker.lg-thinq) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-thinq/)

:thumbsup: No errors found

### [ioBroker.openhab](https://github.com/iobroker-community-adapters/ioBroker.openhab)
[Downloads](https://www.npmjs.com/package/iobroker.openhab) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.openhab/)

- [ ] :heavy_exclamation_mark: [E104] No common.titleLang found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.openhab) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2017-2022 bluefox <dogafox@gmail.com>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2017-2022 bluefox <dogafox@gmail.com>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.rainbird](https://github.com/StrathCole/ioBroker.rainbird)
[Downloads](https://www.npmjs.com/package/iobroker.rainbird) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.rainbird/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/StrathCole/ioBroker.rainbird/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/StrathCole/ioBroker.rainbird/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 Marius Burkard <m.burkard@pixcept.de>" at the end of [README.md](https://github.com/StrathCole/ioBroker.rainbird/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Marius Burkard <m.burkard@pixcept.de>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by git-kick** [comment]
Hi, I am trying to bring in `e3dc-rscp`.
I see the message `👀 [W400] Cannot find "e3dc-rscp" in latest repository`
Am I right that this is not an error because `e3dc-rscp` is new and therefore not in latest repo so far?

**Comment by ldittmar81** [comment]
> Hi, I am trying to bring in `e3dc-rscp`. I see the message `👀 [W400] Cannot find "e3dc-rscp" in latest repository` Am I right that this is not an error because `e3dc-rscp` is new and therefore not in latest repo so far?
You're right. There are no errors automatically found.

**Comment by ldittmar81** [comment]
Close https://github.com/ioBroker/AdapterRequests/issues/676 after review

**Comment by Apollon77** [comment]
hi,

here some review comments:
* (optional) If you like you can remove all the encrypt/decrypt stuff and use the automatic solution ... see best practices in Readme of this repo for infos. YOu just need to add an "encrptedNative" and "protectedNative" sections to io-package and add a propoer admin globalDependency.
* please remove https://github.com/git-kick/ioBroker.e3dc-rscp/blob/master/io-package.json#L67 if you do not offer a tab, also remove https://github.com/git-kick/ioBroker.e3dc-rscp/blob/master/admin/%40tab_m.html
* You use sentry. Please add an info about it to Readme on top, please see https://github.com/ioBroker/plugin-sentry#how-can-i-get-my-sentry-account-as-a-developer
* https://github.com/git-kick/ioBroker.e3dc-rscp/blob/master/main.js#L4-L19 should not be needed because the sentry plugin already does that, see the plugin readme for the way to access the Sentry instance if needed
* The timeout here https://github.com/git-kick/ioBroker.e3dc-rscp/blob/master/main.js#L525 can not be cleared in unload  -also make sure that not multiple such timers run in parallel
* Please also close the network connection in on unload ... Best try to test the adapter stop in compact mode

Thank you for checking and adjuting

**Comment by Apollon77** [comment]
Hi, for Sentry:
* I think you are rthe first one to track "transactions" in sentry :-), but in fact as described in https://github.com/ioBroker/plugin-sentry#send-own-additional-events-to-sentry you can use (in on.ready) such code to get the internally used Sentry instance. Then you simply do not fo "Sentry.withScope" but your command

For Compavt mode:
* The interesting stuff happens when you stop the adapter ... then check your log (maybe set to debug or such to gain more logs) if still logic is executed. Same for start adapter again after stopping (or restart) and check pot errors loggen that could mean overlaps (but in your case most likely nothing seen because you just connect to another service ...

Did that help?

**Comment by git-kick** [comment]
Hi, thanks for your reply, yes it helps.

**Sentry**: I removed the plugin for now. It was only a trial effort. I put it to the backlog.

**Compact mode**: adapter falls back to normal mode, and I cannot find out the reason, see [new topic](https://forum.iobroker.net/topic/51572/cannot-start-adapter-0-in-compact-mode).
All timers are now reset onUnload(), also tcpConnection ist closed/destroyed.

How is the way forward? On hold until the [topic](https://forum.iobroker.net/topic/51572/cannot-start-adapter-0-in-compact-mode) is solved?

**Comment by Apollon77** [comment]
loading files relatively like you do in https://github.com/git-kick/ioBroker.e3dc-rscp/blob/master/main.js#L8 can break beause formally this depends on the "working directory of the started nodejs process". This works for require because they always load rerative to the "script file that has the require in".
So use:

`eval(fs.readFileSync(__dirname + "/admin/words.js").toString());`

(ok, better is to require the path library and execute `path.join(__dirname, 'admin/words.js)`... that should do the trick

**Comment by git-kick** [comment]
@Apollon77: Many thanks, it works using `__dirname` as you suggested.

Testing `e3dc-rscp` in Compact Mode was successful, no issues detected.

I think this completes my answers concerning your [review comments](https://github.com/ioBroker/ioBroker.repositories/pull/1589#issuecomment-1015845692). Or did I miss something?

**Comment by Apollon77** [comment]
Then all fine, please update npm and I will be happy to merge :-)

**Comment by git-kick** [comment]
v1.0.0 is on npm, but I have some trouble passing the github tests - getting different error messages for every attempt, kind of strange.

I will update here as soon as testing is ok.

**Comment by Apollon77** [comment]
If you need support also just poke here or in Discord/Telegram

**Comment by git-kick** [comment]
Ups, never think @Apollon77 gives you a minute to edit your post :-D

My third attempt on github worked, all tests passed now, npm updated.

**Comment by Apollon77** [comment]
> Ups, never think @Apollon77 gives you a minute to edit your post :-D

lol :-)))

Welcome in the repo!

**Comment by git-kick** [comment]
Danke für den super Support, Ingo!
-Uli

----------------------------------------

20.01.2022 18:01:28 Ingo Fischer ***@***.***>:

**Comment by git-kick** [comment]
Many thanks!

For proceeding to stable, I need a **discovery** interface - could you guide me to some how-to, I failed when searching the forum.

**Comment by Apollon77** [comment]
You do not "need to" have a discovery ... If your dapter integrates devices that can be discovered then it would be great to add to discovery adapter.

So IF it is possible then you need to do a PR for https://github.com/ioBroker/ioBroker.discovery/tree/master/lib/adapters and addyour file there to detect  a device.
In fact discovery will scan all IPs in the network but can also do mdns or udp

**Pull request merged**
