### PR TITLE
palazzetti adapter added to sources-dist-stable.json

### PR DESCRIPTION
**Pull request by inapsis**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.palazzetti](https://github.com/inapsis/ioBroker.palazzetti)
[Downloads](https://www.npmjs.com/package/iobroker.palazzetti) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.palazzetti/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/inapsis/ioBroker.palazzetti/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W400] Cannot find "palazzetti" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by inapsis** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.palazzetti](https://github.com/inapsis/ioBroker.palazzetti)
[Downloads](https://www.npmjs.com/package/iobroker.palazzetti) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.palazzetti/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "palazzetti" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Jey-Cee** [comment]
Needed:
- Link to the manufacturer or device webpage
- Automated testing on Travis-CI.org is not enabled
- [ConnectionType](https://github.com/ioBroker/ioBroker.repositories#connection-types) is missing
- A lot of the Objects do have the role "state" please check if you can find better [roles](https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md#state-roles) for it, if not make proposals for new ones
- main.js: onObjectChange is not used so could be removed

Comments:
- Objects handling: Objects seems not to be created dynamicly, so you can define them in io-package.json at instanceObjects
- Objects handling: Object names should be human readable. Example "control.pwr" -> better  "Power" or "Turn Power on"
- Objects handling: You have labels defined that are related to the states, for this purpose could be used the `common.states: {1:"1";2:"ON"}`. 
- libraries could be placed in folder "lib". Makes it a bit cleaner.

**Comment by Apollon77** [comment]
@inapsis Did you saw the comments?

**Comment by DutchmanNL** [comment]
@inapsis any update?

**Comment by Apollon77** [comment]
@inapsis do you have an update?

**Comment by inapsis** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.palazzetti](https://github.com/inapsis/ioBroker.palazzetti)
[Downloads](https://www.npmjs.com/package/iobroker.palazzetti) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.palazzetti/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "palazzetti" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@inapsis do you have an update? How should we proceed?

**Comment by inapsis** [comment]
Hi @Apollon77, I have tried to adapt all your comments and needs and posted already a new version some weeks ago.
I am not sure if something additional needed to request a review again.

**Comment by Apollon77** [comment]
Ahh ok, I waited for a info back when done :-)

I had a short check and found one last small thing:
* please add js-controller >=2.0.0 as dep in io-package (because you use adapter-core 2.4.0)

Beside that I just saw that all the states are set in parallel ... you maybe want to use also Async methods and promises here

Thank you for a fast check.

**Comment by inapsis** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.palazzetti](https://github.com/inapsis/ioBroker.palazzetti)
[Downloads](https://www.npmjs.com/package/iobroker.palazzetti) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.palazzetti/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "palazzetti" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by inapsis** [comment]
Hi @Apollon77, thanks for your fast reply... 
I adapted the js-controller dependency as requested. 
For all set states I have already used adapter.setStateAsync,... nevertheless the promise result is now processed additionally.

**Pull request merged**
