### PR TITLE
Add BayernLuft Adapter to latest

### PR DESCRIPTION
**Pull request by Marco15453**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bayernluefter](https://github.com/Marco15453/ioBroker.bayernluefter)
[Downloads](https://www.npmjs.com/package/iobroker.bayernluefter) 
[NPM](https://nodei.co/npm/iobroker.bayernluefter/)

- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/uk/translations.json" not found, but admin support is declared
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/Marco15453/ioBroker.bayernluefter", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Marco15453/ioBroker.bayernluefter/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "bayernluefter" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
SUpported languages notes can be ignored

**Comment by Marco15453** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bayernluefter](https://github.com/Marco15453/ioBroker.bayernluefter)
[Downloads](https://www.npmjs.com/package/iobroker.bayernluefter) 
[NPM](https://nodei.co/npm/iobroker.bayernluefter/)

- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/uk/translations.json" not found, but admin support is declared
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Marco15453/ioBroker.bayernluefter/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "bayernluefter" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Marco15453** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
Hi, here is my review feedback:
* YOu choose a very creative way to work around node-fetch being ESM only in v3An alternative is to use https://github.com/esm2cjs/node-fetch#esm2cjsnode-fetch ... I'm also completely unsure if this have performance or memory consumption issues ... in fact it will always import it "again" - for every call ... feels suboptimal.
* Please add meaningfull translations for your field into the translation files :-) https://github.com/Marco15453/ioBroker.bayernluft/blob/main/admin/i18n/de/translations.json is dummy stuff :-)
* Please move https://github.com/Marco15453/ioBroker.bayernluft/blob/main/main.js#L57 one line on top of the setState - setState could throw an error ... clearTimeout not.
* It might be easier to remember which objects were already checked and so existing than checkig this for every calue you write in each "data read loop" This produces a lot of database traffic which is unneeded.
* Please check and adjust the roles against https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md (e.g. string can not be "indicator"
* Please only react to state changes with ack === false (or is this the second return in stateChange but a typo?)
* While it is somehow working it is cleaner code to use await with setStateAsync instead of setState :-) (e.g. https://github.com/Marco15453/ioBroker.bayernluft/blob/3977421cec03784437a667b28fb1ed8f6fc865f4/main.js#L152)
* Please enforce meaningful minimum/limts for the pullInterval
* Maybe you want to add a timeout for the node-fetch requests and make sure that the timeouts are set in a way that the pullIntervall can not be smaller then "timeout*2" (because two calls when I got it right)
Thank you for checking and adjusting the mentioned relevant points

**Comment by Marco15453** [comment]
> * It might be easier to remember which objects were already checked and so existing than checkig this for every calue you write in each "data read loop" This produces a lot of database traffic which is unneeded.

What do you exactly mean with this?

**Comment by Apollon77** [comment]
Right now whenever you receive data and want to write a state you do a getObject and then do comparisms based on that object. Given the point that datatype, unit and such not change with each data request (if this would be true we need to talk about other topics) in fact  ONE getObject at the start would be enough if you simply would create a Map in the adapter wehere you remember this object by his id. So you also know the content without having to read it from the DB everytime anew

**Comment by Apollon77** [comment]
@Marco15453 Happy new year, how we should proceed?

**Comment by Marco15453** [comment]
I don't quite understand what you exactly want, if you could destribe it a bit better.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bayernluefter](https://github.com/Marco15453/ioBroker.bayernluefter)
[Downloads](https://www.npmjs.com/package/iobroker.bayernluefter) 
[NPM](https://nodei.co/npm/iobroker.bayernluefter/)

- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/Marco15453/ioBroker.bayernluefter/blob/master/package.json) must be lowercase and be equal to "iobroker.bayernluefter". Now is "iobroker.bayernluft"
- [ ] :heavy_exclamation_mark: [E103] "common.name" in [io-package.json](https://github.com/Marco15453/ioBroker.bayernluefter/blob/master/io-package.json) must be equal to "bayernluefter'". Now is bayernluft
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.bayernluefter)!. Please execute in adapter directory: `npm owner add bluefox iobroker.bayernluefter`
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/uk/translations.json" or "admin/i18n/uk.json" not found, but admin support is declared
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Marco15453/ioBroker.bayernluefter/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/Marco15453/ioBroker.bayernluefter/blob/master/package.json) (1.2.2) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.bayernluefter) ({"_id":"iobroker.bayernluefter","name":"iobroker.bayernluefter","time":{"created":"2022-10-31T12:27:57.986Z","1.0.0":"2022-10-31T12:27:58.198Z","modified":"2022-11-04T20:32:58.749Z","1.0.2":"2022-10-31T12:33:11.324Z","1.1.0":"2022-10-31T13:53:38.032Z","1.1.1":"2022-10-31T13:59:36.502Z","1.1.2":"2022-10-31T14:43:23.802Z","1.2.0":"2022-11-03T18:53:16.251Z","unpublished":{"time":"2022-11-04T20:32:58.749Z","versions":["1.0.0","1.0.2","1.1.0","1.1.1","1.1.2","1.2.0"]}}})
- [ ] :eyes: [W400] Cannot find "bayernluefter" in latest repository

### [ioBroker.bayernluft](https://github.com/Marco15453/ioBroker.bayernluft)
[Downloads](https://www.npmjs.com/package/iobroker.bayernluft) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.bayernluft/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.bayernluft)!. Please execute in adapter directory: `npm owner add bluefox iobroker.bayernluft`
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/uk/translations.json" or "admin/i18n/uk.json" not found, but admin support is declared
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Marco15453/ioBroker.bayernluft/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "bayernluft" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@Marco15453 
> I don't quite understand what you exactly want, if you could destribe it a bit better.

To which point exactly you need more information? Is it about the remember alreadyf created objects or any other point?

if it is that point then this is simply a performance topic: 
In your checkDevices when you write data then you always do a "getObject" to verify if the object is existing or not. If yes you just do setState else you craete objects, but you aaalways do a getObject. And in fact you do this in any pull loop, so any x Seconds.
My idea was that you have e.g. ean object with named keys where you remember when you did the getObject check or created the object becaus ethen you do not need to do that again for thw whole run of your instance.

Is that more clear?

Innfact with a getObject you dpuble the number of requests your adapter does internally to the DB per "pull loop".

**Comment by mcm1957** [comment]
Please add node 18 test-and-release.yml and (optionally) add node 20 to testing matrix.

And in addition please REMOVE source-dist-stabel from this PR. New adapters MUST be available for some time at latest before accepted for stabel repository. So ist inappropiate to add this adapter to both repositories at once

Thanks
McM1957

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
PR must not change latest and stabel at the same time
Addition to stable requires that the adapter is available at latest for some time (at least a week) and have some users.

**So please remove changes for stable repo from this PR**

**Comment by Marco15453** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Check of bayernluefter irrelavant and caused by old commits.

❗ [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.bayernluft)!. Please execute in adapter directory: npm owner add bluefox iobroker.bayernluft

must be fixed, further review to be done

**Comment by Marco15453** [comment]
RE-CHECK!

**Comment by Marco15453** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
@Marco15453 Please check the checker comments

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@Marco15453 
As there was no reaction to last poll from mid 2023 and adapter has not been updated since app 2 years this PR seems to be outdated / stale.

@Marco15453 
Please respond if you still want this adapter to be added to the repositories and would adapt the adapter if required after review. I'll do a new rive then.

**If there is no reaction / comment until 15.04.2024 I will close this PR**

Of course opening a new PR at any time is welcome.

Thanks for writing an adapter for ioBroker.

**Pull request closed without merging**
