### PR TITLE
Update loxone to 1.1.0

### PR DESCRIPTION
**Pull request by UncleSamSwiss**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.loxone](https://github.com/UncleSamSwiss/ioBroker.loxone)
[Downloads](https://www.npmjs.com/package/iobroker.loxone) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.loxone/)

- [ ] :heavy_exclamation_mark: [E106] Title should not have word "adapter" in the name. It is clear, that this is adapter. Now: Loxone Miniserver Adapter
- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin3 support
- [ ] :heavy_exclamation_mark: [E116] No SPDX license found. Please use one of listed here: https://spdx.org/licenses/
- [ ] :heavy_exclamation_mark: [E117] Licenses in [package.json](https://github.com/UncleSamSwiss/ioBroker.loxone/blob/master/package.json) and in [io-package.json](https://github.com/UncleSamSwiss/ioBroker.loxone/blob/master/io-package.json) are different
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.loxone)!. Please execute in adapter directory: `npm owner add bluefox iobroker.loxone`
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/UncleSamSwiss/ioBroker.loxone) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E506] Word "Names" is not translated to russian in [admin/words.js](https://github.com/UncleSamSwiss/ioBroker.loxone/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/UncleSamSwiss/ioBroker.loxone", press the settings button beside the about title and add some topics.
- [ ] :heavy_exclamation_mark: [E604] No `## License` found in [README.md](https://github.com/UncleSamSwiss/ioBroker.loxone/blob/master/README.md)
- [ ] :eyes: [W113] Adapter should support compact mode


*Add comment "RE-CHECK!" to start check anew*

**Comment by UncleSamSwiss** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.loxone](https://github.com/UncleSamSwiss/ioBroker.loxone)
[Downloads](https://www.npmjs.com/package/iobroker.loxone) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.loxone/)

- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin3 support
- [ ] :eyes: [W113] Adapter should support compact mode


*Add comment "RE-CHECK!" to start check anew*

**Comment by UncleSamSwiss** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.loxone](https://github.com/UncleSamSwiss/ioBroker.loxone)
[Downloads](https://www.npmjs.com/package/iobroker.loxone) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.loxone/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode


*Add comment "RE-CHECK!" to start check anew*

**Comment by UncleSamSwiss** [comment]
Tried to re-run the Travis CI, but every time it hits timeouts and gives errors about other adapter's icons missing. I believe this PR should be OK now.

**Comment by Apollon77** [comment]
Thank you!

**Pull request merged**
