### PR TITLE
Update atlas-scientific-ezo-i2c to 2.3.0

### PR DESCRIPTION
**Pull request by Buzze11**
Please update my adapter ioBroker.atlas-scientific-ezo-i2c to version 2.3.0.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
@Buzze11 

Did you create a tester Thread at forum?
If not, please create one to check for some feedback.

If already done, please provide link. 
ANY discussion/test topic is ok, it need not be at tester forum althgough this is the prefered location.

see https://github.com/ioBroker/ioBrsee https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-stable-repository

**Comment by mcm1957** [comment]
2.3.0 created 14.08.2023
7 User

**Comment by Buzze11** [comment]
@mcm1957 
No, i just followed a mail from Bluefox who mentioned to think about adding it to the stable version. I haven`t been aware that it must be added first to a tester Thread

**Comment by mcm1957** [comment]
No problem at all.

If addition does not work ping homoran at forum.
The main goal for forum thread is that users are informed of your work and theres some central discussion topic during initial release.

**Comment by mcm1957** [comment]
@Buzze11 
Did you get write access in the meantime?
Did you already create a test topic?

**Comment by Buzze11** [comment]
No unfortunately I did not get the write access to the Testers Forum till yesterday. I’ve had no time today to check it again. Am 16.09.2023 um 20:30 schrieb Martin M. ***@***.***>:﻿
@Buzze11
Did you get write access in the meantime?
Did you already create a test topic?

**Comment by mcm1957** [comment]
whats you user at forum?

**Comment by Buzze11** [comment]
I am Buzze11Am 16.09.2023 um 21:19 schrieb Martin M. ***@***.***>:﻿
whats you user at forum?

**Comment by Buzze11** [comment]
Just FYI, I have the adapter continuously running since the first release and did some fixes for some users already. It will be hard for testers as well, as you need the quite expensive Atlas Scientific hardware to be able to test it. And due to the „latest“ repo you don’t get too much attention as a bunch of users will habe the flag not set in ioBroker because default is „stable“Am 16.09.2023 um 22:26 schrieb Thomas Buchholz ***@***.***>:﻿I am Buzze11Am 16.09.2023 um 21:19 schrieb Martin M. ***@***.***>:﻿
whats you user at forum?

**Comment by mcm1957** [comment]
RE-CHECK!

**Pull request merged**
