### PR TITLE
add elgato-key-light to Latest

### PR DESCRIPTION
**Pull request by xXBJXx**
Please add my adapter ioBroker.elgato-key-light to latest.

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.elgato-key-light](https://github.com/xXBJXx/ioBroker.elgato-key-light)
[Downloads](https://www.npmjs.com/package/iobroker.elgato-key-light) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.elgato-key-light/)

- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/xXBJXx/ioBroker.elgato-key-light/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "elgato-key-light" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.elgato-key-light](https://github.com/xXBJXx/ioBroker.elgato-key-light)
[Downloads](https://www.npmjs.com/package/iobroker.elgato-key-light) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.elgato-key-light/)

- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/xXBJXx/ioBroker.elgato-key-light/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "elgato-key-light" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- [ ] errors reported by Apollon77 must be fixed

  see comment above
  
- [ ] adapter has 'singleton' set to true (aka only one instance per host allowed) - why?

  Why is 'singleton=true' attribute set. Thes limits the usage of the adapter to one single instance per host.

- [ ] invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```.- You are using the serial number reported by the device. Please verify that this serial number does not contain any forbissen characters or spaces and replace such characterw i.e. by '_'.

- [ ] axios timeout

  axios calls should specify a specific timeout. Accoring to axios documentation the default for the option timeout is 0 (no timeout). This could result in an stalled adapter.

- [ ] onStateChange handler ignores ack flag 

  The adapter must honor the ack flag when processing onStateChange events. Whenever the onStateChange handler is called for an own state (a state owned by the processing instance of the adapter) it must ignore this event if the ack flags is set. Only stateChanges with ack==false are allowed to be processed.

  When processing foreign states which are output of another adapter  processing must only occure if the ack flag is true.

- [ ] role button

  states with role button should (mast) specify common.read=false.
  see https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md
  https://github.com/xXBJXx/ioBroker.elgato-key-light/blob/43315a3a6059ddea5c83e4583205195bcc4a6816/src/main.ts#L363C1-L363C1

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.
  
- [ ] check and limit configurable timeouts / intervals
  
  Node setTimeout/setInterval routines have a maximum allowed value of 2,147,483,647 ms. Using delays larger than 2,147,483,647 ms (about 24.8 days) result in the timeout being executed immediately. So all (user configurable) values passed to setTimeout / setInterval should be checked and limited.
  
- [ ] adapt testing to supported node releases

  Tests for node 16 is mandatory unless you require node 18 and higher.
  Tests for node 18 is mandatory as many users already use node 18 and node 16 will be eol and deprected Q3/2023.
  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x],
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
Development of adapter suspended for a currently unknown timeframe.
PR cancelled

Please open a ne PR if development to be continued

**Pull request closed without merging**
