### PR TITLE
Update Viessmann

### PR DESCRIPTION
**Pull request by misanorot**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.viessmann](https://github.com/misanorot/ioBroker.viessmann)
[Downloads](https://www.npmjs.com/package/iobroker.viessmann) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.viessmann/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 1.3.1
- [ ] :eyes: [W113] Adapter should support compact mode


*Add comment "RE-CHECK!" to start check anew*

**Comment by misanorot** [comment]
Done....

**Comment by Apollon77** [comment]
... but then we also need formally a 1.3.2?!

**Pull request merged**
