### PR TITLE
Add Apple-Find-Me and Remove Find-My-Iphone from Apollon77

### PR DESCRIPTION
**Pull request by PfisterDaniel**
Now i've fixed all Issues from feedback that comes from Apollon77 and i recreate the PR.

Feedback: https://github.com/ioBroker/ioBroker.repositories/pull/1722#issuecomment-1066492404

I hope now it's all correct

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi, only some small stuff left:
* Must: Adaptertests should execute npm run test:integration as adapter tests and test:package in the check-and-lint step :-)
* Must: The admin-dependency in io-package needs to go into "globalDependencies" section
* Hint: You can use "protectedNative" additionally to encryptedNative to prevent outside access to the encrypted data
* Hint: Thank you for moving to a timeout instead schedule. YOu can now also remove the dependency from package.lock :-)
* Hint: https://github.com/PfisterDaniel/ioBroker.apple-find-me/blob/master/main.js#L593 ... also re-set the timeout here? Else the adapter gets "stuck"
* Hint: When using "await adapter.setObjectNotExists" you should better use the Async methods... -> await adapter.setObjectNotExistsAsync

Rest looks fine. Thank you for your support.

You can leave open here, just poke when updated

**Comment by PfisterDaniel** [comment]
Ok, i fixed the issues :-) Please check again.


- [x] Must: Adaptertests should execute npm run test:integration as adapter tests and test:package in the check-and-lint step :-)
- [x] Must: The admin-dependency in io-package needs to go into "globalDependencies" section
- [x] Hint: You can use "protectedNative" additionally to encryptedNative to prevent outside access to the encrypted data
- [x] Hint: Thank you for moving to a timeout instead schedule. YOu can now also remove the dependency from package.lock :-)
- [x] Hint: https://github.com/PfisterDaniel/ioBroker.apple-find-me/blob/master/main.js#L593 ... also re-set the timeout here? Else the adapter gets "stuck"
- [x] Hint: When using "await adapter.setObjectNotExists" you should better use the Async methods... -> await adapter.setObjectNotExistsAsync

**Comment by Apollon77** [comment]
Hi,

one very last thing:

* please remove https://github.com/PfisterDaniel/ioBroker.apple-find-me/blob/master/io-package.json#L178 ... installedFrom must not exist

Then please release a new version and we are ready to merge!

**Comment by PfisterDaniel** [comment]
Update io-package.json and release a new Version

**Comment by Apollon77** [comment]
Welcome!

@PfisterDaniel I have prepared an Admin Notification for the deprecation of the old adapter too ... If you do a stable PR next for "the same content" (your adapter in, the other out) then I will add that afterwards

**Comment by Apollon77** [comment]
@PfisterDaniel Doywe want to continue and do stable includiontoo? Just create the PR

**Pull request merged**
