### PR TITLE
adding rct adapter

### PR DESCRIPTION
**Pull request by lauff**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.rct](https://github.com/lauff/ioBroker.rct)
[Downloads](https://www.npmjs.com/package/iobroker.rct) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.rct/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "rct" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@lauff Anything we can support with?

**Comment by lauff** [comment]
@Apollon77, thanks for your valuable feedback, but unfortunately I currently (also at least for the next 3 months) don't find the time to look at that in detail and fix the issues.

**Comment by Apollon77** [comment]
@lauff Is time better now? Can we help somehow?

**Comment by lauff** [comment]
Unfortunately, I still don't find the time to look into the details about what needed to be done to follow-up on your comments.

If these are fixes that you can do, I would be more than happy and appreciate it a lot!

**Comment by Apollon77** [comment]
@lauff https://github.com/lauff/ioBroker.rct/pull/10 have fun. Please TEST! maybe also do a test of m reconnect idea

**Comment by lauff** [comment]
@Apollon77 thanks a lot for your support!

**Comment by lauff** [comment]
not sure it was a good idea to close the pull request - so reopening it ;-)

**Comment by Apollon77** [comment]
:-) Just tell when you tested it and released a new version then we can continue here

**Comment by lauff** [comment]
I tested it and released v1.0.1

**Pull request merged**
