### PR TITLE
add Ford Adapter

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.ford](https://github.com/TA2k/ioBroker.ford)
[Downloads](https://www.npmjs.com/package/iobroker.ford) 
[NPM](https://nodei.co/npm/iobroker.ford/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.ford)!. Please execute in adapter directory: `npm owner add bluefox iobroker.ford`
- [ ] :eyes: [W400] Cannot find "ford" in latest repository

### [ioBroker.nissan](https://github.com/TA2k/ioBroker.nissan)
[Downloads](https://www.npmjs.com/package/iobroker.nissan) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.nissan/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "nissan" in latest repository

### [ioBroker.wmswebcontrol](https://github.com/TA2k/ioBroker.wmswebcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.wmswebcontrol) 
[NPM](https://nodei.co/npm/iobroker.wmswebcontrol/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "wmswebcontrol" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

Review Feedback:
* Please update testing lib, else all your tests will fail
* Please set connecion state to false in unload :-)
* really setting timeout only new in https://github.com/TA2k/ioBroker.ford/blob/master/main.js#L378 ? What about deleting an existing one first?

Only last needs to be checked and pot fixed, rest optional

**Comment by TA2k** [comment]
Issues fixed

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.wmswebcontrol](https://github.com/TA2k/ioBroker.wmswebcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.wmswebcontrol) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.wmswebcontrol/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "wmswebcontrol" in latest repository

### [ioBroker.nissan](https://github.com/TA2k/ioBroker.nissan)
[Downloads](https://www.npmjs.com/package/iobroker.nissan) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.nissan/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "nissan" in latest repository

### [ioBroker.ford](https://github.com/TA2k/ioBroker.ford)
[Downloads](https://www.npmjs.com/package/iobroker.ford) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.ford/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "ford" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Thank you, please poke again when new verison is released on npm

**Comment by TA2k** [comment]
Done

**Comment by foxriver76** [comment]
Hm why there are 3 adapters in this PR? Are Nissan and waren’s also published after issues addressed in PR were fixed, then I would just merge this one @TA2k

**Comment by TA2k** [comment]
No only 1 adapter in this PR see also file changed but the branch was created after commiting the other this leads to this wrongly added checks. 
This can be ignored

**Pull request merged**
