### PR TITLE
iobroker.accuweather adapter added

### PR DESCRIPTION
**Pull request by algar42**

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi,

here some review comments:

* [E605] No actual year found in copyright. Please add "Copyright (c) 2020 algar42 <igor.aleschenkov@gmail.com>" at the end of README.md
* [E701] No actual year found in LICENSE. Please add "Copyright (c) 2020 algar42 <igor.aleschenkov@gmail.com>" at the start of LICENSE
* [E816] file tsconfig.json found in repository, but not found in .npmignore
* If it makes sense to store the api keys or such in an encrypted form then you should implement that
* you need to store and clear all timeouts and intervals on "unbind" (e.g. https://github.com/iobroker-community-adapters/ioBroker.accuweather/blob/master/main.js#L300), else compact mode is broken
* please do not use setObject because this will pot. override custom settings on the object ( at least in controller < 2.0). Use setObjectNotExists

Please review and follow the development best practices: https://github.com/ioBroker/ioBroker.repositories#development-and-coding-best-practices

**Comment by algar42** [comment]
All points above should now be fixed

**Comment by GermanBluefox** [comment]
Timeouts could run up to 10 seconds. They must be stopped by unload too:
https://github.com/iobroker-community-adapters/ioBroker.accuweather/blob/master/main.js#L304

**Comment by algar42** [comment]
> Timeouts could run up to 10 seconds. They must be stopped by unload too:
> https://github.com/iobroker-community-adapters/ioBroker.accuweather/blob/master/main.js#L304

Thanks!
Updated. v1.1.3 published

**Comment by GermanBluefox** [comment]
## Automated adapter checker
### ioBroker.accuweather
 * [E301] Tests on Travis-ci.org are broken. Please fix.

**Comment by algar42** [comment]
It fails build for windows. it looks like it fails trying to deploy to npm - I don't know why and can't understand how to fix :(

**Pull request merged**
