### PR TITLE
adapter "device-reminder": release to latest

### PR DESCRIPTION
**Pull request by Xenon-s**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
Very first feedback: The READEME.md must be english. YOu can put a german version in a special folder and specify this in io-package (see js adapter), then it will be used

**Comment by Xenon-s** [comment]
How can I store two different readme in the IO package? Does the wiki have to be in English too?

**Comment by Xenon-s** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
Only readme needs to be english because will be auto translated for www.iobroker.net

Examples https://github.com/ioBroker/ioBroker.javascript/blob/master/io-package.json#L280-L292

**Comment by Xenon-s** [comment]
@Apollon77 @GermanBluefox  Is there anything I need to revise?

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "device-reminder" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi, some review comments:
* really Template? ;-) https://github.com/Xenon-s/ioBroker.device-reminder/blob/master/main.js#L29
* could it be that you forgot to also clear https://github.com/Xenon-s/ioBroker.device-reminder/blob/master/main.js#L589 on unload?

**Comment by Xenon-s** [comment]
@Apollon77 
1. I missed that ! :D 
2. done 

pls re-check ;)

**Comment by Apollon77** [comment]
Welcome in the repo

**Pull request merged**
