### PR TITLE
Add sunnyporal to sources

### PR DESCRIPTION
**Pull request by marvincaspar**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sunnyportal](https://github.com/marvincaspar/ioBroker.sunnyportal)
[Downloads](https://www.npmjs.com/package/iobroker.sunnyportal) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sunnyportal/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:marvincaspar/ioBroker.sunnyportal.git. Expected: git+https://github.com/marvincaspar/ioBroker.sunnyportal.git
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/marvincaspar/ioBroker.sunnyportal", press the first "Edit" button you will find on the page and add the description.
- [ ] :eyes: [W400] Cannot find "sunnyportal" in latest repository
- [ ] :eyes: [W505] setTimeout found in "build/main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
Please clear timeout on unload: https://github.com/marvincaspar/ioBroker.sunnyportal/blob/master/src/main.ts#L213

**Comment by marvincaspar** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sunnyportal](https://github.com/marvincaspar/ioBroker.sunnyportal)
[Downloads](https://www.npmjs.com/package/iobroker.sunnyportal) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sunnyportal/)

- [ ] :heavy_exclamation_mark: [E506] Word "sunnyportal adapter settings" is not translated to russian in [admin/words.js](https://github.com/marvincaspar/ioBroker.sunnyportal/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "sunnyPortalEmail" is not translated to russian in [admin/words.js](https://github.com/marvincaspar/ioBroker.sunnyportal/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "sunnyPortalPassword" is not translated to russian in [admin/words.js](https://github.com/marvincaspar/ioBroker.sunnyportal/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W400] Cannot find "sunnyportal" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by marvincaspar** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sunnyportal](https://github.com/marvincaspar/ioBroker.sunnyportal)
[Downloads](https://www.npmjs.com/package/iobroker.sunnyportal) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sunnyportal/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "sunnyportal" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
