### PR TITLE
Added Trashschedule adapter

### PR DESCRIPTION
**Pull request by klein0r**
See https://forum.iobroker.net/topic/27050/test-adapter-trashschedule-v0-0-x/ for details

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker
### ioBroker.trashschedule
No errors found

**Comment by Apollon77** [comment]
Some more review feedback:
* please translate the texts. you can use https://translator.iobroker.in/ for this
* you subscribe to all adapter states in https://github.com/klein0r/ioBroker.trashschedule/blob/master/main.js#L92 but only react on the foreign one from ical
* maybe this adapter could be of type "subscribe" ... @GermanBluefox any details on that idea? I don't know if this works with a dynamic subscribed id?!
* "added vis templates"? Missing?

**Comment by ldittmar81** [comment]
For auto translation you should read this: https://forum.iobroker.net/topic/19047/gulp-ist-kein-hexenwerk-auto-translation

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule)
[Downloads](https://www.npmjs.com/package/iobroker.trashschedule) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.trashschedule/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in admin/words.js. You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W400] Cannot find "trashschedule" in latest repository

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule)
[Downloads](https://www.npmjs.com/package/iobroker.trashschedule) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.trashschedule/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js]("https://github.com/klein0r/ioBroker.trashschedule/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W400] Cannot find "trashschedule" in latest repository

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule)
[Downloads](https://www.npmjs.com/package/iobroker.trashschedule) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.trashschedule/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js]("https://github.com/klein0r/ioBroker.trashschedule/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W400] Cannot find "trashschedule" in latest repository

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule)
[Downloads](https://www.npmjs.com/package/iobroker.trashschedule) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.trashschedule/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/klein0r/ioBroker.trashschedule/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W400] Cannot find "trashschedule" in latest repository

**Comment by klein0r** [comment]
Ok, fixed all the issues

**Pull request merged**
