### PR TITLE
Add new ioBroker.cleveron adapter

### PR DESCRIPTION
**Pull request by forelleblau**
Adapter-checker checked, Appveyor-tested

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.cleveron](https://github.com/iobroker-community-adapters/ioBroker.cleveron)
[Downloads](https://www.npmjs.com/package/iobroker.cleveron) 
[NPM](https://nodei.co/npm/iobroker.cleveron/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.cleveron)!. Please execute in adapter directory: `npm owner add bluefox iobroker.cleveron`
- [ ] :eyes: [W400] Cannot find "cleveron" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by forelleblau** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.cleveron](https://github.com/iobroker-community-adapters/ioBroker.cleveron)
[Downloads](https://www.npmjs.com/package/iobroker.cleveron) 
[NPM](https://nodei.co/npm/iobroker.cleveron/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "cleveron" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by forelleblau** [comment]
"RE-CHECK!"

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by forelleblau** [comment]
[Forum testing thread](https://forum.iobroker.net/topic/49528/test-adapter-cleveron?_=1637414215580)

But since cleveron is a startup, I don't expect really feedback yet.

**Comment by Apollon77** [comment]
Hi,

sorry that it took that long, here are my review comments:
* Your testing is red, it seems to be like a broken package-lock.json file
* The way you encrypt the password works ... but you could have it more easy by using "encryptedNative" - see readme, optional
* please remove https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L71 if not needed
* same for https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L77
* without logic for statechanges please remove https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L153
* There are unknown roles used e.g. in https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L451 ... please verify the used roles and do not invent new ones yourself --> https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md
* maybe startusing async and await all the object creations? Then such hacks like in https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L521 are not needed ... they will break!
* The timeout set anew in yur timeout function can not be stopped by unload. https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L149

Please check and asjust, thank you

**Comment by forelleblau** [comment]
Thanks for the Feedback here what I could do:

> Your testing is red, it seems to be like a broken package-lock.json file 

package-lock.json fixt, testing ok now.

> The way you encrypt the password works ... but you could have it more easy by using "encryptedNative" - see readme, optional.

tried to settle it with 'encryptedNative' but did not work - will change that later.

> please remove https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L71 if not needed

done

> same for https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L77

done

> without logic for statechanges please remove https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L153

done

> There are unknown roles used e.g. in https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L451 ... please verify the used roles and do not invent new ones yourself --> https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md

done

> maybe startusing async and await all the object creations? Then such hacks like in https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L521 are not needed ... they will break!

fixed with 'asyc function' and 'await ... setObjectNotExistsAsync'

> The timeout set anew in yur timeout function can not be stopped by unload. https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L149

fixed, changed to setInterval / clearInterval

thank you for your support

**Comment by Apollon77** [comment]
Hi,

I had anther look:
* Please do not log the password :-) Then all encryption is useless :-)
* Which problems you had with encryptedNative? if you "Play around" did you alwys did "iob upload adaptername"?
* Note: if you do it that way then you also need to "await" the call in https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L341 ... else this runs async in parallel ... this is ok in your case because last command
* How many objects are created there usually? Because also these many states will be set later and they are not set "Asnc" ... If there are too many this can produce issues in execution ... maybe also use setStateAsync with await?

Additionally please also relese new version to npm after adjustments.

Thank you!

**Comment by forelleblau** [comment]
Hi
Thanks a lot for review & feedback. 

> Please do not log the password :-) Then all encryption is useless :-)

done, sorry 

> Which problems you had with encryptedNative? if you "Play around" did you alwys did "iob upload adaptername"?

Thanks for insisting on this one. I tried again and now it works. Might be, that I did not change index_m.html with my last tries. 

> Note: if you do it that way then you also need to "await" the call in https://github.com/iobroker-community-adapters/ioBroker.cleveron/blob/main/main.js#L341 ... else this runs async in parallel ... this is ok in your case because last command

'till now, that was my way to handle asynchronity (cascade). Left it as is, might change it in a futur version, if the API the adapter works with will get more complex.

>How many objects are created there usually? Because also these many states will be set later and they are not set "Asnc" ... If there are too many this can produce issues in execution ... maybe also use setStateAsync with await?

Difficult to say. It's 13 objects per (physical) device. I think that the average number of devices per ioBroker-instance will be below 10. Nevertheless, changed to `await setStateAsync.`

> Additionally please also relese new version to npm after adjustments.

done, it's iobroker.cleveron@0.0.4

Thanks a lot for doing this really great job with ioBroker

**Comment by Apollon77** [comment]
> Thanks for insisting on this one.

Sure because it makes the developer live thaaaat much easier :-)

Thank you very much for the changes

**Pull request merged**
