### PR TITLE
Update Stable versions (27 adapter)

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by mcm1957** [comment]
@TA2k 

**Please split updates into seperate PRs per adapter and fix issues reported by adapter checker** to handle checks / and processing independently.

Please verify that:
- Adapters have release information added to README.md (Error 606 must be fixed)
- Verify that README,md is written in (pure) english.
- translations are present at io-package.json (at least english and german is mandatory)
- github tests for node 16/18/20 are implemented and working

Note: Error 605 and 701 (copyright year missing) can be ignored!

**Comment by TA2k** [comment]
Sorry I have not time for this. Please close or merge

**Comment by mcm1957** [comment]
In addition please state why you request stable updates for adapters you die not work on lately. I.e. worx has been maintained by lucky-esa lately. Dis you discusse with him to request an update of stable? It would be at least good practice to ask the (active) maintainer in my oppinion.

**Comment by mcm1957** [comment]
I will close here - please create seperate PRs. Using www.iobroker.dev this should a one click action (if all adater passes checks withpiut errors.)

@Apollon77 FYI

**Comment by mcm1957** [comment]
@TA2k 
> Sorry I have not time for this. Please close or merge

Please explain what actions are too much timeconsuming.
If splitting the PR is the problem - well can be handled as ONE PR too.

But the mentioned / reported issues

- missing releasenotes entry at README.md
- missing access to npm for bluefox
- missing translations for news 
- miccing common.connectionType and common.dataSource

shouldn't be a problem to fix as those information directly effects the users comfort when using / installing the adapter.

Please let me know, if you plan to fix / have fixed those issues so that I can do a selective merge when fixed.

**Comment by TA2k** [comment]
Release notes are in io-package.json
npm access was invited but not accepted
if the same text in German as in English no translation needed
this are old adapters the user never saw the information for connectionType and was fine with this

working adapter version is more important then copyright in readme, bad auto translated changelog or comfort infos like connectionType

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Pull request closed without merging**
