### PR TITLE
add cec2 to latest

### PR DESCRIPTION
**Pull request by Garfonso**
seems ready for some testing 😄 

Forum thread exists for quite a time now: https://forum.iobroker.net/topic/29491/test-adapter-cec2/

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.cec2](https://github.com/iobroker-community-adapters/ioBroker.cec2)
[Downloads](https://www.npmjs.com/package/iobroker.cec2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.cec2/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/iobroker-community-adapters/ioBroker.cec2/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E603] NO "## Changelog" found in [README.md](https://github.com/iobroker-community-adapters/ioBroker.cec2/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 Garfonso <garfonso@mobo.info>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.cec2/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Garfonso <garfonso@mobo.info>" at the start of LICENSE
- [ ] :eyes: [W400] Cannot find "cec2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Garfonso** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.cec2](https://github.com/iobroker-community-adapters/ioBroker.cec2)
[Downloads](https://www.npmjs.com/package/iobroker.cec2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.cec2/)

- [ ] :heavy_exclamation_mark: [E603] NO "## Changelog" found in [README.md](https://github.com/iobroker-community-adapters/ioBroker.cec2/blob/master/README.md)
- [ ] :eyes: [W400] Cannot find "cec2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Garfonso** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.cec2](https://github.com/iobroker-community-adapters/ioBroker.cec2)
[Downloads](https://www.npmjs.com/package/iobroker.cec2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.cec2/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "cec2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

some review comments:
* please also add the info "channel" to the instanceObjects
* why you need plugin-sentry as sdep? it is not used and provided by js-controller... so can be removed as dep from adapter
* in io-package native section 8https://github.com/iobroker-community-adapters/ioBroker.cec2/blob/master/io-package.json#L145-L152) more fields are in then you can edit via admin ... planned that way?
* you use adapter-core 2.4.0; you need to define js.controller 2.0.0+ as "dependency" in io-package
* if you do not needed object changes please also do not register the event handler

Thank you for checking and adjusting

**Comment by Garfonso** [comment]
Hi,

thanks for your comments. I fixed all of them. Only cecDebug is left as invisible parameter. Not 100% sure I will keep it or make it configurable or what... will see how those issues evolve.

Best Regards,
Achim

**Comment by Apollon77** [comment]
Good job!

**Pull request merged**
