### PR TITLE
added awattar adapter

### PR DESCRIPTION
**Pull request by sirjojo69**

### CODE REVIEW

**Comment by sirjojo69** [comment]
https://github.com/iobroker-community-adapters/ioBroker.discovergy/issues/45

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by sirjojo69** [comment]
> 
> 
> RE-CHECK!

hmmm... recheck was denn? fehlt was?

**Comment by Apollon77** [comment]
AN sich stösst das nen automatischen adaptercheck an ... hm .. :-)

**Comment by Apollon77** [comment]
did manually (https://adapter-check.iobroker.in/):

> [E503] "iob_npm.done" found in repo! Please add it to .gitignore
[E818] file iob_npm.done found in repository, but not found in .npmignore
[E914] file iob_npm.done found in repository, but not found in .gitignore

Please check and fix first

**Comment by sirjojo69** [comment]
> 
> 
> did manually (https://adapter-check.iobroker.in/):
> 
> > [E503] "iob_npm.done" found in repo! Please add it to .gitignore
> > [E818] file iob_npm.done found in repository, but not found in .npmignore
> > [E914] file iob_npm.done found in repository, but not found in .gitignore
> 
> Please check and fix first

hab das file gelöscht, zu git und npm ignore hinzugefügt, ein neues build / release gemacht, die neue version hier eintragen und den PR aktualisiert. passt das so?

**Comment by sirjojo69** [comment]
> 
> 
> did manually (https://adapter-check.iobroker.in/):
> 
> > [E503] "iob_npm.done" found in repo! Please add it to .gitignore
> > [E818] file iob_npm.done found in repository, but not found in .npmignore
> > [E914] file iob_npm.done found in repository, but not found in .gitignore
> 
> Please check and fix first

hab das jetzt vor 3 tagen gefixt. Fehlt noch was?

**Comment by sirjojo69** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.awattar](https://github.com/sirjojo69/ioBroker.awattar)
[Downloads](https://www.npmjs.com/package/iobroker.awattar) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.awattar/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "awattar" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by sirjojo69** [comment]
> 
> 
> did manually (https://adapter-check.iobroker.in/):
> 
> > [E503] "iob_npm.done" found in repo! Please add it to .gitignore
> > [E818] file iob_npm.done found in repository, but not found in .npmignore
> > [E914] file iob_npm.done found in repository, but not found in .gitignore
> 
> Please check and fix first

Wieso geht bei diesem PR nix weiter? Wenn noch was fehlen sollte, ich checks nicht. Irgendwie keine Kommunikation... :-(

**Comment by Apollon77** [comment]
i need to find time for review

**Comment by Apollon77** [comment]
Hi,

some review comments:
* please add all translations to io.package. Use the iobroker translation tool
* stateChange is not needed (https://github.com/sirjojo69/ioBroker.awattar/blob/master/main.js#L49)
* how many states the adapter is setting? seems like many. Please use async/await to make that sequencial, because else these many of parallel requests can have bad impacts on user systems ... then also the "stop faillback" is not needed https://github.com/sirjojo69/ioBroker.awattar/blob/master/main.js#L339

**Comment by Apollon77** [comment]
@sirjojo69 Any update?

**Comment by sirjojo69** [comment]
hi @Apollon77 .. i´m struggeling with your recommended refactoring regarding async/await, since this is my first adapter and i´m not that frondend guy. so that will take its time. meanwhile it is used directly out of the git repo...

**Comment by Apollon77** [comment]
@sirjojo69 If you need support or just a place to unload frustration  (;-) ) we have developer groups in Discord and Telegram and also in the Forum ...

**Comment by Apollon77** [comment]
@sirjojo69 anything where we can support?

**Comment by sirjojo69** [comment]
I´m still struggeling with your recommended code change to make use of „async / await“.

Perhaps you can point me to an adapter using async/await technique, so i can learn from there….

 

 

Von: Ingo Fischer ***@***.***> 
Gesendet: Donnerstag, 8. April 2021 07:35
An: ioBroker/ioBroker.repositories ***@***.***>
Cc: sirjojo69 ***@***.***>; Mention ***@***.***>
Betreff: Re: [ioBroker/ioBroker.repositories] added awattar adapter (#986)

 

@sirjojo69 <https://github.com/sirjojo69>  anything where we can support?

**Comment by AlCalzone** [comment]
Hilft das als Startpunkt?
https://gist.github.com/AlCalzone/d14b854b69ce5e8a03718336cc650a95#

**Comment by crycode-de** [comment]
@sirjojo69 The async/await logic is quite simple.
You [main function](https://github.com/sirjojo69/ioBroker.awattar/blob/master/main.js#L85) is already marked as an async function. That's good! 

Now you should change all `adapter.setState(...)` and `adapter.setObjectNotExists(...)` calls simply to `await adapter.setStateAsync(...)` and `await adapter.setObjectNotExistsAsync(...)`.

Example:
```js
adapter.setObjectNotExists("Rawdata", { ...
```
should become
```js
await adapter.setObjectNotExistsAsync("Rawdata", { ...
```

Each `adapter.*Async` method returns a promise, which will be resolved if the asynchronous operation is done.
At each `await` you code will wait (without blocking other code parts) until the promise of the `adapter.*Async` method is resolved.

Dosing so, you can guarantee that the objects and states are set up in the right order.

An example for the async/await logic you may find here in my ioBroker.canbus adapter: https://github.com/crycode-de/ioBroker.canbus/blob/98577788574c0a5e87bb62286d586e0d5e9d8249/build/main.js#L561

**Comment by sirjojo69** [comment]
thanks for this. with this helpful hints there should be no further obstacles to implement that... i will go for it at the weekend...

**Comment by sirjojo69** [comment]
> 
> 
> @sirjojo69 The async/await logic is quite simple.
> You [main function](https://github.com/sirjojo69/ioBroker.awattar/blob/master/main.js#L85) is already marked as an async function. That's good!
> 
> Now you should change all `adapter.setState(...)` and `adapter.setObjectNotExists(...)` calls simply to `await adapter.setStateAsync(...)` and `await adapter.setObjectNotExistsAsync(...)`.
> 
> Example:
> 
> ```js
> adapter.setObjectNotExists("Rawdata", { ...
> ```
> 
> should become
> 
> ```js
> await adapter.setObjectNotExistsAsync("Rawdata", { ...
> ```
> 
> Each `adapter.*Async` method returns a promise, which will be resolved if the asynchronous operation is done.
> At each `await` you code will wait (without blocking other code parts) until the promise of the `adapter.*Async` method is resolved.
> 
> Dosing so, you can guarantee that the objects and states are set up in the right order.
> 
> An example for the async/await logic you may find here in my ioBroker.canbus adapter: https://github.com/crycode-de/ioBroker.canbus/blob/98577788574c0a5e87bb62286d586e0d5e9d8249/build/main.js#L561

sadly it seems to be not that easy.
when i replace `adapter.setObjectNotExists` with recommended `await adapter.setObjectNotExistsAsync` 
the whole adapter drashes in my test instance...

grafik

**Comment by Apollon77** [comment]
I expect that you also need to declare the "surrounding function" where the "await" is done as "async"

**Comment by sirjojo69** [comment]
thats already implemented... must be something else...

**Comment by Apollon77** [comment]
Then try stopping adapter in admin and go to cli and execute "iobroker debug awattar" ... maybe that brings better error output

**Comment by sirjojo69** [comment]
hmmmm.. that brings up the man page of command iobroker. seems that there is no command `iobroker debug [adapter]`. it seems that the iobroker command is different between a win and debian installation. my dev system is a win10 vm. i will setup a new proxmox vm to have a debian based test installation and give it a try....

**Comment by sirjojo69** [comment]
ok... i setup a debian based dev vm...
i stopped the adapter in admin and executed "iobroker debug awattar". that bings up the following error:
grafik

and this is strange, since the the surrounding function for line 120 is "main" and this function is declared as async...
grafik

**Comment by Apollon77** [comment]
The code here is running in the callbackj function on request ... which is not async :-)

see Line 112

**Comment by crycode-de** [comment]
The callback function of you request in line 112 is not an async function, like Apollon77 already mentioned.
You may change this line to
```js
request(options, async (error, resonse, body) => {
```
Note the `async` keyword ;-)

**Comment by sirjojo69** [comment]
ok... i changed that accordingly. sadly the error remains the same... did i miss another point?

**Comment by crycode-de** [comment]
Probably an other position, where you are using `await` inside a callback function.
Each function with an `await` inside have to be declared as `async`.

**Comment by sirjojo69** [comment]
perhaps you can have a second look at the repo. i did not push the recent version (since it does not work) but the only things i changed were your suggestions. so the structure remained untouched. Do you see any other callback functions?

**Comment by sirjojo69** [comment]
perhaps i should not use request at all...? 
https://stackoverflow.com/questions/45778474/proper-request-with-async-await-in-node-js

**Comment by crycode-de** [comment]
[request](https://github.com/request/request) is deprecated for a while now.
I would suggest to use [axios](https://github.com/axios/axios) instead.

Example for axios: 
```js
const axios = require('axios');

const api = axios.create({
  baseURL: adapter.config.aWATTarApiUrl
});

async function xyz () {
  const res = await api.get(`?start=...`);
  // res.data now holds your parsed json object, no need to call JSON.parse manually
}
```

I don't see any other callback (affected by the async/await logic) in your `main.js` at the moment.

**Comment by sirjojo69** [comment]
Good things come to those who wait. ;-)
i refactored everything to make use of axios and pushed it ... plz check

**Comment by crycode-de** [comment]
Now you are mixing the "normal" promise logic (`.then`) and the async/await logic.
I would suggest changing
```js
    axios({
        method: 'get',
        baseURL: urlEpoch,
        timeout: 10000,
        responseType: 'json'
    }).then(
       async (response) => {
```
to use `await` as well.

For error handling, you should wrap this into `try {...} catch (e) {...}`.


```js
    let response;
    try {
       resonse = await axios({
          method: 'get',
          baseURL: urlEpoch,
          timeout: 10000,
          responseType: 'json'
      });
    } catch (error) {
      // your error handling for axios errors
      // ...
      // return from the main function
      return;
    }

    const content = response.data;
```

Also you should set the state values with the _ack_ flag set to `true`.  
Example:
```js
await adapter.setStateAsync(stateBaseName + "start", startTime, true);
```

https://github.com/sirjojo69/ioBroker.awattar/blob/master/main.js#L338
There you aren't using the async functions. This should be changed as well imho.

**Comment by sirjojo69** [comment]
this is fixed... plz check...

**Comment by sirjojo69** [comment]
> 
> 
> @sirjojo69 Whats the status? The comments from @crycode-de are all also great. Anything where you need support?

sorry, just no time. i will try to implement @crycode-de s suggestions by next week...

**Comment by Apollon77** [comment]
@sirjojo69 Did you found time?

**Comment by sirjojo69** [comment]
Sadly not. I try to solve next issues at the weekend…

 

Von: Ingo Fischer ***@***.***> 
Gesendet: Donnerstag, 22. Juli 2021 22:26
An: ioBroker/ioBroker.repositories ***@***.***>
Cc: sirjojo69 ***@***.***>; Mention ***@***.***>
Betreff: Re: [ioBroker/ioBroker.repositories] added awattar adapter (#986)

 

@sirjojo69 <https://github.com/sirjojo69>  Did you found time?

**Comment by Apollon77** [comment]
Just ping when I should check again

**Comment by sirjojo69** [comment]
> 
> 
> Some review according to the [checklist](https://github.com/ioBroker/ioBroker.repositories/blob/master/REVIEW_CHECKLIST.md) to assist @Apollon77:
> ## Readme
> 
>     * Your readme is completely in German. In my opinion it's ok because the adapter is specific for a German service, but you should add a short description in English to let non-german people know what it is for.
> 
>     * The order of the changelog entries should be reversed. The newest entry should be on top.
> 
>     * Adjust the license information to include the current year like "Copyright (c) 2020-2021 ...".
> 
> 
> ## Testing
> 
>     * You may add Node.js 16.x to the adapter tests [here](https://github.com/sirjojo69/ioBroker.awattar/blob/master/.github/workflows/test-and-release.yml#L53)
> 
> 
> ## package.json
> 
>     * You should remove the [request dependency](https://github.com/sirjojo69/ioBroker.awattar/blob/master/package.json#L22) since you are using axios.
> 
>     * You may remove axios from _devDependencies_ since you have it in you _dependencies_.
> 
> 
> ## io-package.json
> 
>     * News and title are only translated in de and en. Maybe add the missing translations using the [ioBroker translator](https://translator.iobroker.in/) service?
> 
> 
> ## directories and files
> 
>     * Looks good to me.
> 
> 
> ## index_m.html
> 
>     * You are mixing English and German texts [here](https://github.com/sirjojo69/ioBroker.awattar/blob/master/admin/index_m.html#L100). They should be in English.
> 
>     * Your translations are missing in [words.js](https://github.com/sirjojo69/ioBroker.awattar/blob/master/admin/words.js). Consider using Weblate for the translations to get "cloud" translations from the community.
> 
> 
> ## Adapter Logic
> 
>     * Some `setStateAsync` calls may be parallelized using `await Promise.all([setStateAsync(...), ...])`.

every point has (finally) been implemented. The only thing not done was the hint for index_m.html. The only german words used there are that specific that it would be more confusing to the usual (german)  user to translate that into english. This is a phrase one could find on his bill, but not if i translate that into english....

**Comment by Apollon77** [comment]
I love to add it to the repo. Please release a new version because 1.0.5 is from november 2020. 

Here some more (optional) comments:
* there is a special "role" "json" for json data ... you might want to use that for Rawdata
* If all logic is using await correctly and such then you do not need the timeout here https://github.com/sirjojo69/ioBroker.awattar/blob/master/main.js#L376-L378
* the "desc" in io-package is still only de/en :-)

**Comment by sirjojo69** [comment]
i released 1.0.6. right even now...

**Pull request merged**
