### PR TITLE
add ioBroker.alarm sources-dist.json

### PR DESCRIPTION
**Pull request by misanorot**
Sorry but I dont understood the issues from the adapter checker.

### CODE REVIEW

**Comment by Apollon77** [comment]
> [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html

when you use selectID,js you need to also provide the mentioned file and this one is missing.

> [E503] "iob_npm.done" found in repo! Please add it to .gitignore

delete the file iob_npm.done from Github or all to gitignore file. This comes because you copied and install folder from iobroker and is not allowed to be in the git or npm package!!

> [E603] NO "## Changelog" found in README.md

Add a "## Changelog" headline/section to the readme. This is used in Admin

> [E604] No "## License" found in README.md

Add a "## License" headline/section to the readme. This is used in Admin

> [W113] Adapter should support compact mode

You implemented comact mode, but io-package.json says "compact: false"

**Comment by misanorot** [comment]
Hi Apollon77,

to E502--> thats not clear for me, it is a script that comes with the admin admin adapter. I thing the problem comes from  the script himself? 

to W113--> The compact mode is not so easy. All async things like setState and so on are very critical and im not a professinal coder. You said "You implemented comact mode", how can I prevent this? Comment out the "compact: false" in ther io-package?

The rest is done...

**Comment by GermanBluefox** [comment]
Actually I planned "alarm" word for exactly such functionality and it should be sometimes important, like scenes, javascript, devices.... 
Adapter must work :)

**Comment by Apollon77** [comment]
@GermanBluefox Can you provide infos for E502?

@misanorot Normally compact mode works as when you start the adapter normally. Yiu just need to make sure that all timouts, intervals and servers and other resources are cleared in "unload" correctly.
In fact simply enable compact mode for your iobroker machine and enable it for your instance and test if anything wors as usual

**Comment by misanorot** [comment]
@bluefox

For me it is okay when I rename my little project? When you wish. I think your idea is much much bigger than my. For me it is also okay when the adapter stay out of iobroker sources. You have to decide...

**Comment by misanorot** [comment]
> @GermanBluefox Can you provide infos for E502?
> 
> @misanorot Normally compact mode works as when you start the adapter normally. Yiu just need to make sure that all timouts, intervals and servers and other resources are cleared in "unload" correctly.
> In fact simply enable compact mode for your iobroker machine and enable it for your instance and test if anything wors as usual

Is it possible thats a little problem with v3 admin?

I think in V2 the image is here https://github.com/ioBroker/ioBroker.admin/blob/a937e0388244d18f11eaa156a0240d7c4210c2a9/www/img/info-big.png

In the selectID.js I found this ...

https://github.com/ioBroker/ioBroker.admin/blob/9d4d9303f087c8a5e40cb2263d7415828625c3bc/src/lib/js/selectID.js#L157

and this...

https://github.com/ioBroker/ioBroker.admin/blob/9d4d9303f087c8a5e40cb2263d7415828625c3bc/src/lib/js/selectID.js#L1147

the picture is in V3 here:

https://github.com/ioBroker/ioBroker.admin/blob/master/src/img/info-big.png

I am not sure if the src is correct?

**Comment by Apollon77** [comment]
The stuff from arc will be available in the www dir after building. So path should work. Check your local installed version ... there you see where Iris in the final paths

**Comment by GermanBluefox** [comment]
## Automated adapter checker
### ioBroker.alarm
 * [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html

**Comment by Apollon77** [comment]
@GermanBluefox Can you please tell more exact what the adapter dev needs to do here?

**Comment by GermanBluefox** [comment]
> @GermanBluefox Can you please tell more exact what the adapter dev needs to do here?

This file https://github.com/ioBroker/ioBroker.admin/blob/master/src/img/info-big.png must be checked in in `admin/img/info-big.png`, because it used in selectID.js

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alarm](https://github.com/misanorot/ioBroker.alarm)
[Downloads](https://www.npmjs.com/package/iobroker.alarm) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.alarm/)

- [ ] :heavy_exclamation_mark: [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html 
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "alarm" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by misanorot** [comment]
I don't know what you mean, sorry. Please help

**Comment by GermanBluefox** [comment]
Add created a Pull Request

**Comment by misanorot** [comment]
> Add created a Pull Request

oh my god, so simple......

**Comment by misanorot** [comment]
How is the status? Would Bluefox like the name "Alarm" now? Or why can't the adapter be included in the source list?

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alarm](https://github.com/misanorot/ioBroker.alarm)
[Downloads](https://www.npmjs.com/package/iobroker.alarm) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.alarm/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "alarm" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
