### PR TITLE
add webui

### PR DESCRIPTION
**Pull request by jogibear9988**
add webui

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.webui](https://github.com/iobroker-community-adapters/ioBroker.webui)
[Downloads](https://www.npmjs.com/package/iobroker.webui) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.webui/)

- [ ] :heavy_exclamation_mark: [E013] No author found in the [package.json](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/package.json)
- [ ] :heavy_exclamation_mark: [E101] [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/io-package.json) must have at least empty "native" attribute
- [ ] :heavy_exclamation_mark: [E104] No common.titleLang found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E110] Icon not found in the [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E111] extIcon not found in the [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E118] Versions in [package.json](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/package.json) and in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/io-package.json) are different
- [ ] :heavy_exclamation_mark: [E130] No news found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.webui)!. Please execute in adapter directory: `npm owner add bluefox iobroker.webui`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/iobroker-community-adapters/ioBroker.webui", press the settings button beside the about title and add some topics.
- [ ] :heavy_exclamation_mark: [E603] NO "## Changelog" found in [README.md](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E604] No `## License` found in [README.md](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 " at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E813] file src/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "webui" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jogibear9988** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.webui](https://github.com/iobroker-community-adapters/ioBroker.webui)
[Downloads](https://www.npmjs.com/package/iobroker.webui) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.webui/)

- [ ] :heavy_exclamation_mark: [E100] Cannot parse [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/io-package.json): SyntaxError: Unexpected token n in JSON at position 1850
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 jochen.kuehner@gmx.de" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E813] file src/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore


*Add comment "RE-CHECK!" to start check anew*

**Comment by jogibear9988** [comment]
@Apollon77 I think I fixed everything, but not testing.
I will not add UI tests, as I've no time to do them. And there is no backend code.

**Comment by jogibear9988** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.webui](https://github.com/iobroker-community-adapters/ioBroker.webui)
[Downloads](https://www.npmjs.com/package/iobroker.webui) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.webui/)

- [ ] :heavy_exclamation_mark: [E100] Cannot parse [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/master/io-package.json): SyntaxError: Unexpected token n in JSON at position 1850
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 jochen.kuehner@gmx.de" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E813] file src/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore


*Add comment "RE-CHECK!" to start check anew*

**Comment by jogibear9988** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.webui](https://github.com/iobroker-community-adapters/ioBroker.webui)
[Downloads](https://www.npmjs.com/package/iobroker.webui) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.webui/)

- [ ] :heavy_exclamation_mark: [E151] common.connectionType type has an invalid type none
- [ ] :heavy_exclamation_mark: [E152] common.dataSource type has an invalid type none
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 jochen.kuehner@gmx.de" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E813] file src/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "webui" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jogibear9988** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.webui](https://github.com/iobroker-community-adapters/ioBroker.webui)
[Downloads](https://www.npmjs.com/package/iobroker.webui) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.webui/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 jochen.kuehner@gmx.de" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E813] file src/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "webui" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jogibear9988** [comment]
@Apollon77 

- [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 jochen.kuehner@gmx.de" at the start of LICENSE
this is in the readme, but I've already added 2022
-  [E813] file src/ found in repository, but not found in .npmignore
it is in the npmignore
- [E816] file tsconfig.json found in repository, but not found in .npmignore
it is...

**Comment by Apollon77** [comment]
@jogibear9988 Formally you can not add a copyright for a year which is not there ...but your topic

The other two "flse positives" are ok.

For testing: The testing includes 
* check of the package files. This is needed to make sure all is current there
* check that the "npm install" of the adapter works with all deps and such  and ideally on Linux. MacOS and WIndows and with the relevant LTS nodejs versions that are supported. It is correct that "executing tests" makes no sense for an UI adapter and this can be scipped in this case, but the other two parts should be included as tests.

The tests so make sure that the adapter can be installed and not break because of invalid deps or such stuff

**Comment by jogibear9988** [comment]
RE-CHECK!

**Comment by jogibear9988** [comment]
@Apollon77 should now all been fixed

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.webui](https://github.com/iobroker-community-adapters/ioBroker.webui)
[Downloads](https://www.npmjs.com/package/iobroker.webui) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.webui/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 jochen.kuehner@gmx.de" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E813] file src/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "webui" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jogibear9988** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.webui](https://github.com/iobroker-community-adapters/ioBroker.webui)
[Downloads](https://www.npmjs.com/package/iobroker.webui) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.webui/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 jochen.kuehner@gmx.de" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E813] file src/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "webui" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by ldittmar81** [comment]
> @Apollon77
> 
> * [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 [jochen.kuehner@gmx.de](mailto:jochen.kuehner@gmx.de)" at the start of LICENSE
>   this is in the readme, but I've already added 2022
It's not in the readme it's in License
[Copyright (c) 2020 node projects](https://github.com/iobroker-community-adapters/ioBroker.webui/blob/6f61cdac9ff801ef5a4d874f1f84b2d2a630976c/LICENSE#L3)

**Comment by jogibear9988** [comment]
@ldittmar81 now it should be fixed

**Comment by jogibear9988** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.webui](https://github.com/iobroker-community-adapters/ioBroker.webui)
[Downloads](https://www.npmjs.com/package/iobroker.webui) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.webui/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.0.12
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E813] file src/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "webui" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by ldittmar81** [comment]
@jogibear9988 there is one little problem with your .npmignore

You got /test, /src, /tsconfig.json etc... but it should be test/, src/ m tsconfig.json (without /) - this ist the last point. Then its all fixed.

**Comment by Apollon77** [comment]
@AlCalzone @GermanBluefox or any other "Frontend experiences developer" ... Here I need support on the review

**Comment by jogibear9988** [comment]
the / at start I've done explicitly. I only want these directorys removed from the root.

**Comment by jogibear9988** [comment]
and why I'm not allowed to include the src in the package? If I'd like to for debugging?

**Comment by Apollon77** [comment]
Nothing against including src ...would be fully ok

**Comment by jogibear9988** [comment]
why then the error??

**Comment by jogibear9988** [comment]
is this then okay?

**Comment by AlCalzone** [comment]
> and why I'm not allowed to include the src in the package? If I'd like to for debugging?

If you want to debug, you should include the generated sourcemaps instead. The debugger will then show you the original ts sources.

**Comment by AlCalzone** [comment]
Just out of curiosity: Was that import meant to be that way?
https://github.com/iobroker-community-adapters/ioBroker.webui/blob/6f61cdac9ff801ef5a4d874f1f84b2d2a630976c/src/IobrokerWebuiAppShell.ts#L1

rather than
```ts
import '@node-projects/web-component-designer'
```

**Comment by AlCalzone** [comment]
A few more things that seem off:
https://github.com/iobroker-community-adapters/ioBroker.webui/blob/b36e356d3ed753216da055566725d617e431d655/src/IobrokerHandler.ts#L63
`await (await ...)`?

https://github.com/iobroker-community-adapters/ioBroker.webui/blob/b36e356d3ed753216da055566725d617e431d655/src/IobrokerHandler.ts#L67
That's not what `map()` is designed for. You want `forEach()`

same in the `readAllScreens` function

**Comment by jogibear9988** [comment]
> ```ts
> import '@node-projects/web-component-designer'
> ```

It is not wrong...

**Comment by jogibear9988** [comment]
> `await (await ...)`?

oh yes, typo


> That's not what `map()` is designed for. You want `forEach()`

yes, was used in another way before...

It is still a WIP, I only wanted to add it, so it could be installed from the UI.

**Comment by AlCalzone** [comment]
Maybe I wasn't clear. Your current import is
```js
'../node_modules/@node-projects/web-component-designer/dist/index.js'
```
and I proposed 
```
'@node-projects/web-component-designer'
```
instead

**Comment by Apollon77** [comment]
How do we want to continue here? @jogibear9988 are the topics addressed?

**Comment by Apollon77** [comment]
@jogibear9988 ?

**Comment by jogibear9988** [comment]
we need to wait till webui V1 is ready. Think maybe February

**Comment by Apollon77** [comment]
So should we close here and you open a new PR when done or continue with latest repo?

**Comment by ldittmar81** [comment]
@jogibear9988 close this PR and you open a new one when its ready?

**Comment by jogibear9988** [comment]
I'll open again when RC is there ready

**Pull request closed without merging**
