### PR TITLE
Added awtrix light to beta

### PR DESCRIPTION
**Pull request by klein0r**
See https://forum.iobroker.net/topic/65571/test-adapter-awtrix-light

### CODE REVIEW

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

  
- consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- check and limit configurable timeouts / intervals
  
  Node setTimeout/setInterval routines have a maximum allowed value of 2,147,483,647 ms. Using delays larger than 2,147,483,647 ms (about 24.8 days) result in the timeout being executed immediately. So all (user configurable) values passed to setTimeout / setInterval should be checked and limited.
  
  historyAppsRefreshInterval seems to have no upper limit which could cause an overflow and a n immidate trigger - at least in Theory if user enters some unreasonable big values. Consider to limit maximum value.

- adapt testing to supported node releases

  Tests for node 16 is mandatory unless you require node 18 and higher. (already OK)
  Tests for node 18 is mandatory as many users already use node 18 and node 16 will be eol and deprected Q3/2023. (already OK)
  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x],

**NOTE: none of those suggustion should be blockimng for merging the PR.** 

Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by klein0r** [comment]
@mcm1957 Thanks, fixed in 0.1.1

**Pull request merged**
