### PR TITLE
update virtualpowermeter from 1.0.0 to 1.1.1

### PR DESCRIPTION
**Pull request by Omega236**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Omega236** [comment]
? Ich weiß nicht was damit gemeint ist

**Comment by Apollon77** [comment]
Damit triggert man den Adapter-Checker ... alles gut

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.virtualpowermeter](https://github.com/Omega236/ioBroker.virtualpowermeter)
[Downloads](https://www.npmjs.com/package/iobroker.virtualpowermeter) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.virtualpowermeter/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Omega236/ioBroker.virtualpowermeter) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/Omega236/ioBroker.virtualpowermeter/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Lutz Sebastian <general.of.omega@googlemail.com>" at the end of [README.md](https://github.com/Omega236/ioBroker.virtualpowermeter/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2020 Lutz Sebastian <general.of.omega@googlemail.com>" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore


*Add comment "RE-CHECK!" to start check anew*

**Comment by Omega236** [comment]
ich habe noch dieses Problem, das ich nicht weiß wie ich es korrekt beheben soll:
https://forum.iobroker.net/topic/32262/travis-ci-error-mit-nodejs-8
@Apollon77  wie ist die richtige vorgehensweise?

**Comment by Omega236** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.virtualpowermeter](https://github.com/Omega236/ioBroker.virtualpowermeter)
[Downloads](https://www.npmjs.com/package/iobroker.virtualpowermeter) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.virtualpowermeter/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Omega236/ioBroker.virtualpowermeter) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/Omega236/ioBroker.virtualpowermeter/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore


*Add comment "RE-CHECK!" to start check anew*

**Comment by Omega236** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.virtualpowermeter](https://github.com/Omega236/ioBroker.virtualpowermeter)
[Downloads](https://www.npmjs.com/package/iobroker.virtualpowermeter) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.virtualpowermeter/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request closed without merging**
