### PR TITLE
(simatec) Add tinker monitor

### PR DESCRIPTION
**Pull request by simatec**

### CODE REVIEW

**Comment by Apollon77** [comment]
Pease fix io-package.json!! Line 38 is missing a quote

**Comment by simatec** [comment]
Fix is done ...

**Comment by Apollon77** [comment]
I would live to see one more thing: green tests :-) I know it is broken since my update because I was not able to update the package-lock.json (because I do not have a tinker hardware). So please update package-lock and then testing should get green and we can proceed. Thank you!

**Comment by DutchmanNL** [comment]
@simatec 

Please have a look at :
https://github.com/simatec/ioBroker.tinker/pull/7

**Comment by simatec** [comment]
Thanks @DutchmanNL, I did not see that ... sorry

**Comment by DutchmanNL** [comment]
> Thanks @DutchmanNL, I did not see that ... sorry

no problem that's why we are a community and help each other :)

test will still fail until you update locally on an tinker installation the package lock with npm I

I can't do that on Mac, wrong architecture :/

**Comment by simatec** [comment]
I'll do that tonight and then update to Github

**Comment by DutchmanNL** [comment]
> I'll do that tonight and then update to Github

cool ! please give an update here after that, as far I see the testing part is the only missing peace to get into stable :)

**Comment by simatec** [comment]
package-lock is now up2date ... ;-)

**Comment by simatec** [comment]
Travis CI is now green ;-)
Unbenannt

**Comment by Apollon77** [comment]
yyeeeayyy :-)

**Comment by DutchmanNL** [comment]
Cool Welcome to stable ! ;)

**Pull request merged**
