### PR TITLE
Add schedule-switcher to latest

### PR DESCRIPTION
**Pull request by Lucky-ESA**
Please add my adapter ioBroker.schedule-switcher to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

reminder 28.10.2024

**Comment by mcm1957** [comment]
@simatec 
Please take a look in respect to responsive design.
Thanks

**Comment by simatec** [comment]
Please consider migrating to admin 5 UI (jsonConfig)
Here is the Schema...

https://github.com/ioBroker/ioBroker.admin/blob/master/packages/jsonConfig/SCHEMA.md

**Comment by mcm1957** [comment]
@Lucky-ESA 
I must agree to @simatec. A short look at the admin UI looks like this UI could be configured using jsonConfig easily (2 or ther fields and a table). Please discuss with @simatec why this new adapetr should still use materialize and not start with jsonConfig.

**Comment by Lucky-ESA** [comment]
> Please consider migrating to admin 5 UI (jsonConfig)

Is implemented in release 0.0.2

**Comment by Lucky-ESA** [comment]
Release 0.0.2 is online.

**Comment by simatec** [comment]
From my side the jsonConfig looks good

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by Lucky-ESA** [comment]
RE-CHECK!

**Comment by Lucky-ESA** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] types at dependencies

  Are you sure that
  ```
      "@types/node-schedule": "^2.1.7",
      "@types/suncalc": "^1.9.2",
  ```
  is needed at user systems / needed as dependency? Most likely types are only needed during developmeng and hence liste as devDependencies. Please chak and eventually mode the dependency.

  This remark is not blocking.
  
Thanks for reading and evaluating this suggestions.
McM1957

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Pull request merged**
