### PR TITLE
register iobroker.blebox adapter

### PR DESCRIPTION
**Pull request by ka-vaNu**
Please publish my adapter to the official list.

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi, normally you first add it to the latest repository :-) Can you please add it there too?

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.blebox](https://github.com/ka-vaNu/ioBroker.blebox)
[Downloads](https://www.npmjs.com/package/iobroker.blebox) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.blebox/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "blebox" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by ka-vaNu** [comment]
> Hi, normally you first add it to the latest repository :-) Can you please add it there too?
OK, how do i commit to the latest repository? The only open branches are "master", "ocpp" and "AlCalzone-patch-8" regarding to https://github.com/ioBroker/ioBroker.repositories/branches/active

**Comment by Apollon77** [comment]
just add it to https://github.com/ioBroker/ioBroker.repositories/blob/master/sources-dist.json ... also see the README of this project ... all infos are in there :-))

**Comment by ka-vaNu** [comment]
addToLatest fails with the following message:
`C:\Workspace\ioBroker.repositories>npm run addToLatest -- --name iobroker.blebox --type iot-systems

> iobroker.repositories@1.0.4 addToLatest
> node lib/scripts.js addToLatest "--name" "iobroker.blebox" "--type" "iot-systems"


ERROR: Request failed with status code 404`

**Comment by ka-vaNu** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.blebox](https://github.com/ka-vaNu/ioBroker.blebox)
[Downloads](https://www.npmjs.com/package/iobroker.blebox) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.blebox/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "blebox" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by ka-vaNu** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.blebox](https://github.com/ka-vaNu/ioBroker.blebox)
[Downloads](https://www.npmjs.com/package/iobroker.blebox) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.blebox/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "blebox" in latest repository

### [ioBroker.nibeuplink](https://github.com/sebilm/ioBroker.nibeuplink)
[Downloads](https://www.npmjs.com/package/iobroker.nibeuplink) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.nibeuplink/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 Sebastian Haesselbarth <seb@sebmail.de>" at the end of [README.md](https://github.com/sebilm/ioBroker.nibeuplink/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Sebastian Haesselbarth <seb@sebmail.de>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by ka-vaNu** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.blebox](https://github.com/ka-vaNu/ioBroker.blebox)
[Downloads](https://www.npmjs.com/package/iobroker.blebox) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.blebox/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "blebox" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by ka-vaNu** [comment]
RE-CHECK!

**Comment by ka-vaNu** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.blebox](https://github.com/ka-vaNu/ioBroker.blebox)
[Downloads](https://www.npmjs.com/package/iobroker.blebox) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.blebox/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "blebox" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Please remove this one line https://github.com/ioBroker/ioBroker.repositories/pull/1604/files#diff-1384831e45cb5b5fc71b065c642c35169d0ee196221e07b4b81075a0d3b0aed8R131 and we are fine :)

**Comment by Apollon77** [comment]
(Latest repo gets version from npm twice a day automatically)

**Comment by ka-vaNu** [comment]
Thanks for your support, i was totally confused...

**Comment by ka-vaNu** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.blebox](https://github.com/ka-vaNu/ioBroker.blebox)
[Downloads](https://www.npmjs.com/package/iobroker.blebox) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.blebox/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "blebox" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
this message is normal because not yet approved for latest ... all fine

**Comment by Apollon77** [comment]
I will do an Adapter review next

**Comment by Apollon77** [comment]
Hi, here some review comments:

* What you do with this? https://github.com/ka-vaNu/ioBroker.blebox/blob/master/main.js#L39-L42
* Please clewanup Readme and maybe add some moer infos for the users? ;-) https://github.com/ka-vaNu/ioBroker.blebox#blebox-adapter-for-iobroker
* Please translate the io-package fields (beside news) in all languages ... you can use iobroker translation tool for it, see readme of this repo
* Please add missing config values (extLog) to io-package with the default value. But normally there are several loglevels ... why nopt use these? Users can switch debug levels. Or is it that much that you fear performance issues?
* Plesse clean all schedules, timeouts, intervals and all such in "Unload" call! Clao close all connections or other used resources!
* In onStateChange you should only react on changes with state.ack===false ... or is there a reason to also react on ack=true in your case?
* Please check all used roles ... a numbr or boolean with role "text" makes no sense! --> https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md
* For number values that have a meaning you can use common.states to give that conect for UIs ... then you could also use such nimbers for controlling commands (like your "u"/"d" and such ---> https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md#attributes-for-specific-object-types

Please check the comments and adjust. Thank you

**Comment by ka-vaNu** [comment]
[ ]     What you do with this? https://github.com/ka-vaNu/ioBroker.blebox/blob/master/main.js#L39-L42
[ ]     Please clewanup Readme and maybe add some moer infos for the users? ;-) https://github.com/ka-vaNu/ioBroker.blebox#blebox-adapter-for-iobroker
[ ]     Please translate the io-package fields (beside news) in all languages ... you can use iobroker translation tool for it, see readme of this repo
[ ]     Please add missing config values (extLog) to io-package with the default value. But normally there are several loglevels ... why nopt use these? Users can switch debug levels. Or is it that much that you fear performance issues?
[ ]     Plesse clean all schedules, timeouts, intervals and all such in "Unload" call! Clao close all connections or other used resources!
[ ]     In onStateChange you should only react on changes with state.ack===false ... or is there a reason to also react on ack=true in your case?
[ ]     Please check all used roles ... a numbr or boolean with role "text" makes no sense! --> https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md
[ ]     For number values that have a meaning you can use common.states to give that conect for UIs ... then you could also use such nimbers for controlling commands (like your "u"/"d" and such ---> https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md#attributes-for-specific-object-types

**Comment by ka-vaNu** [comment]
RE-CHECK

**Comment by ka-vaNu** [comment]
I published a new version 0.1.2 after adjusting the issues mentioned above

**Comment by ka-vaNu** [comment]
OK, thanks for the codereview & feedback. Fixed the else-block issue and send ack=true in case of updates from adapter.

**Pull request merged**
