### PR TITLE
Sonnen stable bump

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sonnen](https://github.com/foxriver76/ioBroker.sonnen)
[Downloads](https://www.npmjs.com/package/iobroker.sonnen) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sonnen/)

- [ ] :heavy_exclamation_mark: [E506] Word "IP-Address:" is not translated to russian in [admin/words.js](https://github.com/foxriver76/ioBroker.sonnen/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "IP-Address of your sonnen battery" is not translated to russian in [admin/words.js](https://github.com/foxriver76/ioBroker.sonnen/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "Poll interval (ms)" is not translated to russian in [admin/words.js](https://github.com/foxriver76/ioBroker.sonnen/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sonnen](https://github.com/foxriver76/ioBroker.sonnen)
[Downloads](https://www.npmjs.com/package/iobroker.sonnen) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sonnen/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sonnen](https://github.com/foxriver76/ioBroker.sonnen)
[Downloads](https://www.npmjs.com/package/iobroker.sonnen) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sonnen/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
