### PR TITLE
Add vds2465-server to latest

### PR DESCRIPTION
**Pull request by Hirsch-DE**

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi,

thank youfor your work, here some review comments
* Please add Bluefox as owner on npm as ciontained in the needed steps (see README of this repo)
* Please translate https://github.com/Hirsch-DE/ioBroker.vds2465-server/blob/main/io-package.json#L19-L29 with the iobroker translate tool
* Please adjust this PR and change branch to main instead master ... please also check pot other places
* Please remove https://github.com/Hirsch-DE/ioBroker.vds2465-server/blob/main/io-package.json#L82
* Why ou chose tier 3? (https://github.com/Hirsch-DE/ioBroker.vds2465-server/blob/main/io-package.json#L64) ... I think 2 is better
* it seems you decided for JSONConfig ... I think you can then remove https://github.com/Hirsch-DE/ioBroker.vds2465-server/tree/main/admin/src (pot including build scriots and setps in testing and such)
* Please provde translations for the JSONCOnfig texts ( in fact in an i18n direcory with subdir per language and a translate.json per language. You can just will en and user adapter-dev lib as translator
* why you need https://github.com/Hirsch-DE/ioBroker.vds2465-server/blob/main/main.js#L38 ? Should be unneeded
* If you do not need messages please remove https://github.com/Hirsch-DE/ioBroker.vds2465-server/blob/main/main.js#L214-L224 and also set messagebox to false in io-package
* Whats this? https://github.com/Hirsch-DE/ioBroker.vds2465-server/blob/9788a457629f842947b27e8b2373210c4f45ee23/main.js#L722-L724 ... why you need it? When you structure code correctly with awaits and such it should not be needed

Thank you for checking and adjusting

Ingo

**Comment by Hirsch-DE** [comment]
Hallo,
ich habe ein paar Anpassungen vorgenommen entsprechend der Kommentare.
Bluefox ist bei npm unter "Invitations" aufgeführt!
Message soll noch verwendet werden, daher vorhanden.
Ich hoffe, dass es jetzt soweit alles Passt.

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vds2465-server](https://github.com/Hirsch-DE/ioBroker.vds2465-server)
[Downloads](https://www.npmjs.com/package/iobroker.vds2465-server) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vds2465-server/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Hirsch-DE/ioBroker.vds2465-server/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "vds2465-server" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.adguard](https://github.com/o0shojo0o/ioBroker.adguard)
[Downloads](https://www.npmjs.com/package/iobroker.adguard) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.adguard/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/o0shojo0o/ioBroker.adguard/blob/master/io-package.json)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.chromecast](https://github.com/iobroker-community-adapters/ioBroker.chromecast)
[Downloads](https://www.npmjs.com/package/iobroker.chromecast) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.chromecast/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.chromecast/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.hue-extended](https://github.com/iobroker-community-adapters/ioBroker.hue-extended)
[Downloads](https://www.npmjs.com/package/iobroker.hue-extended) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hue-extended/)

- [ ] :heavy_exclamation_mark: [E104] No "common.titleLang" found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.hue-extended/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E145] No "common.news" found for actual version 2.0.1
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.hue-extended/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.hue-extended/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E154] common.dependencies must contain {"js-controller": ">=2.0.0"} or later - recommended: {"js-controller": ">=3.3.22"}
- [ ] :heavy_exclamation_mark: [E506] Word "bridgeType" is not translated to russian in [admin/words.js](https://github.com/iobroker-community-adapters/ioBroker.hue-extended/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E606] Current adapter version 2.0.1 not found in [README.md](https://github.com/iobroker-community-adapters/ioBroker.hue-extended/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2019-2022 zefau <zefau@mailbox.org>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.hue-extended/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2019-2022 zefau <zefau@mailbox.org>" at the start of LICENSE
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.hue-extended/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W172] "common.localLink" in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.hue-extended/blob/master/io-package.json) is deprecated. Please define object "common.localLinks": { "_default": "..." }
- [ ] :eyes: [W202] Version of [package.json](https://github.com/iobroker-community-adapters/ioBroker.hue-extended/blob/master/package.json) (2.0.1) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.hue-extended) (2.0.0)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package
- [ ] :eyes: [W302] Use github actions instead of [travis](https://travis-ci.com/)-ci

### [ioBroker.pixelit](https://github.com/pixelit-project/ioBroker.pixelit)
[Downloads](https://www.npmjs.com/package/iobroker.pixelit) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.pixelit/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/pixelit-project/ioBroker.pixelit/blob/master/io-package.json)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/pixelit-project/ioBroker.pixelit/blob/master/io-package.json)
- [ ] :eyes: [W172] "common.localLink" in [io-package.json](https://github.com/pixelit-project/ioBroker.pixelit/blob/master/io-package.json) is deprecated. Please define object "common.localLinks": { "_default": "..." }
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.sensebox](https://github.com/AlCalzone/ioBroker.sensebox)
[Downloads](https://www.npmjs.com/package/iobroker.sensebox) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sensebox/)

- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/AlCalzone/ioBroker.sensebox", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/AlCalzone/ioBroker.sensebox/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

in fact all good and I will merge it,but I would still recomment to remove admin/src* because not needed when I see it right  - together with all the admin build scripts in package.json ... In fact that might confuse because of that "dead stuff". But up to you.

Additionally the "wait loop" in https://github.com/Hirsch-DE/ioBroker.vds2465-server/blob/457a81bedd88f94361f1eb3ddc8e3f91e599c51a/main.js#L692-L695 is in my eyes till questionable. But if you want to stay that way please add at least a variable which is set to "true" when unload method is called and only continue after your loop if not already unloaded

I will merge and accept but please do the requested change.

Ingo

**Pull request merged**
