### PR TITLE
add rssfeed to latest

### PR DESCRIPTION
**Pull request by oweitman**
Please add rssfeed to latest

### CODE REVIEW

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.rssfeed](https://github.com/oweitman/ioBroker.rssfeed)
[Downloads](https://www.npmjs.com/package/iobroker.rssfeed) 
[NPM](https://nodei.co/npm/iobroker.rssfeed/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/oweitman/iobroker.rssfeed/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:oweitman/ioBroker.rssfeed.git. Expected: git+https://github.com/oweitman/iobroker.rssfeed.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/io-package.json) must be equal to "". Now is rssfeed
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.rssfeed)!. Please execute in adapter directory: "npm owner add bluefox iobroker."
- [ ] :eyes: [W400] Cannot find "" in latest repository

### [ioBroker.rssfeed](https://github.com/oweitman/ioBroker.rssfeed)
[Downloads](https://www.npmjs.com/package/iobroker.rssfeed) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.rssfeed/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:oweitman/ioBroker.rssfeed.git. Expected: git+https://github.com/oweitman/ioBroker.rssfeed.git
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.rssfeed)!. Please execute in adapter directory: `npm owner add bluefox iobroker.rssfeed`
- [ ] :eyes: [W400] Cannot find "rssfeed" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by oweitman** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.rssfeed](https://github.com/oweitman/ioBroker.rssfeed)
[Downloads](https://www.npmjs.com/package/iobroker.rssfeed) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.rssfeed/)

- [ ] :heavy_exclamation_mark: [E504] "main.js found in [package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/package.json), but not found as file
- [ ] :eyes: [W400] Cannot find "rssfeed" in latest repository

### [ioBroker.rssfeed](https://github.com/oweitman/ioBroker.rssfeed)
[Downloads](https://www.npmjs.com/package/iobroker.rssfeed) 
[NPM](https://nodei.co/npm/iobroker.rssfeed/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/oweitman/iobroker.rssfeed/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git+https://github.com/oweitman/ioBroker.rssfeed.git. Expected: git+https://github.com/oweitman/iobroker.rssfeed.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/io-package.json) must be equal to "". Now is rssfeed
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.rssfeed)!. Please execute in adapter directory: "npm owner add bluefox iobroker."
- [ ] :eyes: [W400] Cannot find "" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by oweitman** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.rssfeed](https://github.com/oweitman/ioBroker.rssfeed)
[Downloads](https://www.npmjs.com/package/iobroker.rssfeed) 
[NPM](https://nodei.co/npm/iobroker.rssfeed/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/oweitman/iobroker.rssfeed/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git+https://github.com/oweitman/ioBroker.rssfeed.git. Expected: git+https://github.com/oweitman/iobroker.rssfeed.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/io-package.json) must be equal to "". Now is rssfeed
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.rssfeed)!. Please execute in adapter directory: "npm owner add bluefox iobroker."
- [ ] :eyes: [W400] Cannot find "" in latest repository

### [ioBroker.rssfeed](https://github.com/oweitman/ioBroker.rssfeed)
[Downloads](https://www.npmjs.com/package/iobroker.rssfeed) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.rssfeed/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "rssfeed" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.rssfeed](https://github.com/oweitman/ioBroker.rssfeed)
[Downloads](https://www.npmjs.com/package/iobroker.rssfeed) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.rssfeed/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "rssfeed" in latest repository

### [ioBroker.rssfeed](https://github.com/oweitman/ioBroker.rssfeed)
[Downloads](https://www.npmjs.com/package/iobroker.rssfeed) 
[NPM](https://nodei.co/npm/iobroker.rssfeed/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/oweitman/iobroker.rssfeed/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git+https://github.com/oweitman/ioBroker.rssfeed.git. Expected: git+https://github.com/oweitman/iobroker.rssfeed.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/io-package.json) must be equal to "". Now is rssfeed
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.rssfeed)!. Please execute in adapter directory: "npm owner add bluefox iobroker."
- [ ] :eyes: [W400] Cannot find "" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by oweitman** [comment]
should i do something now?
in the comment are 2 version of the results of the adapter checker.
if i try the adapter checker then i get everything is ok, except the warning 
[W400] Cannot find "rssfeed" in latest repository

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.rssfeed](https://github.com/oweitman/ioBroker.rssfeed)
[Downloads](https://www.npmjs.com/package/iobroker.rssfeed) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.rssfeed/)

- [ ] :heavy_exclamation_mark: [E130] Too many news found in [io-package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/io-package.json). Mast be less than 21. Please remove old news.
- [ ] :eyes: [W400] Cannot find "rssfeed" in latest repository

### [ioBroker.rssfeed](https://github.com/oweitman/ioBroker.rssfeed)
[Downloads](https://www.npmjs.com/package/iobroker.rssfeed) 
[NPM](https://nodei.co/npm/iobroker.rssfeed/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/oweitman/iobroker.rssfeed/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git+https://github.com/oweitman/ioBroker.rssfeed.git. Expected: git+https://github.com/oweitman/iobroker.rssfeed.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/io-package.json) must be equal to "". Now is rssfeed
- [ ] :heavy_exclamation_mark: [E130] Too many news found in [io-package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/io-package.json). Mast be less than 21. Please remove old news.
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.rssfeed)!. Please execute in adapter directory: "npm owner add bluefox iobroker."
- [ ] :eyes: [W400] Cannot find "" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.rssfeed](https://github.com/oweitman/ioBroker.rssfeed)
[Downloads](https://www.npmjs.com/package/iobroker.rssfeed) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.rssfeed/)

- [ ] :heavy_exclamation_mark: [E130] Too many news found in [io-package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/io-package.json). Mast be less than 21. Please remove old news.
- [ ] :eyes: [W400] Cannot find "rssfeed" in latest repository

### [ioBroker.rssfeed](https://github.com/oweitman/ioBroker.rssfeed)
[Downloads](https://www.npmjs.com/package/iobroker.rssfeed) 
[NPM](https://nodei.co/npm/iobroker.rssfeed/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/oweitman/iobroker.rssfeed/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git+https://github.com/oweitman/ioBroker.rssfeed.git. Expected: git+https://github.com/oweitman/iobroker.rssfeed.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/io-package.json) must be equal to "". Now is rssfeed
- [ ] :heavy_exclamation_mark: [E130] Too many news found in [io-package.json](https://github.com/oweitman/ioBroker.rssfeed/blob/master/io-package.json). Mast be less than 21. Please remove old news.
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.rssfeed)!. Please execute in adapter directory: "npm owner add bluefox iobroker."
- [ ] :eyes: [W400] Cannot find "" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
