### PR TITLE
Please Add enigma2 Adapter to Repo

### PR DESCRIPTION
**Pull request by Matten-Matten**
"version": "1.3.2"

Gruß
Matten Matten

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.enigma2](https://github.com/Matten-Matten/ioBroker.enigma2)
[Downloads](https://www.npmjs.com/package/iobroker.enigma2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.enigma2/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Matten-Matten/ioBroker.enigma2) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/Matten-Matten/ioBroker.enigma2", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2020 Matten-Matten <matten-matten@web.de>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "enigma2" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.enigma2](https://github.com/Matten-Matten/ioBroker.enigma2)
[Downloads](https://www.npmjs.com/package/iobroker.enigma2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.enigma2/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Matten-Matten/ioBroker.enigma2) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2020 Matten-Matten <matten-matten@web.de>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "enigma2" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
@Matten-Matten please fix checker comments

**Comment by Matten-Matten** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.enigma2](https://github.com/Matten-Matten/ioBroker.enigma2)
[Downloads](https://www.npmjs.com/package/iobroker.enigma2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.enigma2/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Matten-Matten/ioBroker.enigma2) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2020 Matten-Matten <matten-matten@web.de>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "enigma2" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Ok, according to README work stopped, so I close here too

**Pull request closed without merging**
