### PR TITLE
Add waterkotte-easycon to latest

### PR DESCRIPTION
**Pull request by theknut**

### CODE REVIEW

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] unused onStateChange handler

  You configred an onStateChange handler but it looks like this handler does not do any important tasks. Please remove the handler if the adapter does not react on state changes.

- [ ] onStateChange handler ignores ack flag (NOT BLOCKING - information for future use only)

  The adapter must honor the ack flag when processing onStateChange events. Whenever the onStateChange handler is called for an own state (a state owned by the processing instance of the adapter) it must ignore this event if the ack flags is set. Only stateChanges with ack==false are allowed to be processed.

  When processing foreign states which are output of another adapter  processing must only occure if the ack flag is true.


- [ ] Is there any reason to not use i18n translation environment?
  
  I suggest to evaluate to use i18n translation environment and the iobroker/adapter-dev environment (https://github.com/ioBroker/adapter-dev#iobroker-adapter-dev). You could easyly add new strings to the english json and run ```npm run translate``` afterward. When using i18n environment activating iobrokers weblate translation system (see https://github.com/ioBrokerTranslator/doc) is trivial.  
  
  Hardcoding text inside jsonConfig blocks usage of weblate transaltion system. 

  NOTE: This is a suggestion only and nozt blocking.


- [ ] check and limit configurable timeouts / intervals
  
  Node setTimeout/setInterval routines have a maximum allowed value of 2,147,483,647 ms. Using delays larger than 2,147,483,647 ms (about 24.8 days) result in the timeout being executed immediately. So all (user configurable) values passed to setTimeout / setInterval should be checked in code and limited. Checking/limiting in code is required as config data could be changed directly or by some other adapter too, so limiting at ui level might not be sufficient.
  
  I suggest to change the paramater at ui to minutes or seconds. Users would not expect a ms parameter here.
 
  And in any case limit the interval ta UI and inside code (!) to a reasonable value. Polling too fast could result in starting a new polling cycle before the previous cycle has finished. This could result in a crash of the complet ioBroker installation due to resource problems. Please ensure that pollingIntervall cannot by smaller than the longest prosessing time of a poll loop or replace setInterval by a setTimeout started at the end of a poll. This would be the most stable solution anyway.


- [ ] Add timeout to axios calls

  All axios calls should have a timeout set. The default value for axios timeout is 0 which results in no timeout. So an unresponsive remote system could lead to an hanging adapter. Either set an appropiate timeout per axios call or set a default timeout globally for the axios instance.

  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
@theknut

How shall we continue?
Do you need any help?
Did you notice the last comment and the provided PR?

Please check andfix or at least comment the issues listed earlier 
**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

reminder 8.4.2024

**Comment by theknut** [comment]
Sorry, I was sick and didn't find the time to review it. I'm back now and will do it in the coming days.

**Comment by theknut** [comment]
All tasks have been resolved as per https://github.com/theknut/ioBroker.waterkotte-easycon/commit/4932be865f0715a2c59f5c87a1ac6bfd4185ca2e

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@theknut 

Some more feedback - sorry

- [ ] onUnload registration missing

	```this.on("unload", this.onUnload.bind(this));```

  got lost at some time. So the onUnload handler will not be called. Please (re)add. See template for details: https://github.com/ioBroker/ioBroker.example/blob/55c3807672e11b281be472120043e8f2aa656bb9/TypeScript/src/main.ts#L23

Everything else looks good. Thanks for your effort.

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

reminder 19.4.2024

**Comment by theknut** [comment]
- [x] bound onUnload via https://github.com/theknut/ioBroker.waterkotte-easycon/commit/acb311ebf1f78f08ffbb8ac2697a5de67f749c4e
- [x] updated `@iobroker/adapter-core` to `3.06` via https://github.com/theknut/ioBroker.waterkotte-easycon/commit/d9a0e2d43d51e0da0854ab2262e6f8428e486d80

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Pull request merged**
