### PR TITLE
Add sun2000-modbus to latest (replacement for #3007)

### PR DESCRIPTION
**Pull request by mcm1957**
@daolis
This is a replacement PR for #3007 which has been closed due to merge conflicts causing reasonable wrong positives

### CODE REVIEW

**Comment by mcm1957** [comment]
@daolis

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] Readme.md should contain a link to the manufacturer and/or device

  The README.md of any adapter related to device or m ultiple devices of a manufacturer should contain a link the manufacturers website and/or to a description of the device. This is to anable new users to easily check wether they associate the adapter with the correct device(s). (See https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository paragraph 4.)

- [ ] unusual usage of admin columns

  Usage of adminColumns is very unusual. It looks like you are trying to display configuration data. As space at objects tab is very limits adminCOlumns sholud be used only if they provide a big beneit for users. Headers must be as short as possible and not be longer than typical data.
  I suggest to remove adminColumns completly for this adapter. Otehrwise please specify why you think thea provide what benefit to users.

- [ ] avoid usage of setObject

  setObject(Async) creates a new object whenever it is called. You should avoid using setObject unless you really want to create new objects. Creating a new object deletes any userConfig, i.e. configures history logging which is most likely not desired. Most likely either setObjectNotExists oder (even better in most cases) extendObject should be used. Extend Object ensures that attributes like role, read/write flag etc. are set as specified and hence extendObjet shul dbe preferred when called onece during startup of the adapter.

  see https://github.com/daolis/ioBroker.sun2000-modbus/blob/bef1ac1388cf1f0893abd48f820bd38a703d4912/src/lib/states.ts#L283
 
- [ ] unused onStateChange handler

  You configred an onStateChange handler but it looks like this handler does not do any important tasks. Please remove the handler if the adapter does not react on state changes.

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whnever a dedicated role exists.

  model name should be info.name
  serial number should be info.serial
  etc. 

  writeable states make no sense as no processing is implemented, i.e.
  https://github.com/daolis/ioBroker.sun2000-modbus/blob/bef1ac1388cf1f0893abd48f820bd38a703d4912/io-package.json#L288

  Please review and check all roles.

  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
Any news?
Do you need help?
reminder 31.12.2023

**Comment by daolis** [comment]
Hi, sorry, for the late answer.
Wanted to do it in vacation, but now i'm sick.
Will do it when im fit again.

**Comment by mcm1957** [comment]
> @mcm1957 Hi, sorry, for the late answer. Wanted to do it in vacation, but now i'm sick. Will do it when im fit again.

No problem at all. Thanks for the feedback.

And first all get healthy again soon.
My best wishes

mcm1957

**Comment by mcm1957** [comment]
reminder 31.01.2024

**Comment by daolis** [comment]
@mcm1957 I created a PR with the requested changes. Could you pls take a look.. Thanks
https://github.com/daolis/ioBroker.sun2000-modbus/pull/27

If all is ok, then i will merge it and create a new release...

**Comment by mcm1957** [comment]
Changes look good at a quick scan.

**Please add a comment when you have merged**

**Comment by daolis** [comment]
@mcm1957 Merged and created release 0.0.2

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

**Comment by daolis** [comment]
Thank you Martin for the support!

**Pull request merged**
