### PR TITLE
Update zendure-solarflow to 1.8.8

### PR DESCRIPTION
**Pull request by nograx**
Please update my adapter ioBroker.zendure-solarflow to version 1.8.8.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
node.js 22 tests are missing.
Please merge https://github.com/nograx/ioBroker.zendure-solarflow/pull/69

A new release is not yet required, but tests should pass using github head revisions

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by nograx** [comment]
RE-CHECK!

**Pull request merged**
