### PR TITLE
VIS Material Advanced reached stable

### PR DESCRIPTION
**Pull request by EdgarM73**
see forum https://forum.iobroker.net/topic/37235/vis-material-advanced-widgets/25

regards
E

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/iobroker-community-adapters/ioBroker.vis-material-advanced.git. Expected: git+https://github.com/EdgarM73/ioBroker.vis-material-advanced.git
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Please check the warnings and fix them

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/ioBroker/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: 404

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/iobroker-community-adapters/ioBroker.vis-material-advanced.git. Expected: git+https://github.com/EdgarM73/ioBroker.vis-material-advanced.git
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
The URL needs to be https://github.com/iobroker-community-adapters/ioBroker.vis-material-advanced

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/ioBroker/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: 404

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/iobroker-community-adapters/ioBroker.vis-material-advanced. Expected: git+https://github.com/EdgarM73/ioBroker.vis-material-advanced.git
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
... still not changed ?!

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/ioBroker/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: 404

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/iobroker-community-adapters/ioBroker.vis-material-advanced. Expected: git+https://github.com/EdgarM73/ioBroker.vis-material-advanced.git
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@EdgarM73 you need to pussh the changes if you do some ... or simply close and recreate the PR

**Pull request closed without merging**
