### PR TITLE
add anel hut to latest

### PR DESCRIPTION
**Pull request by dan1-de**
Hi, 
please add my adapter for anelhut to stable. 
This adapter was tested with the developer of anel. 
All devices are working.

Br
Daniel

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.anelhut](https://github.com/dan1-de/ioBroker.anelhut)
[Downloads](https://www.npmjs.com/package/iobroker.anelhut) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.anelhut/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal


*Add comment "RE-CHECK!" to start check anew*

**Comment by dan1-de** [comment]
Sorry, but I have no logo with same width and height.

**Comment by Apollon77** [comment]
Hello, here are my review comments:
* please add  the default values for all configation options to io-package native https://github.com/dan1-de/ioBroker.anelhut/blob/main/io-package.json#L75-L78
* I know that it will be manual work but would it not be better to encrxpt the passwords stored here? I'm sorry but the auto-encrypt feature from cointroller can not be used in "arrays" :-(
* it seems that info.connection is missing as object? https://github.com/dan1-de/ioBroker.anelhut/runs/2058555301#step:6:233 ... ideally add it to instanceObjects in io-package
* is the subscribe here https://github.com/dan1-de/ioBroker.anelhut/blob/75a6aee8e3dadb5f18d3a2a70da5b4cb70b9b2b9/src/main.ts#L118 really to be executed on every update? SHould not be a bigger issue, but still strange
* I think it needs unneeded calls that you check the object existence on every write ... I think this is enough once (you can use a map /Objects-keys to remember which object was created/checked already for instance. Same for all the devices/channels in update method
* I also think that the template code https://github.com/dan1-de/ioBroker.anelhut/blob/75a6aee8e3dadb5f18d3a2a70da5b4cb70b9b2b9/src/main.ts#L236-L282 can easiely be removed, or ?! ;-)
* * you need to clear all timeout and connections in https://github.com/dan1-de/ioBroker.anelhut/blob/75a6aee8e3dadb5f18d3a2a70da5b4cb70b9b2b9/src/main.ts#L288-L299 (e.g. the socket/dgram you open in your communication class
* I would also see it as best practice to add a try catch around the socket bin call because it can fail if the port is already used or such.

Please check the comments and adjust accordingly. Please poke here again when I should have another look

**Comment by Apollon77** [comment]
for 1.) best conact use in Telegram or Discord ... there are developer groups

for 2.) I would simply make a object "createdObjects={};" and as soon as you create one set the ID there as true and check if it is set 

I will re-reiew the next days

**Comment by dan1-de** [comment]
HI @Apollon77, 

can we move this to latest ?

**Comment by Apollon77** [comment]
Can you please check the testing of your adapter. The last tests failed ... And yes afte rthis we can go ahead

**Comment by dan1-de** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.anelhut](https://github.com/dan1-de/ioBroker.anelhut)
[Downloads](https://www.npmjs.com/package/iobroker.anelhut) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.anelhut/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal


*Add comment "RE-CHECK!" to start check anew*

**Comment by dan1-de** [comment]
@Apollon77 
I can not run the unit tests. Is this an error with the CI toolchain ?
See: https://github.com/dan1-de/ioBroker.anelhut/pull/17/checks?check_run_id=3154532029

**Comment by Apollon77** [comment]
@dan1-de just remove testing for nodejs 10 and add node.js 16 ... nodjes 10 is eol

**Comment by Apollon77** [comment]
Please just poke when I should have another look

**Comment by dan1-de** [comment]
Hi @Apollon77, 

I removed the node v10 and the tests are working now with node v12 & v14.
image

**Comment by Apollon77** [comment]
Great, then welcome. Would be awesome if you can check the topics listed above, but no showstoppers

**Pull request merged**
