### PR TITLE
add intex

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.intex](https://github.com/TA2k/ioBroker.intex)
[Downloads](https://www.npmjs.com/package/iobroker.intex) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.intex/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "intex" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

review result:
* sleep issue vs unload (like in other adapter https://github.com/TA2k/ioBroker.intex/blob/master/main.js#L210
* please remember created objects :-) https://github.com/TA2k/ioBroker.intex/blob/master/main.js#L229 (not a must .... up to you, performance topic )

**Comment by TA2k** [comment]
sleep timer fixed
will not improve the object creation for now

**Comment by Apollon77** [comment]
Please also release to npm

**Comment by TA2k** [comment]
done

**Pull request merged**
