### PR TITLE
Add radar-trap to latest

### PR DESCRIPTION
**Pull request by Steiger04**

### CODE REVIEW

**Comment by mcm1957** [comment]
Link to adapter repo: https://github.com/Steiger04/ioBroker.radar-trap

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.radar-trap](https://github.com/Steiger04/ioBroker.radar-trap)
[Downloads](https://www.npmjs.com/package/iobroker.radar-trap) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.radar-trap/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.radar-trap)!. Please execute in adapter directory: `npm owner add bluefox iobroker.radar-trap`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Steiger04/ioBroker.radar-trap/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "radar-trap" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- errors reported by adapter checker must be fixed

  Especially error  ```[E201] Bluefox was not found in the collaborators on NPM!.``` must be fixed. If you just invited Bluefox its ignore to wait for his reaction. Please state that the invitation has been sent in this case.
  
- Readme.md is very short

  The README.md of this adapter is very minimalistic. Please add a description of the configuration of the adapter. If you provide an external documentation - which should be located at doc/xx directory - please add links to at least the english documentation.

  Readme states 'radar-trap visualizes regional reports' - please add at least the most importent sources the adapter uses to the documentation. If the adapter sends informations about routes (and hence personal informations) the users should be informaed which systems / providers get this information. 

  Please add information about the areas / countries the adapter provides information for.


- consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- check and limit configurable timeouts / intervals
  
  Node setTimeout/setInterval routines have a maximum allowed value of 2,147,483,647 ms. Using delays larger than 2,147,483,647 ms (about 24.8 days) result in the timeout being executed immediately. So all (user configurable) values passed to setTimeout / setInterval should be checked and limited.
  
- check and limit intervals used to access cloud services
  
  Limit all intervals used to access cloud services to a reasonable value. If users configure an inapprobiate access rate this could lead to suspending the service by the provider for all ioBroker users.  

  I'm not sure how the scheduler configuration is created. So I leave this remark active. If the limits are already limited / fixed at reasonable values, please ignore.
  
- adapt testing to supported node releases

  Tests for node 16 is mandatory unless you require node 18 and higher. (already OK)
  Tests for node 18 is mandatory as many users already use node 18 and node 16 will be eol and deprected Q3/2023. (already OK)
  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x],

- github dependabot support ids disabled
  
  Please consider setting up dependabot support (and to ease life the workflow auto-merge.yml). Dependabot will ensure that your adapter uses the most recent versions of external packages and avoids problem due to outdted base libraries. Dependabit provides PRs at you repository to update the dependencies. Depending on you setting, especially on auto-merge.yml configuration no or only minor revisions will be outmatically merged into you main branch. All major revisions must (ans should) be reviewed by you.

   On the other side this recommandation is NO blocking point for accepting the adapter. So if you really prefer to manualle check for updates (and have time tzo do it) you might use this way too.
  
  
Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by Steiger04** [comment]
@mcm1957  Danke für Dein Feedback. Ich habe jetzt folgendes gemacht:

1.  Doku als GitHub-Wiki ergänzt und in der README verlinkt. 
2.  test-and-release.yaml angepasst (Node.js 18.x und 20.x)
3. bluefox als maintainer vorgeschlagen 
image

Bei setTimeout/setInterval ist aus meiner Sicht eigentlich alles fein. Ich nutze server-seitig croner als Package für die Cronjobs und auch setInterval wird verwendet. Beim unload wird dann aber alles aufgeräumt. 

```
private onUnload(callback: () => void): void {
		try {
			Scheduler.deleteAll();

			this.unsubscribeStatesAsync("*").catch((ex) => console.log(ex));

			server.close();
			this.setStateAsync("info.connection", false, true).catch((ex) =>
				console.log(ex),
			);

			callback();
		} catch {
			callback();
		}
	}
```
mit
```
static deleteAll(): void {
		for (const _schedule of Scheduler.#scheduleMap.values()) {
			if (_schedule.interval !== null) {
				clearInterval(_schedule.interval);
			}

			_schedule.cronJob.stop();
		}

		Scheduler.#scheduleMap.clear();
	}
```

**Comment by Steiger04** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.radar-trap](https://github.com/Steiger04/ioBroker.radar-trap)
[Downloads](https://www.npmjs.com/package/iobroker.radar-trap) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.radar-trap/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.radar-trap)!. Please execute in adapter directory: `npm owner add bluefox iobroker.radar-trap`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Steiger04/ioBroker.radar-trap/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "radar-trap" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.radar-trap](https://github.com/Steiger04/ioBroker.radar-trap)
[Downloads](https://www.npmjs.com/package/iobroker.radar-trap) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.radar-trap/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.radar-trap)!. Please execute in adapter directory: `npm owner add bluefox iobroker.radar-trap`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Steiger04/ioBroker.radar-trap/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "radar-trap" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
> Bei setTimeout/setInterval ist aus meiner Sicht eigentlich alles fein.

Das stimmt soweit ich es sehen kann. Allerdings bieten die von ioBroker zur Verfügung gestellten Routinen noch ein zusätzliches Netz (automatisches Cleanup und Werteprüfung). Daher sind sie zu empfehlen - blocking ist das aber definitiv nicht.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.radar-trap](https://github.com/Steiger04/ioBroker.radar-trap)
[Downloads](https://www.npmjs.com/package/iobroker.radar-trap) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.radar-trap/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.radar-trap)!. Please execute in adapter directory: `npm owner add bluefox iobroker.radar-trap`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Steiger04/ioBroker.radar-trap/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "radar-trap" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Steiger04** [comment]
@mcm1957 Muss ich denn jetzt noch irgendetwas tun, außer etwas Geduld zu haben?

**Comment by mcm1957** [comment]
Bluefox muss m.W. nach OWNER Rechte haben. Kann final nur @Apollon77 beantworten.

Rechte sollen sicherdtellen dass bei "Verschwinden" des Devs der Name im NOM nicht blockiert bleibt ohne dass jemand den Adapter wartet.

**Comment by Apollon77** [comment]
Also ja, warten und bitte - siehe Readme - Bluefix auf npm als Maintainer mit einladen.

**Comment by Steiger04** [comment]
@Apollon77 Über `npm owner add bluefox iobroker.radar-trap` gibt es unter win11 immer Schimpfe,

`npm ERR! owner mutate Error getting user data for bluefox
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://registry.npmjs.org/-/user/org.couchdb.user:bluefox`

deshalb hab ich bluefox unter npm ja auch direkt invited (s.o.). Rr müsste  jetzt eine Email bekommen haben und einmal klicken und dann wäre doch alles gut und ich könnte noch einmal einen RE-CHECK machen, damit Du Dir den Code nochmal anschauen  und ggf. ein bisschen meckern kannst, richtig?

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.radar-trap](https://github.com/Steiger04/ioBroker.radar-trap)
[Downloads](https://www.npmjs.com/package/iobroker.radar-trap) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.radar-trap/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.radar-trap)!. Please execute in adapter directory: `npm owner add bluefox iobroker.radar-trap`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Steiger04/ioBroker.radar-trap/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "radar-trap" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Steiger04** [comment]
@GermanBluefox Kansnt Du bitte die npm-Einladung annehmen. Du müsstest via npm eine Email bekommen haben. Danke.

**Comment by Steiger04** [comment]
@mcm1957 @Apollon77 Irgendwie tut sich bei bluefox und npm nichts. Muss ich ihn irgendwie anders kontaktieren, oder wie läuft das? Kurzes feedback wäre nett.

**Comment by mcm1957** [comment]
Von deiner Seite her soweit ich sehen kann alles ok. Latest Requestvstauen sichvzur Zeit nur bei Apollon77. Er gibt Bescheid wenn fu doch noch was tin musst. Hat auchvguten Draht zu GermanBlueFox :-)

**Comment by mcm1957** [comment]
@bluefox seems to be still missing:
```
E:\GitHub\iobroker-community-adapters\ioBroker.fronius>npm owner ls iobroker.radar-trap
steiger04 <steiger04@posteo.de>

E:\GitHub\iobroker-community-adapters\ioBroker.fronius>
```

Please execute the following command at commandline once more:
```npm owner add bluefox iobroker.radar-trap```

**Comment by Steiger04** [comment]
@mcm1957 Wenn ich `npm owner add bluefox iobroker.radar-trap` aufrufe bekomme ich immer die oben schon gezeigte Fehlermeldung, deshalb habe ich ja bluefox direkt über npm eingeladen, nur eben noch keine Antwort erhalten. Irgendeine Idee wie ich die Fehlermeldung wegbekomme?

**Comment by mcm1957** [comment]
Nö leider keine Ahnung.
Am besten warten bis sich das Apollon77 ansehen kann.

**Comment by Steiger04** [comment]
@Apollon77 Hast Du eventuell eine Idee wie ich den Fehler wegbekomme? bluefox reagiert ja nicht auf die direkte npm-Einladung.

**Comment by mcm1957** [comment]
Apollon77 wird sich das nach seinem Urlaub ansehen. Bitte noch etwas Geduld.
Danke

**Comment by Apollon77** [comment]
Bitte shcik ihm die einladung nochmal ... scheinbar war sie abgelaufen

**Comment by Steiger04** [comment]
@Apollon77 Habe gerade bluefox auf npm neu eingeladen. Hoffentlich klappt es jetzt.  Melde dich, wenn ich noch was tun muss.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.radar-trap](https://github.com/Steiger04/ioBroker.radar-trap)
[Downloads](https://www.npmjs.com/package/iobroker.radar-trap) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.radar-trap/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Steiger04/ioBroker.radar-trap/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "radar-trap" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-REVIEW

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- Readme.md / Documentation **(NEW)**

  As ioBroker is an international software an english Readme is mandatory. As you moved the documentation to the wiki (what is ok in my opinnon) and english documentation within the wiki is required too.

  So either add a (minimal) documentation in english languge into README.md or ass an eglish documentation using the wiki andprovide an link at README.md
 
- consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
   see first review (NOTE: non blocking for accaptance) 

- check and limit configurable timeouts / intervals
  
   did not check again, see first review, might be solved.
  
- check and limit intervals used to access cloud services
  
   did not check again, see first review, might be solved.
  
- github dependabot support ids disabled
  
   see first review (NOTE: non blocking for accaptance) 
  
  
Thanks for reading and evalutaing these suggestions.
McM1957

**Comment by Steiger04** [comment]
@mcm1957 Im neuen Release v1.0.4 gibt es in der README.md einen neuen Link auf die englische Version des Wiki.
@Apollon77  Es gibt eine relevante Stelle (s.o.), wo server-seitig setInterval genutzt wird. Dabei ist sichergestellt, dass clearInterval mit onUnload() alles vor einem unload aufräumt. Es gibt also erstmal keine Notwendigkeit für eine Änderung an dieser Stelle, meine ich. Wenn es hier noch Diskussionsbedarf gibt, oder noch etwas anderes gemacht werden muss, dann jederzeit hier melden. Danke.

**Pull request merged**
