### PR TITLE
add myenergi

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.myenergi](https://github.com/TA2k/ioBroker.myenergi)
[Downloads](https://www.npmjs.com/package/iobroker.myenergi) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.myenergi/)

:thumbsup: No errors found

### [ioBroker.myenergi](https://github.com/iobroker-community-adapters/ioBroker.myenergi)
[Downloads](https://www.npmjs.com/package/iobroker.myenergi) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.myenergi/)

- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/iobroker-community-adapters/ioBroker.myenergi", press the settings button beside the about title and add some topics.
- [ ] :heavy_exclamation_mark: [E606] Current adapter version 0.0.2 not found in [README.md](https://github.com/iobroker-community-adapters/ioBroker.myenergi/blob/master/README.md)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.myenergi/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "myenergi" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.myenergi](https://github.com/TA2k/ioBroker.myenergi)
[Downloads](https://www.npmjs.com/package/iobroker.myenergi) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.myenergi/)

:thumbsup: No errors found

### [ioBroker.myenergi](https://github.com/iobroker-community-adapters/ioBroker.myenergi)
[Downloads](https://www.npmjs.com/package/iobroker.myenergi) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.myenergi/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.myenergi/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "myenergi" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Please fix building an testing

**Pull request merged**
