### PR TITLE
Add sia and contactid adapter to stable Version

### PR DESCRIPTION
**Pull request by schmupu**

### CODE REVIEW

**Comment by schmupu** [comment]
No, it is not possible to add the adapters to the discovery adapter. Both listen on a givin port for incoming messages.

**Comment by GermanBluefox** [comment]
But if they can listen, can they answer on requests?

пн, 27 авг. 2018 г., 22:36 schmupu <notifications@github.com>:

**Comment by schmupu** [comment]
The contactid and sia adpater are „server“ and waiting for a connection from alarm system. It does not matter if the request comes from an Abus, Lupusec or other alarmsystem. The alarm system IP address will not be provided and needed in the contactid and sia adpater configuration.

Process:

1. **Alarmsystem (client)** ---- sends contatactid/sia message -----> **ioBroker (contacted/sia adapter)**
2. **ioBroker (contacted/sia adapter)**  -----  sends a ack ----->  **Alarmsystem (client)**
3.

**Comment by Apollon77** [comment]
Aahh so communication is started by the alarmsystem ... then yes ... :-(

**Pull request merged**
