### PR TITLE
add adapter fuelpricemonitor to latest

### PR DESCRIPTION
**Pull request by HGlab01**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) 
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "fuelpricemonitor" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by HGlab01** [comment]
Both info are available in https://github.com/HGlab01/ioBroker.fuelpricemonitor/blob/master/io-package.json
E150: https://github.com/HGlab01/ioBroker.fuelpricemonitor/blob/master/io-package.json#L52
E152: https://github.com/HGlab01/ioBroker.fuelpricemonitor/blob/master/io-package.json#L53

RE-CHECK

**Comment by HGlab01** [comment]
RE-CHECK

**Pull request closed without merging**
