### PR TITLE
add weather-warnings to latest

### PR DESCRIPTION
**Pull request by ticaki**
todo:

- [x] English Readme.md: My daughter is translating the readme for me right now, it may take a few more days.

### CODE REVIEW

**Comment by ticaki** [comment]
English readme is ready. If the adapter would be ok for you, I would create a new release on Saturday evening.

**Comment by mcm1957** [comment]
README.md does not effect release. Feel free to create a release whenever something is fixed / updated.

**Comment by mcm1957** [comment]
lgtm

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter <name> <version>" to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, ist OK to continue using this topic too.

**Pull request merged**
