### PR TITLE
Update minuvis to 2.3.3 at stable

### PR DESCRIPTION
**Pull request by SVallant**

### CODE REVIEW

**Comment by mcm1957** [comment]
@SVallant 

Your adapter https://github.com/minukodu/ioBroker.minuvis does not use standard iobroker testing.

Please see requirements https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository

```
Adapter needs to have at least Adapter basic testing (installing, running) using GitHub actions. More information in forum from apollon77 (Just take from other adapters the samples)
```

You may copy the ```test-and-release.yml``` workflow from the example adapter or newly created adapter. If you need help, please let uas know.

Please feel free if you need any help setting up standard testing and / or if you prefer a PR to fix this.

**Please add a comment when you have reviewed and fixed the suggestion or at least commented the suggestions and you think the adapter is ready for a re-review**

**Comment by SVallant** [comment]
clase pull request, adpater does not have standard iobroker testing.

**Comment by mcm1957** [comment]
Why did you close the PR.

Standard GH testing is required for all Adapters and should not be a big problem.
If you need any help, please let us know.

Or do you want the adapter to be removed from the repositories?

**Comment by SVallant** [comment]
i closed this because i have to update the adapter and then a have new version number
is this wrong ?

_Or do you want the adapter to be removed from the repositories?_ NO

**Comment by mcm1957** [comment]
Updates to the adapter repository are needed.

A new version is NOT needed as long the tests do not show a problem with the adapter. The std. github tests are run at every commit, so even adding a space to README.md will trigger them.

If no change to code is required no new release is required. 

Most likely the lint check will throw issues. Its OK to disable it at the first pass (lint:false at workflow). But I strongly suggest to enable it later and fix the issues. As this will require code changes (and even if only changeing single an ddouble quortes) a test is strongly recommended. So if linter throws issues I suggest to disable it now to minimize your workload, create a issue and process it when you are working at the adapter the next time.

Martin (mcm1957)

**Comment by SVallant** [comment]
ok

**Comment by mcm1957** [comment]
Sorry for late feedback.

I must revise my reqeust to add standard ioBroker github testing. I just detected that your adapetr deos NOT provide any adapter code, it contains only a www component. So standard github tests do not provide any testing / are not possible at all.

Sorry for the fact that I dod not notice that at the first look.

I'll continuie with the stable upgrade now.

**Comment by mcm1957** [comment]
2.3.3 created 04.04.2023
OK

**Pull request merged**
