### PR TITLE
Alexa-shoppinglist Adapter

### PR DESCRIPTION
**Pull request by MiRo1310**
https://forum.iobroker.net/topic/52705/test-adapter-adapter-alexa-shoppinglist-v0-1-x-github-latest

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alexa-timer-vis](https://github.com/MiRo1310/ioBroker.alexa-timer-vis)
[Downloads](https://www.npmjs.com/package/iobroker.alexa-timer-vis) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alexa-timer-vis/)

:thumbsup: No errors found

### [ioBroker.zoneminder](https://github.com/iobroker-community-adapters/ioBroker.zoneminder)
[Downloads](https://www.npmjs.com/package/iobroker.zoneminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.zoneminder/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/io-package.json). Must be removed.
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E154] common.dependencies must contain {"js-controller": ">=2.0.0"} or {"js-controller": ">=3.0.0"}
- [ ] :heavy_exclamation_mark: [E504] "main.js found in [package.json](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.zoneminder) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 MeisterTR <meistertr.smarthome@gmail.com>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.zoneminder/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 MeisterTR <meistertr.smarthome@gmail.com>" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore

### [ioBroker.zwave2](https://github.com/AlCalzone/ioBroker.zwave2)
[Downloads](https://www.npmjs.com/package/iobroker.zwave2) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.zwave2/)

:thumbsup: No errors found

### [io-package.json](https://github.com/controller/io-package.json)
[Downloads](https://www.npmjs.com/package/io-package.json) 
[NPM](https://nodei.co/npm/io-package.json/)

- [ ] :heavy_exclamation_mark: 404: Invalid URL

### [ioBroker.ems-esp](https://github.com/tp1de/ioBroker.ems-esp)
[Downloads](https://www.npmjs.com/package/iobroker.ems-esp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ems-esp/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/tp1de/ioBroker.ems-esp/blob/master/io-package.json). Must be removed.

### [ioBroker.jarvis](https://github.com/Zefau/ioBroker.jarvis)
[Downloads](https://www.npmjs.com/package/iobroker.jarvis) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.jarvis/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 3.0.12-beta.1
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)

### [ioBroker.openligadb](https://github.com/oweitman/ioBroker.openligadb)
[Downloads](https://www.npmjs.com/package/iobroker.openligadb) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.openligadb/)

:thumbsup: No errors found

### [ioBroker.hikvision-alarmserver](https://github.com/raintonr/ioBroker.hikvision-alarmserver)
[Downloads](https://www.npmjs.com/package/iobroker.hikvision-alarmserver) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hikvision-alarmserver/)

- [ ] :heavy_exclamation_mark: [E407] Meta URL(latest) must be equal to https://raw.githubusercontent.com/raintonr/ioBroker.hikvision-alarmserver/main/io-package.json

### [ioBroker.resol](https://github.com/Grizzelbee/ioBroker.resol)
[Downloads](https://www.npmjs.com/package/iobroker.resol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.resol/)

- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/Grizzelbee/ioBroker.resol/master/
- [ ] :heavy_exclamation_mark: [E426] Icon(stable) must be in the following path: https://raw.githubusercontent.com/Grizzelbee/ioBroker.resol/master/

### [ioBroker.alexa-shoppinglist](https://github.com/MiRo1310/ioBroker.alexa-shoppinglist)
[Downloads](https://www.npmjs.com/package/iobroker.alexa-shoppinglist) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.alexa-shoppinglist/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "alexa-shoppinglist" in latest repository

### [ioBroker.eusec](https://github.com/bropat/ioBroker.eusec)
[Downloads](https://www.npmjs.com/package/iobroker.eusec) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.eusec/)

:thumbsup: No errors found

### [ioBroker.shelly](https://github.com/iobroker-community-adapters/ioBroker.shelly)
[Downloads](https://www.npmjs.com/package/iobroker.shelly) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.shelly/)

:thumbsup: No errors found

### [ioBroker.ws](https://github.com/ioBroker/ioBroker.ws)
[Downloads](https://www.npmjs.com/package/iobroker.ws) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ws/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

here some review feedback:
* (Must change) The usage of "states" (e.g. https://github.com/MiRo1310/ioBroker.alexa-shoppinglist/blob/main/io-package.json#L170-L173) is formally only defined for number states! And IF it would work then https://github.com/MiRo1310/ioBroker.alexa-shoppinglist/blob/main/io-package.json#L174 is wrong because the value should be "time" instead!
* (Must change) Please remove https://github.com/MiRo1310/ioBroker.alexa-shoppinglist/blob/main/main.js#L33 because you now have regstered two event receivers ... I think the unused one can be removed
* (Feedback/Optional) you can add some more keywords to https://github.com/MiRo1310/ioBroker.alexa-shoppinglist/blob/main/io-package.json#L75 :-)) "alexa", "shoppinglist" would be the obvious ones ;-)
* (Feedback/Optional) The initialization of these two variables here is done async ...https://github.com/MiRo1310/ioBroker.alexa-shoppinglist/blob/main/main.js#L78-L90 ... and other asyn ccode then uses them later ... honestly ... this can work ... or not and is a complete "timing" topic. You might want to rethink that
* (Feedback/Optional) The try/catch in https://github.com/MiRo1310/ioBroker.alexa-shoppinglist/blob/main/main.js#L394-L402 is useless because will never have any effect ebcause nothing is awaited
* (Feedback/Optional) catching error but not logging it will make it near to impossible to you to debug anything ... You might want to add logs
* Do you miss somre more state.ack===false checks in https://github.com/MiRo1310/ioBroker.alexa-shoppinglist/blob/main/main.js#L321-L346 ?

Honestly, why do you use this callback/async-await mix in your code? Just stick with async await and everything will be much more easy and straight forward :-)

Please at least change the must topics, but in fact the code is would need some more rework

**Comment by Apollon77** [comment]
@MiRo1310 Anything I/we can support with?

**Comment by MiRo1310** [comment]
@Apollon77 
Hi vielen Dank der Nachfrage. 
Soweit habe ich alle Punkte erledigt, bis auf Punkt 4. und ganz unten der Punkt das ich async und callback vermischt habe. 
Wie könnte ich das anders machen? Da ich Anfänger bin weiß ich das nicht, Bzw habe keine Idee dazu.

**Comment by Apollon77** [comment]
Für #4 und auch generell: Du hast einige stellen wo du mit async und dann "await logik()" arbeitest. Früher hat man das mit callbacks gemacht. Du mischst beides mal so und mal so. AM Ende ist es mit Callback - wie bei ä4 so das der code im callback ausgeführt wird wenn das Kommando dfertig ist.

also ein

```
getState(id, (err, state) => {
  do something(state);
});
```

ist das gleiche wie

```
const state = await getStateAsyc(id);
do something(state)
```

Anders ist das Error handling ... im callback machst einfach `if(err)` ... beim await ists ein try/catch drumrum.

Damit kannst Du alles mit nem callback entsprechend aucf await umbauen , womit du das in #4 angemerkte fixen kannst weil die funktion schon async ist ...

verstanden?

**Comment by MiRo1310** [comment]
> Für #4 und auch generell: Du hast einige stellen wo du mit async und dann "await logik()" arbeitest. Früher hat man das mit callbacks gemacht. Du mischst beides mal so und mal so. AM Ende ist es mit Callback - wie bei ä4 so das der code im callback ausgeführt wird wenn das Kommando dfertig ist.
> 
> also ein
> 
> ```
> getState(id, (err, state) => {
>   do something(state);
> });
> ```
> 
> ist das gleiche wie
> 
> ```
> const state = await getStateAsyc(id);
> do something(state)
> ```
> 
> Anders ist das Error handling ... im callback machst einfach `if(err)` ... beim await ists ein try/catch drumrum.
> 
> Damit kannst Du alles mit nem callback entsprechend aucf await umbauen , womit du das in #4 angemerkte fixen kannst weil die funktion schon async ist ...
> 
> verstanden?

**Comment by MiRo1310** [comment]
@Apollon77 
Ja das habe ich soweit verstanden.
Ich werde das mal umbauen und sage dir dann Bescheid

**Comment by MiRo1310** [comment]
@Apollon77 

ich habe es angepasst

**Pull request merged**
