### PR TITLE
publish switchbot-hub

### PR DESCRIPTION
**Pull request by DutchmanNL**
beta looks good, please publish

https://github.com/ioBroker/AdapterRequests/issues/197

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found

### [ioBroker.switchbot-hub](https://github.com/DrozmotiX/ioBroker.switchbot-hub)
[Downloads](https://www.npmjs.com/package/iobroker.switchbot-hub) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.switchbot-hub/)

- [ ] :heavy_exclamation_mark: [E104] No common.title found in [io-package.json](https://github.com/DrozmotiX/ioBroker.switchbot-hub/blob/master/io-package.json)


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found

### [ioBroker.switchbot-hub](https://github.com/DrozmotiX/ioBroker.switchbot-hub)
[Downloads](https://www.npmjs.com/package/iobroker.switchbot-hub) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.switchbot-hub/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hey, review feeddback:
* encrypted native usage needs a globalDependencies of admin >= 4.0.9
* please update testing lib
* why you kill your error details again?? https://github.com/DrozmotiX/ioBroker.switchbot-hub/blob/main/main.js#L144 ;-)

**Comment by ldittmar81** [comment]
@DutchmanNL - do you need help here?

**Comment by Apollon77** [comment]
@DutchmanNL any news? :-)

**Comment by Apollon77** [comment]
@DutchmanNL How we should continue? Can we help somehow? Should we do a PR with relevant changes? But that would still require you to verify and test and release it afterwards because the changes can only be done "blind". ANd also we should fix the Sentry spammer issues before latest repo

**Comment by Apollon77** [comment]
@DutchmanNL Happy new year, how we should proceed?

**Comment by Apollon77** [comment]
@DutchmanNL Any update?

**Comment by mcm1957** [comment]
Please remove node 12 and 14 from test-and-release.yml, add node 18 and (optionally) add node 20 to testing matrix.
Node 14 is no longer supported and tests will fail since 22.5.2023.
Node 12 is unsupport sionce a longer time

Thanks
McM1957

**Comment by mcm1957** [comment]
@DutchmanNL 

Please let us know if you are still maintaining this adapter and are intrested in registratrion at latest repositories.

If you are still interested I will do a new review to check what issues are still open / already fixed and to get this PR merged.

Please simply post any reply (and check and fix github tests at repository).

**If we do not get any responce with 30 days we will close this PR.** 
But of course a new PR will be welcome at any time.

**Comment by mcm1957** [comment]
@DutchmanNL 
A kind reminder
**If we do not receive any response (comment) here this PR will be closed after 6.9.2023**

**Comment by mcm1957** [comment]
Please open a new PR if this adapter has been updated to current level (i.e. node 16/18/20) and tested with js.controller-5.
Repo looks a little bite stale currently.

**Pull request closed without merging**
