### PR TITLE
add fakeroku to commmunity

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by mcm1957** [comment]
@foxriver76 
@Apollon77 

Normally I would try to fix before releasing, and I can (and would) fix the errors of course if desired - but not before end of next week due to holiday absence. But as this PR only changes the urls but NOT the (stable) release I would suggest to merge the PR. Some issues should be solved by doing this anyway.

**Please confirm if OK to merge anyway.**

I assume that a new release is planned too to include js5 fixes. @foxriver76 you seem to have triggered one but the workflow failed due to node 14 usage. I just fixed test-and-releaswe workflow but please do the failed upload to npm manually (or create a new release) if not yet done.

**Review by mcm1957 — COMMENTED** [review]
@foxriver76 
@Apollon77 

Normally I would try to fix before releasing, and I can (and would) fix the errors of course if desired - but not before end of next week due to holiday absence. But as this PR only changes the urls but NOT the (stable) release I would suggest to merge the PR. Some issues should be solved by doing this anyway.

**Please confirm if OK to merge anyway.**

I assume that a new release is planned too to include js5 fixes. @foxriver76 you seem to have triggered one but the workflow failed due to node 14 usage. I just fixed test-and-releaswe workflow but please do the failed upload to npm manually (or create a new release) if not yet done.

**Comment by foxriver76** [comment]
No maintainer

Release failed because of missing npm permissions in the workflow, however it has been published manually

**Comment by mcm1957** [comment]
OK, I'll merge this PR for now. This should solve most issues.
The other ones I'll log as issue

**Pull request merged**
