### PR TITLE
Added gira-iot

### PR DESCRIPTION
**Pull request by klein0r**
and fixed argv argument parsing

see https://www.npmjs.com/package/minimist

> argv._ contains all the arguments that didn't have an option associated with them.

### CODE REVIEW

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.gira-iot](https://github.com/klein0r/ioBroker.gira-iot)
[Downloads](https://www.npmjs.com/package/iobroker.gira-iot) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.gira-iot/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.gira-iot)!. Please execute in adapter directory: `npm owner add bluefox iobroker.gira-iot`
- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/uk/translations.json" or "admin/i18n/uk.json" not found, but admin support is declared
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "gira-iot" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
Welcome in the repo.

One note: in unload try to do the tasks that prduce most unlikely an exception" like clearing Timeouts/Intervals first to make sure they are cleared.

Ingo

**Pull request merged**
