### PR TITLE
Update sources-dist-stable.json add alarm

### PR DESCRIPTION
**Pull request by misanorot**
add alarm

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alarm](https://github.com/misanorot/ioBroker.alarm)
[Downloads](https://www.npmjs.com/package/iobroker.alarm) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alarm/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@misanorot any chance for a compact mode support?

**Comment by misanorot** [comment]
Hello,
I think compact mode is a very good thing, but it is dangerous with all async things and I am a hobby programmer. At the moment compact mode is for the system  too dangerous with my adapter. In the future I will learn more about compact mode and the processes.

**Pull request merged**
