### PR TITLE
Update net-tools to 1.0.6

### PR DESCRIPTION
**Pull request by Jey-Cee**
Please update my adapter ioBroker.net-tools to version 1.0.6.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
Please fix test-and-release workflow. This must pass for a release to be added to stable.

Seems that io-package.json contains commin.license AND common.licenseInformation. common.license must be removed;
1) common.license should not exist together with common.licenseInformation

**Comment by Jey-Cee** [comment]
Not possible actual if you want to use developer portal for release:
https://github.com/ioBroker/dev-portal/issues/75

**Comment by mcm1957** [comment]
> Not possible actual if you want to use developer portal for release: [ioBroker/dev-portal#75](https://github.com/ioBroker/dev-portal/issues/75)

Please ignore the false positive from adapter checker for now. You can update the stable release manually - should not be a problem for you :-). And you already created a PR - so no problem with dev-portal for now.

Please fix package.json so that workflow test-and release passes the tests.

**Comment by mcm1957** [comment]
Standard GH Tests OK

**Comment by mcm1957** [comment]
OK lt. Bluefox:

@Bluefox27
Frage: 
Existiert für den Adapter ioBroker.net-tools, maintained by JeeCey eine kommerzielle Vereinbarung mit der GmbH die erlaubt diesen Adapter als paid adapter anzubieten?
-----------
https://t.me/c/2020938082/354
Ja. Ich habe 15% angefordert

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
[E115] - false positive

**Pull request merged**
