### PR TITLE
add winsipbrowser to latest repository

### PR DESCRIPTION
**Pull request by Bettman66**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.winsipbrowser](https://github.com/Bettman66/ioBroker.winsipbrowser)
[Downloads](https://www.npmjs.com/package/iobroker.winsipbrowser) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.winsipbrowser/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "winsipbrowser" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

here some review comments; just small stuff :-) :
* I think "communication" is not that right for the type ... the fullybrowser adapter uses "utility" ... or is it because of the "sip" part?
* Please only have english in readme (because of automatic translation). You can add a second Readme.md for german
* Hint: https://github.com/Bettman66/ioBroker.winsipbrowser/blob/master/lib/client.js#L285 is normally not needed because logged automatically
* Hint: When using GH Actions you can remove travis (https://github.com/Bettman66/ioBroker.winsipbrowser/blob/master/.travis.yml)

Thank you for checking and adjusting

**Comment by Bettman66** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.winsipbrowser](https://github.com/Bettman66/ioBroker.winsipbrowser)
[Downloads](https://www.npmjs.com/package/iobroker.winsipbrowser) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.winsipbrowser/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "winsipbrowser" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
I also adjusted the type here in PR, welcome in the repo

**Pull request merged**
