### PR TITLE
added e3dc-rscp@1.0.5 stable

### PR DESCRIPTION
**Pull request by git-kick**

### CODE REVIEW

**Comment by Apollon77** [comment]
Can you please rebase the PR? It seems you change other stuff too then just the stable file ... and in fact it is in latest already ...

**Comment by Apollon77** [comment]
@git-kick Ping

**Comment by git-kick** [comment]
The "other stuff" are my older commits for earlier versions. I tried to rebase using that [Howto](https://github.com/openedx/edx-platform/wiki/How-to-Rebase-a-Pull-Request), but did not succeed.

Since the change in `sources-dist-stable.json` is very straight forward, could we just discard PR#1785 and I create a completely new branch? Or is there any simple way for me to reset this branch to current `ioBroker.repositories/master`?

"and in fact it is in latest already" - I cannot confirm, I still get 1.0.1 as newest stable version when trying to install or update the adapter.

**Comment by git-kick** [comment]
Done, see #1801

**Pull request closed without merging**
