### PR TITLE
Add new adapter tino and tinyrx4

### PR DESCRIPTION
**Pull request by bowao**

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi, some review comments:

Tino AND TinyRX4:
- if not used please remobe stateChanged and objectsChanged 
- you never reset "info.connection" so it should stay at true forever ;-)
- please close serialport connection on unload else compact mode will get big problems and will crash ( did you tested it with compact mode?)
- remove "subscribeStates" if you  dio not need it
- placing debug code in the adapter is not really best practice ;-)
- consider removing .vscode from Github

**Comment by bowao** [comment]
Done

**Comment by Apollon77** [comment]
Sorry,but please check at least tinyrx4 again. serial port is not closed in onUnload! (Blocker)
Please also check adapter in compat mode that stopping really stops everything including state updates and that also restarting works.

Also you should react on serial disconnects at least with setting info.connection to false, maybe also automatic reconnects or such (sPort.on('error')...)

**Comment by bowao** [comment]
Uups. 
Sorry i forgot to upload the tinyrx4 main.js to github.
Now it is complete on github and npm.

I did some compact tests too. 
Both adapters in the same compact group, mutually switched on and off several times.
No error or problem detected. Both work as expected on js-controller 2.0.34

**Comment by Apollon77** [comment]
Thank you very much!

**Pull request merged**
