### PR TITLE
Add vis-2-widgets-rssfeed  to latest

### PR DESCRIPTION
**Pull request by oweitman**
[E124] Main file not found under URL: https://raw.githubusercontent.com/oweitman/ioBroker.vis-2-widgets-rssfeed/main/widgets/vis-2-widgets-rssfeed/customWidgets.js 
**-> datei wird im build prozess erzeugt**

[E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.vis-2-widgets-rssfeed" 
**-> bluefox wurde hinzugefügt und hat angenommen**

[E519] "widgets/vis-2-widgets-rssfeed/customWidgets.js" found in package.json, but not found as file 
**-> datei wird im build prozess erzeugt**

[W400] Cannot find "vis-2-widgets-rssfeed" in latest repository 
**-> ja genau, hier ist es**

[W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package 
**-> für vis-2 widgets wird es noch benötigt**

### CODE REVIEW

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

**Comment by mcm1957** [comment]
[E519] "widgets/vis-2-widgets-rssfeed/customWidgets.js" found in [package.json](https://github.com/oweitman/ioBroker.vis-2-widgets-rssfeed/blob/master/package.json), but not found as file can be ignored (false positive)

**Comment by oweitman** [comment]
RE-CHECK!

**Comment by oweitman** [comment]
[W184] "common.noConfig" is deprecated for admin >= 5 at [io-package.json](https://github.com/oweitman/ioBroker.vis-2-widgets-rssfeed/blob/master/io-package.json). Please use property "adminUI.config":"none".

und

 [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)

ersteres ist etwas missverständlich formuliert. deprecated sieht so aus als ob man es entfernen sollte.

**Comment by oweitman** [comment]
RE-CHECK!

**Comment by oweitman** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] errors reported by adapter checker 

  Errors for now. Chcker has to be improved.

Thanks for reading and evaluating this suggestions.
McM1957

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

**Comment by oweitman** [comment]
Danke

**Pull request merged**
