### PR TITLE
pls update icontwo to 1.3.0

### PR DESCRIPTION
**Pull request by skvarel**

### CODE REVIEW

**Comment by mcm1957** [comment]
1.3.0 created 28.12.2023

**Comment by skvarel** [comment]
> 1.3.0 created 28.12.2023

Yes .. it is just an icon adapter. Added some icons only.

**Comment by mcm1957** [comment]
guess you closed on error.

**Comment by mcm1957** [comment]
> > 1.3.0 created 28.12.2023
> 
> Yes .. it is just an icon adapter. Added some icons only.

OK, did not check yet.
OK for fast lane

**Pull request merged**
