### PR TITLE
Add midas-aquatemp to latest

### PR DESCRIPTION
**Pull request by MiRo1310**

### CODE REVIEW

**Comment by MiRo1310** [comment]
RE-CHECK!

**Comment by MiRo1310** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

remember 14.08.2024

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different opinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] Readme.md should contain a link to the manufacturer and/or device

  The README.md of any adapter related to device or multiple devices of a manufacturer should contain a link the manufacturers website and/or to a description of the device. This is to anable new users to easily check wether they associate the adapter with the correct device(s). (See https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository paragraph 4.)

- [ ] minimize logging

  Please  reduce logging to information important for user. I.e. I doubt that a user has much benefit to see that the token has been refreshed or that the objects have been created. Such logging is OK and valuable in case of problems but I suggest to use debug level for them. Some examples

  https://github.com/MiRo1310/ioBroker.midas-aquatemp/blob/97199701ccceda5488e41f6bb1cd387fa54d508d/src/lib/token.ts#L14

  https://github.com/MiRo1310/ioBroker.midas-aquatemp/blob/97199701ccceda5488e41f6bb1cd387fa54d508d/src/lib/createState.ts#L402

- [ ] sensitive information must not be logged into logfile

  To avoid publishing sensitive information when forwarding logs, those information should never be written into the logs but either omitted or at least partly masked so that the information cannot be misused. This relates at least to usernames, passwords, unique (user assigned) keys and tokens. In addition personal information like name, address, gegraphical coordinates should not be logged too.

  see https://github.com/MiRo1310/ioBroker.midas-aquatemp/blob/97199701ccceda5488e41f6bb1cd387fa54d508d/src/lib/token.ts#L28

- [ ] access to cloud.linked-go.com

  Adapter accesses cloud.linked-go.com site. Is this site related to midas? There is no Impressum at this site. It looks a little dubious. If it is related to midas please provide some proof / link. An in any case please document the access to the website differing from the manufacturer at README so that users are informed an later questions are avoided.

  https://github.com/MiRo1310/ioBroker.midas-aquatemp/blob/97199701ccceda5488e41f6bb1cd387fa54d508d/src/lib/endPoints.ts#L9

- [ ] please review object creation
  
  Here https://github.com/MiRo1310/ioBroker.midas-aquatemp/blob/97199701ccceda5488e41f6bb1cd387fa54d508d/src/lib/saveValue.ts#L30 you create a state if it does bot exist. But you set the state value oly if it already exists - not if it has been just created. (see return). Is this really desired?

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whenever a dedicated role exists.
  value.* is always a read only state. Changeable states must be level.*. See schema definition noted above.

  See as an example - but please check every role:

  https://github.com/MiRo1310/ioBroker.midas-aquatemp/blob/97199701ccceda5488e41f6bb1cd387fa54d508d/src/lib/createState.ts#L45

  https://github.com/MiRo1310/ioBroker.midas-aquatemp/blob/97199701ccceda5488e41f6bb1cd387fa54d508d/src/lib/createState.ts#L150

- [ ] i18n cleanup suggested

  option 1 / option 2 seem to be realted to template
  Using usernamen adn Username seems confusing (or one of them is obsolete)
  https://github.com/MiRo1310/ioBroker.midas-aquatemp/blob/97199701ccceda5488e41f6bb1cd387fa54d508d/admin/i18n/de/translations.json#L2

- [ ] Add timeout to axios calls

  All axios calls should have a timeout set. The default value for axios timeout is 0 which results in no timeout. So an unresponsive remote system could lead to an hanging adapter. Either set an appropiate timeout per axios call or set a default timeout globally for the axios instance.
  
- [ ] check and limit configurable timeouts / intervals
  
  Node setTimeout/setInterval routines have a maximum allowed value of 2,147,483,647 ms. Using delays larger than 2,147,483,647 ms (about 24.8 days) result in the timeout being executed immediately. So all (user configurable) values passed to setTimeout / setInterval should be checked in code and limited. Checking/limiting in code is required as config data could be changed directly or by some other adapter too, so limiting at ui level might not be sufficient.
  
  see config.config refresh

- [ ] adapt testing to supported node releases

  Tests for node 18 are mandatory. 
  Tests for node 20 are mandatory as this is the recommended node version. 
  Tests for node 22 are mandatory unless you already know incompatibilities which cannot be fixed immidiatly. In this case please create a issue stating the problem and fix as soon as possible.
  
  So the recommended testmatrix is [18.x, 20.x, 22.x] depending on engines requirments setting at package.json 

  Tests must be performed at all supported platforms (linux, windows, mac) unless special hardware or software restrictions prohibit this.

  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
@MiRo1310 
Did you close this PR on purpose?
Why?
Or did you close on error i.e. by deleting a branch or fork?

In any case a new PR is welcone.

**Comment by MiRo1310** [comment]
I have no information about which devices are supported and nothing about the API. I received a script from a user and built it into an adapter. There are only 8 installations, and so I won't invest much more time in it at the moment, as I have little time at the moment.

**Pull request closed without merging**
