### PR TITLE
added places adapter

### PR DESCRIPTION
**Pull request by BasGo**
Hi. Aufgrund der Vielzahl der Geo-Adapter (OwnTracks, Geofency, EgiGeoZone) und deren redundantes "Home"-Handling: hier mal eine generische Variante mit der Möglichkeit, beliebig viele Orte erstellen und rein message-basiert arbeiten zu können. VG Bastian

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Please add me to collaborators.
https://github.com/ioBroker/ioBroker.repositories#add-owner-to-packet

**Comment by Apollon77** [comment]
Adaptertesting and Admin3 compatible configuration is missing too! Please refer to the template adapter and subscribe to travis-ci and appveyor

**Comment by BasGo** [comment]
- You have **both** been added to **collaborators**
- **Bluefox** is now an **owner for NPM package**
- **adapter testing** has been **activated**
- **configuration** has been changed to be **Admin3 compatible**

Anything forgottten? :-)

**Comment by GermanBluefox** [comment]
:) Looks perfect.



2018-03-15 13:49 GMT+01:00 BasGo <notifications@github.com>:

**Comment by Apollon77** [comment]
agree :-)

**Pull request merged**
