### PR TITLE
new adapter ioBroker.minuaru

### PR DESCRIPTION
**Pull request by SVallant**
Result of Adapter Checker:

- [E506] "admin/jsonCustom.json" not found, but custom support is declared
- [E300] Not found on travis. Please setup travis

both false positive:

- jsonCustom.json is there
- please add travis.com to checker together with travis.org

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by SVallant** [comment]
Hi @Apollon77 

here some review comments:

 _Please add adapter testing also to the travis job (or better go to Github Actions?) - right now only package testing is done_
yes, is planned before adding to stable. Can you give me some example of testing admin/custom.json ?

_Is the adapter type storage really making sense_ 
for me it is the same like "ioBroker.history", storing and displaying alarm-messages
What other type would you suggest ???

_Please remove admin from the "dependencies" list_ , _minimum js-controller 3.3 as dependency_
 done

data-directory ( now .../iobroker-data/minuaru.0) changed, please check if config 
https://github.com/minukodu/ioBroker.minuaru/blob/bde7c341d48c60561fdce6d27f10b785feae7ed5/io-package.json#L127
is correct for backup

Thank you for this good support

**Comment by Apollon77** [comment]
@SVallant 

1.) Testing custom ... in fact you can create an object with the relevant custom entries before adapter get started and such. In fact we have very detailed testing for history and such (eg. https://github.com/ioBroker/ioBroker.history/blob/master/test/testAdapter.js#L100-L116), but this uses the "legacy testing scripts" and not the new testing lib. But basically "the same" is possible there too...
2.) I would see it more "alarm" or "misc-data" dependeing on what you want to focus on. I think the main focus is more about "doing something based on actions" and not "dump storage of data"
3.) Backup/Data Dir: seems fine.. maybe test it :-) you can check that it restored on "restore" or that it is contained in the backup file

**Comment by Apollon77** [comment]
Additionally for testing: even if you do not add real custom testing it is better then nothing to just proof that install and start basically works. But yes you can also go deep into functional testing ;-)

**Comment by SVallant** [comment]
adapter's type is "misc-data" now, since alarm-adpters or mostly "security"-Adapters
Backup works like you said 
wirting tests will be a big challenge next weeks ... ;-)

**Comment by Apollon77** [comment]
For tests: As said: For the repo addition it would be enought to just see adater starting basically (so execute the integration tests - done). More is optinal after that

**Comment by Apollon77** [comment]
@SVallant Anything we can support with? Just poke when ready for re-review.

**Comment by SVallant** [comment]
No, thanks, just no available time at the moment .... other projects are more important

**Comment by Apollon77** [comment]
@SVallant if it is only about the testing thenthis would just be requirement that "it runs and starts the adapter", custom testing is formally not required

**Comment by SVallant** [comment]
@Apollon77 Adapter is ready for latest now. Do you a new PR?

**Comment by Apollon77** [comment]
resolve the conlfucts or do a new PR (but please add a linkto here) ... up to you :-)

**Pull request closed without merging**
