### PR TITLE
Update musiccast to 1.1.3 at stable

### PR DESCRIPTION
**Pull request by foxthefox**
update musiccast 1.1.3

### CODE REVIEW

**Comment by mcm1957** [comment]
@foxthefox 
Your adapter https://github.com/foxthefox/ioBroker.musiccast does not use standard iobroker testing using node 16/18/20

Please see requirements https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository which is also required for stable repository.

Adapter needs to have at least Adapter basic testing (installing, running) using GitHub actions. More information in forum from apollon77 (Just take from other adapters the samples)

Currently your testmatrix only contains node 18. Iobroker officially supports node 16 / 18 / 20. Tests should be run for every node version supported. So please add node 16 and node 20 to your test matrix and retrigger a test. 

If you do not or cannot support node 16, it's ok the add an 'engine: >=18' clause to package.json so that node 18 or newer ist required during installation.

If you know that you adapter fails with node 20 temporary omit node 20 tests but add an issue describing the problem and try to fix it as soon as possible.

Please feel free if you need any help setting up standard testing and / or if you prefer a that we / I create a PR to fix this.

Please add a comment when you have reviewed and fixed the suggestion or at least commented the suggestions and you think the adapter is ready for a re-review

**Comment by foxthefox** [comment]
I hope it is sufficient to add the version 16 and 20 to the testing and it is not needed to create a new version of the adapter.

**Comment by mcm1957** [comment]
NO new versio n is required.
Simply add the node versions to the matrix an trigger a run, i.e by adding a spce to README.md or chnaging some other file to trigger the github action. Its ok if the current main revision passes.

**Comment by foxthefox** [comment]
testing is now with 16,18,20

**Comment by mcm1957** [comment]
1.1.3 created 24.09.2023
OK

**Pull request merged**
