### PR TITLE
add new adapter iogopro

### PR DESCRIPTION
**Pull request by nisiode**
this adapter will replace the current iogo adapter within the next weeks/months

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heatingcontrol](https://github.com/rg-engineering/ioBroker.heatingcontrol)
[Downloads](https://www.npmjs.com/package/iobroker.heatingcontrol) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heatingcontrol/)

:thumbsup: No errors found

### [ioBroker.iogopro](https://github.com/nisiode/ioBroker.iogopro)
[Downloads](https://www.npmjs.com/package/iobroker.iogopro) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.iogopro/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "iogopro" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by nisiode** [comment]
PR is now 7 days old... is anything missing or needs some fixing?

**Comment by Apollon77** [comment]
No, just time to review ...  stay tuned

**Comment by nisiode** [comment]
good to know, take your time

**Comment by Apollon77** [comment]
Review Feedback:
* store apKey encrypted?
* unload callback is called too early https://github.com/nisiode/ioBroker.iogopro/blob/master/src/main.ts#L115-L122 is don async ... so callbback needs to be in the "then"/catch cases or you need tzo "await" the signout
Rest as talked in Discord

**Comment by nisiode** [comment]
both remarks solved

**Comment by Apollon77** [comment]
Welcome in the repo

**Pull request merged**
