### PR TITLE
add psa adapter to latest

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.psa](https://github.com/TA2k/ioBroker.psa)
[Downloads](https://www.npmjs.com/package/iobroker.psa) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.psa/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "psa" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
Hey @TA2k, thanks for your PR. 

Here are some things which need to be fixed or clarified.

https://github.com/TA2k/ioBroker.psa/blob/30aa88d6bfb244d6c793f950694c5fe18fd478af/io-package.json#L84 requires controller requires controller 3 but dependency in io-pack only requires v2

please translate news https://github.com/TA2k/ioBroker.psa/blob/30aa88d6bfb244d6c793f950694c5fe18fd478af/io-package.json#L10 you could also use the release script which is already defined as a dev dep https://github.com/TA2k/ioBroker.psa/blob/30aa88d6bfb244d6c793f950694c5fe18fd478af/package.json#L28

Changelog is missing releases? https://github.com/TA2k/ioBroker.psa#changelog

Please specify minimum node version via engines field of package.json

since you are polling an api with intervals, you should think of about two things:

1. better make it timeouts where the timeout only starts after the poll logic has been completed, 
2.make a min possible interval else users can configure 1 second and API will maybe be floated, the providers wouldn't like it

Why steteChange handler https://github.com/TA2k/ioBroker.psa/blob/30aa88d6bfb244d6c793f950694c5fe18fd478af/main.js#L361 and subscription to alle states when nothing is done at stateChange

You are using info.connection https://github.com/TA2k/ioBroker.psa/blob/30aa88d6bfb244d6c793f950694c5fe18fd478af/io-package.json#L95 but the info channel itself is not created, please also create it.

The rest looks good to me. 👍 

Thanks for your work. 👨‍💻

**Comment by TA2k** [comment]
fix issue but I prefer the interval to make it more robust against connection problems

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.psa](https://github.com/TA2k/ioBroker.psa)
[Downloads](https://www.npmjs.com/package/iobroker.psa) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.psa/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "psa" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@TA2k 
lol https://github.com/TA2k/ioBroker.psa/blob/master/io-package.json#L26 :))

Rest is fine

**Pull request merged**
