### PR TITLE
Add Heizungssteuerung Adapter

### PR DESCRIPTION
**Pull request by jbeenenga**
Heizungssteuerung Adapter

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
Hi,

here some review comments.

* please add Bluefox as owner on npm, as described in readme of this repo
* please translate https://github.com/jbeenenga/ioBroker.heizungssteuerung/blob/main/io-package.json#L91-L113 - you can use the iobroker translation tool
* You do not really connect to anything, for what you have the info.connection state? You also dso not set it. I think there is no need to have that for your case. Please remove the objects from your io-package
* please remove https://github.com/jbeenenga/ioBroker.heizungssteuerung/blob/main/main.js#L197 and https://github.com/jbeenenga/ioBroker.heizungssteuerung/blob/main/main.js#L212 if you do not need it ...or might want to subscribe to enum objects so that changes done there are seen by the adapter?
* Please add more details on how to configure to Readme

Thank you for checking and adjusting

**Comment by jbeenenga** [comment]
Hi,
thanks for your feedback. 
I have adjusted your hints. 
The user bluefox is invited to npm package but has not accepted invite yet.

**Comment by jbeenenga** [comment]
Hi @Apollon77 ,
are there any open points I have to fix to make the request acceptable?

Thanks

**Comment by Apollon77** [comment]
I die not had the time before y vacation to recheck. Will do after vacation next week.

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heizungssteuerung](https://github.com/jbeenenga/ioBroker.heizungssteuerung)
[Downloads](https://www.npmjs.com/package/iobroker.heizungssteuerung) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.heizungssteuerung/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "heizungssteuerung" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jbeenenga** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heizungssteuerung](https://github.com/jbeenenga/ioBroker.heizungssteuerung)
[Downloads](https://www.npmjs.com/package/iobroker.heizungssteuerung) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.heizungssteuerung/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "heizungssteuerung" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Welcome in the repo and sorry that the re-review took that long

**Pull request merged**
