### PR TITLE
New Stable Version of swiss-weather-api

### PR DESCRIPTION
**Pull request by baerengraben**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.swiss-weather-api](https://github.com/baerengraben/ioBroker.swiss-weather-api)
[Downloads](https://www.npmjs.com/package/iobroker.swiss-weather-api) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.swiss-weather-api/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/baerengraben/ioBroker.swiss-weather-api/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W505] setTimeout found in "main.js, but no clearTimeout detected

### [ioBroker.swiss-weather-api](https://github.com/baerengraben/ioBroker.swiss-weather-api)
[Downloads](https://www.npmjs.com/package/iobroker.swiss-weather-api) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.swiss-weather-api/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/baerengraben/ioBroker.swiss-weather-api/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :eyes: [W505] setTimeout found in "main.js, but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.swiss-weather-api](https://github.com/baerengraben/ioBroker.swiss-weather-api)
[Downloads](https://www.npmjs.com/package/iobroker.swiss-weather-api) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.swiss-weather-api/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/baerengraben/ioBroker.swiss-weather-api/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W505] setTimeout found in "main.js, but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by baerengraben** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.swiss-weather-api](https://github.com/baerengraben/ioBroker.swiss-weather-api)
[Downloads](https://www.npmjs.com/package/iobroker.swiss-weather-api) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.swiss-weather-api/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js, but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
But please check also 

    👀 [W505] setTimeout found in "main.js, but no clearTimeout detected

... else compact mode will break

**Comment by baerengraben** [comment]
I need some help for solving "setTimeout found in "main.js, but no clearTimeout detected"
What exactly is the problem? In belong to "setTimeout" I haven't changed anything compared to my previous stable version.

**Comment by Apollon77** [comment]
Then it was broken all the time and was not seen in initial review :-)) We added this as a check in the repo checked to make sure to get this solved.

For compact mode to work correctly it is essential that all timeouts or intervals (and also resoirces like servers, connections and such) used in the adapter are completely cleared and ended in "unload". If a timeout continues to run after unload in compact mode this can have bad effects to the whole system.

Best is to store all timeouts (in your case) in a variable and use clearTimoeut to stop that in unload

**Comment by baerengraben** [comment]
Okay, thanks for the explanation. :)  I'll do the change this weekend.

**Comment by baerengraben** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.swiss-weather-api](https://github.com/baerengraben/ioBroker.swiss-weather-api)
[Downloads](https://www.npmjs.com/package/iobroker.swiss-weather-api) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.swiss-weather-api/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
