### PR TITLE
Update sainlogic stable to 0.10.5

### PR DESCRIPTION
**Pull request by phifogg**

### CODE REVIEW

**Comment by mcm1957** [comment]
1.10.4 created 23.7.2023
8 user

1.10.5 created 23.7.2023
77 user

**Comment by mcm1957** [comment]
@phifogg 
Are you sure that an update to 1.10.4 is desired?
1.10.5 has been created at same date and hence 1.10.5 has been tested latest sinde 23.7.

**Comment by mcm1957** [comment]
@phifogg
Are you sure that an update to 1.10.4 is desired?
1.10.5 has been created at same date and hence 1.10.5 has been tested at latest since 23.7.

**Comment by phifogg** [comment]
AH.. good point. I'll update to 10.5 for stable. I didn't expect people to update that quickly :D

**Pull request merged**
