### PR TITLE
Add extron 0.2.15 to stable

### PR DESCRIPTION
**Pull request by Bannsaenger**
Please update my adapter ioBroker.extron to version 0.2.15.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
@Bannsaenger 

Any adapter revision released to stable MUST have working Github based standard tests. Your tests fail.
The reason is that you merge eslint to 9.x.x while still using an old configuration. 

Suggested solution:
REVERT PR https://github.com/Bannsaenger/ioBroker.extron/pull/22 by selecting the revert button at PR and merge the created new PR. I've already don ethe first step and created PR https://github.com/Bannsaenger/ioBroker.extron/pull/24: Please allow tests to run and if OK merge ther PR. This will downgrade eslint to 8.57.0 and should revert checks to a working configuration.

In addition please fix at least the Errors reported by adapterchecker (see above and  https://github.com/Bannsaenger/ioBroker.extron/issues/23). It's sufficient to fix the errors

- ❗ [E026] "{'engines': {'node'>='16'}}" is required at [package.json](https://github.com/Bannsaenger/ioBroker.extron/blob/master/package.json), "{'engines':{'node'>='18'}}" is recommened - BUT PLEASE SEE BELOW
- ❗ [E162] js-controller 4.0.15 listed as dependency but 4.0.24 is required as minimum, 5.0.19 is recommended. Please update dependency at [io-package.json](https://github.com/Bannsaenger/ioBroker.extron/blob/master/io-package.json).
- ❗ [E204] Version "0.2.16" listed at common.news at [io-package.json](https://github.com/Bannsaenger/ioBroker.extron/blob/master/io-package.json) does not exist at [NPM](https://www.npmjs.com/package/iobroker.extron). Please remove from news section.

And as a last point:
You currently have tests for node.js 20 and 22 configured at test-and-release workflow. So please EITHER add node 18 tests to your test matrix OR add 'engines': { 'node' >= '20'} to package.json.

Please drop a node as soon as those issues are fixed. 
at GitHu. a new release is **NOT** required.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by Bannsaenger** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Your Adapter has been added to stable repository. If you like you can extend the news message here:

https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/history/history.md

If you add some more information / description, please consider to add this information to README.md too.

If you have any questions related to the news file, please contact @Apollon77 for further information.

Please note, that the PR announcing the new adapter at stable might not be merged.
https://github.com/ioBroker/ioBroker.docs/pull/

**Pull request merged**
