### PR TITLE
Update sainlogic to 0.11.4

### PR DESCRIPTION
**Pull request by mcm1957**
@phifogg
see https://github.com/ioBroker/ioBroker.repositories/pull/3862
But this PR contains too many commits for checker to work.

### CODE REVIEW

**Comment by mcm1957** [comment]
README and news must be fixed
see https://github.com/phifogg/ioBroker.sainlogic/issues/204

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by phifogg** [comment]
RE-CHECK

**Comment by phifogg** [comment]
RE-CHECK!

**Comment by phifogg** [comment]
RE-CHECK!

**Comment by phifogg** [comment]
I am a bit lost what to do with this one and google couldn't help a lot:
 ❗ [E114] No adapter are allowed in the repo without admin support (set "common.adminUI.config = none" if adapter has no configuration)

Also the license part, I believe I have updated the license as requested in both files. Probably some stupid mistake.

**Comment by mcm1957** [comment]
Sorry for problems and thanks for your attempts.

I'll check this evening and give feedback.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by phifogg** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Bingo
Sieht gut aus DANKE.

Die restl. Warnings sind non blocking. Da kannst was machen wenn du dazu kommst oder sie auch ignorieren.  Ob di gulp doch noch wo benutzt weisst du am Besten. Und ob du die Optionen Sprachen übersetzen lassen willst kannst auch du entscheiden. Drr checker warnt da nur dass was empfohlenes fehlt (de u en wären error).

Danke f super schnellen Einsatz..Stabke merge schau ich abends .. bin unterwegs

**Pull request merged**
