### PR TITLE
Add vis-2-widgets-inventwo to latest

### PR DESCRIPTION
**Pull request by mcm1957**
replacement for #3458

@jkvarel
Please watch this PR to get updatea

### CODE REVIEW

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

reminder 10.4.2024

**Comment by mcm1957** [comment]
First feedback:
correct licenseentry is: (E183)

````
    "licenseInformation": {
      "license": "MIT",
      "type": "free",
      "link": "https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/blob/master/LICENSE"  << optional, not used for free
    }
```
and remove common.license (E182)

E117 is a follow up error

E124 can be ignored, will be fixed with next checker release

E201 - please invite bluefox if not yet done

E80x Please correct repository

E603 Please fix README. And please fill README with information about the adapter / widget - currently it is much too short.

**Comment by jkvarel** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@jkvarel

Thanks for fixing the notes from review. You did not drop a commant so I did not look at this PR until today.

Adapter looks good now.

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Comment by jkvarel** [comment]
@mcm1957 , thank you for merging. 

I didn't drop a comment because there is still an issue with the test-and-release for macos with node 18 and first wanted to fix that. The local tests action fails.

**Comment by mcm1957** [comment]
Are you sure the mac od node 18 is really a issue?
Its only causing a timeout as far as I see. Did you try to start a rerun.
Sometimes mac and windows simply time out due to overload and the next run with identical code succeeds.

**Pull request merged**
