### PR TITLE
Update tapo to 0.2.9

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by TA2k** [comment]
run with disabled listing

**Comment by mcm1957** [comment]
Thanks - tests look good now

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
0.2.9 created 30.01.2024
26 User

**Comment by mcm1957** [comment]
master - main switch done by
https://github.com/ioBroker/ioBroker.repositories/pull/3264
https://github.com/ioBroker/ioBroker.repositories/pull/3265

Version update handled by https://github.com/ioBroker/ioBroker.repositories/pull/3281

**Pull request closed without merging**
