### PR TITLE
E-Control-at-fuel Adapter

### PR DESCRIPTION
**Pull request by xXBJXx**
[Forumbeitrag](https://forum.iobroker.net/topic/33033/e-control-at-fuel-kraftstoffpreise-f%C3%BCr-%C3%B6sterreich)

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.e-control-at-fuel](https://github.com/xXBJXx/ioBroker.e-control-at-fuel)
[Downloads](https://www.npmjs.com/package/iobroker.e-control-at-fuel) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.e-control-at-fuel/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.e-control-at-fuel)!. Please execute in adapter directory: `npm owner add bluefox iobroker.e-control-at-fuel`
- [ ] :eyes: [W400] Cannot find "e-control-at-fuel" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Ok, the npm error seems to be a false positive ... bluefox is added

**Comment by Apollon77** [comment]
@xXBJXx  Please adjust the following:
* You use Sentry but this is nowhere informed about in the Readme. Please add information about it. YOu can do like the other adapters (e.g. check Tuya adapter)
* Please remove the onObjectChange handler if not needed, same for on StateChanged
* What all these "awaits" in https://github.com/xXBJXx/ioBroker.e-control-at-fuel/blob/master/main.js#L630 and following lines are doing? I thought the value is an object?

**Comment by xXBJXx** [comment]
@Apollon77  
I added the information about Sentry to the README and
removed the unnecessary await and onObjectChange / StateChanged.

**Comment by Apollon77** [comment]
Hey, thank you, fine in general,  ut one note:
All those https://github.com/xXBJXx/ioBroker.e-control-at-fuel/blob/master/main.js#L611 without await in front of them will run async and so the "try/catch" around it will have no effect ... is this intended? Any error in a setStateAsync would crash the adapter because of an unhandled Promise rejection ... Maybe you want to add the await in from of all relevant ...Async calls?

**Comment by Apollon77** [comment]
Please tell me if you want to adjust it (I would say you should, else one use with a strange response can spam your sentry account to death :-)

**Comment by xXBJXx** [comment]
oh yes i will change it tomorrow

**Comment by xXBJXx** [comment]
I changed the code a little so that it works better and swapped the setStateAsync for setState because in my opinion it is not necessary.

I first tried await this.setStateAsync because there are quite a few await then these messages appear in the log at start

`admin.0 | 2020-07-03 00:57:30.239 | info | (24244) Unsubscribe from all states, except system's, because over 3  seconds the number of events is over 200 (in last second 0)
`

`admin.0 | 2020-07-03 00:58:31.169 | info | (24244) Subscribe on all states again`

**Comment by GermanBluefox** [comment]
How many variables will be written normally with one read?
Brief check shows that for every station 20-50 states. If the user have 5 stations so up to 250 variables will be written all together!

**Comment by xXBJXx** [comment]
I looked at the code again and found a few bugs that caused the problem with the many events and fixed them.
A maximum of 10 stations are created per region and each station has 23 states that are written but not all at once.
Now it's going as it should.

**Comment by xXBJXx** [comment]
I have another adapter that could now be included in the latest [WallPanel](https://forum.iobroker.net/topic/36438/test-adapter-wallpanel)

**Comment by DutchmanNL** [comment]
@Apollon77 e-control : all feedback has been taken care of, positive advice

@xXBJXx 
About Wallpaper : 
- sentry I used but try/catch elements which indicate code errors are not send to sentry
- looks like the create state function is called at each api call causing an extend object (write)
is it needed to changes these objects all the time ?
https://github.com/xXBJXx/ioBroker.wallpanel/blob/master/main.js#L583-L631
- there is no check if state is writeable which could cause un-executable api calls.
Or are all states writable ? : https://github.com/xXBJXx/ioBroker.wallpanel/blob/master/main.js#L698-L731

**Comment by xXBJXx** [comment]
> Über Wallpaper:
> 
> * Sentry Ich habe verwendet, aber Try / Catch-Elemente, die auf Codefehler hinweisen, werden nicht an Sentry gesendet
> * Es sieht so aus, als würde die Funktion zum Erstellen eines Status bei jedem API-Aufruf aufgerufen, wodurch ein erweitertes Objekt (Schreiben) verursacht wird. Ist 
>   es erforderlich, diese Objekte ständig zu ändern? 
>   https://github.com/xXBJXx/ioBroker.wallpanel/blob/master/main.js#L583-L631
> * Es wird nicht überprüft, ob der Status beschreibbar ist, was zu nicht ausführbaren API-Aufrufen führen kann. 
>   Oder sind alle Staaten beschreibbar? : https://github.com/xXBJXx/ioBroker.wallpanel/blob/master/main.js#L698-L731

**Comment by xXBJXx** [comment]
@DutchmanNL 
> About Wallpaper :
> 
> * sentry I used but try/catch elements which indicate code errors are not send to sentry

Before I send messages to sentry I have to take a look at how it should be structured.

> * looks like the create state function is called at each api call causing an extend object (write)
>   is it needed to changes these objects all the time ?
>   https://github.com/xXBJXx/ioBroker.wallpanel/blob/master/main.js#L583-L631

I changed the extendObjectAsync to setObjectNotExistsAsync.

> * there is no check if state is writeable which could cause un-executable api calls.
>   Or are all states writable ? : https://github.com/xXBJXx/ioBroker.wallpanel/blob/master/main.js#L698-L731

All of these states are writable - they are all command states.

**Comment by DutchmanNL** [comment]
thank you, looks good now @Apollon77 positive advice for both

**Comment by xXBJXx** [comment]
I withdraw the pull request and close it since nothing has happened here for months.

**Comment by Apollon77** [comment]
I'm sorry, but also we need to find time to review. Are you still interested?

**Comment by Apollon77** [comment]
@xXBJXx Review comments (if you still want or not your thing):
* please do not set all the states async as you do in https://github.com/xXBJXx/ioBroker.e-control-at-fuel/blob/master/main.js#L208 and following. Please use await and Async methods or other options to make sure that states are set one after the other to not overload the system ... also the use of setState inside an asny c method runs all of that in parallel too
* you do not need to add sentry as a dependency ... the js-controller has that included

**Pull request closed without merging**
