### PR TITLE
Suggest jarvis for latest repository

### PR DESCRIPTION
**Pull request by Zefau**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.jarvis](https://github.com/Zefau/ioBroker.jarvis)
[Downloads](https://www.npmjs.com/package/iobroker.jarvis) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.jarvis/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 1.0.0-rc.2
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "jarvis" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Zefau** [comment]
> No news found for actual version 1.0.0-rc.2

`1.0.0-rc.2` is only on Github, not npm. News for `1.0.0-rc.1` is available.

> [E300] Not found on travis. Please setup travis

It is on pro, see https://travis-ci.com/Zefau/ioBroker.jarvis

> [W400] Cannot find "jarvis" in latest repository

Trying with this issue 🥇

**Comment by Zefau** [comment]
@Apollon77

**Comment by Zefau** [comment]
Is it actually possible to check branches (https://github.com/Zefau/ioBroker.jarvis/tree/v1.0.x) with https://adapter-check.iobroker.in/ ?

**Comment by Apollon77** [comment]
No, adapter checker always check master

**Comment by Zefau** [comment]
Would you merge though?
> No news found for actual version 1.0.0-rc.2

`1.0.0-rc.2` is only on Github, not npm. News for `1.0.0-rc.1` is available.

> [E300] Not found on travis. Please setup travis

It is on pro, see https://travis-ci.com/Zefau/ioBroker.jarvis

> [W400] Cannot find "jarvis" in latest repository

Trying with this issue 🥇

**Comment by Apollon77** [comment]
@Zefau 
Some comments (I checked the 1.0.x branch):
* if unit tests fail that way as they do then do not run them ... or fix them ;-)
* For now ok, but at least in the io-package we should have all languages translated that are standard! Please change that till stable - or we need to discuss again about this in the community; also having links only as version new is not that user friendly and shoukd be changed
* "installedFrom" needs to be removed from io-package!! Please fix that
* Note: https://github.com/Zefau/ioBroker.jarvis/blob/v1.0.x/lib/library.js#L302 ... "delete this._STATES[key]" is the official command ... I do not know if there is a difference to set to undefined ...

**Comment by Zefau** [comment]
Unit test runs successful, see https://travis-ci.com/github/Zefau/ioBroker.jarvis/branches

Where do you see it failing? 

Translation will be done, even though I'm not a friend of Google translated texts.

Io package will be cleaned soon.

Is there something wrong with `delete` from your perspective? It is like setting it to undefined, but that is addressed in the code.

**Comment by Apollon77** [comment]
For delete vs undefined I really do not know.  It should be the same effect, but „delete“ is the official way to delete a value. Maybe there are differences in the deeeeeeep insides ... that’s why it was just a note. 

Tests do not fail but when you check travis log output from Master i saw unhandled promise rejection on unit tests.

**Comment by Zefau** [comment]
Didn't see that, thanks! 

https://github.com/Zefau/ioBroker.jarvis/issues/90
https://github.com/Zefau/ioBroker.jarvis/issues/91
https://github.com/Zefau/ioBroker.jarvis/issues/93

**Pull request merged**
