### PR TITLE
Added hikvision-alarmserver

### PR DESCRIPTION
**Pull request by raintonr**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
Hi,

here some review comments:
* Please enable GitHub actions for testing. I assume you just need to fix this line to be "master"  https://github.com/raintonr/ioBroker.hikvision-alarmserver/blob/master/.github/workflows/test-and-release.yml#L8
* I propose to add a try/catch around server initializstion, else adapter might crash when port is already used or such
* If possible please remember that the object was created 8https://github.com/raintonr/ioBroker.hikvision-alarmserver/blob/master/main.js#L99), else you do unneeded traffic on any event :-)

So rest is fine. Please enable testing that I can see it :-)

**Comment by Apollon77** [comment]
PS: ANd please also theck the automtátic checker stuff above

**Comment by raintonr** [comment]
> here some review comments:

All valid points and handled.

**Comment by raintonr** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hikvision-alarmserver](https://github.com/raintonr/ioBroker.hikvision-alarmserver)
[Downloads](https://www.npmjs.com/package/iobroker.hikvision-alarmserver) 
[NPM](https://nodei.co/npm/iobroker.hikvision-alarmserver/)

- [ ] :heavy_exclamation_mark: [E118] Versions in [package.json](https://github.com/raintonr/ioBroker.hikvision-alarmserver/blob/master/package.json) and in [io-package.json](https://github.com/raintonr/ioBroker.hikvision-alarmserver/blob/master/io-package.json) are different
- [ ] :eyes: [W400] Cannot find "hikvision-alarmserver" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Did you also checked the testing results after activating it? You should ;-)
https://github.com/raintonr/ioBroker.hikvision-alarmserver/runs/4886686732?check_suite_focus=true ... your package-lock is outdated

**Comment by raintonr** [comment]
I do not appreciate this 'humour'.

**Comment by Apollon77** [comment]
Sorry

**Comment by raintonr** [comment]
Ok.

Clone my repo and npm install and you will see it's not that simple.

**Comment by Apollon77** [comment]
Honestly: Then remove the package-lock.json and replace all npm ci by "npm install" and done

**Comment by Apollon77** [comment]
But ok let me check

**Comment by Apollon77** [comment]
approve run please in https://github.com/raintonr/ioBroker.hikvision-alarmserver/pull/1

**Comment by raintonr** [comment]
> approve run please in [raintonr/ioBroker.hikvision-alarmserver#1](https://github.com/raintonr/ioBroker.hikvision-alarmserver/pull/1)

Yeah... that failed :disappointed:

**Comment by raintonr** [comment]
> Honestly: Then remove the package-lock.json and replace all npm ci by "npm install" and done

Yes - that was the issue :disappointed:

**Comment by raintonr** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hikvision-alarmserver](https://github.com/raintonr/ioBroker.hikvision-alarmserver)
[Downloads](https://www.npmjs.com/package/iobroker.hikvision-alarmserver) 
[NPM](https://nodei.co/npm/iobroker.hikvision-alarmserver/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "hikvision-alarmserver" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by raintonr** [comment]
> W400] Cannot find "hikvision-alarmserver" in latest repository

What's this about? Isn't the point of this PR to get it out to the repo?

**Comment by raintonr** [comment]
Yes... exactly!

https://github.com/ioBroker/ioBroker.repochecker/blob/300585c6e83212f4ab8f771f62734ddb95593e94/index.js#L1124

So this is good to merge then?

**Comment by Apollon77** [comment]
I will check tonight

**Comment by raintonr** [comment]
Adapter-Review needed? No worries... review away :smile: 

https://github.com/raintonr/ioBroker.hikvision-alarmserver

**Comment by ldittmar81** [comment]
@raintonr That means it's our turn. Maybe you don't have to do anything else. :-)

**Pull request merged**
