### PR TITLE
New adapter elero-usb-transmitter added.

### PR DESCRIPTION
**Pull request by marc2016**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.elero-usb-transmitter](https://github.com/marc2016/ioBroker.elero-usb-transmitter)
[Downloads](https://www.npmjs.com/package/iobroker.elero-usb-transmitter) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.elero-usb-transmitter/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.elero-usb-transmitter)!. Please execute in adapter directory: `npm owner add bluefox iobroker.elero-usb-transmitter`
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/marc2016/ioBroker.elero-usb-transmitter", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/marc2016/ioBroker.elero-usb-transmitter", press the settings button beside the about title and add some topics.
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Marc <marc@lammers.dev>" at the start of LICENSE
- [ ] :eyes: [W400] Cannot find "elero-usb-transmitter" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by marc2016** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.elero-usb-transmitter](https://github.com/marc2016/ioBroker.elero-usb-transmitter)
[Downloads](https://www.npmjs.com/package/iobroker.elero-usb-transmitter) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.elero-usb-transmitter/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.elero-usb-transmitter)!. Please execute in adapter directory: `npm owner add bluefox iobroker.elero-usb-transmitter`
- [ ] :eyes: [W400] Cannot find "elero-usb-transmitter" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by marc2016** [comment]
I invited bluefox to nom package.

**Comment by Apollon77** [comment]
The including of stable for the other adapter is intended?

**Comment by marc2016** [comment]
Sorry, I pushed this change to the wrong branch. I removed it again.

**Comment by Apollon77** [comment]
Hi,

Here some review comments:
* testing is meeh ... Maybe try to use windows-2019 instead of latest. does it fix the issues?
* Please translate at least the titleLang and these static fields into all languages. YOu can use the iobroker translate tool (see readme/best practices)
* Please respect state.ack in onStateChanged handler. state changes with ack=true must be NOT used to control anything!
* If messages are not needed please remove the handler
* Is https://github.com/marc2016/ioBroker.elero-usb-transmitter/blob/master/package.json#L22 still needed?
* (0.4.0 is missing in changelog in readme)

Thank you for checking and adjusting the topics, please poke again when done

**Comment by marc2016** [comment]
Hi @Apollon77 

thank you for the review!
I have implemented all the comments. The tip with windows-2019 was very good. The workflow is now running.

**Comment by Apollon77** [comment]
Hi, one is left :-)

* please translate https://github.com/marc2016/ioBroker.elero-usb-transmitter/blob/master/io-package.json#L104-L126 :-) you can usethe iobroker translation tool ... see readme of this repo!

Rest is fine

**Comment by marc2016** [comment]
Sorry,  I missed this two :-(

I added the translation :-)

**Comment by Apollon77** [comment]
All good. Please release the 0.5.2 :-)

**Comment by marc2016** [comment]
I released version  0.5.2 :-) Thank you!

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.elero-usb-transmitter](https://github.com/marc2016/ioBroker.elero-usb-transmitter)
[Downloads](https://www.npmjs.com/package/iobroker.elero-usb-transmitter) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.elero-usb-transmitter/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.elero-usb-transmitter)!. Please execute in adapter directory: `npm owner add bluefox iobroker.elero-usb-transmitter`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/marc2016/ioBroker.elero-usb-transmitter/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W400] Cannot find "elero-usb-transmitter" in latest repository
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.panasonic-comfort-cloud](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud)
[Downloads](https://www.npmjs.com/package/iobroker.panasonic-comfort-cloud) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.panasonic-comfort-cloud/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 marc <marc@lammers.dev>" at the end of [README.md](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 marc <marc@lammers.dev>" at the start of LICENSE
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.ph803w](https://github.com/Apollon77/ioBroker.ph803w)
[Downloads](https://www.npmjs.com/package/iobroker.ph803w) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ph803w/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.ph803w)!. Please execute in adapter directory: `npm owner add bluefox iobroker.ph803w`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Apollon77/ioBroker.ph803w/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
All good, but please adress:

> ❗ [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.elero-usb-transmitter)!. Please execute in adapter directory: npm owner add bluefox iobroker.elero-usb-transmitter

Then we are ready for repo

**Comment by marc2016** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.ph803w](https://github.com/Apollon77/ioBroker.ph803w)
[Downloads](https://www.npmjs.com/package/iobroker.ph803w) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ph803w/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.ph803w)!. Please execute in adapter directory: `npm owner add bluefox iobroker.ph803w`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Apollon77/ioBroker.ph803w/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)

### [ioBroker.panasonic-comfort-cloud](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud)
[Downloads](https://www.npmjs.com/package/iobroker.panasonic-comfort-cloud) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.panasonic-comfort-cloud/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 marc <marc@lammers.dev>" at the end of [README.md](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 marc <marc@lammers.dev>" at the start of LICENSE
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.elero-usb-transmitter](https://github.com/marc2016/ioBroker.elero-usb-transmitter)
[Downloads](https://www.npmjs.com/package/iobroker.elero-usb-transmitter) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.elero-usb-transmitter/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.elero-usb-transmitter)!. Please execute in adapter directory: `npm owner add bluefox iobroker.elero-usb-transmitter`
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W400] Cannot find "elero-usb-transmitter" in latest repository
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by marc2016** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.panasonic-comfort-cloud](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud)
[Downloads](https://www.npmjs.com/package/iobroker.panasonic-comfort-cloud) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.panasonic-comfort-cloud/)

- [ ] :heavy_exclamation_mark: [E130] Too many "common.news" found in [io-package.json](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/blob/master/io-package.json). Must be less than 20. Please remove old news.
- [ ] :heavy_exclamation_mark: [E606] Current adapter version 2.0.5 not found in [README.md](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 marc <marc@lammers.dev>" at the start of LICENSE
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)

### [ioBroker.ph803w](https://github.com/Apollon77/ioBroker.ph803w)
[Downloads](https://www.npmjs.com/package/iobroker.ph803w) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ph803w/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.ph803w)!. Please execute in adapter directory: `npm owner add bluefox iobroker.ph803w`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Apollon77/ioBroker.ph803w/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)

### [ioBroker.elero-usb-transmitter](https://github.com/marc2016/ioBroker.elero-usb-transmitter)
[Downloads](https://www.npmjs.com/package/iobroker.elero-usb-transmitter) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.elero-usb-transmitter/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W400] Cannot find "elero-usb-transmitter" in latest repository
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@marc2016 I saw Bluefos is added. Then welcome inn the repo!

**Pull request merged**
