### PR TITLE
Added Birthdays Adapter

### PR DESCRIPTION
**Pull request by klein0r**

### CODE REVIEW

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.birthdays](https://github.com/klein0r/ioBroker.birthdays)
[Downloads](https://www.npmjs.com/package/iobroker.birthdays) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.birthdays/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.birthdays)!. Please execute in adapter directory: `npm owner add bluefox iobroker.birthdays`
- [ ] :eyes: [W400] Cannot find "birthdays" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
All good, I will add to repo, but do you really need that "killTimeout" construct? If yes why? You have set a timeout on the axios request, and so with all rest (if all good async/await) then should never be relevant ... :-)

**Comment by Apollon77** [comment]
Note: Also removes SUnnyportal from repo because no longer working

**Pull request merged**
