### PR TITLE
Squeezeboxroc Adapter latest

### PR DESCRIPTION
**Pull request by oweitman**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
I created a couple of issues :https://github.com/oweitman/ioBroker.squeezeboxrpc/issues

**Comment by oweitman** [comment]
> I created a couple of issues :https://github.com/oweitman/ioBroker.squeezeboxrpc/issues

The issues are fixed

**Comment by Apollon77** [comment]
hey, I also found some things:
* you subscribe to the states twice (one time in main() and one time in the server class. better remove one :)
* you use an interval to disciver things and do external communication. M personally do not like Intervall here because the intervall fires new cals unless f the action from before has finished. When you run into network timeouts this may cause reuests piling up

**Comment by Apollon77** [comment]
And please sort your adapter in on correct alphabetical position!!

**Comment by oweitman** [comment]
> hey, I also found some things:
> 
> * you subscribe to the states twice (one time in main() and one time in the server class. better remove one :)
> * you use an interval to disciver things and do external communication. M personally do not like Intervall here because the intervall fires new cals unless f the action from before has finished. When you run into network timeouts this may cause reuests piling up

both points are fixed and a new release was published to github and npm

**Comment by oweitman** [comment]
> And please sort your adapter in on correct alphabetical position!!

the pull request was updated with another commit to move the adapter in alphabeticaly order

**Comment by GermanBluefox** [comment]
Thank you!

**Pull request merged**
