### PR TITLE
add heos to latest

### PR DESCRIPTION
**Pull request by withstu**
GitHub: https://github.com/withstu/ioBroker.heos
Forum: https://forum.iobroker.net/topic/10420/vorlage-denon-heos-script

Please review and add to Latest.

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heos](https://github.com/withstu/ioBroker.heos)
[Downloads](https://www.npmjs.com/package/iobroker.heos) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.heos/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "heos" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by withstu** [comment]
@GermanBluefox @Apollon77 Any updates here? Can I support you somehow?

**Comment by Apollon77** [comment]
mega sorry ... in the next days

**Comment by Apollon77** [comment]
Hey,
* please make sure thall all Timeouts (also https://github.com/withstu/ioBroker.heos/blob/0ad694a5e3a8b04a92eaa9504f37023a6590a7a6/lib/heos-player.js#L798 ) are reset in onUnload!
* please make sure only to use desfined roles! see https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md#media
* after all sleep you need to check that the adapter was not "unloaded" in between ... https://github.com/withstu/ioBroker.heos/blob/0ad694a5e3a8b04a92eaa9504f37023a6590a7a6/lib/heos-player.js#L1448

**Comment by withstu** [comment]
@Apollon77 Thanks for the feedback. I've fixed the following in the version 1.6.1:
- clear timeouts and intervals before unload
- adapt all roles to the defined role list
- remove the sleep in the tts module completely

**Comment by Apollon77** [comment]
Thank you for the fast reponse, welcome in the repo

**Pull request merged**
