### PR TITLE
add minuvis to latest

### PR DESCRIPTION
**Pull request by SVallant**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.minuvis](https://github.com/minukodu/ioBroker.minuvis)
[Downloads](https://www.npmjs.com/package/iobroker.minuvis) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.minuvis/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.0.4
- [ ] :heavy_exclamation_mark: [E124] Main file not found under URL: https://raw.githubusercontent.com/minukodu/ioBroker.minuvis/master/Gruntfile.js
- [ ] :heavy_exclamation_mark: [E504] "Gruntfile.js found in [package.json](https://github.com/minukodu/ioBroker.minuvis/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/minukodu/ioBroker.minuvis" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "minuvis" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@SVallant could you please look into these findings and fix them?

**Comment by SVallant** [comment]
yes, of course

**Comment by SVallant** [comment]
i copied this configuration from iobroker.rickshaw, (there is also no Gruntfile.js)
since i do not have a main.js and it is " "onlyWWW": true," 
what is the correct configuration ?
Can i delete the "main"-Section in package.json ??

**Comment by Apollon77** [comment]
Delete main in this case should make sense.
(riskshaw is relatively outdated, so ;-)

**Comment by SVallant** [comment]
ok, i will delete it
thank you

**Pull request closed without merging**
