### PR TITLE
Add janitza-gridvis to latest

### PR DESCRIPTION
**Pull request by BenAhrdt**
Please add my adapter ioBroker.janitza-gridvis to latest.

*This pull request was created by https://www.iobroker.dev 79ffd9b.*

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by BenAhrdt** [comment]
@Garfonso Thanks for the hints.
I will check and change them in a fiew days / weeks :-D

here my comments on the first look:

Change to setObjectNotExistsAsync: OK, top. thanks

[https://github.com/BenAhrdt/ioBroker.janitza-gridvis/blob/main/admin/jsonConfig.json#L178](https://github.com/BenAhrdt/ioBroker.janitza-gridvis/blob/main/admin/jsonConfig.json#L178)

**Comment by BenAhrdt** [comment]
I changed the major things

**Comment by Garfonso** [comment]
> => I create this value with the cronjob creater in the config. => ????

Ok, ignore my comment. Seems like I misread something. 

> So now i have to use the words.js?
As discussed in telegram, of course not. But strings that show up in UI should be either translated (if possible) or English.

**Comment by BenAhrdt** [comment]
i have implemented the translation.
so the Adapter will be included?

**Comment by Apollon77** [comment]
Re-Review will be done soon

**Comment by Apollon77** [comment]
hi,

thank you @Garfonso for the great check!

Here my my review feedback whats left:
* when you only have jsonconfig add a globalDependencies for admin >=5.0.0
* do you really log partly in a localized way? You can do that ,.. I wish you much fun when you get teh first chinese debug log to research an issue *gg* thats the reason why logs are usually always english
* Is that number in the State ID really unique? What happens in the grid config or such when you delete something ... might get the ID reused? Else you end in total data mix ...
*

**Comment by BenAhrdt** [comment]
- global dependencies will be added.
- i will change the logs into english => your write.
- the id is unique. if the user deletes a device and creats a new one a used id will not be used again.

**Comment by BenAhrdt** [comment]
Everything should be changed now.
I do some changes i reaction of a beta tester

**Comment by BenAhrdt** [comment]
Is something to do?

**Pull request merged**
