### PR TITLE
add todoist2

### PR DESCRIPTION
**Pull request by rde-master**
add for the first time my adapter todoist2

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.todoist2](https://github.com/rde-master/ioBroker.todoist2)
[Downloads](https://www.npmjs.com/package/iobroker.todoist2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.todoist2/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.todoist2)!. Please execute in adapter directory: `npm owner add bluefox iobroker.todoist2`
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/rde-master/ioBroker.todoist2) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2020 rde-master <info@rde-master.de>" at the start of LICENSE
- [ ] :eyes: [W400] Cannot find "todoist2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by rde-master** [comment]
Hallo,
wenn ich den Adapter Checker durchführe ist nur dieser Fehler drin:

[E701] No actual year found in LICENSE. Please add "Copyright (c) 2020 rde-master <info@rde-master.de>" at the start of LICENSE

Der Satz steht allerdings drin.

**Comment by Apollon77** [comment]
in readme ... yes ,... but here https://github.com/rde-master/ioBroker.todoist2/blob/master/LICENSE not!

**Comment by Apollon77** [comment]
and license ist in your case maybe 2019-2020 or?!

**Comment by rde-master** [comment]
oh sorry, now i have added that.

**Comment by rde-master** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.todoist2](https://github.com/rde-master/ioBroker.todoist2)
[Downloads](https://www.npmjs.com/package/iobroker.todoist2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.todoist2/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "todoist2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hello, some review comments:
* on state Change normally checks for the ack flag because ack=true is normally ignored (beside special reasons)
* your objects miss roles. please add them (see https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md for allowed values)
* As personal Note: Using "interval" with external communications can be problematic on network error sor timeouts because the intervall will "fire the next call" after the given time. Make sure that it can not happen that connections pile up and that porper timeouts are used. A better option is to use timeouts and set them at the end of one call to start next in x ms.
* you might want to add error handling for requests .. e.g. https://github.com/rde-master/ioBroker.todoist2/blob/master/main.js#L431 ... in fact only catching the json parse error might work ... but is not realyl clean way :-)
* you migth want to check the response is really an object before accessing a key (https://github.com/rde-master/ioBroker.todoist2/blob/master/main.js#L477) because in timeout cases it might be empty.
* These timeout construicts are very strange ... https://github.com/rde-master/ioBroker.todoist2/blob/master/main.js#L1956-L2001 Whe  they are used? with propoer await they should not be needed
* you should reset the variabled to null when timeouts were triggered and check that value is there before calling clear because else it might get errors.

**Comment by Apollon77** [comment]
Can I ask why you closed it?

**Comment by mcm1957** [comment]
This issue seems to be outdated

This issue suggests to update the stable version of this adapter to ${issue.to} but in meantime an updateto version ${res[0].latest.version} is sugested.

So this issue will be closed and repleaced by an updates one.

**Pull request closed without merging**
