### PR TITLE
added google-sharedlocations adapter

### PR DESCRIPTION
**Pull request by t4qjXH8N**
This is an adapter to poll the locations from users from Google Sharedlocations. Some users want this adapter to be in the repo.

### CODE REVIEW

**Comment by Apollon77** [comment]
@t4qjXH8N please provide common.license in io-package.json thank you

**Comment by t4qjXH8N** [comment]
I think it is there, isn't it?

**Comment by Apollon77** [comment]
it exists in package.json, but not in io-package.json :-)

**Comment by t4qjXH8N** [comment]
Sorry, it is definitely there in the io-package. json line 5. License is also showing up in the adapter list.

**Pull request merged**
