### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by Jey-Cee**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please also add „published“ key with current date and time.

**Comment by Jey-Cee** [comment]
Done

**Comment by Apollon77** [comment]
Meta and icon from different repos? ;-)

**Comment by GermanBluefox** [comment]
Please add bluefox or iobroker org to owners

**Comment by Apollon77** [comment]
And make testing please green :-)

**Comment by Apollon77** [comment]
... ok testing is missing in package.json :-)

**Comment by Apollon77** [comment]
BTW: Do the adapter really stop after one execution? Maybe you should add a "adapter.stop()" call at the end

**Comment by GermanBluefox** [comment]
Ok? Or not yet?

**Comment by Jey-Cee** [comment]
Yepp OK

**Comment by Apollon77** [comment]
Bu testing partially red :-)

**Pull request merged**
