### PR TITLE
Add clage-dsx to latest

### PR DESCRIPTION
**Pull request by TheBam1990**
Add Clage-DSX adapter

### CODE REVIEW

**Comment by TheBam1990** [comment]
Done the both Error

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.clage-dsx](https://github.com/TheBam1990/ioBroker.clage-dsx)
[Downloads](https://www.npmjs.com/package/iobroker.clage-dsx) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.clage-dsx/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "clage-dsx" in latest repository
- [ ] :eyes: [W801] .npmignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

sorry that it took that long. Here are my review topics:
* Your testing is red. Please update https://github.com/TheBam1990/ioBroker.clage-dsx/blob/master/package.json#L25 to 2.5.x to fix this
* Please get translations for https://github.com/TheBam1990/ioBroker.clage-dsx/blob/master/io-package.json#L31 :-) You can use the translation tool
* Please add a common.globalDependencies with admin >4.0.9 to make sure the encryptedNative functions are supported
* Please check your Ibject definitions.. there are some "Indicators" with "write=true" (e.g. https://github.com/TheBam1990/ioBroker.clage-dsx/blob/master/main.js#L226) and also numbers as "indicators" (normally it is boolean only) -> please check on https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md
* What is that 3s delay for in https://github.com/TheBam1990/ioBroker.clage-dsx/blob/e9ff6922a931e696506b0dc5eff4f6f29637a925/main.js#L138 ? You await the reeponse above so response is there already ;-) (I think also in this case you always were setting the values received 3s before ... and next update was also running
* I think it could be more optional to remember the Agent instance created in https://github.com/TheBam1990/ioBroker.clage-dsx/blob/e9ff6922a931e696506b0dc5eff4f6f29637a925/main.js#L128 instead of creating a new one every 3s (better memory usage!)

Thank you for checking and adjusting

**Comment by ldittmar81** [comment]
@TheBam1990 Have the suggestions been implemented and can we look at the project again or do you need help?

**Comment by Apollon77** [comment]
@TheBam1990 How we should continue? Can we help somehow? Should we do a PR with relevant changes? But that would still require you to verify and test and release it afterwards because the changes can only be done "blind".

**Comment by Apollon77** [comment]
@TheBam1990 Please enable testing in https://github.com/TheBam1990/ioBroker.clage-dsx/pull/2

**Comment by Apollon77** [comment]
@TheBam1990 Maybe you should regenerate package-lock.json once more (iodeally delete package-locl.jsopn and node_modules and execute "npm i" ... then testig coukd work. Then after checking please release new version and we can continue here

**Comment by Apollon77** [comment]
@TheBam1990 Happy new year, how we should proceed?

**Comment by Apollon77** [comment]
@TheBam1990 How we finishe this? Maybe just update once packages and release new npm?

**Comment by mcm1957** [comment]
Please remove node 14 from test-and-release.yml and (optionally) add node 20 to testing matrix.
Node 14 is no longer supported and tests will fail since 22.5.2023.

Thanks
McM1957

**Comment by mcm1957** [comment]
@TheBam1990 

Please let us know if you are still maintaining this adapter and are interested in registration at latest repositories.

If you are still interested I will do a new review to check what issues are still open / already fixed and to get this PR merged.

Please simply post any reply (and check and fix github tests at repository).

**If we do not get any responce with 30 days we will close this PR.** 
But of course a new PR will be welcome at any time.

**Comment by mcm1957** [comment]
@TheBam1990 
A kind reminder
**If we do not receive any response (comment) here this PR will be closed after 6.9.2023**

**Comment by mcm1957** [comment]
@TheBam1990
Ich kann gerne ein neues Review machen um den Handlungsbedarf für eine Aufnahme festzustellen / zu aktualisiseren.
Ich / Wir können auch gerne die Github Dinge wie Anpassung der minimalen Tests machen.
Mangels Hardware kann ich aber die Funktionalität nicht testen.

Da du wenig Zeit hast - wie du schreibst - könnte es auch eine Alternative sein, das Repository in den Bereich iobroker-community-adapters (https://github.com/iobroker-community-adapters) zu verschieben. Dort könnten anderer ioBroker Entwickelr direkt drauf zugreifen und mitarbeiten (icj kann aber derzeit nicht sagen, ob jemand Zeit / Lust und Testhardware hat). Du würdest natürlich weiterhin Schreibzugriuff behalten können. Denk einfach mal drüber nach.

**Comment by mcm1957** [comment]
@TheBam1990 
As there was no reaction to last poll from end 2023 and adapter has not been updated since app 2 years this PR seems to be outdated / stale.

@TheBam1990 
Please respond if you still want this adapter to be added to the repositories and would adapt the adapter if required after review. I'll do a new review then.

**If there is no reaction / comment until 15.04.2024 I will close this PR**

Of course opening a new PR at any time is welcome.

Thanks for writing an adapter for ioBroker.

reminder 31.3.2024

**Comment by mcm1957** [comment]
@TheBam1990 
As there was no reaction to last poll from end 2023 and adapter has not been updated since app 2 years this PR seems to be outdated / stale.

@TheBam1990 
Please respond if you still want this adapter to be added to the repositories and would adapt the adapter if required after review. I'll do a new review then.

**If there is no reaction / comment until 15.04.2024 I will close this PR**

Of course opening a new PR at any time is welcome.

Thanks for writing an adapter for ioBroker.

reminder 31.3.2024

**Comment by mcm1957** [comment]
As there was no reaction this PR has been closed.

**Please feel free to open a new PR as soon as you think the adapter is ready for a new review**

**Pull request closed without merging**
