### PR TITLE
Neuer Adapter: innoxel

### PR DESCRIPTION
**Pull request by matthsc**
Forum thread:
https://forum.iobroker.net/topic/50871/neuer-adapter-innoxel

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.froeling](https://github.com/TA2k/ioBroker.froeling)
[Downloads](https://www.npmjs.com/package/iobroker.froeling) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.froeling/)

:thumbsup: No errors found

### [ioBroker.innoxel](https://github.com/matthsc/ioBroker.innoxel)
[Downloads](https://www.npmjs.com/package/iobroker.innoxel) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.innoxel/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 matthsc <matthsc@gmx.net>" at the end of [README.md](https://github.com/matthsc/ioBroker.innoxel/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 matthsc <matthsc@gmx.net>" at the start of LICENSE
- [ ] :eyes: [W400] Cannot find "innoxel" in latest repository

### [ioBroker.lg-thinq](https://github.com/TA2k/ioBroker.lg-thinq)
[Downloads](https://www.npmjs.com/package/iobroker.lg-thinq) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-thinq/)

:thumbsup: No errors found

### [ioBroker.openhab](https://github.com/iobroker-community-adapters/ioBroker.openhab)
[Downloads](https://www.npmjs.com/package/iobroker.openhab) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.openhab/)

- [ ] :heavy_exclamation_mark: [E104] No common.titleLang found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.openhab) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2017-2022 bluefox <dogafox@gmail.com>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.openhab/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2017-2022 bluefox <dogafox@gmail.com>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.rainbird](https://github.com/StrathCole/ioBroker.rainbird)
[Downloads](https://www.npmjs.com/package/iobroker.rainbird) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.rainbird/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/StrathCole/ioBroker.rainbird/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/StrathCole/ioBroker.rainbird/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2022 Marius Burkard <m.burkard@pixcept.de>" at the end of [README.md](https://github.com/StrathCole/ioBroker.rainbird/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Marius Burkard <m.burkard@pixcept.de>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
lol ... you directly run into the year change :-)) Please update ... and I will do other review later

**Comment by Apollon77** [comment]
Then here some review comments:
* please sync the adapter settings and make sure default values for all are in io-package native section. I think there are some missing.
* To automatically encrypt the password you also need sto edd "encryptedNative" withthat field into io-package.  Right now the password is not getting stored encrypted!
* Please put the admin dependency into section "globalDependencies" instead of "dependencies" in io-package (else admin on the host where adapter runs needs to be in that version ... but there might be no admin on the host
* Please add roles to https://github.com/matthsc/ioBroker.innoxel/blob/main/io-package.json#L103-L125 ... please choose matching values from https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md
* If you require nodejs 12 then please add this to the package.json as "engine" definition https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines
* maybe better check in https://github.com/matthsc/ioBroker.innoxel/blob/main/src/main.ts#L180 that there is no former timeout running ... else you would overwrite it and can not end him anymore. Or can this never happen?

Just some small stuff, Just poke here when you have checked and addressed it.

PS: Happy new year

**Comment by matthsc** [comment]
A happy new year to you too, and thanks for the review and feedback!

I think I addressed all points and published as 0.1.1:

> * please sync the adapter settings and make sure default values for all are in io-package native section. I think there are some missing.

double checked everything, but didn't find any discrepancies between io-package.json, adapter-config.d.ts, and admin settings.tsx.

> * To automatically encrypt the password you also need sto edd "encryptedNative" withthat field into io-package.  Right now the password is not getting stored encrypted!

Done. Hope it is ok to have the field in both encryptedNative and protectedNative? Or should I only use one?

> * Please put the admin dependency into section "globalDependencies" instead of "dependencies" in io-package (else admin on the host where adapter runs needs to be in that version ... but there might be no admin on the host

Done

> * Please add roles to https://github.com/matthsc/ioBroker.innoxel/blob/main/io-package.json#L103-L125 ... please choose matching values from https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md

Done

> * If you require nodejs 12 then please add this to the package.json as "engine" definition https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines

Done

> * maybe better check in https://github.com/matthsc/ioBroker.innoxel/blob/main/src/main.ts#L180 that there is no former timeout running ... else you would overwrite it and can not end him anymore. Or can this never happen?

It ~~can't~~ shouldn't happen, but I try to clear it now before setting it

**Comment by Apollon77** [comment]
> Hope it is ok to have the field in both encryptedNative and protectedNative? Or should I only use one?

Two fields, two purposes ... :-) but in my eyes anything in encrspted should also be in protected

* encryptedNative is for auto encryption
* protectedNative makes sure that only your adapter instance or Admin adapter are allowed to read these fields. For all other "requestors" (getObject) the fields listed there will be removed before object is returned

Rest is fine, welcome in the repo

**Pull request merged**
