### PR TITLE
update version

### PR DESCRIPTION
**Pull request by twonky4**

### CODE REVIEW

**Comment by BuZZy1337** [comment]
Published date must not be changed. It shows the date when the adapter was released for the first time.

**Comment by Apollon77** [comment]
Published date should never be updated.

**Comment by twonky4** [comment]
publish date change reverted

**Comment by Apollon77** [comment]
sources-dist.json (=Latest) should not have a version at all ...

**Comment by twonky4** [comment]
version removed from sources-dist.json

**Pull request merged**
