### PR TITLE
update bsblan version to 0.1.0

### PR DESCRIPTION
**Pull request by hacki11**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bsblan](https://github.com/hacki11/ioBroker.bsblan)
[Downloads](https://www.npmjs.com/package/iobroker.bsblan) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.bsblan/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/hacki11/ioBroker.bsblan", press the first "Edit" button you will find on the page and add the description.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
I accept the PR, but please @hacki11 add the repo text

**Comment by hacki11** [comment]
A description was already set since long time but i had this message in my issues, too. 
Is there an additional description needed?

**Comment by Apollon77** [comment]
yes you are right ... strange. seems to be a false positive

**Comment by Apollon77** [comment]
Thank you for checking

**Pull request merged**
