### PR TITLE
adds netatmo-crawler

### PR DESCRIPTION
**Pull request by Bart1909**

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi, some review comments:
* you should add more error handling ... e.g. https://github.com/Bart1909/ioBroker.netatmo-crawler/blob/master/main.js#L203 ... there are many cases where it is not error, ut also no body or no response is set in the callback and such ...
* adapte core 2.4.0 requires at least js-controller 2.0.0, please update this in io-package dependencies

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.netatmo-crawler](https://github.com/Bart1909/ioBroker.netatmo-crawler)
[Downloads](https://www.npmjs.com/package/iobroker.netatmo-crawler) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.netatmo-crawler/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/Bart1909/ioBroker.netatmo-crawler", press the first "Edit" button you will find on the page and add the description.
- [ ] :eyes: [W400] Cannot find "netatmo-crawler" in latest repository

### [ioBroker.senec](https://github.com/nobl/ioBroker.senec)
[Downloads](https://www.npmjs.com/package/iobroker.senec) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.senec/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/nobl/ioBroker.senec", press the first "Edit" button you will find on the page and add the description.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Please ignore the false positive from the checker. this is ok

**Comment by Bart1909** [comment]
Hi @Apollon77 ,
Version 0.3.0 adds more error handling and requires at least js-controller 2.0.0
(This should be updated in the template-creator i think)

**Comment by Bart1909** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.netatmo-crawler](https://github.com/Bart1909/ioBroker.netatmo-crawler)
[Downloads](https://www.npmjs.com/package/iobroker.netatmo-crawler) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.netatmo-crawler/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/Bart1909/ioBroker.netatmo-crawler", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/Bart1909/ioBroker.netatmo-crawler" and press `Manage topics`
- [ ] :heavy_exclamation_mark: [E603] NO "## Changelog" found in [README.md](https://github.com/Bart1909/ioBroker.netatmo-crawler/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E604] No `## License` found in [README.md](https://github.com/Bart1909/ioBroker.netatmo-crawler/blob/master/README.md)
- [ ] :eyes: [W400] Cannot find "netatmo-crawler" in latest repository

### [ioBroker.senec](https://github.com/nobl/ioBroker.senec)
[Downloads](https://www.npmjs.com/package/iobroker.senec) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.senec/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/nobl/ioBroker.senec", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/nobl/ioBroker.senec" and press `Manage topics`


*Add comment "RE-CHECK!" to start check anew*

**Comment by Bart1909** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.netatmo-crawler](https://github.com/Bart1909/ioBroker.netatmo-crawler)
[Downloads](https://www.npmjs.com/package/iobroker.netatmo-crawler) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.netatmo-crawler/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/Bart1909/ioBroker.netatmo-crawler", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/Bart1909/ioBroker.netatmo-crawler" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "netatmo-crawler" in latest repository

### [ioBroker.senec](https://github.com/nobl/ioBroker.senec)
[Downloads](https://www.npmjs.com/package/iobroker.senec) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.senec/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/nobl/ioBroker.senec", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/nobl/ioBroker.senec" and press `Manage topics`


*Add comment "RE-CHECK!" to start check anew*

**Comment by Bart1909** [comment]
@Apollon77 can you say, when this will be merged?
I‘ve implemented a lot of error handling

**Comment by GermanBluefox** [comment]
You don' need a unload handler. It is empty

**Pull request merged**
