### PR TITLE
Update solarmanpv to 0.2.2

### PR DESCRIPTION
**Pull request by raschy**
Please update my adapter ioBroker.solarmanpv to version 0.2.2.

*This pull request was created by https://www.iobroker.dev 2fef783.*

### CODE REVIEW

**Comment by Apollon77** [comment]
SHould we adjust the adapter type to energy? I think this fits better then iot-systems or?! We can also do that in a followup PR.

**Comment by raschy** [comment]
Yes, we can do that, that's exactly what it is.

**Comment by Apollon77** [comment]
Ok, then please:
* update it in io-package in your repo (no need for a new version) first
* make a PRS here in repo für both files.

**Comment by raschy** [comment]
I have now specified "energy" as the type in the io-package. What is a PRS, please?

**Comment by Apollon77** [comment]
hehe ... a PR ... "Pull Request" ... typo

**Comment by raschy** [comment]
Now it falls on my feet. I should create a PR, but I don't know how to do it.

**Comment by Apollon77** [comment]
easiest way is to go in Github webpage on the file you want to edit and hit the pencil icon, edit what you like and then scroll down and "propose change" ... on next page click "create PR". done

**Pull request merged**
