### PR TITLE
Update to V2.0.3

### PR DESCRIPTION
**Pull request by frankjoke**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.broadlink2](https://github.com/frankjoke/ioBroker.broadlink2)
[Downloads](https://www.npmjs.com/package/iobroker.broadlink2) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.broadlink2/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/frankjoke/ioBroker.broadlink2) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E504] found setInterval in "broadlink2.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2014-2020 Frank Joke <frankjoke@hotmail.com>" at the end of [README.md](https://github.com/frankjoke/ioBroker.broadlink2/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2014-2020 Frank Joke <frankjoke@hotmail.com>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@frankjoke kannst Du mal bitte die Anmerkungen ansehen?

**Comment by frankjoke** [comment]
Ok, mach ich, aber arbeite gerade an V 2.1 und werd es eher dort gelöst haben!

**Pull request merged**
