### PR TITLE
PR FHEM Adapter 1.3.0 latest

### PR DESCRIPTION
**Pull request by LausiD**

### CODE REVIEW

**Comment by LausiD** [comment]
sorry, stable not latest

**Comment by Apollon77** [comment]
ääähm .. nope ... npm is 1.2.1 only ... so first of all I would bring 1.3.0 to latest ... ok?

**Comment by LausiD** [comment]
Yes, of course.New PR 1.3.0 stable after 1.3.0 latest?Sorry, my first time....Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Ingo Fischer <notifications@github.com> Datum: 22.07.19  12:31  (GMT+01:00) An: "ioBroker/ioBroker.repositories" <ioBroker.repositories@noreply.github.com> Cc: LausiD <login@dirk-lausberg.de>, Author <author@noreply.github.com> Betreff: Re: [ioBroker/ioBroker.repositories] PR FHEM Adapter 1.3.0 latest
  (#451) ääähm .. nope ... npm is 1.2.1 only ... so first of all I would bring 1.3.0 to latest ... ok?



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ioBroker/ioBroker.repositories/pull/451?email_source=notifications\u0026email_token=AJHJS22YVCW6YK47NKV7NOLQAWEBZA5CNFSM4IFR5A22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2PP76I#issuecomment-513736697",

"url": "https://github.com/ioBroker/ioBroker.repositories/pull/451?email_source=notifications\u0026email_token=AJHJS22YVCW6YK47NKV7NOLQAWEBZA5CNFSM4IFR5A22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2PP76I#issuecomment-513736697",

"name": "View Pull Request"

},

"description": "View this Pull Request on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Apollon77** [comment]
1.3.0 on npm now, latest soon

**Pull request merged**
