### PR TITLE
Add epson_ecotank_et_2750

### PR DESCRIPTION
**Pull request by o0shojo0o**
https://forum.iobroker.net/topic/40984/test-adapter-epson-ecotank-et-2750-v0-0-x

### CODE REVIEW

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.epson_ecotank_et_2750](https://github.com/o0shojo0o/ioBroker.epson_ecotank_et_2750)
[Downloads](https://www.npmjs.com/package/iobroker.epson_ecotank_et_2750) 
[NPM](https://nodei.co/npm/iobroker.epson_ecotank_et_2750/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "epson_ecotank_et_2750" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hello,

here some review comments:
* Please add a js-controller dependenc to the io.package to require at least js-controller 2.0.0 (because using adapter.core 2.4.0)
* should not be needed https://github.com/o0shojo0o/ioBroker.epson_ecotank_et_2750/blob/master/io-package.json#L61-L66
* why needed? https://github.com/o0shojo0o/ioBroker.epson_ecotank_et_2750/blob/master/main.js#L18
* you shoould await the object creation because else you set a state value efore object is created https://github.com/o0shojo0o/ioBroker.epson_ecotank_et_2750/blob/master/main.js#L128 and following
* with a default synctime of 3h ... should this really be a deamon adaoter? Is not schedule sufficient?

Thank you for checking and adjusting

**Comment by o0shojo0o** [comment]
Thank you for your review, 
i have to admit that I forked a project from the stable and adapted it for the printer and had not looked through them completely. 
Shame on me... 
I have now adjusted the said places and also lowered the default interval to 10 minutes, as I also use it.

**Comment by Apollon77** [comment]
welcome to the repo

**Pull request merged**
