### PR TITLE
Update ioBroker.oppoplayer to 0.2.3

### PR DESCRIPTION
**Pull request by volkerrichert**
### 0.2.3
* (volkerrichert) add missing seconds definitions in io-package.json

### 0.2.2
* (volkerrichert) "enable" compact mode

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.oppoplayer](https://github.com/volkerrichert/ioBroker.oppoplayer)
[Downloads](https://www.npmjs.com/package/iobroker.oppoplayer) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.oppoplayer/)

- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E149] instanceObject common.type has an invalid value: int
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/volkerrichert/ioBroker.oppoplayer/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/volkerrichert/ioBroker.oppoplayer/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/volkerrichert/ioBroker.oppoplayer) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2018-2021 Volker Richert <volker@richert.nrw>" at the end of [README.md](https://github.com/volkerrichert/ioBroker.oppoplayer/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2018-2021 Volker Richert <volker@richert.nrw>" at the start of LICENSE

### [ioBroker.tvprogram](https://github.com/oweitman/ioBroker.tvprogram)
[Downloads](https://www.npmjs.com/package/iobroker.tvprogram) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.tvprogram/)

- [ ] :heavy_exclamation_mark: [E402] Types of adapter in latest repository and in [io-package.json](https://github.com/oweitman/ioBroker.tvprogram/blob/master/io-package.json) are different "misc-data" !== "visualization"
- [ ] :heavy_exclamation_mark: [E422] Types of adapter in stable repository and in [io-package.json](https://github.com/oweitman/ioBroker.tvprogram/blob/master/io-package.json) are different "misc-data" !== "visualization"


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@volkerrichert please check the warnings above. a datatype "int" as used in some of your objects is not existing. Use "number" please.
I would like to decline this PR and ask you to fix that and come back with a new version, ok?

**Comment by volkerrichert** [comment]
hi Apollo, that's fine. 

I'll change int and the other stuff. Where do i find the travis findings?

**Comment by Apollon77** [comment]
https://travis-ci.org/github/volkerrichert/ioBroker.oppoplayer ... nodejs 8 testing should be disabled ... add 14 please

**Pull request closed without merging**
