### PR TITLE
Update sources-dist-stable.json

### PR DESCRIPTION
**Pull request by arteck**
fullybrowser
hs100

### CODE REVIEW

**Comment by DutchmanNL** [comment]
@arteck should we really release this one or remove from repo and replace with tablet control ?

there are now 2 adapter doing exactly the same which is quite inefficient

**Comment by arteck** [comment]
we have 2 hue adapter and 2 fritzbox and and and..

**Comment by Apollon77** [comment]
@DutchmanNL This adapter is NOT controling the tablet! It is controlling the FullyBrowserAPI ... so it can do much more and is another app and a valid approach, so YES we SHOULD have two different adapters unless Tablet Control also can control all aspects of the FulyBrowser App itself

**Comment by DutchmanNL** [comment]
@Apollon77 it does and more, has been developments by Issi as replacement for the fully Browser Adapter and also discussed with the current owner of fully kiosk Adapter who indicated to stop developing this Adapter as new functionality would not be included anymore that's why I was surprised and mentioned it...

**Comment by Apollon77** [comment]
@arteck ??

**Comment by arteck** [comment]
the other Adapter have not a Stable Status .. where is the Problem ?? the Adater is smaller as the other one..

**Pull request merged**
