### PR TITLE
Update ems-esp to 2.5.1

### PR DESCRIPTION
**Pull request by tp1de**
Please update my adapter ioBroker.ems-esp to version 2.5.1.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
Some feedback to Releasenotes:

- replace request by axios
- move database config to parameter page

Those lines are command form, so the user is instructed to replace request or to move the database. Thats definitly not what you want to say :-). Whne reading the german translations you will understand. You better should write

- 'replaced request by axios' or 'request has been replaced by axios'
- database config was moved to parameter page

**Comment by tp1de** [comment]
> * [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI

@mcm1957  I do have difficulties to understand this remark. Do I have to change anything?

**Comment by mcm1957** [comment]
> > * [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
> 
> @mcm1957 I do have difficulties to understand this remark. Do I have to change anything?

You can ignore this warning.
It's only a suggestion to migrate to either jsConfig OR react bassed ui in the long term. Adapterchecker does not difference between checks for repo updates and manual general quality checks and suggestions.

Theres no actionr equired by you
Thanks for asking

**Comment by mcm1957** [comment]
RE-CHECK!

**Pull request merged**
