### PR TITLE
added iobroker.adb to latest

### PR DESCRIPTION
**Pull request by om2804**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by om2804** [comment]
> 
> 
> RE-CHECK!

Translation added. What else ?

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
Hi,
some review comments:
* please do not use setObjectAsync (e.g. https://github.com/om2804/ioBroker.adb/blob/master/main.js#L389) but setObjectNotExistsAsync ... else older js-controller Versions could remove some custom settings on objects
* https://github.com/om2804/ioBroker.adb/blob/master/main.js#L390 should be "device" as object type and not state because it is the parent of the other objects
* what you write here for a file? https://github.com/om2804/ioBroker.adb/blob/master/main.js#L366 I can not find a meta file called "tts.userfiles" (and also that name makes not really sense or?! You should see errors in log with js.controller 3

**Comment by om2804** [comment]
>     * what you write here for a file? https://github.com/om2804/ioBroker.adb/blob/master/main.js#L366 I can not find a meta file called "tts.userfiles" (and also that name makes not really sense or?! You should see errors in log with js.controller 3

Screenshot write to adapter folder by relative path
E.g. absolute path for Windows C:\iobroker\SmartHome\iobroker-data\files\adb.0\tts.userfiles\screenshot.png

**Comment by om2804** [comment]
> Hi,
> some review comments:
> 
>     * please do not use setObjectAsync (e.g. https://github.com/om2804/ioBroker.adb/blob/master/main.js#L389) but setObjectNotExistsAsync ... else older js-controller Versions could remove some custom settings on objects
> 
>     * https://github.com/om2804/ioBroker.adb/blob/master/main.js#L390 should be "device" as object type and not state because it is the parent of the other objects
> 
>     * what you write here for a file? https://github.com/om2804/ioBroker.adb/blob/master/main.js#L366 I can not find a meta file called "tts.userfiles" (and also that name makes not really sense or?! You should see errors in log with js.controller 3

fixed it

**Comment by Apollon77** [comment]
Hey @om2804,

sorry for the mega delay. I have one last comment:
* with the adapter-core 2.4.0 dependency the js.controller dependency in io-package too to go to >=2.0.0

Thenk you that adjustment. :-)

**Comment by om2804** [comment]
>     * with the adapter-core 2.4.0 dependency the js.controller dependency in io-package too to go to >=2.0.0

done

**Comment by Apollon77** [comment]
welcome

**Pull request merged**
