### PR TITLE
Adding MieleCloudService v1.0.5 to stable repo

### PR DESCRIPTION
**Pull request by Grizzelbee**
according to issue https://github.com/Grizzelbee/ioBroker.mielecloudservice/issues/16

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.org](https://travis-ci.org/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.
Add comment "RE-CHECK!" to start check anew

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.
Add comment "RE-CHECK!" to start check anew

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Ok, hp-ilo irrelevant here (was just "touched" because a space).

**Comment by Apollon77** [comment]
Tests are green too ...

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hp-ilo](https://github.com/SebastianSchultz/ioBroker.hp-ilo)
[Downloads](https://www.npmjs.com/package/iobroker.hp-ilo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hp-ilo/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "hp-ilo.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Sebastian Schultz <mail@sebastian-schultz.de>" at the end of [README.md](https://github.com/SebastianSchultz/ioBroker.hp-ilo/blob/master/README.md)

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
