### PR TITLE
Update countdown to 2.0.1

### PR DESCRIPTION
**Pull request by jack-blackson**

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.countdown](https://github.com/jack-blackson/ioBroker.countdown)
[Downloads](https://www.npmjs.com/package/iobroker.countdown) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.countdown/)

- [ ] :heavy_exclamation_mark: [E606] Current adapter version 2.0.1 not found in [README.md](https://github.com/jack-blackson/ioBroker.countdown/blob/master/README.md)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.countdown](https://github.com/jack-blackson/ioBroker.countdown)
[Downloads](https://www.npmjs.com/package/iobroker.countdown) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.countdown/)

- [ ] :heavy_exclamation_mark: [E606] Current adapter version 2.0.1 not found in [README.md](https://github.com/jack-blackson/ioBroker.countdown/blob/master/README.md)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
E606 seems to be false positive

**Comment by jack-blackson** [comment]
> @jack-blackson E606 is caused by an incorrect fiormatting if revision headers. It should be level three (### 1.2.3 ...) but is level two (## 1.2.2 ...) so it is not detected by checker. Please fix with next release (or use @alcazone/release-script).
> 
> Everything's fine for now

Thanks for checking. I updated the readme file.

**Pull request merged**
