### PR TITLE
Add envertech-pv to latest

### PR DESCRIPTION
**Pull request by mcm1957**
Please add my adapter ioBroker.envertech-pv to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
replacemengt for #2189 which has been deleted on error during test

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.envertech-pv](https://github.com/iobroker-community-adapters/ioBroker.envertech-pv)
[Downloads](https://www.npmjs.com/package/iobroker.envertech-pv) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.envertech-pv/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.envertech-pv/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "envertech-pv" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
NOTE: This adapter has been written by me (at least major pafrts).
So use LGTM with attention and take a look anyway. I only want to indicate, that I am not aware of problems

**Pull request merged**
