### PR TITLE
solarlog v1.2.2 to stable

### PR DESCRIPTION
**Pull request by forelleblau**
feedback see: [Forum:Tester](https://forum.iobroker.net/topic/27793/test-adapter-solarlog-v1-2-x-latest/6)

### CODE REVIEW

**Comment by forelleblau** [comment]
feedback for luxtronik1 see [Forum](https://forum.iobroker.net/topic/20185/adapter-luxtronik-1-w%C3%A4rmepumpensteuerung/49)

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.solarlog](https://github.com/iobroker-community-adapters/ioBroker.solarlog)
[Downloads](https://www.npmjs.com/package/iobroker.solarlog) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.solarlog/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2018-2020 Marcel Adam <marceladam@gmx.ch>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.solarlog/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2018-2020 Marcel Adam <marceladam@gmx.ch>" at the start of LICENSE
- [ ] :eyes: [W505] setTimout found in "main.js, but no clearTimeout detected
- [ ] :eyes: [W801] .npmignore not found
- [ ] :eyes: [W901] .gitignore not found

### [ioBroker.luxtronik1](https://github.com/iobroker-community-adapters/ioBroker.luxtronik1)
[Downloads](https://www.npmjs.com/package/iobroker.luxtronik1) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luxtronik1/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2018-2020 Marcel Adam <marceladam@gmx.ch>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.luxtronik1/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2018-2020 Marcel Adam <marceladam@gmx.ch>" at the start of LICENSE
- [ ] :eyes: [W505] setTimout found in "main.js, but no clearTimeout detected
- [ ] :eyes: [W801] .npmignore not found
- [ ] :eyes: [W901] .gitignore not found

**Comment by forelleblau** [comment]
E605 & E701 fixed @ solarlog & luxtronik1

**Comment by Apollon77** [comment]
Then please oush new version number here in this PR

**Comment by forelleblau** [comment]
Sorry, hope it's ok now:
solarlog now published as v1.2.3 on github & npm.
luxtronik1 now published as v0.2.1 on github & npm.

**Comment by forelleblau** [comment]
Once more sorry, now travis-checks fail and I don't know why.

**Comment by forelleblau** [comment]
Ich hoffe, jetzt ist alles in Ordnung. Die Fehler sind behoben, die aktuellen Versionennummern sind im PR und die Travis-Tests der Adapter sind auch wieder grün.

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.luxtronik1](https://github.com/iobroker-community-adapters/ioBroker.luxtronik1)
[Downloads](https://www.npmjs.com/package/iobroker.luxtronik1) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luxtronik1/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js, but no clearTimeout detected
- [ ] :eyes: [W801] .npmignore not found
- [ ] :eyes: [W901] .gitignore not found

### [ioBroker.solarlog](https://github.com/iobroker-community-adapters/ioBroker.solarlog)
[Downloads](https://www.npmjs.com/package/iobroker.solarlog) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.solarlog/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js, but no clearTimeout detected
- [ ] :eyes: [W801] .npmignore not found
- [ ] :eyes: [W901] .gitignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
> Ich hoffe, jetzt ist alles in Ordnung.

Scheinbar ist da noch was

**Comment by forelleblau** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.luxtronik1](https://github.com/iobroker-community-adapters/ioBroker.luxtronik1)
[Downloads](https://www.npmjs.com/package/iobroker.luxtronik1) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luxtronik1/)

:thumbsup: No errors found

### [ioBroker.solarlog](https://github.com/iobroker-community-adapters/ioBroker.solarlog)
[Downloads](https://www.npmjs.com/package/iobroker.solarlog) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.solarlog/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
But now the versions should get updated, or ?!

**Comment by forelleblau** [comment]
Is on the way, as soon as I‘ll find a Minute....

**Comment by forelleblau** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.luxtronik1](https://github.com/iobroker-community-adapters/ioBroker.luxtronik1)
[Downloads](https://www.npmjs.com/package/iobroker.luxtronik1) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luxtronik1/)

- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E814] file appveyor.yml found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore

### [ioBroker.solarlog](https://github.com/iobroker-community-adapters/ioBroker.solarlog)
[Downloads](https://www.npmjs.com/package/iobroker.solarlog) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.solarlog/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by forelleblau** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.luxtronik1](https://github.com/iobroker-community-adapters/ioBroker.luxtronik1)
[Downloads](https://www.npmjs.com/package/iobroker.luxtronik1) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luxtronik1/)

:thumbsup: No errors found

### [ioBroker.solarlog](https://github.com/iobroker-community-adapters/ioBroker.solarlog)
[Downloads](https://www.npmjs.com/package/iobroker.solarlog) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.solarlog/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by forelleblau** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.luxtronik1](https://github.com/iobroker-community-adapters/ioBroker.luxtronik1)
[Downloads](https://www.npmjs.com/package/iobroker.luxtronik1) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luxtronik1/)

:thumbsup: No errors found

### [ioBroker.solarlog](https://github.com/iobroker-community-adapters/ioBroker.solarlog)
[Downloads](https://www.npmjs.com/package/iobroker.solarlog) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.solarlog/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by forelleblau** [comment]
So, hope I'm ready now. Travis is green, checker has 2 thumbs up, versions updated and pushed to npm, up-to-date version number in PR.....

**Comment by Apollon77** [comment]
Thank you

**Pull request merged**
