### PR TITLE
update admin 4 and web 3 "chains"

### PR DESCRIPTION
**Pull request by Apollon77**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.admin](https://github.com/ioBroker/ioBroker.admin)
[Downloads](https://www.npmjs.com/package/iobroker.admin) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.admin/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/ioBroker/ioBroker.admin) are broken. Please fix.
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.cloud](https://github.com/ioBroker/ioBroker.cloud)
[Downloads](https://www.npmjs.com/package/iobroker.cloud) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.cloud/)

- [ ] :heavy_exclamation_mark: [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html 
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 bluefox <dogafox@gmail.com>" at the end of [README.md](https://github.com/ioBroker/ioBroker.devices/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2020 bluefox <dogafox@gmail.com>" at the start of LICENSE

### [ioBroker.habpanel](https://github.com/iobroker-community-adapters/ioBroker.habpanel)
[Downloads](https://www.npmjs.com/package/iobroker.habpanel) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.habpanel/)

- [ ] :heavy_exclamation_mark: [E021] "licenses" in [package.json](https://github.com/iobroker-community-adapters/ioBroker.habpanel/blob/master/package.json) are depricated. Please use only "license": "NAME" field.
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.habpanel) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E604] No `## License` found in [README.md](https://github.com/iobroker-community-adapters/ioBroker.habpanel/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore

### [ioBroker.iot](https://github.com/ioBroker/ioBroker.iot)
[Downloads](https://www.npmjs.com/package/iobroker.iot) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iot/)

:thumbsup: No errors found

### [ioBroker.javascript](https://github.com/ioBroker/ioBroker.javascript)
[Downloads](https://www.npmjs.com/package/iobroker.javascript) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.javascript/)

:thumbsup: No errors found

### [ioBroker.material](https://github.com/ioBroker/ioBroker.material)
[Downloads](https://www.npmjs.com/package/iobroker.material) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.material/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/ioBroker/ioBroker.material) are broken. Please fix.

### [ioBroker.socketio](https://github.com/ioBroker/ioBroker.socketio)
[Downloads](https://www.npmjs.com/package/iobroker.socketio) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.socketio/)

- [ ] :heavy_exclamation_mark: [E021] "licenses" in [package.json](https://github.com/ioBroker/ioBroker.socketio/blob/master/package.json) are depricated. Please use only "license": "NAME" field.

### [ioBroker.web](https://github.com/ioBroker/ioBroker.web)
[Downloads](https://www.npmjs.com/package/iobroker.web) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.web/)

- [ ] :heavy_exclamation_mark: [E604] No `## License` found in [README.md](https://github.com/ioBroker/ioBroker.web/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2014-2020 bluefox <dogafox@gmail.com>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.admin](https://github.com/ioBroker/ioBroker.admin)
[Downloads](https://www.npmjs.com/package/iobroker.admin) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.admin/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/ioBroker/ioBroker.admin) are broken. Please fix.
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.cloud](https://github.com/ioBroker/ioBroker.cloud)
[Downloads](https://www.npmjs.com/package/iobroker.cloud) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.cloud/)

- [ ] :heavy_exclamation_mark: [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html 
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 bluefox <dogafox@gmail.com>" at the end of [README.md](https://github.com/ioBroker/ioBroker.devices/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2020 bluefox <dogafox@gmail.com>" at the start of LICENSE

### [ioBroker.habpanel](https://github.com/iobroker-community-adapters/ioBroker.habpanel)
[Downloads](https://www.npmjs.com/package/iobroker.habpanel) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.habpanel/)

- [ ] :heavy_exclamation_mark: [E021] "licenses" in [package.json](https://github.com/iobroker-community-adapters/ioBroker.habpanel/blob/master/package.json) are depricated. Please use only "license": "NAME" field.
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.habpanel) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E604] No `## License` found in [README.md](https://github.com/iobroker-community-adapters/ioBroker.habpanel/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore

### [ioBroker.iot](https://github.com/ioBroker/ioBroker.iot)
[Downloads](https://www.npmjs.com/package/iobroker.iot) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iot/)

:thumbsup: No errors found

### [ioBroker.javascript](https://github.com/ioBroker/ioBroker.javascript)
[Downloads](https://www.npmjs.com/package/iobroker.javascript) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.javascript/)

:thumbsup: No errors found

### [ioBroker.material](https://github.com/ioBroker/ioBroker.material)
[Downloads](https://www.npmjs.com/package/iobroker.material) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.material/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/ioBroker/ioBroker.material) are broken. Please fix.

### [ioBroker.socketio](https://github.com/ioBroker/ioBroker.socketio)
[Downloads](https://www.npmjs.com/package/iobroker.socketio) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.socketio/)

- [ ] :heavy_exclamation_mark: [E021] "licenses" in [package.json](https://github.com/ioBroker/ioBroker.socketio/blob/master/package.json) are depricated. Please use only "license": "NAME" field.

### [ioBroker.web](https://github.com/ioBroker/ioBroker.web)
[Downloads](https://www.npmjs.com/package/iobroker.web) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.web/)

- [ ] :heavy_exclamation_mark: [E604] No `## License` found in [README.md](https://github.com/ioBroker/ioBroker.web/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2014-2020 bluefox <dogafox@gmail.com>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.admin](https://github.com/ioBroker/ioBroker.admin)
[Downloads](https://www.npmjs.com/package/iobroker.admin) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.admin/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/ioBroker/ioBroker.admin) are broken. Please fix.

### [ioBroker.cloud](https://github.com/ioBroker/ioBroker.cloud)
[Downloads](https://www.npmjs.com/package/iobroker.cloud) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.cloud/)

- [ ] :heavy_exclamation_mark: [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html 

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)

### [ioBroker.habpanel](https://github.com/iobroker-community-adapters/ioBroker.habpanel)
[Downloads](https://www.npmjs.com/package/iobroker.habpanel) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.habpanel/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.habpanel) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E604] No `## License` found in [README.md](https://github.com/iobroker-community-adapters/ioBroker.habpanel/blob/master/README.md)

### [ioBroker.iot](https://github.com/ioBroker/ioBroker.iot)
[Downloads](https://www.npmjs.com/package/iobroker.iot) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iot/)

:thumbsup: No errors found

### [ioBroker.javascript](https://github.com/ioBroker/ioBroker.javascript)
[Downloads](https://www.npmjs.com/package/iobroker.javascript) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.javascript/)

:thumbsup: No errors found

### [ioBroker.material](https://github.com/ioBroker/ioBroker.material)
[Downloads](https://www.npmjs.com/package/iobroker.material) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.material/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/ioBroker/ioBroker.material) are broken. Please fix.

### [ioBroker.socketio](https://github.com/ioBroker/ioBroker.socketio)
[Downloads](https://www.npmjs.com/package/iobroker.socketio) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.socketio/)

:thumbsup: No errors found

### [ioBroker.web](https://github.com/ioBroker/ioBroker.web)
[Downloads](https://www.npmjs.com/package/iobroker.web) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.web/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
