### PR TITLE
Add zigbee2mqtt

### PR DESCRIPTION
**Pull request by o0shojo0o**

### CODE REVIEW

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.zigbee2mqtt](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt)
[Downloads](https://www.npmjs.com/package/iobroker.zigbee2mqtt) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.zigbee2mqtt/)

:thumbsup: No errors found
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W400] Cannot find "zigbee2mqtt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,
hhere a short review feedback:

* not critical but if you use Async you shoulkd also await it ... or use the "Non async" method :-) e.g. https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/blob/main/main.js#L55
* please also close the websocket/mqtt connections on unload

Rest I only fly over and looked ok ... Please check and adjust the above

**Comment by o0shojo0o** [comment]
Thank you for your review, I have fixed all the points.

**Comment by o0shojo0o** [comment]
@Apollon77 are there still open points?

**Comment by Apollon77** [comment]
Yes me finding time for recheck.

**Comment by o0shojo0o** [comment]
Add to stable @2.5.0

**Comment by o0shojo0o** [comment]
Update stable to v2.6.0

**Comment by Apollon77** [comment]
oooooohhhhh @o0shojo0o one thing ... type "lighting"??? I think it is more or? type "hardware" like ziugbee adapter?

A change here would be "io.package change on github" and the PR here ... Can you please do that before I merge?
A new release is not urgently needed ... enough for next update

**Comment by o0shojo0o** [comment]
fixed ;)

**Pull request merged**
