### PR TITLE
Added volumio adapter

### PR DESCRIPTION
**Pull request by a-i-ks**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.volumio](https://github.com/a-i-ks/ioBroker.volumio)
[Downloads](https://www.npmjs.com/package/iobroker.volumio) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.volumio/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "volumio" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by a-i-ks** [comment]
Have I forgotten anything?

**Comment by Apollon77** [comment]
Hi,

her emy review commemts:
* please also add the "info" channel in the instanceObjects :-)
* you might want to catch error slike https://github.com/a-i-ks/ioBroker.volumio/runs/1866445280#step:6:367, else the adapter might crash directly when unconfigured?!
* please make sure to also close the http server you open in unload - basically cleanup ALL resources!!

Thank you for checking and adjusting that

**Comment by a-i-ks** [comment]
Thanks for the review and comments. This is my first JavaScript project and I am still learning. I will be fixing this. How should I proceed regarding this? The current version (0.1.0) is already released. That means I will now incorporate the review comments into a 0.1.1 and then adapt this pull request.

**Comment by Apollon77** [comment]
Exactly, just leave open here and update the PR with new version and ping us for another review round :-)

**Comment by a-i-ks** [comment]
All review comments have been implemented

**Comment by Apollon77** [comment]
Hey, without conflig like started in testing you still have some missing error handling ... https://github.com/a-i-ks/ioBroker.volumio/runs/1931436539?check_suite_focus=true#step:6:375

Please catch such stuff and add proper checks

**Comment by a-i-ks** [comment]
The problem should be fixed now. The tests run without unhandled exceptions. Thanks for the feedback.

**Comment by Apollon77** [comment]
Thank you!

**Pull request merged**
