### PR TITLE
add ioBroker.adguard to latest

### PR DESCRIPTION
**Pull request by o0shojo0o**

### CODE REVIEW

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.adguard](https://github.com/o0shojo0o/ioBroker.adguard)
[Downloads](https://www.npmjs.com/package/iobroker.adguard) 
[NPM](https://nodei.co/npm/iobroker.adguard/)

- [ ] :heavy_exclamation_mark: [E104] No common.title found in [io-package.json](https://github.com/o0shojo0o/ioBroker.adguard/blob/master/io-package.json)


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.adguard](https://github.com/o0shojo0o/ioBroker.adguard)
[Downloads](https://www.npmjs.com/package/iobroker.adguard) 
[NPM](https://nodei.co/npm/iobroker.adguard/)

- [ ] :heavy_exclamation_mark: [E104] No common.title found in [io-package.json](https://github.com/o0shojo0o/ioBroker.adguard/blob/master/io-package.json)


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.adguard](https://github.com/o0shojo0o/ioBroker.adguard)
[Downloads](https://www.npmjs.com/package/iobroker.adguard) 
[NPM](https://nodei.co/npm/iobroker.adguard/)

- [ ] :heavy_exclamation_mark: [E104] No common.title found in [io-package.json](https://github.com/o0shojo0o/ioBroker.adguard/blob/master/io-package.json)


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.adguard](https://github.com/o0shojo0o/ioBroker.adguard)
[Downloads](https://www.npmjs.com/package/iobroker.adguard) 
[NPM](https://nodei.co/npm/iobroker.adguard/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi, here some review comments:
* if possible please only call setObjectsNotExists if it is first time in the run and object known (https://github.com/o0shojo0o/ioBroker.adguard/blob/989877992eb4dde79513592c3bd84803ee8e9f02/build/main.js#L191) ... it costs some resources and time
* in unload you should remember that it was called https://github.com/o0shojo0o/ioBroker.adguard/blob/989877992eb4dde79513592c3bd84803ee8e9f02/build/main.js#L97 ... else the case could happen that you start requesting all your stuff, then someone stops adapter and the timoeut is cleared ... but code at the end simply starts s new one because it do not know that unload was called in the meantime
Please have a look. In fact both topics no show stoppers for repo entry, but if you like to fix first I would wait ... Give me Feedback please

**Comment by o0shojo0o** [comment]
Hi and thanks again for your review, I will gladly try to optimize the adapter according to your suggestions!
Are you maybe today or the days in Discord online?

Greetings
Dennis

**Comment by Apollon77** [comment]
Try Discord, I should see it :-) ... but you can also try the developer channer there, there arse some devs more to help out and I might see questions there faster

**Comment by o0shojo0o** [comment]
is adjusted with v0.0.6

**Comment by Apollon77** [comment]
welcome in the repo

**Pull request merged**
