### PR TITLE
add todoist2

### PR DESCRIPTION
**Pull request by rde-master**
add Todoist 0.4.0

### CODE REVIEW

**Comment by rde-master** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.todoist2](https://github.com/rde-master/ioBroker.todoist2)
[Downloads](https://www.npmjs.com/package/iobroker.todoist2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.todoist2/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/rde-master/ioBroker.todoist2) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/rde-master/ioBroker.todoist2", press the first "Edit" button you will find on the page and add the description.
- [ ] :eyes: [W400] Cannot find "todoist2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by rde-master** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.todoist2](https://github.com/rde-master/ioBroker.todoist2)
[Downloads](https://www.npmjs.com/package/iobroker.todoist2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.todoist2/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/rde-master/ioBroker.todoist2) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/rde-master/ioBroker.todoist2", press the first "Edit" button you will find on the page and add the description.
- [ ] :eyes: [W400] Cannot find "todoist2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by rde-master** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.todoist2](https://github.com/rde-master/ioBroker.todoist2)
[Downloads](https://www.npmjs.com/package/iobroker.todoist2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.todoist2/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/rde-master/ioBroker.todoist2) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/rde-master/ioBroker.todoist2", press the first "Edit" button you will find on the page and add the description.
- [ ] :eyes: [W400] Cannot find "todoist2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by rde-master** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.todoist2](https://github.com/rde-master/ioBroker.todoist2)
[Downloads](https://www.npmjs.com/package/iobroker.todoist2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.todoist2/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/rde-master/ioBroker.todoist2) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/rde-master/ioBroker.todoist2", press the first "Edit" button you will find on the page and add the description.
- [ ] :eyes: [W400] Cannot find "todoist2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
* Please clean up your package.json ... there is stuff in that only is there when you did an npm install of that package (basically all the keys with _ at the beginning.
* Please also add the info channel object in https://github.com/rde-master/ioBroker.todoist2/blob/master/io-package.json#L114
* supportsCustom and the custom view is included in io-package but no custom_m defined ... so I expect it can be removed or?
* why a restartSchedule is defined? https://github.com/rde-master/ioBroker.todoist2/blob/master/io-package.json#L73

**Comment by rde-master** [comment]
all your comments are done:
- package.json is cleand up
- info channel object ist added
- supports Custom and custom view ist deletet
- schedule is deletet (it was for the Case, that the connection is lost,... i build a logic so that is no longer needed)

I have added version 0.6.0 to npm to...

**Comment by rde-master** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.todoist2](https://github.com/rde-master/ioBroker.todoist2)
[Downloads](https://www.npmjs.com/package/iobroker.todoist2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.todoist2/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/rde-master/ioBroker.todoist2", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/rde-master/ioBroker.todoist2" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "todoist2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.todoist2](https://github.com/rde-master/ioBroker.todoist2)
[Downloads](https://www.npmjs.com/package/iobroker.todoist2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.todoist2/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "todoist2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request closed without merging**
