### PR TITLE
update daswetter, ebus and sbfspot

### PR DESCRIPTION
**Pull request by rg-engineering**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.daswetter](https://github.com/rg-engineering/ioBroker.daswetter)
[Downloads](https://www.npmjs.com/package/iobroker.daswetter) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.daswetter/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.ebus](https://github.com/rg-engineering/ioBroker.ebus)
[Downloads](https://www.npmjs.com/package/iobroker.ebus) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ebus/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.sbfspot](https://github.com/rg-engineering/ioBroker.sbfspot)
[Downloads](https://www.npmjs.com/package/iobroker.sbfspot) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sbfspot/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
These timeouts .... for what they are used? Each interval and timeout needs to be clearer in “ unload” or else compact mode will break!! Please check.

**Comment by rg-engineering** [comment]
the timeouts are used to stop adapter after certain time. All adapters are scheduled adapter and could hang for external reasons (waiting for data). So I use a timeout to force termination of adapter.
since this was only a warning I thought I can fix this later?

**Comment by Apollon77** [comment]
Ok in this case. Just wanted to make sure it is Adressed. And for scheduled the compact mode is also not yet relevant. But in fact you should try to check the async Code flow and set proper timeouts for requests. Then such a failsafe stop timeout should not be needed at all ;-)

**Pull request merged**
