### PR TITLE
Please add adapter merakicmx to repository latest.

### PR DESCRIPTION
**Pull request by MiGoller**
Hey all,

please add my adapter ioBroker.merakicmx to the repository latest. There are no known issues to me and I still did not receive any negative feedback on https://forum.iobroker.net/topic/32352/test-adapter-merakicmx-v0-2-x-github-npm .

This is my first pull request to add one of my adapters to an ioBroker repository. Please let me know, if I will have to fulfill any further steps.

KR,
Michael

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.merakicmx](https://github.com/MiGoller/ioBroker.merakicmx)
[Downloads](https://www.npmjs.com/package/iobroker.merakicmx) 
[NPM](https://nodei.co/npm/iobroker.merakicmx/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "merakicmx" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
@MiGoller 

* please do subscribe unneeded to object changes (code does not do anything but triggers on changes) n:
https://github.com/MiGoller/ioBroker.merakicmx/blob/master/main.js#L31
https://github.com/MiGoller/ioBroker.merakicmx/blob/master/main.js#L83-L90

* same for on state change 
https://github.com/MiGoller/ioBroker.merakicmx/blob/master/main.js#L32
https://github.com/MiGoller/ioBroker.merakicmx/blob/master/main.js#L98-L106

* on massage example from template can also be removed ?
https://github.com/MiGoller/ioBroker.merakicmx/blob/master/main.js#L33
https://github.com/MiGoller/ioBroker.merakicmx/blob/master/main.js#L108-L123

* better use timeout instead of interval to avoid multiple running processes (only start new time when previous action is completed)
https://github.com/MiGoller/ioBroker.merakicmx/blob/master/main.js#L54

**Comment by MiGoller** [comment]
@DutchmanNL 
Thank you for your feedback. 

- I've removed unneeded code and replaced intervals by a timeout implementation. 
- Travis CI builds are ok and the adapter works fine after modification in my testing environment.
- I've updated version to 0.2.7

**Comment by MiGoller** [comment]
Is there anything more I have to do?

**Comment by Apollon77** [comment]
Hi, sorry for the delay. Here some review comments and required changes:
* with adapter-core 2.4.0 as dep you need to require at least js-controller 2.0
* would it make sense to store the secret encrypted? js.controller 3 can support here automatically
* is this timout at https://github.com/MiGoller/ioBroker.merakicmx/blob/master/lib/merakiCmxDbConnector.js#L488 also cleared at unload?
* tip: add on('error') handler to https://github.com/MiGoller/ioBroker.merakicmx/blob/master/lib/cmxreceiver.js ... else it can lead to exceptions and crashes

Thank you for checking and adjusting it

**Comment by MiGoller** [comment]
Hey @Apollon77 ,

thank you for your feedback. I've updated the dependencies and modified the code to clear the mentioned timeout under any circumstances. Can you give me a hint to find an example for the encrypted values mit js-controller 3.x?

But I'm struggling adding an error handler to cmreceiver.js. Right now I just can treat exceptions like bind address is in use only with a basic uncaughtException pattern. I'll have a further look at it the next days.

Thx,

KR,
Michael

**Comment by Apollon77** [comment]
an app.on('error', err => {...}) should work or?!

For auto encrypt you need:
* config https://github.com/iobroker-community-adapters/ioBroker.tr-064/blob/master/io-package.json#L311-L316

And if you do not want to limit to js-controller 3 you also need "fallback" code like
* https://github.com/iobroker-community-adapters/ioBroker.tr-064/blob/master/admin/index_m.html#L246-L248
* https://github.com/iobroker-community-adapters/ioBroker.tr-064/blob/master/admin/index_m.html#L382-L384
* https://github.com/iobroker-community-adapters/ioBroker.tr-064/blob/master/main.js#L111-L121

If you say "hey js-controller 3 is enough" then you just need nothing but the config

**Comment by MiGoller** [comment]
Hey @Apollon77 ,

Thanks a lot! I'll adopt the pattern to support js-controller 2.x as well. The mentioned code snippets will do the trick.

But adding the `on('error', err => {...})` handler to the Express Application does not work; Express 4.x applications just support mount events (`on('mount', err => {...})`) (s. http://expressjs.com/en/4x/api.html#app.onmount). But the created Node.js [http(s)-server](https://nodejs.org/api/http.html#http_class_http_server) does support error events. Errors like addresses or ports are already in use will not throw an uncaught exception and will not crash and restart the adapter anymore.

I'll let you know when I'll have finished the modifications. Thx again.

Kind Regards,
MiGoller

**Comment by Apollon77** [comment]
great to hear that the review feedback was valuable

**Comment by Apollon77** [comment]
@MiGoller Hey, any update?

**Comment by MiGoller** [comment]
Hey @Apollon77 . I wasn't operational for a while, but I'll start to continue the modifications. KR, MiGoller

**Comment by Apollon77** [comment]
Just tell when done! Good luck

**Comment by Apollon77** [comment]
@MiGoller Can we support anyhow?

**Comment by MiGoller** [comment]
@Apollon77 Thank you very much. Just had a lot of work at the office after leaving the hospital. Just started to work at my ioBroker adapters to get them added to the ioBroker repositories. I'll let you know if you could support anyhow, ok?

**Comment by Apollon77** [comment]
Awesome! If you need support or developer exchange join telegram groups or Discord ... some devs are always around there :-)

**Comment by DutchmanNL** [comment]
Hier der link zur Discord Kommune https://discord.gg/HwUCwsH

**Comment by Apollon77** [comment]
@MiGoller Any news?

**Comment by ldittmar81** [comment]
@MiGoller - Hello MiGoller... do you need some help with the development?

**Comment by Apollon77** [comment]
@MiGoller How we should continue? Can we help somehow? Should we do a PR with relevant changes?

**Comment by Apollon77** [comment]
@MiGoller Happy new year, how we should proceed?

**Comment by MiGoller** [comment]
@Apollon77 , thank you for your support. Please close the request; I'll continue to enhance my Life360 adapter to get it added to the repo but not this adapter.

**Comment by Apollon77** [comment]
@MiGoller I could also offer to provide a PR to adress the issues ... then it would be just testing that then ... because honestly ... it is not much what is left here ....

**Comment by MiGoller** [comment]
Hey @Apollon77 , thank you very much for your assistance. Please provide a PR and I'll do the tests. Thx

**Comment by Apollon77** [comment]
I will try to find time soon, sorry for the delay

**Comment by Apollon77** [comment]
I might not find time soon ...

**Comment by mcm1957** [comment]
As there was no activity at this adapter since app 2 years and you stated that you do not plan to further develop this adapter (https://github.com/ioBroker/ioBroker.repositories/pull/886#issuecomment-1397498037) I will close here.

Please feel free to open a new PR at any time. I will do a ne review whenever requested by you.

THANKS for working with ioBroker and maintaining other adapter(s)

**Pull request closed without merging**
