### PR TITLE
update upnp to v1.0.16

### PR DESCRIPTION
**Pull request by Jey-Cee**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.upnp](https://github.com/iobroker-community-adapters/ioBroker.upnp)
[Downloads](https://www.npmjs.com/package/iobroker.upnp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.upnp/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.upnp) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2016-2020 Jey Cee <jey-cee@live.com>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.upnp/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2016-2020 Jey Cee <jey-cee@live.com>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.upnp](https://github.com/iobroker-community-adapters/ioBroker.upnp)
[Downloads](https://www.npmjs.com/package/iobroker.upnp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.upnp/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
