### PR TITLE
add hyperion_NG adapter as lighting

### PR DESCRIPTION
**Pull request by felixganzer**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)

### [ioBroker.hyperion_ng](https://github.com/felixganzer/ioBroker.hyperion_ng)
[Downloads](https://www.npmjs.com/package/iobroker.hyperion_ng) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.hyperion_ng/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.1.9
- [ ] :eyes: [W400] Cannot find "hyperion_ng" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@felixganzer Please add news :-)

**Comment by felixganzer** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)

### [ioBroker.hyperion_ng](https://github.com/felixganzer/ioBroker.hyperion_ng)
[Downloads](https://www.npmjs.com/package/iobroker.hyperion_ng) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.hyperion_ng/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "hyperion_ng" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hello,

sorry for the late review. Here the comments:
* Please fix the testing
* please remove all the "stuff inserted by an npm install" from the package.json. Check other adapters what should be in (basically kill all _* fields)
* please replace the image (see admin and readme)
* the socket initialized by your API class should be closed in unload before callback is called! ( I expect you never tried the adapter in compact mode, or ?!)

Please check and adjust these things. Thank you

**Comment by felixganzer** [comment]
"the socket initialized by your API class should be closed in unload before callback is called! ( I expect you never tried the adapter in compact mode, or ?!)"

Ich verstehe nicht ganz, was du mit diesem Punkt meinst. Ich schließe doch den Socket, bevor ich diesen wieder öffne.

Was ist der compact mode?

**Comment by Apollon77** [comment]
In "Unload" müssen ALLE Verbindungen, Timouts, Intervals - alles was im Adapter noch läuft - beendet werden. Heisst wenn "Unload" aufgerufen wird musst du das socket zum Gerät bitte beenden bevor du den callback in unload aufrufst. 

Ich denke auch ein check der  https://github.com/ioBroker/ioBroker.repositories#development-and-coding-best-practices gibt hier mehr Klarheit.

Compact-Mode: siehe https://github.com/ioBroker/ioBroker.js-controller#start-adapter-instances-in-compact-mode

Es gibt CLI Befehle um einen Adapter im compact mode laufen zu lassen.

**Comment by felixganzer** [comment]
alles erledigt

**Comment by Apollon77** [comment]
Hey,
maybe you want to catch errors like https://github.com/felixganzer/ioBroker.hyperion_ng/runs/1853302457#step:6:309 !? ;-) else the adapter crashes hard (best register an error event handler on the socket.

Additionally please check the roles (sorry did not saw thet in first review)... e.g. control.state is no state that is defined (see https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md)

Why you use timeouts here to set state values? https://github.com/felixganzer/ioBroker.hyperion_ng/blob/93e10a34a03c6a79c8930e93c1c77e693f7374f0/main.js#L822
These timeouts are not clearable by unload ...

**Comment by felixganzer** [comment]
I added the error handler for the socket connection error. I also change the state roles to a correct one.

I know the timeouts are not elegant. If I change the state of the hyperion instance, for example deactivate or activate it, it need a couple of time. So I have to wait to readout the new state. It did not exist any query status flag to use. For stability of the commununication I use a timeout of 200 ms.

**Comment by Apollon77** [comment]
If you really need some time then you should maybe make sure thatthe "unload callback" is called with a delay of at least those 200ms - or maybe 400. Or you increase the stopTimeout (see e.g. influxdb adapter) and then also make sure to delay the callback call, but make sure no other action sis started in this "graceful shutdown time"

**Comment by felixganzer** [comment]
I implemented the stopTimeout. Also i added an timer that will be set at every communicaiton delay. At the adapter unload this timer will be checked.

**Comment by Apollon77** [comment]
Hey,
sorry but with https://github.com/felixganzer/ioBroker.hyperion_ng/blob/master/main.js#L632-L637 the callback is called twice :-) maybe a return is missing? Additionally getCOmmunicationTimeout is a method!! there are brackets missing.

**Comment by felixganzer** [comment]
Sorry. It was late at this day. I fixed it.

**Comment by Apollon77** [comment]
Welcome in the repo!

**Pull request merged**
