### PR TITLE
Maint: Username changed and Bump Huum to 0.4.4

### PR DESCRIPTION
**Pull request by Chris-656**
- change of User name
- Bump huum to 0.4.4

### CODE REVIEW

**Comment by Apollon77** [comment]
Please also adjust in the "latest" file

**Comment by mcm1957** [comment]
@Chris-656 
I think the following changes should be checked too :

-) update latest repository (sources-dist.latest) (Apollon77 already mentioned)
-) fitbit-fitness should get a new release (in my oppinion). 0.4.8 was released 2 months ago (according to github and npm registry). Github's io-package.json contains the new username but still release 0.4.8. Repos list version 0.4.8 too. Please check whether something went wrong and a 0.4.9 should be released as 0.4.8 will still deliver the old package content.

**Comment by Chris-656** [comment]
> latest reposito

I am not sure where to find the latest file "sources-dist.latest"  rest is done

**Comment by mcm1957** [comment]
> > latest reposito
> 
> I am not sure where to find the latest file "sources-dist.latest" ; rest is done

Sorry, my fault. should be .json of course.

**Pull request merged**
