### PR TITLE
update iogo to 0.5.6

### PR DESCRIPTION
**Pull request by nisiode**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!!

**Comment by nisiode** [comment]
What do you mean exactly? Who should check something?

**Comment by Apollon77** [comment]
(it is for an automated checker) :-)

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.iogo](https://github.com/nisiode/ioBroker.iogo)
[Downloads](https://www.npmjs.com/package/iobroker.iogo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iogo/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js, but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.iogo](https://github.com/nisiode/ioBroker.iogo)
[Downloads](https://www.npmjs.com/package/iobroker.iogo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iogo/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js, but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.iogo](https://github.com/nisiode/ioBroker.iogo)
[Downloads](https://www.npmjs.com/package/iobroker.iogo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iogo/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js, but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by nisiode** [comment]
> (it is for an automated checker) :-)

nice feature

but PR is still not merged... anything else missing?

**Comment by Apollon77** [comment]
saw that??

    👀 [W505] setTimeout found in "main.js, but no clearTimeout detected

Can you please check? Else compact mode will break if timeouts are not cleared in on unload!

**Comment by nisiode** [comment]
yes, I saw that. But seems to me like a warning because the main message is "No errors found".

**Comment by Apollon77** [comment]
We will change that. Because compact mode is kind og required in the meantime this becomes an error

**Comment by nisiode** [comment]
RE-CHECK!

**Comment by nisiode** [comment]
> We will change that. Because compact mode is kind og required in the meantime this becomes an error

understood, makes sense

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.iogo](https://github.com/nisiode/ioBroker.iogo)
[Downloads](https://www.npmjs.com/package/iobroker.iogo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iogo/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
awesome!

**Comment by Apollon77** [comment]
Normally we wait till a number of users have tested a new version ... would make an exception this time :-))

**Pull request merged**
