### PR TITLE
Added zoe2

### PR DESCRIPTION
**Pull request by fungus75**
Renault ZOE Adapter using the Renault API that is active since 2019 (API V2)

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [blob](https://github.com/ioBroker.zoe2/blob)
[Downloads](https://www.npmjs.com/package/blob) 
[NPM](https://nodei.co/npm/blob/)

- [ ] :heavy_exclamation_mark: 404

### [ioBroker.zoe2](https://github.com/fungus75/ioBroker.zoe2)
[Downloads](https://www.npmjs.com/package/iobroker.zoe2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.zoe2/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "zoe2" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected
- [ ] :eyes: [W801] .npmignore not found
- [ ] :eyes: [W901] .gitignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@fungus75 Please check the comments from the automatic checker ... Please also have a read over the dev elopment best practices (in readme of this project) and you can also floy over the review checklist (own md file in this repo) ... that should help to prepare for the review. Please drop a line when done

**Comment by fungus75** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [blob](https://github.com/ioBroker.zoe2/blob)
[Downloads](https://www.npmjs.com/package/blob) 
[NPM](https://nodei.co/npm/blob/)

- [ ] :heavy_exclamation_mark: 404

### [ioBroker.zoe2](https://github.com/fungus75/ioBroker.zoe2)
[Downloads](https://www.npmjs.com/package/iobroker.zoe2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.zoe2/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "zoe2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by fungus75** [comment]
> @fungus75 Please check the comments from the automatic checker ... Please also have a read over the dev elopment best practices (in readme of this project) and you can also floy over the review checklist (own md file in this repo) ... that should help to prepare for the review. Please drop a line when done

Have done the adjustments and also made adapter "compact mode" compatible.
From my point of view, it is ready for the repo ;-)

**Comment by Apollon77** [comment]
I would have some feedback and change requests:
* Please store the password encrypted! See the development best practices about details ... when you require js-controller 3.0 (as dependency in io-package) and admin 4.0.10+ as "globalDependency" at least you just need to add some konfiguration and it is handled automatically
* you use adapter-core in your code (https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L6) but dfo not have it as depenendcy ... this will not work that way that good. also if you provide adapter-core 2.4.0 as dep please note that you then need to require js.controller 2.0.0+ in io-package.json at least
* please add all default values for the admin editable values (https://github.com/fungus75/ioBroker.zoe2/blob/master/admin/index_m.html#L117-L125) into io-package native section
* please add testing correctly (https://travis-ci.org/github/fungus75/ioBroker.zoe2/jobs/758750522#L416) - you need to add the relevant package.json "scripts" entries to execute the tests. ALso the "test" directly with the tests is missing, so nothing would be executed.
* you have not defined a state change handler. please remove https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L41
* tip: https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L69 (e.g.) alwys check that "response" is defined before accessing it. in timeout cases "error" mighly be falsy but response undefined.
* if your code is correctly structured and you use async/await in all places there should be NO reason for this code https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L157-L160 ... this is just in other adapters because they work unclean.
* here https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L193-L196 (and in feeled like 20 more places) you set a new timeout ... the ones from before is still running ... so terminate will be executed multiple times ... bad idea. if you have that better make sure to use meaningfiul timeouts for the requests you do. that whole structure (sorry to say that) is broken)
* also problematic becasue on unload you should clear ALL timeouts ... 
* role "data" is not defined. see https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L880 for allowed role values
* all object creations and state setting is "parallel". This should get many warnings in js-controller 3.2 (try it ... use that new version, delete instace, start new)

Please check the developer best practices in the readme of this repo and mybe check back with other developers in Telegram or Discord to get some hints on how to handle these things correctly.

Thank you for checking and adjusting this.

**Comment by Apollon77** [comment]
@fungus75 Can we support anyhow in fixing the mentioned things?

**Comment by fungus75** [comment]
Thanks, but currently is is only a lack of time.
I have some ideas which I want to do along with your hints, but have not enough time ;-)

**Comment by Apollon77** [comment]
@fungus75 Did you had time? Anything we can help with?

**Comment by fungus75** [comment]
> 
> 
> @fungus75 Did you had time? Anything we can help with?

Next week looks good. I'm going to adjust. Have some ideas... ;-)

**Comment by Apollon77** [comment]
cool, just poke for another review. Time should be better now

**Comment by fungus75** [comment]
> I would have some feedback and change requests:
> 
> * Please store the password encrypted! See the development best practices about details ... when you require js-controller 3.0 (as dependency in io-package) and admin 4.0.10+ as "globalDependency" at least you just need to add some konfiguration and it is handled automatically
> * you use adapter-core in your code (https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L6) but dfo not have it as depenendcy ... this will not work that way that good. also if you provide adapter-core 2.4.0 as dep please note that you then need to require js.controller 2.0.0+ in io-package.json at least
> * please add all default values for the admin editable values (https://github.com/fungus75/ioBroker.zoe2/blob/master/admin/index_m.html#L117-L125) into io-package native section
> * please add testing correctly (https://travis-ci.org/github/fungus75/ioBroker.zoe2/jobs/758750522#L416) - you need to add the relevant package.json "scripts" entries to execute the tests. ALso the "test" directly with the tests is missing, so nothing would be executed.
> * you have not defined a state change handler. please remove https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L41
> * tip: https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L69 (e.g.) alwys check that "response" is defined before accessing it. in timeout cases "error" mighly be falsy but response undefined.
> * if your code is correctly structured and you use async/await in all places there should be NO reason for this code https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L157-L160 ... this is just in other adapters because they work unclean.
> * here https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L193-L196 (and in feeled like 20 more places) you set a new timeout ... the ones from before is still running ... so terminate will be executed multiple times ... bad idea. if you have that better make sure to use meaningfiul timeouts for the requests you do. that whole structure (sorry to say that) is broken)
> * also problematic becasue on unload you should clear ALL timeouts ...
> * role "data" is not defined. see https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L880 for allowed role values
> * all object creations and state setting is "parallel". This should get many warnings in js-controller 3.2 (try it ... use that new version, delete instace, start new)
> 
> Please check the developer best practices in the readme of this repo and mybe check back with other developers in Telegram or Discord to get some hints on how to handle these things correctly.
> 
> Thank you for checking and adjusting this.

Hi Appollon77,
I've done most of your suggestions. But I do not have any clue how to do that password-encryption-stuff.
Can you help me in that issue (or give me a documentation what to do,...)

Thanks a lot

**Comment by fungus75** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [blob](https://github.com/ioBroker.zoe2/blob)
[Downloads](https://www.npmjs.com/package/blob) 
[NPM](https://nodei.co/npm/blob/)

- [ ] :heavy_exclamation_mark: 404

### [ioBroker.zoe2](https://github.com/fungus75/ioBroker.zoe2)
[Downloads](https://www.npmjs.com/package/iobroker.zoe2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.zoe2/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "zoe2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
I checked again and added it.

One note:
* https://github.com/fungus75/ioBroker.zoe2/blob/master/main.js#L80 ... in timeout cases also "response" might be "null" or "undefined" ... so better check before accessing it
* * you do not validate that the response body is a JSON but always "parse" the response ... this will crash if they would return an error page or such ... better make a try/catch around the JSON-parse calls

**Pull request merged**
