### PR TITLE
Update js-controller to 6.0.9 and javascript to 8.7.6

### PR DESCRIPTION
**Pull request by foxriver76**
Just a prep PR we should wait around a week up from here.

### CODE REVIEW

**Comment by Apollon77** [comment]
How we make suer that javascript 8.7.1 is there too if needed for custom packages?

**Comment by foxriver76** [comment]
> How we make suer that javascript 8.7.1 is there too if needed for custom packages?

from TG:

8.7.1 because of the issue with typescript types yes, so far we have always said with controller update please do all other updates before. otherwise it just does the same as before... with versions that can't do it yet and with the intermediate versions everything works except typescript types...

**Comment by mcm1957** [comment]
note: https://github.com/ioBroker/ioBroker.javascript/issues/1645

**Comment by foxriver76** [comment]
ready to merge from my side @Apollon77 @mcm1957

**Comment by Apollon77** [comment]
kk, please do not forget the tag npm updates

**Comment by foxriver76** [comment]
> kk, please do not forget the tag npm updates

Isn’t this now done by CI? @mcm1957

**Comment by mcm1957** [comment]
> > kk, please do not forget the tag npm updates
> 
> Isn’t this now done by CI? @mcm1957

Yes should be done by a workflow

**Comment by mcm1957** [comment]
I do not see any reason to wait longer except that maybe we could wait one more day so that new js-controller gets available at 2.8. As on 1.8. Dependabot will send some mails and therevis a small Chance to not see urgent notifications at Mailbox at 1.x of month.

**Comment by mcm1957** [comment]
Please let me know if I should release today or tomorrow or feel free to merge yourself

**Pull request merged**
