### PR TITLE
Add vis-2-widgets-ovarious to latest

### PR DESCRIPTION
**Pull request by mcm1957**
@oweitman 

follow up for https://github.com/ioBroker/ioBroker.repositories/pull/3859

### CODE REVIEW

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

**Comment by mcm1957** [comment]
reminder 4.8.2024

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by oweitman** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by oweitman** [comment]
What is
Consider adding plugin "@alcalzone/release-script-plugin-manual-review".
On npm is no readme and the github link leads to 404

**Comment by mcm1957** [comment]
https://github.com/AlCalzone/release-script#plugins

manual-review plugin pauses release creation after files have been prepared and before they are committed. This is a good solution to review text published at news section of io-package.json and to simply correkt (i.e. german) nonsense before committing and publishing. Simply open io-package.json while script is pausing and read and ev. correkt news text. After saving the releasescript can / will continue as normal. If preferred you can also abort at this point and revert allc changes using git. 

We discussed this at dev-meeting ans decided to add the plugin per default - hence it is suggested by checker too.

Of course this is no blocking point for any release and it's you decision to igniore this warning.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Pull request merged**
