### PR TITLE
add tapo

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
would be category iot-systems be better here?

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tapo](https://github.com/TA2k/ioBroker.tapo)
[Downloads](https://www.npmjs.com/package/iobroker.tapo) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.tapo/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "tapo" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
I think type iot-systems would match better. Please change it in Adapter and PR. Thank you

**Comment by TA2k** [comment]
Fixed

**Pull request merged**
