### PR TITLE
Add adapter sun2000 to latest

### PR DESCRIPTION
**Pull request by bolliy**
I think that my additional adapter for Sun2000 is justified. Because it can process up to 5 inverters at the same time.

br stephan

### CODE REVIEW

**Comment by bolliy** [comment]
RE-CHECK!

**Comment by bolliy** [comment]
Forum Tester: https://forum.iobroker.net/topic/71768/test-adapter-sun2000-v0-1-x-huawei-wechselrichter

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

You will find the results of the review and evntually issues / suggestings as a communt to this PR. So please keep this PR watched. 

If you have any urgent questions feel free to ask.

mcm1957

**Comment by mcm1957** [comment]
reminder 01.02.2024

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] info states

  Why do you duplicate config information into ion.xxx states? This is at least unusal. Consider this as a remark, I do not consider it blocking,

- [ ] unused onStateChange handler

  You configred an onStateChange handler but it looks like this handler does not do any important tasks. Please remove the handler if the adapter does not react on state changes.

  
Thanks for reading and evaluating this suggestions.
McM1957


reminder 12.2.2024

**Comment by bolliy** [comment]
Thanks for checking my adapter!

"info state": I suspected that if the states were deleted manually, they would not be automatically recreated after a restart the adapter. 

„unused onStateChange handler“: I have remove the handler and push the changes to github.

Do I have to create a new adapter npm version so that the adapter can be included in the ioBroker repro?

**Comment by bolliy** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
> "info state": I suspected that if the states were deleted manually, they would not be automatically recreated after a restart the adapter.

My remark refers to the fact that those states exist at all. Most adapters do not duplicate their own configuration into states at all. So I suggested to remove those states. But as I already wrote this is not blocking.

> Do I have to create a new adapter npm version so that the adapter can be included in the ioBroker repro?
no, code change will go with next release anyway.

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Comment by bolliy** [comment]
Thank you Martin for your support. I am pleased about the quick response!

**Pull request merged**
