### PR TITLE
Updated eusec to 1.2.0 at stable

### PR DESCRIPTION
**Pull request by bropat**

### CODE REVIEW

**Comment by mcm1957** [comment]
1.2.0 created 04.11.2023

**Comment by mcm1957** [comment]
Why did you close the PR?
Was this done on error or on purpose?

**Comment by mcm1957** [comment]
ok - i see 1.2.1 is here ...

**Comment by bropat** [comment]
@mcm1957 

I have closed it because I found a bug and I have published a new version.

**Pull request closed without merging**
