### PR TITLE
Please add apcups.

### PR DESCRIPTION
**Pull request by XHunter74**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.apcups](https://github.com/xhunter74/ioBroker.apcups)
[Downloads](https://www.npmjs.com/package/iobroker.apcups) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.apcups/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/XHunter74/ioBroker.apcups. Expected: git+https://github.com/xhunter74/ioBroker.apcups.git
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "apcups" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by XHunter74** [comment]
.travis.yml existed on git before check. Actually, I don't know why the validator raised this error. Could you please help me to resolve this issue?

**Comment by XHunter74** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.apcups](https://github.com/xhunter74/ioBroker.apcups)
[Downloads](https://www.npmjs.com/package/iobroker.apcups) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.apcups/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "apcups" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hello @XHunter74,

here some review comments:
* Please translate the standard infos like desc and titleLang in io-package in all languages. You can use the ioBroker translation tool for it (see Readme of this project)
* When you specify the info.connection object in https://github.com/XHunter74/ioBroker.apcups/blob/master/io-package.json#L336 please also add the parent channel "info"
* Please also add macos and windows to the testing
* YOu need to preptect the "delay" in https://github.com/XHunter74/ioBroker.apcups/blob/master/main.js#L50 to make sure that not "Unload" was called in between. Starting with js.controller 4.0 we have a new adapter.delay that handles that and is "unload-safe" but that might be a bit too early :-)
* Please add some more information to the readme, maybe a setup link for apcups and such ... might help users :-)

Thank you for checking and adjusting

**Comment by Apollon77** [comment]
Ignore the travis error ... you have github actions, all fine

**Comment by XHunter74** [comment]
Seems I fixed all issues.
Thank you.

**Comment by XHunter74** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.apcups](https://github.com/xhunter74/ioBroker.apcups)
[Downloads](https://www.npmjs.com/package/iobroker.apcups) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.apcups/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "apcups" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@XHunter74 Thank you, Ihave just two last things:
* I think category "hardware" fits better (also because the "Nur "adapter is also in that category. Needs to be adjusted in io-package and in the repo PR
* Please remove the version number frtom the latest repo file .. the version here is automatically requested from npm twice a day

After that we are fine to add.

Thank you

**Comment by XHunter74** [comment]
Fixed all open issues.

**Comment by XHunter74** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.apcups](https://github.com/xhunter74/ioBroker.apcups)
[Downloads](https://www.npmjs.com/package/iobroker.apcups) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.apcups/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "apcups" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Thank you and welcome in the repo

**Pull request merged**
