### PR TITLE
Update hue-extended in stable

### PR DESCRIPTION
**Pull request by Zefau**
https://github.com/Zefau/ioBroker.hue-extended/issues/47

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hue-extended](https://github.com/Zefau/ioBroker.hue-extended)
[Downloads](https://www.npmjs.com/package/iobroker.hue-extended) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hue-extended/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/Zefau/ioBroker.hue-extended/blob/master/io-package.json). Must be removed.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Please remove that field and publish a new version!

**Comment by Zefau** [comment]
Fixed, please merge.

**Comment by Apollon77** [comment]
Please think about release a new version to npm with this fix and send this in for stable too

**Pull request merged**
