### PR TITLE
add ico to latest

### PR DESCRIPTION
**Pull request by Garfonso**
initial adapter to solve https://github.com/ioBroker/AdapterRequests/issues/447 (currently only official "cloud" way and very basic).

//Edit:
Forum thread: https://forum.iobroker.net/topic/46468/ico-pool-sensor-von-ondilo

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [io-package.json](https://github.com/main/io-package.json)
[Downloads](https://www.npmjs.com/package/io-package.json) 
[NPM](https://nodei.co/npm/io-package.json/)

- [ ] :heavy_exclamation_mark: 404


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi, some comments
* Please add aadmin=>4.0.9 to common.globalDependencies to use the passwoerd encryption 
* Please do not self-define new roles :-)) Happy to propose new ones, but please use official ones https://github.com/iobroker-community-adapters/ioBroker.ico-cloud/blob/main/src/main.ts#L160-L174
* when the timeout callback is called the timout is already cleared, no need for https://github.com/iobroker-community-adapters/ioBroker.ico-cloud/blob/main/src/main.ts#L281

Thanks for checking and adjusting

**Comment by Garfonso** [comment]
Thanks for the comments. I implemented all of your suggestions in v0.0.5.

**Comment by Apollon77** [comment]
All goood and welcome

BTW: YOu also might ewant to use "protectedNative"?

**Pull request merged**
