### PR TITLE
Added omnicomm-lls

### PR DESCRIPTION
**Pull request by instalator**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.omnicomm-lls](https://github.com/instalator/ioBroker.omnicomm-lls)
[Downloads](https://www.npmjs.com/package/iobroker.omnicomm-lls) 
[NPM](https://nodei.co/npm/iobroker.omnicomm-lls/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "omnicomm-lls" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,
one review comments:
* adapter-core 2.4.0 kind of requires js-controller 2+ ... please adjust the dependency ... we just discovered that effect today ... sorry

**Comment by DutchmanNL** [comment]
@instalator any update ?

**Comment by Apollon77** [comment]
@instalator any update?

**Comment by Apollon77** [comment]
@instalator COme on, only one line to change :-)

**Comment by instalator** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.omnicomm-lls](https://github.com/instalator/ioBroker.omnicomm-lls)
[Downloads](https://www.npmjs.com/package/iobroker.omnicomm-lls) 
[NPM](https://nodei.co/npm/iobroker.omnicomm-lls/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/instalator/ioBroker.omnicomm-lls/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/instalator/ioBroker.omnicomm-lls/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 instalator <vvvalt@mail.ru>" at the start of LICENSE
- [ ] :eyes: [W400] Cannot find "omnicomm-lls" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by instalator** [comment]
> @instalator COme on, only one line to change :-)

?

**Comment by instalator** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.omnicomm-lls](https://github.com/instalator/ioBroker.omnicomm-lls)
[Downloads](https://www.npmjs.com/package/iobroker.omnicomm-lls) 
[NPM](https://nodei.co/npm/iobroker.omnicomm-lls/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/instalator/ioBroker.omnicomm-lls/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/instalator/ioBroker.omnicomm-lls/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "omnicomm-lls" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@instalator it was the update in https://github.com/instalator/ioBroker.omnicomm-lls/blob/master/io-package.json#L67 :-)

Could you please also add the other tow fields to io.package common ? Details see https://github.com/ioBroker/ioBroker.repositories#connection-types

Thank you!

**Comment by instalator** [comment]
> @instalator it was the update in https://github.com/instalator/ioBroker.omnicomm-lls/blob/master/io-package.json#L67 :-)
> 
> Could you please also add the other tow fields to io.package common ? Details see https://github.com/ioBroker/ioBroker.repositories#connection-types
> 
> Thank you!

https://github.com/instalator/ioBroker.omnicomm-lls/commit/87f065ab32626cbcad80d7b3bb3f57911d35430b

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.omnicomm-lls](https://github.com/instalator/ioBroker.omnicomm-lls)
[Downloads](https://www.npmjs.com/package/iobroker.omnicomm-lls) 
[NPM](https://nodei.co/npm/iobroker.omnicomm-lls/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "omnicomm-lls" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
