### PR TITLE
add midea adapter

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.midea](https://github.com/TA2k/ioBroker.midea)
[Downloads](https://www.npmjs.com/package/iobroker.midea) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.midea/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.midea)!. Please execute in adapter directory: `npm owner add bluefox iobroker.midea`
- [ ] :eyes: [W400] Cannot find "midea" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.midea](https://github.com/TA2k/ioBroker.midea)
[Downloads](https://www.npmjs.com/package/iobroker.midea) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.midea/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.midea)!. Please execute in adapter directory: `npm owner add bluefox iobroker.midea`
- [ ] :eyes: [W400] Cannot find "midea" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.midea](https://github.com/TA2k/ioBroker.midea)
[Downloads](https://www.npmjs.com/package/iobroker.midea) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.midea/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "midea" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
"RE-CHECK!"

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.midea](https://github.com/TA2k/ioBroker.midea)
[Downloads](https://www.npmjs.com/package/iobroker.midea) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.midea/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "midea" in latest repository

### [ioBroker.homeconnect](https://github.com/dna909/ioBroker.homeconnect)
[Downloads](https://www.npmjs.com/package/iobroker.homeconnect) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.homeconnect/)

- [ ] :heavy_exclamation_mark: [E013] No author found in the [package.json](https://github.com/dna909/ioBroker.homeconnect/blob/master/package.json)
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/dna909/ioBroker.homeconnect) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2020 undefined" at the start of LICENSE
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.vaillant](https://github.com/TA2k/ioBroker.vaillant)
[Downloads](https://www.npmjs.com/package/iobroker.vaillant) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vaillant/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/TA2k/ioBroker.vaillant) are broken. Please fix.

### [ioBroker.vw-connect](https://github.com/TA2k/ioBroker.vw-connect)
[Downloads](https://www.npmjs.com/package/iobroker.vw-connect) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vw-connect/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected
- [ ] :eyes: [W901] .gitignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.homeconnect](https://github.com/dna909/ioBroker.homeconnect)
[Downloads](https://www.npmjs.com/package/iobroker.homeconnect) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.homeconnect/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/dna909/ioBroker.homeconnect) are broken. Please fix.

### [ioBroker.vaillant](https://github.com/TA2k/ioBroker.vaillant)
[Downloads](https://www.npmjs.com/package/iobroker.vaillant) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vaillant/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/TA2k/ioBroker.vaillant) are broken. Please fix.

### [ioBroker.vw-connect](https://github.com/TA2k/ioBroker.vw-connect)
[Downloads](https://www.npmjs.com/package/iobroker.vw-connect) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vw-connect/)

:thumbsup: No errors found
- [ ] :eyes: [W901] .gitignore not found

### [ioBroker.midea](https://github.com/TA2k/ioBroker.midea)
[Downloads](https://www.npmjs.com/package/iobroker.midea) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.midea/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "midea" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.homeconnect](https://github.com/dna909/ioBroker.homeconnect)
[Downloads](https://www.npmjs.com/package/iobroker.homeconnect) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.homeconnect/)

:thumbsup: No errors found

### [ioBroker.vaillant](https://github.com/TA2k/ioBroker.vaillant)
[Downloads](https://www.npmjs.com/package/iobroker.vaillant) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vaillant/)

:thumbsup: No errors found

### [ioBroker.vw-connect](https://github.com/TA2k/ioBroker.vw-connect)
[Downloads](https://www.npmjs.com/package/iobroker.vw-connect) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vw-connect/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected
- [ ] :eyes: [W901] .gitignore not found

### [ioBroker.midea](https://github.com/TA2k/ioBroker.midea)
[Downloads](https://www.npmjs.com/package/iobroker.midea) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.midea/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "midea" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.midea](https://github.com/TA2k/ioBroker.midea)
[Downloads](https://www.npmjs.com/package/iobroker.midea) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.midea/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "midea" in latest repository

### [ioBroker.homeconnect](https://github.com/dna909/ioBroker.homeconnect)
[Downloads](https://www.npmjs.com/package/iobroker.homeconnect) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.homeconnect/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/dna909/ioBroker.homeconnect) are broken. Please fix.

### [ioBroker.vaillant](https://github.com/TA2k/ioBroker.vaillant)
[Downloads](https://www.npmjs.com/package/iobroker.vaillant) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vaillant/)

:thumbsup: No errors found

### [ioBroker.vw-connect](https://github.com/TA2k/ioBroker.vw-connect)
[Downloads](https://www.npmjs.com/package/iobroker.vw-connect) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vw-connect/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
