### PR TITLE
Update anelhut from 1.0.13. to 1.0.15

### PR DESCRIPTION
**Pull request by dan1-de**
1.0.15
(dan1-de) Bugfix for new jscontroller 5: https://github.com/dan1-de/ioBroker.anelhut/issues/35
1.0.14
(dan1-de) Added new Logs messages for Relais Switch Command in Debug Mode

### CODE REVIEW

**Comment by mcm1957** [comment]
1.0.15 created 13.08.2023 (today)

New releases MUST be available at lastest for at least 5 days and have some users there. Exceptions accure if this is a very urgend hotfix.

**In addition you release has several issues whiuch must be fixed:**

- [ ] [E140] width and height of logo are not equal

- [ ] standard github testing is not functional or did not report success 

  Every release is required to pass at least minimum standard github testing. This is not the case here. Please update testing and retrigger a (hopefully) successful run.

  As node 14 is end of life and will no longer be supported by js-controller 5.x, consider removing node 14.x tests from matrix id still present.
  Tests for node 16 is mandatory unless you require node 18 and higher.
  Tests for node 18 is mandatory as node 18 is the recommended node version for ioBroker. Node 16 will be eol and deprected Q3/2023.
  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x],

**The following issues can be fixed easyly so I would aks to fix them imiidiatly too. If this is not appropiate, please fix until next release:**

 ❗ [E801] No repository about text found. Please go to "https://github.com/dan1-de/ioBroker.anelhut", press the settings button beside the about title and add the description.
 ❗ [E802] No topics found in the repository. Please go to "https://github.com/dan1-de/ioBroker.anelhut", press the settings button beside the about title and add some topics.
 ❗ [E605] No actual year found in copyright. Please add "Copyright (c) 2023 dan1-de [dan1-de@gmx.de](mailto:dan1-de@gmx.de)" at the end of [README.md](https://github.com/dan1-de/ioBroker.anelhut/blob/master/README.md)
 ❗ [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 dan1-de [dan1-de@gmx.de](mailto:dan1-de@gmx.de)" at the start of LICENSE

**I will check those errors adn come back if something must be fixed by you. Adaptions to repository entry will be done by me.**
 ❗ [E405] Icon must be in the following path: https://raw.githubusercontent.com/dan1-de/ioBroker.anelhut/main/
 ❗ [E407] Meta URL (latest) must be equal to https://raw.githubusercontent.com/dan1-de/ioBroker.anelhut/main/io-package.json
 ❗ [E426] Icon (stable) must be in the following path: https://raw.githubusercontent.com/dan1-de/ioBroker.anelhut/main/
 ❗ [E428] Meta URL (stable) must be equal to https://raw.githubusercontent.com/dan1-de/ioBroker.anelhut/main/io-package.json

**All other issues reported by adapter checker should be reviewed carefully and fixed for the next release if possible.**

If you have any concerns or need help, please let us know. Feel free to ping me or Apollon77 be mentionen us in a comment.

**Comment by dan1-de** [comment]
RE-CHECK!

**Comment by dan1-de** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
The path errors are most likely errors at existing repo entries. I will check and fix.

Admin5 ui is a warning and can be ignored. If possible chevk whether ui still works with admin 6

You may remove common.title but its not required. Its only a warning. Entry is now ignored by admin. Its replaced by common.titleLang which seems to exist already. TitleLang is multi lingual while title was english only.


I ll give some infos related to testing or provide a pr for you. I'm on mobile now, so please wait a little bit until i can use pc.

Rhanks for fixing all other issues.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
> The path errors are most likely errors at existing repo entries. I will check and fix.
> 
> Admin5 ui is a warning and can be ignored. If possible chevk whether ui still works with admin 6
> 
> You may remove common.title but its not required. Its only a warning. Entry is now ignored by admin. Its replaced by common.titleLang which seems to exist already. TitleLang is multi lingual while title was english only.
> 
> I ll give some infos related to testing or provide a pr for you. I'm on mobile now, so please wait a little bit until i can use pc.
> 
> Rhanks for fixing all other issues.

@dan1-de 

All issues reported by adapter checker are fixed now or can be ignored.

Please respond to PR for testing to finalize this too

**Comment by dan1-de** [comment]
RE-CHECK!

**Comment by dan1-de** [comment]
Hi @mcm1957 
thanks for your PR. Looks good now. Can we integrate the version 1.0.15 now into stable ?

**Pull request merged**
