### PR TITLE
Update sources-dist.json

### PR DESCRIPTION
**Pull request by TA2k**
Added nightscout Adapter
https://forum.iobroker.net/topic/23575/aufruf-adapter-für-nightscout

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Missing description

**Comment by TA2k** [comment]
I added a description in the readme. short description already in package and io-package
Nightscout (CGM in the Cloud) is an open source, DIY project that allows real time access to a CGM data via personal website, smartwatch viewers, or apps and widgets available for smartphones.

**Comment by Apollon77** [comment]
Some review comments from me too:
- you should remove .vscode directory from GitHub and set an gitignore
- you can use https://translator.iobroker.in/ to translate news and such in all relevant languages, please add that for the news in future :-)

**Comment by Apollon77** [comment]
Oh found one thin: you set info.connection state ... but the object is never defined. Normally it is done as instanceObject in io-package ... please check that!

**Comment by TA2k** [comment]
Thanks for the advices. But it strange thate connection is working without defined in io-package.
Maybe a short docu what the best practice for translation is at the moment because with this 5 options in the gulp script it is not easy to find the correct way

**Comment by ldittmar81** [comment]
I wrote a short description about Auto-Translation in German here: https://forum.iobroker.net/topic/19047/gulp-ist-kein-hexenwerk-auto-translation

**Pull request merged**
