### PR TITLE
add adapter iobroker.kostal-piko-ba to latest

### PR DESCRIPTION
**Pull request by hombach**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.kostal-piko-ba](https://github.com/hombach/ioBroker.kostal-piko-ba)
[Downloads](https://www.npmjs.com/package/iobroker.kostal-piko-ba) 
[NPM](https://nodei.co/npm/iobroker.kostal-piko-ba/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.2.8
- [ ] :eyes: [W400] Cannot find "kostal-piko-ba" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@hombach Can you please add the news?

**Comment by hombach** [comment]
added latest news

**Comment by hombach** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.kostal-piko-ba](https://github.com/hombach/ioBroker.kostal-piko-ba)
[Downloads](https://www.npmjs.com/package/iobroker.kostal-piko-ba) 
[NPM](https://nodei.co/npm/iobroker.kostal-piko-ba/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "kostal-piko-ba" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

some review comments:
* is the admin Tab really planned? The tab_m.html seems to be test stuff only ... please remove it also in io-package or implement it as planned
* The way you have defined the dependencies only works correct since js-controller 3. Best put the admin dependency in "globalDependencies"
* Is "supportCustoms": true, correct?! Yes there is a custom_m.html but do you really want to use it? Idon't thinl so. Please remove both
* Please do not use setObjectAsync, but setObjectNotExists, else in older js-controllers it could kill some set custom flags on the object
* You could move all those statically defined objects into io-package.json in instanceObjects then they are created automatically
* If you do not need state/object changes please also not implement onObject/StateChange methods
* As personal note: using intervals for "external communication" can lead to problems if there are network problems because then requests can pile up (especially when no timeouts were set) ... better is a timeout which is newly set at the end of the former request
*

**Comment by hombach** [comment]
Hello Apollon77, thanks for your comments - I will adapt according your remarks. Good idea about a timeout adapting last network results!

**Comment by Apollon77** [comment]
Just ping here when done.Thank you!

**Comment by hombach** [comment]
PING.....
all fixes DONE:

+ is the adminTab really planned ? The tab_m.html seems to be test stuff only
        ...please remove it also in io-package or implement it as planned => REMOVED adminTab
+ The way you have defined the dependencies only works correct since js - controller 3.
        Best put the admin dependency in "globalDependencies" => CHANGED to ">=3.0.0"
+ Is "supportCustoms": true, correct ? There is a custom_m.html but do you want to use it?
         => REMOVED BOTH
+ Please do not use setObjectAsync, but setObjectNotExists => MOVED TO io-package.json
+ You could move all those statically defined objects into io - package.json
         => MOVED TO io-package.json
+ If you do not need state/object changes please also not implement onXxxChange methods
         => METHODS REMOVED
+ using intervals for "external communication" can lead to problems if there are
        network problems because then requests can pile up (especially when no timeouts were set)
        ...better is a timeout which is newly set at the end of the former request
        => CHANGED to setTimeout - 10 min in case of trouble

**Comment by hombach** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.kostal-piko-ba](https://github.com/hombach/ioBroker.kostal-piko-ba)
[Downloads](https://www.npmjs.com/package/iobroker.kostal-piko-ba) 
[NPM](https://nodei.co/npm/iobroker.kostal-piko-ba/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "kostal-piko-ba" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by hombach** [comment]
PING ...  is there the necessity for any further action from my side?

**Comment by hombach** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.kostal-piko-ba](https://github.com/hombach/ioBroker.kostal-piko-ba)
[Downloads](https://www.npmjs.com/package/iobroker.kostal-piko-ba) 
[NPM](https://nodei.co/npm/iobroker.kostal-piko-ba/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/hombach/ioBroker.kostal-piko-ba", press the first "Edit" button you will find on the page and add the description.
- [ ] :eyes: [W400] Cannot find "kostal-piko-ba" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by hombach** [comment]
❗ [E801] No repository about text found.    ->   False positive!?!?

**Pull request closed without merging**
