### PR TITLE
new version OPi-adapter

### PR DESCRIPTION
**Pull request by PrinzEisenherz1**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
published is the date of first publish. Not the actual one.
I know it is a bit wired, but it is so.

**Comment by PrinzEisenherz1** [comment]
How can i see the actual date and time of publish? I ve published the new version with npm publish command. I that correct?

Johnny

**Comment by Apollon77** [comment]
on npm website: https://www.npmjs.com/package/iobroker.opi

**Comment by GermanBluefox** [comment]
The actual version date will be fetched automatically by repo script. You do not must provide it.

**Comment by PrinzEisenherz1** [comment]
ok, thanks for the Info!

Johnny

**Pull request merged**
