### PR TITLE
Added OctoPrint 1.0.0

### PR DESCRIPTION
**Pull request by klein0r**

### CODE REVIEW

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.octoprint](https://github.com/klein0r/ioBroker.octoprint)
[Downloads](https://www.npmjs.com/package/iobroker.octoprint) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.octoprint/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.octoprint](https://github.com/klein0r/ioBroker.octoprint)
[Downloads](https://www.npmjs.com/package/iobroker.octoprint) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.octoprint/)

:thumbsup: No errors found

### [ioBroker.youtube](https://github.com/klein0r/ioBroker.youtube)
[Downloads](https://www.npmjs.com/package/iobroker.youtube) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.youtube/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@klein0r octoprint is not in latest Repo??? What???

**Comment by klein0r** [comment]
@Apollon77 ?!?!

https://github.com/ioBroker/ioBroker.repositories/blob/ab0cfb57a741f1310af3c00648b7b2bce45c471f/sources-dist.json#L1005-L1008

**Comment by Apollon77** [comment]
Everything good. We had an issue in the repo file. Fixed in the meantime.

**Pull request merged**
