### PR TITLE
Update fitbit-fitness to 0.5.0

### PR DESCRIPTION
**Pull request by Chris-656**
Please update my adapter ioBroker.fitbit-fitness to version 0.5.0.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
0.5.0 created 18.11.2023

**Comment by mcm1957** [comment]
@Chris-656 
Please confirm, that open issue https://github.com/Chris-656/ioBroker.fitbit-fitness/issues/13 is fixed with 0.5.0.
Stable release MUST work with js-controller 5

**Comment by Chris-656** [comment]
> @Chris-656 Please confirm, that open issue [Chris-656/ioBroker.fitbit-fitness#13](https://github.com/Chris-656/ioBroker.fitbit-fitness/issues/13) is fixed with 0.5.0. Stable release MUST work with js-controller 5
> 
> Plesase also react on [Chris-656/ioBroker.fitbit-fitness#11](https://github.com/Chris-656/ioBroker.fitbit-fitness/issues/11) and answer the questions asked there.

see [Issue](https://forum.iobroker.net/topic/68290/js-controller-5-0-x-jetzt-f%C3%BCr-alle-user-im-stable/86)

In my environment:
starting. Version 0.4.10 in /opt/iobroker/node_modules/iobroker.fitbit-fitness, node: v16.20.2, js-controller: 5.0.12
it works fine without any issues
regards Chris

**Comment by mcm1957** [comment]
0.5.0 created 18.11.2023
19 User (>10%)
OK

**Pull request merged**
