### PR TITLE
Update iobroker.easee

### PR DESCRIPTION
**Pull request by Newan**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.easee](https://github.com/Newan/ioBroker.easee)
[Downloads](https://www.npmjs.com/package/iobroker.easee) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.easee/)

:thumbsup: No errors found

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) 
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

:thumbsup: No errors found

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

:thumbsup: No errors found

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Morluktom <strassertom@gmx.de>" at the start of LICENSE

### [ioBroker.bluelink](https://github.com/Newan/ioBroker.bluelink)
[Downloads](https://www.npmjs.com/package/iobroker.bluelink) 
[NPM](https://nodei.co/npm/iobroker.bluelink/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "bluelink" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Newan** [comment]
what needs to be fixed?

**Comment by Apollon77** [comment]
@Newan 
Please also add some more infos on the adapter into the Readme. Thank you

* you might want to encrypt the "clientSescret" value?
* plesse add all languages fpr the io-package standard fields ... you can use the iobroker translation tool (see dev best practices here in repo readme)
* defining own "encrypt/decrypt" in https://github.com/Newan/ioBroker.easee/blob/master/admin/index_m.html#L23 can conflict with admin ones and lead to errors in admin javascript. best use own names or switch tp the auto encrypt/decrypt where you do not need to do that at all and only configure it (see dev best practices)
* please think about using info.connection instead "online" (or additionally) - then admin would show yellow status if not "online" ... justdefine needed objects in io-package and set that state
* please check if really that much states are indicators (only boolean should be indicators :-) see https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md
* makes it really sense to do all these setObjectNotExists on every data update? Normally done only once on beginning :-)

Please check and adjust. Thank you

**Comment by Apollon77** [comment]
@Apollon77 bluelink reviewed and ok!! see https://github.com/ioBroker/ioBroker.repositories/pull/1204

**Comment by Apollon77** [comment]
@Newan any news here?

**Comment by Newan** [comment]
> @Newan any news here?

Sorry a little under time pressure.
I rebuild this and get back to you, please give me some more time

**Comment by Newan** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/sbormann/ioBroker.alias-manager/blob/master/io-package.json). Must be removed.
- [ ] :heavy_exclamation_mark: [E506] Word "Adopt common.custom (some datapoints have custom configurations for adapters like History, SQL or iQontrol, which are stored in common.custom)" is not translated to german in [admin/words.js](https://github.com/sbormann/ioBroker.alias-manager/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/sbormann/ioBroker.alias-manager) are broken. Please fix.

### [ioBroker.easee](https://github.com/Newan/ioBroker.easee)
[Downloads](https://www.npmjs.com/package/iobroker.easee) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.easee/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

:thumbsup: No errors found

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Morluktom <strassertom@gmx.de>" at the start of LICENSE

### [ioBroker.bluelink](https://github.com/Newan/ioBroker.bluelink)
[Downloads](https://www.npmjs.com/package/iobroker.bluelink) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.bluelink/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "bluelink" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Newan** [comment]
> @Newan
> Please also add some more infos on the adapter into the Readme. Thank you
> 
> * you might want to encrypt the "clientSescret" value?
> * plesse add all languages fpr the io-package standard fields ... you can use the iobroker translation tool (see dev best practices here in repo readme)
> * defining own "encrypt/decrypt" in https://github.com/Newan/ioBroker.easee/blob/master/admin/index_m.html#L23 can conflict with admin ones and lead to errors in admin javascript. best use own names or switch tp the auto encrypt/decrypt where you do not need to do that at all and only configure it (see dev best practices)
> * please think about using info.connection instead "online" (or additionally) - then admin would show yellow status if not "online" ... justdefine needed objects in io-package and set that state
> * please check if really that much states are indicators (only boolean should be indicators :-) see https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md
> * makes it really sense to do all these setObjectNotExists on every data update? Normally done only once on beginning :-)
> 
> Please check and adjust. Thank you

Hello, i fixed it all, i hope. The last adjust, setObjectNotExists -> this is only called if the wallbox ist not in the array and a new comes, so the create-Function is only called onced

**Comment by Newan** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bluelink](https://github.com/Newan/ioBroker.bluelink)
[Downloads](https://www.npmjs.com/package/iobroker.bluelink) 
[NPM](https://nodei.co/npm/iobroker.bluelink/)

- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "bluelink" in latest repository

### [ioBroker.easee](https://github.com/Newan/ioBroker.easee)
[Downloads](https://www.npmjs.com/package/iobroker.easee) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.easee/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/sbormann/ioBroker.alias-manager/blob/master/io-package.json). Must be removed.
- [ ] :heavy_exclamation_mark: [E506] Word "Adopt common.custom (some datapoints have custom configurations for adapters like History, SQL or iQontrol, which are stored in common.custom)" is not translated to german in [admin/words.js](https://github.com/sbormann/ioBroker.alias-manager/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/sbormann/ioBroker.alias-manager) are broken. Please fix.

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

:thumbsup: No errors found

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Morluktom <strassertom@gmx.de>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
