### PR TITLE
Add remeha-home to latest

### PR DESCRIPTION
**Pull request by simatec**
Please add my adapter ioBroker.remeha-home to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

reminder 17.9.2024

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@simatec 

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] Readme.md should contain a link to the manufacturer and/or device

  The README.md of any adapter related to device or m ultiple devices of a manufacturer should contain a link the manufacturers website and/or to a description of the device. This is to anable new users to easily check wether they associate the adapter with the correct device(s). (See https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository paragraph 4.)

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  data.roomThermostat.setPoint is writeable, so it must have role level.temperature.
  https://github.com/simatec/ioBroker.remeha-home/blob/1f411cd6bfe3d62596c4222a3c5478cbbeb9261e/main.js#L130

- [ ] adapt testing to supported node releases

  Tests for node 18 are mandatory as this is the recommended node version unless you require node 20 minimum. 
  Tests for node 20 are mandatory as this is the recommended node version. 
  Tests for node 21 are mandatory unless you already know incompatibilities which cannot be fixed immidiatly. In this case please create a issue stating the problem and fix as soon as possible.
  
  So the recommended testmatrix is [18.x, 20.x, 22.x] depending on engines requirments setting at package.json 

  Tests must be performed at all supported platforms (linux, windows, mac) unless special hardware or software restrictions prohibit this.
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

reminder 28.9.2024

**Comment by simatec** [comment]
all done...

**Comment by mcm1957** [comment]
> all done...

WAU - faster then light!
Thanks - I'm a little bit slower :-(

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Pull request merged**
