### PR TITLE
add frigate to sources-dist.json

### PR DESCRIPTION
**Pull request by Bettman66**

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.frigate](https://github.com/Bettman66/ioBroker.frigate)
[Downloads](https://www.npmjs.com/package/iobroker.frigate) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.frigate/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "frigate" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
link to adapter repo: https://github.com/Bettman66/ioBroker.frigate

**Comment by mcm1957** [comment]
In parts copied from #2252:

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- Translation of configuration is missing / incomplete

  ioBroker is an international software, So please use the multilanguage support provided per default. You added some translations into i18n files but also added infile translations for english and german only into jsonCOnfig.json.

  Translations must be done EITHER:
  a) by adding all translations into jsonConfig.json as an array containing ALL supported languages
  b) OR by suing i18n system. In this case you simpl write
  ``` "label":"My Url"```
into jsonConfig.json and add the line 
``` "My Url":"MyUrl"```
into en\translations.json assuming the english translation should be unchanged.
  Afterwards you run the translator using ```npm run translate``` assuming you have installed developer tools (adapter-dev, see https://github.com/ioBroker/adapter-dev)

  The recommended chose is b) as this will support weblate translation too and is easier to maintain then writing all translations into jsonCOnfig.json. 
  As ioBroker is international soiftware the config gui need all languages translated. 
  
Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by Bettman66** [comment]
i use
`npm run translate all`
but  jsonConfig.json was not translate.

**Comment by Bettman66** [comment]
ok, I got it.
the translation is not added in the jsonConfig.json, that was my understanding error.

**Comment by mcm1957** [comment]
Sorry for late reply. I m not at pc currently. 
The translations are only stored at lang/translations.jsin. english is the master.. 
Others are created from it.

At jsonconfig label entry contains only a string when using i18n,,no object. This dtring is used at key into translations.json. most devs usecthe englush text here but you can alsobise sime geberic text like lbkHelpText.

Please feel free to ask if any problems. I can recommend telegram chsnnels iobroker adoster development starers. https://t.me/+gsX-e8k4mLtmZjZk. Channel is synced with discord too. Normally yout geht answers there faster.

**Comment by mcm1957** [comment]
translations seem to be ok now.

**Pull request merged**
