### PR TITLE
time_switch_clock

### PR DESCRIPTION
**Pull request by XSDiVer**
first steps in javascript - maybe the adapter can be included in the beta repository.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.time_switch_clock](https://github.com/XSDiVer/ioBroker.time_switch_clock)
[Downloads](https://www.npmjs.com/package/iobroker.time_switch_clock) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.time_switch_clock/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "time_switch_clock" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Garfonso** [comment]
A short review.

1. Please sort in your adapter alphabetically. Currently, it is just added at the bottom of the JSON file.
2. you might want to [remove the deprecated unit test](https://github.com/ioBroker/create-adapter/blob/master/docs/updates/20220506_remove_unit_tests.md).
3. In io-package.json you define a local link `https://github.com/XSDiVer/ioBroker.time_switch_clock/blob/main/io-package.json#L146` -> but it seems to just link to the local vis edit. Is that correct? If so, then I think that should be removed. It should be sufficient that the vis-adapter contains this link. Distributing this link to other adapters will make it hard, if this link is once to be changed. Also, is it not possible to use this adapter with a different visualization adapter? (also, there is neither a dependency on vis nor on web...)
4. Please remove the `info.connection` state (and info channel) from your [io-package.json](https://github.com/XSDiVer/ioBroker.time_switch_clock/blob/main/io-package.json#L180) and your adapter-code. They are only meant to indicate a connection to an out-world server / device which is not what your adapter does.
5. You add an object `Setup.number_of_triggers`. Please also add `Setup` as `channel` or `folder` (similar to the info channel from above).
6. You don't process object changes, please remove the handler ([here](https://github.com/XSDiVer/ioBroker.time_switch_clock/blob/main/main.js#L104) and [here](https://github.com/XSDiVer/ioBroker.time_switch_clock/blob/main/main.js#L3234))
7. Similar to the `Setup`-channel there are neither channels / folders for `Weekday` and `trigger_1` to `trigger_6` created.
8. Why do you check the time [here](https://github.com/XSDiVer/ioBroker.time_switch_clock/blob/main/main.js#L906)? Just cancel the timeout (i.e. make sure that it does not run, for example in compact mode!).


Regarding your code... There is a LOT of code duplication. Feel free to ask in the starter-telegram group or somewhere else on how to reduce that... But, I guess this is optional for the time being.

Note to other reviewers: There is a widgets folder and contents seem sensible to me, but I have no experience with widgets.

**Comment by Apollon77** [comment]
@XSDiVer Ready for a re-review?

**Comment by Apollon77** [comment]
@XSDiVer Next time please do a post when ready ... emote reactions are not notified as email :-)

Here my review comments:
* please remove the localLink, as @Garfonso already told you because it is "just" open the vis ... This is not needed. Vis has its own link
* Your adapter contains a widget so you should add a common.restartAdapters['vis'] to io-package to make sure the new plugin gets seen by vis
* async here (example, maybe more such plavces!) not needed because no await is used https://github.com/XSDiVer/ioBroker.time_switch_clock/blob/main/main.js#L1118
* state changes should only ne processed as commands when ack-flag is set to false ... Please add this check
* when using a *Async method you should also use "await "... OR remove the Async from the method name. Otherwise can end in crashes

I did not really checked all code because yes, much duplicated ... ;-)

Thank you for checking and adjusting

**Comment by Apollon77** [comment]
@XSDiVer Is there anything we can help with?

**Comment by XSDiVer** [comment]
> @XSDiVer Is there anything we can help with?

Hello Apollon, 

in the moment I have not the time to fix the Adapter, but I tink in the near future I will go forward.

If anyone wants to remove the code duplcations or is interessted to develop the Adapter together with me,
feel free to contact me :o)

If I need some help (and I am sure I need) I contact you in our Telegram Channel 👍

**Comment by Apollon77** [comment]
the code duplications are no blocker for repo btw (they hjust make a proper review a bit harder)

**Comment by Apollon77** [comment]
Happy new year,any update?

**Comment by Apollon77** [comment]
@XSDiVer How we should continue?

**Comment by mcm1957** [comment]
Please remove node 14 from test-and-release.yml and (optionally) add node 20 to testing matrix.
Node 14 is no longer supported and tests will fail since 22.5.2023.

Thanks
McM1957

**Comment by XSDiVer** [comment]
> Please remove node 14 from test-and-release.yml and (optionally) add node 20 to testing matrix. Node 14 is no longer supported and tests will fail since 22.5.2023.
> 
> Thanks McM1957

Done...

**Comment by XSDiVer** [comment]
> @XSDiVer How we should continue?

If I had more time I would start the whole thing all over again. But it's a little tricky at the moment.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.time_switch_clock](https://github.com/XSDiVer/ioBroker.time_switch_clock)
[Downloads](https://www.npmjs.com/package/iobroker.time_switch_clock) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.time_switch_clock/)

- [ ] :heavy_exclamation_mark: [E518] "@alcalzone/release-script" is used, but ".releaseconfig.json" not found
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "time_switch_clock" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by XSDiVer** [comment]
> ## Automated adapter checker
> ### [ioBroker.time_switch_clock](https://github.com/XSDiVer/ioBroker.time_switch_clock)
> 
> [Downloads](https://www.npmjs.com/package/iobroker.time_switch_clock) Number of Installations (latest) [NPM](https://nodei.co/npm/iobroker.time_switch_clock/)
> 
>     * [ ]  ❗ [E518] "@alcalzone/release-script" is used, but ".releaseconfig.json" not found
> 
>     * [ ]  👀 [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
> 
>     * [ ]  👀 [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
> 
>     * [ ]  👀 [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
> 
>     * [ ]  👀 [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
> 
>     * [ ]  👀 [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
> 
>     * [ ]  👀 [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
> 
>     * [ ]  👀 [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
> 
>     * [ ]  👀 [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
> 
>     * [ ]  👀 [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
> 
>     * [ ]  👀 [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
> 
>     * [ ]  👀 [W400] Cannot find "time_switch_clock" in latest repository
> 
> 
> _Add comment "RE-CHECK!" to start check anew_

RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@XSDiVer 

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

After a long time I checked this old PR again. According to github you did some further work on the adapter -although the last release is from Aigust 2022. If you are still interested in listing the adapter at repos, I will try to get the re-review done within a few days after you gave feedback to the small number of current issues (see below).

This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] package.json must specifiy required nodejs version

  Please consioder adding en engines clause to package.json. Especially if you use adapter-core 3.x.x or newer nodegs 16 or newer must be reuested:
  ```
    "engines": {
    "node": ">= 16"
  },
  ```
  
- [ ] please verify that all dependencies are up to date

  Several plugins for alcalcone/releasescript are missing.
  
- [ ] log messages should be english

  All log messages (adapter.log.xxx /this.log.xxx) should be english. Some of your messages are german, please translate.
  If really desired, messages could use multiple languages - but this is strongly discoured as support might be complicated. Could you read an chinese error log? 

- [ ] onStateChange handler ignores ack flag 

  The adapter must honor the ack flag when processing onStateChange events resulting from users changing the adapters state. Whenever the onStateChange handler is called for an **own** state (a state owned by the processing instance of the adapter) it must ignore this event if the ack flags is set. Only stateChanges with ack==false are allowed to be processed.

  If the adapter subsribes to own states and wants to react whenever the adapter writes to its own state reacting on ack is ok.

  When processing foreign states which are output of another adapter  processing must only occure if the ack flag is true.

  REacting on special states (0_userdata_0, alias, javascript) ack might be ignored as prefered by you as many users do not understand ackusage.

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whnever a dedicated role exists.

- [ ] some labels seem to have no translation into all languages
  
  It seems that some labels are not translated into all supported languages, i.e. ...
  Please consider adding missing translations
  
- [ ] Is there any reason to not use i18n translation environment?
  
  I suggest to evaluate to use i18n translation environment and the iobroker/adapter-dev environment (https://github.com/ioBroker/adapter-dev#iobroker-adapter-dev). You could easyly add new strings to the english json and run ```npm run translate``` afterward. When using i18n environment activating iobrokers weblate translation system (see https://github.com/ioBrokerTranslator/doc) is trivial.  
  
- [ ] consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

  You already use this.setTimout, but not everywhere, i.e. https://github.com/XSDiVer/ioBroker.time_switch_clock/blob/445139370205031a3c2ca0d4d0b155fce8956799/main.js#L912

- [ ] all Timers / Intervalls must be canceled at onUnload

  All timers / intervallls must be cancelled at onUnlad. This is required as otherwise the timer could be fired when using compact mode after unloading the stopped adpater which will crah the compact process afterwards.

  see as an exaple https://github.com/XSDiVer/ioBroker.time_switch_clock/blob/445139370205031a3c2ca0d4d0b155fce8956799/main.js#L912  
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by XSDiVer** [comment]
Hello McM1957,

Thank you for your kind words and for taking the time to review the adapter. I truly appreciate your efforts and dedication to the ioBroker community.

I've carefully considered your suggestions and feedback. While I value the improvements you've highlighted, I regret to inform you that, due to current time constraints, I am unable to address these issues promptly.

I understand the importance of maintaining and updating the adapter, and I am grateful for your detailed insights. If you or @Apollon77 have any urgent concerns or specific questions that require immediate attention, please feel free to reach out to me, and I'll do my best to assist as time allows.

I want to express my gratitude for your understanding and patience. I will certainly plan to revisit and address these suggestions when my schedule permits.

Thank you once again for your support and valuable input.

Best regards,

XSDiVer

**Pull request closed without merging**
