### PR TITLE
Add drag-indicator to latest

### PR DESCRIPTION
**Pull request by BenAhrdt**
Please add my adapter ioBroker.drag-indicator to latest.

*This pull request was created by https://www.iobroker.dev 79ffd9b.*

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

here are my review comments:
* [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.drag-indicator"
* Please remove dev stuff from Readme and add some more information about the adapter there
* admin/i18n dir mising on GitHub but jsonCustom.json with i18n=true provided
* Formally state.val === null is a value value! (undefined is nit but null is) https://github.com/BenAhrdt/ioBroker.drag-indicator/blob/main/main.js#L324
* You use == in many places. Please be aware of the pot. side effects (and comparism to ===)
* Depending on the number of activated states please consider to use a gliobal "subscribeForeignStates(*) if it is > 100 indivual subscribed because of performance reasons.

Thank you for checking and adjusting

**Comment by Apollon77** [comment]
PS:

* custom_m.html seems unchanged from template ... please remove it ... and then add admin "globalDependency" to io-package to admin >= 5.0.0

**Comment by Apollon77** [comment]
PPS:
* Do you write back a change into the "foreign" namespace??? https://github.com/BenAhrdt/ioBroker.drag-indicator/blob/main/main.js#L353-L356 with ack=true. Please NEVER do that!! Only the adapter that owens this state should do that

**Comment by Apollon77** [comment]
Hi,

review feedback:
* It seems that Bluefox was still not added to NPM for the repository? [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.drag-indicator"

Besid ethis we seems to be ready

**Comment by Apollon77** [comment]
PS: BEside one thing ... the adapter type "enegery" does not make sense. Please use "misc-data" and adjust in io-package and in this PR

**Comment by Apollon77** [comment]
Please remove the info channel from io-package

**Comment by BenAhrdt** [comment]
Everything should be changed now.

**Comment by BenAhrdt** [comment]
Is something to do?

**Comment by Apollon77** [comment]
welcome in the repo

**Comment by Apollon77** [comment]
welcome in the repo

**Pull request merged**
