### PR TITLE
add adapter artnet-recorder to latest

### PR DESCRIPTION
**Pull request by Bannsaenger**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

:thumbsup: No errors found

### [ioBroker.x-touch](https://github.com/Bannsaenger/ioBroker.x-touch)
[Downloads](https://www.npmjs.com/package/iobroker.x-touch) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.x-touch/)

:thumbsup: No errors found

### [ioBroker.artnet-recorder](https://github.com/Bannsaenger/ioBroker.artnet-recorder)
[Downloads](https://www.npmjs.com/package/iobroker.artnet-recorder) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.artnet-recorder/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "artnet-recorder" in latest repository

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E151] common.connectionType type has an invalid type none
- [ ] :heavy_exclamation_mark: [E152] common.dataSource type has an invalid type none


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

review comments:

Must be fixed: 
* Please check your testing logs ... you should fix https://github.com/realhawker/ioBroker.netro/runs/4376378445?check_suite_focus=true#step:2:519 ... reason is that you used this.setInterval to set it but clearInterval (official variant) in https://github.com/realhawker/ioBroker.netro/blob/master/src/main.ts#L277 to clear :-)

Other comments:
* why async in https://github.com/realhawker/ioBroker.netro/blob/master/src/main.ts#L11 ?
* it would be more perfoermant to remember if all objects for a devices are initaolized instaed of always doing that "setObjectNotExists" in each data update loop https://github.com/realhawker/ioBroker.netro/blob/master/src/main.ts#L174
* you can remove https://github.com/realhawker/ioBroker.netro/blob/master/src/main.ts#L287 because you do not need it
* Why the update interval is fixed ad not configurable?

Thank you

**Comment by Apollon77** [comment]
Correct review commenst come soon

**Comment by Apollon77** [comment]
Hi, hjere are the review comments:

Must be fixed:
* The adapter is not having a tab and not having "customs" settings. Please remove https://github.com/Bannsaenger/ioBroker.artnet-recorder/blob/master/io-package.json#L67-L85 from io-package
* Why you change this? https://github.com/Bannsaenger/ioBroker.artnet-recorder/blob/master/main.js#L565 for compact mode the instance needs to be returned

Further comments:
* why you use that self thingy here? Makes no sense https://github.com/Bannsaenger/ioBroker.artnet-recorder/blob/master/main.js#L75
* makes it really sens to have "." as "unspecified local directory" as default working directory (https://github.com/Bannsaenger/ioBroker.artnet-recorder/blob/master/main.js#L120) ... if this would be in the node_modules directory then any adapter update would remove all content. I think it is better to use an instance specific directory like possibkle with https://github.com/ioBroker/adapter-core#getabsoluteinstancedatadir ... this can then also be included in backup or such ... for other cases it would make sense to require an absolute directory path

**Comment by ldittmar81** [comment]
@Bannsaenger Have the suggestions been implemented and can we look at the project again or do you need help?

**Comment by Bannsaenger** [comment]
Hi,
if have fixed the suggestions (i hope so)

- The Line 595 (returning the instance): I've added the use strict due to a error with jshint. I fixed it in jshint.rc and reverted the line to the original state.
- the self thingy is returned to this. I made this because i had errors with using this in the past. Now ist works with this.
- Thanks for the hint with the directory

**Comment by ldittmar81** [comment]
@Bannsaenger I got two little points....

https://github.com/Bannsaenger/ioBroker.artnet-recorder/blob/268aef6a67bb4c261788999989bcf57463bb8081/LICENSE#L3
and
https://github.com/Bannsaenger/ioBroker.artnet-recorder/blob/master/README.md

Copyright 2021-2022 ... Happy new year :-)

**Comment by Apollon77** [comment]
@Bannsaenger 
I had a look again and have one last thing  ...
* https://github.com/Bannsaenger/ioBroker.artnet-recorder/blob/master/io-package.json#L70 is still wrong. YOu do not have customs
AFter that we are done :-)

Pleas fix and updatenpm and poke again. Thank you

**Comment by Bannsaenger** [comment]
Ok, both commets fixed.
Thanks

**Comment by Apollon77** [comment]
Welcome!

**Pull request merged**
