### PR TITLE
Update sources-dist.json with adapter powerfox2

### PR DESCRIPTION
**Pull request by Ax-LED**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.powerfox2](https://github.com/Ax-LED/ioBroker.powerfox2)
[Downloads](https://www.npmjs.com/package/iobroker.powerfox2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.powerfox2/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/ax-led/ioBroker.powerfox2. Expected: git+https://github.com/Ax-LED/ioBroker.powerfox2.git
- [ ] :eyes: [W400] Cannot find "powerfox2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Ax-LED** [comment]
what do i have to do? And where do i have to do it?
Thanks in advance.
Regards
AxLED

**Comment by Ax-LED** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.powerfox2](https://github.com/Ax-LED/ioBroker.powerfox2)
[Downloads](https://www.npmjs.com/package/iobroker.powerfox2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.powerfox2/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/ax-led/ioBroker.powerfox2.git. Expected: git+https://github.com/Ax-LED/ioBroker.powerfox2.git
- [ ] :eyes: [W400] Cannot find "powerfox2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request closed without merging**
