### PR TITLE
Add espresense to latest

### PR DESCRIPTION
**Pull request by ticaki**

### CODE REVIEW

**Comment by mcm1957** [comment]
reminder 27.12.2023

**Comment by mcm1957** [comment]
reminder 24.12.2023

**Comment by mcm1957** [comment]
reminder 27.12.2023

**Comment by mcm1957** [comment]
reminder 24.12.2023

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter <name> <version>" to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, ist OK to continue using this topic too.

**Comment by ticaki** [comment]
Danke :)

**Pull request merged**
