### PR TITLE
hue-extended v1.3.8 to stable

### PR DESCRIPTION
**Pull request by Zefau**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hue-extended](https://github.com/Zefau/ioBroker.hue-extended)
[Downloads](https://www.npmjs.com/package/iobroker.hue-extended) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hue-extended/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 2.0.0-beta.1
- [ ] :heavy_exclamation_mark: [E506] Word "bridgeType" is not translated to russian in [admin/words.js](https://github.com/Zefau/ioBroker.hue-extended/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/Zefau/ioBroker.hue-extended", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/Zefau/ioBroker.hue-extended" and press `Manage topics`


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@Zefau could you please check the notes ... but Iwill merge

**Comment by Zefau** [comment]
Thanks for merging.

E145: this pr is for 1.3.8, not 2.0.0. Thus, no news so far
E506: I will add this in the next. That is indeed missing, but no pain.
E801 / E802: Wrong in my point of view. Both is defined in the repo.

**Pull request merged**
