### PR TITLE
Update openligadb to 1.3.4 

### PR DESCRIPTION
**Pull request by oweitman**

### CODE REVIEW

**Comment by mcm1957** [comment]
@oweitman 

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

Sorry to say, but the adapter currently does no longer pass standard tests. Fixing the following issues and creating a new release (as some fixes will not get into the release otherwise)  is required before updateing the release at stable repository:

The following issues reported by adapter checker must be fixed:
- [ ] :heavy_exclamation_mark: [E160] "admin" is not allowed in common.dependencies
- [ ] :heavy_exclamation_mark: [E606] Current adapter version 1.3.4 not found in [README.md](https://github.com/oweitman/ioBroker.openligadb/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2023 oweitman <oweitman@gmx.de>" at the end of [README.md](https://github.com/oweitman/ioBroker.openligadb/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 oweitman <oweitman@gmx.de>" at the start of LICENSE
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/oweitman/ioBroker.openligadb/blob/master/io-package.json)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn) (at least german and english is mandatory)

In addition the following issues must be fixed:
  
- [ ] adapt testing to supported node releases

  As node 12 and 14 are end of life and will no longer be supported by js-controller 5.x, remove node 14.x tests from matrix
  Tests for node 16 is mandatory unless you require node 18 and higher.
  Tests for node 18 is mandatory as many users already use node 18 and node 16 will be eol and deprected Q3/2023.
  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x],

- [ ] standard github tests are mandatory

  Its mandatore that standard github tests (wiorkflow test-and-release.yml) is present and all tests pass.

In addiotn the following suggestions apply:

- [ ] consider updating adapter dependencies
  
  Due to outdated / failint test environmenzt dependabot automerges have been stalled. As you will be creating a new release, check if its applicable to update dependencies together with this step.

Finally I would like to ask whther default logging level "debug" is really required. Most likely the default log level should be info. (But this is an info only and will not block update at stable repo)

**Comment by mcm1957** [comment]
@oweitman 

I've reviewed my comment posted yesterday. The number of issues to be fixed could look excessive. Its not my goal to block your valuable work and prohibit that users get improved code. So I want to clearify that only 2 issues MUST be fixed - all others are optional and it would be Ok to fix them until the next relase. As most of them do not require much work, I would recommend to fix them too now - but if ypour time does not allow, it would be OK to defer.


**The following issues reported by adapter checker must be fixed:**

- [ ] [E160] "admin" is not allowed in common.dependencies
  
  Admin dependency must be located at "globalDependencies". Fixing this will require a new release as updating the npm package is required as part of the fix.

- [ ] standard github tests are mandatory

  As node 12 and 14 are end of life and will no longer be supported by js-controller 5.x, remove node 12.x and 14.x tests from matrix
  Tests for node 16 is mandatory unless you require node 18 and higher.
  Tests for node 18 is mandatory as many users already use node 18 and node 16 will be eol and deprected Q3/2023.
  Please add node 20 tests unless you already know incompatibilities.

  Its mandatore that standard github tests (workflow test-and-release.yml) is present and all tests pass.


**The following issue should be really fixed if possible and your time allows**

- [ ] [E606] Current adapter version 1.3.4 not found in [README.md](https://github.com/oweitman/ioBroker.openligadb/blob/master/README.md)

  README.md must contain the changelog information so that users can see what has been changed. I will not consider this issue as blocking point, butt please add the info to README.md as soon as possible.


**The following issues are ok to be fixed with the next release** - but of course they might be fixed now too :-). Keeping them open definitly does not block an update.

- [ ] [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn) (at least german and english is mandatory)

- [ ] [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/oweitman/ioBroker.openligadb/blob/master/io-package.json) (cosmetic only!)
- [ ] [E605] No actual year found in copyright. Please add "Copyright (c) 2023 oweitman <oweitman@gmx.de>" at the end of [README.md](https://github.com/oweitman/ioBroker.openligadb/blob/master/README.md) (cosmetic only!)
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 oweitman <oweitman@gmx.de>" at the start of LICENSE (cosmetic only!)

In addition I would suggest the following tasks (but thats completly up to ypiu to decide whether you do it or not):

- [ ] consider updating adapter dependencies
  
  Due to outdated / failint test environmenzt dependabot automerges have been stalled. As you will be creating a new release, check if its applicable to update dependencies together with this step.

- [ ] I would like to ask whther default logging level "debug" is really required. Most likely the default log level should be info. (But this is an info only and will not block update at stable repo)


I hope you understand to goal to require standard tests for stable repository. Please respond if you have any concerns or questions or need any sort of help.

Thanks
mcm1957

**Comment by mcm1957** [comment]
@oweitman 
How shall we continue?
Do you have time to fix the issues listed above in th near future?
Or should we close her for now and you create a new PR in futire after fixing the issues.

**Comment by oweitman** [comment]
We close it and I open a new one

**Pull request closed without merging**
