### PR TITLE
add niu

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.niu](https://github.com/TA2k/ioBroker.niu)
[Downloads](https://www.npmjs.com/package/iobroker.niu) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.niu/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.niu)!. Please execute in adapter directory: `npm owner add bluefox iobroker.niu`
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W400] Cannot find "niu" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.niu](https://github.com/TA2k/ioBroker.niu)
[Downloads](https://www.npmjs.com/package/iobroker.niu) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.niu/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.niu)!. Please execute in adapter directory: `npm owner add bluefox iobroker.niu`
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W400] Cannot find "niu" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Welcome

**Pull request merged**
