### PR TITLE
Add open-epaper-link to latest

### PR DESCRIPTION
**Pull request by DutchmanNL**

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by DutchmanNL** [comment]
> @ticaki 
> 
> @DutchmanNL 
> 
> Did you notice the feedback? I do not see a comment thet the remarks have been processed and a re-review would be appropiate.

Hi, Urs seen it and Most of the already solves will Update the Review State as soon the last open item (onStateChange) is ready

**Comment by mcm1957** [comment]
Any news?
reminder 31.12.2023

**Comment by mcm1957** [comment]
@DutchmanNL 

Happy New Year !

How shall we continue?

**Please let me/us know if you encounter any problem and which timefram you expect to fix the mentionend issues.**

mcm1957

reminder 15.01.2024

**Comment by mcm1957** [comment]
@DutchmanNL

How shall we continue?
Are you working in this?
Is someone else working on this adapter?

Please let me/us know if you encounter any problem and which timefram you expect to fix the mentionend issues.

mcm1957

reminder 21.01.2024

**Comment by mcm1957** [comment]
How should we continue?
Do you need any further help?

**Please let me/us know (by adding a comment) when all issues noted earlier are processed by you and a new review seesm to be appropiate.**

**If there is no response until 28.2.2024 this PR might be closed.**

reminder 15.2.2024

**Comment by mcm1957** [comment]
How should we continue?
Do you need any further help?

**Please let me/us know (by adding a comment) when all issues noted earlier are processed by you and a new review seesm to be appropiate.**

**If there is no response until 28.2.2024 this PR might be closed.**

reminder 22.2.2024

**Comment by mcm1957** [comment]
How should we continue?
Do you need any further help?

Please let me/us know (by adding a comment) when all issues noted earlier are processed by you and a new review seesm to be appropiate.

**If there is no response until 28.2.2024 this PR will be closed.**

reminder 28.2.2024

**Pull request closed without merging**
