### PR TITLE
Update lgtv 1.1.10

### PR DESCRIPTION
**Pull request by SebastianSchultz**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lgtv](https://github.com/SebastianSchultz/ioBroker.lgtv)
[Downloads](https://www.npmjs.com/package/iobroker.lgtv) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lgtv/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/SebastianSchultz/ioBroker.lgtv/blob/master/io-package.json). Must be removed.


*Add comment "RE-CHECK!" to start check anew*

**Comment by SebastianSchultz** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lgtv](https://github.com/SebastianSchultz/ioBroker.lgtv)
[Downloads](https://www.npmjs.com/package/iobroker.lgtv) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lgtv/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
