### PR TITLE
push Nuki v. 1.4.1 to stable

### PR DESCRIPTION
**Pull request by smaragdschlange**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nuki](https://github.com/smaragdschlange/ioBroker.nuki)
[Downloads](https://www.npmjs.com/package/iobroker.nuki) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.nuki/)

- [ ] :heavy_exclamation_mark: [E152] common.dataSource type has an invalid type push,pull


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@smaragdschlange I merge now but please fix the comment!

**Pull request merged**
