### PR TITLE
new adapter minuaru

### PR DESCRIPTION
**Pull request by SVallant**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.minuaru](https://github.com/minukodu/ioBroker.minuaru)
[Downloads](https://www.npmjs.com/package/iobroker.minuaru) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.minuaru/)

:thumbsup: No errors found
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/minukodu/ioBroker.minuaru/blob/master/package.json) (1.0.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.minuaru) (0.9.7)
- [ ] :eyes: [W400] Cannot find "minuaru" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by SVallant** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.minuaru](https://github.com/minukodu/ioBroker.minuaru)
[Downloads](https://www.npmjs.com/package/iobroker.minuaru) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.minuaru/)

:thumbsup: No errors found
- [ ] :eyes: [W202] Version of [package.json](https://github.com/minukodu/ioBroker.minuaru/blob/master/package.json) (1.0.1) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.minuaru) (0.9.7)
- [ ] :eyes: [W400] Cannot find "minuaru" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by SVallant** [comment]
npm version is up to date
see https://github.com/ioBroker/ioBroker.repochecker/issues/80

**Comment by SVallant** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
Hi @SVallant,

my main review comment is "still" the topic about checking state.ack flag for own states that control things (like acknowledge alarms). Such controlling calls should be only executed when ack=false. To react on other external states is maybe different and is ok irrelevant of ack flag, but own states should respect this.

For unload code is fine, just make sure that all is done in 500ms ... or you need to set a higher unload delay in io-package ...

Please check the above thing and then we are done

Ingo

**Comment by SVallant** [comment]
Fixed now with Version V1.1.0

- ack=false is checked now for acknowledge alarms and delete alarm-table
- unload just resets the registered-states-array (and clears all timeouts) and cancels the check-timestamp-schedule, this should always be done in 500ms

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.minuaru](https://github.com/minukodu/ioBroker.minuaru)
[Downloads](https://www.npmjs.com/package/iobroker.minuaru) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.minuaru/)

:thumbsup: No errors found
- [ ] :eyes: [W202] Version of [package.json](https://github.com/minukodu/ioBroker.minuaru/blob/master/package.json) (1.1.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.minuaru) (1.0.1)
- [ ] :eyes: [W400] Cannot find "minuaru" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by SVallant** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.minuaru](https://github.com/minukodu/ioBroker.minuaru)
[Downloads](https://www.npmjs.com/package/iobroker.minuaru) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.minuaru/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "minuaru" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.minuaru](https://github.com/minukodu/ioBroker.minuaru)
[Downloads](https://www.npmjs.com/package/iobroker.minuaru) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.minuaru/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "minuaru" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.minuaru](https://github.com/minukodu/ioBroker.minuaru)
[Downloads](https://www.npmjs.com/package/iobroker.minuaru) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.minuaru/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "minuaru" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
@Apollon77 
Please do this re-review personally. The stateChange logic is to complex that I am sure to detect whether your remarks have been satified completly.

**Pull request merged**
