### PR TITLE
adding tesla wall connector gen 3 to latest

### PR DESCRIPTION
**Pull request by nobl**
Wish to add an adapter for the Tesla Wall Connector Gen 3 to latest repo.

### CODE REVIEW

**Comment by Apollon77** [comment]
@nobl The URLS in that PR mix main and master ... whats right?

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tesla-wallconnector3](https://github.com/nobl/ioBroker.tesla-wallconnector3)
[Downloads](https://www.npmjs.com/package/iobroker.tesla-wallconnector3) 
[NPM](https://nodei.co/npm/iobroker.tesla-wallconnector3/)

- [ ] :heavy_exclamation_mark: [E510] "/admin/i18n/uk/translations.json" not found, but admin support is declared
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "tesla-wallconnector3" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
The Checker warnings can be ignored

**Comment by nobl** [comment]
> @nobl The URLS in that PR mix main and master ... whats right?

No idea where this came from. Sorry - didn't double check what the npm script produced. (and I don't use "main")

For the Checker warnings: The online checker apparently differs (fails if you have uk in - so I removed it).

**Comment by nobl** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tesla-wallconnector3](https://github.com/nobl/ioBroker.tesla-wallconnector3)
[Downloads](https://www.npmjs.com/package/iobroker.tesla-wallconnector3) 
[NPM](https://nodei.co/npm/iobroker.tesla-wallconnector3/)

:thumbsup: No errors found
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "tesla-wallconnector3" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by nobl** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tesla-wallconnector3](https://github.com/nobl/ioBroker.tesla-wallconnector3)
[Downloads](https://www.npmjs.com/package/iobroker.tesla-wallconnector3) 
[NPM](https://nodei.co/npm/iobroker.tesla-wallconnector3/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "tesla-wallconnector3" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

here some review feedback:
* you show in your readme the way to install the adater using npm install ... this is no good idea and if - uncomplete :-) after such an install also an "iob upload adaptername" is needed. But ideally let users use Admin to install adapters independent from where.
* Please decide if you want to provide i18n dir with translatuon files OR have the translations "Inline in the jsonConfig field" :-) Your i18n files are dummy right now. Best practice would be to have all texts in i18n Files and not inline, but both is allowed
* https://github.com/nobl/ioBroker.tesla-wallconnector3/blob/main/main.js#L88 is executed async ... so you will have the language "somewhen later" ... is this making sense? WHy not use asny method and await .... then you have the data directly
* In general: You only need to declare methods "async" if you also want to use "await" in them ... if not there is no benefit
* You might want to add special handing for "null" or such (if this can happen). Because null is a valid value for all types, but returns "object" as type. Also make sure that type "Object" needs to be stored stringified
* When you query the object anyway would it then not make sense to only do "setObjectNotExist" only if the object do not exist? ;-) In fact this all is a lot of database traffic you do ... maybe also think about to cache the objects to not have that many db calls - because you do all of this for any received data ...
* Your approach with setTimeout has one "pitfall": If unload is called while currently an axios request is running your would set a new timeout after unload was finished. So you could remember the fact that unload was called by a variable and check before setting new timeout - or use adapter.setTimeout and js-controller >=4.0 as dep then it is unload-safe

Thank you for checking and adjusting the mentioned topics

**Comment by nobl** [comment]
> @nobl Happy new year, how we should proceed?

Sorry :(
Don't have ressources atm to see for that - but any pull-request is quite welcome :)

**Comment by Apollon77** [comment]
yes we overlapped ... if you like check my "PR" (with conflicts ... if you like get ideas from it and close  then). Tell me when re-review please as new post

**Comment by nobl** [comment]
@Apollon77 ok - I think we should be gtg from here :)

**Pull request merged**
