### PR TITLE
new adapter minuaru

### PR DESCRIPTION
**Pull request by SVallant**

### CODE REVIEW

**Comment by SVallant** [comment]
This is a new one for https://github.com/ioBroker/ioBroker.repositories/pull/1682

**Comment by Apollon77** [comment]
Hi @SVallant,

I checked it again:
* you still do not check state.ack flag in on State Change handler ... normally commands should only be executed with ack= false ... mainly relevant for "state changes of your own namespace" here. Or is there a reason to ignore the ack flag?

And a short tip: For paths it is better to use path.join() instead of building paths with e.g. "/" string additions :-)

Thank you for an info, rest looks good

**Comment by Apollon77** [comment]
@SVallant any news?

**Comment by SVallant** [comment]
not yet, we discovered some issues, so it is not stable enough

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.meross](https://github.com/Apollon77/ioBroker.meross)
[Downloads](https://www.npmjs.com/package/iobroker.meross) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.meross/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Apollon77/ioBroker.meross/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)

### [ioBroker.minuaru](https://github.com/minukodu/ioBroker.minuaru)
[Downloads](https://www.npmjs.com/package/iobroker.minuaru) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.minuaru/)

:thumbsup: No errors found
- [ ] :eyes: [W202] Version of [package.json](https://github.com/minukodu/ioBroker.minuaru/blob/master/package.json) (0.9.8) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.minuaru) (0.9.7)
- [ ] :eyes: [W400] Cannot find "minuaru" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@SVallant How we should continue? Close PR and you reopen when ready or whats best?

**Comment by SVallant** [comment]
Closing PR, further improvements of adapter, then i will make a new pr

**Pull request closed without merging**
