### PR TITLE
Update schoolfree 0.5.0

### PR DESCRIPTION
**Pull request by simatec**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.schoolfree](https://github.com/simatec/ioBroker.schoolfree)
[Downloads](https://www.npmjs.com/package/iobroker.schoolfree) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.schoolfree/)

- [ ] :heavy_exclamation_mark: [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html 
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@simatec Can you please have a look at the notes above?

**Comment by simatec** [comment]
@Apollon77 
I fixed it on Github for the next release. The next release is still under development.
https://github.com/simatec/ioBroker.schoolfree/commit/38eb9a95ff2893e9eb4cf68c8d86f12e55c1124d

Release 0.5.0 contains important changes because the API for calling the holidays has changed.

**Comment by simatec** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.schoolfree](https://github.com/simatec/ioBroker.schoolfree)
[Downloads](https://www.npmjs.com/package/iobroker.schoolfree) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.schoolfree/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
