### PR TITLE
 new version for DasWetter and vis-weather and minmax newly added 

### PR DESCRIPTION
**Pull request by rg-engineering**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please pull the repo firt and solve the conflicts!

**Comment by Apollon77** [comment]
I checked minmax and there are somethings left todo :-)

1.) Add Bluefox to npmas owner please (see repo requirements) ... and maybe also check for your older adapter too ... Thank you!
2.) On Travis I saw that only the package testing was executed but not the adapter testing .. that is strange and should be fixed before
3.) please add the license to io.package in common.license
4.) Some more documentation in README would be great

Thank you for checking and fixing these topics

**Comment by rg-engineering** [comment]
@Apollon77 can you please merge at least the part for DasWetter and vis-weather?
The other open issues for minmax I'll close soon.
BTW: bluefox is already maintainer of all of my iobroker npm -packages...

**Comment by Apollon77** [comment]
Ok,I have removed minmax. please do a separate PR for it!

**Pull request merged**
