### PR TITLE
add yahoo-stock-market adapter to stable

### PR DESCRIPTION
**Pull request by Newan**

### CODE REVIEW

**Comment by mcm1957** [comment]
json file is invalid -missing comma after type element.
Please fix.

**Comment by Newan** [comment]
fixed, sry

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Result from adapter checker:

[E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.yahoo-stock-market"
[E510] "/admin/i18n/uk/translations.json" or "admin/i18n/uk.json" not found, but admin support is declared

[W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W202] Version of package.json (0.0.4) doesn't match latest version on NPM (0.0.3)
[W504] setInterval found in "build/main.js", but no clearInterval detected

**Comment by mcm1957** [comment]
E201 must be fixed before adding to stable.

**Comment by Newan** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
C:\Users\Martin>npm owner list iobroker.yahoo-stock-market
bluefox <dogafox@gmail.com>
realnewan <info@newan.de>

**Comment by mcm1957** [comment]
release at 12.09.2022

OK

**Pull request merged**
