### PR TITLE
Update sources-dist-stable.json

### PR DESCRIPTION
**Pull request by Sickboy78**
sureflap
v1.1.7 has been tested vor several weeks and is stable
v1.1.8 fixes critical issue for changes in external API as of 01.06.2023

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sureflap](https://github.com/Sickboy78/ioBroker.sureflap)
[Downloads](https://www.npmjs.com/package/iobroker.sureflap) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sureflap/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2023 Sickboy78 <asmoday_666@gmx.de>" at the end of [README.md](https://github.com/Sickboy78/ioBroker.sureflap/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 Sickboy78 <asmoday_666@gmx.de>" at the start of LICENSE
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Sickboy78/ioBroker.sureflap/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/Sickboy78/ioBroker.sureflap/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
**OK** due to hotfix need

**Comment by Sickboy78** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sureflap](https://github.com/Sickboy78/ioBroker.sureflap)
[Downloads](https://www.npmjs.com/package/iobroker.sureflap) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sureflap/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by Sickboy78** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sureflap](https://github.com/Sickboy78/ioBroker.sureflap)
[Downloads](https://www.npmjs.com/package/iobroker.sureflap) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sureflap/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
