### PR TITLE
Added Zont adapter

### PR DESCRIPTION
**Pull request by kirovilya**

### CODE REVIEW

**Comment by Apollon77** [comment]
Thank you!
Please check that all requirements from https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-repository are fullfilled (especially enabled adapter testing using Travis-CI/Appveyor).

And lease give Bluefox access to npm , also as described on README.

**Comment by kirovilya** [comment]
I think I did it right. Look please

**Comment by Apollon77** [comment]
You have enabled Travis-ci/Appveyor with your own account? Then please do a commit to get the tests running ... or better ... get the needed testfiles. Please see the ioBroker Template  for files and what you need to add to package.json

**Comment by kirovilya** [comment]
It's ok now?

**Comment by Apollon77** [comment]
Not completely :-) Tests run but nothing is tested beside npm install stuff. The magic happens when you add

```
  "devDependencies": {
    "gulp": "^3.9.1",
    "mocha": "^4.1.0",
    "chai": "^4.1.2"
  },
"scripts": {
    "test": "node node_modules/mocha/bin/mocha --exit"
  }
```

to the package.json . then the tests should show a lot more

**Comment by kirovilya** [comment]
well, added.
need change version and re publish npm after that?

**Comment by Apollon77** [comment]
looks good now. in future tests will run on every commit so you can check at least basically that nothing broke by checking the tests before npm release or such. And you can add real testing for your lib if you want ...
No, no need to publish to npm. You may want to exclude the test-directory and the test config files from npm by adding them to .npmignore or such.

Bluefox added as npm owner too? Then we can accept your adapter!

**Comment by kirovilya** [comment]
Yes. Look https://www.npmjs.com/package/iobroker.zont
Bluefox in collaborators

**Comment by Apollon77** [comment]
Welcome Zont :-)

**Comment by kirovilya** [comment]
Thank you for help!

**Comment by kirovilya** [comment]
When will updated http://download.iobroker.net/sources-dist-latest.json ?

**Comment by Apollon77** [comment]
at latest end of this day, so should be in stable and latest tomorrow

**Comment by kirovilya** [comment]
ок. thank you

**Pull request merged**
