### PR TITLE
Added tr-064-community

### PR DESCRIPTION
**Pull request by ldittmar81**

### CODE REVIEW

**Comment by Apollon77** [comment]
but we also should remove the tr-064 one (original soef), or ?!

**Comment by Apollon77** [comment]
AHHHH STOP!! we can not do that! I still have no package on npm because still waiting for npmjs approval on the name

**Comment by ldittmar81** [comment]
:-D ... Ok... We can wait till it´s done. ;-)

**Comment by GermanBluefox** [comment]
Done?

**Comment by Apollon77** [comment]
No, I still wait for npmjs answers. There is a chance that we get the original package name ... but they answer really slow ;-(

**Comment by ldittmar81** [comment]
Cool... I think they must to ask soef, wait for the answer, ask again, wait agait... This may take a lot of time. 🤷🏻‍♂️

**Comment by Apollon77** [comment]
We will see.

**Comment by GermanBluefox** [comment]
OK. we can now proceed with real tr-064

**Comment by Apollon77** [comment]
Yes, I need to revert all the repo changes to get rid of -community and rename the repo ...

**Pull request closed without merging**
