### PR TITLE
Add enocean to latest

### PR DESCRIPTION
**Pull request by Jey-Cee**
Please add my adapter ioBroker.enocean to latest.

*This pull request was created by https://www.iobroker.dev 79ffd9b.*

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi, some review feedback:
* Please check for state.ack===false in onCHange ... i miss this in most places - or is there a reason for it? (in fact the check for the from namespace shoudl be changed into this (unless you know that your code would set ack=false himself and you not want to react on it ;-) 

Rest looks fine so far

**Comment by Apollon77** [comment]
@Jey-Cee Any status update?

**Comment by Jey-Cee** [comment]
Code is updated and there where no issues reported since 26 days.
So it is ok to publish.

**Comment by Apollon77** [comment]
Yes code looks good, but there was no new version released with these changes, so please do that. Thank you

**Comment by Jey-Cee** [comment]
grafik

**Pull request merged**
