### PR TITLE
ValloxMV Adapter 1.1.1

### PR DESCRIPTION
**Pull request by hacki11**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.valloxmv](https://github.com/hacki11/ioBroker.valloxmv)
[Downloads](https://www.npmjs.com/package/iobroker.valloxmv) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.valloxmv/)

- [ ] :heavy_exclamation_mark: [E506] Word "host" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "port" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "interval" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/hacki11/ioBroker.valloxmv", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/hacki11/ioBroker.valloxmv" and press `Manage topics`


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@hacki11 can you please check the comments for the future versions?

**Comment by hacki11** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.valloxmv](https://github.com/hacki11/ioBroker.valloxmv)
[Downloads](https://www.npmjs.com/package/iobroker.valloxmv) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.valloxmv/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/hacki11/ioBroker.valloxmv", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/hacki11/ioBroker.valloxmv" and press `Manage topics`


*Add comment "RE-CHECK!" to start check anew*

**Comment by hacki11** [comment]
Fixed all issues in my adapter and in the adapter checker:
https://github.com/ioBroker/ioBroker.repochecker/pull/34

**Comment by hacki11** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.valloxmv](https://github.com/hacki11/ioBroker.valloxmv)
[Downloads](https://www.npmjs.com/package/iobroker.valloxmv) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.valloxmv/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by hacki11** [comment]
Bump

**Comment by Apollon77** [comment]
thank you

**Pull request merged**
