### PR TITLE
Add lowpass-filter to latest

### PR DESCRIPTION
**Pull request by BenAhrdt**
Please add my adapter ioBroker.lowpass-filter to latest.

*This pull request was created by https://www.iobroker.dev 79ffd9b.*

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Ok, next round:
* Bluefox still missing on NPM. Please add
* Please translate the entries https://github.com/BenAhrdt/ioBroker.lowpass-filter/blob/main/io-package.json#L80-L102 ... you can use the iobroker translatuon tool for it, see readme of this repo
* Please change adapter type in io-püackage and this PR to "misc_data"
* without the connection state please also remove the info channel ... https://github.com/BenAhrdt/ioBroker.lowpass-filter/blob/main/io-package.json#L141-L148

Thank you

**Comment by BenAhrdt** [comment]
all changes are done

**Comment by BenAhrdt** [comment]
Everything should be changed now.
I can't do anything about the conflict with alexa2.

**Comment by BenAhrdt** [comment]
Is something to do?

**Comment by Apollon77** [comment]
welcome in the repo

**Pull request merged**
