### PR TITLE
add gigaset-elements 0.3.0 to stable

### PR DESCRIPTION
**Pull request by matthsc**
Forum thread: https://forum.iobroker.net/topic/51917/neuer-adapter-gigaset-elements

It has been in latest for way to long and should finally be moved to stable.

### CODE REVIEW

**Comment by matthsc** [comment]
RE-CHECK!

**Comment by matthsc** [comment]
I've updated the LICENSE year in git, is that enough or do we really need a new release?

The build/main.js checks seem a little to eager, those are build files and part of the npm package, but I did not commit them to git.

**Comment by mcm1957** [comment]
Correction the copyright year is pk. Needs NO new release.

**Comment by mcm1957** [comment]
@Apollon77 
Please review

Adapter is new to stable. Semms to have same env as #2379 but checker is satisfied here.

My possibilitues at mobile are too limited for analyses

**Pull request merged**
