### PR TITLE
Update webui to 0.18.4

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by mcm1957** [comment]
0.18.4 created 03.12.2023

**Comment by mcm1957** [comment]
This PR requests update to 0.18.4.

0.18.4 seesm to contain several know (and in meantime fixed) issues as release 0.18.5 up to 0.8.15 have been created containing only bug fixes.

So wouldn't it be appropiate to skip 0.18.4 and to release a newer version containging the bug fixes to stable?

**Comment by jogibear9988** [comment]
> This PR requests update to 0.18.4.
> 
> 0.18.4 seesm to contain several know (and in meantime fixed) issues as release 0.18.5 up to 0.8.15 have been created containing only bug fixes.
> 
> So wouldn't it be appropiate to skip 0.18.4 and to release a newer version containging the bug fixes to stable?

I'm constantly workin on this. So there will often be a newer Version, cause you only allow merge to stable if the package is a few weeks old.
So this Version is okay, and I'll create a new pull req for the next version at some time.

**Comment by mcm1957** [comment]
> i

**Pull request merged**
