### PR TITLE
add srm to latest

### PR DESCRIPTION
**Pull request by stephan1827**
Add adapter srm to latest

### CODE REVIEW

**Comment by mcm1957** [comment]
Pr ok please ignore other adapters

**Comment by ticaki** [comment]
As already explained in Telegram, a todo list with key points for the purpose of documentation.

- [ ] use Adapter.setTimeout()
- [ ] use FORBIDDEN_CHARS for not predefined data points
- [ ] only use roles from https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md
- [ ] add xs:12 to jsonConfig.json for cellphones

**Comment by stephan1827** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@stephan1827 

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```, i.e. by using the following snippet:
  ```
  function name2id(pName) {
      return (pName || '').replace(adapter.FORBIDDEN_CHARS, '_');
  }
  ```
  You handle FORBIDDEN_CHARS during creation of mesh states but noit at setting the state values - if I'm correct

  https://github.com/stephan1827/ioBroker.srm/blob/b1b514e8f4d608c68e6814a22b31653dccadbec7/main.js#L235
  https://github.com/stephan1827/ioBroker.srm/blob/b1b514e8f4d608c68e6814a22b31653dccadbec7/main.js#L239

- [ ] consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

  You already use this.setTimeout. At least at one place you use clearTimeout, please adapt to this.clearTimeout. Additionally set/clearIntervall should be replaced by this.set/clearInterval.

  see https://github.com/stephan1827/ioBroker.srm/blob/b1b514e8f4d608c68e6814a22b31653dccadbec7/main.js#L168
  https://github.com/stephan1827/ioBroker.srm/blob/b1b514e8f4d608c68e6814a22b31653dccadbec7/main.js#L184
  https://github.com/stephan1827/ioBroker.srm/blob/b1b514e8f4d608c68e6814a22b31653dccadbec7/main.js#L92
  https://github.com/stephan1827/ioBroker.srm/blob/b1b514e8f4d608c68e6814a22b31653dccadbec7/main.js#L188
  https://github.com/stephan1827/ioBroker.srm/blob/b1b514e8f4d608c68e6814a22b31653dccadbec7/main.js#L92
  likely more plöaces - please check

- [ ] code for scheduled adapters
  Your adapter is running as daemon (https://github.com/stephan1827/ioBroker.srm/blob/b1b514e8f4d608c68e6814a22b31653dccadbec7/io-package.json#L114) - which is OK. Why do you use some code dedicated to schedule mode?
  https://github.com/stephan1827/ioBroker.srm/blob/b1b514e8f4d608c68e6814a22b31653dccadbec7/main.js#L172

  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by stephan1827** [comment]
Fixed version is up

**Comment by mcm1957** [comment]
@stephan1827 

Some more feedback (non blocking) - eveluate for next release

- [ ] double replece is better than none :-)
   https://github.com/stephan1827/ioBroker.srm/blob/db321d7050c23ffadc7d5a6f5062ec8c99973747/main.js#L225

-[ ] cpu saving
   I don'nt know how much js jit compiler does an optimize, bute replacing once and using a variable could evntually save some cpu cycles
  https://github.com/stephan1827/ioBroker.srm/blob/db321d7050c23ffadc7d5a6f5062ec8c99973747/main.js#L225

**Comment by mcm1957** [comment]
@stephan1827 

This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, ist OK to continue using this topic too.

**Comment by stephan1827** [comment]
Thx for the detailed review and hints

**Pull request merged**
