### PR TITLE
Added Adapter "weatherflow_udp"

### PR DESCRIPTION
**Pull request by woessmich**
Dies ist ein Adapter um die Daten, die die Tempest Wetterstation von Weatherflow per UDP im lokalen Netzwerk sendet auszuwerten.
Der Thread zum Adapter ist https://forum.iobroker.net/topic/35007/adapter-weatherflow_udp.
Danke für einen Review.

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
@foxriver76 Thank you!

**Comment by foxriver76** [comment]
Hi @woessmich,

thank you for your PR. 

### Needs to be fixed:
- https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L762
please clear your timeout here, calling clearTimeout without a timer will do nothing, you have to assign your timer to a variable and pass it to the `clearTimeout` function
- Async methods do not support callbacks and besides this, this is a very bad practice https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L796
- https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L40 and https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L777 -> no states are subscribed and you are not doing anything relevant on the state change, please remove the handler
- It looks like your adapter is not providing a tab so please remove `adminTab` and other tab related fields https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/io-package.json#L78-L95

### Should be fixed:
- https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L46 the async is not necessary, you are not awaiting anything inside this method
- `==` comparisons shouldn't be used in most contexts, e.g. https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L201 it would be better to use `===` comparisons which also consider the types being equal
- You should get rid of using `var`, better use `let` and `const`
- Think about using the node engines field to avoid users struggling with incompatible node versions, see https://github.com/Apollon77/ioBroker.alexa2/blob/c48d5955fbe0e6e38ebac9b0910247db0f542b39/package.json#L31

### Tips: 
- For classical iterating, you can simply use `for x of []` instead of badly readable constructs like in https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L830
        while (i<stateparts.length-1) {
            stateBase=[stateBase,stateparts[i]].join(".");
            i++;
        }
```javascript
for (const statePart of stateparts) {
   stateBase = [stateBase, statePart].join(".");
}
```
However, in this special context, it would be more resource-saving to just use string concatenation
```javascript
   stateBase = `${stateBase}.${statePart}`
```

- Use your eslint. I mentioned to not use `var` in some comments above. This pattern is also defined in your eslint config https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/.eslintrc.json#L17 
So in general you should use eslint, which helps you to keep your code style consistent and avoid some errors, eslint can fix most of your errors automatically by running eslint on the configured files. In most IDEs, this can be done automatically on saving or via shortcut

Thank you and happy coding :computer:

**Comment by woessmich** [comment]
Hi @foxriver76 
Thank you for the thorough review, much appreciated.

### Needed fixes:

> https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L762
please clear your timeout here, calling clearTimeout without a timer will do nothing, you have to assign your timer to a variable and pass it to the clearTimeout function
>
OK, corrected

> Async methods do not support callbacks and besides this, this is a very bad practice https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L796
>
revised completely, hopefully OK now

> https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L40 and https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L777 -> no states are subscribed and you are not doing anything relevant on the state change, please remove the handler
>
OK, removed

> It looks like your adapter is not providing a tab so please remove adminTab and other tab related fields https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/io-package.json#L78-L95
>
OK, removed

### Recommended fixes

> https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L46 the async is not necessary, you are not awaiting anything inside this method
>
OK, fixed

> == comparisons shouldn't be used in most contexts, e.g. https://github.com/woessmich/ioBroker.weatherflow_udp/blob/004aaa96a8d83b76ba2e8687663a885a581b7088/main.js#L201 it would be better to use === comparisons which also consider the types being equal
>
OK, changed

> You should get rid of using var, better use let and const
Think about using the node engines field to avoid users struggling with incompatible node versions, see https://github.com/Apollon77/ioBroker.alexa2/blob/c48d5955fbe0e6e38ebac9b0910247db0f542b39/package.json#L31
>
That was a tricky one as I did (do) not really get the concept yet and eslint is also new to me but I am confident I got it

Thank you again for reviewing

**Comment by woessmich** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

:thumbsup: No errors found

### [ioBroker.weatherflow_udp](https://github.com/woessmich/ioBroker.weatherflow_udp)
[Downloads](https://www.npmjs.com/package/iobroker.weatherflow_udp) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.weatherflow_udp/)

- [ ] :heavy_exclamation_mark: [E014] [NPM](https://www.npmjs.com/package/iobroker.weatherflow_udp) information found in [package.json](https://github.com/woessmich/ioBroker.weatherflow_udp/blob/master/package.json). Please remove all attributes starting with "_"
- [ ] :eyes: [W400] Cannot find "weatherflow_udp" in latest repository
- [ ] :eyes: [W901] .gitignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by woessmich** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

:thumbsup: No errors found

### [ioBroker.weatherflow_udp](https://github.com/woessmich/ioBroker.weatherflow_udp)
[Downloads](https://www.npmjs.com/package/iobroker.weatherflow_udp) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.weatherflow_udp/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/woessmich/ioBroker.weatherflow_udp) are broken. Please fix.
- [ ] :eyes: [W400] Cannot find "weatherflow_udp" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by woessmich** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

:thumbsup: No errors found

### [ioBroker.weatherflow_udp](https://github.com/woessmich/ioBroker.weatherflow_udp)
[Downloads](https://www.npmjs.com/package/iobroker.weatherflow_udp) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.weatherflow_udp/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/woessmich/ioBroker.weatherflow_udp) are broken. Please fix.
- [ ] :eyes: [W400] Cannot find "weatherflow_udp" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by woessmich** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

:thumbsup: No errors found

### [ioBroker.weatherflow_udp](https://github.com/woessmich/ioBroker.weatherflow_udp)
[Downloads](https://www.npmjs.com/package/iobroker.weatherflow_udp) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.weatherflow_udp/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "weatherflow_udp" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
Looks good, in some cases, there are still `!=` comparisons. And I would tempt you to log errors in your `catch` blocks because inside your `try` blocks lots of different things happen and it will be better to know which errors occur to be able to fix them later.

**Comment by woessmich** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alarm](https://github.com/misanorot/ioBroker.alarm)
[Downloads](https://www.npmjs.com/package/iobroker.alarm) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alarm/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/misanorot/ioBroker.alarm/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/misanorot/ioBroker.alarm/blob/master/io-package.json)
- [ ] :eyes: [W113] Adapter should support compact mode

### [ioBroker.followthesun](https://github.com/HGlab01/ioBroker.followthesun)
[Downloads](https://www.npmjs.com/package/iobroker.followthesun) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.followthesun/)

:thumbsup: No errors found

### [ioBroker.ham](https://github.com/ioBroker/ioBroker.ham)
[Downloads](https://www.npmjs.com/package/iobroker.ham) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ham/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.ham/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.ham/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.iogo](https://github.com/nisiode/ioBroker.iogo)
[Downloads](https://www.npmjs.com/package/iobroker.iogo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iogo/)

:thumbsup: No errors found

### [ioBroker.linkeddevices](https://github.com/Scrounger/ioBroker.linkeddevices)
[Downloads](https://www.npmjs.com/package/iobroker.linkeddevices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.linkeddevices/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/Scrounger/ioBroker.linkeddevices/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/Scrounger/ioBroker.linkeddevices/blob/master/io-package.json)

### [ioBroker.mihome](https://github.com/ioBroker/ioBroker.mihome)
[Downloads](https://www.npmjs.com/package/iobroker.mihome) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mihome/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.mihome/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.mihome/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2017-2020 bluefox <dogafox@gmail.com>" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E814] file appveyor.yml found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore

### [ioBroker.tradfri](https://github.com/AlCalzone/ioBroker.tradfri)
[Downloads](https://www.npmjs.com/package/iobroker.tradfri) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.tradfri/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/AlCalzone/ioBroker.tradfri/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/AlCalzone/ioBroker.tradfri/blob/master/io-package.json)
- [ ] :eyes: [W801] .npmignore not found

### [ioBroker.zwave2](https://github.com/AlCalzone/ioBroker.zwave2)
[Downloads](https://www.npmjs.com/package/iobroker.zwave2) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.zwave2/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "build/main.js", but no clearTimeout detected

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

:thumbsup: No errors found

### [ioBroker.hass](https://github.com/ioBroker/ioBroker.hass)
[Downloads](https://www.npmjs.com/package/iobroker.hass) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hass/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.hass/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.hass/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E814] file appveyor.yml found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.weatherflow_udp](https://github.com/woessmich/ioBroker.weatherflow_udp)
[Downloads](https://www.npmjs.com/package/iobroker.weatherflow_udp) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.weatherflow_udp/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "weatherflow_udp" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by woessmich** [comment]
@foxriver76 
OK, Thank you again!
I once more checked for != and == and reworked the try blocks. Actually they were not really needed in that way.
What is my next step to do in order to get the adapter to the latest repository?

**Comment by woessmich** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alarm](https://github.com/misanorot/ioBroker.alarm)
[Downloads](https://www.npmjs.com/package/iobroker.alarm) 
[NPM](https://nodei.co/npm/iobroker.alarm/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/misanorot/ioBroker.alarm/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/misanorot/ioBroker.alarm/blob/master/io-package.json)
- [ ] :eyes: [W113] Adapter should support compact mode

### [ioBroker.followthesun](https://github.com/HGlab01/ioBroker.followthesun)
[Downloads](https://www.npmjs.com/package/iobroker.followthesun) 
[NPM](https://nodei.co/npm/iobroker.followthesun/)

:thumbsup: No errors found

### [ioBroker.ham](https://github.com/ioBroker/ioBroker.ham)
[Downloads](https://www.npmjs.com/package/iobroker.ham) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.ham/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.ham/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.ham/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.iogo](https://github.com/nisiode/ioBroker.iogo)
[Downloads](https://www.npmjs.com/package/iobroker.iogo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.iogo/)

:thumbsup: No errors found

### [ioBroker.linkeddevices](https://github.com/Scrounger/ioBroker.linkeddevices)
[Downloads](https://www.npmjs.com/package/iobroker.linkeddevices) 
[NPM](https://nodei.co/npm/iobroker.linkeddevices/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/Scrounger/ioBroker.linkeddevices/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/Scrounger/ioBroker.linkeddevices/blob/master/io-package.json)

### [ioBroker.mihome](https://github.com/ioBroker/ioBroker.mihome)
[Downloads](https://www.npmjs.com/package/iobroker.mihome) 
[NPM](https://nodei.co/npm/iobroker.mihome/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.mihome/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.mihome/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2017-2020 bluefox <dogafox@gmail.com>" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E814] file appveyor.yml found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore

### [ioBroker.tradfri](https://github.com/AlCalzone/ioBroker.tradfri)
[Downloads](https://www.npmjs.com/package/iobroker.tradfri) 
[NPM](https://nodei.co/npm/iobroker.tradfri/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/AlCalzone/ioBroker.tradfri/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/AlCalzone/ioBroker.tradfri/blob/master/io-package.json)
- [ ] :eyes: [W801] .npmignore not found

### [ioBroker.zwave2](https://github.com/AlCalzone/ioBroker.zwave2)
[Downloads](https://www.npmjs.com/package/iobroker.zwave2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.zwave2/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "build/main.js", but no clearTimeout detected

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

:thumbsup: No errors found

### [ioBroker.hass](https://github.com/ioBroker/ioBroker.hass)
[Downloads](https://www.npmjs.com/package/iobroker.hass) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hass/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.hass/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.hass/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E814] file appveyor.yml found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.weatherflow_udp](https://github.com/woessmich/ioBroker.weatherflow_udp)
[Downloads](https://www.npmjs.com/package/iobroker.weatherflow_udp) 
[NPM](https://nodei.co/npm/iobroker.weatherflow_udp/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "weatherflow_udp" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
