### PR TITLE
add tinymqttbroker to latest

### PR DESCRIPTION
**Pull request by HGlab01**
https://github.com/HGlab01/ioBroker.tinymqttbroker

image

### CODE REVIEW

**Comment by HGlab01** [comment]
E201 --> invited, see screenshot

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- [ ] errors reported by adapter checker must be fixed

  Especially error  ```[E201] Bluefox was not found in the collaborators on NPM!.``` must be fixed. If you just invited Bluefox its ignore to wait for his reaction. Please state that the invitation has been sent in this case.
  
- [ ] lower limit for mqttpo really desired?

  Do you really want to limit the mqtt port to be at least 1882 but not lower? Or did you want to specify a default value only? (remark is definitly non blocking)
  https://github.com/HGlab01/ioBroker.tinyMQTTbroker/blob/9e6cc4c5107e8306b5c0ca77d7d815270f295331/admin/jsonConfig.json#L5-L9

- [ ] unused onStateChange handler

  You configred an onStateChange handler but it looks like this handler does not do any important tasks. Please remove the handler if the adapter does not react on state changes.

  According to your README.md a working state change handling is required. Are you sure the correct code is committed into the repository?

FUTHER CHECKS SKIPPED UNTIL CODE STATE CONFIRMED.

Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by HGlab01** [comment]
Thanks for feedback!

**- [ ] errors reported by adapter checker must be fixed**
see screenshot; Invite was done - https://github.com/ioBroker/ioBroker.repositories/pull/2400#issue-1782413257


**- [ ] lower limit for mqttpo really desired**
standard ports are 1883, 1884, 1885 etc.  - therefore it is was defined on purpose


**- [ ] unused onStateChange handler: it is not registered in the constructor**   https://github.com/HGlab01/ioBroker.tinyMQTTbroker/blob/9e6cc4c5107e8306b5c0ca77d7d815270f295331/src/main.ts#L21
For sure we can discuss if it is goód practice to keep the handler altough it is not used; nevertheless it was on purpose

**Comment by mcm1957** [comment]
Ok, I read the lines within README.md wrong:
```
For publishing message I use on ioBroker state listening for any changes and pushing it to the broker. The state expects a JSON with 'topic' and 'message'.```

and was wondering why no code handling the state listen ing exits. 
Was my fault., the adpater does not listen on any state. And you are right there's no onStateStange subscription.

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- [ ] errors reported by adapter checker must be fixed

  Especially error  ```[E201] Bluefox was not found in the collaborators on NPM!.``` must be fixed. If you just invited Bluefox its ignore to wait for his reaction. Please state that the invitation has been sent in this case.

   I keep this only as a reminder until BlueFox has accepted the invite. No action required by you currently.
  
- [ ] some labels seem to have no translation into all languages (non blocking)
  
  It seems that some labels are not translated into all supported languages.
  All i18n/<lang>/translation.json seem to contain the default values only.
  Please consider adding the existing labels from jsonCOnfig.json into the neglish translation.json and run `npm translate`

  If you want to use local translation inside jsonCOnfig.json please set i18n attribute to false and tremove i18n file tree. This is only recommended if you have very littel text to translate and this will block translation  support using weblate.iobroker.net.
    
Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by HGlab01** [comment]
no it is nerd-clean 😂🤣

**Pull request merged**
