### PR TITLE
Update smartgarden to 2.0.1

### PR DESCRIPTION
**Pull request by jpgorganizer**
new stable version v2.0.1 for smartgarden adapter

### CODE REVIEW

**Comment by mcm1957** [comment]
This adapter currently does not meet standards. Standard GitHub based testing is mandatory.
I'll provide a PR with the required changes / additions. Please stand by.

**Comment by jpgorganizer** [comment]
RE-CHECK!

**Comment by jpgorganizer** [comment]
RE-CHECK!

**Comment by jpgorganizer** [comment]
RE-CHECK!

**Comment by jpgorganizer** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
I've provided a PR (https://github.com/jpgorganizer/ioBroker.smartgarden/pull/74) to add standard github based testing. Standard testing currently fails due to some unhandled exception at integration test. I've described details at PR.

As standard Tests must pass and fixing the unhandled exception requires a code change and a new revison, I will close here. Please open a new PR as soon as fixed release exists.

If you have any questions, feel free to ask - here or at ioBroker telegram development channels (Invites at https://www.iobroker.dev).

**Pull request closed without merging**
