### PR TITLE
Add ioBroker.tautulli to latest repo

### PR DESCRIPTION
**Pull request by Zefau**

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi, please check the repository needs. At least the point to add Bluefox as npm owner was missed, maybe more :-)

Futrther fast check results:
* some tables in your readme are broken
* the latest commits do not have running travis.ci tests?
* personal note: setnterval for "external communication" is dangerous because if there are timeouts or such the setInterval will start new connections when the time comes ... so you can DOS yourself. Maybe better us setTimeout and restart at the end of retrieval
* maybe also consider adding compact mode support (see issue) and discovery support if possible

**Comment by GermanBluefox** [comment]
https://adapter-check.iobroker.in/?q=https://github.com/Zefau/ioBroker.tautulli

**Comment by Apollon77** [comment]
Thank you and welcome tautulli :-)

**Comment by GermanBluefox** [comment]
No license found in io-package.json

**Comment by Apollon77** [comment]
Shit. Missed that one :-(

**Comment by Zefau** [comment]
Looks like licence information is missing in all my `io-package.json` (applies for nello and roomba as well). I will add the information.

**Comment by Apollon77** [comment]
Thank you

**Pull request merged**
