### PR TITLE
Added nmea to latest

### PR DESCRIPTION
**Pull request by GermanBluefox**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

You will find the results of the review and evntually issues / suggestings as a communt to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

mcm1957

**Comment by mcm1957** [comment]
For review remarks see
https://github.com/ioBroker/ioBroker.nmea/issues/14

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Pull request merged**
