### PR TITLE
AirConWithMe Adapter (neuer Versuch)

### PR DESCRIPTION
**Pull request by weggetor**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
Hi, here are my review comments:
* you created and also configured an own admin tab but with only dummy content. Please remove admin files and io-package config or implement the tab :-)
* what you do with the custom_m? I would assume also this is dummy only. So if you do not use it please remove it also there and from io-package
* maybe choose a better "non-potential-conflicting" variablename if you want to store data in the adapter object because in fact we culd use such a generic variablename in there anytime :-) https://github.com/weggetor/ioBroker.airconwithme/blob/main/src/main.ts#L108

Thank you for checking and adjusting my comments

**Comment by Apollon77** [comment]
PS: and please rebase the PR here, seems conflicting

**Comment by Apollon77** [comment]
@weggetor Do you need any support for the adjustments!?

**Comment by weggetor** [comment]
OK, I fixed the issues (had no knowledge about the admin tab! It's removed now) and updated the pull request. Hope everything works now !

**Comment by weggetor** [comment]
@Apollon77 Any news on this ?

**Comment by Apollon77** [comment]
will try to find time on weekend sorry

**Comment by weggetor** [comment]
@Apollon77 - Ping

**Comment by Apollon77** [comment]
I know ... Pong ;-)
I need to switch away from fixing another 10 adapters for js-controller 3.3 release to review it seems ;-)

**Comment by Apollon77** [comment]
WElcoem and sorry for the delay.

**Pull request merged**
