### PR TITLE
Update sources-dist-stable.json

### PR DESCRIPTION
**Pull request by SebastianSchultz**
lgtv v1.1.4

### CODE REVIEW

**Comment by GermanBluefox** [comment]
LGTM

**Comment by SebastianSchultz** [comment]
Hi Bluefox,

what do you mean with "LGTM" ???

**Comment by Apollon77** [comment]
Looks Good To Me :-)

**Comment by Apollon77** [comment]
Is the 1.1.4 an important bugfix? Because no user so far uses this version and normally we wait till stable till we see some installs ... exceptions are only important bugfixes or such

**Comment by SebastianSchultz** [comment]
No it's "only" an improvement in Performance and stability. Sorry :)

**Comment by Apollon77** [comment]
No need for sorry ... So if your are sure it does not break we can merge it ... or we wait some days for usrs to catch up in latest

**Comment by SebastianSchultz** [comment]
We still can wait :)

**Pull request merged**
