### PR TITLE
iqontrol 0.1.0 stable

### PR DESCRIPTION
**Pull request by sbormann**

### CODE REVIEW

**Comment by Apollon77** [comment]
when this version was published? it is not contained in the statistics so far

**Comment by sbormann** [comment]
Just before creating the pull request.

Von: Ingo Fischer <notifications@github.com>
Gesendet: Sonntag, 28. Juli 2019 00:13
An: ioBroker/ioBroker.repositories <ioBroker.repositories@noreply.github.com>
Cc: Sebastian Bormann <sebastian@bormann.net>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.repositories] iqontrol 0.1.0 stable (#455)


when this version was published? it is not contained in the statistics so far

**Comment by Apollon77** [comment]
Wer there chnages or just a new version number? Idea is normally to bring versions into stable after have them tested in latest :-)

**Comment by sbormann** [comment]
Just minor changes, small bug fixes.

Von: Ingo Fischer <notifications@github.com>
Gesendet: Sonntag, 28. Juli 2019 00:21
An: ioBroker/ioBroker.repositories <ioBroker.repositories@noreply.github.com>
Cc: Sebastian Bormann <sebastian@bormann.net>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.repositories] iqontrol 0.1.0 stable (#455)


Wer there chnages or just a new version number? Idea is normally to bring versions into stable after have them tested in latest :-)

**Comment by sbormann** [comment]
But we can wait a few days to wait for feedback.
Did not know how this is handled – but it makes sense what you say.

Von: Ingo Fischer <notifications@github.com>
Gesendet: Sonntag, 28. Juli 2019 00:21
An: ioBroker/ioBroker.repositories <ioBroker.repositories@noreply.github.com>
Cc: Sebastian Bormann <sebastian@bormann.net>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.repositories] iqontrol 0.1.0 stable (#455)


Wer there chnages or just a new version number? Idea is normally to bring versions into stable after have them tested in latest :-)

**Comment by Apollon77** [comment]
Ok, i Monitor the usage of 0.1.0 and accept it the next days. That you for your great work

**Comment by Apollon77** [comment]
15% is ok I think :-)

**Pull request merged**
