### PR TITLE
update deconz & added heytech

### PR DESCRIPTION
**Pull request by Jey-Cee**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please check https://adapter-check.iobroker.in/ for heytech!

**Comment by Apollon77** [comment]
Also see Travis from Repo:

Icon of adapter heytech: https://raw.githubusercontent.com/jey-cee/ioBroker.heytech/master/admin/hass-mqtt.png not getable

**Comment by Jey-Cee** [comment]
now looks better

**Comment by Apollon77** [comment]
Please check https://adapter-check.iobroker.in/ for heytech! ;-)

**Comment by Jey-Cee** [comment]
No probs found

**Comment by Apollon77** [comment]
?? [E019] Invalid repository URL: https://github.com/Jey-Cee/ioBroker.heytech. Expected: git+https://github.com/jey-cee/ioBroker.heytech.git

**Comment by Jey-Cee** [comment]
Plesse check the Adapter checker, this wasnt shown to me.

**Pull request merged**
