### PR TITLE
solarviewdatareader added to latest

### PR DESCRIPTION
**Pull request by afuerhoff**
[Forum Test](https://forum.iobroker.net/topic/26558/test-adapter-solarviewdatareader-v0-0-x)
[Forum Entwicklung](https://forum.iobroker.net/topic/23359/neuer-adapter-solarviewdatareader)

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by afuerhoff** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by afuerhoff** [comment]
@GermanBluefox 
Hallo, was für einen Fehler habe ich hier gemacht?

**Comment by afuerhoff** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by afuerhoff** [comment]
@Apollon77 
Hallo, was muss ich hier machen? Was ist schief gelaufen? Ich komme hier nicht weiter.

**Comment by Apollon77** [comment]
Wir checken gerade

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.solarviewdatareader](https://github.com/afuerhoff/ioBroker.solarviewdatareader)
[Downloads](https://www.npmjs.com/package/iobroker.solarviewdatareader) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.solarviewdatareader/)

- [ ] :heavy_exclamation_mark: [E506] Word "host" is not translated to russian in [admin/words.js](https://github.com/afuerhoff/ioBroker.solarviewdatareader/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "port" is not translated to russian in [admin/words.js](https://github.com/afuerhoff/ioBroker.solarviewdatareader/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "interval" is not translated to russian in [admin/words.js](https://github.com/afuerhoff/ioBroker.solarviewdatareader/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W400] Cannot find "solarviewdatareader" in latest repository

### [ioBroker.valloxmv](https://github.com/hacki11/ioBroker.valloxmv)
[Downloads](https://www.npmjs.com/package/iobroker.valloxmv) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.valloxmv/)

- [ ] :heavy_exclamation_mark: [E506] Word "host" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "port" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "interval" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations


*Add comment "RE-CHECK!" to start check anew*

**Comment by afuerhoff** [comment]
@Apollon77 
Warum ist hier der Adapter ioBroker.valloxmv aufgeführt? Das ist nicht meiner.
Das verstehe ich nicht.
Die Übersetzungen sollten eigentlich auch passen.

**Comment by Apollon77** [comment]
The checker checks ll "touched" adapters in that PR ... and both are touched. SImply ignore the other one

**Pull request merged**
