### PR TITLE
add withings

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.withings](https://github.com/TA2k/ioBroker.withings)
[Downloads](https://www.npmjs.com/package/iobroker.withings) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.withings/)

- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/TA2k/ioBroker.withings", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "withings" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.withings](https://github.com/TA2k/ioBroker.withings)
[Downloads](https://www.npmjs.com/package/iobroker.withings) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.withings/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "withings" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by ldittmar81** [comment]
@Apollon77 No errors found. Review can be done.

Please close https://github.com/ioBroker/AdapterRequests/issues/142 after review.

**Pull request merged**
