### PR TITLE
add linux-control to latest

### PR DESCRIPTION
**Pull request by Scrounger**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.linux-control](https://github.com/Scrounger/ioBroker.linux-control)
[Downloads](https://www.npmjs.com/package/iobroker.linux-control) 
[NPM](https://nodei.co/npm/iobroker.linux-control/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/Scrounger/iobroker.linux-control/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/Scrounger/ioBroker.linux-control/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/Scrounger/ioBroker.linux-control. Expected: git+https://github.com/Scrounger/iobroker.linux-control.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/Scrounger/ioBroker.linux-control/blob/master/io-package.json) must be equal to "". Now is linux-control
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html 
- [ ] :heavy_exclamation_mark: [E504] found setInterval in "main.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/Scrounger/iobroker.linux-control", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@Scrounger please check the checker comments

**Comment by Scrounger** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.linux-control](https://github.com/Scrounger/ioBroker.linux-control)
[Downloads](https://www.npmjs.com/package/iobroker.linux-control) 
[NPM](https://nodei.co/npm/iobroker.linux-control/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/Scrounger/iobroker.linux-control/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/Scrounger/ioBroker.linux-control/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/Scrounger/ioBroker.linux-control. Expected: git+https://github.com/Scrounger/iobroker.linux-control.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/Scrounger/ioBroker.linux-control/blob/master/io-package.json) must be equal to "". Now is linux-control
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :eyes: [W400] Cannot find "" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Scrounger** [comment]
i'm confused, result at https://adapter-check.iobroker.in/ is ok?

**Comment by Scrounger** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.linux-control](https://github.com/Scrounger/ioBroker.linux-control)
[Downloads](https://www.npmjs.com/package/iobroker.linux-control) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.linux-control/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "linux-control" in latest repository

### [ioBroker.linux-control](https://github.com/Scrounger/ioBroker.linux-control)
[Downloads](https://www.npmjs.com/package/iobroker.linux-control) 
[NPM](https://nodei.co/npm/iobroker.linux-control/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/Scrounger/iobroker.linux-control/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/Scrounger/ioBroker.linux-control/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/Scrounger/ioBroker.linux-control. Expected: git+https://github.com/Scrounger/iobroker.linux-control.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/Scrounger/ioBroker.linux-control/blob/master/io-package.json) must be equal to "". Now is linux-control
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :eyes: [W400] Cannot find "" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
Yes. Checker looks better: https://adapter-check.iobroker.in/?q=https://github.com/Scrounger/ioBroker.linux-control

**Comment by GermanBluefox** [comment]
But the intervals must be cleared on unload: https://github.com/Scrounger/ioBroker.linux-control/blob/master/main.js#L52

This does not work: https://github.com/Scrounger/ioBroker.linux-control/blob/master/main.js#L858

**Comment by Scrounger** [comment]
done in v 0.2.4

https://github.com/Scrounger/ioBroker.linux-control/blob/9be8c9ba0e968f456b3bbf3dbdf48d3d9c06470a/main.js#L82

https://github.com/Scrounger/ioBroker.linux-control/blob/9be8c9ba0e968f456b3bbf3dbdf48d3d9c06470a/main.js#L856

**Pull request merged**
