### PR TITLE
Added controme adapter to sources-dist.json

### PR DESCRIPTION
**Pull request by MadErstam**
Added controme adapter to sources-dist.json

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [io-package.json](https://github.com/main/io-package.json)
[Downloads](https://www.npmjs.com/package/io-package.json) 
[NPM](https://nodei.co/npm/io-package.json/)

- [ ] :heavy_exclamation_mark: 404


*Add comment "RE-CHECK!" to start check anew*

**Comment by MadErstam** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [io-package.json](https://github.com/main/io-package.json)
[Downloads](https://www.npmjs.com/package/io-package.json) 
[NPM](https://nodei.co/npm/io-package.json/)

- [ ] :heavy_exclamation_mark: 404


*Add comment "RE-CHECK!" to start check anew*

**Comment by MadErstam** [comment]
Ich verstehe ehrlich gesagt die Fehlermeldung nicht. Im Repository liegt klar eine io-package.json. Kann mir hier jemand weiterhelfen, was das Problem ist?

**Comment by Apollon77** [comment]
Yes but https://raw.githubusercontent.com/maderstam/ioBroker.controme/main/io-package.jso gives a 404 not found

**Comment by Apollon77** [comment]
ignore last post :-) so yes ... no idesa ... all good

**Comment by Apollon77** [comment]
Hello,

here some review feedback:

* Please add encryption for the password. Details see Develoepr best practices in the readme of this repo
* please remove iob_npm.done  file!
* why you do that in the async method? https://github.com/MadErstam/ioBroker.controme/blob/main/main.js#L84
* best practice would be to not use intervals because they might react strange when it comes to network issues (e.g. reuests pile up), but up to you. Best practice see readme
* ideally remember which objects were already created/checked in a run to not have that setObjectNotExists on every update (which simply costs performance)

Thank you for looking into my comments and adjusting accordingly. Please poke back here once done

**Comment by MadErstam** [comment]
Hi Apollon77,

thank you for the feedback! I have adjusted according to your comments and have published a new version 0.2.0 to Github including some further features I had planned to develop.

> * Please add encryption for the password. Details see Develoepr best practices in the readme of this repo

Done!
> * please remove iob_npm.done  file!

Done!

> * why you do that in the async method? https://github.com/MadErstam/ioBroker.controme/blob/main/main.js#L84

Because I have little understanding of how this whole asnyc stuff works. However, I already took that out of async, so this is fixed as well.

> * best practice would be to not use intervals because they might react strange when it comes to network issues (e.g. reuests pile up), but up to you. Best practice see readme

I agree and will look into this in a next revision, since this requires some more thought on my side. For now, since all api calls are to a local device, I will keep it as is.

> * ideally remember which objects were already created/checked in a run to not have that setObjectNotExists on every update (which simply costs performance)

Done, recreating new objects is now only done upon user request.

> Thank you for looking into my comments and adjusting accordingly. Please poke back here once done

I did not yet publish a new NPM packet. Is it OK to await your next feedback or should I do this now?

**Comment by MadErstam** [comment]
RE-CHECK!

**Comment by MadErstam** [comment]
This is the same issue as earlier. The file io-package.json exists and is correctly listed. This seems to be a bug in the auto adapter checker.

**Comment by MadErstam** [comment]
Can I do anything to expedite this check? The issues have all been resolved by now, so I would really appreciate if this adapter could get added to latest!

**Comment by Apollon77** [comment]
I will do another review

**Comment by Apollon77** [comment]
Hi,

* will https://github.com/MadErstam/ioBroker.controme/blob/main/main.js#L60-L72 really work? normally the getObject is async but your code runs further ... if is uses the password before in a call it might not be decrypeted. You can also depend on js-controller 3+ (and admin >=4.0.9 as "globalDependency" in io-package to use the auto encryption handling ... then all this is done for you automatically. Just defining the password field in encrypted/protectedNative then in io-package
* if you do the object creation that way https://github.com/MadErstam/ioBroker.controme/blob/main/main.js#L155 add a "return" after that extendObject because the extend will restart adapter anyway

And please publish a new npm package after changing, because else I would need with merge on that then :-)

**Comment by MadErstam** [comment]
Hi!

> * will https://github.com/MadErstam/ioBroker.controme/blob/main/main.js#L60-L72 really work? normally the getObject is async but your code runs further ... if is uses the password before in a call it might not be decrypeted. You can also depend on js-controller 3+ (and admin >=4.0.9 as "globalDependency" in io-package to use the auto encryption handling ... then all this is done for you automatically. Just defining the password field in encrypted/protectedNative then in io-package

I actually took that part from the prepareMain function in Apollon77/iobroker.meross (since the best practices told me to look there). No tester has indicated any problem, so it seems to work, but I honestly don't know what that part actually does ;). Can you elaborate on what you mean by "Just defining the password field in encrypted/protectedNative then in io-package"? Happy to change that part to whatever it should be.

> * if you do the object creation that way https://github.com/MadErstam/ioBroker.controme/blob/main/main.js#L155 add a "return" after that extendObject because the extend will restart adapter anyway

Again I really could use a bit of help here. The original line is:
```
try {
    await this.extendForeignObjectAsync('system.adapter.${this.namespace}', { native: { forceReInit: false } });
} catch (e) {
    this.log.error('Could not set forceReinit to false: ${e.message}');
}
```
Do you mean that I change it to:
```
try {
    await this.extendForeignObjectAsync('system.adapter.${this.namespace}', { native: { forceReInit: false } });
    return;
} catch (e) {
    this.log.error('Could not set forceReinit to false: ${e.message}');
}
```
Maybe a stupid question, but what is the difference here?

> And please publish a new npm package after changing, because else I would need with merge on that then :-)
Already did and will do again when I do further changes.

Thank you in advance!

**Comment by Apollon77** [comment]
sorry for the late feedback:

For encryption, see https://github.com/ioBroker/ioBroker.js-controller#automatically-encryptdecrypt-configuration-fields ... in fact you "just" need to define the fields to be encrypted there and add a "globalDependencies" with "admin >= 4.0.9 to io-package and you can remove all code where you encrypt or decrypt stuff because admin will encrypt automatically and the js.controller will decrypt automatically when the adapter starts :-) So you need to do nothing anymore with that 

To second question: That the controller restarts the adapter after object change takes some short time ... in that time your code contines to run - but in fact you know that with the extend there will be a restart, so no need to execute further code :-)

**Comment by Apollon77** [comment]
@MadErstam Any update?

**Comment by ldittmar81** [comment]
@MadErstam can I help you with this adapter?

**Comment by Apollon77** [comment]
@MadErstam ok, tests fail now? https://github.com/MadErstam/ioBroker.controme/runs/6685369658?check_suite_focus=true#step:6:65 The version numbers in package.json und io-package shopuld be in sync. Please check this

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.controme](https://github.com/maderstam/ioBroker.controme)
[Downloads](https://www.npmjs.com/package/iobroker.controme) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.controme/)

- [ ] :heavy_exclamation_mark: [E118] Versions in [package.json](https://github.com/maderstam/ioBroker.controme/blob/master/package.json) and in [io-package.json](https://github.com/maderstam/ioBroker.controme/blob/master/io-package.json) are different
- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/maderstam/ioBroker.controme/blob/master/io-package.json). Must be removed.
- [ ] :heavy_exclamation_mark: [E160] "admin" is not allowed in common.dependencies
- [ ] :heavy_exclamation_mark: [E512] "admin/jsonCustom.json5" not found, but custom support is declared
- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/maderstam/ioBroker.controme/blob/master/iob_npm.done)" found in repo! Remove that file
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 MadErstam <erstam@gmx.de>" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E914] file iob_npm.done found in repository, but not found in .gitignore
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/maderstam/ioBroker.controme/blob/master/io-package.json)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/maderstam/ioBroker.controme/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "controme" in latest repository
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
How we should continue? Can we help somehow? Should we do a PR with relevant changes? If it is just the version number this should be a 1 minute fix :)

**Comment by Apollon77** [comment]
@MadErstam Happy new year, how we should proceed?

**Comment by Apollon77** [comment]
@MadErstam How we should continue?

**Comment by mcm1957** [comment]
@MadErstam 

Please let us know if you are still maintaining this adapter and are intrested in registratrion at latest repositories.

If you are still interested I will do a new review to check what issues are still open / already fixed and to get this PR merged.

Please simply post a reply.

**If we do not get any responce with 30 days we will close this PR.** 
But of course a new PR will be welcome at any time.

**Comment by mcm1957** [comment]
@MadErstam 
A kind reminder
**If we do not receive any response (comment) here this PR will be closed after 6.9.2023**

**Comment by mcm1957** [comment]
closed due to inactivity.

Please feel free to create new PR at any time. Using www-iobroker.dev this can be done with a single click.

**Pull request closed without merging**
