### PR TITLE
- added plenticore adapter

### PR DESCRIPTION
**Pull request by StrathCole**
ioBroker.plenticore Adapter for KOSTAL Plenticore Plus

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Can you fix this?
image

**Comment by StrathCole** [comment]
Done in 1.1.0 just pushed to git and npm

**Comment by Apollon77** [comment]
Here are my review comments:
* Needs fix please: add all editable fields to io-package native with their default values
* Note: Do you really want to write in the adapters node_module directory? This is deleted on every update of the adapter ... Better use iobroker-data/instance directory? (https://github.com/StrathCole/ioBroker.plenticore/blob/master/main.js#L10)
* Note: How long the code in "Unload" normally needs? 500ms is the default time limit before adapter is killed hard. If it needs more time set io-package.common-stopTimeout with a higher value
* Note: if you do not need on-message please do not implement it 
* Note: The code https://github.com/StrathCole/ioBroker.plenticore/blob/master/main.js#L1149 is executed arallel to the other code because async, so it could be that the variable is set to false later ...
* Note: Do I see it correct that in many places createOrSetState is used also during runtime and not initial only? so for each "setState" you read the object too? This costs performance! Please re-think it. Alternatively you could use the oject cache from adapter class ...
* Note: The two api calls are done kind of in parallel at https://github.com/StrathCole/ioBroker.plenticore/blob/master/main.js#L1632 and other places. If you rely on that the first was finished before doing the second you should chain them in the callback!
* Needs fix: you do not store the timoeut here and do not end it in unload: https://github.com/StrathCole/ioBroker.plenticore/blob/master/main.js#L1666
* Needs fix: please use adapter.terminate if available instead of process.exit, else compact mode gets killed. (https://github.com/StrathCole/ioBroker.plenticore/blob/master/main.js#L1818)
* Note: The code in https://github.com/StrathCole/ioBroker.plenticore/blob/master/main.js#L1664-L1667 culd mean that you start polling twice (e.g. when I have set 6000) ;-)
* Note: Me personally do not like setInterval when doing external communications. Reason: When a timeout or such happens the next intervall fires as requested also when the run before is still running ... So requests can pile up and strange things happen. I think better is to set a timout for next run at the end of last run.
* Needs fixing: Please add intgration testing that starts adapter - or is there a reason not to have it?

**Comment by StrathCole** [comment]
Hopefully everything was addressed now.

**Pull request merged**
