### PR TITLE
Add zwave2 to stable

### PR DESCRIPTION
**Pull request by AlCalzone**
I'm preparing the stable release for Z-Wave 2. v0.14.6 will probably be the final version before that is going to happen.

I'm raising this PR to find potential problems while the final tests are going on.

### CODE REVIEW

**Comment by AlCalzone** [comment]
Well... that was easy :D

**Comment by AlCalzone** [comment]
1.0.0 will be released in a couple of minutes. It is relatively new, but well-tested:
* 0.14.x test thread: https://forum.iobroker.net/topic/33733/test-adapter-z-wave-2-v0-14-x/75
* The jump from 0.14.9 to 1.0.0 only contains a config change for Danfoss devices which was tested here: https://forum.iobroker.net/topic/33166/test-adapter-z-wave-2-v0-12-x-0-13-x/101

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.zwave2](https://github.com/AlCalzone/ioBroker.zwave2)
[Downloads](https://www.npmjs.com/package/iobroker.zwave2) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.zwave2/)

- [ ] :heavy_exclamation_mark: [E603] NO "## Changelog" found in [README.md](https://github.com/AlCalzone/ioBroker.zwave2/blob/master/README.md)


*Add comment "RE-CHECK!" to start check anew*

**Comment by AlCalzone** [comment]
Hmm, the changelog is now in `CHANGELOG.md`. Does it **really** have to be in the readme?

**Comment by Apollon77** [comment]
np

**Comment by GermanBluefox** [comment]
Changelog is required for www.iobroker.net site. 

You can place only last 3-5 changes in readme.md and the rest on changelog.md. like here: https://github.com/ioBroker/ioBroker.admin/blob/master/CHANGELOG_OLD.md

**Comment by AlCalzone** [comment]
Ok then I'll need to update my release Script to handle multiple files

**Pull request merged**
