### PR TITLE
airconwithme adapter

### PR DESCRIPTION
**Pull request by weggetor**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by weggetor** [comment]
Hi @Apollon77  is RE-CHECK something I should do or is it a reminder for you ?

**Comment by Apollon77** [comment]
Hm ...normally that triggers a check ... hm :-)

**Comment by Apollon77** [comment]
Can you please fix the json?
https://github.com/ioBroker/ioBroker.repositories/pull/1190/files#diff-2f081148e7c1e967d95d62cf221b95076ecfce50a93bb9f82bc96d0ddb2d05a1R24

... best close this PR and make a new one because then the auto check should work as expected :-)

**Comment by weggetor** [comment]
closing and reopening

**Pull request closed without merging**
