### PR TITLE
Update blebox to v2.1.0

### PR DESCRIPTION
**Pull request by ka-vaNu**

### CODE REVIEW

**Comment by mcm1957** [comment]
Link to adapter: https://github.com/ka-vaNu/ioBroker.blebox

**Comment by mcm1957** [comment]
Please fix the following issues:

- [ ] README.md should be written in pure english

  As ioBroker is an international software supporting several languages the main README.md file should be written in pure english. Its ok to add additional Readme-<lang>.mds of course. README.md is translated automatically into other languages to be used at ioBroker website - other languages or mixed languges are desturbing this functionality.

- [ ] adapt testing to supported node releases

  As node 14 is end of life and will no longer be supported by js-controller 5.x, consider removing node 14.x tests from matrix id still present.
  Tests for node 16 is mandatory unless you require node 18 and higher (at package.json).
  Tests for node 18 is mandatory as this is the recommended node version and node 16 will be eol and deprected Q3/2023.
  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x] or [18.x, 20.x] depending on engines requirments setting at package.json 

  As node 16 is end-of-life now, it's ok to remove node 16 from testing. In this case please require node 18 as minimum node version at pacakge.json.

- [ ] functional minimal guthub tests are required, check that
   - GitHub Actions are enabled
   - package tests are executed
   - adapter tests (integration) are executed and "green" (also really ok, scroll over test results)

**Comment by ka-vaNu** [comment]
Hi!

Thanks for your review. I fixed the mentioned issues. Readme.MD is noch translated, minimum nodejs-version is now 16.x and github actions are working fine. Also the integrationtests are green.

**Comment by mcm1957** [comment]
2.1.0 created 13.10.2023

**Comment by mcm1957** [comment]
2.1.0 created 13.10.2023
4 user (3%)
OK

**Pull request merged**
