### PR TITLE
Add iobroker.haassohn adapter to latest

### PR DESCRIPTION
**Pull request by marvingrieger**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)

### [ioBroker.haassohn](https://github.com/marvingrieger/ioBroker.haassohn)
[Downloads](https://www.npmjs.com/package/iobroker.haassohn) 
[NPM](https://nodei.co/npm/iobroker.haassohn/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "haassohn" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by marvingrieger** [comment]
Hello @GermanBluefox, can you tell me what needs to be fixed?

**Comment by marvingrieger** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/xenon-s/ioBroker.device-reminder/blob/master/iob_npm.done)" found in repo! Please add it to .gitignore
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 xenon-s <ente_s@hotmail.de>" at the end of [README.md](https://github.com/xenon-s/ioBroker.device-reminder/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 xenon-s <ente_s@hotmail.de>" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E818] file iob_npm.done found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E914] file iob_npm.done found in repository, but not found in .gitignore

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)

### [ioBroker.haassohn](https://github.com/marvingrieger/ioBroker.haassohn)
[Downloads](https://www.npmjs.com/package/iobroker.haassohn) 
[NPM](https://nodei.co/npm/iobroker.haassohn/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "haassohn" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by marvingrieger** [comment]
RE-CHECK!"

**Comment by marvingrieger** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.device-reminder](https://github.com/xenon-s/ioBroker.device-reminder)
[Downloads](https://www.npmjs.com/package/iobroker.device-reminder) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.device-reminder/)

- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/xenon-s/ioBroker.device-reminder/blob/master/iob_npm.done)" found in repo! Please add it to .gitignore
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 xenon-s <ente_s@hotmail.de>" at the end of [README.md](https://github.com/xenon-s/ioBroker.device-reminder/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 xenon-s <ente_s@hotmail.de>" at the start of LICENSE
- [ ] :heavy_exclamation_mark: [E818] file iob_npm.done found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E914] file iob_npm.done found in repository, but not found in .gitignore

### [ioBroker.devices](https://github.com/ioBroker/ioBroker.devices)
[Downloads](https://www.npmjs.com/package/iobroker.devices) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.devices/)

- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/ioBroker/ioBroker.devices/blob/master/io-package.json)

### [ioBroker.haassohn](https://github.com/marvingrieger/ioBroker.haassohn)
[Downloads](https://www.npmjs.com/package/iobroker.haassohn) 
[NPM](https://nodei.co/npm/iobroker.haassohn/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "haassohn" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
All good for your adapter ...we now will do a review

**Comment by foxriver76** [comment]
Hello @marvingrieger,

thanks for your PR and your patience. Please find my review below.

### Has to be fixed
- Please at least use [ioBroker Translator](https://translator.iobroker.in/) to provided more languages than German and English, e.g. https://github.com/marvingrieger/ioBroker.haassohn/blob/c3dfc6c00485e27594ad94de982e6d9826221990/io-package.json#L69
- The referenced docs are non-existing, better specify your readme https://github.com/marvingrieger/ioBroker.haassohn/blob/c3dfc6c00485e27594ad94de982e6d9826221990/io-package.json#L75
- The docs are only templates, please at least add them to .npmignore otherwise they will be downloaded at every installation w/o providing any relevant content

### Should be fixed
- I would recommend you to migrate testing from travis/appveyor to GH actions, which is a lot faster and of course integrated
- adapter startup unit test is now deprecated, so you can remove https://github.com/marvingrieger/ioBroker.haassohn/blob/master/test/unit.js and https://github.com/marvingrieger/ioBroker.haassohn/blob/c3dfc6c00485e27594ad94de982e6d9826221990/package.json#L42 except you will define your own unit tests in the near future
- You should really avoid using `var` like https://github.com/marvingrieger/ioBroker.haassohn/blob/c3dfc6c00485e27594ad94de982e6d9826221990/main.js#L16 and everywhere else in your code. Modern javascript has `const` and `let`, for such patterns I can really recommend you the `eslint` module which takes care of this
- `module.parent` is deprecated https://github.com/marvingrieger/ioBroker.haassohn/blob/c3dfc6c00485e27594ad94de982e6d9826221990/main.js#L487, better check `module === require.main`
- you have a very complex adapter disabling handling in your code, you can simply call `adapter.terminate` this will stop the execution without disabling the adapter, which is pretty much what you do in your code

I am looking forward to the revised version of your adapter. Happy coding :computer:

**Comment by marvingrieger** [comment]
Hello @foxriver76,

thanks for your valuable feedback! I fixed the "_Has to be fixed"_-issues and some of the "_Should be fixed_"-issues.

For the remaining "_Should be fixed_"-ones I created issues within my repository ([#23](https://github.com/marvingrieger/ioBroker.haassohn/issues/23), [#24](https://github.com/marvingrieger/ioBroker.haassohn/issues/24), [#25](https://github.com/marvingrieger/ioBroker.haassohn/issues/25)). I will address them one after another.

Can you re-check?

**Comment by foxriver76** [comment]
Thanks, oh I saw you also changed index_m.html to using `let` and co, there you have to be careful, because some users use very old browsers. However, for admin it should be okay, it is more of an issue if you implement visualization stuff which users are running on tablets, like vis widgets.

**Pull request merged**
