### PR TITLE
add sainlogic to latest

### PR DESCRIPTION
**Pull request by phifogg**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sainlogic](https://github.com/phifogg/ioBroker.sainlogic)
[Downloads](https://www.npmjs.com/package/iobroker.sainlogic) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sainlogic/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.sainlogic)!. Please execute in adapter directory: `npm owner add bluefox iobroker.sainlogic`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E603] NO "## Changelog" found in [README.md](https://github.com/phifogg/ioBroker.sainlogic/blob/master/README.md)
- [ ] :eyes: [W400] Cannot find "sainlogic" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@phifogg Please see the comments from the checker. also https://github.com/ioBroker/ioBroker.repositories#development-and-coding-best-practices is a good information source

**Comment by phifogg** [comment]
Hi Apollon, I did execute 'npm access grant read-write iobroker:developers iobroker.<adaptername>' - is bluefox still required as additional owner?

**Comment by Apollon77** [comment]
Mostly the grant to the developer group does not worsk :-( Thats why please add bluefox (better safe here :-) 

Changelog is meaned as changelogsection in your readme! like https://github.com/Apollon77/ioBroker.tuya#changelog
In fact the change log there kind of "twice". The changelog in readme is the "verbose one" if you like and will be shown in Admin and on webseite when people want to see infos on Adapter. The "news" in io-package.json and the "short update changelog" shown in Admin when people get updates for your adspter so that they know whats changed roughly

**Comment by phifogg** [comment]
Trying to add bluefox I get this error:
npm ERR! owner mutate Error getting user data for bluefox
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://registry.npmjs.org/-/user/org.couchdb.user:bluefox

**Comment by phifogg** [comment]
As for changelog... i would think this should be improved. Makes already 3 places to update a version info (package.json, io-package.json and README) ... i am happy to have a changelog as I get the need for it, but three places?

**Comment by phifogg** [comment]
I've added bluefox manually in npmjs.org. Can you re-run your checks?

**Comment by phifogg** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sainlogic](https://github.com/phifogg/ioBroker.sainlogic)
[Downloads](https://www.npmjs.com/package/iobroker.sainlogic) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sainlogic/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.sainlogic)!. Please execute in adapter directory: `npm owner add bluefox iobroker.sainlogic`
- [ ] :eyes: [W400] Cannot find "sainlogic" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by phifogg** [comment]
Anmerkung 2020-05-29 231711

**Comment by Apollon77** [comment]
Maybe try https://github.com/AlCalzone/release-script/blob/master/src/release.ts#L6 :-) cool small tool ... you just write the infos in readme.md in changelog  and this does everything icnluding news transpation

**Comment by phifogg** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sainlogic](https://github.com/phifogg/ioBroker.sainlogic)
[Downloads](https://www.npmjs.com/package/iobroker.sainlogic) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sainlogic/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.sainlogic)!. Please execute in adapter directory: `npm owner add bluefox iobroker.sainlogic`
- [ ] :eyes: [W400] Cannot find "sainlogic" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by phifogg** [comment]
i tried adding bluefox and based on my screenshot above he should be. why would the check still fail?

**Comment by Apollon77** [comment]
Yes seems to be a false positive, everything ok

**Comment by phifogg** [comment]
How do we get this moved forward? Sitting here since 19 days now.

**Comment by Apollon77** [comment]
Hi, some comments:
* you can use https://translator.iobroker.in/ to translate news and such in all relevant languages
* Please do not use https://github.com/phifogg/ioBroker.sainlogic/blob/master/main.js#L44 setObjectAsync, but setObjectNotExists 
* Please remove onObjectChange if not needed. same for onStateCange

**Comment by DutchmanNL** [comment]
@phifogg any update?

**Comment by Apollon77** [comment]
@phifogg any news?

**Comment by phifogg** [comment]
I did all but the translation.... 
Kind of not on my important list as it works just fine without...

**Comment by Apollon77** [comment]
I checked repo, setObject and also objectChange is still in. Maybe you forgot to push?

**Comment by Apollon77** [comment]
@phifogg could you please adjust the setObject to use setObjectsNotExists please ... then we would be ready for the repo :-)

**Comment by phifogg** [comment]
Indeed, changes where 'stuck' in my dev branch. I have merged them back to main now.

**Comment by Apollon77** [comment]
Hey, I had another check and saw one strange thing ... did you forot to add the unload event? the onUnload method is there but not called from somewhere. Sorry this needs to be fixed! :-)

**Comment by phifogg** [comment]
It is there, main.js around line 256.

**Comment by Apollon77** [comment]
yes the method itself is there ... but needs to be bound to the unload event like the others https://github.com/phifogg/ioBroker.sainlogic/blob/master/main.js#L29-L32

**Comment by phifogg** [comment]
Oh dear... now I know what you meant.
This has been addressed now.

**Comment by Apollon77** [comment]
Awesome :-) ANd welcome in the repo

**Pull request merged**
