### PR TITLE
update viessmannapi url

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
I assume you have ok from original developer?

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.viessmannapi](https://github.com/TA2k/ioBroker.viessmannapi)
[Downloads](https://www.npmjs.com/package/iobroker.viessmannapi) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.viessmannapi/)

- [ ] :heavy_exclamation_mark: [E104] No common.title found in [io-package.json](https://github.com/TA2k/ioBroker.viessmannapi/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.viessmannapi/master/
- [ ] :heavy_exclamation_mark: [E407] Meta URL(latest) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.viessmannapi/master/io-package.json


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.viessmannapi](https://github.com/TA2k/ioBroker.viessmannapi)
[Downloads](https://www.npmjs.com/package/iobroker.viessmannapi) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.viessmannapi/)

- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.viessmannapi/master/
- [ ] :heavy_exclamation_mark: [E407] Meta URL(latest) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.viessmannapi/master/io-package.json


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
No no response from the original developer.
Bluefox overwrite original not working adapter on npm

**Pull request merged**
