### PR TITLE
proxmoix to stable

### PR DESCRIPTION
**Pull request by MeisterTR**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.proxmox](https://github.com/iobroker-community-adapters/ioBroker.proxmox)
[Downloads](https://www.npmjs.com/package/iobroker.proxmox) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.proxmox/)

- [ ] :heavy_exclamation_mark: [E504] found setInterval in "main.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 MeisterTR <meistertr.smarthome@gmail.com>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.proxmox/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2020 MeisterTR <meistertr.smarthome@gmail.com>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode

**Comment by MeisterTR** [comment]
fixed the errors

**Comment by Apollon77** [comment]
Then please push new version number in this PR :-)

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.proxmox](https://github.com/iobroker-community-adapters/ioBroker.proxmox)
[Downloads](https://www.npmjs.com/package/iobroker.proxmox) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.proxmox/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
