### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by foxriver76**
-Added Denon Adapter v0.1.9 to stable & latest

### CODE REVIEW

**Comment by Apollon77** [comment]
In latest file please without version ;-)

**Comment by Apollon77** [comment]
Bluefox and ioBroker organization set as owner on npm?

**Comment by Apollon77** [comment]
And please add common.license in io-package with our license!

**Comment by foxriver76** [comment]
Bluefox is set as owner, see: https://www.npmjs.com/package/iobroker.denon/v/0.1.9
I will fix the license, thanks for the feedback

**Comment by foxriver76** [comment]
see https://github.com/foxriver76/ioBroker.denon/commit/f5b9a9e1b7055fa39855c612e2469f5c374f09f7
If this is all, I will publish it as 0.2.0 to npm and set it as stable.

**Comment by Apollon77** [comment]
Please do so :-)

**Comment by foxriver76** [comment]
done.

**Comment by Apollon77** [comment]
stable here still 0.1.9?

**Pull request merged**
