### PR TITLE
Add boschindego to latest

### PR DESCRIPTION
**Pull request by mcm1957**
@TA2k 
This is a replacement for #2918

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestions or want to discuss some special aspects.
 
- [ ] Readme.md is very short

  The README.md of this adapter is very minimalistic. Please consider add a short description about the functionality of the adpter,  add links the the manufacturer site (if applicable) and add a description of the configuration of the adapter. If you provide an external documentation - which should be located at doc/xx directory - please add links to at least the english documentation.

   This remark is NOT blocking, consider it as a feedback only with one exception: A link to the manufactorers site / device page should be added i n any case. This will help users to check if the adapter is releted to the device they are loking for. 
  
- [ ] package.json contains override

  Is there a special reason to specify overrides at package.json?
  ```
  "overrides": {
    "axios": "^1.6.1"
  }
  ```
  Please let me know the reason.

- [ ] Why did you decide to not use i18n environment?
  
  You added translations directly into jsonConfig.json. Please consider movin to i18n tree solution as this will enable usage of weblate and hence provide the possibility for native speakers to correct transaltions at theit langiuge easily.

   This remark is NOT blocking, consider it as a feedback as it can be changed anytime later withut much side effects.
  
- [ ] consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

   This remark is NOT blocking, consider it as a feedback for improvement

- [ ] check and limit configurable timeouts / intervals
  
  Node setTimeout/setInterval routines have a maximum allowed value of 2,147,483,647 ms. Using delays larger than 2,147,483,647 ms (about 24.8 days) result in the timeout being executed immediately. So all (user configurable) values passed to setTimeout / setInterval should be checked in code and limited. Checking/limiting in code is required as config data could be changed directly or by some other adapter too, so limiting at ui level might not be sufficient.

  Minimum is checked, but maximum seems to be not checked currently. This could (in theory) be a problem especially when not using this.setToeout/this.setInterval.
  
- [ ] check and adapt testing
  
  Standard iobroker testing is required but seems to be missing. Please activate standard deploy workflow at .github/workflows/test-and-release.yml as all community adapters should have a common release workflow enabled. https://github.com/iobroker-community-adapters/ioBroker.boschindego/blob/8de22ca95444c4dee6afc2ad7f5757fbee476343/.github/workflows/test-and-release.yml#L58
  
- [ ] This adapter seems to use sentry, but no sentry info is added to Readme.md
  
  This adapter seems to use sentry for error logging. Please add the suggested sentry information at the top of Readme.md
  
  ```**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0.```
  
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by TA2k** [comment]
Added information to readme 
But I will not link to  the manufacturer site because of copyright issues
Overrides are needed because the release scripts packages are not maintained and using vulnerable version of axios
Weblate translation is so bad I is not recommended to use it and for 3 line of text makes no sense to introduce this folder structure

I prefer to use the direct implementation to have full control about it
limit check is added

release part is not active in the GitHub action workflow file

sentry information is added

**Comment by mcm1957** [comment]
>Overrides are needed because the release scripts packages are not maintained and using vulnerable version of axios

Do you refer to @alcalcone\releasescript?
How should they effect the productive environment at all?


>release part is not active in the GitHub action workflow file

Yes, but it should as this is a community adapter and I do not ssee a reason to not use the automatic deploy. Its (besides activation)mdefinitly no additional work neither during test nor during release.

**Comment by TA2k** [comment]
productive environment not but still an issue when npm install 

release part is now active in the GitHub action workflow file

**Comment by mcm1957** [comment]
> productive environment not but still an issue when npm install

Could you please give some more information. As this issue should effect more adaoters it should be fixed. Should be discussed with @AlCalzone

**Comment by mcm1957** [comment]
One think I just detected. Theres a repo: https://github.com/a1development/ioBroker.boschindego
Did you fork / importand adpat this earlier adapter or is your work a independent (re)write. If imported I would suggest to add some credits, (But this is indo only and not a requirement=

**Comment by TA2k** [comment]
independent rewrite

**Comment by mcm1957** [comment]
> independent rewrite

DANKE für deine Arbeit und Zeit

**Comment by mcm1957** [comment]
@TA2k 

This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, ist OK to continue using this topic too.

**Pull request merged**
