### PR TITLE
Update Growatt to V3.0.4

### PR DESCRIPTION
**Pull request by PLCHome**

### CODE REVIEW

**Comment by mcm1957** [comment]
Please fix the following issue. Adding Info to README.md is suufficient, NO new release is required.

- [ ] This adapter seems to use sentry, but no sentry info is added to Readme.md
  
  This adapter seems to use sentry for error logging. Please add the suggested sentry information at the top of Readme.md
  
  ```**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0.```
  
Thanks
McM1957

**Comment by PLCHome** [comment]
changed

**Comment by mcm1957** [comment]
thanks

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
3.0.4 created 03.07.2023
107 User (9%)
OK

**Pull request merged**
