### PR TITLE
Transfer yamaha to community

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.yamaha](https://github.com/iobroker-community-adapters/ioBroker.yamaha)
[Downloads](https://www.npmjs.com/package/iobroker.yamaha) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.yamaha/)

- [ ] :heavy_exclamation_mark: 404


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.yamaha](https://github.com/iobroker-community-adapters/ioBroker.yamaha)
[Downloads](https://www.npmjs.com/package/iobroker.yamaha) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.yamaha/)

- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/iobroker-community-adapters/ioBroker.yamaha/blob/master/package.json) must be lowercase and be equal to "iobroker.yamaha". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/soef/iobroker.yamaha. Expected: git+https://github.com/iobroker-community-adapters/ioBroker.yamaha.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.yamaha/blob/master/io-package.json) must be equal to "yamaha". Now is yamaha-community
- [ ] :heavy_exclamation_mark: [E109] desc in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.yamaha/blob/master/io-package.json) should be an object for many languages. Found only Yamaha AVR Adapter
- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin3 support
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/
- [ ] :heavy_exclamation_mark: [E407] Meta URL(latest) must be equal to https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/io-package.json
- [ ] :heavy_exclamation_mark: [E426] Icon(stable) must be in the following path: https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/
- [ ] :heavy_exclamation_mark: [E428] Meta URL(stable)  must be equal to https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/io-package.json
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2015-2020 soef <soef@gmx.net>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.yamaha/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2015-2020 soef <soef@gmx.net>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.yamaha](https://github.com/iobroker-community-adapters/ioBroker.yamaha)
[Downloads](https://www.npmjs.com/package/iobroker.yamaha) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.yamaha/)

- [ ] :heavy_exclamation_mark: [E109] desc in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.yamaha/blob/master/io-package.json) should be an object for many languages. Found only Yamaha AVR Adapter
- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin3 support
- [ ] :heavy_exclamation_mark: [E125] External icon not found under URL: https://github.com/iobroker-community-adapters/ioBroker.yamaha/master/admin/yamaha.png
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/
- [ ] :heavy_exclamation_mark: [E407] Meta URL(latest) must be equal to https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/io-package.json
- [ ] :heavy_exclamation_mark: [E426] Icon(stable) must be in the following path: https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/
- [ ] :heavy_exclamation_mark: [E428] Meta URL(stable)  must be equal to https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/io-package.json
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2015-2020 soef <soef@gmx.net>" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.yamaha/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2015-2020 soef <soef@gmx.net>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.yamaha](https://github.com/iobroker-community-adapters/ioBroker.yamaha)
[Downloads](https://www.npmjs.com/package/iobroker.yamaha) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.yamaha/)

- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/
- [ ] :heavy_exclamation_mark: [E407] Meta URL(latest) must be equal to https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/io-package.json
- [ ] :heavy_exclamation_mark: [E426] Icon(stable) must be in the following path: https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/
- [ ] :heavy_exclamation_mark: [E428] Meta URL(stable)  must be equal to https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/io-package.json


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@foxriver76

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.yamaha](https://github.com/iobroker-community-adapters/ioBroker.yamaha)
[Downloads](https://www.npmjs.com/package/iobroker.yamaha) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.yamaha/)

- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/
- [ ] :heavy_exclamation_mark: [E407] Meta URL(latest) must be equal to https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/io-package.json
- [ ] :heavy_exclamation_mark: [E426] Icon(stable) must be in the following path: https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/
- [ ] :heavy_exclamation_mark: [E428] Meta URL(stable)  must be equal to https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha/master/io-package.json


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
This is ready to merge. The corrected paths are part of this PR, seems like the check is a little bit weird here.

**Pull request merged**
