### PR TITLE
Update Plex in stable repo

### PR DESCRIPTION
**Pull request by Zefau**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.plex](https://github.com/Zefau/ioBroker.plex)
[Downloads](https://www.npmjs.com/package/iobroker.plex) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.plex/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.9.0
- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/Zefau/ioBroker.plex/blob/master/io-package.json). Must be removed.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@Zefau can you please fix the errors :-) Thank you

**Comment by Zefau** [comment]
I will fix it soon now, but just to remark, this is a stable bump to 0.8.11, not 0.9.0
```
No news found for actual version 0.9.0
```

**Comment by Zefau** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.plex](https://github.com/Zefau/ioBroker.plex)
[Downloads](https://www.npmjs.com/package/iobroker.plex) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.plex/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Zefau** [comment]
@Apollon77 please merge, thanks :)

**Pull request merged**
