### PR TITLE
add net-tools to latest

### PR DESCRIPTION
**Pull request by Jey-Cee**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.net-tools](https://github.com/jey-cee/ioBroker.net-tools)
[Downloads](https://www.npmjs.com/package/iobroker.net-tools) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.net-tools/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.net-tools)!. Please execute in adapter directory: `npm owner add bluefox iobroker.net-tools`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E502] "admin/img/info-big.png" not found, but selectID.js used in index_m.html 
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/jey-cee/ioBroker.net-tools", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/jey-cee/ioBroker.net-tools", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "net-tools" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Jey-Cee** [comment]
RE-CHECK

**Comment by Jey-Cee** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.net-tools](https://github.com/jey-cee/ioBroker.net-tools)
[Downloads](https://www.npmjs.com/package/iobroker.net-tools) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.net-tools/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.net-tools)!. Please execute in adapter directory: `npm owner add bluefox iobroker.net-tools`
- [ ] :eyes: [W400] Cannot find "net-tools" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Jey-Cee** [comment]
Last 2 are false positive

**Comment by Apollon77** [comment]
Hi, some review comments
*  whats the reason for the controller dep >=3.1.6?
* https://github.com/Jey-Cee/ioBroker.net-tools/blob/9b010f176f72629328c42838b7ca1ab1eb6bc6e5/main.js#L127 as example can throw exceptions and they are not catched and will kil the adapter instance ... optimize?
* really setObject? COuld work because of the high controller dep ... https://github.com/Jey-Cee/ioBroker.net-tools/blob/9b010f176f72629328c42838b7ca1ab1eb6bc6e5/main.js#L281

**Comment by Jey-Cee** [comment]
> * whats the reason for the controller dep >=3.1.6?

Decided to set it to the same Version as in my developer machine, because I haven't tested any lower version.


> * really setObject? COuld work because of the high controller dep ... https://github.com/Jey-Cee/ioBroker.net-tools/blob/9b010f176f72629328c42838b7ca1ab1eb6bc6e5/main.js#L281

Yes really, as extendObject does not work and i wasn't able to find the reason. 





> * https://github.com/Jey-Cee/ioBroker.net-tools/blob/9b010f176f72629328c42838b7ca1ab1eb6bc6e5/main.js#L127 as example can throw exceptions and they are not catched and will kil the adapter instance ... optimize?

I will check.

**Comment by Apollon77** [comment]
> Yes really, as extendObject does not work and i wasn't able to find the reason.

extendObject need to work I use that in several adapters of mine... you just need to provide the full object definition then (at least in js-controller 3.x+) extendObject will also create object if relevant

**Comment by Jey-Cee** [comment]
> extendObject need to work I use that in several adapters of mine...

I also used it in the past, but for unknown reason it stopped updating objects and a unreliable function is useless.
I noticed that in deConz adapter, where this function was working for a year (or longer). The function was called correct and returns no error.



> you just need to provide the full object definition then

Means that it is neccessary to pass the full object definition? If so why was it changed and not communicated, as it is a breaking change to this function.

Tested it with full object definition and only the part that has to be updated, result was the same nothing happens.

**Comment by Apollon77** [comment]
> I also used it in the past, but for unknown reason it stopped updating objects and a unreliable function is useless.
I noticed that in deConz adapter, where this function was working for a year (or longer). The function was called correct and returns no error.

This would be very bad and need to be fixed. please craete js-controller is with details

> Means that it is neccessary to pass the full object definition? If so why was it changed and not communicated, as it is a breaking change to this function.

No, if you just want to extend existing objects you can do partially. But you could also use extend to completely create the object and update data in one step - then you need full definition

**Comment by Apollon77** [comment]
@Jey-Cee how we continue here. Can we get more infos on the extendObject problem please?

**Comment by Jey-Cee** [comment]
Merge the PR, the extendObject problem is no reason for not merging it.
And no actual i can not provide more information on this, while i do not have more. I use it on enocean and it seems to work, but i have not done a deeper research.

**Comment by Apollon77** [comment]
In fact it is your risk to destroy visu- and history- and such custom settings for all objects of your adapter ... In fact we urge devs to use extend or setObjectsNotExists as a clear best practice

**Pull request merged**
