### PR TITLE
Add smoothed to latest

### PR DESCRIPTION
**Pull request by BenAhrdt**
Please add my adapter ioBroker.smoothed to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
reminder 27.2.2024

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by BenAhrdt** [comment]
? is there something to do?

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.
And sorry for the long time to wait for a review.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] typo in README.md ?

   ```smoothes selected signas according to a selected function```
   I guess signas should read as signa**l**s

- [ ] Readme.md is very short

  The README.md of this adapter is very minimalistic. If you have timme please add some more description an i.e. an example. I think (from teelgram discussions) this adapter could provide filtering using high / low pass but for sure m uch more functionality. This should be described at readme so users can decide to test the adapter.

- [ ] invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```, i.e. by using the following snippet:
```
function name2id(pName) {
    return (pName || '').replace(adapter.FORBIDDEN_CHARS, '_');
}
```
  At least channelname is extracted from user config (https://github.com/BenAhrdt/ioBroker.smoothed/blob/0aa65bc897d143ea7a4b03d20ee94780be0b1c97/lib/modules/statehandling.js#L124). This must be filtered. Did not check other sources (like smotthed value). Please ensure that all ids retrieved from external sources (like user input) are filtered for illegal characters.

- [ ] onStateChange handler ignores ack flag 

  The adapter must honor the ack flag when processing onStateChange events. Whenever the onStateChange handler is called for an own state (a state owned by the processing instance of the adapter) it must ignore this event if the ack flags is set. Only stateChanges with ack==false are allowed to be processed.

  When processing foreign states which are output of another adapter  processing must only occure if the ack flag is true.

  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
reminder 12.3.2024

**Comment by BenAhrdt** [comment]
I will have a Look for your comments this week.
First of all i have to say that the Adapter Loks at values to Smooth them. So it is possible the values came out from orher adapters (EVER) with ack = true.
So the ack flag dont matters on this Adapter, because the adapter just work with the States and dont Write them.

**Comment by mcm1957** [comment]
> So it is possible the values came out from orher adapters (EVER) with ack = true. So the ack flag dont matters on this Adapter, because the adapter just work with the States and dont Write them.

If you are reading values output by other adapters they should be acked by the writing adapter, see last line of the remark:
 
> When processing foreign states which are output of another adapter processing must only occure if the ack flag is true.

Do you really want to process unacknowledged values of other adapters ?

**Comment by BenAhrdt** [comment]
Yes. Because in the past There were many questions about it with States from scripts which are not acked.
The Adapter Can work With it, cause of the Timestampe.

**Comment by BenAhrdt** [comment]
Here my comments to the changes.
(All chanes are done and work)

 typo in README.md ?

smoothes selected signas according to a selected function
I guess signas should read as signals

 Readme.md is very short

The README.md of this adapter is very minimalistic. If you have timme please add some more description an i.e. an example. I think (from teelgram discussions) this adapter could provide filtering using high / low pass but for sure m uch more functionality. This should be described at readme so users can decide to test the adapter.


=> `Readme changes`

 invalid characters should be filtered from object ids

Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character. Iobroker provides the constant adapter.FORBIDDEN_CHARS, i.e. by using the following snippet:

function name2id(pName) {
    return (pName || '').replace(adapter.FORBIDDEN_CHARS, '_');
}

=> `Use replace(adapter.FORBIDDEN_CHARS, '_') and in case there was a forbidden char,
the adapter give a warning and dont create the state`

At least channelname is extracted from user config (https://github.com/BenAhrdt/ioBroker.smoothed/blob/0aa65bc897d143ea7a4b03d20ee94780be0b1c97/lib/modules/statehandling.js#L124). This must be filtered. Did not check other sources (like smotthed value). Please ensure that all ids retrieved from external sources (like user input) are filtered for illegal characters.

=> `see point before... checking the name and id. if the id is nadditionally not a number,
adapter will log a warning and dont create sate`

 onStateChange handler ignores ack flag

The adapter must honor the ack flag when processing onStateChange events. Whenever the onStateChange handler is called for an own state (a state owned by the processing instance of the adapter) it must ignore this event if the ack flags is set. Only stateChanges with ack==false are allowed to be processed.

When processing foreign states which are output of another adapter processing must only occure if the ack flag is true.

Thanks for reading and evaluating this suggestions.
McM1957

Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!

=> `This pointis discussed. the Adater smoothes acknowledged and not acknoledged values (in case of values out of some scripts the useres are asking me to smooth this not acknowledged values.
This is possible, because the Adapter dont write this values (ids), just read and safe timestamp.
If it will be writen from other sources with acknowledge = false and maybe 1ms later with false, there is no problem
caused of the timestamp it will be calculatet correctly`

**Comment by mcm1957** [comment]
RE-CHECK!

**Pull request merged**
