### PR TITLE
pegelalarm added to latest

### PR DESCRIPTION
**Pull request by simatec**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.pegelalarm](https://github.com/simatec/ioBroker.pegelalarm)
[Downloads](https://www.npmjs.com/package/iobroker.pegelalarm) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.pegelalarm/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.pegelalarm)!. Please execute in adapter directory: `npm owner add bluefox iobroker.pegelalarm`
- [ ] :eyes: [W400] Cannot find "pegelalarm" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by simatec** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.pegelalarm](https://github.com/simatec/ioBroker.pegelalarm)
[Downloads](https://www.npmjs.com/package/iobroker.pegelalarm) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.pegelalarm/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.pegelalarm)!. Please execute in adapter directory: `npm owner add bluefox iobroker.pegelalarm`
- [ ] :eyes: [W400] Cannot find "pegelalarm" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by simatec** [comment]
bluefox is added

**Comment by simatec** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.pegelalarm](https://github.com/simatec/ioBroker.pegelalarm)
[Downloads](https://www.npmjs.com/package/iobroker.pegelalarm) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.pegelalarm/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "pegelalarm" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by simatec** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.pegelalarm](https://github.com/simatec/ioBroker.pegelalarm)
[Downloads](https://www.npmjs.com/package/iobroker.pegelalarm) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.pegelalarm/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "pegelalarm" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hey, my review comments:
* why request AND axios is used? is request needed at all?
* admin deps should be better in "globalDependencies" unless oyu really need admin on same host
* if you do that global error catcching then most likely sentry will never report anything https://github.com/simatec/ioBroker.pegelalarm/blob/master/main.js#L66-L70
* please remove if not needed https://github.com/simatec/ioBroker.pegelalarm/blob/master/main.js#L92-L100 (and for schedule also most likely nonsens)
* there are several places where error handling could be enhanced :-) (e.g. https://github.com/simatec/ioBroker.pegelalarm/blob/master/main.js#L136-L142)
* if everything is strictly awaited and sich then https://github.com/simatec/ioBroker.pegelalarm/blob/master/main.js#L460-L476 should not be needed at all as a timeout ...

**Comment by simatec** [comment]
Thanks for your feedback. I fixed all of your comments in version 1.1.6

**Comment by simatec** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.pegelalarm](https://github.com/simatec/ioBroker.pegelalarm)
[Downloads](https://www.npmjs.com/package/iobroker.pegelalarm) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.pegelalarm/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "pegelalarm" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
