### PR TITLE
Update jeelink to 1.2.5

### PR DESCRIPTION
**Pull request by foxthefox**
Update to 1.2.5 as of the automatic whish

### CODE REVIEW

**Comment by mcm1957** [comment]
@foxthefox 
❗ [E606] Current adapter version 1.2.5 not found in [README.md](https://github.com/foxthefox/ioBroker.jeelink/blob/master/README.md)
Please fix README.md

Fix at GitHub is sufficient - no new Release is required.

**Comment by foxthefox** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
README has been fixed - THANKS

**Comment by mcm1957** [comment]
RE-CHECK!

**Pull request merged**
