### PR TITLE
Update adpater instalator

### PR DESCRIPTION
**Pull request by instalator**
starline
kodi
mercury
mclighting
mpd
foobar2000
lgtv-rs
sanext
haier
exchangerates
omnicomm-lls
synology
benq
mikrotik

### CODE REVIEW

**Comment by Apollon77** [comment]
Please fix https://travis-ci.org/github/ioBroker/ioBroker.repositories/builds/760540115#L1459

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by instalator** [comment]
> Please fix https://travis-ci.org/github/ioBroker/ioBroker.repositories/builds/760540115#L1459

fixed

**Pull request merged**
