### PR TITLE
added imap adapter

### PR DESCRIPTION
**Pull request by Lucky-ESA**
https://forum.iobroker.net/topic/63400/test-adapter-iobroker-imap-v0-0-1-github

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
sources-dist.json is INVALID.
Seems you have edited this file manually and forget a terminatin comma.

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.


- Readme.md should provide information about the adapter and its configuration

Please enhance Readme.md to include some description of the adapter and how it is configured. Links to extra files containing documentation are ok too - but those files should be located at github repository.

A link to a repository discussion only is not a sufficient documentation in my oppinion.

- consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval. Note that this is a suggestion only.
  
Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by Lucky-ESA** [comment]
> sources-dist.json is INVALID. Seems you have edited this file manually and forget a terminatin comma.
done

> Readme.md should provide information about the adapter and its configuration
done

> consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
done

RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by Lucky-ESA** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
automatic adapter checker faile due to invalid json at first commit.
manuel check is OK

[W400] Cannot find "imap" in latest repository

**Comment by Lucky-ESA** [comment]
1. OK, then we'll wait
2. This adapter has english description only.
3. I have a issue with @azure/msal-node [action](https://github.com/Lucky-ESA/ioBroker.imap/actions/runs/4869223471/jobs/8683484876) But I can remove this module.

**Comment by Apollon77** [comment]
1.) translating log lines is unusual and normally harder to maintain and "use" by the developr itself. Else no reason "against" it
2.) Completely ok, ideally just add the forum link without anygerman text so that also readme itself is en only, all ok
3.) yes nodejs 20 becomes lts in some months, so it migt be good to have tests run for it.

For me no reason against addition to repo.

Thank you @mcm1957 for the detailed look and @Lucky-ESA for your efforts!

**Pull request merged**
