### PR TITLE
add lg-thinq

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lg-thinq](https://github.com/TA2k/ioBroker.lg-thinq)
[Downloads](https://www.npmjs.com/package/iobroker.lg-thinq) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.lg-thinq/)

- [ ] :heavy_exclamation_mark: [E104] No common.title found in [io-package.json](https://github.com/TA2k/ioBroker.lg-thinq/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/TA2k/ioBroker.lg-thinq", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "lg-thinq" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lg-thinq](https://github.com/TA2k/ioBroker.lg-thinq)
[Downloads](https://www.npmjs.com/package/iobroker.lg-thinq) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.lg-thinq/)

- [ ] :heavy_exclamation_mark: [E104] No common.title found in [io-package.json](https://github.com/TA2k/ioBroker.lg-thinq/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/TA2k/ioBroker.lg-thinq", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "lg-thinq" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lg-thinq](https://github.com/TA2k/ioBroker.lg-thinq)
[Downloads](https://www.npmjs.com/package/iobroker.lg-thinq) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.lg-thinq/)

- [ ] :heavy_exclamation_mark: [E104] No common.title found in [io-package.json](https://github.com/TA2k/ioBroker.lg-thinq/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "lg-thinq" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lg-thinq](https://github.com/TA2k/ioBroker.lg-thinq)
[Downloads](https://www.npmjs.com/package/iobroker.lg-thinq) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.lg-thinq/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "lg-thinq" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

 some review comments:

* which such a construct you will not see if unload got called and e.g. in compact mode your code would run further, but the DB is gone after 500ms ... https://github.com/TA2k/ioBroker.lg-thinq/blob/master/main.js#L111 ... maybe add a check if unload was called? (and why the delay is needed?) same in https://github.com/TA2k/ioBroker.lg-thinq/blob/master/main.js#L238 ... or you need to adjust the "sleep" to that you can kill all the open sleep timeoiuts on unload!
* https://github.com/TA2k/ioBroker.lg-thinq/blob/master/main.js#L726-L737 ... thaat makes not tht much sense ... on each data run you update the object - also when just before was created? This is not very performant and also no best practice! especially makes no sense inside https://github.com/TA2k/ioBroker.lg-thinq/blob/master/main.js#L690 ... in this code the onbject always exists ... ?! Same later in the code ...

Please check and adjust

**Comment by TA2k** [comment]
Fixed both issue
Creation of objects happens only once on the initial load of the adapter

**Comment by Apollon77** [comment]
Please also release to npm

**Comment by TA2k** [comment]
done

**Pull request merged**
