### PR TITLE
Add hydrawise 0.2.8 to stable

### PR DESCRIPTION
**Pull request by SentiQ**

### CODE REVIEW

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

reminder 15.4.2024

**Comment by SentiQ** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
reminder 22.4.2024

**Comment by SentiQ** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Pull request merged**
