### PR TITLE
Zigbee 0.7.1

### PR DESCRIPTION
**Pull request by kirovilya**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
How can you shift latest and stable simultaneously? Is latest tested now by users?

**Comment by kirovilya** [comment]
ok i understood

**Comment by kirovilya** [comment]
Thanks for clarifying

**Comment by kirovilya** [comment]
@Apollon77 Little did not understand the last ...
What does "normally do not have a Version field" mean? Where it is not necessary to specify the version?

**Comment by kirovilya** [comment]
Ah! I understood. Removed version

**Comment by Apollon77** [comment]
"Little" was shitty Handy auto-correction ;-)

**Comment by kirovilya** [comment]
Thank you! :)

**Pull request merged**
