### PR TITLE
Add Zigbee adapter

### PR DESCRIPTION
**Pull request by kirovilya**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please add Test Script execution to package.json. Currently no tests are executed. Check tests afterwards please. 
And please add the license to io-package.json in common. 

You added Bluefox as npm owner for the package ?!

**Comment by kirovilya** [comment]
It is ok now?

> You added Bluefox as npm owner for the package ?!
yes

**Comment by Apollon77** [comment]
Thank you, I accept it, but you shoukd check the teste.
a nodejs 4.x test is failing - you could add strict mode to files or remove nodejs 4.x from tests :-) And testing (e.g. nodejs 8) shows an exception when adapter is stopped at the end...

**Comment by kirovilya** [comment]
Thank you! I will try to add support Node 4.x for internal parts...

**Pull request merged**
