### PR TITLE
Add new adapte serve

### PR DESCRIPTION
**Pull request by yaming116**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
image

**Comment by GermanBluefox** [comment]
image
Sorry. If you will not extend the description, It cannot be added.
抱歉。 如果您不扩展描述，则无法添加

**Comment by yaming116** [comment]
already added

**Comment by Apollon77** [comment]
Why you closed it?

**Comment by yaming116** [comment]
has bug,i am sorry

**Comment by Apollon77** [comment]
Ok, reopen or do a new one once fixed. good luck!! :-)

**Pull request closed without merging**
