### PR TITLE
release multicast

### PR DESCRIPTION
**Pull request by DutchmanNL**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please check https://adapter-check.iobroker.in/ for your adapter ...

**Comment by Apollon77** [comment]
* best also remove .vscode from github
* news do not contain 0.1.0 :-)

**Comment by DutchmanNL** [comment]
> https://adapter-check.iobroker.in/

all fixed,

Adapter check keeps complaining about Bluefox not being the owner, but commando succeeded : 

```
npm owner add bluefox iobroker.multicast
+ bluefox (iobroker.multicast)
```

Schermafbeelding 2019-08-09 om 16 07 29

adapter checker complains about raw image : 

[E125] External icon not found under URL: https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.multicast/master/admin/multicast.png

But its there and I can use the link

**Comment by DutchmanNL** [comment]
> * best also remove .vscode from github
> * news do not contain 0.1.0 :-)

fixed

**Comment by Apollon77** [comment]
welcome

**Pull request merged**
