### PR TITLE
Bump fuelpricemonitor to 0.3.5

### PR DESCRIPTION
**Pull request by HGlab01**
https://github.com/HGlab01/ioBroker.fuelpricemonitor/issues/544

### CODE REVIEW

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by HGlab01** [comment]
Nothing to be fixed in my point of view --> I do nit understand the label "must be fixed"

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Label has been set by first run where copyright year was too old. This has been fixed in the meantime.
So everything seems to be ok at the memoment.

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by HGlab01** [comment]
> Label has been set by first run where copyright year was too old. This has been fixed in the meantime.
> 
> [W505] setTimeout found in "main.js", but no clearTimeout detected should be investigated - I'll do a little bit later.

gone :-)

**Comment by HGlab01** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
0.3.5 created 07.07.2023
50 User (10%)
OK

**Pull request merged**
