### PR TITLE
Added Binance adapter to sources-dist.json

### PR DESCRIPTION
**Pull request by Kartax**

### CODE REVIEW

**Comment by Kartax** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.binance](https://github.com/Kartax/ioBroker.binance)
[Downloads](https://www.npmjs.com/package/iobroker.binance) 
[NPM](https://nodei.co/npm/iobroker.binance/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "binance" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Kartax** [comment]
@GermanBluefox I merged your pull request on my repository.

**Comment by Kartax** [comment]
@GermanBluefox @Apollon77 What is left for me to do in order to have the adapter added to the latest repository?

**Pull request merged**
