### PR TITLE
add nsclient to latest

### PR DESCRIPTION
**Pull request by mcm1957**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nsclient](https://github.com/iobroker-community-adapters/ioBroker.nsclient)
[Downloads](https://www.npmjs.com/package/iobroker.nsclient) 
[NPM](https://nodei.co/npm/iobroker.nsclient/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.nsclient/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "nsclient" in latest repository

### [ioBroker.tankerkoenig](https://github.com/Pix---/ioBroker.tankerkoenig)
[Downloads](https://www.npmjs.com/package/iobroker.tankerkoenig) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.tankerkoenig/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/package.json) (2.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.tankerkoenig) (2.1.1)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
@GermanBluefox 
Testresults refering to TANKERKÖNIG seem to be misplaced here. It's not my adapter nor can/will I dajust anything at tankerkoenig.

Just for info, maybe this Info is missing somewhere else.

**Comment by Apollon77** [comment]
Hi,

I only have one kind of "formal" ewview feedback:
* io-package native section should contain the default values, so in your case an empty "devs" array, or?

Beside this everything is good. I will merge. please add the devs: [] in next version,thank you

**Pull request merged**
