### PR TITLE
add valuetrackerovertime to latest

### PR DESCRIPTION
**Pull request by Omega236**
add valuetrackerovertime to latest

### CODE REVIEW

**Comment by Omega236** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.valuetrackerovertime](https://github.com/Omega236/ioBroker.valuetrackerovertime)
[Downloads](https://www.npmjs.com/package/iobroker.valuetrackerovertime) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.valuetrackerovertime/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 Omega236 <general.of.omega@googlemail.com>" at the end of [README.md](https://github.com/Omega236/ioBroker.valuetrackerovertime/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Omega236 <general.of.omega@googlemail.com>" at the start of LICENSE
- [ ] :eyes: [W400] Cannot find "valuetrackerovertime" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@Omega236 please adjust the things mentioned by comment above

**Comment by Omega236** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.valuetrackerovertime](https://github.com/Omega236/ioBroker.valuetrackerovertime)
[Downloads](https://www.npmjs.com/package/iobroker.valuetrackerovertime) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.valuetrackerovertime/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "valuetrackerovertime" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Omega236** [comment]
was muss ich tun, damit es übernommen wird?

**Comment by Apollon77** [comment]
Wir müssen für den Review Zeit finden, etwas geduld bitte

**Comment by Apollon77** [comment]
Hello, some review comments:
* the news should be provided in some more languages. See the Readme of the repo in best practices for a link to an translation tool
* please adjust the adaptertype (io-package and repo) to "misc-data". I think this matches better then "storage"
* Idea: instead of hard coding sql.0 as history instance why not leave it empty and use the default history instance from system config?
* you need to stop all the crons in your "unload" method
* https://github.com/Omega236/ioBroker.valuetrackerovertime/blob/master/main.js#L177 ... i think it is better to use isNan()
* please use an getObjectView to get all objects with a custom setting instead of https://github.com/Omega236/ioBroker.valuetrackerovertime/blob/master/main.js#L195 ... check history/sql/influxdb adapters how they do that

Thank you for checking  and adjusting it.

**Comment by Omega236** [comment]
>     * Idea: instead of hard coding sql.0 as history instance why not leave it empty and use the default history instance from system config?

Irgenwie finde ich nicht raus wie ich darauf zugreife. Und ich kenne auf Anhieb auch keinen adapter der dies verwendet außer flot und da verstehe ich es nicht.

**Comment by Apollon77** [comment]
Am Ende machst du ein "getObject('system.config')" (bzw Async und so ..) und da ist es common.defaultHistory

**Comment by Omega236** [comment]
So Version 0.6.0 hat alle Anpassungen

- [x] the news should be provided in some more languages. See the Readme of the repo in best practices for a link to an translation tool
    
- [x] please adjust the adaptertype (io-package and repo) to "misc-data". I think this matches better then "storage"

- [x] Idea: instead of hard coding sql.0 as history instance why not leave it empty and use the default history instance from system config?

- [x] you need to stop all the crons in your "unload" method

- [ ] ~~https://github.com/Omega236/ioBroker.valuetrackerovertime/blob/master/main.js#L177 ... i think it is better to use isNan()~~
    Ich finde dadurch wird der Code schlechter lesbar

- [x]   please use an getObjectView to get all objects with a custom setting instead of https://github.com/Omega236/ioBroker.valuetrackerovertime/blob/master/main.js#L195 ... check history/sql/influxdb adapters how they do that

**Comment by Omega236** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.valuetrackerovertime](https://github.com/Omega236/ioBroker.valuetrackerovertime)
[Downloads](https://www.npmjs.com/package/iobroker.valuetrackerovertime) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.valuetrackerovertime/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "valuetrackerovertime" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hey, thank you,

BTW https://github.com/Omega236/ioBroker.valuetrackerovertime/blob/a82ef0f5d13b9c14ca29a24e80fccafb717ff52e/main.js#L149-L150 is not needed ...

**Pull request merged**
