### PR TITLE
add nina to repo and update stable for homeconnect and nightscout

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please add "published" for the stable entries ... nightscout is already in latest?

**Comment by TA2k** [comment]
I added.
Yes it is. 
Nina is not yet in latest. But test very well:
https://forum.iobroker.net/topic/23866/aufruf-nina-gefahrenmeldung-adapter

**Comment by GermanBluefox** [comment]
@TA2k I just working on integration of nightscout (as server) into ioBroker.
Your nightscout adapter is just collects a couple of values via socket.io.
My nightscout will start the nightscout server and it will be possible to collect sugar measures via iot cloud.
Can I take your name for nightscout and you will rename your adapter into nightscout-client ?

**Comment by TA2k** [comment]
Of course i will rename the adapter

**Comment by GermanBluefox** [comment]
> Now before merging in stable?

Of course before.

**Comment by TA2k** [comment]
ok nightscout is removed it is only nina and a update for homeconnect

**Pull request merged**
