### PR TITLE
Add govee-app to latest

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.govee-app](https://github.com/TA2k/ioBroker.govee-app)
[Downloads](https://www.npmjs.com/package/iobroker.govee-app) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.govee-app/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.govee-app)!. Please execute in adapter directory: `npm owner add bluefox iobroker.govee-app`
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "govee-app" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
@TA2k 
Please state whether https://github.com/ioBroker/AdapterRequests/issues/510will be solved with this adapter - of if this is some different device / unit / requirement.

**Comment by TA2k** [comment]
Solved by this adapter
The original iobroker.govee adapter is not developed anymore

**Comment by mcm1957** [comment]
Thanks for the info and your work.
I switched state of adapetr reqeust and will close ist as soon as the adapter is available at latest repo.

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- please fix issues reported by adapter checker
  
  - add bluefox to npm if not already done
  - add missing title for uk

- Readme.md should be written in pure english

  As ioBroker is an international software supporting several languages the main Readme.md file should be written in english. Its ok to add additional Readme-xxx.mds of course.
  
- Readme.md contains multiple languages
  
  Please remove the german version / all non english versions from Readme.md because Readme.md gets automatically translated and this will not work with multiple languages within Readme.md. You can add locatlized Readme pages in (docs/de and docs/en) like https://github.com/iobroker-community-adapters/ioBroker.pvforecast/tree/main/docs and add it to io-package (see https://github.com/iobroker-community-adapters/ioBroker.pvforecast/blob/main/io-package.json#L119-L122)
  
- jsonConfig.json missing uk

  jsonConfig.jsosn seems to be missing translations fpr uk. Please add uk or use i18n environment an translate to all languages using npm run tranbslate tool.

- consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- sleep utility

  Time used at sleep routine seem to be missing from cleanup at onUnload. 
  In addtion I suggest to use the delay functionality provided by iobroker package instead of own sleep:
```
    /**
     * delays the fulfillment of the promise the amount of time.
     * it will not fulfill during and after adapter shutdown
     *
     * @param timeout - timeout in milliseconds
     * @returns promise when timeout is over
     */
```
- check reLoginTimeout, refreshTokenTimeout 

  these timeouts are cleared at onUnload but seem to be unused

  
- This adapter seems to use sentry, but no sentry info is added to Readme.md
  
  This adapter seems to use sentry for error logging as the sentry plkugin is configured at io-package.json. Please add the suggested sentry information at the top of Readme.md
  
  ```**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0.```
  
  
Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.govee-app](https://github.com/TA2k/ioBroker.govee-app)
[Downloads](https://www.npmjs.com/package/iobroker.govee-app) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.govee-app/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "govee-app" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
I includes the comments.
Please ensure create adapter is also creating uk translation and the types are fixe before demand it in the review
image

I will not change the readme.md Because it means for me more support effort because 90% of the user are German speaking and misunderstandings means for me more work.

The auto translation of iobroker is really bad and nobody is able to find the translated readme or separate added documentations

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.govee-app](https://github.com/TA2k/ioBroker.govee-app)
[Downloads](https://www.npmjs.com/package/iobroker.govee-app) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.govee-app/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "govee-app" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
Please remove node 14 from test-and-release.yml and (optionally) add node 20 to testing matrix.
Node 14 is no longer supported and tests will fail since 22.5.2023.

Thanks
McM1957

**Comment by mcm1957** [comment]
@TA2k 
If this PR has been closed on error, please open a new one.

**Pull request closed without merging**
