### PR TITLE
Updating MieleCloudService in Stable to V1.1.0

### PR DESCRIPTION
**Pull request by Grizzelbee**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
hm ... no travis testing anymore since 10.3.?

**Comment by Grizzelbee** [comment]
@Apollon77 
> hm ... no travis testing anymore since 10.3.?

yeah. Since there wasn't very much development in the past ten days.
Is there any problem with that?

**Comment by Apollon77** [comment]
Just wondering because there are commits after that in your project ... and they had no travis checkmark

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mielecloudservice](https://github.com/Grizzelbee/ioBroker.mielecloudservice)
[Downloads](https://www.npmjs.com/package/iobroker.mielecloudservice) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mielecloudservice/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Grizzelbee/ioBroker.mielecloudservice) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
