### PR TITLE
Added go-e for Hardware go-eCharger

### PR DESCRIPTION
**Pull request by MK-2001**
Added an adapter for go-e for the hardware go-eCharger.
Similar to #852 / #853.
But with no error in the checking tools of ioBroker.

### CODE REVIEW

**Comment by MK-2001** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.go-e](https://github.com/MK-2001/ioBroker.go-e)
[Downloads](https://www.npmjs.com/package/iobroker.go-e) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.go-e/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "go-e" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
I could see 111 variables here (https://github.com/MK-2001/ioBroker.go-e/blob/master/main.js#L199) that ALL will be set in parallel.
I suggest max 10 variables in parallel. Please use async/await or write them in serial.

**Comment by MK-2001** [comment]
Should be fixed with this PR to Version 0.0.5 https://github.com/MK-2001/ioBroker.go-e/pull/7

**Comment by MK-2001** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.go-e](https://github.com/MK-2001/ioBroker.go-e)
[Downloads](https://www.npmjs.com/package/iobroker.go-e) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.go-e/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "go-e" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by MK-2001** [comment]
@GermanBluefox I just tried to handle a limit of parallel updated with commit. Is this also working? 3b9e99ea317ee899d53cd1e61c987390e9f303fe

**Comment by GermanBluefox** [comment]
> @GermanBluefox I just tried to handle a limit of parallel updated with commit. Is this also working? https://github.com/MK-2001/ioBroker.go-e/commit/3b9e99ea317ee899d53cd1e61c987390e9f303fe

Interesting solution. Yes it should work.

**Pull request merged**
