### PR TITLE
Add new version of iobroker.apcups

### PR DESCRIPTION
**Pull request by XHunter74**

### CODE REVIEW

**Comment by Apollon77** [comment]
Really a new stable version 1h after release ;-) Normally stable versions stay in latest untill thes are proofed some days by users and got some installations ... or is that an important bugfix?

**Comment by XHunter74** [comment]
Just bug fixing that should not impact functionality.

**Comment by Apollon77** [comment]
Ok I merge now, but in the future please give new versions some days in Beta/Latest before pushing to stable ( and you do not wanna hear all own/other stories how "should not" can be wrong ;-)

**Comment by XHunter74** [comment]
Ok, this moment of publishing flow was not clear to me.

**Pull request merged**
