### PR TITLE
Add Bluelink Adapter (for Hyundai and Kia vehicle)

### PR DESCRIPTION
**Pull request by Newan**
Request from: https://github.com/ioBroker/AdapterRequests/issues/403

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

:thumbsup: No errors found

### [ioBroker.easee](https://github.com/Newan/ioBroker.easee)
[Downloads](https://www.npmjs.com/package/iobroker.easee) 
[NPM](https://nodei.co/npm/iobroker.easee/)

:thumbsup: No errors found

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

:thumbsup: No errors found

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Morluktom <strassertom@gmx.de>" at the start of LICENSE

### [ioBroker.bluelink](https://github.com/Newan/ioBroker.bluelink)
[Downloads](https://www.npmjs.com/package/iobroker.bluelink) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.bluelink/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 1.0.1
- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.bluelink)!. Please execute in adapter directory: `npm owner add bluefox iobroker.bluelink`
- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/Newan/ioBroker.bluelink/blob/master/iob_npm.done)" found in repo! Please add it to .gitignore
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/Newan/ioBroker.bluelink", press the settings button beside the about title and add some topics.
- [ ] :heavy_exclamation_mark: [E914] file iob_npm.done found in repository, but not found in .gitignore
- [ ] :eyes: [W400] Cannot find "bluelink" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Newan** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.bluelink](https://github.com/Newan/ioBroker.bluelink)
[Downloads](https://www.npmjs.com/package/iobroker.bluelink) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.bluelink/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.bluelink)!. Please execute in adapter directory: `npm owner add bluefox iobroker.bluelink`
- [ ] :eyes: [W400] Cannot find "bluelink" in latest repository

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

:thumbsup: No errors found

### [ioBroker.easee](https://github.com/Newan/ioBroker.easee)
[Downloads](https://www.npmjs.com/package/iobroker.easee) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.easee/)

- [ ] :heavy_exclamation_mark: [E504] "main.js found in [package.json](https://github.com/Newan/ioBroker.easee/blob/master/package.json), but not found as file

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

:thumbsup: No errors found

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Morluktom <strassertom@gmx.de>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by Newan** [comment]
image

Add it manuell:
image

**Comment by Newan** [comment]
Please see my comment. I don't know how can fixed this?

**Comment by Apollon77** [comment]
All good, sometimes the check has false positives

**Comment by Newan** [comment]
> All good, sometimes the check has false positives

what needs to be fixed?

**Comment by Apollon77** [comment]
Hi @Newan,

welcome in the repository, butp please add some more infos in Readme about adapter and what it can do and pot important config infos

Thank you!

**Comment by Apollon77** [comment]
PS: Merge waits for easee check because combined

**Comment by Apollon77** [comment]
already merged

**Pull request closed without merging**
