### PR TITLE
add icons-freepic to latest

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jogibear9988** [comment]
RE-CHECK!

**Comment by jogibear9988** [comment]
E118 is wrong... the versions are the same

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- [ ] Readme.md should contain a link to the original location of the icons 

  The README.md should contain a reference link to the original place where the author of the icons has published them. If there is no such place, please state this and add a reference to the location those icons have been copied from.

- [ ] Readme.md should contain a reference to the original license

   Please add a link to the original license the icons have been published with by the authgor and check whether this license is compatible with the MIT license used at this adapter. If no link is possible, please indicate how you verified the license to meet MIT, i.e. by pointing to some document or webseites which explicitly allow public use of these icons withoiut further restrictions.

- [ ] add credits

  Even if not required by original author some credit section to state who (person, organisation, ...) has been created the icons and has allowed public use whould be appropiate (in my oppinion).
  
- [ ] package.json contains invalid main attribute
  ```"main": "README.md",```
  The main field is a module ID that is the primary entry point to your program. README.md is for sure no java script module.
  Please remove the incorrect and unused parameter.

  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
@Apollon77 
Please check especially the license situation. (Maybe ist all ok anyway but witghout a clear reference to an original license I cannot decide)

**Comment by jogibear9988** [comment]
the licences of this one are complexer... don't know exactly what they are... but we already deliver the icons in habpanel.

**Comment by mcm1957** [comment]
@Apollon77 - please chcke if licensing is OK

**Comment by mcm1957** [comment]
@Apollon77 - ping, this adapter is waiting for a review by you

**Pull request merged**
