### PR TITLE
conflict resolved

### PR DESCRIPTION
**Pull request by AWhiteKnight**

### CODE REVIEW

**Comment by Apollon77** [comment]
Is this release an impotant bugfix or why bring to stable that fast after releaseß ONly 2 installations use this version

**Comment by AWhiteKnight** [comment]
It is a fix for #24 reducing the amount of messages by more than 50%

**Comment by Apollon77** [comment]
Ok, then no problem ... should I merge it?

**Comment by AWhiteKnight** [comment]
Yes please :-)

**Pull request merged**
