### PR TITLE
Bump Tado to 0.4.11

### PR DESCRIPTION
**Pull request by HGlab01**

### CODE REVIEW

**Comment by mcm1957** [comment]
0.4.11 created 09.10.2023
72 user
OK

**Comment by mcm1957** [comment]
@HGlab01 
Please fix ad least sentry issue:

- [ ] This adapter seems to use sentry, but no sentry info is added to Readme.md
  
  This adapter seems to use sentry for error logging. Please add the suggested sentry information at the top of Readme.md
  
  ```**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0.```
  
- [ ] Readme.md should contain a link to the manufacturer and/or device (**non blocking** but could be solved at once)

  The README.md of any adapter related to device or m ultiple devices of a manufacturer should contain a link the manufacturers website and/or to a description of the device. This is to anable new users to easily check wether they associate the adapter with the correct device(s). (See https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository paragraph 4.)

**Comment by HGlab01** [comment]
@mcm1957 thanks, sentry info gots lost somewhen/somehow. Link added as well

**Comment by mcm1957** [comment]
0.4.11 created 09.10.2023
88 user
OK

**Pull request merged**
