### PR TITLE
Update rct to 1.2.7

### PR DESCRIPTION
**Pull request by NCIceWolf**
Please update stable version of ioBroker.rct from 1.2.4 to 1.2.7

Changelog:
1.2.7 (2024-05-05)
(Andreas Ruttkamp) prim_sm.state added
(NCIceWolf) handling of type errors added
(Andreas Ruttkamp) some Code cleaning
(NCIceWolf) Update io-package.json

1.2.6 (2024-05-03)
(Andreas Ruttkamp) unused parameter deleted

1.2.5 (2024-05-02)
(Andreas Ruttkamp) misspelling in rct_core2 corrected 
(Andreas Ruttkamp) Missing ack:true added
(Andreas Ruttkamp) datatypes corrected
(NCIceWolf) changes to correct loosing connection

### CODE REVIEW

**Comment by mcm1957** [comment]
@aruttkamp 
Is this update requested by you? 
Did you authorize @NCIceWolf to request an update?

**Comment by aruttkamp** [comment]
@mcm1957 
>Is this update requested by you?
No
I think we should wait minimum 7 days. Actually its 2 days old and we have no issues ....

**Comment by mcm1957** [comment]
OK, 1 week minimum time at latest will be enforced by me anyway unless there is not hot-fix requested. See tagging.

The main goal of my comment was to check whether this PR is authorized by you as the repoowner differs from issuer of PR and this repo is not part of a organization. If I read your answer correctly this PR has not been dsicussed before creation. As it is a little bit early too **I will close it for now. Please create a new PR as soon as you think your version is ready for stable.**

**Comment by NCIceWolf** [comment]
Hey guys!
Wasn't my intention to cause any misunderstandings here, I believed this PR to reach @aruttkamp for approval anyway.
I did not flag it as hot fix, yet it practically is one.
Version 1.2.4 has communication issues with the inverter since the vendor changed something on their end on 24.04.2024, so a version >1.2.4 is needed for correct operation.
I just wanted to make sure all “stable-users” get this fix rather sooner than later.

**Comment by mcm1957** [comment]
Hi, @NCIceWolf ,
thanks for feedback. And MANY THANKS for working at an adapter usn supporting ioBroker.

From time to time some users request repository updates although they are not involved in the adapter development. This is most likely done with very good targets, but releasing should be controlled by maintainers only. So I always ask the repo owner / known maintainer to confirm if such a request is ok, espscially if the requesting user is new. I do not have the possibility to check access rights at foreign repositories so I cannot check if a user requesing a PR has at least write access or een admin acccess to a repo. Sorry if this blocks sometimes. And thats absolutly no critic at you. In opposite: Thanks for helping and supporting.

If an urgent update is required due to changes at provider site this is classic reason for a hotfix / fast lane request. I tried to reopen this PR but the repo behind this PR was already deleted so I cannot do this anymore.

**@aruttkamp 
Please create a PR as soon as you want a newer version be released to stable (or comment her, then I can do this too if you temporary do not have access to a system to do so.**

**Comment by aruttkamp** [comment]
@mcm1957 
PR #3592 created.

**Pull request closed without merging**
