### PR TITLE
add Heizoel adapter

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.psa](https://github.com/TA2k/ioBroker.psa)
[Downloads](https://www.npmjs.com/package/iobroker.psa) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.psa/)

:thumbsup: No errors found

### [ioBroker.heizoel](https://github.com/TA2k/ioBroker.heizoel)
[Downloads](https://www.npmjs.com/package/iobroker.heizoel) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.heizoel/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.heizoel)!. Please execute in adapter directory: `npm owner add bluefox iobroker.heizoel`
- [ ] :eyes: [W400] Cannot find "heizoel" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.psa](https://github.com/TA2k/ioBroker.psa)
[Downloads](https://www.npmjs.com/package/iobroker.psa) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.psa/)

:thumbsup: No errors found

### [ioBroker.heizoel](https://github.com/TA2k/ioBroker.heizoel)
[Downloads](https://www.npmjs.com/package/iobroker.heizoel) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.heizoel/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.heizoel)!. Please execute in adapter directory: `npm owner add bluefox iobroker.heizoel`
- [ ] :eyes: [W400] Cannot find "heizoel" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

some comments:
* axios dep twice? https://github.com/TA2k/ioBroker.heizoel/blob/master/package.json#L33
* really type metering? What it is metering? I would more say misc-data or such
* I think you know my usual "do not use Intervals when doing external communication because can have side effects on timout issues or such ... ;-))
* does it really make sense to update heizöl prices every 30s? That adapter feels better as scheduled one in my eyes ... or?

Rest ok basically ... What do you think?

**Comment by TA2k** [comment]
removed axios from devdep
change to misc-data
set minimum to 30min. Maybe scheduled is better but I don't think the different is not so much

**Comment by Apollon77** [comment]
> Maybe scheduled is better but I don't think the different is not so much

The difference are roughly 30-50MB RAM usage on the host ...

**Comment by TA2k** [comment]
But you need every 30min the 30-50mb anyway?

**Comment by Apollon77** [comment]
Yes for some seconds :-) But hey up to you ... I just tell my personal opinion ... no blocker for repo.

Please adjust the type also here in PR, then we are ready to go

**Comment by TA2k** [comment]
changed type

**Pull request merged**
