### PR TITLE
new adapter smartgarden

### PR DESCRIPTION
**Pull request by jpgorganizer**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.smartgarden](https://github.com/jpgorganizer/ioBroker.smartgarden)
[Downloads](https://www.npmjs.com/package/iobroker.smartgarden) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.smartgarden/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "smartgarden" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jpgorganizer** [comment]
I don't understand ... is there something I should do now?

**Comment by jpgorganizer** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.smartgarden](https://github.com/jpgorganizer/ioBroker.smartgarden)
[Downloads](https://www.npmjs.com/package/iobroker.smartgarden) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.smartgarden/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.smartgarden)!. Please execute in adapter directory: `npm owner add bluefox iobroker.smartgarden`
- [ ] :eyes: [W400] Cannot find "smartgarden" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jpgorganizer** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.smartgarden](https://github.com/jpgorganizer/ioBroker.smartgarden)
[Downloads](https://www.npmjs.com/package/iobroker.smartgarden) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.smartgarden/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.smartgarden)!. Please execute in adapter directory: `npm owner add bluefox iobroker.smartgarden`
- [ ] :eyes: [W400] Cannot find "smartgarden" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jpgorganizer** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.smartgarden](https://github.com/jpgorganizer/ioBroker.smartgarden)
[Downloads](https://www.npmjs.com/package/iobroker.smartgarden) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.smartgarden/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.smartgarden)!. Please execute in adapter directory: `npm owner add bluefox iobroker.smartgarden`
- [ ] :eyes: [W400] Cannot find "smartgarden" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jpgorganizer** [comment]
I added Bluefox to NPM. The adapter check still brings the error. What should be done? 

See also https://forum.iobroker.net/topic/33168/e201-bluefox-was-not-found-in-the-collaborators-on-npm

**Comment by Apollon77** [comment]
Everything ok, seems to be a false positive.

**Comment by jpgorganizer** [comment]
what is the further process? waiting for ???

**Comment by Apollon77** [comment]
> waiting for ???
me to find time for a short code review :-)

**Comment by jpgorganizer** [comment]
> 
> 
> Needed:
> 
>     * [ConnectionType](https://github.com/ioBroker/ioBroker.repositories#connection-types) is missing

mmh, I can see it
grafik

**Comment by jpgorganizer** [comment]
> 
> 
> @jpgorganizer some comments:
> 
>     * please remove on-object-change if not needed
> 
>     * All Timeouts or Intervals used needs to be cleared on "unload". The api.js uses timouts that are ot cleared ... (just had a short look). Else comact mode will break!

done, please review again.
Thanks for the hints.

**Pull request merged**
