### PR TITLE
add sonnen-charger to latest

### PR DESCRIPTION
**Pull request by ChrisWbb**
https://github.com/ChrisWbb/ioBroker.sonnen-charger

### CODE REVIEW

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- Readme.md is very short

  If you have some spare time, please consider adding some more infos to readme, especially a clear description what device(s) this adapter is for. Add a link to the manufactorers website i.e. Also a short description what kind of information / manipulation is possible.

  If some documentation is useful for users add it to Readme.md or create a description below docs directory and ass a link to Readme.md.

- Field _id:chargerSettings.serialNumber seems to be duplicated at io-package.json
  https://github.com/ChrisWbb/ioBroker.sonnen-charger/blob/main/io-package.json#L168
  https://github.com/ChrisWbb/ioBroker.sonnen-charger/blob/main/io-package.json#L181

- Check onStateChange handling
  It looks like your onStateChange code does not respect the ack flag.
  Normally Adaptercode should only react on state changes issued with ack=false and ignore state changes with ack=true as long as it does not want to react on vales set by other adapters etc. Users should enter commands / set states with ack=false.
  See https://forum.iobroker.net/topic/61876/best%C3%A4tigt-acknowledged-flag-bedeutung-ein-mysterium?_=1680075857780 and eventually discuss this with @Apollon77 

- consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on onLoad. Additional checks on those limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.
  
Thanks for reading and evaluating these suggestions.
McM1957

**Comment by GioElCapitano98** [comment]
Hello,
i want to test the adapter for the sonnen charger too.
But i dont't find the adapter in iobroker.
where can i download the adapter and how can i install the sonnen charger adapter on the rpi 4 / iobroker ?

**Comment by mcm1957** [comment]
Adapter repository: https://github.com/ChrisWbb/ioBroker.sonnen-charger

Currently only available via github installation in expert mode.
Thios adapter is not yet release as stable in repositories.
If you need further Instructions please ask at forum (forum.iobroker.net) or contact developer via adapter repository.
This PR is not the place to discuss adapter usage, issues or feature requests.

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sonnen-charger](https://github.com/ChrisWbb/ioBroker.sonnen-charger)
[Downloads](https://www.npmjs.com/package/iobroker.sonnen-charger) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sonnen-charger/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "sonnen-charger" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
@ChrisWbb 
You entered the following url at sourced-dist.json:
"icon": "https://raw.githubusercontent.com/ChrisWbb/ioBroker.sonnen-charger/master/admin/sonnen.png",

But the file is named sonnen-charger.png - at least now.

Please correct PR

**Comment by mcm1957** [comment]
"sonnen-charger": {
    "meta": "https://raw.githubusercontent.com/ChrisWbb/ioBroker.sonnen-charger/master/io-package.json",
    "icon": "https://raw.githubusercontent.com/ChrisWbb/ioBroker.sonnen-charger/master/admin/sonnen.png",    **<<< wrong filename**
    "type": "energy"
  },  

@ChrisWbb - please fix PR, filename is OK as the picture normally is named identical to adapter

**Comment by Apollon77** [comment]
@mcm1957 But the image naming is no requirement and also not really a best practice ... no need to enforce that. so This is ok fpr me

**Comment by mcm1957** [comment]
> @mcm1957 But the image naming is no requirement and also not really a best practice ... no need to enforce that. so This is ok fpr me

@Apollon77 
I noticed that the icon url points to a non existing file. So EITHER the PR / icon url OR the filename need to be corrected. 
This causes the github checks to fail (see screenshot) - so I think this must be corrected. It not about the name itself - it might by xtzrcs6if453hjc.jpg too as long as the url point to this file.

image

Or is this statement incorrect too? In this case sorry for the statements.
McM1957

**Comment by Apollon77** [comment]
This statement is meaning that the UR is wrong completely ... and the file is not there. 

SO yes it needs to be changed to https://raw.githubusercontent.com/ChrisWbb/ioBroker.sonnen-charger/master/admin/sonnen-charger.png ... but not because the file needs to be named like the adapter ... but because the file was not there because it was an copy/paste error :-)

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sonnen-charger](https://github.com/ChrisWbb/ioBroker.sonnen-charger)
[Downloads](https://www.npmjs.com/package/iobroker.sonnen-charger) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sonnen-charger/)

:thumbsup: No errors found
- [ ] :eyes: [W202] Version of [package.json](https://github.com/ChrisWbb/ioBroker.sonnen-charger/blob/master/package.json) (1.1.1) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.sonnen-charger) (1.1.0)
- [ ] :eyes: [W400] Cannot find "sonnen-charger" in latest repository

### [ioBroker.frontier_silicon](https://github.com/iobroker-community-adapters/ioBroker.frontier_silicon)
[Downloads](https://www.npmjs.com/package/iobroker.frontier_silicon) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.frontier_silicon/)

:thumbsup: No errors found

### [ioBroker.logparser](https://github.com/iobroker-community-adapters/ioBroker.logparser)
[Downloads](https://www.npmjs.com/package/iobroker.logparser) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.logparser/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.logparser/blob/master/io-package.json)


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sonnen-charger](https://github.com/ChrisWbb/ioBroker.sonnen-charger)
[Downloads](https://www.npmjs.com/package/iobroker.sonnen-charger) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sonnen-charger/)

:thumbsup: No errors found
- [ ] :eyes: [W202] Version of [package.json](https://github.com/ChrisWbb/ioBroker.sonnen-charger/blob/master/package.json) (1.1.1) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.sonnen-charger) (1.1.0)
- [ ] :eyes: [W400] Cannot find "sonnen-charger" in latest repository

### [ioBroker.comfoair](https://github.com/iobroker-community-adapters/ioBroker.comfoair)
[Downloads](https://www.npmjs.com/package/iobroker.comfoair) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.comfoair/)

:thumbsup: No errors found
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.frontier_silicon](https://github.com/iobroker-community-adapters/ioBroker.frontier_silicon)
[Downloads](https://www.npmjs.com/package/iobroker.frontier_silicon) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.frontier_silicon/)

:thumbsup: No errors found

### [ioBroker.go-e](https://github.com/MK-2001/ioBroker.go-e)
[Downloads](https://www.npmjs.com/package/iobroker.go-e) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.go-e/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/io-package.json). Must be removed.
- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/MK-2001/ioBroker.go-e/main/
- [ ] :heavy_exclamation_mark: [E407] Meta URL (latest) must be equal to https://raw.githubusercontent.com/MK-2001/ioBroker.go-e/main/io-package.json
- [ ] :heavy_exclamation_mark: [E426] Icon (stable) must be in the following path: https://raw.githubusercontent.com/MK-2001/ioBroker.go-e/main/
- [ ] :heavy_exclamation_mark: [E428] Meta URL (stable) must be equal to https://raw.githubusercontent.com/MK-2001/ioBroker.go-e/main/io-package.json
- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/MK-2001/ioBroker.go-e/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)

### [ioBroker.hm-rega](https://github.com/ioBroker/ioBroker.hm-rega)
[Downloads](https://www.npmjs.com/package/iobroker.hm-rega) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.hm-rega/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/ioBroker/ioBroker.hm-rega/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.homekit-controller](https://github.com/Apollon77/ioBroker.homekit-controller)
[Downloads](https://www.npmjs.com/package/iobroker.homekit-controller) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.homekit-controller/)

- [ ] :heavy_exclamation_mark: [E142] logo is too big. It must be less or equal than 512x512
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.homekit-controller)!. Please execute in adapter directory: `npm owner add bluefox iobroker.homekit-controller`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Apollon77/ioBroker.homekit-controller/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.kostal-piko-ba](https://github.com/hombach/ioBroker.kostal-piko-ba)
[Downloads](https://www.npmjs.com/package/iobroker.kostal-piko-ba) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.kostal-piko-ba/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI

### [ioBroker.logparser](https://github.com/iobroker-community-adapters/ioBroker.logparser)
[Downloads](https://www.npmjs.com/package/iobroker.logparser) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.logparser/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.logparser/blob/master/io-package.json)

### [ioBroker.loxone](https://github.com/UncleSamSwiss/ioBroker.loxone)
[Downloads](https://www.npmjs.com/package/iobroker.loxone) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.loxone/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/UncleSamSwiss/ioBroker.loxone/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)

### [ioBroker.meteoalarm](https://github.com/jack-blackson/ioBroker.meteoalarm)
[Downloads](https://www.npmjs.com/package/iobroker.meteoalarm) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.meteoalarm/)

- [ ] :heavy_exclamation_mark: [E606] Current adapter version 2.3.5 not found in [README.md](https://github.com/jack-blackson/ioBroker.meteoalarm/blob/master/README.md)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.puppeteer](https://github.com/foxriver76/ioBroker.puppeteer)
[Downloads](https://www.npmjs.com/package/iobroker.puppeteer) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.puppeteer/)

- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.puppeteer)!. Please execute in adapter directory: `npm owner add bluefox iobroker.puppeteer`
- [ ] :heavy_exclamation_mark: [E518] "@alcalzone/release-script" is used, but ".releaseconfig.json" not found
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2023 Moritz Heusinger <moritz.heusinger@gmail.com>" at the end of [README.md](https://github.com/foxriver76/ioBroker.puppeteer/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 Moritz Heusinger <moritz.heusinger@gmail.com>" at the start of LICENSE
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/foxriver76/ioBroker.puppeteer/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)

### [ioBroker.solarmanpv](https://github.com/raschy/ioBroker.solarmanpv)
[Downloads](https://www.npmjs.com/package/iobroker.solarmanpv) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.solarmanpv/)

:thumbsup: No errors found

### [ioBroker.statistics](https://github.com/iobroker-community-adapters/ioBroker.statistics)
[Downloads](https://www.npmjs.com/package/iobroker.statistics) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.statistics/)

:thumbsup: No errors found
- [ ] :eyes: [W202] Version of [package.json](https://github.com/iobroker-community-adapters/ioBroker.statistics/blob/master/package.json) (2.3.1) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.statistics) (2.3.0)

### [ioBroker.vds2465-server](https://github.com/Hirsch-DE/ioBroker.vds2465-server)
[Downloads](https://www.npmjs.com/package/iobroker.vds2465-server) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vds2465-server/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.vds2465-server)!. Please execute in adapter directory: `npm owner add bluefox iobroker.vds2465-server`
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2023 Hirsch-DE <github731@hirschfeldonline.de>" at the end of [README.md](https://github.com/Hirsch-DE/ioBroker.vds2465-server/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 Hirsch-DE <github731@hirschfeldonline.de>" at the start of LICENSE
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W515] Why you decided to disable i18n support?
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.vis](https://github.com/ioBroker/ioBroker.vis)
[Downloads](https://www.npmjs.com/package/iobroker.vis) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/ioBroker/ioBroker.vis/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/ioBroker/ioBroker.vis/blob/master/package.json) (2.0.29) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.vis) (1.4.16)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
I would like to give some additional (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.
  
- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  As an example customMaxCurrent currently has role "indoicator" set. As this state is of type number and has a unit "A" assigned, this state seems to contain a value. So role value.current seesm to be appropiate. "numberOfPhases" is quite sure no indicator either. States with role indicator must have type boolen.

  Please review roles. Those are i.e. used by tapyedetector and vis ans should match standards.

- [ ] adapt testing to supported node releases

  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x],

Everything looks good to me.

Thanks for reading and evaluating this suggestions and sorry for the late / addition remarks. Please fix and/or comment I'll set the request to lgtm so that Apollon77 will continue asap.

McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
How shall we continue?
Please let us know if you plan zu fix the noted issues in the near future - or as an alterntive - like to discuss some / all of those points.

**Comment by ChrisWbb** [comment]
@mcm1957 : thanks for your review. I fixed your findings.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@ChrisWbb 

Looks goog now.

**Please note that release 1.1.1 has not yet been published at npm**

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter <name> <version>" to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

**Note: If an other testing topic already exists, ist OK to continue using this topic too.**

**Pull request merged**
