### PR TITLE
added dingz adapter

### PR DESCRIPTION
**Pull request by rgwch**
Adapter for the  <http://dingz.ch> smart buttons. 
The adapterchecker https://adapter-check.iobroker.in/ keeps on complaining "not found in travis" even though travis passes perfectly. i can't do anything more about it. So if you like it, take it, if not, leave it.

### CODE REVIEW

**Comment by rgwch** [comment]
Added adapter for [MyStrom Wifi Button](https://mystrom.ch/de/wifi-button/)
Same problem with adapter checker as stated above.

**Comment by rgwch** [comment]
Added adapter for [Mystrom Wifi Bulb](https://mystrom.ch/de/wifi-bulb/)
Same problem with adapter checker as stated above.

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.dingz](https://github.com/rgwch/ioBroker.dingz)
[Downloads](https://www.npmjs.com/package/iobroker.dingz) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.dingz/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "dingz" in latest repository

### [ioBroker.midea](https://github.com/TA2k/ioBroker.midea)
[Downloads](https://www.npmjs.com/package/iobroker.midea) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.midea/)

:thumbsup: No errors found

### [ioBroker.mystrom-wifi-bulb](https://github.com/rgwch/ioBroker.mystrom-wifi-bulb)
[Downloads](https://www.npmjs.com/package/iobroker.mystrom-wifi-bulb) 
[NPM](https://nodei.co/npm/iobroker.mystrom-wifi-bulb/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.1.3
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.mystrom-wifi-bulb)!. Please execute in adapter directory: `npm owner add bluefox iobroker.mystrom-wifi-bulb`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "mystrom-wifi-bulb" in latest repository

### [ioBroker.mystrom-wifi-button](https://github.com/rgwch/ioBroker.mystrom-wifi-button)
[Downloads](https://www.npmjs.com/package/iobroker.mystrom-wifi-button) 
[NPM](https://nodei.co/npm/iobroker.mystrom-wifi-button/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E813] file src/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E817] file tsconfig.build.json found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "mystrom-wifi-button" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by rgwch** [comment]
Simply not true. 
Dingz travis is here: https://travis-ci.com/github/rgwch/ioBroker.dingz
wifi-bulb travis is here: https://travis-ci.com/github/rgwch/ioBroker.mystrom-wifi-bulb
wifi-button travis is here: https://travis-ci.com/github/rgwch/ioBroker.mystrom-wifi-button

So if you want some other travis, please state more clearly, what you want. 
The thing with .npmignore is also not correct. All complained files were there. I added them now twice...

So, if you don't like the adapters, please feel free to delete this PR.

**Comment by rgwch** [comment]
mystrom-wifi-switch travis is here: https://travis-ci.com/github/rgwch/ioBroker.mystrom-wifi-switch

**Comment by Apollon77** [comment]
Yes the checker sometimes has issues correctly "seeing" travis ... this is ok if it is there

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.dingz](https://github.com/rgwch/ioBroker.dingz)
[Downloads](https://www.npmjs.com/package/iobroker.dingz) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.dingz/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "dingz" in latest repository

### [ioBroker.midea](https://github.com/TA2k/ioBroker.midea)
[Downloads](https://www.npmjs.com/package/iobroker.midea) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.midea/)

:thumbsup: No errors found

### [ioBroker.mystrom-wifi-switch](https://github.com/rgwch/ioBroker.mystrom-wifi-switch)
[Downloads](https://www.npmjs.com/package/iobroker.mystrom-wifi-switch) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.mystrom-wifi-switch/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 2.0.2
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "mystrom-wifi-switch" in latest repository

### [ioBroker.mystrom-wifi-bulb](https://github.com/rgwch/ioBroker.mystrom-wifi-bulb)
[Downloads](https://www.npmjs.com/package/iobroker.mystrom-wifi-bulb) 
[NPM](https://nodei.co/npm/iobroker.mystrom-wifi-bulb/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "mystrom-wifi-bulb" in latest repository

### [ioBroker.mystrom-wifi-button](https://github.com/rgwch/ioBroker.mystrom-wifi-button)
[Downloads](https://www.npmjs.com/package/iobroker.mystrom-wifi-button) 
[NPM](https://nodei.co/npm/iobroker.mystrom-wifi-button/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "mystrom-wifi-button" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@rgwch please check the missing news thing

**Comment by rgwch** [comment]
RE-CHECK

**Pull request closed without merging**
