### PR TITLE
Add tractive-gps to latest

### PR DESCRIPTION
**Pull request by xXBJXx**
Please add my adapter ioBroker.tractive-gps to latest.

*This pull request was created by https://www.iobroker.dev 2fef783.*

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tractive-gps](https://github.com/xXBJXx/ioBroker.tractive-gps)
[Downloads](https://www.npmjs.com/package/iobroker.tractive-gps) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.tractive-gps/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/xXBJXx/ioBroker.tractive-gps/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "tractive-gps" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hey,
* git dependencies are always problematic sometimes ... (https://github.com/xXBJXx/ioBroker.tractive-gps/blob/main/package.json#L69) WHats you changes? Why not doing PR?
* Why you implement the decryption yourself and not use the standard options so that adapter handles all this? At least in main.ts

I will accept the latest addition but before stable you shoukd ideally rethink the git dep

**Comment by Apollon77** [comment]
PS: Ignore my comments on git dep ... just a dev dependency ... :-)

**Pull request merged**
