### PR TITLE
update nina and velux adapter in stable

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nina](https://github.com/TA2k/ioBroker.nina)
[Downloads](https://www.npmjs.com/package/iobroker.nina) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.nina/)

:thumbsup: No errors found

### [ioBroker.velux](https://github.com/TA2k/ioBroker.velux)
[Downloads](https://www.npmjs.com/package/iobroker.velux) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.velux/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nina](https://github.com/TA2k/ioBroker.nina)
[Downloads](https://www.npmjs.com/package/iobroker.nina) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.nina/)

:thumbsup: No errors found

### [ioBroker.velux](https://github.com/TA2k/ioBroker.velux)
[Downloads](https://www.npmjs.com/package/iobroker.velux) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.velux/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Can you also please update the fixed stable version then in the PR for velux
:-)

**Comment by TA2k** [comment]
update the version

**Comment by Apollon77** [comment]
Thank you!

**Pull request merged**
