### PR TITLE
Update ZWave stable version

### PR DESCRIPTION
**Pull request by AlCalzone**

### CODE REVIEW

**Comment by Apollon77** [comment]
Had 1.3.1 also the Forbidden characters reference to js-controller? Should not a 1.4.2 go to stable?

**Comment by AlCalzone** [comment]
You're right, but a 1.4.2 would have to wait a bit before stable. This one is motivated from users not being able to install 1.3.x anymore.

**Comment by Apollon77** [comment]
But because js-conttoller 1.5.11 being stable an upfdate to 1.4.1 would mean many problems, or?

**Comment by AlCalzone** [comment]
Hotfixed to 1.4.2 with the regex/replace change

**Pull request merged**
