### PR TITLE
Add mediola-gateway to latest

### PR DESCRIPTION
**Pull request by oelison**
Please add my adapter ioBroker.mediola-gateway to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.mediola-gateway](https://github.com/oelison/ioBroker.mediola-gateway)
[Downloads](https://www.npmjs.com/package/iobroker.mediola-gateway) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.mediola-gateway/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "mediola-gateway" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
follow up of https://github.com/ioBroker/ioBroker.repositories/pull/2296which was deleted on error

**Comment by mcm1957** [comment]
RESULT of RE-CHECK

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- check info logging [info only]
  I would suggest to check whether the info logging at onStateChange is useful for users or should be change to debug at netx release.
```            
   this.log.info(`state ${id} changed: ${state.val} (ack = ${state.ack})`);
```
  Note that this is no blocking point for lates in my oppinion but only a feedback.
  
Thanks for reading and evalutaing this suggestions.
McM1957


RE-CHECK is OK for me, no issues to be fixed left from my side

Please wait for Review from Apollon77 (will within the next two weeks - sorry).

**Comment by Apollon77** [comment]
Yes info logging shopuld be used when it makes sense ... state changes mostly could be debug in my eyes

**Pull request merged**
