### PR TITLE
Add mieleathome

### PR DESCRIPTION
**Pull request by hash99**

### CODE REVIEW

**Comment by hash99** [comment]
Please check.

**Comment by Apollon77** [comment]
basically ok, but what is the "iobroker-data" directory in the repo?
Also all those "MACOS" files with . at the beginning should not be in reoo (are they maybe also in npm package)

Additionally: on npm is already 1.0.0 ... Do you still want 0.0.4 to come into stable?

**Comment by Apollon77** [comment]
@hash99 ping :-) any news here?

**Comment by Apollon77** [comment]
@hash99 any news?

**Pull request closed without merging**
