### PR TITLE
release myvbus propose file change

### PR DESCRIPTION
**Pull request by pdbjjens**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.myvbus](https://github.com/iobroker-community-adapters/ioBroker.myvbus)
[Downloads](https://www.npmjs.com/package/iobroker.myvbus) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.myvbus/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "myvbus" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

please also enable travis-ci. Thank you!

Additionally some review comments:
* (needs fix) You need to encrypt passwords before storing. YOu could check my meross Adapteror other for examples.

The rest looks really great. Thank you!

**Comment by DutchmanNL** [comment]
recheck

**Comment by DutchmanNL** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.myvbus](https://github.com/iobroker-community-adapters/ioBroker.myvbus)
[Downloads](https://www.npmjs.com/package/iobroker.myvbus) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.myvbus/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "myvbus" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
RE-CHECK!

travis activated

**Comment by DutchmanNL** [comment]
RE-CHECK!

travis activated

**Comment by DutchmanNL** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.myvbus](https://github.com/iobroker-community-adapters/ioBroker.myvbus)
[Downloads](https://www.npmjs.com/package/iobroker.myvbus) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.myvbus/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "myvbus" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by pdbjjens** [comment]
Password Encryption added and tested

**Comment by DutchmanNL** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.myvbus](https://github.com/iobroker-community-adapters/ioBroker.myvbus)
[Downloads](https://www.npmjs.com/package/iobroker.myvbus) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.myvbus/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "myvbus" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by DutchmanNL** [comment]
@Apollon77 password encryption added,  ready for release.

I also a activated travis and all is working/green

Schermafbeelding 2020-04-05 om 10 33 59

**Pull request merged**
