### PR TITLE
add renault

### PR DESCRIPTION
**Pull request by TA2k**
General adapter for renault cars, should replace the zoe2 adapter in the future

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.renault](https://github.com/TA2k/ioBroker.renault)
[Downloads](https://www.npmjs.com/package/iobroker.renault) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.renault/)

- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :eyes: [W400] Cannot find "renault" in latest repository
- [ ] :eyes: [W801] .npmignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.renault](https://github.com/TA2k/ioBroker.renault)
[Downloads](https://www.npmjs.com/package/iobroker.renault) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.renault/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "renault" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
