### PR TITLE
Added teslamateapi

### PR DESCRIPTION
**Pull request by virusbrain**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tankerkoenig](https://github.com/Pix---/ioBroker.tankerkoenig)
[Downloads](https://www.npmjs.com/package/iobroker.tankerkoenig) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.tankerkoenig/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/package.json) (2.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.tankerkoenig) (2.1.1)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.teslamateapi](https://github.com/virusbrain/ioBroker.teslamateapi)
[Downloads](https://www.npmjs.com/package/iobroker.teslamateapi) 
[NPM](https://nodei.co/npm/iobroker.teslamateapi/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/virusbrain/ioBroker.teslamateapi", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/virusbrain/ioBroker.teslamateapi", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/virusbrain/ioBroker.teslamateapi/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "teslamateapi" in latest repository
- [ ] :eyes: [W504] setInterval found in "main.js", but no clearInterval detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by virusbrain** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tankerkoenig](https://github.com/Pix---/ioBroker.tankerkoenig)
[Downloads](https://www.npmjs.com/package/iobroker.tankerkoenig) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.tankerkoenig/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/package.json) (2.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.tankerkoenig) (2.1.1)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.teslamateapi](https://github.com/virusbrain/ioBroker.teslamateapi)
[Downloads](https://www.npmjs.com/package/iobroker.teslamateapi) 
[NPM](https://nodei.co/npm/iobroker.teslamateapi/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/virusbrain/ioBroker.teslamateapi/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "teslamateapi" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by virusbrain** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tankerkoenig](https://github.com/Pix---/ioBroker.tankerkoenig)
[Downloads](https://www.npmjs.com/package/iobroker.tankerkoenig) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.tankerkoenig/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/package.json) (2.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.tankerkoenig) (2.1.1)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.teslamateapi](https://github.com/virusbrain/ioBroker.teslamateapi)
[Downloads](https://www.npmjs.com/package/iobroker.teslamateapi) 
[NPM](https://nodei.co/npm/iobroker.teslamateapi/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/virusbrain/ioBroker.teslamateapi/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "teslamateapi" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by virusbrain** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tankerkoenig](https://github.com/Pix---/ioBroker.tankerkoenig)
[Downloads](https://www.npmjs.com/package/iobroker.tankerkoenig) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.tankerkoenig/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/package.json) (2.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.tankerkoenig) (2.1.1)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.teslamateapi](https://github.com/virusbrain/ioBroker.teslamateapi)
[Downloads](https://www.npmjs.com/package/iobroker.teslamateapi) 
[NPM](https://nodei.co/npm/iobroker.teslamateapi/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/virusbrain/ioBroker.teslamateapi/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "teslamateapi" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by virusbrain** [comment]
Hi! Does I have something more todo?

**Comment by Apollon77** [comment]
Did you checked

>  👀 [W505] setTimeout found in "main.js", but no clearTimeout detected

?

**Comment by virusbrain** [comment]
> Did you checked
> 
> > 👀 [W505] setTimeout found in "main.js", but no clearTimeout detected
> 
> ?

Thanks for your reponse! Yes, this point I have already checked and fixed it with https://github.com/virusbrain/ioBroker.teslamateapi/commit/a0bad51b2aa4bfddf6ffb013362dd125b3d3a0f5.

**Comment by Apollon77** [comment]
Ok, Then I need to do the official review

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tankerkoenig](https://github.com/Pix---/ioBroker.tankerkoenig)
[Downloads](https://www.npmjs.com/package/iobroker.tankerkoenig) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.tankerkoenig/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/package.json) (2.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.tankerkoenig) (2.1.1)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.teslamateapi](https://github.com/virusbrain/ioBroker.teslamateapi)
[Downloads](https://www.npmjs.com/package/iobroker.teslamateapi) 
[NPM](https://nodei.co/npm/iobroker.teslamateapi/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/virusbrain/ioBroker.teslamateapi/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "teslamateapi" in latest repository
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
PS: your fix was most likely good, But not the fic for the info :-)

https://github.com/virusbrain/ioBroker.teslamateapi/blob/main/main.js#L178 is the reason ... You miss the handling of unload in this case because if unload is called the db connection is gone 500ms later, and your delay comes back after 2s.

Easiest way is to require js-controller 4.0 and use "this.setTimeout"/this.clearTimeout (same for Interval) and await this.delay :-) This is unload safe

**Comment by virusbrain** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tankerkoenig](https://github.com/Pix---/ioBroker.tankerkoenig)
[Downloads](https://www.npmjs.com/package/iobroker.tankerkoenig) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.tankerkoenig/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/package.json) (2.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.tankerkoenig) (2.1.1)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.teslamateapi](https://github.com/virusbrain/ioBroker.teslamateapi)
[Downloads](https://www.npmjs.com/package/iobroker.teslamateapi) 
[NPM](https://nodei.co/npm/iobroker.teslamateapi/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/virusbrain/ioBroker.teslamateapi/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "teslamateapi" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by virusbrain** [comment]
> PS: your fix was most likely good, But not the fic for the info :-)
> 
> https://github.com/virusbrain/ioBroker.teslamateapi/blob/main/main.js#L178 is the reason ... You miss the handling of unload in this case because if unload is called the db connection is gone 500ms later, and your delay comes back after 2s.
> 
> Easiest way is to require js-controller 4.0 and use "this.setTimeout"/this.clearTimeout (same for Interval) and await this.delay :-) This is unload safe

Thanks for your feedback! Should be fixed now :-).

**Comment by Apollon77** [comment]
Hi,

ok, here my review feedback:
* Please move this dependency to devDeps: https://github.com/virusbrain/ioBroker.teslamateapi/blob/main/package.json#L21
* Should the access-Token be stored better encrypted? (just define io-package encryptedNative and protectedNative with an array with the filedname and it is handled automatically)
* Beside jsonconfig and the admin5 dependency you still have an index_m.html and a build dummy admin ui in admin? Please remove this. With this you should also remove all thebuild scripts from package.json and testing that are then unneeded ... most likely also many dev Deps could be removed
* Please make sure with a Request timeout of 3s that the data update interval is not lower because it could end in strange issues with your data interval and too many requests going out
* Please only react to state changes to when ack flag is set to false (https://github.com/virusbrain/ioBroker.teslamateapi/blob/main/main.js#L122)
* The code mixture of await and promise chaining with then is unusual ... but in fact up to you ;-) Ideally you decide for one methodology
* When using setObjectNotExistsAsync you should also await it ... else it can also here happen that the setState is executed before the object exists leading to warning logs for the users.
* ALso the objects are checked for existence in every interval to update data ... this is normally uneeded. You should remember which objects where created and then not always try to create them again ...

Thank you for checking and adjusting

**Comment by virusbrain** [comment]
Thanks for your feedback! I should have addressed all of your remarks, but with the following I have some problems:

> Beside jsonconfig and the admin5 dependency you still have an index_m.html and a build dummy admin ui in admin? Please remove this. With this you should also remove all thebuild scripts from package.json and testing that are then unneeded ... most likely also many dev Deps could be removed

I removed the admin/src directory but then the GitHub Actions do not work as expected. Could you give me some more information about this? Or maybe some stuff to read about?

**Comment by virusbrain** [comment]
Hopefully everything should be fixed now.

**Comment by Apollon77** [comment]
Thank you for the adjustments! Welcome in the repo

**Pull request merged**
