### PR TITLE
Binance Adapter added to sources-dist.json

### PR DESCRIPTION
**Pull request by Kartax**

### CODE REVIEW

**Comment by Kartax** [comment]
https://github.com/Kartax/ioBroker.binance
https://www.npmjs.com/package/iobroker.binance
https://travis-ci.com/github/Kartax/ioBroker.binance

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.binance](https://github.com/Kartax/ioBroker.binance)
[Downloads](https://www.npmjs.com/package/iobroker.binance) 
[NPM](https://nodei.co/npm/iobroker.binance/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/Kartax/ioBroker.binance/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W400] Cannot find "binance" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Kartax** [comment]
@GermanBluefox 
I am not sure what the adapter checker complains about. Both "Binance" and "API" are words that will not be translated. Everything else is:
image

**Comment by Kartax** [comment]
nevermind... i found the real problem.

**Comment by Kartax** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.binance](https://github.com/Kartax/ioBroker.binance)
[Downloads](https://www.npmjs.com/package/iobroker.binance) 
[NPM](https://nodei.co/npm/iobroker.binance/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "binance" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@Kartax Why you closed the PR?

**Comment by Kartax** [comment]
@Apollon77 I opened a new one #701

**Pull request closed without merging**
