### PR TITLE
Add klf200 to repository

### PR DESCRIPTION
**Pull request by MiSchroe**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Please add bluefox to owner on npm

**Comment by MiSchroe** [comment]
Added bluefox as owner.

**Comment by GermanBluefox** [comment]
Can it be level.blind  ?

https://github.com/MiSchroe/ioBroker.klf200/blob/master/main.js#L430


Indicator cannot be writable.
https://github.com/MiSchroe/ioBroker.klf200/blob/master/main.js#L463

It is switch.

**Comment by MiSchroe** [comment]
> Can it be level.blind ?
>https://github.com/MiSchroe/ioBroker.klf200/blob/master/main.js#L430

The types which I check for can be blinds or windows. I will change the type to level.blind for all blind types, what is the best level for a window?

> Indicator cannot be writable.
> https://github.com/MiSchroe/ioBroker.klf200/blob/master/main.js#L463

I will fix that.

**Comment by GermanBluefox** [comment]
>I will change the type to level.blind for all blind types, what is the best level for a window?

There is no "level.window".  But we can create it. 
Take level.blind for now.

**Comment by MiSchroe** [comment]
I have changed the role of the silent state to `switch` and the level will be `level.blind`. I have moved the latter to a separate function, which makes it easier to change it to something like `level.window` when that will be available.

**Pull request merged**
