### PR TITLE
add ioBroker.vis-2-widgets-ovarious to latest repository

### PR DESCRIPTION
**Pull request by oweitman**

### CODE REVIEW

**Comment by oweitman** [comment]
E201 invitation is send to bluefox
W184 as already reported if i remove common.noConfig then another error is shown
W400 yes, sure

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

**Comment by mcm1957** [comment]
Some Info regarding checker messages:

 ❗ [E204] Version(s) "0.1.1, 0.1.0" listed at common.news at [io-package.json](https://github.com/oweitman/ioBroker.vis-2-widgets-ovarious/blob/master/io-package.json) do not exist at [NPM](https://www.npmjs.com/package/iobroker.vis-2-widgets-ovarious). Please remove from news.

Releases not available at npm must not be listed at common.news. Please remove those release and eventually add the changes to next higher available release if desired. Admin uses news entries to configure user selectable release when doing an installation of a specific release. If this release is not abvailable at npm installation fails and users do not know why the see a release but get an error when trying to install.

 👀 [W184] "common.noConfig" is deprecated for admin >= 5 at [io-package.json](https://github.com/oweitman/ioBroker.vis-2-widgets-ovarious/blob/master/io-package.json). Please use property "adminUI.config":"none".

Please remove common.noConfig and use adminUI.config:none. If there is still an other error please ignore this error - I'll check.

👀 [W523] "package-lock.json" not found in repo! Please remove from .gitignore!

package-lock.json should be present at github to speed up installation during tests. If you really want to do a full installation during test workflows you can ignore this warning. Maybe tha warning will be suppressed if build is done during every test anyway. I'll make a note.

**Comment by mcm1957** [comment]
Your adapter is named vis-2-widgets-ovarious and NOT ovarious. Please correct sources-dist.json.

**Comment by mcm1957** [comment]
reminder 4.8.2024

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Will be further processed by https://github.com/ioBroker/ioBroker.repositories/pull/3866

as alphabetic order is incorrect
broken commit (invalid reponame) blocks normal checks.

Please subscribe https://github.com/ioBroker/ioBroker.repositories/pull/3866 to get notifications

**Comment by oweitman** [comment]
RE-CHECK!

**Pull request closed without merging**
