### PR TITLE
Bump huum

### PR DESCRIPTION
**Pull request by Chris-656**
Adapter iobroker HUUM bump version to satble 0.4.0

### CODE REVIEW

**Comment by Chris-1965** [comment]
I have a querstion. In the adapters the new version 0.4.0 of the adapter huum-sauna has no icon and no description. Maybe I have forgot something. 
grafik

best regards Chris

**Comment by Apollon77** [comment]
Welche Admin version?

**Comment by Apollon77** [comment]
Bildschirmfoto 2022-09-12 um 16 25 59

works for me?

**Comment by Chris-1965** [comment]
Dear Ingo,
I have admin Version 6.2.17  installed. The latest Version of huum-sauna is 0.4.0 in the repo, bumped it on 22.8.
In your snapshot there is 0.3.8 available.

Regards Chris

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Ingo ***@***.***>
Gesendet: Montag, 12. September 2022 16:26
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [ioBroker/ioBroker.repositories] Bump huum (PR #1911)


[Bildschirmfoto 2022-09-12 um 16 25 59]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11976694%2F189679609-be6bf4bb-3acc-480b-9dcf-03fdc744b768.png&data=05%7C01%7C%7Cb9e2a952148f45c3f83608da94cac455%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637985895852558774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iTPeyki7lEKm3iPRMVmtsvfuOe7m0tJGubSNiFo6XSM%3D&reserved=0>

works for me?

**Pull request merged**
