### PR TITLE
Added go-e for device go-eCharger 

### PR DESCRIPTION
**Pull request by MK-2001**
Ursprünglich für Request #852

### CODE REVIEW

**Comment by MK-2001** [comment]
Hello, Why the automated scripts are not starting here :(
https://adapter-check.iobroker.in I passed here (except E802, E801), but is there in my repo Topics and About text.

**Comment by MK-2001** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.go-echarger](https://github.com/MK-2001/ioBroker.go-echarger)
[Downloads](https://www.npmjs.com/package/iobroker.go-echarger) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.go-echarger/)

- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/package.json) must be lowercase and be equal to "iobroker.go-echarger". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/io-package.json) must be equal to "go-echarger". Now is go-e
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/MK-2001/ioBroker.go-echarger", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/MK-2001/ioBroker.go-echarger" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "go-echarger" in latest repository

### [ioBroker.go-e](https://github.com/MK-2001/ioBroker.go-e)
[Downloads](https://www.npmjs.com/package/iobroker.go-e) 
[NPM](https://nodei.co/npm/iobroker.go-e/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/MK-2001/ioBroker.go-e", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/MK-2001/ioBroker.go-e" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "go-e" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by MK-2001** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.go-echarger](https://github.com/MK-2001/ioBroker.go-echarger)
[Downloads](https://www.npmjs.com/package/iobroker.go-echarger) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.go-echarger/)

- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/package.json) must be lowercase and be equal to "iobroker.go-echarger". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/MK-2001/ioBroker.go-e. Expected: git+https://github.com/MK-2001/ioBroker.go-echarger.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/io-package.json) must be equal to "go-echarger". Now is go-e
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/MK-2001/ioBroker.go-echarger", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/MK-2001/ioBroker.go-echarger" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "go-echarger" in latest repository

### [ioBroker.go-e](https://github.com/MK-2001/ioBroker.go-e)
[Downloads](https://www.npmjs.com/package/iobroker.go-e) 
[NPM](https://nodei.co/npm/iobroker.go-e/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/MK-2001/ioBroker.go-e", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/MK-2001/ioBroker.go-e" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "go-e" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by MK-2001** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.go-echarger](https://github.com/MK-2001/ioBroker.go-echarger)
[Downloads](https://www.npmjs.com/package/iobroker.go-echarger) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.go-echarger/)

- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/package.json) must be lowercase and be equal to "iobroker.go-echarger". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/MK-2001/ioBroker.go-e. Expected: git+https://github.com/MK-2001/ioBroker.go-echarger.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/io-package.json) must be equal to "go-echarger". Now is go-e
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/MK-2001/ioBroker.go-echarger", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/MK-2001/ioBroker.go-echarger" and press `Manage topics`
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E816] file tsconfig.json found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "go-echarger" in latest repository

### [ioBroker.go-e](https://github.com/MK-2001/ioBroker.go-e)
[Downloads](https://www.npmjs.com/package/iobroker.go-e) 
[NPM](https://nodei.co/npm/iobroker.go-e/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/MK-2001/ioBroker.go-e", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/MK-2001/ioBroker.go-e" and press `Manage topics`
- [ ] :eyes: [W400] Cannot find "go-e" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by MK-2001** [comment]
Was muss ich machen, damit der alte Name iobroker.go-echarger nicht mehr gefunden wird? Der Name ist nicht mehr in Verwendung und musste bei Norm zu Go-e geändert werden.

**Comment by Trunks1982** [comment]
Name in der io-Package und Package.json ändern

**Comment by Trunks1982** [comment]
Name in der io-Package und Package.json ändern

**Comment by Trunks1982** [comment]
Am einfachsten wäre mit Adapter creator neuen Adapter erstellen mit richtigen Namen, Code übernehmen alten Name aus repo löschen

**Comment by MK-2001** [comment]
Ich habe das mal nun so getan. ich habe keine einzige Codezeile ausbessern können. 
Warten wir das Review von Ingo ab, dann sehen wir ob es weiter geht. M.E. ist alles i.O. die erste Zeile scheint noch aus dem ersten Commit den alten Adapters zu kommen. Wenn ich das RePo nochmals neu Forken muss, mache ich da auch gerne, aber unter Files in diesem Merge wird ersichtlich, dass nur noch der go-e enthalten ist.

**Comment by Trunks1982** [comment]
Dutchman hatte mir das so gesagt.Und meinte da wäre noch viel zu tun.Hat aber auch angeboten über any ne sitzung zu machen und uns das zu zeigen.

**Comment by MK-2001** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.go-e](https://github.com/MK-2001/ioBroker.go-e)
[Downloads](https://www.npmjs.com/package/iobroker.go-e) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.go-e/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "go-e" in latest repository

### [ioBroker.go-echarger](https://github.com/MK-2001/ioBroker.go-echarger)
[Downloads](https://www.npmjs.com/package/iobroker.go-echarger) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.go-echarger/)

- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/package.json) must be lowercase and be equal to "iobroker.go-echarger". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/MK-2001/ioBroker.go-e. Expected: git+https://github.com/MK-2001/ioBroker.go-echarger.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/io-package.json) must be equal to "go-echarger". Now is go-e
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "go-echarger" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by MK-2001** [comment]
Geschlossen, da ich ohne ein ReBase den Fehler zum veralteten Namen nicht weg bekommen habe. Neu: #867 

(Die Analyse der repo-scripts und das checker-tool von Böuefox war echt nicht leicht.. ;-) )

**Pull request closed without merging**
