### PR TITLE
Add opendtu to latest

### PR DESCRIPTION
**Pull request by o0shojo0o**
Please add my adapter ioBroker.opendtu to latest.

*This pull request was created by https://www.iobroker.dev 2fef783.*

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by hombach** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker
No changed adapters found


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
link to repository: https://github.com/o0shojo0o/ioBroker.opendtu

**Comment by mcm1957** [comment]
Result from adapter checker (= OK):

[W171] "common.title" is deprecated in io-package.json
[W400] Cannot find "opendtu" in latest repository

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.


- Readme.md is very short

  The README.md of this adapter is very minimalistic. Please add a short description about the functionality of the adpter,  add links the the manufacturer site (if applicable) and add a description of the configuration of the adapter. If you provide an external documentation - which should be located at doc/xx directory - please add links to at least the english documentation.
  
Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by o0shojo0o** [comment]
Hi @mcm1957, 
yes you are right the readme was very short. 
I have improved that now ;)

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lightify](https://github.com/soef/ioBroker.lightify)
[Downloads](https://www.npmjs.com/package/iobroker.lightify) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lightify/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL in [package.json](https://github.com/soef/ioBroker.lightify/blob/master/package.json): https://github.com/soef/iobroker.lightify. Expected: git@github.com:soef/ioBroker.lightify.git or https://github.com/soef/ioBroker.lightify.git
- [ ] :heavy_exclamation_mark: [E104] No "common.titleLang" found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E115] No license found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)

### [ioBroker.mihome-cloud](https://github.com/TA2k/ioBroker.mihome-cloud)
[Downloads](https://www.npmjs.com/package/iobroker.mihome-cloud) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mihome-cloud/)

- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
- [ ] :heavy_exclamation_mark: [E407] Meta URL (latest) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
- [ ] :heavy_exclamation_mark: [E426] Icon (stable) must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
- [ ] :heavy_exclamation_mark: [E428] Meta URL (stable) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
- [ ] :heavy_exclamation_mark: [E606] Current adapter version 0.1.0 not found in [README.md](https://github.com/TA2k/ioBroker.mihome-cloud/blob/master/README.md)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/TA2k/ioBroker.mihome-cloud/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W515] Why you decided to disable i18n support?

### [ioBroker.opendtu](https://github.com/o0shojo0o/ioBroker.opendtu)
[Downloads](https://www.npmjs.com/package/iobroker.opendtu) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.opendtu/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/o0shojo0o/ioBroker.opendtu/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "opendtu" in latest repository

### [ioBroker.semp](https://github.com/rg-engineering/ioBroker.semp)
[Downloads](https://www.npmjs.com/package/iobroker.semp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.semp/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.semp)!. Please execute in adapter directory: `npm owner add bluefox iobroker.semp`
- [ ] :heavy_exclamation_mark: [E506] Word "DeviceSwitchOffAtEndOfTimer" is not translated to german in [admin/words.js](https://github.com/rg-engineering/ioBroker.semp/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "DeviceSwitchOffAtEndOfTimer" is not translated to russian in [admin/words.js](https://github.com/rg-engineering/ioBroker.semp/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W202] Version of [package.json](https://github.com/rg-engineering/ioBroker.semp/blob/master/package.json) (1.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.semp) (1.0.0)


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.opendtu](https://github.com/o0shojo0o/ioBroker.opendtu)
[Downloads](https://www.npmjs.com/package/iobroker.opendtu) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.opendtu/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/o0shojo0o/ioBroker.opendtu/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "opendtu" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by hombach** [comment]
I like this adapter - works fine and might be helpful to a lot of people. Would be great to see it in latest repo....
@o0shojo0o: I would also state that it should be placed in stable, too  -  perhaps as version 1.0??

**Comment by mcm1957** [comment]
> I like this adapter - works fine and might be helpful to a lot of people. Would be great to see it in latest repo.... @o0shojo0o: I would also state that it should be placed in stable, too - perhaps as version 1.0??

Don 't worry.
Request for latest is waiting for review.
Stable will be reminded automatically after some time.

Please use forum or adapter repository for further discussion

**Comment by o0shojo0o** [comment]
Hello, I know that the work here depends on a few people and that it is also a lot of work.
But after 5 months, no one should need an adapter request for **latest**, especially not the developers who already have experience with ioBroker and have also successfully provided other adapters.

**Comment by mcm1957** [comment]
@o0shojo0o 
Did you delete this PR on purpose?
Otherwise please reopen and reference rhis PR inew PR

**Comment by o0shojo0o** [comment]
@mcm1957 That was an oversight by me I will create a new PR immediately.

**Comment by mcm1957** [comment]
I though so.
Your not the first one with this occuring.
Is more likely due to extreme long review time.
Sorry

**Comment by Apollon77** [comment]
@o0shojo0o Why closed? I'm about to process all the requests soon ...

**Pull request closed without merging**
