### PR TITLE
add froeling

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.froeling](https://github.com/TA2k/ioBroker.froeling)
[Downloads](https://www.npmjs.com/package/iobroker.froeling) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.froeling/)

- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/TA2k/ioBroker.froeling", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "froeling" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.froeling](https://github.com/TA2k/ioBroker.froeling)
[Downloads](https://www.npmjs.com/package/iobroker.froeling) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.froeling/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "froeling" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
