### PR TITLE
Update e3dc-rscp to 1.2.2

### PR DESCRIPTION
**Pull request by git-kick**
Please update my adapter ioBroker.e3dc-rscp to version 1.2.2.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.e3dc-rscp](https://github.com/git-kick/ioBroker.e3dc-rscp)
[Downloads](https://www.npmjs.com/package/iobroker.e3dc-rscp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.e3dc-rscp/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/git-kick/ioBroker.e3dc-rscp/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
This release has been created at 25.05.2023, 18:10:00 and is now not even available at latest repository.

Release must be available at latest for one or two weeks and/or have a significant number of users and have no major issues.
Exceptions exists of course, ie. if this is a hiot fix for an urgent problem.

Please indicate why this release should be released immidiatly - otherwise I will keep it in evidence and release in some time.

**Comment by git-kick** [comment]
> This release has been created at 25.05.2023, 18:10:00 and is now not even available at latest repository.
> 
> Release must be available at latest for one or two weeks and/or have a significant number of users and have no major issues. Exceptions exists of course, ie. if this is a hiot fix for an urgent problem.
> 
> Please indicate why this release should be released immidiatly - otherwise I will keep it in evidence and release in some time.

Thank you for the heads-up. In fact, 1.2.2 is kind of an urgent fix for 1.2.1 (see [Issue#160](https://github.com/git-kick/ioBroker.e3dc-rscp/issues/160)) - this is why I intended to skip 1.2.1 in stable repo.

But it is not crucial: the bug/fix does not affect the majority of users, so I expect no big impact when waiting 2 weeks before v1.2.2 is declared "stable".

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.e3dc-rscp](https://github.com/git-kick/ioBroker.e3dc-rscp)
[Downloads](https://www.npmjs.com/package/iobroker.e3dc-rscp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.e3dc-rscp/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/git-kick/ioBroker.e3dc-rscp/blob/master/package.json) (1.2.3) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.e3dc-rscp) (1.2.2)


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
@git-kick 

Thanks for fixing the adapter checker issues so fast.
I'll release the 1.2.2 after the holidays if no major issue arises and some users from latest have used as you note an important fix.

I would ask to fix two other problems:

- This adapter seems to use sentry, but no sentry info is added to Readme.md
  
  This adapter seems to use sentry for error logging. Please add the suggested sentry information at the top of Readme.md
  
  ```**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0.```

**Please add the sentry info to README.md.** See other adapters if you need more info.
A new release is NOT necessary for this change as github always displays the head revision anyway.

- The PR has (now) conflicts cause by the fact that you created PRs for 1.2.1 and 1.2.2 from the same base while 1.2.1 is now released. I can fix this druing merge, but maybe it's easier if you rebose the PR yourself.
 

Note that the warnings reported by re-check (https://github.com/ioBroker/ioBroker.repositories/pull/2310#issuecomment-1564646541) can be ignored. Form my side we are done as soon as you add the sentry info and the requested release is active at lasted for some days.

Thanks for effort and for maintaining thsi adapter.

**Comment by git-kick** [comment]
> Please add the sentry info to README.md

done (master branch).

**Comment by git-kick** [comment]
> * maybe it's easier if you rebose the PR yourself.

I'm afraid I do not really understand what I should do. 
I tried to repeat "Set as stable" in the ioBroker Developer Portal, but failed:

> **Update ioBroker.e3dc-rscp to 1.2.2 in stable repository**
> Connecting to GitHub...
> Connected to GitHub as git-kick
> Found fork git-kick/ioBroker.repositories
> Cloning repository from GitHub
> Creating branch e3dc-rscp-1.2.2
> Preparing ioBroker.repositories (this may take a while)
> Updating e3dc-rscp to 1.2.2 locally
> Pushing changes to git-kick/ioBroker.repositories
> Error: Process exited with 1
> Failed 

How can I (re-)trigger the v1.2.2 release for the stable repo?

**Comment by mcm1957** [comment]
> > * maybe it's easier if you rebose the PR yourself.
> 
> I'm afraid I do not really understand what I should do. I tried to repeat "Set as stable" in the ioBroker Developer Portal, but failed:
> 
> How can I (re-)trigger the v1.2.2 release for the stable repo?

OK, sorry for the typ.
rebose should read REBASE, that a git functionality

The "problem" is that there is a merge conflict currently.

I'm not a spcialist with github so I cannot answer hwo to effectly rebase at your side. Sorry.

**I will fix this during merge - so do not bother further with this detail.** 

For the future - please ensure that thers only ONE open PR for a single adapter in parallel.

Thanks for processing my suggestions.

**Comment by git-kick** [comment]
> **I will fix this during merge - so do not bother further with this detail.**
> 
> For the future - please ensure that thers only ONE open PR for a single adapter in parallel.

Many thanks. I rely on you this time and next time, I will do my best to avoid two concurrent PRs.

**Comment by mcm1957** [comment]
1.2.2 25.5. user 52 (5%)

sentry has been added to readme.md

OK wg. wichtigem Fix

**Pull request merged**
