### PR TITLE
add smartgarden to stable

### PR DESCRIPTION
**Pull request by jpgorganizer**
Please add smartgarden adapter to stable repo. Thanks

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.smartgarden](https://github.com/jpgorganizer/ioBroker.smartgarden)
[Downloads](https://www.npmjs.com/package/iobroker.smartgarden) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.smartgarden/)

- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/jpgorganizer/ioBroker.smartgarden", press the first "Edit" button you will find on the page and add the description.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@jpgorganizer please add About for Repo!

**Comment by jpgorganizer** [comment]
> @jpgorganizer please add About for Repo!

sorry, but this is not understandable for me - About is there - has always been there ????

grafik

Thanks for merging.

**Comment by Apollon77** [comment]
kk, then seems false positive :-)

**Pull request merged**
