### PR TITLE
Added Telegram-Menu to latest

### PR DESCRIPTION
**Pull request by MiRo1310**

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alexa-shoppinglist](https://github.com/MiRo1310/ioBroker.alexa-shoppinglist)
[Downloads](https://www.npmjs.com/package/iobroker.alexa-shoppinglist) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alexa-shoppinglist/)

:thumbsup: No errors found

### [ioBroker.airzone](https://github.com/SilentPhoenix11/ioBroker.airzone)
[Downloads](https://www.npmjs.com/package/iobroker.airzone) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.airzone/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/SilentPhoenix11/ioBroker.airzone/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/SilentPhoenix11/ioBroker.airzone/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.lightify](https://github.com/soef/ioBroker.lightify)
[Downloads](https://www.npmjs.com/package/iobroker.lightify) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lightify/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL in [package.json](https://github.com/soef/ioBroker.lightify/blob/master/package.json): https://github.com/soef/iobroker.lightify. Expected: git@github.com:soef/ioBroker.lightify.git or https://github.com/soef/ioBroker.lightify.git
- [ ] :heavy_exclamation_mark: [E104] No "common.titleLang" found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E115] No license found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/soef/ioBroker.lightify/blob/master/io-package.json)
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)

### [ioBroker.mihome-cloud](https://github.com/TA2k/ioBroker.mihome-cloud)
[Downloads](https://www.npmjs.com/package/iobroker.mihome-cloud) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.mihome-cloud/)

- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
- [ ] :heavy_exclamation_mark: [E407] Meta URL (latest) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
- [ ] :heavy_exclamation_mark: [E426] Icon (stable) must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
- [ ] :heavy_exclamation_mark: [E428] Meta URL (stable) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
- [ ] :heavy_exclamation_mark: [E606] Current adapter version 0.1.0 not found in [README.md](https://github.com/TA2k/ioBroker.mihome-cloud/blob/master/README.md)
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/TA2k/ioBroker.mihome-cloud/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W515] Why you decided to disable i18n support?

### [ioBroker.semp](https://github.com/rg-engineering/ioBroker.semp)
[Downloads](https://www.npmjs.com/package/iobroker.semp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.semp/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.semp)!. Please execute in adapter directory: `npm owner add bluefox iobroker.semp`
- [ ] :heavy_exclamation_mark: [E506] Word "DeviceSwitchOffAtEndOfTimer" is not translated to german in [admin/words.js](https://github.com/rg-engineering/ioBroker.semp/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "DeviceSwitchOffAtEndOfTimer" is not translated to russian in [admin/words.js](https://github.com/rg-engineering/ioBroker.semp/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W202] Version of [package.json](https://github.com/rg-engineering/ioBroker.semp/blob/master/package.json) (1.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.semp) (1.0.0)

### [ioBroker.telegram-menu](https://github.com/MiRo1310/ioBroker.telegram-menu)
[Downloads](https://www.npmjs.com/package/iobroker.telegram-menu) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.telegram-menu/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "telegram-menu" in latest repository

### [ioBroker.vis-2-widgets-gauges](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges)
[Downloads](https://www.npmjs.com/package/iobroker.vis-2-widgets-gauges) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-2-widgets-gauges/)

- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E162] onlyWWW should have common.mode "none" in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E124] Main file not found under URL: https://raw.githubusercontent.com/ioBroker/ioBroker.vis-2-widgets-gauges/main/main.js
- [ ] :heavy_exclamation_mark: [E504] "main.js" found in [package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

### [ioBroker.vis-2-widgets-material](https://github.com/ioBroker/ioBroker.vis-2-widgets-material)
[Downloads](https://www.npmjs.com/package/iobroker.vis-2-widgets-material) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-2-widgets-material/)

- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin support (set "common.noConfig = true" and "common.adminUI.config = none" if adapter has no configuration)
- [ ] :heavy_exclamation_mark: [E162] onlyWWW should have common.mode "none" in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E142] logo is too big. It must be less or equal than 512x512
- [ ] :heavy_exclamation_mark: [E124] Main file not found under URL: https://raw.githubusercontent.com/ioBroker/ioBroker.vis-2-widgets-material/main/main.js
- [ ] :heavy_exclamation_mark: [E504] "main.js" found in [package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/master/package.json), but not found as file
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/ioBroker/ioBroker.vis-2-widgets-material", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/ioBroker/ioBroker.vis-2-widgets-material", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
Link to adapter repo: https://github.com/MiRo1310/ioBroker.telegram-menu

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- please check in future that you PRs contain exactly one sources-*.json file
  
  Additions to latest and to stable MUST be seperated into two PRs. As your stable json does not contain any real changes, this PR will likely be accepted by Apollon77. But please check in future to ease our life :-)

- documentation should use neutral form (cosmetic only!)

  According to documentation rules, no personla forms should be used:
``` Mit && als Platzhalter kannst du den Wert im Text platzieren``` should be written as ```...kann man ...```.

  But I want to explicitly say THANKS for good and multilanguage docu provided!

- consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

  
Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alexa-shoppinglist](https://github.com/MiRo1310/ioBroker.alexa-shoppinglist)
[Downloads](https://www.npmjs.com/package/iobroker.alexa-shoppinglist) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alexa-shoppinglist/)

:thumbsup: No errors found

### [ioBroker.airzone](https://github.com/SilentPhoenix11/ioBroker.airzone)
[Downloads](https://www.npmjs.com/package/iobroker.airzone) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.airzone/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/SilentPhoenix11/ioBroker.airzone/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/SilentPhoenix11/ioBroker.airzone/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.semp](https://github.com/rg-engineering/ioBroker.semp)
[Downloads](https://www.npmjs.com/package/iobroker.semp) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.semp/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.semp)!. Please execute in adapter directory: `npm owner add bluefox iobroker.semp`
- [ ] :heavy_exclamation_mark: [E506] Word "DeviceSwitchOffAtEndOfTimer" is not translated to german in [admin/words.js](https://github.com/rg-engineering/ioBroker.semp/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "DeviceSwitchOffAtEndOfTimer" is not translated to russian in [admin/words.js](https://github.com/rg-engineering/ioBroker.semp/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W202] Version of [package.json](https://github.com/rg-engineering/ioBroker.semp/blob/master/package.json) (1.2.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.semp) (1.0.0)

### [ioBroker.telegram-menu](https://github.com/MiRo1310/ioBroker.telegram-menu)
[Downloads](https://www.npmjs.com/package/iobroker.telegram-menu) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.telegram-menu/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "telegram-menu" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alexa-shoppinglist](https://github.com/MiRo1310/ioBroker.alexa-shoppinglist)
[Downloads](https://www.npmjs.com/package/iobroker.alexa-shoppinglist) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alexa-shoppinglist/)

:thumbsup: No errors found

### [ioBroker.airzone](https://github.com/SilentPhoenix11/ioBroker.airzone)
[Downloads](https://www.npmjs.com/package/iobroker.airzone) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.airzone/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/SilentPhoenix11/ioBroker.airzone/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/SilentPhoenix11/ioBroker.airzone/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.telegram-menu](https://github.com/MiRo1310/ioBroker.telegram-menu)
[Downloads](https://www.npmjs.com/package/iobroker.telegram-menu) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.telegram-menu/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "telegram-menu" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
Did you close this PR on purpose?
Or was ist done on error as a sideeffect of yout force-push operation?
In tzhe later case please open a new PR an make a reference to this PR.

**Pull request closed without merging**
