### PR TITLE
Add vis-2-widgets-inventwo to latest

### PR DESCRIPTION
**Pull request by jkvarel**

### CODE REVIEW

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

reminder 10.4.2024

**Comment by mcm1957** [comment]
@jkvarel 
Looks like you added the adapter manually. Please move your adapzter to the alphabetically correct position.

**Comment by jkvarel** [comment]
oh yes, the comma after the last entry right? Now everything should be correct?

**Comment by mcm1957** [comment]
RE-CHECK!

**Pull request closed without merging**
