### PR TITLE
Add freeathome adapter

### PR DESCRIPTION
**Pull request by mobilutz**
This adds the existing freeathome adapter from here:
https://github.com/mobilutz/ioBroker.freeathome

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.freeathome](https://github.com/mobilutz/ioBroker.freeathome)
[Downloads](https://www.npmjs.com/package/iobroker.freeathome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.freeathome/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "freeathome" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

here some review comments:
* Please add adapter testing to your github action.You just execute package testing right now. In fact you need to run test:integration too (and remove nodejs 10 from testing because will fail; and update testing dep to at least 2.5.4) and please add windows and macos for testing
* maybe think about if https://github.com/mobilutz/ioBroker.freeathome/blob/main/package.json#L23 with >= is really making sense? this would also update to a major upgrade like a 2.0 which might break stuff
* please translate titleLang and Desc in io-package to all languages. You can use iobroker translate tool (see readme of this repo)
* Plase also encrypt the password (encryptedNative additionally to protectedNative)
* If you add the state https://github.com/mobilutz/ioBroker.freeathome/blob/main/io-package.json#L112 please also add the info channel
* For what the meta object in https://github.com/mobilutz/ioBroker.freeathome/blob/main/io-package.json#L105 is used/needed? Are users uploading files there or downloading some?
* Please add commonn details in https://github.com/mobilutz/ioBroker.freeathome/blob/main/lib/freeathome.js#L82 and all other places that match to the content, see https://www.iobroker.net/#en/documentation/dev/objectsschema.md (for mandatory state properties)
* Constructs like https://github.com/mobilutz/ioBroker.freeathome/blob/main/lib/freeathome.js#L102-L111 lead to info logging because object is created async and so not existing when the next line is executed. est use async/await and the Async methods to make sure it is executed one after the other

Hints:
* https://github.com/mobilutz/ioBroker.freeathome/blob/main/main.js#L38-L39 ... you can remive that elf topic by using Arrow functions 

```
this.cron = setInterval(() => {
    this.updateAllDevices();
}, 60000);
```

Thank you for considering and adjusting

**Comment by mobilutz** [comment]
Thanks @Apollon77 
I will tackle the points soon.

**Comment by Apollon77** [comment]
@mobilutz any news?, Anything I/we can support?

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.freeathome](https://github.com/mobilutz/ioBroker.freeathome)
[Downloads](https://www.npmjs.com/package/iobroker.freeathome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.freeathome/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/mobilutz/ioBroker.freeathome/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W400] Cannot find "freeathome" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@mobilutz How we should continue? Can we help somehow? Should we do a PR with relevant changes? But that would still require you to verify and test and release it afterwards because the changes can only be done "blind".

**Comment by mobilutz** [comment]
@Apollon77 I finally got around to tackling this - at least a bit.

> * Please add adapter testing to your github action.You just execute package testing right now. In fact you need to run test:integration too (and remove nodejs 10 from testing because will fail; and update testing dep to at least 2.5.4) and please add windows and macos for testing

I unfortunately did not get around to adding real tests 😦 Because I also don't know how to write them.

But maybe this is enough for `0.0.x` version of the adapter.

> * maybe think about if [https://github.com/mobilutz/ioBroker.freeathome/blob/main/package.json#L23](https://github.com/mobilutz/ioBroker.freeathome/blob/main/package.json?rgh-link-date=2022-02-19T15%3A05%3A21Z#L23) with >= is really making sense? this would also update to a major upgrade like a 2.0 which might break stuff

Done, forced the dependency to be `^1.1.2`

> * please translate titleLang and Desc in io-package to all languages. You can use iobroker translate tool (see readme of this repo)

Done

> * Plase also encrypt the password (encryptedNative additionally to protectedNative)

I still need to do this 😦 

> * If you add the state [https://github.com/mobilutz/ioBroker.freeathome/blob/main/io-package.json#L112](https://github.com/mobilutz/ioBroker.freeathome/blob/main/io-package.json?rgh-link-date=2022-02-19T15%3A05%3A21Z#L112) please also add the info channel

I don't know how 😦 

> * For what the meta object in [https://github.com/mobilutz/ioBroker.freeathome/blob/main/io-package.json#L105](https://github.com/mobilutz/ioBroker.freeathome/blob/main/io-package.json?rgh-link-date=2022-02-19T15%3A05%3A21Z#L105) is used/needed? Are users uploading files there or downloading some?

There is nothing being uploaded nor downloaded. I removed this.

> * Please add commonn details in [https://github.com/mobilutz/ioBroker.freeathome/blob/main/lib/freeathome.js#L82](https://github.com/mobilutz/ioBroker.freeathome/blob/main/lib/freeathome.js?rgh-link-date=2022-02-19T15%3A05%3A21Z#L82) and all other places that match to the content, see https://www.iobroker.net/#en/documentation/dev/objectsschema.md (for mandatory state properties)

Done

> * Constructs like [https://github.com/mobilutz/ioBroker.freeathome/blob/main/lib/freeathome.js#L102-L111](https://github.com/mobilutz/ioBroker.freeathome/blob/main/lib/freeathome.js?rgh-link-date=2022-02-19T15%3A05%3A21Z#L102-L111) lead to info logging because object is created async and so not existing when the next line is executed. est use async/await and the Async methods to make sure it is executed one after the other

Done



Please feel free to open for this adapter, as I think it would benefit from your knowledge. But please don't feel pressured.

Thanks
Lutz

**Comment by mobilutz** [comment]
RE-CHECK!"

**Comment by mobilutz** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.freeathome](https://github.com/mobilutz/ioBroker.freeathome)
[Downloads](https://www.npmjs.com/package/iobroker.freeathome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.freeathome/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/mobilutz/ioBroker.freeathome/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "freeathome" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@mobilutz How we should coninue? DoO you need additional support?

**Comment by Apollon77** [comment]
@mcm1957 If you have time please check the fixes ... Thx!

**Comment by mcm1957** [comment]
I l do

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- [ ] errors reported by adapter checker must be fixed

    Please evaluate issues reported by adapter checker. Copyright year is cosmetiv (and not blocking). But please try to fix missing translations and check why latest revision is not available at npm.

- [ ] consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- [ ] adapt testing to supported node releases

  Tests for node 16 is mandatory unless you require node 18 and higher.
  Tests for node 18 is mandatory as many users already use node 18 and node 16 will be eol and deprected Q3/2023.
  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x],

- [ ] reevaluate state roles 

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please see next topic too
  
- [ ] creation of objects seems to need some cleanup

  Please see https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md

  For example:
  - devices do not have an read/write attribute and no data type (https://github.com/mobilutz/ioBroker.freeathome/blob/a4b58cd279aa9af6b5153e2cdc208e1b7acae8af/lib/freeathome.js#L217)
  - setState does not take type and common attributes but is used to write state value. Please check code , i.e. (https://github.com/mobilutz/ioBroker.freeathome/blob/a4b58cd279aa9af6b5153e2cdc208e1b7acae8af/lib/freeathome.js#L271)

  - I do not think that all datapoints should be writeable.  In addition use correct roles if possible.  Also it's unlikely that all data is of type string (but this could be crrect too).
(https://github.com/mobilutz/ioBroker.freeathome/blob/a4b58cd279aa9af6b5153e2cdc208e1b7acae8af/lib/freeathome.js#L309)

  You can look at documentation here: https://github.com/ioBroker/ioBroker.js-controller/blob/master/packages/controller/doc/classes/AdapterClass.md#


  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by mcm1957** [comment]
How shall we continue?
Please let us know if you plan zu fix the noted issues in the near future - or as an alterntive - like to discuss some / all of those points.

**Comment by mcm1957** [comment]
@mobilutz 

A kind reminder.

Please drop any comment if you still maintain this adapter and will fix testing matrix in a resonable time.
If you need help, let uas know. I can provide a PR to update testing if desired,

**If there is no reaction until 15.12.2023 this PR will be closed.**

@Apollon77 FYI

**Comment by mcm1957** [comment]
**As there has been no reaction to latest comments.I will close this PR now.**

**THANKS that you spent time to implement an adapter.** If you find time to finalize and release the adapter at any tim ein future you are very welcome. Please simply create  new PR in this case.

If you have any quetsions, feel free to contact us

@mcm1957 
@Apollon77

**Pull request closed without merging**
