### PR TITLE
Add new Adapter AIO

### PR DESCRIPTION
**Pull request by Newan**
Read values from Hansol Technics AIO system

### CODE REVIEW

**Comment by Newan** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.aio](https://github.com/Newan/ioBroker.aio)
[Downloads](https://www.npmjs.com/package/iobroker.aio) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.aio/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

sorry that it took that long, here are some review comments:
* please check the roles in https://github.com/Newan/ioBroker.aio/blob/master/io-package.json#L392 (and following) --> https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md ... there might be some better ones?!

Rest is ok, do you want to check roles before I accept the repo PR?

**Comment by Newan** [comment]
Is ok i check the roles!

**Comment by Newan** [comment]
@Apollon77 I fix it, please check it again.

**Comment by Apollon77** [comment]
Thank you very much and welcome in the repo

**Pull request merged**
