### PR TITLE
Added somfy tahoma adapter

### PR DESCRIPTION
**Pull request by StrathCole**
Adapter for controlling Somfy Tahoma

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Can you fix this?
image

**Comment by StrathCole** [comment]
Oh of course. I was told those files should only remain local and not be included in the git repo.

**Comment by StrathCole** [comment]
Done that and pushed to git and npm 0.2.6

**Comment by Apollon77** [comment]
Ok, then also my review comments:
* Needs Fix please: username field missing in io.package - native
* Note: pollInterval is default value 20 ... really? In code you re set it to 5s ... maybe better to adjust default value too
* Needs Fix please: testing only checks packages and install ... you should use the integration test too please - or is there a reason against it?
* Note:you do not need tio implement on-message if you do not use it.
* Note: processStateChangeAck should never be needed because ack=true should only come from adapter and best practive it to ignore these changes
* Note: in timeout cases the variable response in https://github.com/StrathCole/ioBroker.tahoma/blob/master/lib/tahoma.js#L170 might be no object ... mabe check this too (i had crashed´s because of this)
* Needs Fix please: you use timeouts in your "Lib" that are not stoppable on unload and can lead to problems in compact mode: https://github.com/StrathCole/ioBroker.tahoma/blob/master/lib/tahoma.js#L189 Please make sure to handle that  (also applyTimer)

Rest looks good

**Comment by StrathCole** [comment]
All of the mentioned review commends should have been addressed now. Current is 0.3.0.

**Pull request merged**
