### PR TITLE
ioBroker.valloxmv 1.0.3

### PR DESCRIPTION
**Pull request by hacki11**
Bugfix

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Can you fix this?
image

**Comment by hacki11** [comment]
fixed all three issues

**Comment by Apollon77** [comment]
Hi,

I have only one review comment :-)
* Note: You might want to check that config is set before having the adapter crash with Exceptions :-) https://travis-ci.com/hacki11/ioBroker.valloxmv/jobs/277729462#L528

**Comment by hacki11** [comment]
Thanks for the review @Apollon77,

currently the adapter is not crashing, just logging the error.
on connection errors (invalid url or unreachable device) the adapters health is changed and retries connecting until the device is back online or the url is configured correctly.

what could be added is a validation, if the hostname/ip and port is configured at all.
if it is not set the adapter could be shut down immediately

**Pull request merged**
