### PR TITLE
Add procon-ip to the latest repository

### PR DESCRIPTION
**Pull request by ylabonte**
Hi there,

as suggested by your bot (ylabonte/ioBroker.procon-ip#6 or ylabonte/ioBroker.procon-ip#7), I would like to add my adapter for the ProCon.IP pool control unit to your latest repository. Meanwhile there are also a few users that mentioned, it would be nice, to have the adapter available from your official repos. But this was inside the [_closed_ forum](http://forum.pooldigital.de/viewtopic.php?p=19948#p19948) of the adapter's target device...

I am not clear about the process, so I think all necessary information could be taken from the [adapter repository](https://github.com/ylabonte/ioBroker.procon-ip). I have tried to follow all of your checklists and guidelines for adapter development. Please just let me know if you need any further information.

Best regards
Yannic

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.procon-ip](https://github.com/ylabonte/ioBroker.procon-ip)
[Downloads](https://www.npmjs.com/package/iobroker.procon-ip) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.procon-ip/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "procon-ip" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by ylabonte** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.procon-ip](https://github.com/ylabonte/ioBroker.procon-ip)
[Downloads](https://www.npmjs.com/package/iobroker.procon-ip) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.procon-ip/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "procon-ip" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi, here some review comments:
* you have not provided a custom_m.html so please setsupportsCustoms to false!
* you added the code to use Auto Adapter encryot/decrypt but you did not provided "encryptedNative" array with the fieldnames in io-package, so most likely there will be NO encryption at all! (changing this will break itfor your users potentially!) Additionally when you do it that way make sure to rename your "own" encrypt/decrypt methods in index_m.ht,l - else they conflict with the ones also build in in Admin
* Please do not use setObjectAsync (https://github.com/ylabonte/ioBroker.procon-ip/blob/master/src/main.ts#L257, also https://github.com/ylabonte/ioBroker.procon-ip/blob/master/src/main.ts#L351 ...) because this can lead to custom settings being removed in older js-controller versions. User setObjectNotExistsAsync please
* I was not able to find the place where info channel and info.connection  objects were created (https://github.com/ylabonte/ioBroker.procon-ip/blob/master/src/main.ts#L127) Plese add them to the instanceObjects in io-package... see e.g. tuya adapter or such
* please make sure that onUnload also stops the timouts in get state service. unload currently is doing nothing. Else it will break the compact mode - did you ever tested the adapter in compact mode?

Please also have a look at  https://github.com/ioBroker/ioBroker.repositories#development-and-coding-best-practices

**Comment by ylabonte** [comment]
Hi @Apollon77,
thanks for your investigation! I will transfer your feedback into one or more issues, fix all points and maybe refactor some additional parts regarding the best practices posted above. Afterwards I will resolve the merge conflict in this PR and leave a comment here again.

**Comment by ylabonte** [comment]
Just to have this mentioned: I have re-tested the current release regarding the encryption. It is correct that I totally leveraged the built-in mechanism. But I did it that way, that **the desired fields are in fact encrypted** using my AES encryption/decryption functions with cryptjs. Anyways I will fix this to behave as desired by ioBroker! I just wanted to explain that there is a working encryption mechanism as I promised with my release notes. 😅️

Sample _objects.json_ from my testing environment:
```
{
  "controllerUrl": "U2FsdGVkX1/gdLPf/o2lRKj9V8EPuayj4exhc9MKfkUb98HLZiWrkMViwhdpx3oS",
  "basicAuth": true,
  "username": "U2FsdGVkX1/28QEx0Cs/kAPJ9EAQpcz0E8OrL7SKUFQ=",
  "password": "U2FsdGVkX1+wkLL3K9Ke1QxU8Ps7w4e55rnkNkKigsA=",
  "updateInterval": "15000"
}
```

**Comment by ylabonte** [comment]
Hello again,
I (hopefully?) resolved all issues arose from your feedback, created a pull request from that changes to the version you have reviewed and finally have resolved the merge conflict that meanwhile existed on this pull request.

The [closed issues overview](https://github.com/ylabonte/ioBroker.procon-ip/milestone/1?closed=1) of the corresponding milestone might be a good entrypoint, if you want to review the changes in relation to the bullet points of your review.

One thing that is not visible from within the code changes: I have tested the adapter in compact mode. Simply for testing multiple instances of the adapter at once running in a single group. And after that succeeded my productive system runs the adapter together with a harmony and a fakeroku instance in one compact group.

Just let me know, if there is anything else you need to know or I should do.

**Pull request merged**
