### PR TITLE
Add new Adapter tvprogram

### PR DESCRIPTION
**Pull request by oweitman**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tvprogram](https://github.com/oweitman/ioBroker.tvprogram)
[Downloads](https://www.npmjs.com/package/iobroker.tvprogram) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.tvprogram/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "tvprogram" in latest repository

### [ioBroker.tvprogram](https://github.com/oweitman/ioBroker.tvprogram)
[Downloads](https://www.npmjs.com/package/iobroker.tvprogram) 
[NPM](https://nodei.co/npm/iobroker.tvprogram/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/oweitman/iobroker.tvprogram/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/oweitman/ioBroker.tvprogram/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/oweitman/ioBroker.tvprogram. Expected: git+https://github.com/oweitman/iobroker.tvprogram.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/oweitman/ioBroker.tvprogram/blob/master/io-package.json) must be equal to "". Now is tvprogram
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
The icon should also come from github raw content url!

**Comment by Apollon77** [comment]
Hi,

here are my review comments and feedback:
* the news should contain more languages then just english :-) there are gulp scripts or the release script and a translation tool to support on translations
* the adapter is not defined as "singletonHost", so there could be multiple instances, but datadir only uses adaptername and not "namespace" ... multiple instances could overwrite stuff each other

Both no show stoppers, do you want to adjust it before adding to latest or not?

**Comment by oweitman** [comment]
i have updated io-package.json with the translations and the singletonHost setting
thank you for review

**Pull request merged**
