### PR TITLE
Add wireless-mbus to latest

### PR DESCRIPTION
**Pull request by lvogt**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.wireless-mbus](https://github.com/lvogt/ioBroker.wireless-mbus)
[Downloads](https://www.npmjs.com/package/iobroker.wireless-mbus) 
[NPM](https://nodei.co/npm/iobroker.wireless-mbus/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:lvogt/ioBroker.wireless-mbus.git. Expected: git+https://github.com/lvogt/ioBroker.wireless-mbus.git
- [ ] :eyes: [W400] Cannot find "wireless-mbus" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by lvogt** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.wireless-mbus](https://github.com/lvogt/ioBroker.wireless-mbus)
[Downloads](https://www.npmjs.com/package/iobroker.wireless-mbus) 
[NPM](https://nodei.co/npm/iobroker.wireless-mbus/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "wireless-mbus" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by lvogt** [comment]
Shouldn't the `must be fixed` have been removed after the "RE-CHECK!" ?

**Comment by Apollon77** [comment]
... not automatically  :-)

**Comment by Apollon77** [comment]
Sorry that it took that long! Should we remove the non working wmbus adapter from repo? If yes please do a PR ... and I will then write an admin notification

**Pull request merged**
