### PR TITLE
add sureflap:1.0.5 to stable

### PR DESCRIPTION
**Pull request by Sickboy78**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

- [ ] :heavy_exclamation_mark: [E154] common.dependencies must contain {"js-controller": ">=2.0.0"} or {"js-controller": ">=3.0.0"}

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/HGlab01/ioBroker.fuelpricemonitor/main/
- [ ] :heavy_exclamation_mark: [E407] Meta URL(latest) must be equal to https://raw.githubusercontent.com/HGlab01/ioBroker.fuelpricemonitor/main/io-package.json
- [ ] :heavy_exclamation_mark: [E426] Icon(stable) must be in the following path: https://raw.githubusercontent.com/HGlab01/ioBroker.fuelpricemonitor/main/
- [ ] :heavy_exclamation_mark: [E428] Meta URL(stable)  must be equal to https://raw.githubusercontent.com/HGlab01/ioBroker.fuelpricemonitor/main/io-package.json

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Morluktom <strassertom@gmx.de>" at the start of LICENSE

### [ioBroker.sureflap](https://github.com/Sickboy78/ioBroker.sureflap)
[Downloads](https://www.npmjs.com/package/iobroker.sureflap) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sureflap/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

sorry that it took that long, some review topics:
* Note: Because of the admin 4.0.9 globalDep and controller dep in your io-package you do nt need the manual encrypt/decrypt in your index_m file ... but also do not hurt if it is in
* Note: https://github.com/Sickboy78/ioBroker.sureflap/blob/master/main.js#L89 ... we have setObjectNotExistsAsync :-) But ...
* Note: You can also just subscribe to the relevant objects where actions are allowed instead of "any" own statechange ... like "control.*" or such
* It seems to me that you do several API requests and then set data. If this can take in sum (for all rewquests and stuff) > 500ms then in case of an unload you could run into the effect that you clear the updateTimer (but this has no effect because is irrelevant becasue you do all the api requests ... and at the end you set the timer anew - but unload was already finished, so nooen would clear the timer again. So in compact mode your adapter runs forever spamming the log with a lot errors. Ideally remember that unload was called and add checks after each "http request" before processing the data and especially before setting update Timeout again.

Please check out especially the last note and add a guard ... other then that adapter is fine

Please poke again when done, Thank you

**Comment by Sickboy78** [comment]
Hi @Apollon77 ,
I have removed the deprecated manual encryption (point 1) and added a guard, to make sure, no timers are called after unload  (point 4).
Point 2 and 3 need a bit more extensive code changes, I'll do them with the next bigger refactoring.
Hope, thats ok for now.
Best Regards

**Comment by ldittmar81** [comment]
@Sickboy78 Please change the year of the copyright to 2022 or 2021-2022
https://github.com/Sickboy78/ioBroker.sureflap/blob/14d6d4ee6720267b814705b5b8e9a570363c0dba/LICENSE#L3

**Comment by Sickboy78** [comment]
@ldittmar81 done

**Comment by Apollon77** [comment]
@Sickboy78 All good and thank you for your

**Pull request merged**
