### PR TITLE
Update due to security alerts on dependencies

### PR DESCRIPTION
**Pull request by phifogg**

### CODE REVIEW

**Comment by Apollon77** [comment]
Not only an update, or!? ;-) New adapter ....

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sainlogic](https://github.com/phifogg/ioBroker.sainlogic)
[Downloads](https://www.npmjs.com/package/iobroker.sainlogic) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sainlogic/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 Fogg <foggch@gmail.com>" at the end of [README.md](https://github.com/phifogg/ioBroker.sainlogic/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Fogg <foggch@gmail.com>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by phifogg** [comment]
RE-CHECK

**Comment by phifogg** [comment]
RE-CHECK!

**Comment by phifogg** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sainlogic](https://github.com/phifogg/ioBroker.sainlogic)
[Downloads](https://www.npmjs.com/package/iobroker.sainlogic) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sainlogic/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/phifogg/ioBroker.sainlogic) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Fogg <foggch@gmail.com>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by phifogg** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sainlogic](https://github.com/phifogg/ioBroker.sainlogic)
[Downloads](https://www.npmjs.com/package/iobroker.sainlogic) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sainlogic/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Here are some review comments
* Please use iobroker translation tools to add all needed languages for the relevant fields in io-package
* Are callbacks available here ? https://github.com/phifogg/ioBroker.sainlogic/blob/master/main.js#L277-L280 that call when really anything is done? especially for the listener case? If yes please use that to call the unload callback
* travis only executes the package testing and no adapter testing
Thank you for checking and fixing

**Comment by phifogg** [comment]
Thanks. Some questions back:
-> Translate: I found https://weblate.iobroker.net/ - is that what you mean? and if, where is a how-to what I need to do? Frankly, I believe german and english are enough. Have not seen anything else beeing requested by users.
-> Callbacks: Not understanding your question here. Listener is a service which opens a port and waits on inbound connection. On termination of the adapter I need to gracefully close/shutdown. This is what is happening here.
-> Correct. What else do I need here? Simulating inbound http calls to update state values?

I understand a certain level of quality gate, but we are all doing this as hobby and it feeld like a lot of burdon you put on a adapter developers. Just my 5 cent.

**Comment by Apollon77** [comment]
@phifogg 

For translate: The basic information in io-package are required to exist in alle languages because ioBroker offers these and we have a user base in these languages already. The mentioned tool is referenced in https://github.com/ioBroker/ioBroker.repositories#development-and-coding-best-practices ... --> https://translator.iobroker.in/ past text, get translation object back.

For Callbacks: Many "network based servers" provide callbacks or resolved promises  that are cakled after the port is actually really closed (in many cases close is still an async action). If your library/what you use provides sucha close-callback then preferrable use those to call the unload callback. iobroekr assumes that any resources are freed up when you call the unload-callback - so when the ports needs another second to be really closed it can give errors on adapter restarts or in compactmode. Please consider the async nature of JavaScript!

For Testing: You should at least also run the "Integration" tests in CI to see that adapter can start. If you like you can add more testing like simulation http calls, but thats optional.

I understand your feedback on "the burdon", but I think what we do here is bare minimal and we need to make sure that Adapters in the repository are not "hurting" users system and compact mode as example requires some care. Also each Adapter has it's part on how users see the whole ioBroker ecosystem in quality and such, so it is a fine balance we try to reach here.

**Comment by phifogg** [comment]
@Apollon77 
I have added translations for the UI parts now and checked on the callback when closing my http server. These should be adressed now.

As for the integration test in the CI pipeline, i'll check into that with the next release. Hope that will do.

**Comment by phifogg** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sainlogic](https://github.com/phifogg/ioBroker.sainlogic)
[Downloads](https://www.npmjs.com/package/iobroker.sainlogic) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sainlogic/)

- [ ] :heavy_exclamation_mark: [E506] Word "" is not translated to german in [admin/words.js](https://github.com/phifogg/ioBroker.sainlogic/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "" is not translated to russian in [admin/words.js](https://github.com/phifogg/ioBroker.sainlogic/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations


*Add comment "RE-CHECK!" to start check anew*

**Comment by phifogg** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.sainlogic](https://github.com/phifogg/ioBroker.sainlogic)
[Downloads](https://www.npmjs.com/package/iobroker.sainlogic) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.sainlogic/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
