### PR TITLE
Added adapter frontier_silicon

### PR DESCRIPTION
**Pull request by halloamt**
Hi,

this will not run but also not without any modifications. It will fail with this message
>  1) Test Repository
>       Test all Packages in latest are loadable via http and name is equal to io-package.json are :
>     Error: the string "Error occurred, see console output" was thrown, throw an Error :)
>      at runMicrotasks (<anonymous>)
>      at processTicksAndRejections (internal/process/task_queues.js:97:5)

It will however pass this step with only my adapter in the list...

Greetings

### CODE REVIEW

**Comment by halloamt** [comment]
Is there anything I can do to fix this?

**Comment by Apollon77** [comment]
The repo error is cauded by an other adapter ... we are already on it. All good

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.frontier_silicon](https://github.com/halloamt/ioBroker.frontier_silicon)
[Downloads](https://www.npmjs.com/package/iobroker.frontier_silicon) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.frontier_silicon/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:halloamt/ioBroker.frontier_silicon.git. Expected: git+https://github.com/halloamt/ioBroker.frontier_silicon.git
- [ ] :heavy_exclamation_mark: [E141] logo is too small. It mast be greater or equal than 32x32
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/halloamt/ioBroker.frontier_silicon", press the settings button beside the about title and add the description.
- [ ] :eyes: [W400] Cannot find "frontier_silicon" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by halloamt** [comment]
> The repo error is cauded by an other adapter ... we are already on it. All good

Perfect :)

**Comment by halloamt** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.frontier_silicon](https://github.com/halloamt/ioBroker.frontier_silicon)
[Downloads](https://www.npmjs.com/package/iobroker.frontier_silicon) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.frontier_silicon/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:halloamt/ioBroker.frontier_silicon.git. Expected: git+https://github.com/halloamt/ioBroker.frontier_silicon.git
- [ ] :heavy_exclamation_mark: [E141] logo is too small. It mast be greater or equal than 32x32
- [ ] :eyes: [W400] Cannot find "frontier_silicon" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by halloamt** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.frontier_silicon](https://github.com/halloamt/ioBroker.frontier_silicon)
[Downloads](https://www.npmjs.com/package/iobroker.frontier_silicon) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.frontier_silicon/)

- [ ] :heavy_exclamation_mark: [E112] extIcon must be the same as an icon but with github path
- [ ] :heavy_exclamation_mark: [E141] logo is too small. It mast be greater or equal than 32x32
- [ ] :eyes: [W400] Cannot find "frontier_silicon" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by halloamt** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.frontier_silicon](https://github.com/halloamt/ioBroker.frontier_silicon)
[Downloads](https://www.npmjs.com/package/iobroker.frontier_silicon) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.frontier_silicon/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "frontier_silicon" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hello,

some feedback and change needs:
* Please sort the entry in repo in alphabetically and not at the end
* testing is not testing the adapter, but just the package
* for a device you could use object type "device" (https://github.com/halloamt/ioBroker.frontier_silicon/blob/master/io-package.json#L182)
* if you replace ll these inline "function()" by "()=>" you can use this all over the place :-)
* please do not do all these async calls in parallel ... just use "await"
* These "sleep" promise things will break if the adapter is unloaded within such a sleep. Please make sure to remember if an unload happened and check before doing further actions
* can it happen in https://github.com/halloamt/ioBroker.frontier_silicon/blob/master/main.js#L1555 that the timeout is set multiple times?
* really polling every second? https://github.com/halloamt/ioBroker.frontier_silicon/blob/master/main.js#L1557

Please have a look and fix the things needed to be fixed

**Comment by halloamt** [comment]
Hallo :)
>     * Please sort the entry in repo in alphabetically and not at the end

I will do that.

>     * testing is not testing the adapter, but just the package

I'm quite unsure how to test the adapter, could you give me some hints?

>     * for a device you could use object type "device" (https://github.com/halloamt/ioBroker.frontier_silicon/blob/master/io-package.json#L182)

done

>     * if you replace ll these inline "function()" by "()=>" you can use this all over the place :-)

I will do that, but at the moment I will not change anonymous functions to lambdas. I will do that as soon as I find some time for that.

>     * please do not do all these async calls in parallel ... just use "await"

The adapter is much les parallel now. My Pi likes thinks 👍 

>     * These "sleep" promise things will break if the adapter is unloaded within such a sleep. Please make sure to remember if an unload happened and check before doing further actions

True, but nothing serious will be lost.

>     * can it happen in https://github.com/halloamt/ioBroker.frontier_silicon/blob/master/main.js#L1555 that the timeout is set multiple times?

Usually not, I will check that. Maybe an `if` helps.

>     * really polling every second? https://github.com/halloamt/ioBroker.frontier_silicon/blob/master/main.js#L1557

Yes :) Ok, that needs an explanation. The API will not close a request with `GET_NOTIFIES` for 30 seconds. If anything happens during that time an answer is returned. After those 30s an `FS_TIMEOUT`is returned. So there ist no polling every second but only every 30 seconds. The 1s is only a wait between requests. This is configurable now.

> Please have a look and fix the things needed to be fixed

I will, thanks for the feedback.

**Comment by Apollon77** [comment]
> * These "sleep" promise things will break if the adapter is unloaded within such a sleep. Please make sure to remember if an unload happened and check before doing further actions

Ok, maybe my words were not clear enough :-) in comact mode the DB will also be destroyed when adapter is unloaded. If this happens during a sleep your code still runs but can not access any adapter.* methods and interact with the DB. This means you can crash the whole compact process (all adapters in that) or can flood the log with errors. SO please make sure to check it

> * really polling every second?

aahhh a long polling mechanism ... ok then :-)

Just tell when you are ready for another check

**Comment by halloamt** [comment]
> Ok, maybe my words were not clear enough :-) in comact mode the DB will also be destroyed when adapter is unloaded. If this happens during a sleep your code still runs but can not access any adapter.* methods and interact with the DB. This means you can crash the whole compact process (all adapters in that) or can flood the log with errors. SO please make sure to check it

Can you tell me how to check that? I cannot find it. Is an ' if(module`) the right way? Or rather a `if(ret !== null...`?

Thanks :)

**Comment by halloamt** [comment]
Comme ca? The timers are added to a map. That map is cleared from old timers every ~<10 Minutes and also on on Unload.
Would that be ok?

**Comment by Apollon77** [comment]
The map is hm ... ;-) in fact as soon as a timout is done (so time is over) you normally do need to clear it because it is already gone ... but if it works ... all good :-)

**Comment by halloamt** [comment]
The map is only cleared to prevent it from growing too large. The map is only really used that I can clear all sleep timers in `onUnload`. Think of it as a convinience method :)
Thanks for merging 👍

**Pull request merged**
