### PR TITLE
Update sources-dist.json

### PR DESCRIPTION
**Pull request by dkleber89**
Add beckhoff v0.1.0 to latest

### CODE REVIEW

**Comment by Apollon77** [comment]
Pleaded remove the versiondate property

**Comment by dkleber89** [comment]
Okay no prob...Do i need to add version property like in stable?

**Comment by Apollon77** [comment]
No, version only is needed for stable. For latest  version is getting automatically from
Npm once a day

**Comment by Apollon77** [comment]
is in latest repo by tonights update

**Pull request merged**
