### PR TITLE
Updated apcups to 2.0.0

### PR DESCRIPTION
**Pull request by XHunter74**
- Changed the minimal version of nodejs to 16 
 - Changed the minimal version of "@iobroker/adapter-core" to 3.0.4"

### CODE REVIEW

**Comment by mcm1957** [comment]
@XHunter74 

Please consider replacing "private" release workflow with standard iobrokers test-and-release workflow. There seems to be not much a difference, but as you are not using the standard workflow I'll have to check in detail which might delay release a few days.

AND more important:

Please consinder semantiv versioning with next release:
increase patch version if only bug fixes included
increase minor version if nonbreaking changes including nw features are included
increase major version if braking chnages are included.

adding new fileds is for sure no bug fix (1.0.13)
increaing node requiresments is breacking as you write yourself. (1.0.18). Here at least a minor version changes (as this is common praxis for ioBroker) would heve been required.

I do NOT consider this blocking, you do nOT need to create a new release immidiatly (but feel free to do ich you like). I will megre after checking and passing tests anyway - but next time please increase version according to changes included.
Thanks

P.S: If you prefer a PR to update tests let me know.

**Comment by mcm1957** [comment]
reminder 13.02.2023

**Comment by XHunter74** [comment]
> Please consider replacing "private" release workflow with standard iobrokers test-and-release workflow. There seems to be not much a difference, but as you are not using the standard workflow I'll have to check in detail which might delay release a few days.

Could you please tell me how I can switch the project to standard test-and-release workflow?

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by XHunter74** [comment]
I fixed warning and changed repository name 
from  https://raw.githubusercontent.com/xhunter74/... 
to      https://raw.githubusercontent.com/XHunter74/...
and action is failed.

**Comment by mcm1957** [comment]
> I fixed warnings and changed the repository name in io-package.json from https://raw.githubusercontent.com/xhunter74/... to https://raw.githubusercontent.com/XHunter74/... and action has failed. What do you think I should do in this case?

This error:
image

is caused by a difference betwenn latest and stable repo - tested against the release versions. I'll clena this up, no action required by you.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
> I fixed warnings and changed the repository name in io-package.json from https://raw.githubusercontent.com/xhunter74/... to https://raw.githubusercontent.com/XHunter74/... and action has failed. What do you think I should do in this case?

casing changes have been done at stable and latest, so everything is green here again.
Missing "admin" add logo path has been added.

**Comment by mcm1957** [comment]
reminder 25,02,2024

**Comment by mcm1957** [comment]
RE-CHECK!

**Pull request merged**
