### PR TITLE
added stable version 2.0.0 of the wiffi-wz adapter

### PR DESCRIPTION
**Pull request by t4qjXH8N**
This version of the adapter supports all products from stall.biz that support sending a datagram. This adapter was tested by me and at least one other user with a different setup. I suppose it is stable.

### CODE REVIEW

**Comment by t4qjXH8N** [comment]
Sorry for doing this wrong again.

**Comment by t4qjXH8N** [comment]
Maybe "first_published" would be a better name for the field?

**Comment by Apollon77** [comment]
no problem ...

**Comment by GermanBluefox** [comment]
for first_published is too late. Attribute used on many places

**Pull request merged**
