### PR TITLE
Add gotify to latest

### PR DESCRIPTION
**Pull request by ThomasPohl**
Hi, I have developed an iobroker adapter to send messages using [gotify](https://gotify.net/).

There is a thread in the forum:
https://forum.iobroker.net/topic/43305/interesse-an-gotify-adapter/39

I hope this is the correct way to add a new adpater. If there is anything that needs to be done to continue, please let me know.

### CODE REVIEW

**Comment by mcm1957** [comment]
Yes this is the right way. 
Please note that a Review by core team will be performed before merging yozr PR. Due to current load this might last some time.

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestions or before you spend major effort.

- [ ] Readme.md does not contain changelog for latest release

  The changelog at README.md of this adapter does not contain an entry for the current release available at npm. Please update README.md. (A new release is not required, an update at github is sufficient.)

- [ ] consider using axios timeouts

  Consider setting a reasonable timeout for axios post request to avoid waiting forever.
  
  According to axios documentation the default value for timeout is 0 which means no timeout
  https://github.com/axios/axios/blob/main/README.md#request-config
  ```
  // `timeout` specifies the number of milliseconds before the request times out.
  // If the request takes longer than `timeout`, the request will be aborted.
  timeout: 1000, // default is `0` (no timeout)
  ```

- [ ] adapt testing to supported node releases

  Consider adding node 20 tests unless you already know incompatibilities.
  
  The recommended testmatrix is [16.x, 18.x, 20.x],

  
Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by ThomasPohl** [comment]
Thank you for the review.

- I updated the tests to run in node 16, 18, and 20. 
- I added the timeout to the axios call. (Sounds useful )
- I commented all the changes (README and io-package.json) and released them as v0.2.0

**Comment by mcm1957** [comment]
Small hint for future releases:

Normally the latest (newest) release info is on top at README.md. I suggest you reorder the entries. In addition I recommedn @alcalzone/release-script which could support creating a release and update all required files.

**Comment by mcm1957** [comment]
lgtm now

**Comment by mcm1957** [comment]
@ThomasPohl 
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, ist OK to continue using this topic too.

**Pull request merged**
