### PR TITLE
Add voltoplus to latest

### PR DESCRIPTION
**Pull request by Jey-Cee**
Please add my adapter ioBroker.voltoplus to latest.

*This pull request was created by https://www.iobroker.dev 880ea27.*

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
Boith warnings can be ignored

**Comment by Jey-Cee** [comment]
Already ignored ;-)

**Comment by Apollon77** [comment]
Hi,

here review feedback:
* The release script will not work for automatic releases because plugin package for iobroker and release config missing (moszt likely release-script was upgraded 2->3 without checking what changed)
* Please also execute adapter tests (test:integration) on testing. right now only package is tested
* Please store and stop the timeout when unloading or use adapter.setTimeout and js-controller >=4 ( and ideally also test it yourself in compact mode ;-) )

Thank you for checking and adjusting the mentioned topics

**Comment by Jey-Cee** [comment]
Done

**Comment by Apollon77** [comment]
@Jey-Cee I will merge into repo now but you should in any case add a request timeout to axios.

I find it interesting that the testing do not log anything, but most likely this is because he tries to query 0.0.0.0 and maybe hangs in a timeout because he waits unlimited ... (assumption), but yes riught now because no timeput means that network errors would also bring the adapter to hang.

Ingo

**Pull request merged**
