### PR TITLE
updated version auf hausbus_de to 1.2.1

### PR DESCRIPTION
**Pull request by hausbus**
sorry, next try...

### CODE REVIEW

**Comment by mcm1957** [comment]
Sorry, but looks like the entry exists twice now:
```
  "hausbus_de": {
    "meta": "https://raw.githubusercontent.com/hausbus/ioBroker.hausbus_de/main/io-package.json",
    "icon": "https://raw.githubusercontent.com/hausbus/ioBroker.hausbus_de/main/admin/hausbusde.png",
    "type": "iot-systems",
    "version": "1.2.1"
  },
  "hausbus_de": {
    "meta": "https://raw.githubusercontent.com/hausbus/ioBroker.hausbus_de/main/io-package.json",
    "icon": "https://raw.githubusercontent.com/hausbus/ioBroker.hausbus_de/main/admin/hausbusde.png",
    "type": "iot-systems",
    "version": "1.2.1"
  },
```

image

**Comment by mcm1957** [comment]
if you open www.iobroker.dev you should see a "set stable" button next to all releases useable. It shoudl really be only on click :-)

image

**Comment by hausbus** [comment]
That’s a realy nice hint but I am actually struggeling each time I try to release something.
When I tried to set version 1.2.1 as stable in www.iobroker.dev<http://www.iobroker.dev> it said that I have to add .releaseconfig.json although this was not necessary when that release was created. So no chance to setStable ? Then I tried to release a new version that includes this file but not the release script is no longer working. At first it said that yarn is not found although I did not change anything further. Then I installed yarn and now I get the error: [FATAL] Error: Command failed with exit code 1: yarn run build
error Command "build" not found.
yarn run v1.22.19“

Any idea ?
Thanks!
Hermann

Von: Martin M. ***@***.***>
Gesendet: Mittwoch, 10. Mai 2023 20:39
An: ioBroker/ioBroker.repositories ***@***.***>
Cc: Hermann Hoeschen ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.repositories] updated version auf hausbus_de to 1.2.1 (PR #2277)


if you open www.iobroker.dev<http://www.iobroker.dev> you should see a "set stable" button next to all releases useable. It shoudl really be only on click :-)

[image]<https://user-images.githubusercontent.com/28575778/237485105-5de3540a-d11e-4bd2-8de2-e2e00e10d014.png>

**Comment by mcm1957** [comment]
Sorry, read this just now.

Ok, if your environment ist not up to date, you might have to use normal editor :-(.

To get the stable out as fast as possible, I would suggest to us the edit feature directly at github. Open the webbrowser and select sources-dist-stabel within the browser. Then edit the file and change exactly the version at your adapter. Wen saveing / committing github should create a new branch and a matching PR with exactly this change.

**Comment by mcm1957** [comment]
Accoring to you environment problems I would suggest you ask at telegram. We should solve thsi AFTER the stable release is aout and whenever you have time. I'll take a look at the repo in the meantime

**Comment by hausbus** [comment]
Thanks Martin,
I was now able to release a new version and set it as stable.

Von: Martin M. ***@***.***>
Gesendet: Mittwoch, 10. Mai 2023 22:16
An: ioBroker/ioBroker.repositories ***@***.***>
Cc: Hermann Hoeschen ***@***.***>; State change ***@***.***>
Betreff: Re: [ioBroker/ioBroker.repositories] updated version auf hausbus_de to 1.2.1 (PR #2277)


Accoring to you environment problems I would suggest you ask at telegram. We should solve thsi AFTER the stable release is aout and whenever you have time. I'll take a look at the repo in the meantime

**Comment by mcm1957** [comment]
So first feedback
iobroker testing is not up to date:
https://github.com/hausbus/ioBroker.hausbus_de/pull/3

test-and-release must be updated
node 12 must be removed as it is not supported anymore
node 14 should be removed as it is eol too and will not be supported by js-controller 5
tests shpould be performed using node 16, 18 and 20 as node 16 will be eol end of 2023. Node 20 is optional, I suggest to do early compatibility tests but feel free to omit it if your adapter has any problems with node 20

alcazone/release-script 
You have updated to the new release of alcazone/releasescript. 
I'm a bit unsufre why the plugins have different release versions -please verify is this is ok.
The up-to-date version of the releasescript require.s a config file. See https://github.com/AlCalzone/release-script.
You can copy one from a newly created adapter or from ioBroker.tmeplat or i.e. ioBroker.pid adapter. 

After updating run the adapter checker if any more problems reported.

If you encounter further troubles please feel free to ask at telegram channel. I'm sure you will get fest help.
https://t.me/ioBroker_development

**Pull request closed without merging**
