### PR TITLE
add hue-sync-box to latest

### PR DESCRIPTION
**Pull request by xXBJXx**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hue-sync-box](https://github.com/xXBJXx/ioBroker.hue-sync-box)
[Downloads](https://www.npmjs.com/package/iobroker.hue-sync-box) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.hue-sync-box/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/xXBJXx/ioBroker.hue-sync-box/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "hue-sync-box" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

here some review comments:
* you can use tier 2 if you want. https://github.com/xXBJXx/ioBroker.hue-sync-box/blob/main/io-package.json#L115
* you use axios but do not have axion in your dependencies https://github.com/xXBJXx/ioBroker.hue-sync-box/blob/main/src/main.ts#L27. Please move from devdeps to deps

After this it looks good, please poke when fixed and released

Ingo

**Comment by xXBJXx** [comment]
Hi @Apollon77,
thanks for your review, 
I changed the tier to 2, and I also moved axios from devDependencies to dependencies.

**Comment by Apollon77** [comment]
Welcome in the repo :-)

**Pull request merged**
