### PR TITLE
Divera247

### PR DESCRIPTION
**Pull request by TKnpl**
https://forum.iobroker.net/topic/41095/neuer-adapter-divera-24-7

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.divera247](https://github.com/TKnpl/ioBroker.divera247)
[Downloads](https://www.npmjs.com/package/iobroker.divera247) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.divera247/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/TKnpl/ioBroker.divera247/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W400] Cannot find "divera247" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TKnpl** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.divera247](https://github.com/TKnpl/ioBroker.divera247)
[Downloads](https://www.npmjs.com/package/iobroker.divera247) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.divera247/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "divera247" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by TKnpl** [comment]
Am I able to fix the [W400] issue by myself? If yes, can somebody help me? I'm not sure what to do.

**Comment by TKnpl** [comment]
Here is an older forum topic to this use case: https://forum.iobroker.net/topic/18823/divera-adapter?_=1610980399734

**Comment by TKnpl** [comment]
Hello @Apollon77 , please have a look to the first forum link. The adapter has now a first test from a forum user.
Hope now everything if fine for merging. Otherwise please let me know open issues.
Thank you in advance!

**Comment by Apollon77** [comment]
Thank you, we need to do review ..

**Comment by Apollon77** [comment]
Here are some review results:
* please update this PR and sort the adapter in alphabetically
* please add the default values of all config vars to io-package.json native area
* should the accessKey be stored ecrypted? Details on encryption see best practices in repo email
* please await object creation calls (e.g. https://github.com/TKnpl/ioBroker.divera247/blob/master/main.js#L36) and ideally also setState calls
* please make sure that when the interval fired shortly before unload was called that not a new intervalis set because the request was still running ...

Personal note:
* Using intervals with external APIs is risky (https://github.com/TKnpl/ioBroker.divera247/blob/master/main.js#L164-L166) because of the fcat that intervals fire regardless of the fact if the former call was done already
*

**Comment by Apollon77** [comment]
@TKnpl Did you had any chance to look into the review feedback?

**Comment by TKnpl** [comment]
@Apollon77 sorry currently not, I'm on it but not finished right now. Do you have an example for an other option for requesting the API?

**Comment by Apollon77** [comment]
You mean without using an interval? Just use Timeoit and set a new one after anything was done in the last run

**Comment by Apollon77** [comment]
Hi,

* there are still two values missing with their default values in io-package.json
* also encryption of the accesskey is still missing, or not relevant in your eyes?

Please have a look again

**Comment by TKnpl** [comment]
Hi @Apollon77 
- sorry, i thought empty initialisations shall not be listed in io-packag.json -> fixed
- yes I think the encryption of the accesskey is not relevant

**Pull request merged**
