### PR TITLE
Add Growatt solar inverter

### PR DESCRIPTION
**Pull request by PLCHome**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E118] Versions in [package.json](https://github.com/PLCHome/ioBroker.growatt/blob/master/package.json) and in [io-package.json](https://github.com/PLCHome/ioBroker.growatt/blob/master/io-package.json) are different
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.growatt)!. Please execute in adapter directory: `npm owner add bluefox iobroker.growatt`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E504] found setInterval in "main.js, but no clearInterval detected
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/PLCHome/ioBroker.growatt", press the settings button beside the about title and add some topics.
- [ ] :heavy_exclamation_mark: [E812] file test/ found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.0.3
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.0.3
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request closed without merging**
