### PR TITLE
Add controme to latest

### PR DESCRIPTION
**Pull request by MadErstam**
Added controme adapter to ioBroker latest repository.

### CODE REVIEW

**Comment by mcm1957** [comment]
Due to outside activities (ioBroker meeting at solingen) this PR will most likely not be processed  before 12.11.2024.

**Comment by MadErstam** [comment]
RE-CHECK!

**Comment by MadErstam** [comment]
RE-CHECK!

**Comment by MadErstam** [comment]
RE-CHECK!

**Comment by simatec** [comment]
Except for the i18n translations, the jsonConfig looks good and fulfills all resolutions

**Comment by MadErstam** [comment]
RE-CHECK!

**Comment by MadErstam** [comment]
> Except for the i18n translations, the jsonConfig looks good and fulfills all resolutions

I18N translations were already directly included in the jsonConfig.json, but were missing the Ukrainian translations. I have added that now in the latest version. Unfortunately, the warning remains. If you could give me a hint how to fix the warning, I would be happy to make these changes.

**Comment by mcm1957** [comment]
jsonConfig should use traslation stored at i18n files. (admin/i18n/{lang}.json or admin/i18n/{lang}/translation.json). This enables integration into weblate and usage of dev-tools npm run translate.  Direct translations inside jsonConfig is (still) supported but not recommended.

So the warning is correct.

**Comment by MadErstam** [comment]
RE-CHECK!

**Comment by MadErstam** [comment]
> jsonConfig should use traslation stored at i18n files. (admin/i18n/{lang}.json or admin/i18n/{lang}/translation.json). This enables integration into weblate and usage of dev-tools npm run translate. Direct translations inside jsonConfig is (still) supported but not recommended.
> 
> So the warning is correct. Please consider migrating to transaltions located at external files.

OK, understood and changed.

**Comment by mcm1957** [comment]
Sorry, but due to travel / absence I will nozt able to do the review before ioBroker Meeting Solingen next weekend.

**Comment by mcm1957** [comment]
@MadErstam 

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal opinion. @Apollon77 might have additional suggestions or even a different opinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] Readme.md needs formatting

  The README.md of this adapter needs formatting. Please check at https://github.com/MadErstam/ioBroker.controme?tab=readme-ov-file#iobrokercontrome. Especially the table of states available is corrupt.

- [ ] package.json should require up to date js-controller and admin version

  New adapters should request js-controller 5 and admin 6 as minimum if there are no strong reason to support (and test) older releases. So please add / adapt at io-package.json:

  ```
        "dependencies": [
            {
                "js-controller": ">=5.0.19"
            }
        ],
        "globalDependencies": [
            {
                "admin": ">=6.17.14"
            }
        ]
  ```

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whenever a dedicated role exists.

  Role 'value' is reserved for read-only states. Consider using role 'level'if no beeter matching role exists.

- [ ] consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- [ ] check and limit configurable timeouts / intervals
  
  Node setTimeout/setInterval routines have a maximum allowed value of 2,147,483,647 ms. Using delays larger than 2,147,483,647 ms (about 24.8 days) result in the timeout being executed immediately. So all (user configurable) values passed to setTimeout / setInterval should be checked in code and limited. Checking/limiting in code is required as config data could be changed directly or by some other adapter too, so limiting at ui level might not be sufficient.
  
- [ ] unused onMessage handler

  onMessage code seems to not provide any functionality. Please remove unused onMeassge handler from code and config (if enabled there).

- [ ] Why do you set "common.getHistory"

  io-package.json defines 'common.getHistory' as true. I cpould not see any message handler processing such a request. Please check and correct or comment. (https://github.com/MadErstam/ioBroker.controme/blob/f4a22fe1ced429deff16daabefc9e3c0e49960a6/io-package.json#L138)

- [ ] linter setup

  Please use standard iobroker linter setup. This is located at @iobroker/eslint-config. See migration guide at https://github.com/ioBroker/ioBroker.eslint-config/blob/main/MIGRATION.md
  
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

reminder 11.12.2024

**Comment by MadErstam** [comment]
Hi @mcm1957!

Thank you for your comments! I think I fixed all of them. See one deviation to what you recommended regarding package.json below.

**I would consider the adapter ready for a re-review!**

* ☑️ Readme.md needs formatting

Done, was an error in the table formatting

* ☑️  package.json should require up to date js-controller and admin version

Shouldn't these go in io-package.json rather than to package.json? I did not find these two dependencies in any package.json of other adapters I have checked, but rather in io-package.json, where at least the js-controller dependency was already included. Anyway, I have included them now in io-package.json.

* ☑️ reevaluate state roles

Done and fixed. All state roles should now comply with the requirements. Read/write functionality also now matches to the role.

* ☑️ consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout

Done.

* ☑️ check and limit configurable timeouts / intervals

Done. The timeout was already limited due to the variable defining the duration having a maximum value. For the interval, I included an upper limit now well below the max delay.

* ☑️ unused onMessage handler

Done. Was really unused and has been fully removed.

* ☑️ Why do you set "common.getHistory"

Was really not needed. Removed the setting.

* ☑️ linter setup

Done and fixed all new lint errors (prettier) and warnings.

**Comment by mcm1957** [comment]
package.json should require up to date js-controller and admin version

Yes of course. Was a typo in my side. Sorry

**Comment by mcm1957** [comment]
Thnaks for ultra fasct reaction and fixes

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Pull request merged**
