### PR TITLE
Update backitup to 3.0.16

### PR DESCRIPTION
**Pull request by simatec**
Please update my adapter ioBroker.backitup to version 3.0.16.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
@simatec 

Please fix

❗ [E204] Version "3.0.13" listed at common.news at [io-package.json](https://github.com/simatec/ioBroker.backitup/blob/master/io-package.json) does not exist at [NPM](https://www.npmjs.com/package/iobroker.backitup). Please remove from news section.

NO new release is required. But Versions at news section which do not exist at npm cause problems for users trying to install a specific release. Admin selects the releases to be available for installation from news contents. We had several questions at forum where user tried to install a versio n which was offered but got an npm error during installation. It's not obvious for users that a version offered to be selected ist not installable. **So please remove this entry from news section at io-package.json** - NOT from README - its ok to keep it at README.

**Comment by simatec** [comment]
> @simatec
> 
> Please fix
> 
> ❗ [E204] Version "3.0.13" listed at common.news at [io-package.json](https://github.com/simatec/ioBroker.backitup/blob/master/io-package.json) does not exist at [NPM](https://www.npmjs.com/package/iobroker.backitup). Please remove from news section.
> 
> NO new release is required. But Versions at news section which do not exist at npm cause problems for users trying to install a specific release. Admin selects the releases to be available for installation from news contents. We had several questions at forum where user tried to install a versio n which was offered but got an npm error during installation. It's not obvious for users that a version offered to be selected ist not installable. **So please remove this entry from news section at io-package.json** - NOT from README - its ok to keep it at README.

done

**Comment by simatec** [comment]
RE-CHECK!

**Comment by simatec** [comment]
RE-CHECK!

**Pull request merged**
