### PR TITLE
Update homekit-controller stable to 0.5.11

### PR DESCRIPTION
**Pull request by Apollon77**

### CODE REVIEW

**Comment by mcm1957** [comment]
@Apollon77 
Please check at least

❗ [E253] Version of [package.json](https://github.com/Apollon77/ioBroker.homekit-controller/blob/master/package.json) (0.5.10) lower than latest version on [NPM](https://www.npmjs.com/package/iobroker.homekit-controller) (0.5.11)

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
@mcm1957 Version fixed, was a missing push

**Comment by Apollon77** [comment]
And yes the other topics I need to do somewhen

**Comment by mcm1957** [comment]
RE-CHECK!

**Pull request merged**
