### PR TITLE
Update souce-list

### PR DESCRIPTION
**Pull request by TheBam1990**
Add- trivum Adapter

https://forum.iobroker.net/topic/44235/trivum-multiroom-system-adapter-v-0-0-1

Adapter checker have found no problems

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [io-package.json](https://github.com/main/io-package.json)
[Downloads](https://www.npmjs.com/package/io-package.json) 
[NPM](https://nodei.co/npm/io-package.json/)

- [ ] :heavy_exclamation_mark: 404


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Ignore that error

**Comment by o0shojo0o** [comment]
Hi @TheBam1990, 
I noticed the following with your adapters:
- please check your dependencies it is missing e.g. [axios](https://github.com/TheBam1990/ioBroker.trivum/runs/2422103417?check_suite_focus=true#step:6:225). 
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/package.json#L19
- please use const or let and not additionally var 
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L11
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L19
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L308
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L377
- there are variables declared which are not used:
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L10
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L23
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L305
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L335
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L381
- here ; were forgotten: 
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L450
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L453
- Here's another [note](https://eslint.org/docs/rules/no-case-declarations) about Line:
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L487
- The role used here is not valid **[Indicators (boolean, read-only)](https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md#indicators-boolean-read-only)**:
  - https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L100
  - and others place

 I hope I have thought of everything.

**Comment by TheBam1990** [comment]
Hello,

 

Axios is in: https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/package.json#L34

 

 

The variables i Have changed to const and let.

 


Gesendet: Dienstag, 27. April 2021 um 10:03 Uhr
Von: "Dennis Rathjen" ***@***.***>
An: "ioBroker/ioBroker.repositories" ***@***.***>
Cc: "TheBam1990" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [ioBroker/ioBroker.repositories] Update souce-list (#1231)


 

Hi @TheBam1990,
I noticed the following with your adapters:


	please check your dependencies it is missing e.g. axios.

	
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/package.json#L19
	
	
	please use const or let and not additionally var
	
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L11
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L19
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L308
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L377
	
	
	there are variables declared which are not used:
	
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L10 deleted
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L23 deleted
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L305  need for a Later Version. The manufacturer wants to adapt your firmware. This variable is required for this.
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L335 deleted
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L381
		 Deleted
	
	
	here ; were forgotten:
	
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L450  Added
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L453
		Added
	
	
	Here's another note about Line:
	
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L487
		I don't understand the problem here
	
	
	The role used here is not valid Indicators (boolean, read-only):
	
		https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L100
		and others place
		changed
	
	


I hope I have thought of everything.

**Comment by Apollon77** [comment]
Ok, also some review comments from me:

* code style: I do not understand why you use the trivum_adapter variable ... this should be there always unless you create a dynamic "function"
* code style: https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L69 ... *.* should be * ...
* you need to await that here https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L77 and in other places ... else it runs async ... can that work?

The rest is ok ... Please check especially the last point

**Comment by TheBam1990** [comment]
trivum_adapter  is a Placeholder fot "this" in funktions.  

´https://github.com/TheBam1990/ioBroker.trivum/blob/bd2153144195d4f22163a7927b52ec26459a8bfd/main.js#L77 No, it has been working in my test system for several months.

**Comment by Apollon77** [comment]
BTW: In normal cases you do not needs that trivum_adapter variable :-) Just use () => style functions and thisd should always stay stable ... but ok ... "just" code style.

**Pull request merged**
