### PR TITLE
Update Heytech Adapter

### PR DESCRIPTION
**Pull request by ansgarschulte**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heytech](https://github.com/Jey-Cee/ioBroker.heytech)
[Downloads](https://www.npmjs.com/package/iobroker.heytech) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heytech/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/Jey-Cee/ioBroker.heytech) are broken. Please fix.
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@ansgarschulte Please check that really all timeouts and intervals are cleared and clearable in "unload"

**Comment by ansgarschulte** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heytech](https://github.com/Jey-Cee/ioBroker.heytech)
[Downloads](https://www.npmjs.com/package/iobroker.heytech) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heytech/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by ansgarschulte** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heytech](https://github.com/Jey-Cee/ioBroker.heytech)
[Downloads](https://www.npmjs.com/package/iobroker.heytech) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heytech/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 1.0.0


*Add comment "RE-CHECK!" to start check anew*

**Comment by ansgarschulte** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.heytech](https://github.com/Jey-Cee/ioBroker.heytech)
[Downloads](https://www.npmjs.com/package/iobroker.heytech) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.heytech/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
