### PR TITLE
add seq to latest

### PR DESCRIPTION
**Pull request by o0shojo0o**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.linux-control](https://github.com/Scrounger/ioBroker.linux-control)
[Downloads](https://www.npmjs.com/package/iobroker.linux-control) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.linux-control/)

:thumbsup: No errors found

### [ioBroker.seq](https://github.com/o0shojo0o/ioBroker.seq)
[Downloads](https://www.npmjs.com/package/iobroker.seq) 
[NPM](https://nodei.co/npm/iobroker.seq/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/o0shojo0o/ioBroker.seq/blob/master/io-package.json). Must be removed.
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.seq)!. Please execute in adapter directory: `npm owner add bluefox iobroker.seq`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/o0shojo0o/ioBroker.seq", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/o0shojo0o/ioBroker.seq", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "seq" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.linux-control](https://github.com/Scrounger/ioBroker.linux-control)
[Downloads](https://www.npmjs.com/package/iobroker.linux-control) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.linux-control/)

:thumbsup: No errors found

### [ioBroker.seq](https://github.com/o0shojo0o/ioBroker.seq)
[Downloads](https://www.npmjs.com/package/iobroker.seq) 
[NPM](https://nodei.co/npm/iobroker.seq/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.seq)!. Please execute in adapter directory: `npm owner add bluefox iobroker.seq`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "seq" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.linux-control](https://github.com/Scrounger/ioBroker.linux-control)
[Downloads](https://www.npmjs.com/package/iobroker.linux-control) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.linux-control/)

:thumbsup: No errors found

### [ioBroker.seq](https://github.com/o0shojo0o/ioBroker.seq)
[Downloads](https://www.npmjs.com/package/iobroker.seq) 
[NPM](https://nodei.co/npm/iobroker.seq/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.seq)!. Please execute in adapter directory: `npm owner add bluefox iobroker.seq`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "seq" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.linux-control](https://github.com/Scrounger/ioBroker.linux-control)
[Downloads](https://www.npmjs.com/package/iobroker.linux-control) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.linux-control/)

:thumbsup: No errors found

### [ioBroker.seq](https://github.com/o0shojo0o/ioBroker.seq)
[Downloads](https://www.npmjs.com/package/iobroker.seq) 
[NPM](https://nodei.co/npm/iobroker.seq/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "seq" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
As aggreed in Dev meeting and verified with @DutchmanNL travis not implemented

**Comment by DutchmanNL** [comment]
Linux Control is Flagged in this PR But only seq had been Added.
I assume based in the replace of 1 },

**Comment by Apollon77** [comment]
@o0shojo0o Some review comments, please fix:
* when using     "@iobroker/adapter-core": "^2.4.0", s dependency the minimum js.controller dep needs to be 2.0.0!

rest is ok ... SHould be a very fast fix :-)

Please inform when doe. Thank you!

**Comment by o0shojo0o** [comment]
I fixed it :)

**Comment by Apollon77** [comment]
Thank you

**Pull request merged**
