### PR TITLE
add Fiat adapter

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.psa](https://github.com/TA2k/ioBroker.psa)
[Downloads](https://www.npmjs.com/package/iobroker.psa) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.psa/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "psa" in latest repository

### [ioBroker.fiat](https://github.com/TA2k/ioBroker.fiat)
[Downloads](https://www.npmjs.com/package/iobroker.fiat) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.fiat/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "fiat" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Here review results:

* Please also add "admin >= 4.0.9" as common.globalDependencies for the encryption to work properly
* indicator as role is only defined foir booleans ... please check your roles (e.g. https://github.com/TA2k/ioBroker.fiat/blob/3f0bfa1f5a7bc5bd7a5becfae645d437de2ebea4/lib/extractKeys.js#L25 )
* For each data request you again check and pot try to create all the objects that were all there already. this costs a lot performance. Please add a way to detect if an object was already "setObjectNotExists" and then do not call that again - so only call it the firt time for an id.

Thank you for looking into it. The last topic would be great but is no show stopper

**Comment by TA2k** [comment]
fixed all issues

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.psa](https://github.com/TA2k/ioBroker.psa)
[Downloads](https://www.npmjs.com/package/iobroker.psa) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.psa/)

:thumbsup: No errors found

### [ioBroker.fiat](https://github.com/TA2k/ioBroker.fiat)
[Downloads](https://www.npmjs.com/package/iobroker.fiat) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.fiat/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "fiat" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Thank you and welcome

**Pull request merged**
