### PR TITLE
Add new bsblan version

### PR DESCRIPTION
**Pull request by hacki11**
v0.3.0

### CODE REVIEW

**Comment by Apollon77** [comment]
The version was released a day ago ... is it really ready for stable and proofed by users? Or do it have a important fix? Normally stable is updated after 1-2 Weeks or after a significant amount of installations

**Comment by hacki11** [comment]
https://forum.iobroker.net/topic/58595/test-adapter-bsblan-v0-3-x

- added link to test thread
- Converted to draft

**Comment by Apollon77** [comment]
wanna do it now? :-)

**Comment by hacki11** [comment]
Need some more testers and fix a bug. I will clear the draft state when this is fixed

**Comment by Apollon77** [comment]
@hacki11 Happy new year, how we should proceed?

**Pull request closed without merging**
