### PR TITLE
Added binance to sources-dist-stable.json

### PR DESCRIPTION
**Pull request by Kartax**

### CODE REVIEW

**Comment by Kartax** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.binance](https://github.com/Kartax/ioBroker.binance)
[Downloads](https://www.npmjs.com/package/iobroker.binance) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.binance/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
please merge https://github.com/Kartax/ioBroker.binance/pull/12 and make a new version

**Comment by Kartax** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.binance](https://github.com/Kartax/ioBroker.binance)
[Downloads](https://www.npmjs.com/package/iobroker.binance) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.binance/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Kartax** [comment]
@GermanBluefox I merged your changes and tagged V 1.0.5

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.binance](https://github.com/Kartax/ioBroker.binance)
[Downloads](https://www.npmjs.com/package/iobroker.binance) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.binance/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
