### PR TITLE
Please add adapter diashow to latest

### PR DESCRIPTION
**Pull request by gaudes**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

:thumbsup: No errors found

### [io-package.json](https://github.com/main/io-package.json)
[Downloads](https://www.npmjs.com/package/io-package.json) 
[NPM](https://nodei.co/npm/io-package.json/)

- [ ] :heavy_exclamation_mark: 404

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

:thumbsup: No errors found

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Morluktom <strassertom@gmx.de>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

here is some review feedback:
* you really do not check state.ack? https://github.com/gaudes/ioBroker.diashow/blob/main/src/main.ts#L81
* why ever that should go wrong :-)) https://github.com/gaudes/ioBroker.diashow/blob/main/src/main.ts#L288
Rest is ok, please check especially that state.ack thingy ...

**Comment by Apollon77** [comment]
now you mix up PR?!

**Comment by Apollon77** [comment]
@gaudes Any update?

**Comment by gaudes** [comment]
@Apollon77 : Yes, in Discord :-)

Your decision, I can close this PR and create a new one, or you can merge.

I've f*** up my fork, so I can only recreate a new PR to fix this mix here.

**Comment by Apollon77** [comment]
I try rebase ... lets see :-)

**Comment by gaudes** [comment]
@Apollon77 : Thx

**Pull request merged**
