### PR TITLE
Bump huum-sauna to 0.4.5

### PR DESCRIPTION
**Pull request by Chris-656**

### CODE REVIEW

**Comment by Chris-656** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@Chris-656 

Adapgter checker does not find versions as it is looking for level 3 header:

```
## Changelog

<!--
    Placeholder for the next version (at the beginning of the line):
    ### **WORK IN PROGRESS**
-->
### 0.0.8 (2023-07-13)

-   (mcm1957) changed: Overall stability during state updates has been increased
-   (mcm1957) changed: Dependencies have been updated

```

If you have time, please add an addition '#' - if not, I'll accept the current format too of course. Please fix it until next release then.

**Comment by Chris-656** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
0.4.5 created 31.10.2023
5 user (10%)
OK

**Pull request merged**
