### PR TITLE
Add SteMaker/ioBroker.hdg-bavaria repository

### PR DESCRIPTION
**Pull request by SteMaker**
Let me know if there are any adaptations to the adapter or this pull request needed.

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hdg-bavaria](https://github.com/stemaker/ioBroker.hdg-bavaria)
[Downloads](https://www.npmjs.com/package/iobroker.hdg-bavaria) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.hdg-bavaria/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by ldittmar81** [comment]
@Apollon77 - No errors found - Adapter can be reviewed

**Comment by Apollon77** [comment]
Hi,

sorry for the delay:
* Please add "npm test:integration" to the github action testing again, because currently only package tests are executed
* For the channels better use setObjectNotExist to prevent recreation (option in my eyes)

Please re-add testing and we are ready to go :-) Thank you

**Comment by SteMaker** [comment]
Many thanks @Apollon77!

I fixed the integration test and activated it. I also replaced setObject with setObjectNotExist when creating channels. New v0.3.1 is uploaded. Please have a look if any further adaptations are needed.

**Comment by SteMaker** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hdg-bavaria](https://github.com/stemaker/ioBroker.hdg-bavaria)
[Downloads](https://www.npmjs.com/package/iobroker.hdg-bavaria) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.hdg-bavaria/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.3.1


*Add comment "RE-CHECK!" to start check anew*

**Comment by SteMaker** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.hdg-bavaria](https://github.com/stemaker/ioBroker.hdg-bavaria)
[Downloads](https://www.npmjs.com/package/iobroker.hdg-bavaria) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.hdg-bavaria/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Awesome, welcome to the repo!

**Pull request merged**
