### PR TITLE
Update smoothed to 1.0.0

### PR DESCRIPTION
**Pull request by BenAhrdt**
Please update my adapter ioBroker.smoothed to version 1.0.0.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by BenAhrdt** [comment]
@mcm1957 Bluefox asked in a pr to Set 0.5.0 to stable....
Some things e.g. License => licenseinformation
Core >= 3.0.4 to >= 3.0.6 changelog and Build Version 1.0.0

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by BenAhrdt** [comment]
@mcm1957 is there something to do for me?

**Comment by mcm1957** [comment]
> @mcm1957 is there something to do for me?

https://github.com/ioBroker/ioBroker.repositories/pull/3454#issuecomment-2029902329

**Comment by BenAhrdt** [comment]
@mcm1957
OK. like [This Comment](https://github.com/ioBroker/ioBroker.repositories/pull/3454#issuecomment-2030075771)
The changes only are: changes in io-Package and adapter-core Version, like there are hints in the last PR of Version 0.5.0

**Pull request merged**
