### PR TITLE
add seq to stable

### PR DESCRIPTION
**Pull request by o0shojo0o**

### CODE REVIEW

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.seq](https://github.com/o0shojo0o/ioBroker.seq)
[Downloads](https://www.npmjs.com/package/iobroker.seq) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.seq/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/o0shojo0o/ioBroker.seq/blob/master/io-package.json). Must be removed.


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.seq](https://github.com/o0shojo0o/ioBroker.seq)
[Downloads](https://www.npmjs.com/package/iobroker.seq) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.seq/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by o0shojo0o** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.seq](https://github.com/o0shojo0o/ioBroker.seq)
[Downloads](https://www.npmjs.com/package/iobroker.seq) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.seq/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
