### PR TITLE
Updated birthdays, YouTube, LaMetric, Shelly

### PR DESCRIPTION
**Pull request by klein0r**

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.birthdays](https://github.com/klein0r/ioBroker.birthdays)
[Downloads](https://www.npmjs.com/package/iobroker.birthdays) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.birthdays/)

:thumbsup: No errors found

### [ioBroker.youtube](https://github.com/klein0r/ioBroker.youtube)
[Downloads](https://www.npmjs.com/package/iobroker.youtube) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.youtube/)

:thumbsup: No errors found

### [ioBroker.lametric](https://github.com/klein0r/ioBroker.lametric)
[Downloads](https://www.npmjs.com/package/iobroker.lametric) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lametric/)

:thumbsup: No errors found

### [ioBroker.shelly](https://github.com/iobroker-community-adapters/ioBroker.shelly)
[Downloads](https://www.npmjs.com/package/iobroker.shelly) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.shelly/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.shelly/blob/master/io-package.json)


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
birthdays 01.05.2023 - OK
youtube 13.03.2023 - OK
shelly 23.04.2023 - OK

lametric - 10.06.2023 *** released today***

Releases added to stabel should have been available some time at latest repository. lametric is not even at latest because it has been built / tagged today. Please indicate if this is a hotfix or some other condition apply which requires an immidiate release to stable. Otherwise I would suggest to move lametrics to a seperated PR as the other three adapters are ok for stable yet.

**Comment by klein0r** [comment]
> Please indicate if this is a hotfix or some other condition apply which requires an immidiate release to stable.

🙄 Okay, I will re-try i a few month...

**Comment by Apollon77** [comment]
@klein0r I think of for that time, just please consider in the futurre :-)

**Pull request merged**
