### PR TITLE
judoisoft

### PR DESCRIPTION
**Pull request by arteck**

### CODE REVIEW

**Comment by Apollon77** [comment]
hardware really the correct and best category?

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.judoisoft](https://github.com/arteck/ioBroker.judoisoft)
[Downloads](https://www.npmjs.com/package/iobroker.judoisoft) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.judoisoft/)

- [ ] :heavy_exclamation_mark: [E100] Cannot parse [io-package.json](https://github.com/arteck/ioBroker.judoisoft/blob/master/io-package.json): SyntaxError: Unexpected token } in JSON at position 170
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.judoisoft)!. Please execute in adapter directory: `npm owner add bluefox iobroker.judoisoft`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/arteck/ioBroker.judoisoft", press the settings button beside the about title and add some topics.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2018-2021 Arthur Rupp <arteck@outlook.com>" at the end of [README.md](https://github.com/arteck/ioBroker.judoisoft/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2014-2021 Arthur Rupp <arteck@outlook.com>" at the start of LICENSE


*Add comment "RE-CHECK!" to start check anew*

**Comment by arteck** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.judoisoft](https://github.com/arteck/ioBroker.judoisoft)
[Downloads](https://www.npmjs.com/package/iobroker.judoisoft) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.judoisoft/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 1.0.0
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/arteck/ioBroker.judoisoft/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/arteck/ioBroker.judoisoft/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E125] External icon not found under URL: https://raw.githubusercontent.com/arteck/ioBroker.judo/master/admin/judo.png
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.judoisoft)!. Please execute in adapter directory: `npm owner add bluefox iobroker.judoisoft`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/arteck/ioBroker.judoisoft", press the settings button beside the about title and add some topics.
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2014-2021 Arthur Rupp <arteck@outlook.com>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "judoisoft" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by arteck** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.judoisoft](https://github.com/arteck/ioBroker.judoisoft)
[Downloads](https://www.npmjs.com/package/iobroker.judoisoft) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.judoisoft/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.judoisoft)!. Please execute in adapter directory: `npm owner add bluefox iobroker.judoisoft`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/arteck/ioBroker.judoisoft", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "judoisoft" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by arteck** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.judoisoft](https://github.com/arteck/ioBroker.judoisoft)
[Downloads](https://www.npmjs.com/package/iobroker.judoisoft) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.judoisoft/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal
- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.judoisoft)!. Please execute in adapter directory: `npm owner add bluefox iobroker.judoisoft`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "judoisoft" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by arteck** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.judoisoft](https://github.com/arteck/ioBroker.judoisoft)
[Downloads](https://www.npmjs.com/package/iobroker.judoisoft) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.judoisoft/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.judoisoft)!. Please execute in adapter directory: `npm owner add bluefox iobroker.judoisoft`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "judoisoft" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by arteck** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.judoisoft](https://github.com/arteck/ioBroker.judoisoft)
[Downloads](https://www.npmjs.com/package/iobroker.judoisoft) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.judoisoft/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.judoisoft)!. Please execute in adapter directory: `npm owner add bluefox iobroker.judoisoft`
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "judoisoft" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by arteck** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.judoisoft](https://github.com/arteck/ioBroker.judoisoft)
[Downloads](https://www.npmjs.com/package/iobroker.judoisoft) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.judoisoft/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "judoisoft" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Review comments:
* enable testing via travis or github actions
* addd nodejs requirement to package.json please
* not needed https://github.com/arteck/iobroker.judoisoft/blob/master/io-package.json#L58
* adjust to like in repo https://github.com/arteck/iobroker.judoisoft/blob/master/io-package.json#L67
* https://github.com/arteck/iobroker.judoisoft/blob/master/io-package.json#L69 rreally needed?
* default values missing in io-packge native
* remove custom_m.html if not used
* remove object changed if not needed
* you should await setState too
* await object creations

Thank you for the adjustments

**Comment by arteck** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.judoisoft](https://github.com/arteck/ioBroker.judoisoft)
[Downloads](https://www.npmjs.com/package/iobroker.judoisoft) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.judoisoft/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "judoisoft" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by arteck** [comment]
next turn plz

**Comment by arteck** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.judoisoft](https://github.com/arteck/ioBroker.judoisoft)
[Downloads](https://www.npmjs.com/package/iobroker.judoisoft) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.judoisoft/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "judoisoft" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
* fix testing please https://github.com/arteck/iobroker.judoisoft/blob/master/.travis.yml#L7
* please encrypt password
* object change is still doing nothing https://github.com/arteck/iobroker.judoisoft/blob/875b5f90f52a11c70cdde261441511f262b35c00/main.js#L83-L91
* please await object creation https://github.com/arteck/iobroker.judoisoft/blob/master/main.js#L361 e.g.

**Comment by Apollon77** [comment]
@arteck any help needed?

**Pull request merged**
