### PR TITLE
chromecast stable -> 3.0.3

### PR DESCRIPTION
**Pull request by raintonr**

### CODE REVIEW

**Comment by mcm1957** [comment]
This PR does not only provide a version update (sources-dist-stable.json) containing an update of chromecast **BUT ALSO THE ADDITON OF ACME INTO LATEST** (sources-dist.json).

As additions to latest must be reviewed, please SPLIT this PR / remove acme / lastes from this PR. (A PR to add acme seems to exist anyway).

**Comment by raintonr** [comment]
So merge this one first :smile: -> https://github.com/ioBroker/ioBroker.repositories/pull/2122

**Comment by mcm1957** [comment]
> So merge this one first 😄 -> #2122

Review / merging of a LATEST PR requires a review and will last some time while reviews of stable are done very quick normally.

**Comment by mcm1957** [comment]
@Apollon77 
Just for info if you want to do a review of adapter ioBroker.acme. 
This PR merged adapter acme into LASTED too - despite the title of this PR and so bypassed the normal latest review.

I know that the acme Adapter is a little bit special, so it might be OK. But I wnated to inform you.

**Comment by Apollon77** [comment]
Yes acme is special ... so ok, was considered

**Pull request merged**
