### PR TITLE
Bump TibberLink stable to 0.2.7

### PR DESCRIPTION
**Pull request by hombach**

### CODE REVIEW

**Comment by hombach** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
Please fix translation file and please check and confirm that the version included in to release 0.2.7 is OK

**Comment by hombach** [comment]
Translation file version is the same than in 0.2.6....
`{
	"Standard settings": "Standard settings",
	"s_ReferalLink": "If you're not a Tibber user right now, it's greatly appreciated when you're using my reveral link.",
	"Calculator settings": "Calculator settings",
	"tibberlink adapter settings": "Adapter settings for TibberLink",
	"TibberAPIToken": "token for Tibber api",
	"PulseActive": "use Tibber pulse (all homes)",
	"SelectFieldsForFeed": "Select all fields you want to load in feed data (power and timestamp are default):",
	"s_PhasesExplanation": "Voltage and current values  -  on several meters these values are not part of the data frame, therefore the values might be null. There can be other deviations based on concrete meter firmware. Null values won't generate a state in your ioBroker objects at all."
}`
-> Have the checking rules been changed? E.g. no empty spaces in ID of the String? (... yes, I should change this ;) )

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
The problem is definitly NOT caused by some spaces within keys. They are completla Ok.

You saved the english translation file with some edito padding format characters at the start of the file:

PS E:\GitHub\homback\ioBroker.tibberlink\admin\i18n\en> format-hex translations.json

```
           Pfad: E:\GitHub\homback\ioBroker.tibberlink\admin\i18n\en\translations.json

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   EF BB BF 7B 0D 0A 09 22 73 5F 53 74 61 6E 64 61  ï»¿{..."s_Standa
00000010   72 64 53 65 74 74 69 6E 67 73 22 3A 20 22 53 74  rdSettings": "St
00000020   61 6E 64 61 72 64 20 73 65 74 74 69 6E 67 73 22  andard settings"

```

So the first char is NOT the { character.

The german file is ok:

```
PS E:\GitHub\homback\ioBroker.tibberlink\admin\i18n\de> format-hex translations.json


           Pfad: E:\GitHub\homback\ioBroker.tibberlink\admin\i18n\de\translations.json

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   7B 0D 0A 09 22 73 5F 53 74 61 6E 64 61 72 64 53  {..."s_StandardS
00000010   65 74 74 69 6E 67 73 22 3A 20 22 53 74 61 6E 64  ettings": "Stand
00000020   61 72 64 2D 45 69 6E 73 74 65 6C 6C 75 6E 67 65  ard-Einstellunge
```

Please correct and verify if that the bad file is not part of 0.2.7

Most likely THIS commit invented the error:

https://github.com/hombach/ioBroker.tibberlink/commit/4e9c1210e136134a05c3b4826895eae510a954ae

so 0.2.7 is likely to be ok. But please verify by running the adapter with language english selected at 0.2.7

**Comment by hombach** [comment]
You are rigth... version 0.2.7 is still in UTF-8 coding .... new version 0.3.3, only EN translation, is in UTF-8-BOM coding.... WTF!

Thank you very much vor your help!   latest is now fixed, and old 0.2.7 is without the error, so bumping it to stable would be ok - from my point of view!

BTW: I really appreciate this quality checks!

**Comment by hombach** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
OT:

I know this problem from my job.

We had files edited at PC (Windows) , VMS (and Digital Equipment, later Compaq, later HP) Operatings system and edited on Linux. Some of the files have been required to be plain uff8, others ISO-xxx and all have been stored at cvs. All files looked OK - until the got used - from linux, from oracle, ...

**Comment by mcm1957** [comment]
0.2.7 created 9.9.2023
20 User (3%)
OK

**Pull request merged**
