### PR TITLE
Updated Adapters (LaMetric, Trashschedule, YouTube, added OctoPrint)

### PR DESCRIPTION
**Pull request by klein0r**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lametric](https://github.com/klein0r/ioBroker.lametric)
[Downloads](https://www.npmjs.com/package/iobroker.lametric) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.lametric/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/klein0r/ioBroker.lametric/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations

### [ioBroker.luftdaten](https://github.com/klein0r/ioBroker.luftdaten)
[Downloads](https://www.npmjs.com/package/iobroker.luftdaten) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luftdaten/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/klein0r/ioBroker.luftdaten) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/klein0r/ioBroker.luftdaten/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.youtube](https://github.com/klein0r/ioBroker.youtube)
[Downloads](https://www.npmjs.com/package/iobroker.youtube) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.youtube/)

- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/klein0r/ioBroker.youtube/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.octoprint](https://github.com/klein0r/ioBroker.octoprint)
[Downloads](https://www.npmjs.com/package/iobroker.octoprint) 
[NPM](https://nodei.co/npm/iobroker.octoprint/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/klein0r/ioBroker.octoprint) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E506] More non translated in german or russian words found in [admin/words.js](https://github.com/klein0r/ioBroker.octoprint/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W400] Cannot find "octoprint" in latest repository

### [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule)
[Downloads](https://www.npmjs.com/package/iobroker.trashschedule) 
[NPM](https://nodei.co/npm/iobroker.trashschedule/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.youtube](https://github.com/klein0r/ioBroker.youtube)
[Downloads](https://www.npmjs.com/package/iobroker.youtube) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.youtube/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/klein0r/ioBroker.youtube) are broken. Please fix.
- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.lametric](https://github.com/klein0r/ioBroker.lametric)
[Downloads](https://www.npmjs.com/package/iobroker.lametric) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lametric/)

:thumbsup: No errors found

### [ioBroker.luftdaten](https://github.com/klein0r/ioBroker.luftdaten)
[Downloads](https://www.npmjs.com/package/iobroker.luftdaten) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luftdaten/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.octoprint](https://github.com/klein0r/ioBroker.octoprint)
[Downloads](https://www.npmjs.com/package/iobroker.octoprint) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.octoprint/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/klein0r/ioBroker.octoprint) are broken. Please fix.
- [ ] :eyes: [W400] Cannot find "octoprint" in latest repository

### [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule)
[Downloads](https://www.npmjs.com/package/iobroker.trashschedule) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.trashschedule/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.octoprint](https://github.com/klein0r/ioBroker.octoprint)
[Downloads](https://www.npmjs.com/package/iobroker.octoprint) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.octoprint/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "octoprint" in latest repository

### [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule)
[Downloads](https://www.npmjs.com/package/iobroker.trashschedule) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.trashschedule/)

:thumbsup: No errors found

### [ioBroker.lametric](https://github.com/klein0r/ioBroker.lametric)
[Downloads](https://www.npmjs.com/package/iobroker.lametric) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lametric/)

:thumbsup: No errors found

### [ioBroker.luftdaten](https://github.com/klein0r/ioBroker.luftdaten)
[Downloads](https://www.npmjs.com/package/iobroker.luftdaten) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luftdaten/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected

### [ioBroker.youtube](https://github.com/klein0r/ioBroker.youtube)
[Downloads](https://www.npmjs.com/package/iobroker.youtube) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.youtube/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "main.js", but no clearTimeout detected


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@klein0r can you please check the findings by the checker?!

**Comment by klein0r** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.octoprint](https://github.com/klein0r/ioBroker.octoprint)
[Downloads](https://www.npmjs.com/package/iobroker.octoprint) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.octoprint/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "octoprint" in latest repository

### [ioBroker.lametric](https://github.com/klein0r/ioBroker.lametric)
[Downloads](https://www.npmjs.com/package/iobroker.lametric) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lametric/)

:thumbsup: No errors found

### [ioBroker.luftdaten](https://github.com/klein0r/ioBroker.luftdaten)
[Downloads](https://www.npmjs.com/package/iobroker.luftdaten) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.luftdaten/)

:thumbsup: No errors found

### [ioBroker.youtube](https://github.com/klein0r/ioBroker.youtube)
[Downloads](https://www.npmjs.com/package/iobroker.youtube) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.youtube/)

:thumbsup: No errors found

### [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule)
[Downloads](https://www.npmjs.com/package/iobroker.trashschedule) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.trashschedule/)

- [ ] :heavy_exclamation_mark: [E815] file .[travis](https://travis-ci.com/).yml found in repository, but not found in .npmignore


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Some review comments for octoprint:
* you should also check that respinse is defined e.g. https://github.com/klein0r/ioBroker.octoprint/blob/master/main.js#L309 (timeout cases can lead to an undefined response object)
* makes it sense to encrypt the api key?
* onObjectChange is implemented but unused basically

No blockers so I merge

**Comment by klein0r** [comment]
@Apollon77 Is there already a common way / interface to encrypt and decrypt data?

**Comment by Apollon77** [comment]
Starting with js-controller 3.0 yes :-) for older controller versions you need to add additional code

roughly like:
https://github.com/iobroker-community-adapters/ioBroker.tr-064/blob/master/main.js#L111-L114

and 

https://github.com/iobroker-community-adapters/ioBroker.tr-064/blob/master/admin/index_m.html#L210-L212

and 

https://github.com/iobroker-community-adapters/ioBroker.tr-064/blob/master/admin/index_m.html#L344-L346

**Comment by Apollon77** [comment]
PS: I think requirs a contreoller of min 2.x for that way

AND you need for the easy controller 3.0 way:

https://github.com/iobroker-community-adapters/ioBroker.tr-064/blob/master/io-package.json#L166-L171

**Pull request merged**
