### PR TITLE
Update sources-dist.json with adapter powerfox2

### PR DESCRIPTION
**Pull request by Ax-LED**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.solax](https://github.com/simatec/ioBroker.solax)
[Downloads](https://www.npmjs.com/package/iobroker.solax) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.solax/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/simatec/ioBroker.solax/blob/master/io-package.json). Must be removed.

### [ioBroker.powerfox2](https://github.com/Ax-LED/ioBroker.powerfox2)
[Downloads](https://www.npmjs.com/package/iobroker.powerfox2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.powerfox2/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/ax-led/ioBroker.powerfox2.git. Expected: git+https://github.com/Ax-LED/ioBroker.powerfox2.git
- [ ] :eyes: [W400] Cannot find "powerfox2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Ax-LED** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.solax](https://github.com/simatec/ioBroker.solax)
[Downloads](https://www.npmjs.com/package/iobroker.solax) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.solax/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/simatec/ioBroker.solax/blob/master/io-package.json). Must be removed.

### [ioBroker.powerfox2](https://github.com/Ax-LED/ioBroker.powerfox2)
[Downloads](https://www.npmjs.com/package/iobroker.powerfox2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.powerfox2/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/ax-led/ioBroker.powerfox2. Expected: git+https://github.com/Ax-LED/ioBroker.powerfox2.git
- [ ] :eyes: [W400] Cannot find "powerfox2" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Ax-LED** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.powerfox2](https://github.com/Ax-LED/ioBroker.powerfox2)
[Downloads](https://www.npmjs.com/package/iobroker.powerfox2) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.powerfox2/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "powerfox2" in latest repository

### [ioBroker.solax](https://github.com/simatec/ioBroker.solax)
[Downloads](https://www.npmjs.com/package/iobroker.solax) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.solax/)

- [ ] :heavy_exclamation_mark: [E144] common.installedFrom field found in [io-package.json](https://github.com/simatec/ioBroker.solax/blob/master/io-package.json). Must be removed.


*Add comment "RE-CHECK!" to start check anew*

**Comment by ldittmar81** [comment]
@Apollon77 - No errors found - Adapter can be reviewed

**Comment by Apollon77** [comment]
Hi,

sorry that it took so long, here some review comments:
* if you do not use customs please remove https://github.com/Ax-LED/ioBroker.powerfox2/blob/main/admin/custom_m.html
* Where you got that fallback value from for encryption https://github.com/Ax-LED/ioBroker.powerfox2/blob/main/main.js#L42 ?? This is the wrong one and will produce many issues because as soon as the user upgrades his password will be invalid. Please adjust to the official fallback or remove that whiole "self ecnrypt/decrpt" and add controller >=2 and admin >=4.0.9 as deps (admin common.globalDependencies) and remove all own logic and let iobroker handle it please.
* Please do not invent new role names. Please stick to the defined ones from https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md ... (e.g. https://github.com/Ax-LED/ioBroker.powerfox2/blob/main/main.js#L113 ... for other places there are defined roles, please use them)
* Why you need that "hacky" killTimeout (e.g. https://github.com/Ax-LED/ioBroker.powerfox2/blob/main/main.js#L149) ... please try to work without and use proper async /await and such and call one "stop" the the end :-)
* Please remove https://github.com/Ax-LED/ioBroker.powerfox2/blob/main/main.js#L175 if not needed (and yes makes no sense for a schedule adapter)
* Is the default schedule with "every minute" really the best? Becasue of then it would make sense to think about changing to deamon adapter because starting up an nodejs process fpr the adapter and such costs also resources ... and once a minute is often

Please check and adjust

**Comment by Ax-LED** [comment]
Hi Ingo,

thanks for your response, as this is my first adapter, i have a few questions.

- How should we communicate for questions? Github or discord (i am already invited).

- How will changes get in this pull request? Do i have to close this PR, make my changes to the code and do a new pull request or are there other ways?

To 1. is clear to me, i will change it
To 2. can you tell me where to find docs or other adapters, where i can check how to do it right (i reused some code of bazidibavaria who made the initial adapter)?
To 3. i will change my freestyle role 'indicator.outdated' to 'state'. Is this right for true/false values?
To 4. can you tell me where to find docs or other adapters, where i can check how to do it right?
To 5. this is something i can think about it for the future, so far i would like to get the adapter working technically and with right coding

I am looking forward hearing from you

AxLED

**Comment by Apollon77** [comment]
Happy new year!

Communication: as you like, I tink the dev channel in Discord is faster because also other dev are around there ... :-)

Re-Review: YOu simply do the changes and then poke here again ... we leave it open, then it is easier for me to recheck because I have the history :-)

for 2.) If you want to leave it as is you just need to change the "fallback secret" to  'Zgfr56gFe87jJOM'. Otherwise just rome all the "encrypt7decrypt stuff" you have in now and just do like https://github.com/TA2k/ioBroker.renault/blob/master/io-package.json#L70-L86 ... with the "dependencies" you make sure that admin and controller support the automatic encrypt/decrypt and you just define the field. "All done"
to 3.) I think already "indicator" is find (if write=false), check the link I provded for list of defined roles
to 4.) Yes and no :-) In fact several "schedule" adapters use such a killTimeout to make sure the adapter gets killed if something hangs or such, but in fact they always were workarounds for "suboptimal callback style development" or "forgot to set proper communication timeouts" ;-) So make sure all is working as expected and then a `stop()` at the end is the right thing
to 5.) All good ... In fact I told it becaue changing the adapter mode afetr release is meeehhhhhhh ;-)) (because not that easy)

**Comment by Ax-LED** [comment]
@Apollon77 
i did the suggested changes to my repository, except for the [https://github.com/Ax-LED/ioBroker.powerfox2/blob/main/main.js#L175](https://github.com/Ax-LED/ioBroker.powerfox2/blob/main/main.js#L175) since the following error message appeared in the ioBroker logs when the code block was removed: o	host.dev-powerfox2-0034M instance system.adapter.powerfox2.0 terminated with code 6 (UNCAUGHT_EXCEPTION).
Can you please review the PR.
Thanks
AxLED

**Comment by ldittmar81** [comment]
Close https://github.com/ioBroker/AdapterRequests/issues/449 when ready

**Comment by Apollon77** [comment]
@Ax-LED The log should show more then just that ... thwere should be a log with the exception stack trace. Normally this can not happen if you remove this one function (unless you forgot to also remote this call here https://github.com/Ax-LED/ioBroker.powerfox2/blob/main/main.js#L27 ;-)) )

**Comment by Apollon77** [comment]
Additionally please fix your testing :-)) https://github.com/Ax-LED/ioBroker.powerfox2/runs/4680811238?check_suite_focus=true#step:2:496

You might want to add exitcode 0 in testing as allowedExitCode (see https://github.com/ioBroker/testing#adapter-startup-integration-test)

**Comment by Apollon77** [comment]
PS: Rest is fine ... so not much left

**Comment by Ax-LED** [comment]
@Apollon77 
as discussed on discord made the changes to main.js and test/integration.js and re-uploaded (github and npm), anything else I need to do?

AxLED

**Comment by Apollon77** [comment]
Perfect!

**Pull request merged**
