### PR TITLE
add matrix adapter 1.0.0 to stable

### PR DESCRIPTION
**Pull request by oelison**
Node 18 required!
https://github.com/oelison/ioBroker.matrix-org/issues/51

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.matrix-org](https://github.com/oelison/ioBroker.matrix-org)
[Downloads](https://www.npmjs.com/package/iobroker.matrix-org) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.matrix-org/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
1.0.0 created 01.04.2023, 14:36:29
1.0.0 users 24 (17%)
no serious issues

**OK**

**Comment by mcm1957** [comment]
@oelison 
One hint for future
A major release indicates some incompatibility. So changing the major release number users are encouraged to read the releasenotes carefully to decide whta functionality has changed or is no longer provided. As far as I can read from the changelog only dropped support for node 16 (and lower) has changed. Not sure, if this requires a major version change as this is no incompatible change for users perfor,ming an upgrade at existing systems - buts ist ok from my poitn anyway.

The only improvement I would suggest to clearly state that no other incompatibilities exist - including incompatibilities introduced by the unlying software. This would save investigation time for users.

But again - this is only a comment/ feedback  and not blocking point.
Merge will occure within the next minutes.

McM195

**Comment by oelison** [comment]
Okay, good to know.

**Pull request merged**
