### PR TITLE
Add evcc to latest

### PR DESCRIPTION
**Pull request by Newan**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.evcc](https://github.com/Newan/ioBroker.evcc)
[Downloads](https://www.npmjs.com/package/iobroker.evcc) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.evcc/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "evcc" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

thank you for your submission. Here is some review feedback,
* Please activate Github actions so that testing can run and make sure it is green
* the admin UI src is not committed?
* please add the channel objects too for the statis info/status objects
* makes is sense to have port in IP? https://github.com/Newan/ioBroker.evcc/blob/main/io-package.json#L98 This is uncommon ... maybe better have two config fields?
* even if local cinnection because of the intervalb better add a timeout and amake sure interval is not smaller then timeout

Thank you for checking and adjusting,

Ingo

**Comment by Newan** [comment]
@Apollon77 

"please add the channel objects too for the statis info/status objects" -> https://github.com/Newan/ioBroker.evcc/blob/main/src/main.ts#L155 pls a hint what is to do?

"the admin UI src is not committed?" i see the admin folder in the repo?

**Comment by Apollon77** [comment]
1.) was referring to https://github.com/Newan/ioBroker.evcc/blob/main/io-package.json#L101 ... you have no info channel object and no status channel object. Or do you add that in code?
2.) Yes admin folder is there but just the "build" folder .. not the src folder

**Comment by Newan** [comment]
2) i use only jsonConfig now, this are old data -> delte it

**Comment by Newan** [comment]
@Apollon77  why i musst have info.status and info.channel? Other Adapter have this also not: 
https://github.com/TA2k/ioBroker.fronius-solarweb/blob/master/io-package.json

**Comment by Apollon77** [comment]
You miss this one !! https://github.com/TA2k/ioBroker.fronius-solarweb/blob/master/io-package.json#L90-L97

**Comment by Newan** [comment]
fixed

**Comment by Apollon77** [comment]
Then we are fine here too. Please release (and remove nodejs 12 from testing, then it should be ok again). and then I can merge

**Comment by Newan** [comment]
@Apollon77 fixed and release a new version. Thanks

**Pull request merged**
