### PR TITLE
Add heizungssteuerung 1.7.0 to stable

### PR DESCRIPTION
**Pull request by jbeenenga**

### CODE REVIEW

**Comment by jbeenenga** [comment]
RE-CHECK!

**Comment by jbeenenga** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@jbeenenga 
Your adapter https://github.com/jbeenenga/ioBroker.heizungssteuerung does not use standard iobroker testing or standard testing does not succeed

Please see requirements https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository

```
Adapter needs to have at least Adapter basic testing (installing, running) using GitHub actions. More information in forum from apollon77 (Just take from other adapters the samples)
```

You may copy the ```test-and-release.yml``` workflow from the example adapter or newly created adapter. If you need help, please let uas know.

Your current workflow tries to test using node 14 and fails of course. Node 14 is no longer supported by ioBroker since some time and must be removed from tests. Tests must use node 16 / 18 / 20. Node 16 is optional if your adapter requies node 18 or higher.

Please feel free if you need any help setting up standard testing and / or if you prefer a PR to fix this.

**Please add a comment when you have reviewed and fixed the suggestion or at least commented the suggestions and you think the adapter is ready for a re-review**

**Comment by jbeenenga** [comment]
Hi @mcm1957,

I've corrected the node version. Can you please check if everything is fine now?

Thanks

**Pull request merged**
