### PR TITLE
added vis-material-advanced to latest

### PR DESCRIPTION
**Pull request by EdgarM73**
added my widget to latest

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
PS: yes there will be false positives if only widget ... so we check what makes sense

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/EdgarM73/ioBroker.vis-material-advanced", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/EdgarM73/ioBroker.vis-material-advanced", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "vis-material-advanced" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.3.7
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "vis-material-advanced" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "vis-material-advanced" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "vis-material-advanced" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "vis-material-advanced" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "vis-material-advanced" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "vis-material-advanced" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "vis-material-advanced" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "vis-material-advanced" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "vis-material-advanced" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "vis-material-advanced" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by EdgarM73** [comment]
Hi there,

i have tried it several time. in the check it says all checks passed ( including travis ), but the automated adapter checker says there is no travis.

please give me an hint what to do.

regards
E

**Comment by EdgarM73** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.vis-material-advanced](https://github.com/EdgarM73/ioBroker.vis-material-advanced)
[Downloads](https://www.npmjs.com/package/iobroker.vis-material-advanced) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.vis-material-advanced/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "vis-material-advanced" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
