### PR TITLE
Luftdaten Adapter

### PR DESCRIPTION
**Pull request by klein0r**

### CODE REVIEW

**Comment by klein0r** [comment]
https://forum.iobroker.net/viewtopic.php?f=8&t=9865

**Review by BuZZy1337 — COMMENTED** [review]
Maybe the "type" weather would be better for this Adapter?

**Comment by klein0r** [comment]
Thanks for merging. You're right 👍 Weather is much better.

**Comment by Apollon77** [comment]
Is Bluefox added as owner on npm?

BZW: remove folder "widget" please if you are not offering a widget :-)

**Comment by klein0r** [comment]
Yes he is. I've tried to add the organisation iobroker:developers but I've received "forbidden".

**Comment by mcm1957** [comment]
This issue seems to be outdated

This issue suggests to update the stable version of this adapter to ${issue.to} but the current stable version is already ${stable[adapter].version}.

So this issue should be closed.

**Pull request merged**
