### PR TITLE
added loqed to latest

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.loqed](https://github.com/foxriver76/ioBroker.loqed)
[Downloads](https://www.npmjs.com/package/iobroker.loqed) 
[NPM](https://nodei.co/npm/iobroker.loqed/)

- [ ] :heavy_exclamation_mark: [E118] Versions in [package.json](https://github.com/foxriver76/ioBroker.loqed/blob/master/package.json) and in [io-package.json](https://github.com/foxriver76/ioBroker.loqed/blob/master/io-package.json) are different
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/foxriver76/ioBroker.loqed/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "loqed" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.loqed](https://github.com/foxriver76/ioBroker.loqed)
[Downloads](https://www.npmjs.com/package/iobroker.loqed) 
[NPM](https://nodei.co/npm/iobroker.loqed/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "loqed" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
