### PR TITLE
Add nctalk adapter to latest

### PR DESCRIPTION
**Pull request by jjqoie**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nctalk](https://github.com/jjqoie/ioBroker.nctalk)
[Downloads](https://www.npmjs.com/package/iobroker.nctalk) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.nctalk/)

- [ ] :heavy_exclamation_mark: [E518] "@alcalzone/release-script" is used, but ".releaseconfig.json" not found
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2023 Jochen Gerster <jjqoie@gmx.de>" at the end of [README.md](https://github.com/jjqoie/ioBroker.nctalk/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 Jochen Gerster <jjqoie@gmx.de>" at the start of LICENSE
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/jjqoie/ioBroker.nctalk/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/jjqoie/ioBroker.nctalk/blob/master/io-package.json)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "nctalk" in latest repository
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by jjqoie** [comment]
Hi
[E518] "@alcalzone/release-script" is used, but ".releaseconfig.json" not found
seems this came with a newer version of "@alcalzone/release-script" - what should I do now ? update to latest "@alcalzone/release-script"package ?
Anything special to take care of when updating or?

thanks
best regards
Jochen

**Comment by jjqoie** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nctalk](https://github.com/jjqoie/ioBroker.nctalk)
[Downloads](https://www.npmjs.com/package/iobroker.nctalk) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.nctalk/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/jjqoie/ioBroker.nctalk/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/jjqoie/ioBroker.nctalk/blob/master/package.json) (0.3.1) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.nctalk) (0.3.0)
- [ ] :eyes: [W400] Cannot find "nctalk" in latest repository
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by jjqoie** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nctalk](https://github.com/jjqoie/ioBroker.nctalk)
[Downloads](https://www.npmjs.com/package/iobroker.nctalk) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.nctalk/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W202] Version of [package.json](https://github.com/jjqoie/ioBroker.nctalk/blob/master/package.json) (0.3.1) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.nctalk) (0.3.0)
- [ ] :eyes: [W400] Cannot find "nctalk" in latest repository
- [ ] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package


*Add comment "RE-CHECK!" to start check anew*

**Comment by jjqoie** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nctalk](https://github.com/jjqoie/ioBroker.nctalk)
[Downloads](https://www.npmjs.com/package/iobroker.nctalk) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.nctalk/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "nctalk" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jjqoie** [comment]
HI Martin,
thanks for checking :-)

On your last point - yes I was not sure about this point as well and about the prerequisite for "stable"...
For me the adapter runs "stable" :-D and it was also tested/used by several others (~20 if this number can be trusted) for approx 1 year and at the beginning quite some debugging was required but then there were no further problems reported so far...  here the forum entry https://forum.iobroker.net/topic/49298/neuer-adapter-nextcloud-talk-messenger

best regards
Jochen

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nctalk](https://github.com/jjqoie/ioBroker.nctalk)
[Downloads](https://www.npmjs.com/package/iobroker.nctalk) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.nctalk/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "nctalk" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
Please remove node 12 and 14 from test-and-release.yml and add n ode 18 and (optionally) add node 20 to testing matrix.
Node 14 is no longer supported and tests will fail since 22.5.2023.
Node 12 tests fail a longer time ago


In addition PLEASE REMOVE sources-dist-stable.json from this PR. Adapters MUST be some time available at lastest before they are allowed to be added to stable. So adding a new adapter to latest AND stable at the same time is inapproriate.

Thanks
McM1957

**Comment by jjqoie** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.nctalk](https://github.com/jjqoie/ioBroker.nctalk)
[Downloads](https://www.npmjs.com/package/iobroker.nctalk) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.nctalk/)

:thumbsup: No errors found
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W400] Cannot find "nctalk" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by jjqoie** [comment]
Any news here?

**Comment by mcm1957** [comment]
> Any news here?

Sorry to say still waiting for official review by @Apollon77 .

**Comment by jjqoie** [comment]
Ok 1. and 2nd is done
on the 3rd - is this the sequence how it should be?
if ack == false
then for example sent message to nextcloud talk
setstate ack to true?

-----
 onStateChange(id, state) {

        const as = id.split(".");
        const statename = as[as.length - 1];
        let obj = undefined;
        let fullpath = this.adapter.config.upload_path;


        switch (statename) {
            case "SendMessage":
                if (state.ack == false) {
                    // ack==false are commands to be executed
                    this.SendToGroup(state.val);
                    this.adapter.setState(id, state.val, true);
                }
                break;

**Comment by jjqoie** [comment]
On the last point I'm not sure - Are you talking about the eventloop and the eventlooptrigger?


```
    _EventloopTrigger(event, timeout) {

        if (timeout) {
            setTimeout((function (event) {
                this.emit("Eventloop", event);
            }).bind(this), timeout, event);
        } else {
            this.emit("Eventloop", event);
        }
    }
```

**Comment by Apollon77** [comment]
State.ack:
This in the end depends on your logic. In many cases after a controlling action also new values come in and so they are set with ack=true in any case. if it is a state that just sends something out then yes you can also ack the value after successfull action is executed. Or you define it as "send only" state with read=false, then it is only ritable then ack= true is formally not needed

Eventloop:
When I understood the code right then once started tvia this event loop  (and other code places) always a timeout runs and data are updated any 30s ... in iobroker you need to be able to stup these timers to stop the adapter - especially relevant in compact mode.

So yes you shsould save the timeout you set there and allow it to be cleared on unload

**Comment by jjqoie** [comment]
thanks for the reply

On the eventloop - just to be sure you are talking about this timeout?
```
    _EventloopTrigger(event, timeout) {

        if (timeout) {
            **setTimeout((function (event) {**
```
actually this timeout is only used/called in case of an error case and this is if their is an error with the http REST API request to nextcloud talk server. There is a check (waitmsgongoing) that only one http request is pending at the same time. 

Normally (none error case) the event loop takes care of the startup going to the different states of the state machine to gather all required information from the nextcloud talk server needed by this adapter
And then it only takes care of polling for new messages using an http request and the result of this http and initiate then a new one
https://nextcloud-talk.readthedocs.io/en/latest/chat/#receive-chat-messages-of-a-conversation

Or is your point is more that you need a graceful stop of the whole adapter/loop independent of the timeout call or the http request ?

**Comment by jjqoie** [comment]
I'm still stuck what exactly I should change - please advise..

**Comment by jjqoie** [comment]
Anyone who can help ?

**Comment by mcm1957** [comment]
Sorry
My fault. Will try to respond this week.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

Sorry for the late reply. I did a complete rereview including special attention to the points appollon77 already noted.
Please see my feedback based on my personal oppinion. Please feel free to contact @Apollon77 if you cannot follow my suggestions or want to discuss some special aspects.

- [ ] package.json should specifiy required nodejs version

  Please consider adding an engines clause to package.json. Especially if you use adapter-core 3.x.x or newer nodegs 16 or newer must be reuested:
  ```
    "engines": {
    "node": ">= 16"
  },
  ```
  
- [ ] please verify that all dependencies are up to date

  Some dependencies are outdated. Please update to current releases if no special reason to keep an older version exists.
  
  i.e. adapter-core is outdated for sure.

- [ ] on message handler seems to be unused

  There seems to be no fucntional code within onMessage handler (https://github.com/jjqoie/ioBroker.nctalk/blob/3686e3ad961797ce65a5174d3262d66e97adf829/main.js#L239). If this is correct, please remove onMessage handler and remove '"messagebox": true,' from io-package.json.
 
- [ ] onStateChange handler ignores ack flag 

  The adapter must honor the ack flag when processing onStateChange events. Whenever the onStateChange handler is called for an own state (a state owned by the processing instance of the adapter) it must ignore this event if the ack flags is set. Only stateChanges with ack==false are allowed to be processed normally. Exceptions might exist - please discuss if you fell a need for that.

  When processing foreign states (states not created by this adapter)  processing most likely should only occure if the ack flag is true - but there might be exceptions.

- [ ] creation of folders seems to be missing

  Every folder (device, folder, ...) must be created explicitly. You may not create a state name.Sharefile.NetxCloudPath without creating a folder (?) ShareFile first.
  https://github.com/jjqoie/ioBroker.nctalk/blob/3686e3ad961797ce65a5174d3262d66e97adf829/lib/iobtalk.js#L40

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whnever a dedicated role exists.

  Many of your states with role state look like text roles. Please review / adapt to rules linked above.

- [ ] use not too long names for states 

  The text used here looks more like a description (which ia available too)
  https://github.com/jjqoie/ioBroker.nctalk/blob/3686e3ad961797ce65a5174d3262d66e97adf829/lib/iobtalk.js#L43

- [ ] avoid console.log

  console.log should be avoided as it is only useable with a dubugger. Use adapter.log.debug or adapter.log.silly instead.
  Note that adapter.log.* output is visible at debugger console too, so theres seems to be no need for console.log at all.

- [ ] mionimize info logs to contain only really important info

  I do not think thats its very importand for users to know every tme when a working directory is checkd to exist
  https://github.com/jjqoie/ioBroker.nctalk/blob/3686e3ad961797ce65a5174d3262d66e97adf829/lib/webdavsupport.js#L27
  Please check info logs and use i.e. debug or silly for if applicable.

- [ ] why do you subscribe LastReceivedMessage?

  Subscribing on states only written by your own adapter is normally uneccessary overhead. The handler does not do anything more than logging the change. So I suggest to remove the handling part and the subscription adn to move the logging near setState.


- [ ] github dependabot support seems to be missing
  
  It looks like you did not yet setup dependabot support; at least .github/dependaboit.yml is missing.
  
  Please consider setting up dependabot support (and to ease life the workflow auto-merge.yml). Dependabot will ensure that your adapter uses the most recent versions of external packages and avoids problem due to outdted base libraries. Dependabit provides PRs at you repository to update the dependencies. Depending on you setting, especially on auto-merge.yml configuration no or only minor revisions will be outmatically merged into you main branch. All major revisions msiut (ans should) be reviewed by you. 
  
- [ ] nextcloud library and timeouts

  Apollon77 already noted: 
  ```
  in fact this nctalk library has one big downside ... it never stops. The timeouts used in there are not tracked and can not be 
  stopped, soideally that should be enhanced because else this will create big issues in compact mode
  ```
  
  NextCloud does not provide some clear stop/shutdown entry point (or you do not use it). So currently the adapter canot stop all (!) running timers or asynchronous operations in progress. This will cause very big problems in compact mode as in compact ode the adapter shares a process with other adapters. So when unloading this adapter the timers could possibly access adress space of other adapters.
  If you cannot ensure / use a clean stopp/exit functionaliyt of nctalk I suggest to block compact ode for this adapter by setting compact:false at io-package.json.

  to anser your Questsions

  ```
  Would this be onUnload(callback) ??
  Question if onUnload is called do you need an immediate reaction or how fast must the adapter been stopped?
  ````
  
  Yes onOnload is called whenever a adapter is stopped regularly. Withon onAOnlad every executiong timer, intervall or other asynchronously running code must be stopped. This response should be as fast as possible, as far as I know the default is 500ms which could be extended in general altghough this should be avoided.

  Normally adapter regsiter all timer / intvervals createwd and call clearTimer / Intervall during inOnload to abort running timers.

  It's up to you to decide wether to implement a clean unload handling or to leave it "direty" and block compact mode. I would accept both.

Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by jjqoie** [comment]
Hello

concerning "avoid console.log"
Is there any simple approach to use the adapter logging (this.log.info) without the need to propagate the "log" instance to all submodules ? For example a global function or adapter global function?

thx
Jochen

**Comment by mcm1957** [comment]
As far as I know most dev propagate the 'this' (=adapter) info to all submodules during creating them.
But maybe you would get better feedback when aksing at our telegram channel (invite links at https://www.iobroker.dev).

Anyway I would like to state, that usage of console.log is NOT blocking for latest. So feel free to keep using it if you prefer. The major disadvantage is that console.log output is not (easily) retrievable from users while instrcuting them to set logging to debug or sille is an easy thing (at least most of the time :-) ).

**Comment by mcm1957** [comment]
reminder 31.12.2023

**Comment by mcm1957** [comment]
@jjqoie 

Happy New Year !

How shall we continue?
Do you need any help?

**Please let me/us know if you encounter any problem and which timefram you expect to fix the mentionend issues.**

mcm1957

reminder 15.01.2024

**Comment by jjqoie** [comment]
Also happy new year

I have created a branch for this and created an issue to track the latest recent points...
https://github.com/jjqoie/ioBroker.nctalk/issues/12#issue-2061784329
https://github.com/jjqoie/ioBroker.nctalk/commits/2150%23issuecomment-1651871315/

On "why do you subscribe LastReceivedMessage?"
The idea is in case there is a burst of new messages - to implement a handshake to handle them message by message and not risk losing a messages - maybe this is not required if there is already a queuing mechanism in the object state instance ??
What what happen if I quickly update the object value without being acked?

On "github dependabot support seems to be missing"
If you have any reference / guide on your hand - would be helpful

on " nextcloud library and timeouts"
Currently adding shutdown functions - for any timeouts and https open connections
stupid question - how can I see if the adapter really was fully stopped?

br
jochen

**Comment by mcm1957** [comment]
Sorry fro the late reply.

> On "why do you subscribe LastReceivedMessage?" The idea is in case there is a burst of new messages - to implement a handshake to handle them message by message and not risk losing a messages - maybe this is not required if there is already a queuing mechanism in the object state instance ?? What what happen if I quickly update the object value without being acked?

OK, 
I do not really understand why subscribing to this state shoudl help avoiding or handling burst at other states. But as far as I know there is NO queuing at any states. You will always read the last value written to a state. If you need more datails please contact @Apollon77 or Foxriver76. In addtion such questsions would be discussed at out telegram channels at best. Invitelinks see https://www.iobroker.dev

> On "github dependabot support seems to be missing" If you have any reference / guide on your hand - would be helpful

You have a PR for this

> on " nextcloud library and timeouts" Currently adding shutdown functions - for any timeouts and https open connections stupid question - how can I see if the adapter really was fully stopped?

I do not know a way to determine "was fully stopped". And I do not really understand what you are meaning with this sattement. Whenever an adapter is stopped onUnload is called by js-controller. At this routine the adapter must stop all timers, interval timer, subprocesses etc. it has created. After returning from onUnload js-controlelr will terminate the adapter process if applicable or unload the mode (details depend on using copmpact mode or not).

So the requirement is that the adapter must stop whatever it startet.
And of couse the same is required fro all external libraries which should provide some cleanup / unload / terminate etc. entrypoint.

At non compact mode the adapter process will be terminated cleanung up most things anyway. But the user might opt to use compact mode. When using compact mode multiple adapters will share one process. When stopping an adapter tjs.controller unloads this adapters code. So if any timers etc. are still running theres a high risk the this process crashes (due to trying to execute already unloaded code) and so other adapters are effected.

So please ensure that you external library provides the possibility to cleanup everything. If this is not available a potenial option would be to block compact mode for this adapter.


**Please let me/us know (by adding a comment) when all issues noted earlier are processed by you and a new review seesm to be appropiate.**

**Comment by mcm1957** [comment]
How should we continuer?
Do you need any further help?

Please let me/us know (by adding a comment) when all issues noted earlier are processed by you and a new review seesm to be appropiate.

If there is no respnse until 28.2.2024 this PR might be closed.

reminder 15.2.2024

**Comment by mcm1957** [comment]
How should we continue?
Do you need any further help?

**Please let me/us know (by adding a comment) when all issues noted earlier are processed by you and a new review seesm to be appropiate.**

**If there is no response until 28.2.2024 this PR might be closed.**

reminder 22.2.2024

**Comment by jjqoie** [comment]
hi
still working on the "nextcloud library and timeouts" item, which takes a bit longer as I also want to take care of all active http requests also in the other states used during startup.
Could it be that using the "dev-server watch", that the adapter can't be stopped?
BR
Jochen

**Comment by mcm1957** [comment]
Thanks for feedback. As long you are working on the adapter everything is fine.

I do not really undersatnd you question. In general the dev-server should show the same behavior as the normal js-controller. Maybe you could try dev-server run which does not start the adapter and start the adapter afterwards using you ide (i.e. vs-code). But discussing dev-server is a little bit OT here. Please join our telegram groups (or discord) You find links at www.iobroker.dev. There should be devs to discuss the specific problem with you and help solvong it. 

reminder 07.03.2024

**Comment by mcm1957** [comment]
Any news here?
Do you know any timeframe wh  to expect a new revier after your changes?

reminder 1.5.2024

**Comment by mcm1957** [comment]
Any news here?
Do you know any timeframe wh to expect a new review after your changes?

Please let us know whether you are still working at this adapter. Let us know if you need some help or simply more time.

**If there is no reaction until 31.5.2024 we will consider closing this PR.** (Of course you are welcome to open a new PR at any time.) 

reminder 15.5.2024

**Comment by mcm1957** [comment]
Any news here?
Do you know any timeframe wh to expect a new review after your changes?

Please let us know whether you are still working at this adapter. Let us know if you need some help or simply more time.

**If there is no reaction until 31.5.2024 we will consider closing this PR. (Of course you are welcome to open a new PR at any time.)**

reminder 1.6.2024

**Comment by mcm1957** [comment]
As there was no reaction this PR has been closed.

**Please feel free to open a new PR as soon as you think the adapter is ready for a new review**

**Pull request closed without merging**
