### PR TITLE
Update  go-e to 1.0.29

### PR DESCRIPTION
**Pull request by MK-2001**
Push from 1.0.27 to 1.0.29

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@MK-2001 

There are some issues which must be fixed before updating stable revision:

- [ ] README.md does not include a changelog / revision history. Please add at least the last 5 changes into README.md. See other Adapters or the templates for an example. No new release is required for this fix, it's sufficient if README:md is corrected. Changelog is required at README.md as admin relies on it.

- [ ] It's ok to move older changelogs to an seperated file. Please name this file CHANGELOG_OLD.md and place it at root directory of the adapter. If you are using @AlCalzone/release-script this script can move older changelogs to CHANGELOG_OLD.md automatically.  No new release is required for this fix, it's sufficient if file is created / adapted.

- [ ] check and adapt testing

  Standard iobroker testing is required but seems to be missing. Please add and setup ./github/workflows/test-and-release.yml and the corresponding files at /test.

  Tests for node 16 is mandatory unless you require node 18 and higher (at package.json). Tests for node 18 is mandatory as this is the recommended node version and node 16 will be eol and deprected Q3/2023. Consider adding node 20 tests unless you already know incompatibilities.

  So the recommended testmatrix is [16.x, 18.x, 20.x] or [18.x, 20.x] depending on engines requirments setting at package.json

  As node 16 is end-of-life now, it's ok to remove node 16 from testing. In this case please require node 18 as minimum node version at package.json.

  If you need help setting up correct testing, please let us know. I can provide a PR if required.

  No new release is required for this fix, it's sufficient if if tests run successfull with current master/main commit.

- [ ] github dependabot support seems to be missing

  It looks like you did not yet setup dependabot support; at least .github/dependaboit.yml is missing.

  Please consider setting up dependabot support (and to ease life the workflow auto-merge.yml). Dependabot will ensure that your adapter uses the most recent versions of external packages and avoids problem due to outdted base libraries. Dependabit provides PRs at you repository to update the dependencies. Depending on you setting, especially on auto-merge.yml configuration no or only minor revisions will be outmatically merged into you main branch. All major revisions msiut (ans should) be reviewed by you.

  Dependabot support is NOT mandatory, this is only suggestion. But in any case update your dependencies for the next release. axios for example is very outdated, and most likely other dependencies will be too. ioBroker adapter-core needs an update too. But for this release I will not yet consider this blocking.

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

**Comment by MK-2001** [comment]
@mcm1957 
Can you please send mit this PR:
```If you need help setting up correct testing, please let us know. I can provide a PR if required.```
and maybe as well a basic configuration for dependabot.

**Comment by MK-2001** [comment]
RE-CHECK!

**Comment by MK-2001** [comment]
RE-CHECK!

**Comment by MK-2001** [comment]
RE-CHECK!

**Comment by MK-2001** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@MK-2001 
FYI: Its NOT necessary to start repository checks after every check here. You can use the repochecker at www.iobroker.dev too.

**Comment by mcm1957** [comment]
PR to adapt testing https://github.com/MK-2001/ioBroker.go-e/pull/201

Please check / merge befor next release.

**Pull request merged**
