### PR TITLE
LaMetric, YouTube and Luftdaten adapter update

### PR DESCRIPTION
**Pull request by klein0r**

### CODE REVIEW

**Comment by Apollon77** [comment]
both new adapter go directly to stable? Do you have testing threads from Forum or such?

**Comment by Apollon77** [comment]
Review Results:
**Lametric:** (also see https://adapter-check.iobroker.in/)
* Travis-ci and Adapter testing not enabled, please enable (Blocker)
* Bluefox not added to npm as owner (Blocker)
* on-unload should cleanInterval all intervals! (please test in compact mode anso that stopping really stops all actions) (Blocker)
* Please check again all roles (e.g. read only boolean like "meta.bluetooth.available" should be indicator or such, see https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md
* Personal comment: setInterval is dangerous when used together with "external" communication, because it will fire the next call independently if the one before was finished. Using "setTimeout at the end of one process to start the next one is better

**Youtube**
* travis-ci and adapter testing not enabled (Blocker)

Thank you for checking and adjusting

**Comment by klein0r** [comment]
@Apollon77 I'm currently working on CI integration. Which ioBroker adapter has the best (up to date) test coverage and can be used as a template/reference to learn more about unit and integration testing in nodejs / iobroker.

**Comment by klein0r** [comment]
Ok, I've added all repositories to TravisCI and all builds are green right now (just ioBroker testing basic tests)

**Comment by Apollon77** [comment]
If you also make sure clearInterval is used in on unload I can accept the adapters in repo.

**Comment by klein0r** [comment]
Okay I've switched to setTimeout and fixed all eslint issues

**Comment by Apollon77** [comment]
Thank you

**Comment by klein0r** [comment]
❤️

**Pull request merged**
