### PR TITLE
Added adapter epson_xp540

### PR DESCRIPTION
**Pull request by tikodu**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.epson_xp540](https://github.com/tikodu/ioBroker.epson_xp540)
[Downloads](https://www.npmjs.com/package/iobroker.epson_xp540) 
[NPM](https://nodei.co/npm/iobroker.epson_xp540/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:tikodu/ioBroker.epson_xp540.git. Expected: git+https://github.com/tikodu/ioBroker.epson_xp540.git
- [ ] :heavy_exclamation_mark: [E506] Word "epson_xp540 adapter settings" is not translated to russian in [admin/words.js](https://github.com/tikodu/ioBroker.epson_xp540/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "IP or hostname" is not translated to russian in [admin/words.js](https://github.com/tikodu/ioBroker.epson_xp540/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "Update interval in minutes (1 - 60)" is not translated to russian in [admin/words.js](https://github.com/tikodu/ioBroker.epson_xp540/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :eyes: [W400] Cannot find "epson_xp540" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@tikodu plese check the adapter checker comments

**Comment by tikodu** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.epson_xp540](https://github.com/tikodu/ioBroker.epson_xp540)
[Downloads](https://www.npmjs.com/package/iobroker.epson_xp540) 
[NPM](https://nodei.co/npm/iobroker.epson_xp540/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "epson_xp540" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@tikodu Please look into some better error handling, else the adapter will crash directly because he will be started immediately also without first config entered. https://github.com/tikodu/ioBroker.epson_xp540/runs/1872289944#step:6:205

Additionally honestly ... I still think that for querying one URL every 5 minutes a schedule mdoe approach makes more sense then always having 50-80MB RAM in use. What do you think?

**Comment by tikodu** [comment]
> @tikodu Please look into some better error handling, else the adapter will crash directly because he will be started immediately also without first config entered. https://github.com/tikodu/ioBroker.epson_xp540/runs/1872289944#step:6:205
> 
> Additionally honestly ... I still think that for querying one URL every 5 minutes a schedule mdoe approach makes more sense then always having 50-80MB RAM in use. What do you think?

Thank you for your feedback. I don't have any schedule adapters in my setup so far and therefore hadn't thought of this possibility. I have changed the adapter mode to schedule and improved the error handling.

**Comment by Apollon77** [comment]
Hey, cool, but why you need that 10s timeout at the end? if all your await/async are correct it should work without any timeout :-)

**Comment by tikodu** [comment]
> Hey, cool, but why you need that 10s timeout at the end? if all your await/async are correct it should work without any timeout :-)

Sorry for late response - the timeout is a workaround. Without the timeout the build pipline fails due to the integration test: 
`Test the adapter (in a live environment)
       The adapter starts:
     Error: The adapter startup was interrupted unexpectedly with code 1`

The error handling in the adapter stops the cron job if there is no valid configuration. Do you have any idea how the integration test accepts the immediate termination of the adapter?

**Comment by Apollon77** [comment]
Can you link me to such a test result because on github actions it does not seem to happen ...

**Comment by tikodu** [comment]
> Can you link me to such a test result because on github actions it does not seem to happen ...

https://github.com/tikodu/ioBroker.epson_xp540/runs/2308339634

**Comment by Apollon77** [comment]
try to add allowedExitCodes ... see in  https://github.com/ioBroker/testing#adapter-startup-integration-test

**Comment by tikodu** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.epson_xp540](https://github.com/tikodu/ioBroker.epson_xp540)
[Downloads](https://www.npmjs.com/package/iobroker.epson_xp540) 
[NPM](https://nodei.co/npm/iobroker.epson_xp540/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "epson_xp540" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by tikodu** [comment]
> try to add allowedExitCodes ... see in https://github.com/ioBroker/testing#adapter-startup-integration-test
@Apollon77 Yeah, that's it - thanks a lot!

**Comment by Apollon77** [comment]
@tikodu ready for next review round?

**Pull request merged**
