### PR TITLE
added adpater sureflap to latest

### PR DESCRIPTION
**Pull request by Sickboy78**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

:thumbsup: No errors found

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

:thumbsup: No errors found

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Morluktom <strassertom@gmx.de>" at the start of LICENSE

### [ioBroker.sureflap](https://github.com/Sickboy78/ioBroker.sureflap)
[Downloads](https://www.npmjs.com/package/iobroker.sureflap) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sureflap/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.sureflap)!. Please execute in adapter directory: `npm owner add bluefox iobroker.sureflap`
- [ ] :eyes: [W400] Cannot find "sureflap" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Sickboy78** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

:thumbsup: No errors found

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

:thumbsup: No errors found

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Morluktom <strassertom@gmx.de>" at the start of LICENSE

### [ioBroker.sureflap](https://github.com/Sickboy78/ioBroker.sureflap)
[Downloads](https://www.npmjs.com/package/iobroker.sureflap) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sureflap/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.sureflap)!. Please execute in adapter directory: `npm owner add bluefox iobroker.sureflap`
- [ ] :eyes: [W400] Cannot find "sureflap" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Sickboy78** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alias-manager](https://github.com/sbormann/ioBroker.alias-manager)
[Downloads](https://www.npmjs.com/package/iobroker.alias-manager) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alias-manager/)

:thumbsup: No errors found

### [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor)
[Downloads](https://www.npmjs.com/package/iobroker.fuelpricemonitor) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fuelpricemonitor/)

:thumbsup: No errors found

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Morluktom <strassertom@gmx.de>" at the start of LICENSE

### [ioBroker.sureflap](https://github.com/Sickboy78/ioBroker.sureflap)
[Downloads](https://www.npmjs.com/package/iobroker.sureflap) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.sureflap/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "sureflap" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Sickboy78** [comment]
@GermanBluefox ping

**Comment by Apollon77** [comment]
@Sickboy78 ping what?

**Comment by Sickboy78** [comment]
ping ich hab bluefox als owner hinzugefügt und somit den Grund fürs must be fixed label beseitigt

**Comment by Apollon77** [comment]
ahhhh , thx :-)))

**Comment by Apollon77** [comment]
Hi,

here some review comments:
* that feels wrong https://github.com/Sickboy78/ioBroker.sureflap/blob/master/admin/index_m.html#L101
* these objects are already created in io-package.json, so unneeded https://github.com/Sickboy78/ioBroker.sureflap/blob/master/main.js#L558-L559
* do you really make the object creation with every "set a value"? e.g. https://github.com/Sickboy78/ioBroker.sureflap/blob/master/main.js#L570-L572
* you need to set the state value in the callback of object creation ... else you get warnings in js.controller 3.2 (try it ... delete all objects or instance, creaze a new one and start adapter, check logs! (many places all over in your code)
* you always decrypt the passwort with the default key?? https://github.com/Sickboy78/ioBroker.sureflap/blob/master/main.js#L1007 // https://github.com/Sickboy78/ioBroker.sureflap/blob/master/admin/index_m.html#L22 ... maybe think about removing all this and requiring js-controller 3.0 and admin 4.0.9, so that all encrypt/decrypt is done automatically?
Please check and adjust it

**Comment by Sickboy78** [comment]
Danke fürs Feedback, ich schaus mir an.

**Comment by Sickboy78** [comment]
@Apollon77 bitte re-review
Alle Punkte gefixt.
Anmerkung zum dritten Punkt: Hier https://github.com/Sickboy78/ioBroker.sureflap/blob/419c60dbd048420884f8779c6c29961bdd2003a7/main.js#L648 ist es weiterhin notwendig, da diese Objekte dynamisch gelöscht und erzeugt werden.

**Comment by Apollon77** [comment]
* https://github.com/Sickboy78/ioBroker.sureflap/blob/master/main.js#L47 should not be needed. since controller 2 I think we have a setObjectsNotExistsAsync ... but works that way.

Thank you!

**Pull request merged**
