### PR TITLE
Update panasonic-comfort-cloud to 2.2.2

### PR DESCRIPTION
**Pull request by marc2016**

### CODE REVIEW

**Comment by mcm1957** [comment]
2.2.2 created 16.09.2023

**Comment by marc2016** [comment]
RE-CHECK!

**Comment by marc2016** [comment]
Because of an update of the Panasonic REST API the adapter isn't usable with version 2.2.0 anymore.

**Comment by mcm1957** [comment]
Ok, thanks for Info.

**Comment by mcm1957** [comment]
2.2.2 created 16.09.2023
34 user (>10%)
OK

**Pull request merged**
