### PR TITLE
Update sources-dist.json hinzufügen vom Omron-fins Adapter

### PR DESCRIPTION
**Pull request by TheBam1990**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.omron-fins](https://github.com/TheBam1990/ioBroker.omron-fins)
[Downloads](https://www.npmjs.com/package/iobroker.omron-fins) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.omron-fins/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "omron-fins" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi,

sorry for the late review, here some feedbacks:
* please make the readme.md only english. you can place other language in a separate docs folder ... see best practies
* you have defined info.connection in io-package ... so should not be needed in code https://github.com/TheBam1990/ioBroker.omron-fins/blob/master/main.js#L146
* Do you really want to add the "reply" handler to client each time that method is called? https://github.com/TheBam1990/ioBroker.omron-fins/blob/master/main.js#L197
* why async ? https://github.com/TheBam1990/ioBroker.omron-fins/blob/master/main.js#L218
* is "client" having a persiatent connection to the device?  of yes you need to close this connection in "unload" and clean up all other resources!

Please check and adjust. Thank you

**Comment by TheBam1990** [comment]
So Angaben geändert. 
*Eine 2. Readme erstellt für deutsch andere auf Englisch umgestellt. 
*info.connection aus der Main.js entfernt da es ja schon in der io-package vorhanden ist
* Leider muss dies so bei der Funktion sein. Wollte es auch lieber etwas anders lösen. 
* Async entfernt
* Client verbindet sich fragt werte ab bekommt werte und unterbricht die verbindung

**Pull request merged**
