### PR TITLE
Updated all adapters like bmw, broadlink2 and km200 to npm version in stable.

### PR DESCRIPTION
**Pull request by frankjoke**

### CODE REVIEW

**Comment by Apollon77** [comment]
How long these versions are out? broadlink was updated to 1.8.0 3hours ago ... Is there already a "proof" of stability?

**Comment by frankjoke** [comment]
Th 1.8.0 was on Git for about 2 weeks and in forum used by several users. I just changed one file today to keep it in sync with the same files in other adapters before I pushed it to npm.

The others were in use and on npm since more than a month.

**Comment by frankjoke** [comment]
p.s.: The main changes in the last weeks were because of Apollon's test changes :)

**Comment by Apollon77** [comment]
Great!

**Pull request merged**
