### PR TITLE
new adapter: add philips tv

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.philips-tv](https://github.com/AlCalzone/ioBroker.philips-tv)
[Downloads](https://www.npmjs.com/package/iobroker.philips-tv) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.philips-tv/)

- [ ] :heavy_exclamation_mark: [E125] External icon not found under URL: https://raw.githubusercontent.com/AlCalzone/ioBroker.philips-tv/main/admin/philips-tv.png
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/AlCalzone/ioBroker.philips-tv/blob/master/io-package.json)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, zh-cn)
- [ ] :eyes: [W400] Cannot find "philips-tv" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
URL already fixed, it seems like checker uses only the initial PR status

**Comment by Apollon77** [comment]
review comments:
* Please add admin >= 5.x global dep because only jsonconfig is available

Rest is fine

**Pull request merged**
