### PR TITLE
adding adapter Discovergy

### PR DESCRIPTION
**Pull request by DutchmanNL**
https://github.com/DutchmanNL/ioBroker.discovergy

### CODE REVIEW

**Comment by Apollon77** [comment]
Sorry, ich bin der Spielverderber :-))

Please check: https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository

**Comment by Apollon77** [comment]
And testing for repo is broken ... https://raw.githubusercontent.com/DutchmanNL/ioBroker.discovergy/blob/master/io-package.json is an invalid URL ...

**Comment by GermanBluefox** [comment]
Please publish on npm

**Comment by DutchmanNL** [comment]
> And testing for repo is broken ... https://raw.githubusercontent.com/DutchmanNL/ioBroker.discovergy/blob/master/io-package.json is an invalid URL ...

fixed

**Comment by DutchmanNL** [comment]
> Please publish on npm

done

https://www.npmjs.com/package/iobroker.discovergy

**Comment by DutchmanNL** [comment]
> Sorry, ich bin der Spielverderber :-))
> 
> Please check: https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository

1) = correct
2) = correct
3) = correct
4) = present
5) = present
6) = correct
7) = dont realy understand this one will need to figure out it its mandatory for latest repro
8) = done
9) = correct
10) = corrected
11) = published :)
12) = adding organisation failed, added bluefox as owner
`Forbidden : -/team/iobroker/developers/package`
13) = correct ?
14) = correct

Can you please review and provided suggestions if i missed something ?
Thank you !

**Comment by DutchmanNL** [comment]
repository also added to travis for testing, requirement 7 :)

**Comment by Apollon77** [comment]
Cool, will check this night!

**Comment by Apollon77** [comment]
congrats, great work. accepted :-)

**Pull request merged**
