### PR TITLE
Update sources-dist-stable.json to bring ioBroker.beckhoff 1.2.2 to stable

### PR DESCRIPTION
**Pull request by dkleber89**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.beckhoff](https://github.com/dkleber89/ioBroker.beckhoff)
[Downloads](https://www.npmjs.com/package/iobroker.beckhoff) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.beckhoff/)

:thumbsup: No errors found
- [ ] :eyes: [W505] setTimeout found in "beckhoff.js", but no clearTimeout detected
- [ ] :eyes: [W801] .npmignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@dkleber89 We now check a bit deeper about compact more compatibilityand you use a timeout which is not stopped in "unload", but this will break compact mode! Can you please adjust that?

**Comment by dkleber89** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.beckhoff](https://github.com/dkleber89/ioBroker.beckhoff)
[Downloads](https://www.npmjs.com/package/iobroker.beckhoff) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.beckhoff/)

:thumbsup: No errors found
- [ ] :eyes: [W801] .npmignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by dkleber89** [comment]
Closes https://github.com/dkleber89/ioBroker.beckhoff/issues/31

**Pull request merged**
