### PR TITLE
Add Growatt solar inverter

### PR DESCRIPTION
**Pull request by PLCHome**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
Why doesn't that work? What do I have to do so that Travis is recognized.
I've done everything that is in the forum and in the instructions.
Traves checks as OK.

image

image

**Comment by Apollon77** [comment]
Ok, thx!

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
> Why doesn't that work? What do I have to do so that Travis is recognized.
> I've done everything that is in the forum and in the instructions.
> Travis checks as OK.
> 
> image
> 
> image

The same...

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
How do I get this adapter into the ioBroker repository?

**Comment by Apollon77** [comment]
@PLCHome with me or Bluefox finding time to review the adapter :-) Sorry, but I'm currently on vacation, so time is very rare

**Comment by PLCHome** [comment]
thanx

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.0.6
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@PLCHome Here some review comments
* as checker told aboe news are missing for 0.0.6
* with     "@iobroker/adapter-core": "^2.4.0", the js-controller dep needs to be >=2.0.0!
* io-package native defined 5 values, admin sets 7
* it seems to store a password, please do this encrypted - please see Repo Readme for best practices!

Please check and fix and inform us when done

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E118] Versions in [package.json](https://github.com/PLCHome/ioBroker.growatt/blob/master/package.json) and in [io-package.json](https://github.com/PLCHome/ioBroker.growatt/blob/master/io-package.json) are different
- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.0.6
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E118] Versions in [package.json](https://github.com/PLCHome/ioBroker.growatt/blob/master/package.json) and in [io-package.json](https://github.com/PLCHome/ioBroker.growatt/blob/master/io-package.json) are different
- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 0.0.6
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
@Apollon77 fixed:
* as checker told aboe news are missing for 0.0.6
* with "@iobroker/adapter-core": "^2.4.0", the js-controller dep needs to be >=2.0.0!
* io-package native defined 5 values, admin sets 7
* it seems to store a password, please do this encrypted - please see Repo Readme for best practices!

**Comment by PLCHome** [comment]
image

**Comment by PLCHome** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.growatt](https://github.com/PLCHome/ioBroker.growatt)
[Downloads](https://www.npmjs.com/package/iobroker.growatt) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.growatt/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "growatt" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by PLCHome** [comment]
@Apollon77:
All issues from review are fixed.

 [E300] Not found on travis. Please setup travis:
The repro is in Travis and OK
image

**Comment by PLCHome** [comment]
@Apollon77:
All issues from the review have been fixed. I would be happy if the review would be completed and the adapter could be finished.

One would be happy about it:
https://github.com/PLCHome/ioBroker.growatt/issues/1#issuecomment-706708855

**Comment by PLCHome** [comment]
@Apollon77 @GermanBluefox 
All issues from the review have been fixed. I would be happy if the review would be completed and the adapter could be finished.

**Comment by PLCHome** [comment]
I've been trying to get this adapter into the ioBroker for more then 3 months. 
If it is not wanted, I can also stop the project. Should I?

I assume that at least the users and supporters of the adapter are against abort:
@yunagear @kopierschnitte

**Comment by kopierschnitte** [comment]
It would be a pity if this project will be aborted. The code works without any problems since I've started using it a few months ago and I would definitely call it stable.

**Comment by Apollon77** [comment]
@PLCHome No please donot stop. Yes we need to catch up with the reviews ... sorry for that

**Comment by yunagear** [comment]
Also for us a very important project!! As we want to use it for several plants together with iobroker and Grafana.

**Comment by Apollon77** [comment]
Hello,

sorry that it took that long. One personal note: an Interval is risky combined with external communication because interval fires independent if the run before was finished ... better is Timeouts that are set anew at the end of an action.

else is ok, I added the adapter to the repo

**Pull request merged**
