### PR TITLE
add adapter hydrawise to latest

### PR DESCRIPTION
**Pull request by SentiQ**
https://github.com/ioBroker/AdapterRequests/issues/195

### CODE REVIEW

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- [ ] Readme.md is very short

  The README.md of this adapter is very minimalistic. Theres no information about the functionality and the configuration inside.

  Please add a short description about the functionality of the adapter,  add links the the manufacturer site (if applicable) and add a description of the configuration of the adapter. If you provide an external documentation - which should be located at doc/xx directory - please add links to at least the english documentation. Also describe how to get the api-key required for configuration.

- [ ] sensitive information, especially passwords should be stored encrypted
  
  You configuration seems to contain passwords (or other sensitive information) which is not stored encrypted. As long as those information is not stored inside a table you can encrypt and secure this infomation simply by adding the following configuration to io-package.json. The iob runtime will encrypt / decrypt the data as required; no addition programming effort is required. Note that users will need to reenter this info one time after adding encryption, so drop a note at release notes.
  ```
  "encryptedNative": [
    "password",
    "data2"
  ],
  "protectedNative": [
    "password",
    "data2"
  ],
  ```
  I refer to the apiKey which seems to be an id which is (or at least should) not be public.

- [ ] sensitive information should not be logged into logfile

  To avoid publishing sensitive information when forwarding logs, those information should never be written into the logs but either omitted or at least partly masked so that the information cannot be misused. This relates at least to usernames, passwords, uniqui (user assigned) keys and tokens. In addition personal information like name, address, gegraphical coordinagtes should not be logged too.

- [ ] invalid characters should be filtered from object ids
  
  Some characters are not allowed to be used as part of an object id. If an object id is not hardcoded or even depending on user input you should ensure that such an object id does not contain an invalid character.  Iobroker provides the constant ```adapter.FORBIDDEN_CHARS```, i.e. by using the following snippet:
```
function name2id(pName) {
    return (pName || '').replace(adapter.FORBIDDEN_CHARS, '_');
}
```
  You retrive date from the api and  create states depending on the data returned. This data must be checked to contain only valid characters.

- [ ] onStateChange handler ignores ack flag 

  The adapter must honor the ack flag when processing onStateChange events. Whenever the onStateChange handler is called for an own state (a state owned by the processing instance of the adapter) it must ignore this event if the ack flags is set. Only stateChanges with ack==false are allowed to be processed.

  When processing foreign states which are output of another adapter  processing must only occure if the ack flag is true.

- [ ] reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully.
  
- [ ] error text seems to be wrong

   line 451 reads ```reject("Device IP is not configured");``` but the error should indoicate a missing api key.

- [ ] do not mix this.setTiemout / clearTimeout

   You are using this.setTimeout (what is OK). Bute please also use this.clearout to cancel those timers
 
  
Thanks for reading and evalutaing this suggestions.
McM1957

**Comment by SentiQ** [comment]
@mcm1957 I went through your suggestions and made a few changes in my code

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
- [ ] I detected some potential typo / cut and paste error:

  The id 'stopZone' indicates something is to be stopped. So the role 'button.start' seems to be incorrect. The same refers to  state 'schedule.stopall'. 'button.stop' is a valid role too so this role seems to match better if I understand the functionality correct.

- [ ] And please consider fixing
  👀 [W505] setTimeout found in "build/main.js", but no clearTimeout detected

  Although you are using this.setTimeout which is designed to clear pending timeouts (intervals) its considered a good praxis to explicitly clear all timeouts (intervals) at onUnload and leave the ioBroker class internal cleanup only as a safeguard.

  I leave this point to @Apollon77 to decide whether this is mandatory - or feel free to mention him directly for any discussion about this point.

**Comment by SentiQ** [comment]
RE-CHECK!

**Comment by SentiQ** [comment]
@mcm1957 I reviewed and fixed your suggestions

**Comment by mcm1957** [comment]
OK, lgtm

**Comment by mbhomie007** [comment]
Hello @Apollon77 @mcm1957

I hope you can integrate the adapter to latest without any trouble.
I will test it soon.
Thank you.

**Comment by mcm1957** [comment]
@SentiQ 

This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, ist OK to continue using this topic too.

**Comment by SentiQ** [comment]
> @SentiQ
> 
> This adapter has been released to latest repository and should be visible within 24h maximum.
> 
> Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.
> 
> Note: If an other testing topic already exists, ist OK to continue using this topic too.

It seems I don't have the right to create a new thread?

**Comment by mcm1957** [comment]
Possible
Please contact HOMORAN at forum to get matching rights.
Either in any other topic or by chat.
And state that you are devbof adapter snd want to create test topic

Thanks

**Pull request merged**
