### PR TITLE
Added synology

### PR DESCRIPTION
**Pull request by instalator**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.synology](https://github.com/instalator/ioBroker.synology)
[Downloads](https://www.npmjs.com/package/iobroker.synology) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.synology/)

- [ ] :heavy_exclamation_mark: [E503] "[iob_npm.done](https://github.com/instalator/ioBroker.synology/blob/master/iob_npm.done)" found in repo! Please add it to .gitignore
- [ ] :heavy_exclamation_mark: [E818] file iob_npm.done found in repository, but not found in .npmignore
- [ ] :heavy_exclamation_mark: [E914] file iob_npm.done found in repository, but not found in .gitignore


*Add comment "RE-CHECK!" to start check anew*

**Comment by instalator** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.synology](https://github.com/instalator/ioBroker.synology)
[Downloads](https://www.npmjs.com/package/iobroker.synology) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.synology/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by instalator** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.synology](https://github.com/instalator/ioBroker.synology)
[Downloads](https://www.npmjs.com/package/iobroker.synology) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.synology/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
