### PR TITLE
Pls add new Adapter for LG ESS Home Inverter

### PR DESCRIPTION
**Pull request by Morluktom**
This is a new pull request. On the old one was no activity over one month

### CODE REVIEW

**Comment by Apollon77** [comment]
Ok, I see it :-))

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lg-ess-home](https://github.com/Morluktom/ioBroker.lg-ess-home)
[Downloads](https://www.npmjs.com/package/iobroker.lg-ess-home) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.lg-ess-home/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "lg-ess-home" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hey, 
some review comments:
* for mass object creation and stteset please "await" the object creation (e.g. https://github.com/Morluktom/ioBroker.lg-ess-home/blob/master/lib/LgEss.js#L235 and more)
* you should also await setState to lower parallel executed stuff - also check with js-controller 3.2 that no warning appear!
* how many writeable fields exist in your adapter? subscribing each single one works ok up to a certain number, if igher subscring to * and handling in adapter has better performance ... (https://github.com/Morluktom/ioBroker.lg-ess-home/blob/master/lib/LgEss.js#L324)
* please also add a safeguard for the case that "unload" was called (and so all timer were stopped) but in fact a request was still running. this would then be processed and a new timer would be set ... without DB and in compact mode ends in an error flood :-)

Thank you for checking my comments ...

**Comment by Morluktom** [comment]
Hi Apollon, 
rework done.
I have only 4 items you can write, so i think a single subscrib should be ok, or?
thanks
Tom

**Comment by Apollon77** [comment]
You should also await all calls to createDataPoint :-)) else the problem is still there.

**Comment by Morluktom** [comment]
sorry did not understand. ;)
done

**Pull request merged**
