### PR TITLE
Add new Adapter tvprogram

### PR DESCRIPTION
**Pull request by oweitman**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tvprogram](https://github.com/oweitman/ioBroker.tvprogram)
[Downloads](https://www.npmjs.com/package/iobroker.tvprogram) 
[NPM](https://nodei.co/npm/iobroker.tvprogram/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/oweitman/iobroker.tvprogram/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/oweitman/ioBroker.tvprogram/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:oweitman/ioBroker.tvprogram.git. Expected: git+https://github.com/oweitman/iobroker.tvprogram.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/oweitman/ioBroker.tvprogram/blob/master/io-package.json) must be equal to "". Now is tvprogram
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/oweitman/iobroker.tvprogram", press the settings button beside the about title and add some topics.
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2021 oweitman <oweitman@gmx.de>" at the end of [README.md](https://github.com/oweitman/ioBroker.tvprogram/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 oweitman <oweitman@gmx.de>" at the start of LICENSE
- [ ] :eyes: [W400] Cannot find "" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by oweitman** [comment]
hups, stimmt, diesmal vergessen vorher alles zu prüfen

**Comment by oweitman** [comment]
RE-CHECK!
1 remaining errors
due to shut down of https://www.travis-ci.org/ now https://travis-ci.com/github/oweitman/ioBroker.tvprogram

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tvprogram](https://github.com/oweitman/ioBroker.tvprogram)
[Downloads](https://www.npmjs.com/package/iobroker.tvprogram) 
[NPM](https://nodei.co/npm/iobroker.tvprogram/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/oweitman/iobroker.tvprogram/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/oweitman/ioBroker.tvprogram/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/oweitman/ioBroker.tvprogram. Expected: git+https://github.com/oweitman/iobroker.tvprogram.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/oweitman/ioBroker.tvprogram/blob/master/io-package.json) must be equal to "". Now is tvprogram
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Please also adjust the links here in the repo commit

**Comment by oweitman** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tvprogram](https://github.com/oweitman/ioBroker.tvprogram)
[Downloads](https://www.npmjs.com/package/iobroker.tvprogram) 
[NPM](https://nodei.co/npm/iobroker.tvprogram/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/oweitman/iobroker.tvprogram/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/oweitman/ioBroker.tvprogram/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/oweitman/ioBroker.tvprogram. Expected: git+https://github.com/oweitman/iobroker.tvprogram.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/oweitman/ioBroker.tvprogram/blob/master/io-package.json) must be equal to "". Now is tvprogram
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "" in latest repository

### [ioBroker.tvprogram](https://github.com/oweitman/ioBroker.tvprogram)
[Downloads](https://www.npmjs.com/package/iobroker.tvprogram) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.tvprogram/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "tvprogram" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by oweitman** [comment]
RE-CHECK!
1 remaining errors
due to shut down of https://www.travis-ci.org/ now https://travis-ci.com/github/oweitman/ioBroker.tvprogram

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.tvprogram](https://github.com/oweitman/ioBroker.tvprogram)
[Downloads](https://www.npmjs.com/package/iobroker.tvprogram) 
[NPM](https://nodei.co/npm/iobroker.tvprogram/)

- [ ] :heavy_exclamation_mark: [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] :heavy_exclamation_mark: [E004] No adapter name found in URL: https://raw.githubusercontent.com/oweitman/iobroker.tvprogram/master
- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/oweitman/ioBroker.tvprogram/blob/master/package.json) must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: https://github.com/oweitman/ioBroker.tvprogram. Expected: git+https://github.com/oweitman/iobroker.tvprogram.git
- [ ] :heavy_exclamation_mark: [E103] common.name in [io-package.json](https://github.com/oweitman/ioBroker.tvprogram/blob/master/io-package.json) must be equal to "". Now is tvprogram
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "" in latest repository

### [ioBroker.tvprogram](https://github.com/oweitman/ioBroker.tvprogram)
[Downloads](https://www.npmjs.com/package/iobroker.tvprogram) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.tvprogram/)

- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :eyes: [W400] Cannot find "tvprogram" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Pull request closed without merging**
