### PR TITLE
Add LinkedDevices to Stable repository

### PR DESCRIPTION
**Pull request by Scrounger**
Pleas add to stable rep, thanks!

### CODE REVIEW

**Comment by Apollon77** [comment]
could you please solve the conflicts!?

**Comment by Scrounger** [comment]
Done

**Comment by Apollon77** [comment]
SOrry, and please add on correct place in alphabetical order as the others ... ;-) Thank you!

**Comment by Scrounger** [comment]
Done

**Comment by Apollon77** [comment]
I fixed it and now I can merge it

**Pull request merged**
