### PR TITLE
opi monitor implemented

### PR DESCRIPTION
**Pull request by PrinzEisenherz1**
opi monitor implemented

### CODE REVIEW

**Comment by Apollon77** [comment]
Looks good. Please remove macos from .travis.yml then testing should be greeen ... mac is not supported by definition in this case :-)
And please add Bluefox to npm as owner (if not already done): https://github.com/ioBroker/ioBroker.repositories#add-owner-to-packet

**Comment by PrinzEisenherz1** [comment]
Hi apollon77,
.travis.yml is updated now and Bluefox is added as owner to npm

Johnny

**Comment by Apollon77** [comment]
Great, Welcome in the Repo :-))

**Comment by PrinzEisenherz1** [comment]
Thank's ;-)

**Pull request merged**
