### PR TITLE
Update sources-dist-stable.json

### PR DESCRIPTION
**Pull request by SebastianSchultz**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.lgtv](https://github.com/SebastianSchultz/ioBroker.lgtv)
[Downloads](https://www.npmjs.com/package/iobroker.lgtv) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.lgtv/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/SebastianSchultz/ioBroker.lgtv) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by GermanBluefox** [comment]
Please remove node8 from tests. js-controller 3.0 does not support node8

**Comment by SebastianSchultz** [comment]
Done :)

**Pull request merged**
