### PR TITLE
Add ecoflow-mqtt to latest

### PR DESCRIPTION
**Pull request by foxthefox**
Please add my adapter ioBroker.ecoflow-mqtt to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by foxthefox** [comment]
"RE-CHECK!"

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
@foxthefox 
Please fix 
❗ [E162] js-controller 4.0.24 listed as dependency but 4.0.24 is required as minimum, 5.0.19 is recommended. Please update dependency at [io-package.json](https://github.com/foxthefox/ioBroker.ecoflow-mqtt/blob/master/io-package.json).

A new release is not required, fixing at Repo is sufficient as repobuild will pick it up there.

**Comment by foxthefox** [comment]
> @foxthefox Please fix ❗ [E162] js-controller 4.0.24 listed as dependency but 4.0.24 is required as minimum, 5.0.19 is recommended. Please update dependency at [io-package.json](https://github.com/foxthefox/ioBroker.ecoflow-mqtt/blob/master/io-package.json).
> 
> A new release is not required, fixing at Repo is sufficient as repobuild will pick it up there.
> 
> reminder 

yesterday minimum was 4.0.24 🤓

**Comment by mcm1957** [comment]
4.0.24 IS still minimum. See text in Detail.

Theres an error at checker which falls if 4.0.24 is identical to 4.0.24. Sorry and please ignore for now.

**Comment by mcm1957** [comment]
Thnaks for merging test PR. It happenend faster than I could note it here :-)

**Comment by mcm1957** [comment]
Sorry - this PR was merged too fast. The review for latest is still missing.
Processing will be done with follow up #3929.

**Pull request merged**
