### PR TITLE
added adapter iOBroker.chargemaster

### PR DESCRIPTION
**Pull request by hombach**
added new adapter chargemaster for multi wallbox management to charge vehicles with surplus solar energy - development version

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.chargemaster](https://github.com/hombach/ioBroker.chargemaster)
[Downloads](https://www.npmjs.com/package/iobroker.chargemaster) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.chargemaster/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "chargemaster" in latest repository

### [ioBroker.wiobrowser](https://github.com/Bettman66/ioBroker.wiobrowser)
[Downloads](https://www.npmjs.com/package/iobroker.wiobrowser) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.wiobrowser/)

- [ ] :heavy_exclamation_mark: [E130] Too many news found in [io-package.json](https://github.com/Bettman66/ioBroker.wiobrowser/blob/master/io-package.json). Mast be less than 21. Please remove old news.

### [ioBroker.kostal-piko-ba](https://github.com/hombach/ioBroker.kostal-piko-ba)
[Downloads](https://www.npmjs.com/package/iobroker.kostal-piko-ba) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.kostal-piko-ba/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Comment by hombach** [comment]
I don't understand why wiobrowser is auto checked in this pull request. This is not my scope - I can't fix this....

**Comment by Apollon77** [comment]
Ignore that ... all fine

**Comment by hombach** [comment]
_You do not execute the package and adapter tests, please add them to your github actions._
Sorry, don't what you want me to do - github actions and appveyor are executed

_Please remove https://github.com/hombach/ioBroker.chargemaster/blob/master/io-package.json#L104 because you do not have any admin tab_
Removed

_Why you lead the state object in onStateCHsnge ... the current object is actually handed over? Additionally: Only state changes with ack=false should be considered user driven "commands" ... you currently update all cases_
I don't care if ack=false or if it is user driven or elsewhere written

_https://github.com/hombach/ioBroker.chargemaster/blob/master/main.js#L201 ... yes MUST be await, else can never work!_
Removed my own comment, cause it works fine without await an di get errors with await. BatSoC isn't needed synchronous, there are no fast changes nor fast reactions on it.

**Comment by Apollon77** [comment]
1.) Your github actions are not executing the integration tests ... https://github.com/hombach/ioBroker.chargemaster/blob/master/package.json#L53 please add them to one of the actions (and honestly Appveyor is not that relevant, you can test macos, linux and windows with github in the meantime

2.) Caring about "ack flag": The standard meaning of "ack" flag is that "ack=false" are "commands to be executed by the adapter" ad "ack=true" means "stable values set by the adapter and should NOT control anything. If your logic behaves different then this might confuse users and should at least be documented in readme for the users to understand(and honestly als I would be interested whats different in your case here).

3.) honestly ... I have no idea how it works, but fact is that an async method alw<ys return a Promise, and if it is not awaited then the Promise is returned. Honestly - no idea what is the result of a "Number(<promise object>)" construct, i would assume NaN or something like this, so it will most likely not break code, but the logic should not behave as it should ... 
@AlCalzone or do I have ay "Tomaten auf den Augen"?

**Comment by AlCalzone** [comment]
Agreed. Calling an async function requires an await unless you have to work with the raw Promise.

**Comment by hombach** [comment]
Sorry I tried, but don't get this testings running. For my own purposes it's just lost time - which I unfortunately can't spend. 
I've been asked to get the adapter to latest repo by ldittmar81. Perhaps it would be nice for other, too. Especially when it will be finished. 
But sorry - if you can't get me more specific help, I have to cancel this PR.

**Comment by Apollon77** [comment]
@hombach For testing: which error you get? We can help

**Comment by hombach** [comment]
tried to copy test-and-release.yml from  iobroker.testing to my adapter... looks like all used scripts are different to the adapter template I used. So this would need a _total rework_. I don't know about all this connections inside the code, so this is a "Schnitzeljagd" from my point view.

**Comment by Apollon77** [comment]
In fcat you have anything in there already or? 

in fact you need to execute "npm run test:integration" in testing ... this should it be ... test:package yu already execute, or?

**Comment by hombach** [comment]
2022-02-14 22:33:47.323  - error: chargemaster.0 (1944) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-14 22:33:47.323  - error: chargemaster.0 (1944) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.324  - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
    at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
    at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
    at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:297:34)
    at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
    at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.324  - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
2022-02-14 22:33:47.325  - error: chargemaster.0 (1944) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-14 22:33:47.325  - error: chargemaster.0 (1944) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.325  - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
    at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
    at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
    at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:298:34)
    at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
    at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.326  - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
2022-02-14 22:33:47.328  - error: chargemaster.0 (1944) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-14 22:33:47.328  - error: chargemaster.0 (1944) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.328  - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
    at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
    at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
    at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:300:34)
    at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
    at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.328  - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
2022-02-14 22:33:47.329  - error: chargemaster.0 (1944) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-14 22:33:47.329  - error: chargemaster.0 (1944) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.329  - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
    at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
    at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
    at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:301:34)
    at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
    at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.329  - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
2022-02-14 22:33:47.329  - error: chargemaster.0 (1944) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-14 22:33:47.329  - error: chargemaster.0 (1944) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.330  - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
    at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
    at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
    at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:303:34)
    at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
    at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.330  - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
2022-02-14 22:33:47.330  - error: chargemaster.0 (1944) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-14 22:33:47.330  - error: chargemaster.0 (1944) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.330  - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
    at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
    at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
    at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:304:34)
    at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
    at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.331  - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
2022-02-14 22:33:47.331  - error: chargemaster.0 (1944) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-14 22:33:47.331  - error: chargemaster.0 (1944) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.331  - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
    at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
    at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
    at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:300:34)
    at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
    at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.331  - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
2022-02-14 22:33:47.332  - error: chargemaster.0 (1944) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-14 22:33:47.332  - error: chargemaster.0 (1944) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.332  - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
    at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
    at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
    at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:301:34)
    at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
    at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.332  - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
2022-02-14 22:33:47.332  - error: chargemaster.0 (1944) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-14 22:33:47.332  - error: chargemaster.0 (1944) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.333  - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
    at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
    at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
    at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:303:34)
    at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
    at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.333  - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
2022-02-14 22:33:47.333  - error: chargemaster.0 (1944) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-14 22:33:47.333  - error: chargemaster.0 (1944) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.333  - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
    at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
    at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
    at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:304:34)
    at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
    at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.334  - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
2022-02-14 22:33:47.334  - error: chargemaster.0 (1944) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-14 22:33:47.334  - error: chargemaster.0 (1944) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.334  - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
    at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
    at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
    at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:303:34)
    at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
    at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.334  - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
2022-02-14 22:33:47.335  - error: chargemaster.0 (1944) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-14 22:33:47.335  - error: chargemaster.0 (1944) unhandled promise rejection: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.335  - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
    at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
    at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
    at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:304:34)
    at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
    at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.335  - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
2022-02-14 22:33:47.336  - info: chargemaster.0 (1944) Adaptor ChargeMaster cleaned up everything...
2022-02-14 22:33:47.336  - info: chargemaster.0 (1944) terminating
2022-02-14 22:33:47.336  - debug: chargemaster.0 (1944) Plugin sentry destroyed
2022-02-14 22:33:47.337  - warn: chargemaster.0 (1944) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-02-14 22:33:47.337  - error: chargemaster.0 (1944) [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.337  - error: chargemaster.0 (1944) [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.338  - error: chargemaster.0 (1944) [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.338  - debug: chargemaster.0 (1944) Got charge power of wallbox 0: null W; null A
2022-02-14 22:33:47.338  - error: chargemaster.0 (1944) [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.339  - debug: chargemaster.0 (1944) Got charge power of wallbox 0: null W; null A
2022-02-14 22:33:47.339  - error: chargemaster.0 (1944) [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.339  - error: chargemaster.0 (1944) [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.339  - error: chargemaster.0 (1944) [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.339  - debug: chargemaster.0 (1944) Got charge power of wallbox 1: null W; null A
2022-02-14 22:33:47.339  - error: chargemaster.0 (1944) [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.340  - debug: chargemaster.0 (1944) Got charge power of wallbox 1: null W; null A
2022-02-14 22:33:47.340  - error: chargemaster.0 (1944) [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.340  - error: chargemaster.0 (1944) [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.340  - error: chargemaster.0 (1944) [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.340  - debug: chargemaster.0 (1944) Got charge power of wallbox 2: null W; null A
2022-02-14 22:33:47.341  - error: chargemaster.0 (1944) [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.
2022-02-14 22:33:47.341  - debug: chargemaster.0 (1944) Got charge power of wallbox 2: null W; null A
Server memory publish chargemaster.0.Power.Charge {"val":0,"ack":true,"ts":1644878027342,"q":0,"from":"system.adapter.chargemaster.0","user":"system.user.admin","lc":1644878025772}
Server Redis Publish State chargemaster.0.Power.Charge={"val":0,"ack":true,"ts":1644878027342,"q":0,"from":"system.adapter.chargemaster.0","user":"system.user.admin","lc":1644878025772}
 States system redis pmessage */chargemaster.0.Power.Charge:{"val":0,"ack":true,"ts":1644878027342,"q":0,"from":"system.adapter.chargemaster.0","user":"system.user.admin","lc":1644878025772}
Server memory publish chargemaster.0.Power.Charge {"val":0,"ack":true,"ts":1644878027343,"q":0,"from":"system.adapter.chargemaster.0","user":"system.user.admin","lc":1644878025772}
Server Redis Publish State chargemaster.0.Power.Charge={"val":0,"ack":true,"ts":1644878027343,"q":0,"from":"system.adapter.chargemaster.0","user":"system.user.admin","lc":1644878025772}
 States system redis pmessage */chargemaster.0.Power.Charge:{"val":0,"ack":true,"ts":1644878027343,"q":0,"from":"system.adapter.chargemaster.0","user":"system.user.admin","lc":1644878025772}
chargemaster.0(1944) Redis QUIT received, close connection
Server States 127.0.0.1:47456 close Redis connection
chargemaster.0(1944) Redis QUIT received, close connection
Server States 127.0.0.1:47458 close Redis connection
chargemaster.0(1944) Redis QUIT received, close connection
Server States 127.0.0.1:47460 close Redis connection
chargemaster.0(1944) Redis QUIT received, close connection
Server Objects 127.0.0.1:59478 close Redis connection
chargemaster.0(1944) Redis QUIT received, close connection
Server Objects 127.0.0.1:59482 close Redis connection
chargemaster.0(1944) Redis QUIT received, close connection
Server Objects 127.0.0.1:59480 close Redis connection
    1) The adapter starts
Server Redis QUIT received, close connection
Server Objects 127.0.0.1:59468 close Redis connection
Server Redis QUIT received, close connection
Server Objects 127.0.0.1:59470 close Redis connection
Server Redis QUIT received, close connection
Server Objects 127.0.0.1:59466 close Redis connection
Server Redis QUIT received, close connection
Server States 127.0.0.1:47446 close Redis connection
Server Redis QUIT received, close connection
Server States 127.0.0.1:47448 close Redis connection
Server Redis QUIT received, close connection
Server States 127.0.0.1:47[444](https://github.com/hombach/ioBroker.chargemaster/runs/5191899217?check_suite_focus=true#step:6:444) close Redis connection


  0 passing (29s)
  1 failing

  1) Test the adapter (in a live environment)
       The adapter starts:
     Error: The adapter startup was interrupted unexpectedly with code 6
      at TestHarness.<anonymous> (node_modules/@iobroker/testing/build/tests/integration/index.js:119:32)
      at ChildProcess.onClose (node_modules/@iobroker/testing/build/tests/integration/lib/harness.js:144:18)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iobroker.chargemaster@0.3.2 test:integration: `mocha test/integration --exit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iobroker.chargemaster@0.3.2 test:integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-02-14T22_33_47_874Z-debug.log
Error: Process completed with exit code 1.

**Comment by hombach** [comment]
That's not funny - because the adapter is running in **real** world.
I guess there would be the need for a working test environment for this adapter.

**Comment by Apollon77** [comment]
this looks like not integrated error handling. It seems that the testing run have all config empty and your code is doing a setForeignState on an empty ID in this case ... But honestly: This might also happen for any user that initially start your adapter, or?
So maybe you want to add checks before you do such actions?

```
2022-02-14 22:33:47.324 - error: chargemaster.0 (1944) Error: The id is empty! Please provide a valid id.
at Utils.validateId (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19)
at chargemaster.setForeignState (/tmp/test-iobroker.chargemaster/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6023:23)
at chargemaster.Charge_Config (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:297:34)
at chargemaster.StateMachine (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:218:14)
at chargemaster.onReady (/tmp/test-iobroker.chargemaster/node_modules/iobroker.chargemaster/main.js:98:14)
2022-02-14 22:33:47.324 - error: chargemaster.0 (1944) The id is empty! Please provide a valid id.
```

same originated by your line number 298, 300, 301, 303 ... check the output above ... So this might not be a testing error but actually missing error handling in your code. You should not execute a setForeignState if the ID is empty

**Comment by Apollon77** [comment]
PS: I assume "it is running in real workd when properly configured"? ... try a clean fresh installation without any configuration ... I wwould assume a first time user is exactly have this issue like the tests

**Comment by hombach** [comment]
good idea

**Comment by hombach** [comment]
you assumed right - there are missing "some" checks for correct configured data... I had a very bad day yesterday - sorry for beeing somehow pissed ;)
BTW: what is the best way to verify foreign state names? Just verifying that the user put "any" string in there isn't good enough - a hint or idea which adapter could be used to copy from would be great :)

**Comment by Apollon77** [comment]
All fine, happens to all of us :-)

In fact to verify that an object exists you can simply read the object. "getObjectAsync(id)" if you get it back then all good, in anerror is thown or "falsy" comes back then the object do not exist.

Additionally you have the state that can also be set or not (nout I do not know if this is also relevant for you)

**Comment by hombach** [comment]
> in fact you need to execute "npm run test:integration" in testing ... this should it be ... 

integration test added and running without errors. Looks like all issues when starting up with non or wrong configured adapter fixed

**Comment by Apollon77** [comment]
Should I do a re-review then? I'm still (code-wise) sure that https://github.com/hombach/ioBroker.chargemaster/blob/master/main.js#L250 needs an await, but you as the dev should know that better

**Comment by hombach** [comment]
Hi Ingo, yes please - let's do the review.
I switched the upcoming statemachine to async, so I can use await like proposed.

**Comment by Apollon77** [comment]
Then my last topic wouldbe to please also add WIndows and macos to the github actions toalso verify that adapter tests work there (this is mainly to ensure that not a used library or such make isses on one of these operation systems. Thank you

**Comment by hombach** [comment]
DONE!

**Comment by hombach** [comment]
Closing, because I need to pull another request

**Comment by Apollon77** [comment]
Ookkk ... then come up again ... was planning to work through te outstanding request soon :-)

**Comment by hombach** [comment]
Hi Ingo, filed a new PR for this one... ;)

**Pull request closed without merging**
