### PR TITLE
Add sun2000 0.3.1 to stable

### PR DESCRIPTION
**Pull request by bolliy**
Please update my adapter ioBroker.sun2000 to version 0.3.1.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by bolliy** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
## Automated adapter checker

### [ioBroker.sun2000](https://github.com/bolliy/ioBroker.sun2000)
[Downloads](https://www.npmjs.com/package/iobroker.sun2000) Number of Installations (latest) Number of Installations (stable) - [Test and Release](https://github.com/bolliy/ioBroker.sun2000/actions/workflows/test-and-release.yml)
[NPM](https://nodei.co/npm/iobroker.sun2000/)

:thumbsup: No errors found


Adapter releases:  https://www.iobroker.dev/adapter/sun2000/releases
Adapter statistic: https://www.iobroker.dev/adapter/sun2000/statistics

**History and usage information for release 0.3.1:**

0.3.1 created 12.2.2024 (1 days old)
10 users (15.63%)

stable release not yet available

**Please verify that this PR really tries to update to release 0.3.1!**



*Add comment "RE-CHECK!" to start check anew*

**Comment by bolliy** [comment]
RE-CHECK!

**Comment by bolliy** [comment]
Thanks Martin :)

**Pull request merged**
