### PR TITLE
Bumb TibberLink stable to 2.3.2

### PR DESCRIPTION
**Pull request by hombach**

### CODE REVIEW

**Comment by hombach** [comment]
I'm just noticed that now node 18 is recommended.... I'll chnage this for the next release... same for tier and license info.... (this was already planned)

**Comment by hombach** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
> I'm just noticed that now node 18 is recommended.... I'll chnage this for the next release... same for tier and license info.... (this was already planned)

Thanks for you cooperation. Ist no problem - stable will be ereleases soon.

BUT - as far as I checked the complete testing should be miograted to current standards. You do not run pacakge tests and integrations tests. Otherwiese node 16 should have failed since app 3 weeks :-).

I'll create a isse with details. But not sure whether its possible today - I'm not at home and have only access via mobile.

**Comment by mcm1957** [comment]
I've adapter testing to meet current standards and provided a PR
https://github.com/hombach/ioBroker.tibberlink/pull/369

Please verify and merge

(I had to run the tests anyway so the PR is only a sideeffect :-) )

**Comment by hombach** [comment]
> BUT - as far as I checked the complete testing should be miograted to current standards. You do not run pacakge tests and integrations tests. Otherwiese node 16 should have failed since app 3 weeks :-).
> 


I did the test in CI,  and they failed.... it was fixed with    "run: npm install --legacy-peer-deps"  instead of "run: npm install --force" .... ;)

so your PR and my changes overlapped timely... looks funny now - I'll fix this. ;)

BTW: I'm heavily impressed by your work and especially the speed you're supporting this great project named ioBroker - All available thumbs up

**Pull request merged**
