### PR TITLE
adapter huum-sauna added

### PR DESCRIPTION
**Pull request by Chris-656**
Adapter for sauna control using HUUM device

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Apollon77** [comment]
@Chris-1965 Please update this PR and sort in your adapter alphabetically :-)

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [package.json](https://github.com/main/package.json)
[Downloads](https://www.npmjs.com/package/package.json) 
[NPM](https://nodei.co/npm/package.json/)

- [ ] :heavy_exclamation_mark: 404: Invalid URL


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Here also additional review comments:

* Please encrypt the stored password. For instructions how to use the auto encrption feature please check the best practices in the readme  of this repo
* please fix the testing https://github.com/Chris-1965/ioBroker.huum-sauna/runs/4878813294?check_suite_focus=true
* Reason is that you need to add all your required npm modules to the package.json in "dependencies" (e.g.https://github.com/Chris-1965/ioBroker.huum-sauna/runs/4878813294?check_suite_focus=true#step:2:394) Additionally to suncalc2 this should also be axios
* Please only react on stae Changes with ack=== false because ack= true are no commands in https://github.com/Chris-1965/ioBroker.huum-sauna/blob/main/main.js#L282
* Maybe it is a good idea to defeine a minimum value for the interval to prevent that someone tries to ask the cloud server every second or such (also because it will lead to bigger issues if a request would take longer then the interval time because then you start to DOS the cloud server. In general "Intervals" are problematic when it comes to external server communications because they ignmore timeouts (and also you did not define any timeout to the axios request). See bet practices!
* Please check all object roles in https://github.com/Chris-1965/ioBroker.huum-sauna/blob/main/io-package.json#L129 and following and get correct values from https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md

Thank you for considering these comments and adjust accordingly

**Comment by Chris-1965** [comment]
> PR

Done

**Comment by Chris-1965** [comment]
I corrected all issues hopefully created a new version 0.1.5 
regards Chris

**Comment by Apollon77** [comment]
Puuhhh ... your PR did move around many thing ... wtf? Can you please recreate it

**Comment by Apollon77** [comment]
Hi small things left,

* for encryption you chose the most complex way ... I think the readme should have pointed you to the auto encrypt feature , or? But ok ... your decision :-))
* Please only react on stae Changes with ack=== false because ack= true are no commands in https://github.com/Chris-1965/ioBroker.huum-sauna/blob/main/main.js#L322 ... or is there any reason to also process ack=true?
* I would simply use value here or such ... https://github.com/Chris-1965/ioBroker.huum-sauna/blob/main/io-package.json#L234 ... media is not really matching, or?
*

**Comment by Apollon77** [comment]
For Encryption ... hm yes I need to update the specs there ... meross is not really best anymore :-)
In fact:
* add the fields that way https://github.com/TA2k/ioBroker.psa/blob/master/io-package.json#L84-L89
* add these deps at least https://github.com/TA2k/ioBroker.psa/blob/master/io-package.json#L73-L82
* remove all custom encrypt/decrypt stuff

I do not understand what you write above for state Change. Normally the adapter sets the "real values" with ack=true. ack=false is used from outside to control values and tell the adapter to control something

**Comment by Chris-1965** [comment]
> For Encryption ... hm yes I need to update the specs there ... meross is not really best anymore :-) In fact:
> 
>     * add the fields that way https://github.com/TA2k/ioBroker.psa/blob/master/io-package.json#L84-L89
> 
>     * add these deps at least https://github.com/TA2k/ioBroker.psa/blob/master/io-package.json#L73-L82
> 
>     * remove all custom encrypt/decrypt stuff
> 
> 
> I do not understand what you write above for state Change. Normally the adapter sets the "real values" with ack=true. ack=false is used from outside to control values and tell the adapter to control something

ok I will change to new encrypt version.

Regarding the state change:
When I switch on sauna I want to switch on the light after sunset automatically. so I use 
``` 
this.setState("switchLight", state.val, true);
```
in the code as usual. When I trigger the light switch from vis or state from objects iobroker that will we done with ack===false.
So it would not be possible to swicth the light in the adapter unless i use
```
this.setState("switchLight", state.val, false);  // line 335
```

**Comment by Apollon77** [comment]
If the adapter kind of controls itself then why not send an ack=false comand to itself ... then you only ned the logic once and same logic is used as from user ... this would be the clean way ...

**Comment by Chris-1965** [comment]
Updated all comments and fixed them
reagrds Chris

**Comment by Chris-1965** [comment]
created new version and tried to fix issues
regards Chris

**Comment by Chris-1965** [comment]
"RE-CHECK!"

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by Chris-1965** [comment]
RE-CHECK!

**Comment by Chris-1965** [comment]
Is there anything for me to do here ?

**Comment by ldittmar81** [comment]
@Chris-1965 no. It's our turn to check the adapter.

**Comment by Apollon77** [comment]
Cool, looks good, welcome to repository!

**Comment by Apollon77** [comment]
BUT, please fix/recreate the PR because you now added the release script to the repo in your PR??? @Chris-1965

**Comment by Apollon77** [comment]
@Chris-1965 better recreate the PR ...

**Comment by Chris-1965** [comment]
> @Chris-1965 better recreate the PR ...

you mean close the PR and create a new one ?

**Comment by Apollon77** [comment]
@Chris-1965 maybe that the best idea ... simply refeence this PR then we have a connection

**Comment by Chris-1965** [comment]
creating new PR

**Pull request closed without merging**
