### PR TITLE
fullybrowser 1.0.3

### PR DESCRIPTION
**Pull request by arteck**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.fullybrowser](https://github.com/arteck/ioBroker.fullybrowser)
[Downloads](https://www.npmjs.com/package/iobroker.fullybrowser) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fullybrowser/)

- [ ] :heavy_exclamation_mark: [E145] No news found for actual version 1.0.3
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/arteck/ioBroker.fullybrowser) are broken. Please fix.


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@arteck news missing?

**Comment by arteck** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.fullybrowser](https://github.com/arteck/ioBroker.fullybrowser)
[Downloads](https://www.npmjs.com/package/iobroker.fullybrowser) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.fullybrowser/)

:thumbsup: No errors found


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
