### PR TITLE
added deConz Adapter

### PR DESCRIPTION
**Pull request by Jey-Cee**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Please add ioBroker organisation to maintainers:
https://github.com/ioBroker/ioBroker.repositories#add-owner-to-packet

**Comment by Jey-Cee** [comment]
Done

**Comment by Apollon77** [comment]
What was the output of the command? Was it "{}" or something different?

**Comment by Jey-Cee** [comment]
Which Commando?

**Comment by Apollon77** [comment]
Commando to add iobroker team to npm

**Comment by Jey-Cee** [comment]
No npm on Smartphone, added bluefox via npmjs.

**Pull request merged**
