### PR TITLE
add Kress mower

### PR DESCRIPTION
**Pull request by MeisterTR**

### CODE REVIEW

**Comment by Apollon77** [comment]
Thank you. Some small comments:

- Please remove "www" and "widget "dirs of not needed
- same for "docs" if nothing in there ... or better add docs there and reference in io-package :-)
- please add common.license to io-package
- please check again all states to have correct roles (e.g. areas.startSequence do not have a role)
- please add bluefox as npm owner

thank you!

**Comment by Apollon77** [comment]
Also added bluefox as npm owner?

**Comment by GermanBluefox** [comment]
Please Check the roles and descriptions.
https://github.com/MeisterTR/ioBroker.kress/blob/master/io-package.json#L80

Type string cannot have a role "value".

 https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md

**Comment by MeisterTR** [comment]
ok i correct states again.

**Pull request merged**
