### PR TITLE
Add google-spreadsheet to latest

### PR DESCRIPTION
**Pull request by ThomasPohl**
Please add google-spreadsheet to latest.
https://github.com/ThomasPohl/ioBroker.google-spreadsheet

The adapter can store data in google spreadhseets.

### CODE REVIEW

**Comment by menkej** [comment]
I've benn using it for some time. Works fine for me currently.

**Comment by mcm1957** [comment]
First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- [ ] adapter requires node 16 or newer

    Please merge PR https://github.com/ThomasPohl/ioBroker.google-spreadsheet/pull/27. As this adapter is using adapter-core 3.x.x it requires node 16 or newer.

- [ ] potenzial excessive logging (suggestion only, not blocking)

    Please consider to make logging ("row added", ...) either optional (so that user can decide whether required or not) or move it to debug level to avoid filling up logs.

- [ ] check and adapt testing
  
  Standard iobroker testing is required but seems to be missing. Please add and setup ./gizthub/workflows/test-and-release.yml
  
- [ ] adapt testing to supported node releases

  As node 14 is end of life and will no longer be supported by js-controller 5.x, consider removing node 14.x tests from matrix id still present.
  Tests for node 16 is mandatory unless you require node 18 and higher (at package.json).
  Tests for node 18 is mandatory as this is the recommended node version and node 16 will be eol and deprected Q3/2023.
  Consider adding node 20 tests unless you already know incompatibilities.
  
  So the recommended testmatrix is [16.x, 18.x, 20.x] or [18.x, 20.x] depending on engines requirments setting at package.json 

  As node 16 is end-of-life now, it's ok to remove node 16 from testing. In this case please require node 18 as minimum node version at pacakge.json.

- [ ] Consider jsonConfig (suggestion, non blocking)

  This adapter has only a simple config UI, only 3 parameters - if I read it correctly. So I would suggest to consider changing UI config to jsonConfig. This would allow for easy encryption of sensitive data like google access data. 
    
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

FYI: I'll pass the review to Qpollon as I do not have sufficient knowlegde to check blockly support. Sorry for additional delay.

@Apollon77 
Adapter lgtm, but
**adapter provides blockly support. Please check whether this part is OK too**

**Comment by ThomasPohl** [comment]
Hi @mcm1957,
thank you for your review. Feedback is always highly welcome. I implemented all your suggested changes, except of "check and adapt testing". I already added test-and-release.yml, but I can be missing something. Please add some more details on what I need to change to solve this issue.
As soon as @Apollon77 finishes the review on the blockly-part I will include the feedback and create a new release.

**Comment by mcm1957** [comment]
> Hi @mcm1957, thank you for your review. Feedback is always highly welcome. I implemented all your suggested changes, except of "check and adapt testing". I already added test-and-release.yml, but I can be missing something. Please add some more details on what I need to change to solve this issue.

Testing looks OK. N o further action required.
I must have missed removal of first testing statement. Sorry.
The second entry related to testing seems to be left as node 20 was added after review (If I checked correctly).

Technical background:
I use a checklist and remove those entries which do not apply to a specific adapter insted of writing text each time again :-). During this procedure I must have missed to remove the foirst testing block. Sorry for confusion and THANKS for the fast adaptions.

**Comment by mcm1957** [comment]
@Apollon77
Adapter lgtm, but
adapter provides blockly support. Please check whether this part is OK too

**Comment by Apollon77** [comment]
I'm no blockly expert ... but I assume users tested it, so ... go

**Comment by mcm1957** [comment]
@ThomasPohl 

This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, ist OK to continue using this topic too.

**Pull request merged**
