### PR TITLE
Update BLE stable version to 0.7.2

### PR DESCRIPTION
**Pull request by AlCalzone**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please also Update Versiondate Field or remove it

**Comment by AlCalzone** [comment]
Done. 

Where is this documented? I double-checked with `npm run update ble` which also does not change nor remove this field.

**Comment by Apollon77** [comment]
Repo readme I think

**Comment by AlCalzone** [comment]
Ok I was blind. The update script should be fixed then.

**Pull request merged**
