### PR TITLE
add onvif adapter

### PR DESCRIPTION
**Pull request by Haba1234**

### CODE REVIEW

**Comment by Apollon77** [comment]
Can you please check the repo-requirements. testing needs to be enabled and green. Else an at least basic english readme would be awesome.

Additional I noticed on first check:
- io-package common.license is missing
- if you do not provide an Admin-v2 config page then please remove admin/index.html
- io-package ative is empty but you set values in Admin. This should be in sync

Thank you for considering

**Comment by Haba1234** [comment]
> io-package common.license is missing
done
> if you do not provide an Admin-v2 config page then please remove admin/index.html
done
> io-package ative is empty but you set values in Admin. This should be in sync
I did not understand what to do

**Comment by Apollon77** [comment]
The native part in io-Package needs to contain all Adapter config keys that are editable in admin and expected to be in adapter.config.* ... Io-Package contains their default values.

**Comment by Apollon77** [comment]
@Haba1234 Do you need anything more?

**Comment by Haba1234** [comment]
time :)
Soon there will be an English translation.
In io-package there are no more objects. They are created dynamically when a camera is detected.

**Comment by Haba1234** [comment]
done!

**Comment by Apollon77** [comment]
>  In io-package there are no more objects. They are created dynamically when a camera is detected.

Aaaah now I see :-))

Please enable adapter testing (travis-ci at least) in your repo ... I can not see it there. Do you need infos about this?

**Comment by Haba1234** [comment]
Yes it would be nice

**Comment by Apollon77** [comment]
In theory everything should be prepared. Go to https://travis-ci.org, sign in with your Github account and add/enable your project and do a commit in your project OR use the travis-ci options menu "trigger manual build" (or something like this). Then a build should be started. Then you see the results

**Comment by Haba1234** [comment]
done

**Comment by Apollon77** [comment]
looks great ... travis-ci is a great method to check if a change broke it somehow ... so check it before releasing to npm and add more custom adapter specific tests when you like :-)

**Pull request merged**
