### PR TITLE
E3dc rscp@1.1.2

### PR DESCRIPTION
**Pull request by git-kick**

### CODE REVIEW

**Comment by git-kick** [comment]
Sorry for the duplicate, I have fixed it.

Concerning tools: I read [Add a new adapter to the stable repository](https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-stable-repository) and it says

> 1. Fork this repo and clone your fork
> 2. Run npm i
> 3. Run npm run addToStable -- --name <adapter-name> --version <stable-version>
> (replace <adapter-name> with your adapter's name and <stable-version> with the version that should be added to the stable repo)
> 4. Push a commit with the changes to sources-dist-stable.json
> 5. Create a PR

I tried to do that for new versions, but Step 3 just fays "ERROR: e3dc-rscp is already in stable!" (which is true, of course).
So, if there is some automation for lifting to a new version, I'm happy to know (and use from now).

**Comment by mcm1957** [comment]
The most easy way to update the stable version is (or should be):
- go to www.iobroker.dev (and log in using your github account)
- select your adapter from "My Adapters" or if not listed there add it to "Watched Adapters" and select it there
- Klick on the tile Releases / manage
image
- select release and click on "set to stable"
image

That should do the magic.

As an alternative I would suggest to edit the stbale.json file directly at github website This would do the magic of forking an creating a dedicated barnch for you and ensures that no other changes ar enclosed into the PR. But in this case ist up to you to make noy typos invalidating the json file. So this is not the first choice.

**Comment by git-kick** [comment]
Many thanks, I will do so next time.

**Comment by mcm1957** [comment]
@git-kick 
As you created a new PR for the fix , this PR seems to be obsolete. So please close this one (simply klick on close)

**Comment by git-kick** [comment]
Sorry, I'm not so fluent in github & Co....

**Pull request closed without merging**
