### PR TITLE
added puppeteer to latest repo

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alexa2](https://github.com/Apollon77/ioBroker.alexa2)
[Downloads](https://www.npmjs.com/package/iobroker.alexa2) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alexa2/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2018-2022 Apollon77 <ingo@fischer-ka.de>" at the end of [README.md](https://github.com/Apollon77/ioBroker.alexa2/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2018-2022 Apollon77 <ingo@fischer-ka.de>" at the start of LICENSE

### [ioBroker.puppeteer](https://github.com/foxriver76/ioBroker.puppeteer)
[Downloads](https://www.npmjs.com/package/iobroker.puppeteer) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.puppeteer/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:foxriver76/ioBroker.puppeteer.git. Expected: git+https://github.com/foxriver76/ioBroker.puppeteer.git
- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin3 support
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/foxriver76/ioBroker.puppeteer", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W400] Cannot find "puppeteer" in latest repository

### [ioBroker.webuntis](https://github.com/Newan/ioBroker.webuntis)
[Downloads](https://www.npmjs.com/package/iobroker.webuntis) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.webuntis/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.webuntis)!. Please execute in adapter directory: `npm owner add bluefox iobroker.webuntis`


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.alexa2](https://github.com/Apollon77/ioBroker.alexa2)
[Downloads](https://www.npmjs.com/package/iobroker.alexa2) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.alexa2/)

- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2018-2022 Apollon77 <ingo@fischer-ka.de>" at the end of [README.md](https://github.com/Apollon77/ioBroker.alexa2/blob/master/README.md)
- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2018-2022 Apollon77 <ingo@fischer-ka.de>" at the start of LICENSE

### [ioBroker.puppeteer](https://github.com/foxriver76/ioBroker.puppeteer)
[Downloads](https://www.npmjs.com/package/iobroker.puppeteer) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.puppeteer/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com:foxriver76/ioBroker.puppeteer.git. Expected: git+https://github.com/foxriver76/ioBroker.puppeteer.git
- [ ] :heavy_exclamation_mark: [E114] No adapter are allowed in the repo without admin3 support
- [ ] :eyes: [W400] Cannot find "puppeteer" in latest repository

### [ioBroker.webuntis](https://github.com/Newan/ioBroker.webuntis)
[Downloads](https://www.npmjs.com/package/iobroker.webuntis) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.webuntis/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.webuntis)!. Please execute in adapter directory: `npm owner add bluefox iobroker.webuntis`


*Add comment "RE-CHECK!" to start check anew*

**Comment by foxriver76** [comment]
Regarding E114 the adapter has no admin UI.

**Comment by Apollon77** [comment]
Hi,

as discussed in Telegram:
* please prevent file paths that result in in node_modules or iobroker-data/files
* If you like also offer binary states and "adapter.writeFile" in 0_userdata.0 as potential targets :-) (but thats more feature ideas)
* maybe move the subscribe a line more down to prevent calls before the browser got initialized

Please poke when done.

**Comment by foxriver76** [comment]
fixed

**Pull request merged**
