### PR TITLE
Added contact & calendar to latest

### PR DESCRIPTION
**Pull request by WLAN-Kabel**

### CODE REVIEW

**Comment by WLAN-Kabel** [comment]
https://github.com/WLAN-Kabel/ioBroker.contact/commit/2bd98e1dea246ed06ea1056565ddcd6b7dddcc4b

https://github.com/WLAN-Kabel/ioBroker.contact/commit/98af63ecaf1b368fdddc5f4fd44f3ee3e375d2cd

**Comment by Apollon77** [comment]
Hi,
here some review comments:

Calendar:
* Needs fix: Please activate and add travis testing too (GitHub actions are cool, but there is currently no way to see status for multiple adapters at once)
* Note: If you do not need object/state changes please do not implement them (performance)
* Note: As I know using Buffer as in https://github.com/WLAN-Kabel/ioBroker.calendar/blob/master/main.js#L325 is deprecated ... use Buffer.from() instead to prevent deprecation warnings
* Note: I think is is best practice to subscribe to the error event on the http server (https://github.com/WLAN-Kabel/ioBroker.calendar/blob/master/main.js#L855) ... because if you do not do that any error will trow an exception crashing the adapter
* Note: For a simple interval is it not easier to just use setTimeout or setInterval? Having the schedule library in it feels overhead ... and in general (my personal opinion) intervals are dangerous when doing external communication because the interval fires without knowing if the process before was finished. When network problems happen or you have timeouts or such it can so happen that requests pile up and end up in strange behaviours and "DDOS" style problems ...

Contact:
* Needs fix: [E815] file tsconfig.json found in repository, but not found in .npmignore
* Needs fix: The used roles from https://github.com/WLAN-Kabel/ioBroker.contact/blob/master/main.js#L27-L36 and other places are officially not defined. Please only use defined roles or open an issue to discuss adding roles
* Needs fix: Please activate and add travis testing too (GitHub actions are cool, but there is currently no way to see status for multiple adapters at once)
* Note: You use a class style adapter but then still global vars? https://github.com/WLAN-Kabel/ioBroker.contact/blob/master/main.js#L39-L42 Should be unneeded if you move tohgem to class variables
* Note: if you do not use object changes please do not use on-objectchange
* Note: For a simple interval is it not easier to just use setTimeout or setInterval? Having the schedule library in it feels overhead ... and in general (my personal opinion) intervals are dangerous when doing external communication because the interval fires without knowing if the process before was finished. When network problems happen or you have timeouts or such it can so happen that requests pile up and end up in strange behaviours and "DDOS" style problems ...
* Note: When having multiple accounts they are all requested at the same time ... good idea? Or better sequencially process them?
* Note: I think is is best practice to subscribe to the error event on the http server ... because if you do not do that any error will trow an exception crashing the adapter

**Comment by WLAN-Kabel** [comment]
Calendar:
* Travis is already active (https://travis-ci.org/WLAN-Kabel/ioBroker.calendar):
grafik

Contact:
* Travis is already active (https://travis-ci.org/WLAN-Kabel/ioBroker.contact)
* Roles fixed: https://github.com/WLAN-Kabel/ioBroker.contact/commit/babb78ea5ffa82dcb90fc9bb25171263dd49086c
* tsconfig.json is added: https://github.com/WLAN-Kabel/ioBroker.contact/commit/e205c649fd40b2b56b15c7eb70092c36c137d9dd
* Removed onObjectChange: https://github.com/WLAN-Kabel/ioBroker.contact/commit/12fbe9006d4ff2e8da6419e8d6d7f574f7d7f86d

**Comment by Apollon77** [comment]
Please make sure that at least the "integration" tests are executed on travis and github. currently only npm install and package tests run ...

**Comment by WLAN-Kabel** [comment]
Added integrations tests to tarvis and github.

https://github.com/WLAN-Kabel/ioBroker.contact/commit/869e06430b94e8c50cad34d207b21dcf950ae232

https://github.com/WLAN-Kabel/ioBroker.calendar/commit/1b7d118455bac6794680e8d1d7abe978e844e87d

**Comment by foxriver76** [comment]
https://nodejs.org/fr/docs/guides/buffer-constructor-deprecation/

https://github.com/WLAN-Kabel/ioBroker.calendar/blob/master/main.js#L87
https://github.com/WLAN-Kabel/ioBroker.calendar/blob/master/main.js#L336
https://github.com/WLAN-Kabel/ioBroker.calendar/blob/master/main.js#L357
https://github.com/WLAN-Kabel/ioBroker.calendar/blob/master/main.js#L747

Nothing done here:
https://github.com/WLAN-Kabel/ioBroker.calendar/blob/master/main.js#L171

Overhead -> subscribing to all state changes but doing nothing on them:
https://github.com/WLAN-Kabel/ioBroker.calendar/blob/ca6f4cd34765ceddc9973fcf5f7f8fb50846357e/main.js#L139
https://github.com/WLAN-Kabel/ioBroker.calendar/blob/ca6f4cd34765ceddc9973fcf5f7f8fb50846357e/main.js#L186

**Comment by Apollon77** [comment]
@WLAN-Kabel ... DO you have an update for us?

**Comment by WLAN-Kabel** [comment]
I've updated to version 1.1.1

https://github.com/WLAN-Kabel/ioBroker.calendar/commit/ebd0a2662c34e13f4ef5cf79e53b062a0540d365

**Comment by GermanBluefox** [comment]
## Automated adapter checker
### ioBroker.contact
No errors found
### ioBroker.velux
No errors found

**Comment by GermanBluefox** [comment]
## Automated adapter checker
### ioBroker.contact
No errors found
### ioBroker.velux
No errors found
### ioBroker.calendar
No errors found

**Pull request merged**
