### PR TITLE
Add noolitef adapter to repository

### PR DESCRIPTION
**Pull request by paveltsytovich**
Please add beta version of noolitef adapter

Thanks

### CODE REVIEW

**Comment by Apollon77** [comment]
Hi,

here re some review comments:
* Needs fix: The adapter checker shows two errors:
    * [E301] Tests on Travis-ci.org are broken. Please fix ... I think it is mainly because travis is not activated. Please do so and also add the integration tests at least. only package tests are active at the moment.
    * [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Pavel Tsytovich <pavel.tsytovich@gmail.com>" at the end of README.md
* Needs fix: Please remove custom_m.html if you do not use/need it ALso io-package 		"supportCustoms": true should be removed or set to false!
* Note: Please only use setObject (https://github.com/paveltsytovich/ioBroker.noolitef/blob/master/main.js#L198) when you are sure the object is not yet existing! Else you overwrite custom data in js-controller < 2.2
* Note: All in all you shpuld not use the get/setForeign* methods when you work on your adapter namespace. It is easier and more secure to stay with the "Normal" objects that make ure you do not break out of your namespace by code error or such
* Note: Formally the serialport is closed asynchronously from what I know, so te callback shpuld be called in the close-callback ;-) but should work and not break compact mode too much
* Note: for serial adapters it is kind of best practice to get the list of ports from server side (via message) to have the user select in admin ... mybe yu want to add this? A new version f this is e.g. in my smartmeter adapter ...
* needs fixing: You need to make sure that you cann clear all timeouts in on-unload too (e.g. https://github.com/paveltsytovich/ioBroker.noolitef/blob/master/lib/outputDevices.js) because else compact mode will break.

Please also read over https://github.com/ioBroker/ioBroker.repositories/blob/master/README.md#development-and-coding-best-practices ...

**Comment by paveltsytovich** [comment]
> Note: for serial adapters it is kind of best practice to get the list of ports from server side (via message) to have the user select in admin ... mybe yu want to add this? A new version f this is e.g. in my smartmeter adapter ...

Can I use your code for get serial ports list in my adapter?

**Comment by Apollon77** [comment]
> Can I use your code for get serial ports list in my adapter?

Sure ... grab it ... you might need to adjust here and there based on your needs. I will try to add this style code to all "serialport" adapters over time and are happy if other devs take it over.
The mega "pro" in my approach is that not "/dev/ttyUSB0" is stored but ideally the "/dev/serial/by-id/..." path which is stying the same also when the ttyUSBx order changes which can happen on linux boot when you have multiple devices on the same host.

**Comment by Apollon77** [comment]
Please update here when the version is ready for the repo

**Comment by GermanBluefox** [comment]
Any nes here?

**Comment by paveltsytovich** [comment]
Yes. I fixed most of these errors. Plus I did the correct handling of the serial port opening error. It remains to add the code to get a list of available ports from the server. I plan to do this next weekend. There is no time to work on the project during the work week

**Comment by GermanBluefox** [comment]
## Automated adapter checker
### ioBroker.noolitef
No errors found
### ioBroker.velux
No errors found

**Comment by Apollon77** [comment]
@paveltsytovich  Do you have a status update

**Comment by paveltsytovich** [comment]
> @paveltsytovich Do you have a status update

Yes. I implemented all topics from your feedback, except get port list, because busy in last month.

**Comment by Apollon77** [comment]
DO you want to release the current version or want to wait?

**Comment by paveltsytovich** [comment]
Yes, you can publish this version, if missing port list non critical for you. This feature planning in next update

**Pull request merged**
