### PR TITLE
added go-eCharger

### PR DESCRIPTION
**Pull request by MK-2001**
Created the go-eCharger Adapter.
It can in this initial Version read all the variables 

and can change the colors and reduce the current for loading

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.go-echarger](https://github.com/MK-2001/ioBroker.go-echarger)
[Downloads](https://www.npmjs.com/package/iobroker.go-echarger) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.go-echarger/)

- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/package.json) must be lowercase and be equal to "iobroker.go-echarger". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E118] Versions in [package.json](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/package.json) and in [io-package.json](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/io-package.json) are different
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E500] [node_modules](https://github.com/MK-2001/ioBroker.go-echarger/tree/master/node_modules) found in repo. Please delete it
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/MK-2001/ioBroker.go-echarger", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/MK-2001/ioBroker.go-echarger" and press `Manage topics`
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 MK-2001 <go-e@itinsi.de>" at the end of [README.md](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/README.md)
- [ ] :eyes: [W400] Cannot find "go-echarger" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by MK-2001** [comment]
There are some errors wich I can't see in my repo. Eg. E020. Name is already given. in NPM it is published and Bluefox has access...
Can you please help me what is wrong?
Some other fixes are now in the new committed Version.

**Comment by MK-2001** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.go-echarger](https://github.com/MK-2001/ioBroker.go-echarger)
[Downloads](https://www.npmjs.com/package/iobroker.go-echarger) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.go-echarger/)

- [ ] :heavy_exclamation_mark: [E020] Name of adapter in [package.json](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/package.json) must be lowercase and be equal to "iobroker.go-echarger". Now is "undefined"
- [ ] :heavy_exclamation_mark: [E200] Not found on npm. Please publish
- [ ] :heavy_exclamation_mark: [E300] Not found on [travis](https://travis-ci.com/). Please setup [travis](https://travis-ci.com/)
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/MK-2001/ioBroker.go-echarger", press the first "Edit" button you will find on the page and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/MK-2001/ioBroker.go-echarger" and press `Manage topics`
- [ ] :heavy_exclamation_mark: [E605] No actual year found in copyright. Please add "Copyright (c) 2020 MK-2001 <go-e@itinsi.de>" at the end of [README.md](https://github.com/MK-2001/ioBroker.go-echarger/blob/master/README.md)
- [ ] :eyes: [W400] Cannot find "go-echarger" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by MK-2001** [comment]
i have to create a new one. Because someone has registered iobroker.go-echarger, too. 
I will rename it into iobroker.go-e

Thanks a lot.

**Pull request closed without merging**
