### PR TITLE
Please update sources-dist-stable.json for milight-smart-light adapter to version 1.0.5

### PR DESCRIPTION
**Pull request by Steiger04**

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.milight-smart-light](https://github.com/Steiger04/ioBroker.milight-smart-light)
[Downloads](https://www.npmjs.com/package/iobroker.milight-smart-light) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.milight-smart-light/)

- [ ] :heavy_exclamation_mark: [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 Steiger04 <steiger04@posteo.de>" at the start of LICENSE
- [ ] :eyes: [W113] Adapter should support compact mode


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@Steiger04 please update copyright year :-)

**Comment by Steiger04** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.milight-smart-light](https://github.com/Steiger04/ioBroker.milight-smart-light)
[Downloads](https://www.npmjs.com/package/iobroker.milight-smart-light) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.milight-smart-light/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode


*Add comment "RE-CHECK!" to start check anew*

**Comment by Steiger04** [comment]
RE-CHECK!

I will implement the compact mode later.

**Pull request closed without merging**
