### PR TITLE
[New Adapter] gigaset -elements

### PR DESCRIPTION
**Pull request by matthsc**
Adapter for Gigaset Elements alarm system.

Adapter Request: https://github.com/ioBroker/AdapterRequests/issues/12

Forum-Thread: https://forum.iobroker.net/topic/51917/neuer-adapter-gigaset-elements

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.gigaset-elements](https://github.com/matthsc/ioBroker.gigaset-elements)
[Downloads](https://www.npmjs.com/package/iobroker.gigaset-elements) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.gigaset-elements/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "gigaset-elements" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Hi @matthsc,  some review feedback:
* https://github.com/matthsc/ioBroker.gigaset-elements/blob/6bae824c06b83fbd40c5a0b4f6e04e41b67f2f21/src/adapter/elements.ts#L116 whats that for a role? :)
* Is the readme examples here right? https://github.com/matthsc/ioBroker.gigaset-elements#ping

Thank you for these fast checks and fixes

**Comment by matthsc** [comment]
> * https://github.com/matthsc/ioBroker.gigaset-elements/blob/6bae824c06b83fbd40c5a0b4f6e04e41b67f2f21/src/adapter/elements.ts#L116 whats that for a role? :)

The role ist from here: https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md#channel-commonrole-optional
But I realized this is for channels only. I switched the role to value.window now.

> * Is the readme examples here right? https://github.com/matthsc/ioBroker.gigaset-elements#ping

Yes, it is. I use it this way from the admin.

Should be published as 0.1.1 _soon_

**Comment by Apollon77** [comment]
Ok, for readme: what is "innoxel.0" ?? Thsi adapter has a dirfferent name or?! ;-)

**Comment by matthsc** [comment]
doh, sorry, thanks for pointing it out 😂

Fixed.

**Pull request merged**
