### PR TITLE
Update stiebel-isg to 1.7.7 and energymanager to 1.4.2

### PR DESCRIPTION
**Pull request by unltdnetworx**
New confirmed stable version for stiebel-isg and energymanager.

### CODE REVIEW

**Comment by mcm1957** [comment]
energy manager 
1.4.2 created 24.7.
14 user (5%)
OK

stiebel-isg
1.7.7 created 24.7.
26 user (5%)
OK

**Comment by mcm1957** [comment]
@unltdnetworx 

Please add releasenots to README:md for energymanager. README contains RN only up to 1.3.4 while realeses 1.3.5, 1.4.1 and 1.4.2 exist and 1.4.2 should be released to stable.

Adding to README.md is sufficient, no ne release is required !

Thanks.

**Please add a comment after adapting README.md **

**Comment by mcm1957** [comment]
@unltdnetworx
How shall we continue?

Please add releasenots to README.md for energymanager. README contains RN only up to 1.3.4 while realeses 1.3.5, 1.4.1 and 1.4.2 exist and 1.4.2 should be released to stable.

Adding to README.md is sufficient, no ne release is required !

Thanks.

**Please add a comment after adapting README.md**

**Comment by unltdnetworx** [comment]
Readme adapted

**Pull request merged**
