### PR TITLE
add homenet

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.homenet](https://github.com/iobroker-community-adapters/ioBroker.homenet)
[Downloads](https://www.npmjs.com/package/iobroker.homenet) 
[NPM](https://nodei.co/npm/iobroker.homenet/)

:thumbsup: No errors found

### [ioBroker.homenet](https://github.com/TA2k/ioBroker.homenet)
[Downloads](https://www.npmjs.com/package/iobroker.homenet) 
[NPM](https://nodei.co/npm/iobroker.homenet/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/TA2k/ioBroker.homenet/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/TA2k/ioBroker.homenet/blob/master/package.json) (0.0.1) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.homenet) (0.0.2)
- [ ] :eyes: [W400] Cannot find "homenet" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.homenet](https://github.com/iobroker-community-adapters/ioBroker.homenet)
[Downloads](https://www.npmjs.com/package/iobroker.homenet) 
[NPM](https://nodei.co/npm/iobroker.homenet/)

:thumbsup: No errors found

### [ioBroker.homenet](https://github.com/TA2k/ioBroker.homenet)
[Downloads](https://www.npmjs.com/package/iobroker.homenet) 
[NPM](https://nodei.co/npm/iobroker.homenet/)

- [ ] :heavy_exclamation_mark: [E606] Current adapter version 0.0.2 not found in [README.md](https://github.com/TA2k/ioBroker.homenet/blob/master/README.md)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "homenet" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.homenet](https://github.com/iobroker-community-adapters/ioBroker.homenet)
[Downloads](https://www.npmjs.com/package/iobroker.homenet) 
[NPM](https://nodei.co/npm/iobroker.homenet/)

:thumbsup: No errors found

### [ioBroker.homenet](https://github.com/TA2k/ioBroker.homenet)
[Downloads](https://www.npmjs.com/package/iobroker.homenet) 
[NPM](https://nodei.co/npm/iobroker.homenet/)

:thumbsup: No errors found
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "homenet" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Pull request merged**
