### PR TITLE
add apg-info 0.0.1 to stable

### PR DESCRIPTION
**Pull request by HGlab01**

### CODE REVIEW

**Comment by mcm1957** [comment]
0.0.1 created 11.09.2023

**Comment by mcm1957** [comment]
Did you create a tester Therad at forum?
If not, please create one wo check for some feedback.

If already done, please provide link. 
ANY discussion/test topic is ok, it need not be at tester forum althgough this is the prefered location.

see https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-stable-repository

**Comment by HGlab01** [comment]
https://forum.iobroker.net/topic/64251/test-adapter-apg-info-v0-0-x-github

**Comment by mcm1957** [comment]
Thanks and OK so far.
At least no problem feedback :-)

**Comment by mcm1957** [comment]
0.0.1  created 11.09.2023
1 user ...

OK

**Pull request merged**
