### PR TITLE
add doorio

### PR DESCRIPTION
**Pull request by Bettman66**
Selfmade Door Intercom for ioBroker

### CODE REVIEW

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.doorio](https://github.com/Bettman66/ioBroker.doorio)
[Downloads](https://www.npmjs.com/package/iobroker.doorio) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.doorio/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.doorio)!. Please execute in adapter directory: `npm owner add bluefox iobroker.doorio`
- [ ] :eyes: [W400] Cannot find "doorio" in latest repository

### [ioBroker.shellaction](https://github.com/Bettman66/ioBroker.shellaction)
[Downloads](https://www.npmjs.com/package/iobroker.shellaction) 
[NPM](https://nodei.co/npm/iobroker.shellaction/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "shellaction" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Bettman66** [comment]
I added Bluefox to NPM and Github some time ago because the command didn't work. The adapter check still brings the error.

**Comment by Bettman66** [comment]
I deleted Bluefox from NPM again and added it with "npm owner add bluefox iobroker.doorio" without any errors, but the checker brings the error anyway.Bluefox is shown on NPM as an Collaborators.

**Comment by Bettman66** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.shellaction](https://github.com/Bettman66/ioBroker.shellaction)
[Downloads](https://www.npmjs.com/package/iobroker.shellaction) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.shellaction/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.shellaction)!. Please execute in adapter directory: `npm owner add bluefox iobroker.shellaction`
- [ ] :eyes: [W400] Cannot find "shellaction" in latest repository

### [ioBroker.doorio](https://github.com/Bettman66/ioBroker.doorio)
[Downloads](https://www.npmjs.com/package/iobroker.doorio) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.doorio/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "doorio" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Ok, seems to be a false positive regarding Npm

**Comment by Bettman66** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.doorio](https://github.com/Bettman66/ioBroker.doorio)
[Downloads](https://www.npmjs.com/package/iobroker.doorio) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.doorio/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "doorio" in latest repository

### [ioBroker.shellaction](https://github.com/Bettman66/ioBroker.shellaction)
[Downloads](https://www.npmjs.com/package/iobroker.shellaction) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.shellaction/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "shellaction" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by Bettman66** [comment]
Ich habe alle Änderungen erledigt, bis auf die Nutzung der Timeouts. Ich weiß jetzt auch nicht, wie ich das anders lösen könnte. Der Adapter funktioniert hier bei mir schon über 1,5 Jahre ohne Probleme.

**Comment by Bettman66** [comment]
I also added clearing the timeouts, I hope in the right place.

**Comment by Apollon77** [comment]
doorio is ok ...

But now also shellaction is in this PR ...
* also here please do not subscribe to objects if not needed
* please do not use setObjectAsync because in older js-controller this can kill custom settings on the object. Please use extendObjectAsync or setObjectNotExistsAsync (https://github.com/Bettman66/ioBroker.shellaction/blob/master/main.js#L135) or is there a reason to use it there?
* without catch here? https://github.com/Bettman66/ioBroker.shellaction/blob/master/main.js#L269
* is it possible to cancel currently running commands? If yes this would be an idea for "Unload" ... else it could happen that the adapter can be "unloaded" whichthe command is runnignand this will lead to setState calls on non existing database, and will most likely crash the compact mode instance

**Comment by Apollon77** [comment]
PS: shellaction also misses the integration testin on travis. Only package testing is executed

**Comment by Bettman66** [comment]
Please only take over the doorio adapter, I will reprogram the shellaction adapter.

**Comment by Apollon77** [comment]
Ok, I removed shellaction from the PR

**Pull request merged**
