### PR TITLE
BSB LAN Adapter

### PR DESCRIPTION
**Pull request by hacki11**

### CODE REVIEW

**Comment by Apollon77** [comment]
Short Review-Result:
* onUnload should clear the timeout
* please test compact mode, especially that stopping really stops everything
* if onObject/state changes are not needed please do not register it

**Comment by Apollon77** [comment]
@hacki11 Did you find time to check my comments?

**Comment by hacki11** [comment]
Not yet, but thanks for your review I will address the issues!

**Comment by hacki11** [comment]
all three issues are fixed in current master 0.0.6

**Comment by hacki11** [comment]
updated from master and resolved conflicts

**Comment by Apollon77** [comment]
welcome in the repo

**Pull request merged**
