### PR TITLE
Robonect adapter

### PR DESCRIPTION
**Pull request by braindead1**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please sort the adapter in alphabetically!!

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.robonect](https://github.com/braindead1/ioBroker.robonect)
[Downloads](https://www.npmjs.com/package/iobroker.robonect) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.robonect/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "robonect" in latest repository
- [ ] :eyes: [W801] .npmignore not found
- [ ] :eyes: [W901] .gitignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by braindead1** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.robonect](https://github.com/braindead1/ioBroker.robonect)
[Downloads](https://www.npmjs.com/package/iobroker.robonect) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.robonect/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "robonect" in latest repository
- [ ] :eyes: [W801] .npmignore not found
- [ ] :eyes: [W901] .gitignore not found


*Add comment "RE-CHECK!" to start check anew*

**Comment by braindead1** [comment]
@Apollon77 and @GermanBluefox Can you please assist with the failed Travis CI build. Unfortunately I don't know what to do to solve it.

**Comment by Apollon77** [comment]
Travis from Repo is ok, we know reason.

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.coronavirus-statistics](https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics)
[Downloads](https://www.npmjs.com/package/iobroker.coronavirus-statistics) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.coronavirus-statistics/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.coronavirus-statistics)!. Please execute in adapter directory: `npm owner add bluefox iobroker.coronavirus-statistics`
- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/iobroker-community-adapters/ioBroker.coronavirus-statistics) are broken. Please fix.

### [ioBroker.opentherm](https://github.com/iobroker-community-adapters/ioBroker.opentherm)
[Downloads](https://www.npmjs.com/package/iobroker.opentherm) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.opentherm/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal

### [ioBroker.robonect](https://github.com/braindead1/ioBroker.robonect)
[Downloads](https://www.npmjs.com/package/iobroker.robonect) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.robonect/)

:thumbsup: No errors found
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W400] Cannot find "robonect" in latest repository
- [ ] :eyes: [W801] .npmignore not found
- [ ] :eyes: [W901] .gitignore not found

### [ioBroker.vis-inventwo](https://github.com/inventwo/ioBroker.vis-inventwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-inventwo) 
[NPM](https://nodei.co/npm/iobroker.vis-inventwo/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/inventwo/ioBroker.vis-inventwo) are broken. Please fix.

### [ioBroker.covid-19](https://github.com/jiobroker-community-adapters/ioBroker.covid-19)
[Downloads](https://www.npmjs.com/package/iobroker.covid-19) 
[NPM](https://nodei.co/npm/iobroker.covid-19/)

- [ ] :heavy_exclamation_mark: 404

### [ioBroker.valloxmv](https://github.com/hacki11/ioBroker.valloxmv)
[Downloads](https://www.npmjs.com/package/iobroker.valloxmv) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.valloxmv/)

- [ ] :heavy_exclamation_mark: [E506] Word "host" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "port" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "interval" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
Ok, relevant for robonect:
👀 [W113] Adapter should support compact mode
👀 [W801] .npmignore not found
👀 [W901] .gitignore not found

**Comment by braindead1** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.coronavirus-statistics](https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics)
[Downloads](https://www.npmjs.com/package/iobroker.coronavirus-statistics) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.coronavirus-statistics/)

:thumbsup: No errors found

### [ioBroker.opentherm](https://github.com/iobroker-community-adapters/ioBroker.opentherm)
[Downloads](https://www.npmjs.com/package/iobroker.opentherm) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.opentherm/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal

### [ioBroker.vis-inventwo](https://github.com/inventwo/ioBroker.vis-inventwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-inventwo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-inventwo/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/inventwo/ioBroker.vis-inventwo) are broken. Please fix.

### [ioBroker.covid-19](https://github.com/jiobroker-community-adapters/ioBroker.covid-19)
[Downloads](https://www.npmjs.com/package/iobroker.covid-19) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.covid-19/)

- [ ] :heavy_exclamation_mark: 404

### [ioBroker.valloxmv](https://github.com/hacki11/ioBroker.valloxmv)
[Downloads](https://www.npmjs.com/package/iobroker.valloxmv) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.valloxmv/)

- [ ] :heavy_exclamation_mark: [E506] Word "host" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "port" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "interval" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations

### [ioBroker.robonect](https://github.com/braindead1/ioBroker.robonect)
[Downloads](https://www.npmjs.com/package/iobroker.robonect) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.robonect/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "robonect" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by braindead1** [comment]
@Apollon77 I fixed all adapter checker warnings. Please assist how to go on.

**Comment by Apollon77** [comment]
I will have a look tonight

**Comment by Apollon77** [comment]
Hi, some review comments:
* (note) external communications with intervals are dangerous because on timeout cases the interval fires new requests in the defined interval and do not consider if the request before was finished. So it could be that connections sum up. Better are Timeouts that are set for the next run once a run is done
* (note) The error handling on respones is very minimal. Normally also "response && response.statusCode === 200" should be checked and  that the response body is not empty.
* (Needs-fix) Please define roles for your objects!

**Comment by braindead1** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.robonect](https://github.com/braindead1/ioBroker.robonect)
[Downloads](https://www.npmjs.com/package/iobroker.robonect) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.robonect/)

:thumbsup: No errors found
- [ ] :eyes: [W400] Cannot find "robonect" in latest repository

### [ioBroker.coronavirus-statistics](https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics)
[Downloads](https://www.npmjs.com/package/iobroker.coronavirus-statistics) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.coronavirus-statistics/)

:thumbsup: No errors found

### [ioBroker.opentherm](https://github.com/iobroker-community-adapters/ioBroker.opentherm)
[Downloads](https://www.npmjs.com/package/iobroker.opentherm) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.opentherm/)

- [ ] :heavy_exclamation_mark: [E140] width and height of logo are not equal

### [ioBroker.vis-inventwo](https://github.com/inventwo/ioBroker.vis-inventwo)
[Downloads](https://www.npmjs.com/package/iobroker.vis-inventwo) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.vis-inventwo/)

- [ ] :heavy_exclamation_mark: [E301] Tests on [Travis-ci.com](https://travis-ci.com/inventwo/ioBroker.vis-inventwo) are broken. Please fix.

### [ioBroker.covid-19](https://github.com/jiobroker-community-adapters/ioBroker.covid-19)
[Downloads](https://www.npmjs.com/package/iobroker.covid-19) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.covid-19/)

- [ ] :heavy_exclamation_mark: 404

### [ioBroker.valloxmv](https://github.com/hacki11/ioBroker.valloxmv)
[Downloads](https://www.npmjs.com/package/iobroker.valloxmv) Number of Installations (latest) Number of Installations (stable)
[NPM](https://nodei.co/npm/iobroker.valloxmv/)

- [ ] :heavy_exclamation_mark: [E506] Word "host" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "port" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
- [ ] :heavy_exclamation_mark: [E506] Word "interval" is not translated to russian in [admin/words.js](https://github.com/hacki11/ioBroker.valloxmv/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations


*Add comment "RE-CHECK!" to start check anew*

**Comment by braindead1** [comment]
@Apollon77 Can you please check my adapter again. Your comments should all be taken care of.

**Comment by Apollon77** [comment]
Thank you!

**Pull request merged**
