### PR TITLE
Added reolink-810a

### PR DESCRIPTION
**Pull request by sebtig**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please adds more informations to the Readme and clean up the "developer notes". In fact: is that adapter really just for that one devcie (as name suppests) Or is it supporting more reolink devices? Would it more make sense to name it more generic?

**Comment by Apollon77** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.reolink-810a](https://github.com/sebtig/ioBroker.reolink-810a)
[Downloads](https://www.npmjs.com/package/iobroker.reolink-810a) 
[NPM](https://nodei.co/npm/iobroker.reolink-810a/)

- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL: git@github.com/sebtig/ioBroker.reolink-810a. Expected: git@github.com:sebtig/ioBroker.reolink-810a.git or https://github.com/sebtig/ioBroker.reolink-810a.git
- [ ] :heavy_exclamation_mark: [E801] No repository about text found. Please go to "https://github.com/sebtig/ioBroker.reolink-810a", press the settings button beside the about title and add the description.
- [ ] :heavy_exclamation_mark: [E802] No topics found in the repository. Please go to "https://github.com/sebtig/ioBroker.reolink-810a", press the settings button beside the about title and add some topics.
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/sebtig/ioBroker.reolink-810a/blob/master/io-package.json)
- [ ] :eyes: [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/sebtig/ioBroker.reolink-810a/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "reolink-810a" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by sebtig** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.reolink-810a](https://github.com/sebtig/ioBroker.reolink-810a)
[Downloads](https://www.npmjs.com/package/iobroker.reolink-810a) 
[NPM](https://nodei.co/npm/iobroker.reolink-810a/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/sebtig/ioBroker.reolink-810a/blob/master/io-package.json)
- [ ] :eyes: [W400] Cannot find "reolink-810a" in latest repository


*Add comment "RE-CHECK!" to start check anew*

**Comment by sebtig** [comment]
Right now, I only have a Reolink-RLC810A for testing. Further improvement and maybe additional models will follow.
Also, the repo-name "Reolink" was already in use ;-)

**Comment by TA2k** [comment]
Duplicate of https://github.com/aendue/ioBroker.reolink ?

**Comment by Apollon77** [comment]
@sebtig And it was no option to enhance the existing adapter [Reolink?](https://github.com/aendue/ioBroker.reolink) or get in contact with that developer? Does the other adapter also work for this device? Code wise there are several "similarities" ...

**Comment by Apollon77** [comment]
@sebtig Sorry but I need to ask again why a separate adapter when the other adapter also supports that device? Without an answer we would decide to decline this adapter request

**Pull request closed without merging**
