### PR TITLE
Add gotify-ws to latest

### PR DESCRIPTION
**Pull request by simatec**
Please add my adapter ioBroker.gotify-ws to latest.

*This pull request was created by https://www.iobroker.dev c0726ff.*

### CODE REVIEW

**Comment by mcm1957** [comment]
Thanks for spending your time and providing a new adapter for ioBroker.

Your adapter will get a manual review as soon as possible. Please stand by - this might last one or two weeks. Feel free to continue your work and create new releases. You do NOT need to close or update this PR in case of new releases.

In the meantime please check any feedback issues logged by automatic adapter checker and try to fix them.

You will find the results of the review and eventually issues / suggestings as a comment to this PR. So please keep this PR watched.

If you have any urgent questions feel free to ask.

reminder 27.06.2024

**Comment by mcm1957** [comment]
@simatec 

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

I would like to give some feedback based on my personal oppinion. @Apollon77 might have additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him if you cannot follow my suggestions or want to discuss some special aspects.


- [ ] consider using adapter.setTimeout / this.setTimeout instead of (standard) setTimeout
  
  The adapter package provides wrapper routines for native setTimeout, setInterval, clearTimeout and clearInterval. Using those routines ensures that timers are cancelled on on load. Additional checks on thomse limits might be performed, too. So consider replacing native setTimeout/clearTimeout by adapter.setTimeout/adapter.clearTimeout or this.setTimeout/this.clearTimeout. The same refers to setInterval/clearInterval.

- [ ] adapt testing to supported node releases

  Tests for node 18 are mandatory. 
  Tests for node 20 are mandatory as this is the recommended node version. 
  Tests for node 22 should be added unless you already know incompatibilities which cannot be fixed immidiatly. In this case please create a issue stating the problem and fix as soon as possible.
  
  So the recommended testmatrix is [18.x, 20.x, 22.x] depending on engines requirments setting at package.json 

  Note: This is a suggestion only and not blocking.
  
Thanks for reading and evaluating this suggestions.
McM1957

**Please add a comment when you have reviewed and fixed the suggestionsor at least commented the suggestions and you think the adapter is ready for a re-review!**

reminder 28.7.2024

**Comment by simatec** [comment]
@mcm1957 
The two points mentioned have been fixed and the adapter can be checked again

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by mcm1957** [comment]
This adapter has been released to latest repository and should be visible within 24h maximum.

Please create a thread at https://forum.iobroker.net/category/91/tester titled like "Test Adapter " to collect some user feedback and provide a link to this topic when requesting addition to stable repository later.

Note: If an other testing topic already exists, it' OK to continue using this topic too.

**Pull request merged**
