### PR TITLE
panasonic-comfort-cloud 3.0.3

### PR DESCRIPTION
**Pull request by marc2016**

### CODE REVIEW

**Comment by marc2016** [comment]
RE-CHECK!

**Comment by marc2016** [comment]
RE-CHECK!

**Comment by marc2016** [comment]
RE-CHECK!

**Comment by marc2016** [comment]
problems are fixed now. Sorry for the delay.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by marc2016** [comment]
Panasonic changed API again and adapter doesn't work with version 3.0.2 anymore.

**Comment by mcm1957** [comment]
Thanks for Info.
Then lets hurry to get 3.0.3 out and running.

P.S: 63% of users still use 3.0.2 ???

**Comment by marc2016** [comment]
I don't  why so many users still use version 3.0.2. 
I think they don't use the beta repo and don't follow the discussions on the GitHub repo of my adapter.

Thank you for your fast reaction! :-)

**Comment by mcm1957** [comment]
No problem. I only wonder why so many user use a non function version withoput reporting problems ... 
Well "Never trust a statistic unless you have manipulated it yourself"
:-) :-) 

P.S: 3.0.3 should be available at stable already - at least after updating local cache ("Nach updates suchen")

**Pull request merged**
