### PR TITLE
add euhome in latest

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by TA2k** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.euhome](https://github.com/TA2k/ioBroker.euhome)
[Downloads](https://www.npmjs.com/package/iobroker.euhome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.euhome/)

- [ ] :heavy_exclamation_mark: [E201] Bluefox was not found in the collaborators on [NPM](https://www.npmjs.com/package/iobroker.euhome)!. Please execute in adapter directory: `npm owner add bluefox iobroker.euhome`
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/TA2k/ioBroker.euhome/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "euhome" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by mcm1957** [comment]
-) io-package actives senty (https://github.com/TA2k/ioBroker.euhome/blob/f94964ce32a8d0ef5e388462990840bafa67cc27/io-package.json#L60) but readme.md does not contain sentry info.

-) As ioBroker is multilingual shouldn't the readme.md be written in english? An additional german version is ok, but german only? -> to be deided by @apollon

**Comment by Apollon77** [comment]
Yes, the main readme needs to be english please

**Comment by TA2k** [comment]
Done

**Comment by mcm1957** [comment]
Thanks for the fast hange.
Please use the suggested sentry info (see: https://github.com/ioBroker/plugin-sentry#how-can-i-get-my-sentry-account-as-a-developer)

```**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0. ```

The goal is to inform the user what sentry is, what data is transferred and how to disable this festure if the user does not want to provide information. "This adapter uses Sentry" would be suffiient for a developer, but a user who did not read anything about sentry does not get the infomation he should get. At least in my opinion.

**Comment by TA2k** [comment]
done

**Comment by mcm1957** [comment]
I would like to give some more (preliminary) feedback based on my personal oppinion. This is NOT an offical review and @Apollon77 might have several additional suggestions or even a different oppinion to one or the other statement. Please feel free to contact him (or wait for a response from him) if you cannot follow my suggestsions or before you spend major effort.

- Readme.md contains multiple languages

Please remove the german version / all non english versions from Readme.md because Readme.md gets automatically translated and this will not work with multiple languages within Readme.md. You can add locatlized Readme pages in (docs/de and docs/en) like https://github.com/iobroker-community-adapters/ioBroker.pvforecast/tree/main/docs and add it to io-package (see https://github.com/iobroker-community-adapters/ioBroker.pvforecast/blob/main/io-package.json#L119-L122)

- github dependabot support seems to be missing
  
  It looks like you did not yet setup dependabot support; at least .github/dependaboit.yml is missing.
  
  Please consider setting up dependabot support (and to ease life the workflow auto-merge.yml). Dependabot will ensure that your adapter uses the most recent versions of external packages and avoids problem due to outdted base libraries. Dependabit provides PRs at you repository to update the dependencies. Depending on you setting, especially on auto-merge.yml configuration no or only minor revisions will be outmatically merged into you main branch. All major revisions msiut (ans should) be reviewed by you. 
  
Thanks for reading and evalutaing this suggestions. 

McM1957

**Comment by TA2k** [comment]
I prefer multiple language in the readme instead of the language description because this is hard to find for the user

I don't like dependabot because it is update devdependencies and spam notification and commits. I prefer to update and test manually

**Comment by mcm1957** [comment]
> I prefer multiple language in the readme instead of the language description because this is hard to find for the user

Well, @Apollon77  must decide whether multiple languages within Readme.md are acceptable. Readme.md is automatically translated for the website iobroker.net section documentation and non english text will not be handled properly. If you add a linkt o the (german) documentaion within the main and english Readme its trivial for the user to find it in my oppinion. Simply add a "German version", "Itiliean Version", "English version" links at the start of you Readme like other Readme's do.

> I don't like dependabot because it is update devdependencies and spam notification and commits. 
I would not call dependabot sending spam notifications and updating devdependencies too, especially related to iobroker tools, is not a bad idea. But whether you use dependabot with a private repository is of course your decision. So feel free to ignore this remark.

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.euhome](https://github.com/TA2k/ioBroker.euhome)
[Downloads](https://www.npmjs.com/package/iobroker.euhome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.euhome/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/TA2k/ioBroker.euhome/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "euhome" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by TA2k** [comment]
I'm not aware that someone is using www.iobroker.net adapter to check adapter. 

Also German readmes are working fine with the auto translation
https://www.iobroker.net/#de/adapters/adapterref/iobroker.viessmannapi/README.md

**Comment by mcm1957** [comment]
RE-CHECK!

**Comment by GermanBluefox** [comment]
## Automated adapter checker

### [ioBroker.euhome](https://github.com/TA2k/ioBroker.euhome)
[Downloads](https://www.npmjs.com/package/iobroker.euhome) Number of Installations (latest) 
[NPM](https://nodei.co/npm/iobroker.euhome/)

:thumbsup: No errors found
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/TA2k/ioBroker.euhome/blob/master/io-package.json)
- [ ] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W400] Cannot find "euhome" in latest repository
- [ ] :eyes: [W515] Why you decided to disable i18n support?


*Add comment "RE-CHECK!" to start check anew*

**Comment by Apollon77** [comment]
@TA2k It is true that Readme's should be englöish only because of the auto translation ... else that can lead to very strange results.
Yes dependabot is 100% optional and up to the developer.

**Comment by mcm1957** [comment]
@TA2k 
If this PR has been closed on error, please open a new one.

**Pull request closed without merging**
