### PR TITLE
Added Adapter emby

### PR DESCRIPTION
**Pull request by thewhobox**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Travis testing?

**Comment by thewhobox** [comment]
Sorry didnt add it to the readme.
Travis is configured. I started a new test and it's passing.

https://travis-ci.org/thewhobox/ioBroker.emby

**Comment by Apollon77** [comment]
I will check everything later or latest tomorrow

**Comment by Apollon77** [comment]
Hey, sorry for the delay!
Please remove the docs directories or provide content there :-) same in io-package.

Please also check the www directory and remove including io-package reference or fill with content.

After that I am happy to merge :-)

**Comment by thewhobox** [comment]
Hey, no Problem :)

I removed the WWW Folder and the references in io-packege.
And also the docs Folder.

**Pull request merged**
