### PR TITLE
release. wled

### PR DESCRIPTION
**Pull request by DutchmanNL**

### CODE REVIEW

**Comment by Apollon77** [comment]
Review Comments:
- Note: Do I see it correctly that you create an object if not existing just to extend it the line below? https://github.com/iobroker-community-adapters/ioBroker.wled/blob/master/main.js#L218 ... When I know correctly extend will also create the objects with all provided data when not existant ... in your case this might work well
- Need-Fix: Tiumeout is not cleared in on-unload https://github.com/iobroker-community-adapters/ioBroker.wled/blob/master/main.js#L447 (evenr tested compactmode) ;-) ... also this one https://github.com/iobroker-community-adapters/ioBroker.wled/blob/master/main.js#L517
- Note: info connection should be declared in io-package ... then you do not need to craete it ... but if you do, also create the info channel please ;-)

**Comment by DutchmanNL** [comment]
> Review Comments:
> 
> * Note: Do I see it correctly that you create an object if not existing just to extend it the line below? https://github.com/iobroker-community-adapters/ioBroker.wled/blob/master/main.js#L218 ... When I know correctly extend will also create the objects with all provided data when not existant ... in your case this might work well

eh.... yea that's just stupid :/ 

https://github.com/iobroker-community-adapters/ioBroker.wled/commit/9fbb2e89f441e2b8a6fd349449f6d318a57abe8d#diff-7a9076d6d94e62c13d641aa71f19ae8eL217-L226

> * Need-Fix: Tiumeout is not cleared in on-unload https://github.com/iobroker-community-adapters/ioBroker.wled/blob/master/main.js#L447 (evenr tested compactmode) ;-) ... also this one https://github.com/iobroker-community-adapters/ioBroker.wled/blob/master/main.js#L517

fixed timer cleared at unload : https://github.com/iobroker-community-adapters/ioBroker.wled/commit/9fbb2e89f441e2b8a6fd349449f6d318a57abe8d#diff-7a9076d6d94e62c13d641aa71f19ae8eR63-R67

> * Note: info connection should be declared in io-package ... then you do not need to craete it ... but if you do, also create the info channel please ;-)

fixed https://github.com/iobroker-community-adapters/ioBroker.wled/commit/9fbb2e89f441e2b8a6fd349449f6d318a57abe8d#diff-7a9076d6d94e62c13d641aa71f19ae8eR43-R53

But remark : we should adjust the template too as this one is not created in a channel here :)

**Comment by Apollon77** [comment]
> But remark : we should adjust the template too as this one is not created in a channel here :)

The creator should create it with the relevant io-package objects including channel

**Comment by Apollon77** [comment]
For timeouts: What about scan_timer ?!

**Comment by DutchmanNL** [comment]
> For timeouts: What about scan_timer ?!

Stupid me :/

Fixed : https://github.com/iobroker-community-adapters/ioBroker.wled/commit/0d3e39ffef98ea2eadf4f326116333a8ed65dbe9#diff-7a9076d6d94e62c13d641aa71f19ae8e

**Pull request merged**
