### PR TITLE
update deconz -> 0.2.5

### PR DESCRIPTION
**Pull request by Jey-Cee**

### CODE REVIEW

**Comment by Apollon77** [comment]
Do you remember the original published date for stable? Would be better to put in that date ;-)

**Comment by BuZZy1337** [comment]
https://github.com/Jey-Cee/ioBroker.repositories/commit/88c0695eec7767a13bf6bb6972658a106cc802d1

Guess it was 02. Jan?! :grin:

**Comment by Jey-Cee** [comment]
Thanks Buzzy.

@Appollon77 i think we discussed this already in the past. 

Readme Quote:
Update of the version in stable
1. Be sure that the version is tested in forum by users or you fix the critical bug with that.
2. Delete the versionTime or update it to the current time

**Comment by BuZZy1337** [comment]
> Thanks Buzzy.
> 
> @Appollon77 i think we discussed this already in the past.

Yes.. Here.. https://github.com/ioBroker/ioBroker.repositories/pull/116
:rofl:

**Comment by Apollon77** [comment]
yea but "versionTime" != "publishedDate" ... or ?!

**Comment by Jey-Cee** [comment]
> yea but "versionTime" != "publishedDate" ... or ?!

OK, you are right. Then Plesse remove point 2 vor wie have to add it to the json. None oft the Adapter has a "versionTime"

**Pull request merged**
